"""
Generador y Validador del Lote 02 de Fase 10 para CarBot.
Genera exactamente 200 registros de alta fidelidad automotriz para las Clases 6 a 10:
- Clase 6: Empaque de culata soplado o danado
- Clase 7: Falla en termostato o motoventilador de radiador
- Clase 8: Fuga en mangueras de refrigerante o radiador picado
- Clase 9: Consumo de aceite por desgaste de anillos o retenes
- Clase 10: Baja presion de aceite o bomba de aceite defectuosa

Estructura: 40 por clase (10 L1, 15 L2, 15 L3) = 200 registros.
"""

import csv
import re
import sys
from pathlib import Path
import pandas as pd

# Importar validaciones canónicas
sys.path.insert(0, str(Path("backend").resolve()))
from src.core.diagnostico.taxonomia_sistemas import FALLA_A_SISTEMA

CLASE_6 = "Empaque de culata soplado o danado"
CLASE_7 = "Falla en termostato o motoventilador de radiador"
CLASE_8 = "Fuga en mangueras de refrigerante o radiador picado"
CLASE_9 = "Consumo de aceite por desgaste de anillos o retenes"
CLASE_10 = "Baja presion de aceite o bomba de aceite defectuosa"

def generar_datos_lote02():
    casos = []
    idx = 1

    def agregar(id_grupo, clase, nivel, texto, tipo_lenguaje, cond, sint_pres, sint_neg, dtc, req_preg, es_cont, cl_cont, obs):
        nonlocal idx
        reg_id = f"F10-L02-{idx:04d}"
        idx += 1
        casos.append({
            "id": reg_id,
            "id_grupo": id_grupo,
            "clase_objetivo": clase,
            "macro_sistema": "MOTOR",
            "nivel_informacion": nivel,
            "texto_usuario": texto.strip(),
            "tipo_lenguaje": tipo_lenguaje,
            "condicion_operacion": cond.strip(),
            "sintomas_presentes": sint_pres.strip(),
            "sintomas_negados": sint_neg.strip(),
            "dtc": dtc.strip(),
            "requiere_pregunta": req_preg.strip(),
            "es_contrastivo": es_cont.strip(),
            "clase_contrastiva": cl_cont.strip(),
            "fuente": "SINTETICO_IA",
            "observaciones": obs.strip()
        })

    # =========================================================================
    # CLASE 6: Empaque de culata soplado o danado (40 casos: 10 L1, 15 L2, 15 L3)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G06-L1-01", CLASE_6, "L1", "Se me está calentando el carro después de andar un rato.", "COTIDIANO", "marcha", "temperatura_alta", "", "", "SI", "NO", "", "L1 ambiguo inicial calentamiento.")
    agregar("G06-L1-02", CLASE_6, "L1", "Hola maestro, el depósito del agua está botando líquido por la tapa.", "WHATSAPP", "motor_caliente", "rebose_deposito", "", "", "SI", "NO", "", "L1 sobrepresión inicial.")
    agregar("G06-L1-03", CLASE_6, "L1", "Sale un humo blanco por el tubo de escape cuando acelero.", "COTIDIANO", "aceleracion", "humo_blanco_escape", "", "", "SI", "NO", "", "L1 vapor/humo blanco de escape.")
    agregar("G06-L1-04", CLASE_6, "L1", "Mi carro consume agua pero no veo ningún charco abajo.", "COTIDIANO", "marcha", "perdida_refrigerante_sin_charco", "", "", "SI", "NO", "", "L1 pérdida interna sin fuga externa.")
    agregar("G06-L1-05", CLASE_6, "L1", "Siento que el motor perdió fuerza y la aguja de temperatura subió a tres cuartos.", "COTIDIANO", "subida", "perdida_potencia|temperatura_alta", "", "", "SI", "NO", "", "L1 pérdida de fuerza y calor.")
    agregar("G06-L1-06", CLASE_6, "L1", "Buenos días, al revisar la varilla del aceite vi que tiene un color medio lechoso.", "WHATSAPP", "reposo", "aceite_emulsion_lechosa", "", "", "SI", "NO", "", "L1 emulsión lechosa en varilla.")
    agregar("G06-L1-07", CLASE_6, "L1", "El motor tiembla feo en mínimo y calienta más rápido de lo normal.", "TALLER", "ralenti", "ralenti_inestable|calentamiento_rapido", "", "", "SI", "NO", "", "L1 temblor y calentamiento rápido.")
    agregar("G06-L1-08", CLASE_6, "L1", "Se me bazio el refrigerante de la nada y escucho como si hirviera adentro.", "ERROR_ORTOGRAFICO", "motor_caliente", "refrigerante_hierve", "", "", "SI", "NO", "", "L1 ebullición interna con error ortográfico.")
    agregar("G06-L1-09", CLASE_6, "L1", "Mi auto burbujea en el depósito plástico cuando acelero.", "COTIDIANO", "aceleracion", "burbujas_deposito_expansion", "", "", "SI", "NO", "", "L1 burbujeo en depósito de expansión.")
    agregar("G06-L1-10", CLASE_6, "L1", "Motor recalienta bajo carga sostenida y genera contrapresión en el circuito de enfriamiento.", "TECNICO", "bajo_carga", "recalentamiento|sobrepresion_refrigeracion", "", "", "SI", "NO", "", "L1 técnico de sobrepresión.")

    # --- L2 (15 casos) ---
    agregar("G06-L2-01", CLASE_6, "L2", "La temperatura sube en carretera abierta y el depósito de expansión escupe agua caliente, pero el radiador está limpio.", "TALLER", "carretera", "temperatura_alta|expulsion_refrigerante", "radiador_obstruido", "", "NO", "SI", CLASE_7, "L2 sobrepresión a velocidad vs termostato.")
    agregar("G06-L2-02", CLASE_6, "L2", "En las mañanas arranca en tres cilindros botando humo blanco espeso y dulce, emparejando recién a los dos minutos.", "COTIDIANO", "arranque_frio", "arranque_irregular|humo_blanco_dulce", "fuga_combustible", "", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L2 filtración nocturna a cilindros vs encendido.")
    agregar("G06-L2-03", CLASE_6, "L2", "El nivel de refrigerante baja a diario sin fugas visibles en mangueras ni radiador, y la tapa de aceite tiene una pasta café con leche.", "COTIDIANO", "motor_caliente", "perdida_refrigerante|emulsion_tapa_aceite", "fuga_mangueras|fuga_radiador", "", "NO", "SI", CLASE_8, "L2 emulsión aceite-agua sin fuga externa vs mangueras.")
    agregar("G06-L2-04", CLASE_6, "L2", "Mangueras de radiador se ponen duras como piedra a los pocos minutos de arrancar antes de que el motor llegue a 80 grados.", "TECNICO", "calentamiento", "mangueras_infladas_presion", "termostato_trabado", "", "NO", "SI", CLASE_7, "L2 mangueras sobrepresurizadas en frío vs termostato.")
    agregar("G06-L2-05", CLASE_6, "L2", "Hola, cada vez que subo cuestas la aguja se va al rojo y bota refrigerante por el desfogue. En plano no calienta.", "WHATSAPP", "subida", "recalentamiento_subida|expulsion_desfogue", "perdida_plano", "", "NO", "SI", CLASE_7, "L2 calentamiento bajo carga extrema vs motoventilador.")
    agregar("G06-L2-06", CLASE_6, "L2", "Siento olor a refrigerante quemado por el escape al acelerar y el motor tiembla al exigirle, sin que se prenda el check.", "COTIDIANO", "aceleracion", "olor_refrigerante_escape|perdida_potencia", "testigo_check_engine", "", "NO", "NO", "", "L2 refrigerante en cámara de combustión.")
    agregar("G06-L2-07", CLASE_6, "L2", "Se pasa la compresión al agua; al acelerar en ralentí salen burbujas constantes en el tacho auxiliar sin tener termostato puesto.", "TALLER", "ralenti", "burbujas_continuas_tacho", "termostato_instalado", "", "NO", "SI", CLASE_7, "L2 burbujeo sin termostato descarta traba de flujo.")
    agregar("G06-L2-08", CLASE_6, "L2", "El motor recalienta al exigirlo y cuando revisé el refrigerante tenía manchas de aceite flotando en la superficie.", "COTIDIANO", "bajo_carga", "recalentamiento|aceite_en_refrigerante", "fuga_externa", "", "NO", "SI", CLASE_8, "L2 contaminación cruzada aceite en refrigerante.")
    agregar("G06-L2-09", CLASE_6, "L2", "El carro se calienta mucho y cuando saco la bujia del cilindro dos sale mojada con agua no con gasolina.", "ERROR_ORTOGRAFICO", "despues_de_recalentar", "bujia_humeda_refrigerante", "bujia_ahogada_gasolina", "", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L2 líquido refrigerante en bujía con error ortográfico.")
    agregar("G06-L2-10", CLASE_6, "L2", "Pérdida progresiva de compresión en cilindros 3 y 4 contiguos, con recalentamiento sostenido y escape con humo blancuzco.", "TECNICO", "marcha", "perdida_compresion_cilindros_adyacentes|humo_blanco", "falla_chispa", "", "NO", "NO", "", "L2 paso de gases entre cilindros adyacentes.")
    agregar("G06-L2-11", CLASE_6, "L2", "Buenas, el carro no tiene fuga en el piso pero el tacho de agua amanece seco y sale humo blanco en el arranque.", "WHATSAPP", "arranque_frio", "consumo_refrigerante_sin_charco|humo_blanco_manana", "charco_piso", "", "NO", "SI", CLASE_8, "L2 consumo interno nocturno sin charco en suelo.")
    agregar("G06-L2-12", CLASE_6, "L2", "Al pisar a fondo en subida la aguja sube al tope de inmediato y el vapor sopla por la tapa plástica del reservorio.", "COTIDIANO", "subida_fuerte", "aguja_al_rojo_subida|presion_tapa_reservorio", "fallo_bomba_agua", "", "NO", "SI", CLASE_7, "L2 sobrepresión súbita por carga motriz.")
    agregar("G06-L2-13", CLASE_6, "L2", "El aceite en la varilla parece mayonesa espesa y el carro calienta a los diez minutos de encendido sin goteo visible.", "TALLER", "motor_caliente", "emulsion_mayonesa_varilla|recalentamiento", "goteo_mangueras", "", "NO", "SI", CLASE_8, "L2 mezcla agua-aceite con sobrecalentamiento rápido.")
    agregar("G06-L2-14", CLASE_6, "L2", "Se me sopló el empaque creo porque hierve el tacho y cuando acelero fuerte suena un gorgoteo dentro del tablero.", "COTIDIANO", "aceleracion", "ebullicion_tacho|gorgoteo_calefactor", "fuga_calefactor", "", "NO", "NO", "", "L2 burbujas de aire/gas en radiador de calefacción.")
    agregar("G06-L2-15", CLASE_6, "L2", "Presencia de hidrocarburos comprobada en el cuello del radiador, con manguera superior rígida y temperatura que trepa bajo aceleración.", "TECNICO", "aceleracion_carga", "hidrocarburos_refrigerante|manguera_rigida", "falla_ventilador", "", "NO", "SI", CLASE_7, "L2 test positivo de gases de combustión.")

    # --- L3 (15 casos) ---
    agregar("G06-L3-01", CLASE_6, "L3", "El motor recalienta al subir cuestas en autopista botando refrigerante por el tapón de alivio. Al aplicar detector químico de CO2 en el radiador el líquido viró de azul a amarillo. No hay fugas externas.", "TECNICO", "subida_autopista", "recalentamiento_carga|alivio_presion_tapon|co2_refrigerante_positivo", "fugas_externas", "P0217", "NO", "SI", CLASE_8, "L3 químico CO2 positivo y alivio de presión.")
    agregar("G06-L3-02", CLASE_6, "L3", "Arranca con fuerte temblor matutino y humo blanco dulce por el escape. Cilindro 3 registró 75 psi de compresión y al presurizar el cilindro con aire comprimido salieron burbujas por el radiador abierto.", "TALLER", "arranque_frio", "compresion_baja_cilindro|burbujeo_radiador_presurizado|humo_dulce", "falla_inyector", "P0303", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L3 leakdown test con burbujas en radiador.")
    agregar("G06-L3-03", CLASE_6, "L3", "La temperatura trepa a 110 grados en subidas largas. Las mangueras se inflan duras por compresión a los dos minutos de encendido. El electroventilador prende en alta y el termostato nuevo abre a 82 grados.", "TALLER", "subida_carga", "temperatura_110|mangueras_infladas_compresion", "falla_electroventilador|falla_termostato", "", "NO", "SI", CLASE_7, "L3 termostato y ventilador OK pero persiste sobrepresión.")
    agregar("G06-L3-04", CLASE_6, "L3", "Aceite con aspecto lechoso color capuchino en tapa y varilla. Consumo de un litro de refrigerante por semana sin charco en el suelo. La compresión de cilindros 1 y 4 está en 160 psi pero 2 y 3 cayeron a 90 psi.", "TECNICO", "inspeccion_taller", "emulsion_lechosa_aceite|perdida_refrigerante|compresion_baja_adyacentes", "charco_piso", "", "NO", "NO", "", "L3 pérdida de compresión entre cilindros adyacentes y emulsión.")
    agregar("G06-L3-05", CLASE_6, "L3", "Hola maestro, ayer recalentó en carretera y hoy no arranca bien. Saco las bujías 2 y 3 y están oxidadas con gotas de agua verde. El radiador no tiene fuga pero bota compresión al dar arranque.", "WHATSAPP", "arranque", "bujias_oxidadas_agua|escape_compresion_radiador", "fuga_radiador", "", "NO", "SI", CLASE_8, "L3 agua en cilindros tras recalentón en ruta.")
    agregar("G06-L3-06", CLASE_6, "L3", "Temperatura pasa los 105 grados en subida. Al colocar manómetro en el vaso de expansión la presión salta a 22 psi inmediatamente al acelerar a 2500 rpm, superando el límite de la tapa de 15 psi sin fuga externa.", "TECNICO", "aceleracion_estacionaria", "presion_22psi_expansion|sobrepresion_rpm", "fuga_externa", "", "NO", "SI", CLASE_7, "L3 medición manométrica de sobrepresión inmediata.")
    agregar("G06-L3-07", CLASE_6, "L3", "El carro botaba humo blanco dulce al acelerar y bajaba el nivel del agua. En la prueba de fugas de cilindro el cilindro 4 fugó un 40 por ciento hacia el sistema de enfriamiento observándose borbotones en el gollete.", "TALLER", "prueba_estacionaria", "humo_blanco_dulce|fuga_40_porciento_hacia_refrigeracion", "humo_azul_aceite", "", "NO", "SI", CLASE_9, "L3 leakdown test 40% hacia gollete vs aros.")
    agregar("G06-L3-08", CLASE_6, "L3", "Recalentamiento rápido en menos de 10 minutos de marcha. El radiador está frío abajo y tibio arriba pero con mangueras hinchadas a reventar. Al sacar las bujías la cabeza del pistón 1 se ve lavada y reluciente por vapor.", "TALLER", "marcha_corta", "piston_lavado_vapor|mangueras_hinchadas|recalentamiento_rapido", "obstruccion_radiador", "", "NO", "NO", "", "L3 pistón lavado por vapor en cámara.")
    agregar("G06-L3-09", CLASE_6, "L3", "Mi carro recalento en subida y ahora al acelerar gorgorea el tacho de agua y bota vapor blanco por el escape. Ya le cambiaron el termostato y limpiaron el radiador pero la compresion se sigue pasando al agua.", "ERROR_ORTOGRAFICO", "subida_aceleracion", "gorgoreo_tacho|vapor_blanco_escape|compresion_al_agua", "termostato_defectuoso|radiador_sucio", "P0217", "NO", "SI", CLASE_7, "L3 persistencia tras cambio de termostato y radiador.")
    agregar("G06-L3-10", CLASE_6, "L3", "Escáner marca P0300 y P0217. El motor tiembla en ralentí, consume refrigerante de forma interna y genera una nube densa blanca al acelerar tras 15 minutos en tráfico. Aceite presenta microgotas de refrigerante en análisis.", "TECNICO", "trafico_pesado", "dtc_p0300_p0217|consumo_interno_refrigerante|nube_blanca", "humo_negro_combustible", "P0300", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L3 DTC P0300/P0217 con microgotas en aceite.")
    agregar("G06-L3-11", CLASE_6, "L3", "Buenas tardes, el carro pierde agua pero no deja gota en el garaje. Al sacar la varilla el aceite subió dos centímetros sobre el máximo y se ve como café batido. La temperatura sube apenas entra a autopista.", "WHATSAPP", "autopista", "nivel_aceite_elevado_emulsion|perdida_refrigerante_sin_goteo", "goteo_piso", "", "NO", "SI", CLASE_8, "L3 nivel de aceite sube por ingreso de refrigerante.")
    agregar("G06-L3-12", CLASE_6, "L3", "Sobrecalentamiento bajo carga en cuestas. La prueba de presión de refrigerante en frío sostiene 15 psi, pero al encender el motor la aguja oscila bruscamente con cada ciclo de combustión disparándose a 25 psi.", "TECNICO", "encendido_carga", "oscilacion_presion_combustion|sobrepresion_25psi", "fuga_estatica_refrigerante", "", "NO", "SI", CLASE_8, "L3 oscilación rítmica con ciclos de combustión.")
    agregar("G06-L3-13", CLASE_6, "L3", "El vehículo recalienta al rodar más de 20 km/h sostenidos. El depósito bota agua por sobrepresión. No hay fugas en radiador ni mangueras. Al retirar el tapón del aceite se aprecia condensación lechosa densa y olor a gas quemado.", "COTIDIANO", "carretera", "expulsion_agua_sobrepresion|condensacion_lechosa_tapon", "fugas_mangueras|fugas_radiador", "", "NO", "SI", CLASE_8, "L3 condensación en tapón de llenado y expulsión.")
    agregar("G06-L3-14", CLASE_6, "L3", "El motor perdió compresión en caliente y empezó a tirar humo blanco aromático. Las bujías de cilindros 1 y 2 salieron empapadas en refrigerante. Manguera superior con rigidez excesiva antes de 70 grados Celsius.", "TALLER", "motor_caliente", "humo_blanco_aromatico|bujias_empapadas_refrigerante|rigidez_manguera", "falla_chispa", "", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L3 cilindros 1 y 2 con refrigerante y rigidez térmica.")
    agregar("G06-L3-15", CLASE_6, "L3", "Prueba hidrostática de culata arrojó deformación de 0.08 mm en plano de apoyo entre bancadas 2 y 3. El auto recalentaba en aceleración y expulsaba refrigerante por el vaso de expansión sin registrar fallas de electroventilador.", "TECNICO", "aceleracion", "deformacion_plano_culata|expulsion_refrigerante", "falla_electroventilador", "P0217", "NO", "SI", CLASE_7, "L3 metrología de planitud de culata 0.08 mm.")

    # =========================================================================
    # CLASE 7: Falla en termostato o motoventilador de radiador (40 casos: 10 L1, 15 L2, 15 L3)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G07-L1-01", CLASE_7, "L1", "En los semáforos la aguja de temperatura empieza a trepar.", "COTIDIANO", "ralenti_semaforo", "temperatura_sube_parado", "", "", "SI", "NO", "", "L1 calentamiento en detención.")
    agregar("G07-L1-02", CLASE_7, "L1", "El carro calienta cuando estoy parado pero en carretera se normaliza.", "WHATSAPP", "parado_vs_carretera", "calienta_parado|normaliza_carretera", "", "", "SI", "NO", "", "L1 patrón ventilador carretera vs parado.")
    agregar("G07-L1-03", CLASE_7, "L1", "No calienta la calefacción y la aguja nunca llega a la mitad.", "COTIDIANO", "marcha", "calefaccion_fria|aguja_baja", "", "", "SI", "NO", "", "L1 termostato abierto / motor frío.")
    agregar("G07-L1-04", CLASE_7, "L1", "Se escucha el ventilador prendido a máxima velocidad todo el tiempo.", "COTIDIANO", "marcha", "ventilador_continuo", "", "", "SI", "NO", "", "L1 electroventilador en directo continuo.")
    agregar("G07-L1-05", CLASE_7, "L1", "Siento olor a caliente cuando manejo despacio en tráfico.", "COTIDIANO", "trafico_lento", "olor_a_caliente_trafico", "", "", "SI", "NO", "", "L1 olor a caliente en tráfico.")
    agregar("G07-L1-06", CLASE_7, "L1", "El agua del motor se calienta muy rápido a las pocas cuadras.", "TALLER", "pocos_minutos", "calentamiento_muy_rapido", "", "", "SI", "NO", "", "L1 subida rápida sin circulación.")
    agregar("G07-L1-07", CLASE_7, "L1", "La aguja de temperatura baja cuando voy rápido en pista abierta.", "COTIDIANO", "alta_velocidad", "temperatura_cae_velocidad", "", "", "SI", "NO", "", "L1 enfriamiento excesivo en pista.")
    agregar("G07-L1-08", CLASE_7, "L1", "No escucho que prenda el electroventilador cuando el carro calienta.", "WHATSAPP", "motor_caliente", "electroventilador_no_activa", "", "", "SI", "NO", "", "L1 electroventilador inactivo.")
    agregar("G07-L1-09", CLASE_7, "L1", "Ayer me marcó temperatura alta apenas prendí el aire acondicionado en cola.", "COTIDIANO", "trafico_con_aire", "temperatura_alta_con_aire", "", "", "SI", "NO", "", "L1 ventilador no compensa carga de A/C.")
    agregar("G07-L1-10", CLASE_7, "L1", "El motor demora una eternidad en calentar por las mañanas.", "ERROR_ORTOGRAFICO", "arranque_frio", "motor_no_alcanza_temperatura", "", "", "SI", "NO", "", "L1 demora térmica en frío.")

    # --- L2 (15 casos) ---
    agregar("G07-L2-01", CLASE_7, "L2", "En el tráfico de mediodía la temperatura sube casi al rojo, pero apenas avanzo a más de 50 km/h la aguja baja al centro de inmediato.", "COTIDIANO", "trafico_lento", "recalienta_en_trafico|enfria_al_avanzar", "recalentamiento_en_carretera", "", "NO", "SI", CLASE_6, "L2 ventilador inoperante en tráfico vs culata.")
    agregar("G07-L2-02", CLASE_7, "L2", "El motor calienta rapidísimo; la manguera de arriba del radiador quema y la de abajo se siente completamente fría.", "TALLER", "ralenti", "manguera_superior_caliente|manguera_inferior_fria", "circulacion_refrigerante", "", "NO", "SI", CLASE_6, "L2 termostato trabado cerrado por gradiente térmico.")
    agregar("G07-L2-03", CLASE_7, "L2", "Circulando en carretera a 90 km/h la aguja de temperatura se cae casi a cero y el motor empieza a consumir más combustible.", "TECNICO", "carretera_velocidad", "caida_temperatura_carretera|mayor_consumo", "recalentamiento", "P0128", "NO", "NO", "", "L2 termostato trabado abierto con DTC P0128.")
    agregar("G07-L2-04", CLASE_7, "L2", "El electroventilador no arranca ni cuando el tablero marca 100 grados; solo se activa si enciendo el botón del aire acondicionado.", "TALLER", "ralenti_caliente", "ventilador_no_enciende_por_temperatura|enciende_forzado_ac", "falla_motor_ventilador", "", "NO", "NO", "", "L2 falla en relay/sensor de ventilador.")
    agregar("G07-L2-05", CLASE_7, "L2", "Hola, mi carro calienta parado pero el nivel de refrigerante está completo y el aceite está limpio sin nada de mayonesa.", "WHATSAPP", "parado", "calienta_parado", "perdida_refrigerante|emulsion_aceite", "", "NO", "SI", CLASE_6, "L2 descarta culata por ausencia de emulsión y nivel OK.")
    agregar("G07-L2-06", CLASE_7, "L2", "Al quedarme embotellado en cola sube la aguja; abro el capó y veo que el aspa del ventilador está totalmente quieta.", "COTIDIANO", "embotellamiento", "temperatura_sube_cola|ventilador_detenido", "fuga_liquido", "", "NO", "SI", CLASE_8, "L2 visual de ventilador detenido sin fugas.")
    agregar("G07-L2-07", CLASE_7, "L2", "El carro se calienta a los cinco minutos de encendido en plano y sin forzarlo. El agua no circula hacia el panel del radiador.", "TALLER", "plano_sin_carga", "calentamiento_rapido_sin_carga|no_circula_radiador", "fuga_refrigerante", "", "NO", "SI", CLASE_8, "L2 falta de circulación por termostato vs fuga.")
    agregar("G07-L2-08", CLASE_7, "L2", "La calefacción no calienta en carretera y el tablero me arroja código P0128 indicando que el motor no llega a su temperatura de servicio.", "TECNICO", "carretera", "calefaccion_fria|motor_frio_carretera", "sobrecalentamiento", "P0128", "NO", "NO", "", "L2 termostato abierto DTC P0128.")
    agregar("G07-L2-09", CLASE_7, "L2", "El motoventilador vibra horrible y hace un chillido fuerte de buje gastado girando a muy pocas revoluciones en caliente.", "COTIDIANO", "motor_caliente", "chillido_ventilador|baja_velocidad_aspa", "rotura_faja", "", "NO", "NO", "", "L2 desgaste mecánico en motor del ventilador.")
    agregar("G07-L2-10", CLASE_7, "L2", "Se calienta solo al parar en los semaforos despues de rodar media hora. Al andar normal a 60 no calienta nada.", "ERROR_ORTOGRAFICO", "parada_semaforo", "calienta_en_parada", "calienta_a_velocidad", "", "NO", "SI", CLASE_6, "L2 calentamiento exclusivo en detención con ortografía informal.")
    agregar("G07-L2-11", CLASE_7, "L2", "Buenas, el carro calienta cuando estoy en cola y si prendo el aire acondicionado se recalienta mucho más rápido.", "WHATSAPP", "cola_con_ac", "recalienta_en_cola|empeora_con_ac", "humo_blanco", "", "NO", "SI", CLASE_6, "L2 sobrecarga de condensador por ventilador defectuoso.")
    agregar("G07-L2-12", CLASE_7, "L2", "El radiador se mantiene tibio mientras el motor está hirviendo; la válvula termostática parece haberse quedado pegada en su asiento.", "TALLER", "motor_caliente", "radiador_tibio|motor_hirviendo", "perdida_agua", "", "NO", "SI", CLASE_8, "L2 termostato bloqueado mecánicamente cerrado.")
    agregar("G07-L2-13", CLASE_7, "L2", "Aparece testigo Check Engine P0480 y el ventilador principal del radiador no gira al llegar el motor a 98 grados Celsius.", "TECNICO", "ralenti", "dtc_p0480|ventilador_inactivo_98c", "fuga_circuito", "P0480", "NO", "NO", "", "L2 falla de circuito ventilador P0480.")
    agregar("G07-L2-14", CLASE_7, "L2", "El carro calienta parado pero no bota agua ni tiene mangueras reventadas; el nivel se mantiene intacto en la línea de máximo.", "COTIDIANO", "parado", "calienta_parado", "fuga_manguera|baja_nivel", "", "NO", "SI", CLASE_8, "L2 nivel intacto descarta fuga externa.")
    agregar("G07-L2-15", CLASE_7, "L2", "Fusible del electroventilador se quema cada vez que el motor intenta activarlo al llegar a temperatura de régimen.", "TALLER", "activacion_ventilador", "fusible_ventilador_quemado|ventilador_en_corto", "falla_bomba", "", "NO", "NO", "", "L2 cortocircuito en devanado de ventilador.")

    # --- L3 (15 casos) ---
    agregar("G07-L3-01", CLASE_7, "L3", "Temperatura alcanza 108 grados únicamente en ralentí tras 10 minutos de detención. Al escanear con equipo en vivo el sensor ECT marca 106°C pero el comando de baja velocidad del ventilador no energiza el motor eléctrico. El nivel de refrigerante está completo y al rodar a 60 km/h la temperatura cae a 90°C.", "TECNICO", "ralenti_prolongado", "temperatura_108_ralenti|ect_106_sin_ventilador|cae_a_90_en_marcha", "perdida_refrigerante", "P0480", "NO", "SI", CLASE_6, "L3 comando de ventilador inoperante en escáner.")
    agregar("G07-L3-02", CLASE_7, "L3", "El motor recalienta a los 5 kilómetros de recorrido tanto en ciudad como en carretera. Termómetro infrarrojo registra 105°C en la manguera superior y 38°C en la manguera inferior. No hay fugas y el líquido no tiene restos de hidrocarburos ni burbujas.", "TALLER", "marcha_corta", "manguera_sup_105c_inf_38c|recalentamiento_ambas_condiciones", "hidrocarburos_refrigerante|fugas", "", "NO", "SI", CLASE_6, "L3 gradiente térmico 105°C vs 38°C descarta culata.")
    agregar("G07-L3-03", CLASE_7, "L3", "Escáner registra código P0128 permanente. El vehículo circula en carretera a 100 km/h y la temperatura del refrigerante no supera los 65°C. La calefacción emite aire templado y el ajuste de combustible a largo plazo se enriqueció un 12%. El termostato quedó trabado abierto en su carcasa.", "TECNICO", "carretera_100kmh", "dtc_p0128|ect_65c_en_ruta|ltft_enriquecido", "sobrecalentamiento", "P0128", "NO", "NO", "", "L3 termostato trabado abierto con telemetría de trim.")
    agregar("G07-L3-04", CLASE_7, "L3", "En tráfico pesado la aguja roza la zona roja. Al revisar en taller el motor del electroventilador presenta resistencia infinita en su conector por escobillas desgastadas. Se puenteó el relé directo y no giró. El empaque de culata se probó sin fugas de compresión.", "TALLER", "trafico_pesado", "electroventilador_resistencia_infinita|escobillas_gastadas", "fuga_compresion_culata", "", "NO", "SI", CLASE_6, "L3 comprobación eléctrica de motor de ventilador vs culata.")
    agregar("G07-L3-05", CLASE_7, "L3", "Hola, mi carro calienta en los semáforos pero si salgo a la Vía Expresa a 70 km/h la aguja se clava al medio exacto. El nivel de agua no baja nada, no hay humo blanco y el ventilador no arranca por su cuenta.", "WHATSAPP", "via_rapida_vs_semaforo", "calienta_semaforo|enfria_via_rapida", "baja_nivel_agua|humo_blanco", "", "NO", "SI", CLASE_6, "L3 flujo de aire dinámico enfría radiador.")
    agregar("G07-L3-06", CLASE_7, "L3", "Sobrecalentamiento súbito a 112°C. El radiador está frío al tacto en la mitad inferior. Al desmontar la toma de agua se encontró el resorte del termostato roto y el émbolo cruzado en posición totalmente cerrada sin daño en la junta de culata.", "TALLER", "despues_de_recalentar", "termostato_embolo_cruzado_cerrado|radiador_frio_inferior", "dano_junta_culata", "P0217", "NO", "SI", CLASE_6, "L3 inspección física del resorte de termostato.")
    agregar("G07-L3-07", CLASE_7, "L3", "Código P0480 almacenado en ECU. Al realizar prueba de actuadores con el escáner el relé del ventilador de baja velocidad conmuta con clic audible pero no hay salida de 12 voltios hacia el motor por resistencia en el cableado. En carretera la temperatura es de 88°C estable.", "TECNICO", "prueba_actuadores", "dtc_p0480|rele_clic_sin_12v|88c_en_carretera", "falla_termostato", "P0480", "NO", "NO", "", "L3 diagnóstico de caída de voltaje en arnés de ventilador.")
    agregar("G07-L3-08", CLASE_7, "L3", "El vehículo calienta en tráfico congestionado pero el refrigerante está en nivel máximo y no hay burbujeo en el vaso de expansión. Al aplicar corriente directa de 12V a la ficha del electroventilador este no gira y consume 0 amperios por circuito abierto interno.", "TALLER", "trafico_congestionado", "ventilador_consumo_0_amperios|circuito_abierto", "burbujeo_vaso_expansion|perdida_liquido", "", "NO", "SI", CLASE_6, "L3 prueba de corriente directa en ventilador.")
    agregar("G07-L3-09", CLASE_7, "L3", "El auto demora 40 minutos en alcanzar 80 grados y al rodar en bajada la aguja desciende a un cuarto. Termostato retirado para comprobación en banco no cierra herméticamente dejando pasar luz entre el sello y el cuerpo a temperatura ambiente.", "TALLER", "prueba_banco", "termostato_no_cierra_hermetico|demora_calentar", "sobrecalentamiento", "P0128", "NO", "NO", "", "L3 prueba visual de cierre de termostato en frío.")
    agregar("G07-L3-10", CLASE_7, "L3", "El motor recalienta al parar en el semaforo. Mangueras en perfecto estado sin roturas ni fugas, nivel en el maximo, pero el ventilador no gira porque el modulo de control de ventilador esta quemado. En pista libre a 80 km/h la temperatura baja normal.", "ERROR_ORTOGRAFICO", "parada_y_pista_libre", "modulo_ventilador_quemado|temperatura_baja_80kmh", "mangueras_rotas|fugas_refrigerante", "", "NO", "SI", CLASE_8, "L3 módulo de ventilador quemado con mangueras sanas.")
    agregar("G07-L3-11", CLASE_7, "L3", "La temperatura sube en ralentí hasta que salta la alarma acústica a 105°C. El electroventilador solo prende en velocidad alta cuando la presión de alta del gas refrigerante del aire acondicionado supera los 220 psi, pero no activa por la señal del sensor de temperatura de motor.", "TECNICO", "ralenti_con_ac", "electro_no_activa_por_ect|solo_activa_por_presion_ac", "fuga_refrigerante_motor", "", "NO", "NO", "", "L3 activación por presostato de A/C pero no por ECT.")
    agregar("G07-L3-12", CLASE_7, "L3", "El motor calienta en ralentí y ciudad pero el aceite está en óptimo estado y no hay sobrepresión de gases en el radiador. El relé del motoventilador presentó patillas sulfatadas con caída de tensión de 4 voltios bajo carga impidiendo el giro normal del aspa.", "TALLER", "ciudad_ralenti", "rele_sulfatado_caida_4v|aspa_no_gira", "emulsion_aceite|sobrepresion_gases", "", "NO", "SI", CLASE_6, "L3 caída de tensión en relé descarta culata.")
    agregar("G07-L3-13", CLASE_7, "L3", "Recalentamiento rápido en menos de 3 km. Ambas mangueras sin fugas de líquido. La manguera superior se encuentra a 102°C y el radiador permanece templado a 45°C. El termostato se probó en agua caliente en taller y no abrió a los 88°C especificados.", "TALLER", "prueba_banco_termostato", "termostato_no_abre_a_88c|manguera_102c_radiador_45c", "fuga_liquido_mangueras", "P0217", "NO", "SI", CLASE_8, "L3 ensayo en agua caliente de termostato trabado.")
    agregar("G07-L3-14", CLASE_7, "L3", "En autopista despejada a 110 km/h la temperatura se desploma a 60 grados encendiendo el check con DTC P0128. En ralentí en garaje sube a 85 grados lentamente. El termostato instalado carece de empaque de borde y permanece abierto.", "TECNICO", "autopista_despejada", "dtc_p0128|desplome_temperatura_60c", "calentamiento_en_autopista", "P0128", "NO", "NO", "", "L3 termostato con sello roto o abierto en crucero.")
    agregar("G07-L3-15", CLASE_7, "L3", "Maestro, mi carro calienta feo en las colas de la avenida pero saliendo a pista libre no calienta nada. Ya miré el aceite y está doradito, no le falta agua y el ventilador está parado sin moverse cuando la aguja ya pasó la mitad.", "WHATSAPP", "cola_urbana", "calienta_en_cola|ventilador_parado", "aceite_chocolatoso|falta_agua", "", "NO", "SI", CLASE_6, "L3 descripción coloquial WhatsApp descarta culata y fuga.")

    # =========================================================================
    # CLASE 8: Fuga en mangueras de refrigerante o radiador picado (40 casos: 10 L1, 15 L2, 15 L3)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G08-L1-01", CLASE_8, "L1", "Encontré un charco verdoso debajo del parachoques delantero.", "COTIDIANO", "reposo_garaje", "charco_verdoso_delantero", "", "", "SI", "NO", "", "L1 charco de refrigerante.")
    agregar("G08-L1-02", CLASE_8, "L1", "Cada dos días tengo que rellenar el depósito del refrigerante.", "WHATSAPP", "rutina", "relleno_frecuente_refrigerante", "", "", "SI", "NO", "", "L1 pérdida periódica de nivel.")
    agregar("G08-L1-03", CLASE_8, "L1", "Sale vapor blanco por la rejilla del radiador cuando me detengo.", "COTIDIANO", "detencion", "vapor_rejilla_radiador", "", "", "SI", "NO", "", "L1 vapor frontal por fuga caliente.")
    agregar("G08-L1-04", CLASE_8, "L1", "Huele como a dulce quemado cuando bajo del auto.", "COTIDIANO", "despues_de_manejar", "olor_dulce_quemado", "", "", "SI", "NO", "", "L1 olor dulce de etilenglicol evaporado.")
    agregar("G08-L1-05", CLASE_8, "L1", "Vi unas gotas rosadas cayendo cerca de una manguera gruesa.", "WHATSAPP", "motor_encendido", "goteo_rosado_manguera", "", "", "SI", "NO", "", "L1 goteo localizado en manguera.")
    agregar("G08-L1-06", CLASE_8, "L1", "El depósito de agua se vacía solo de un día para otro.", "COTIDIANO", "estacionado", "deposito_se_vacia", "", "", "SI", "NO", "", "L1 vaciado estático de depósito.")
    agregar("G08-L1-07", CLASE_8, "L1", "Se ve como sarro seco de color verde en la esquina del radiador.", "TALLER", "inspeccion_visual", "sarro_verde_esquina_radiador", "", "", "SI", "NO", "", "L1 sarro seco cristalizado en radiador.")
    agregar("G08-L1-08", CLASE_8, "L1", "Ayer escupió agua caliente por delante al llegar a mi casa.", "COTIDIANO", "llegada_parada", "escape_agua_caliente_frontal", "", "", "SI", "NO", "", "L1 rotura/escape frontal repentino.")
    agregar("G08-L1-09", CLASE_8, "L1", "Tengo una manguera del motor hinchada y con humedad en la abrasadera.", "ERROR_ORTOGRAFICO", "inspeccion", "manguera_hinchada_humedad", "", "", "SI", "NO", "", "L1 manguera hinchada con error ortográfico.")
    agregar("G08-L1-10", CLASE_8, "L1", "Pérdida externa de refrigerante con goteo continuo en el soporte inferior del radiador.", "TECNICO", "ralenti", "perdida_externa_goteo_inferior", "", "", "SI", "NO", "", "L1 técnico de goteo en soporte de radiador.")

    # --- L2 (15 casos) ---
    agregar("G08-L2-01", CLASE_8, "L2", "Hay un charco de líquido verde bajo el radiador cada mañana y el nivel baja dos dedos, pero el motor no calienta mientras tenga agua.", "COTIDIANO", "reposo_manana", "charco_verde_radiador|baja_nivel_dos_dedos", "sobrecalentamiento", "", "NO", "SI", CLASE_7, "L2 fuga externa con temperatura normal mientras hay fluido.")
    agregar("G08-L2-02", CLASE_8, "L2", "Se observa un hilo fino de vapor saliendo del panel del radiador y goteo constante por la unión entre el aluminio y el tanque de plástico.", "TALLER", "motor_caliente", "hilo_vapor_panel|goteo_tanque_plastico_aluminio", "falla_ventilador", "", "NO", "SI", CLASE_7, "L2 fisura en sello de tanque plástico de radiador.")
    agregar("G08-L2-03", CLASE_8, "L2", "La manguera superior del radiador tiene una pequeña grieta cerca de la abrazadera y pulveriza refrigerante caliente sobre el alternador.", "COTIDIANO", "aceleracion", "manguera_agrietada|pulverizacion_refrigerante", "humo_blanco_escape", "", "NO", "SI", CLASE_6, "L2 manguera pinchada externa vs humo de culata.")
    agregar("G08-L2-04", CLASE_8, "L2", "Goteo constante de refrigerante rojo por la parte baja del radiador al presurizar el circuito, con aceite de motor completamente limpio.", "TECNICO", "prueba_presion", "goteo_radiador_rojo", "emulsion_aceite", "", "NO", "SI", CLASE_6, "L2 goteo radiador con aceite limpio descarta culata.")
    agregar("G08-L2-05", CLASE_8, "L2", "Hola, encontré agua verde chorreando por la bandeja del motor. El carro camina bien y el ventilador sí gira cuando prende.", "WHATSAPP", "marcha", "chorreo_agua_bandeja", "falla_ventilador", "", "NO", "SI", CLASE_7, "L2 chorreo externo con ventilador funcionando OK.")
    agregar("G08-L2-06", CLASE_8, "L2", "El radiador está picado en la esquina inferior izquierda; se nota sarro blanco con verde acumulado y mancha el piso al enfriarse.", "TALLER", "enfriamiento", "radiador_picado_sarro|mancha_piso_enfriar", "humo_escape", "", "NO", "NO", "", "L2 fuga en frío por dilatación en radiador picado.")
    agregar("G08-L2-07", CLASE_8, "L2", "Manguera del calefactor que entra a la cabina está reseca y gotea sobre la caja de cambios, bajando el depósito cada tres días.", "COTIDIANO", "motor_encendido", "manguera_calefactor_gotea", "temperatura_alta", "", "NO", "NO", "", "L2 manguera de calefactor agrietada.")
    agregar("G08-L2-08", CLASE_8, "L2", "Siento fuerte olor a etilenglicol dulce al parar en peajes y veo gotas que caen al protector de cárter sin que la aguja pase del medio.", "COTIDIANO", "parada_peaje", "olor_etilenglicol|gotas_protector_carter", "temperatura_alta", "", "NO", "SI", CLASE_7, "L2 olor dulce y gotas con aguja al medio.")
    agregar("G08-L2-09", CLASE_8, "L2", "El tanque plastico del radiador tiene una rajadura fina por donde escupe un chorrito de agua caliente cuando acelero.", "ERROR_ORTOGRAFICO", "aceleracion", "tanque_radiador_rajado|chorro_agua", "burbujas_compresion", "", "NO", "SI", CLASE_6, "L2 fisura en tanque plástico con error ortográfico.")
    agregar("G08-L2-10", CLASE_8, "L2", "Caída de presión rápida en el manómetro de prueba de enfriamiento a 15 psi, detectando fuga audible en la manguera inferior del radiador.", "TECNICO", "prueba_bomba_manual", "caida_presion_15psi|fuga_manguera_inferior", "fuga_interna_cilindro", "", "NO", "SI", CLASE_6, "L2 test de presurización con fuga externa audible.")
    agregar("G08-L2-11", CLASE_8, "L2", "Buenas, gotea refrigerante por la manguera fina del retorno al tacho porque la abrazadera original cedió y está floja.", "WHATSAPP", "reposo", "goteo_manguera_retorno|abrazadera_floja", "rotura_radiador", "", "NO", "NO", "", "L2 abrazadera de retorno vencida.")
    agregar("G08-L2-12", CLASE_8, "L2", "Al apagar el motor se escucha un silbido delante y cae un chorro de agua caliente por la unión de la manguera gruesa inferior.", "COTIDIANO", "al_apagar", "silbido_frontal|chorro_manguera_inferior", "ebullicion_interna", "", "NO", "NO", "", "L2 despresurización por rotura de manguera inferior.")
    agregar("G08-L2-13", CLASE_8, "L2", "Radiador con panel corroído por usar agua de caño en vez de refrigerante; tiene microfugas que manchan de óxido y bajan el nivel.", "TALLER", "inspeccion", "radiador_corroido_oxido|microfugas_panel", "falla_empaque", "", "NO", "SI", CLASE_6, "L2 corrosión por agua común vs culata.")
    agregar("G08-L2-14", CLASE_8, "L2", "El auto pierde agua solo cuando calienta y agarra presión, dejando un charco claro debajo del parachoques sin gotear en frío.", "COTIDIANO", "motor_caliente", "fuga_bajo_presion|charco_parachoques", "fuga_estatica_frio", "", "NO", "NO", "", "L2 fuga térmica por dilatación.")
    agregar("G08-L2-15", CLASE_8, "L2", "Manguera bypass de la bomba de agua con hinchazón severa y pérdida por goteo continuo sobre la polea del cigüeñal.", "TECNICO", "ralenti", "manguera_bypass_hinchada|goteo_sobre_polea", "falla_bomba_agua", "", "NO", "NO", "", "L2 manguera bypass degradada.")

    # --- L3 (15 casos) ---
    agregar("G08-L3-01", CLASE_8, "L3", "Pérdida de un litro de refrigerante cada 200 km. Al aplicar la bomba de presurización al radiador a 15 psi con el motor apagado, la presión cae a 5 psi en 30 segundos y se observa un chorro continuo en el tanque lateral plástico del radiador fisurado.", "TECNICO", "prueba_estatica_15psi", "caida_presion_15_a_5psi|chorro_tanque_lateral_fisurado", "fuga_interna|emulsion_aceite", "", "NO", "SI", CLASE_6, "L3 prueba de presión 15 psi localiza fisura en tanque lateral.")
    agregar("G08-L3-02", CLASE_8, "L3", "El cliente reclama olor a refrigerante y charco matutino. En elevador se comprueba manguera inferior de radiador rozada por la polea de la dirección hidráulica, presentando desgaste y perforación milimétrica con fuga activa a temperatura de régimen.", "TALLER", "inspeccion_elevador", "manguera_rozada_polea|perforacion_milimetrica_fuga", "sobrecalentamiento_previo", "", "NO", "NO", "", "L3 daño mecánico por roce en manguera inferior.")
    agregar("G08-L3-03", CLASE_8, "L3", "Vapor blanco saliendo por la parrilla tras 15 minutos de manejo. El panel del radiador de aluminio presenta tres tubos picados con incrustaciones verdes y goteo constante. El aceite de motor está en nivel correcto y el electroventilador conmuta normalmente.", "TALLER", "motor_caliente", "tubos_radiador_picados|vapor_parrilla|goteo_constante", "aceite_contaminado|falla_ventilador", "", "NO", "SI", CLASE_7, "L3 tubos picados con ventilador y aceite conformes.")
    agregar("G08-L3-04", CLASE_8, "L3", "El depósito de refrigerante se vacía cada dos días. Prueba con líquido fluorescente UV reveló fuga brillante en la junta del termostato y abrazadera inferior de radiador. No hay presencia de burbujas en expansión ni hidrocarburos.", "TECNICO", "inspeccion_uv", "fuga_uv_abrazadera_radiador|perdida_refrigerante", "burbujas_expansion|hidrocarburos", "", "NO", "SI", CLASE_6, "L3 trazador UV confirma fuga externa.")
    agregar("G08-L3-05", CLASE_8, "L3", "Hola maestro, goteaba agua rosada bajo el parachoques. Desarmé la defensa y el tanque plástico superior del radiador tiene una rajadura de 10 centímetros cerca del cuello de llenado que escupe líquido con el motor caliente.", "WHATSAPP", "motor_caliente", "rajadura_10cm_tanque_superior|fuga_cuello_llenado", "humo_escape", "", "NO", "SI", CLASE_6, "L3 fisura de 10 cm en tanque superior descarta culata.")
    agregar("G08-L3-06", CLASE_8, "L3", "Al exigir el motor en subida la aguja sube porque el nivel de agua bajó a la mitad. Se constató rotura longitudinal de 2 cm en manguera de retorno de calefacción por envejecimiento de la goma, con charco evidente en el piso de la cochera.", "COTIDIANO", "subida_post_perdida", "rotura_manguera_calefaccion|charco_cochera|nivel_bajo", "falla_empaque_culata", "", "NO", "SI", CLASE_6, "L3 rotura longitudinal de manguera de calefacción.")
    agregar("G08-L3-07", CLASE_8, "L3", "Presurización del sistema a 1.2 bar con manómetro de taller. Se detecta fuga activa por microfisuras en el engrapado del radiador entre el plástico y el aluminio. La compresión de los 4 cilindros se mantiene en 175 psi parejos sin caída.", "TECNICO", "presurizacion_1_2_bar", "fuga_engrapado_radiador|compresion_175psi_pareja", "falla_compresion", "", "NO", "SI", CLASE_6, "L3 engrapado fisurado con compresión 175 psi pareja.")
    agregar("G08-L3-08", CLASE_8, "L3", "El auto botó todo el refrigerante en plena avenida. Se encontró la manguera superior abierta en forma de boca de pez por degradación térmica y química. El radiador está en buen estado y el ventilador enciende a 96°C.", "TALLER", "parada_emergencia", "manguera_superior_abierta_boca_pez|perdida_total_liquido", "dano_radiador|falla_ventilador", "", "NO", "SI", CLASE_7, "L3 rotura boca de pez con ventilador verificado.")
    agregar("G08-L3-09", CLASE_8, "L3", "Tengo una fuga en el radiador que moja la pista cada ves que estaciono. El carro no calienta en movimiento pero el tacho queda seco. El mecanico le puso bomba de aire y salio chorro de agua por el medio del panal del radiador.", "ERROR_ORTOGRAFICO", "estacionamiento", "fuga_panal_radiador|chorro_bajo_presion", "calentamiento_en_movimiento", "", "NO", "SI", CLASE_7, "L3 panal perforado con prueba de aire y error ortográfico.")
    agregar("G08-L3-10", CLASE_8, "L3", "Consumo continuo de medio litro diario de anticongelante. Radiador presenta corrosión galvánica externa con goteo por la base inferior derecha. La prueba de CO2 en gases de escape sobre refrigerante resultó negativa.", "TECNICO", "inspeccion_taller", "corrosion_galvanica_radiador|goteo_inferior_derecho", "co2_refrigerante_negativo", "", "NO", "SI", CLASE_6, "L3 corrosión externa con test CO2 negativo descarta culata.")
    agregar("G08-L3-11", CLASE_8, "L3", "Buenas, gotea líquido verde por debajo del motor al apagarlo. Mirando con linterna se ve la manguera inferior cuarteada con tres chorritos finos hacia el chasis. La temperatura nunca pasó de la mitad.", "WHATSAPP", "al_apagar", "manguera_inferior_cuarteada|chorros_hacia_chasis", "sobrecalentamiento", "", "NO", "NO", "", "L3 chorros visibles en manguera cuarteada.")
    agregar("G08-L3-12", CLASE_8, "L3", "Pérdida de refrigerante solo en frío durante la noche por contracción de la manguera superior reseca sobre la boca de aluminio del termostato. Al encender y dilatar cesa la fuga, dejando charco de 200 ml cada madrugada.", "TALLER", "reposo_nocturno_frio", "fuga_por_contraccion_nocturna|charco_200ml", "fuga_en_caliente", "", "NO", "NO", "", "L3 fuga estática por contracción térmica nocturna.")
    agregar("G08-L3-13", CLASE_8, "L3", "Vapor blanco saliendo bajo el capó al llegar de viaje. Se diagnosticó perforación en el radiador producida por impacto de piedra en carretera. El circuito perdió 1.5 litros pero el motor se apagó a tiempo sin recalentar la culata.", "COTIDIANO", "viaje_carretera", "impacto_piedra_radiador|perforacion_panel|fuga_1_5l", "dano_culata", "", "NO", "SI", CLASE_6, "L3 impacto de piedra en radiador sin daño a culata.")
    agregar("G08-L3-14", CLASE_8, "L3", "Inspección técnica: sistema no retiene 1.0 bar de presión estática. Se evidencia goteo profuso por la manguera de derivación hacia el enfriador de aceite, la cual se encuentra reblandecida por contaminación de aceite externo.", "TECNICO", "presurizacion_estatica", "goteo_manguera_enfriador_aceite|manguera_reblandecida", "dano_radiador_principal", "", "NO", "NO", "", "L3 manguera ablandada por aceite externo con pérdida activa.")
    agregar("G08-L3-15", CLASE_8, "L3", "El auto derramó dos litros de refrigerante en el garaje. La abrazadera inferior tipo resorte del radiador perdió tensión y la manguera se zafó parcialmente. El panel del radiador y el empaque de culata están en perfecto estado.", "TALLER", "garaje", "abrazadera_resorte_vencida|manguera_zafada", "dano_empaque_culata|dano_radiador", "", "NO", "SI", CLASE_6, "L3 abrazadera zafada con culata y radiador intactos.")

    # =========================================================================
    # CLASE 9: Consumo de aceite por desgaste de anillos o retenes (40 casos: 10 L1, 15 L2, 15 L3)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G09-L1-01", CLASE_9, "L1", "El carro me está pidiendo un litro de aceite cada dos semanas.", "COTIDIANO", "marcha", "consumo_aceite_frecuente", "", "", "SI", "NO", "", "L1 consumo elevado de aceite.")
    agregar("G09-L1-02", CLASE_9, "L1", "Bota humo azulado por el escape al arrancar por las mañanas.", "COTIDIANO", "arranque_frio", "humo_azul_manana", "", "", "SI", "NO", "", "L1 humo azul matutino.")
    agregar("G09-L1-03", CLASE_9, "L1", "Siento olor a aceite quemado cuando acelero en carretera.", "COTIDIANO", "carretera", "olor_aceite_quemado", "", "", "SI", "NO", "", "L1 olor a aceite quemado bajo carga.")
    agregar("G09-L1-04", CLASE_9, "L1", "La varilla marca el mínimo de aceite y no veo ninguna mancha en el piso.", "COTIDIANO", "reposo", "nivel_varilla_minimo_sin_mancha", "", "", "SI", "NO", "", "L1 baja de nivel sin fuga externa.")
    agregar("G09-L1-05", CLASE_9, "L1", "Al acelerar fuerte el auto deja una nube medio azul atrás.", "WHATSAPP", "aceleracion_fuerte", "nube_azul_acelerar", "", "", "SI", "NO", "", "L1 nube azul al acelerar fuerte.")
    agregar("G09-L1-06", CLASE_9, "L1", "Tengo que andar con un cuarto de aceite en la maletera para rellenar.", "WHATSAPP", "rutina", "relleno_constante_aceite", "", "", "SI", "NO", "", "L1 hábito de relleno constante.")
    agregar("G09-L1-07", CLASE_9, "L1", "Sale humo por la tapa por donde se echa el aceite si la saco con el motor prendido.", "COTIDIANO", "ralenti", "humo_tapa_llenado_aceite", "", "", "SI", "NO", "", "L1 soplado por tapa de llenado (blow-by).")
    agregar("G09-L1-08", CLASE_9, "L1", "Las bujías salen negras y grasosas cada vez que las reviso.", "TALLER", "inspeccion_bujias", "bujias_carbon_grasoso", "", "", "SI", "NO", "", "L1 bujías empapadas en aceite quemado.")
    agregar("G09-L1-09", CLASE_9, "L1", "El motor consume aceite pero no gotea nada por abajo.", "COTIDIANO", "marcha", "consumo_aceite_sin_goteo", "", "", "SI", "NO", "", "L1 consumo interno sin goteo.")
    agregar("G09-L1-10", CLASE_9, "L1", "Consume aciete y bota humo azul cuando lo piso despues de una bajada.", "ERROR_ORTOGRAFICO", "desaceleracion_bajada", "humo_azul_post_bajada", "", "", "SI", "NO", "", "L1 humo tras retención con error ortográfico.")

    # --- L2 (15 casos) ---
    agregar("G09-L2-01", CLASE_9, "L2", "El auto bota una bocanada de humo azul en el primer arranque matutino que dura 10 segundos y luego desaparece, bajando medio litro de aceite al mes.", "TALLER", "arranque_frio", "bocanada_azul_arranque|consumo_medio_litro", "humo_continuo", "", "NO", "SI", CLASE_10, "L2 retenes de válvula en frío vs bomba de aceite.")
    agregar("G09-L2-02", CLASE_9, "L2", "Consume un litro de aceite cada 800 kilómetros botando humo azul constante en subidas y aceleraciones fuertes, sin manchas en el piso del garaje.", "COTIDIANO", "subida_aceleracion", "consumo_1l_800km|humo_azul_aceleracion", "manchas_piso", "", "NO", "SI", CLASE_10, "L2 desgaste de anillos bajo carga vs presión de bomba.")
    agregar("G09-L2-03", CLASE_9, "L2", "Al retirar la varilla con el motor encendido sopla vapor aceitoso continuo por el tubo y el escape deja hollín negro grasoso en el paragolpes.", "TECNICO", "ralenti", "blowby_tubo_varilla|hollin_grasoso_escape", "perdida_presion_aceite", "", "NO", "SI", CLASE_10, "L2 sobrepresión de cárter (blow-by) vs testigo de presión.")
    agregar("G09-L2-04", CLASE_9, "L2", "Hola, mi carro gasta un galón de aceite entre cambio y cambio. No gotea nada por el retén del cigüeñal y la presión de aceite está perfecta.", "WHATSAPP", "rutina", "gasto_aceite_elevado", "goteo_reten_ciguenal|baja_presion_aceite", "", "NO", "SI", CLASE_10, "L2 consumo con presión de aceite normal descarta bomba.")
    agregar("G09-L2-05", CLASE_9, "L2", "Después de bajar una cuesta larga con freno de motor, al pisar el acelerador a fondo sale una cortina de humo azul por el escape.", "COTIDIANO", "aceleracion_post_retencion", "humo_azul_retencion_vacio", "humo_negro", "", "NO", "NO", "", "L2 succión de aceite por retenes de válvula por alto vacío.")
    agregar("G09-L2-06", CLASE_9, "L2", "Las cuatro bujías presentan costra negra gruesa de carbón aceitoso y el motor consume un litro cada 1000 km sin pérdida de agua.", "TALLER", "inspeccion_bujias", "bujias_costra_aceite|consumo_1l_1000km", "perdida_refrigerante", "", "NO", "SI", CLASE_6, "L2 bujías empapadas sin consumo de agua descarta culata.")
    agregar("G09-L2-07", CLASE_9, "L2", "El motor consume aceite pero no tiene ninguna fuga externa visible. La luz del aceite nunca se prende y no suena ningún cascabeleo de taqués.", "COTIDIANO", "marcha", "consumo_aceite_sin_fuga", "testigo_aceite_encendido|ruido_taques", "", "NO", "SI", CLASE_10, "L2 ausencia de testigo y de ruido descarta bomba defectuosa.")
    agregar("G09-L2-08", CLASE_9, "L2", "Prueba de compresión en seco arrojó 120 psi parejos en los 4 cilindros, pero al agregar una cucharada de aceite subió a 160 psi.", "TECNICO", "prueba_compresion", "compresion_seco_120_humedo_160", "compresion_desigual", "", "NO", "NO", "", "L2 prueba húmeda confirma sellado de anillos.")
    agregar("G09-L2-09", CLASE_9, "L2", "Mi carro bota humo asul cada ves que salgo de un semáforo rápido y tengo que echarle aceite cada semana para que no baje del nivel.", "ERROR_ORTOGRAFICO", "salida_semaforo", "humo_azul_salida|relleno_semanal_aceite", "charco_cochera", "", "NO", "SI", CLASE_10, "L2 humo azul en aceleración con error ortográfico.")
    agregar("G09-L2-10", CLASE_9, "L2", "Humo azulado visible por el retrovisor al pasar los 3500 rpm en carretera abierta. El filtro de aire tiene residuos de aceite del respiradero PCV.", "TALLER", "alta_rpm", "humo_azul_3500rpm|aceite_en_filtro_pcv", "fuga_carter", "", "NO", "NO", "", "L2 blow-by satura sistema PCV en alta rotación.")
    agregar("G09-L2-11", CLASE_9, "L2", "Buenas, el carro tiene 280 mil km y se come un litro cada mil km. En frío humea azul y en caliente se calma un poco.", "WHATSAPP", "arranque_frio_vs_caliente", "consumo_1l_1000km_alto_km|humo_azul_frio", "fuga_reten", "", "NO", "NO", "", "L2 desgaste general por alto kilometraje.")
    agregar("G09-L2-12", CLASE_9, "L2", "El escape huele a aceite quemado penetrante y el catalizador empieza a taparse, arrojando código P0420 por contaminación de aceite.", "TECNICO", "marcha", "olor_aceite_quemado|dtc_p0420_catalizador_aceite", "misfire_encendido", "P0420", "NO", "SI", "Convertidor catalitico ineficiente u obstruido (DTC P0420 / P0430)", "L2 catalizador degradado por consumo crónico de aceite.")
    agregar("G09-L2-13", CLASE_9, "L2", "Se revisó cárter, tapa de balancines y retén de bancada sin detectar goteo; el consumo de litro y medio por cambio es puramente por combustión.", "TALLER", "inspeccion_fugas", "sin_fugas_carter_balancines_bancada|consumo_por_combustion", "goteo_reten", "", "NO", "SI", CLASE_10, "L2 inspección descarta fugas externas.")
    agregar("G09-L2-14", CLASE_9, "L2", "Al pisar el acelerador con el carro caliente tira humo azul grisáceo. La presión de aceite se midió en 40 psi a 2000 rpm estando en rango.", "TECNICO", "aceleracion_caliente", "humo_azul_grisaceo|presion_aceite_40psi_ok", "baja_presion_aceite", "", "NO", "SI", CLASE_10, "L2 presión 40 psi normal descarta falla de bomba.")
    agregar("G09-L2-15", CLASE_9, "L2", "El nivel de aceite baja de la marca FULL a LOW en 600 kilómetros de autopista con humo azul en retenciones y aceleradas bruscas.", "COTIDIANO", "autopista", "caida_full_a_low_600km|humo_azul_retencion", "fuga_externa", "", "NO", "NO", "", "L2 caída acelerada de nivel en autopista.")

    # --- L3 (15 casos) ---
    agregar("G09-L3-01", CLASE_9, "L3", "Consumo excesivo de 1.2 litros de aceite por cada 1000 km sin goteo externo. Prueba de compresión seca marcó 115-118 psi en los 4 cilindros; al inyectar 10 ml de aceite la compresión subió a 155-160 psi en todos, confirmando desgaste en los aros de compresión y rascadores.", "TECNICO", "prueba_compresion_humeda", "consumo_1_2l_1000km|compresion_seca_115_humeda_160", "fugas_externas", "", "NO", "SI", CLASE_10, "L3 prueba seca vs húmeda certifica anillos.")
    agregar("G09-L3-02", CLASE_9, "L3", "El vehículo emite densa humareda azulada durante los primeros 15 segundos tras el arranque en frío luego de estar parado toda la noche. Al calentar el humo cesa y la prueba de compresión arrojó 170 psi parejos, diagnosticándose desgaste en los retenes de guías de válvulas.", "TALLER", "arranque_frio_matutino", "humareda_azul_15seg_frio|compresion_170psi_buena", "humo_continuo_aceleracion", "", "NO", "SI", CLASE_6, "L3 retenes de válvula: humo matutino con compresión 170 psi.")
    agregar("G09-L3-03", CLASE_9, "L3", "Cliente reporta gasto de aceite de 1 litro cada 700 km con humo azul al acelerar a más de 3000 rpm. Inspección endoscópica en cilindros muestra paredes con rayaduras verticales y carbón aceitoso en corona de pistones. El testigo de presión de aceite permanece apagado.", "TECNICO", "endoscopia_cilindros", "rayaduras_cilindro_endoscopia|carbon_corona_piston", "testigo_presion_aceite", "", "NO", "SI", CLASE_10, "L3 endoscopía confirma rayado de cilindro con presión OK.")
    agregar("G09-L3-04", CLASE_9, "L3", "Humo azul constante en aceleraciones bajo carga. Se retiraron las 4 bujías encontrándose electrodos cubiertos de costra de ceniza blanca aceitosa. La prueba de vacío del cárter muestra sobrepresión positiva de 2 psi por paso de compresión a través de anillos desgastados.", "TALLER", "aceleracion_carga", "bujias_ceniza_aceite|presion_positiva_carter_2psi", "falla_bujias_combustible", "P0300", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L3 sobrepresión positiva en cárter por anillos.")
    agregar("G09-L3-05", CLASE_9, "L3", "Hola, mi camioneta quema aceite en subidas botando humo azul por el escape. En 3000 km se tomó 4 litros. La revisaron abajo y no gotea una gota. Las bujías salen empapadas en aceite quemado y no pierde refrigerante.", "WHATSAPP", "subidas", "quema_aceite_humo_azul|consumo_4l_3000km|bujias_aceite", "goteo_externo|perdida_refrigerante", "", "NO", "SI", CLASE_6, "L3 alto consumo en subidas sin pérdida de refrigerante.")
    agregar("G09-L3-06", CLASE_9, "L3", "Vehículo con 240,000 km presenta humo azul al acelerar fuerte y en retención de motor. Presión de aceite medida con manómetro mecánico marca 42 psi a 2500 rpm descartando bomba defectuosa. La prueba de fuga de cilindros arrojó 25% de fuga hacia el cárter en cilindros 2 y 3.", "TECNICO", "prueba_fugas_cilindro", "fuga_25_porciento_a_carter|presion_aceite_42psi_ok", "baja_presion_bomba", "", "NO", "SI", CLASE_10, "L3 leakdown hacia cárter con presión 42 psi descarta bomba.")
    agregar("G09-L3-07", CLASE_9, "L3", "El motor consume aceite a razón de 1 litro cada 650 km. En desaceleración prolongada desde 80 km/h y posterior acelerada a fondo genera una densa nube azul. Retenes de válvulas endurecidos y cristalizados por sobrecalentamiento previo.", "TALLER", "prueba_desaceleracion_aceleracion", "nube_azul_post_desaceleracion|consumo_1l_650km", "perdida_presion", "", "NO", "NO", "", "L3 retención prolongada succiona aceite por retenes cristalizados.")
    agregar("G09-L3-08", CLASE_9, "L3", "DTC P0420 por ineficiencia de catalizador. El sensor de oxígeno posterior reporta lectura contaminada por hollín de aceite. El motor consume 1.5 cuartos de aceite cada 1000 km y genera humo azulado al acelerar en caliente sin goteo en cárter.", "TECNICO", "motor_caliente", "dtc_p0420|sensor_oxigeno_hollin_aceite|consumo_1_5qt", "fuga_carter", "P0420", "NO", "SI", "Convertidor catalitico ineficiente u obstruido (DTC P0420 / P0430)", "L3 DTC P0420 secundario a quema crónica de aceite.")
    agregar("G09-L3-09", CLASE_9, "L3", "Mi carro gasta un litro de aceite cada 500 km y bota humo azul al acelerar. El manómetro marca 35 psi de presion de aceite en caliente, o sea la bomba esta buena pero los anillos ya no sellan y pasan aceite a la camara.", "ERROR_ORTOGRAFICO", "aceleracion_caliente", "gasto_1l_500km|humo_azul|presion_35psi_ok", "falla_bomba_aceite", "", "NO", "SI", CLASE_10, "L3 presión 35 psi confirma aros y descarta bomba con ortografía informal.")
    agregar("G09-L3-10", CLASE_9, "L3", "Inspección de bujías revela depósito vitrificado de aceite quemado en cilindros 1 y 4. Prueba de compresión húmeda confirmó recuperación de 45 psi por cilindro tras sellar aros. Nivel de refrigerante permanece intacto sin mezcla de fluidos.", "TALLER", "taller_bujias", "bujias_deposito_vitrificado|recuperacion_45psi_humeda", "perdida_refrigerante|emulsion", "", "NO", "SI", CLASE_6, "L3 diagnóstico formal de aros sin daño a culata.")
    agregar("G09-L3-11", CLASE_9, "L3", "El cliente debe agregar 1 litro de aceite 20W-50 cada 800 km para mantener la varilla en nivel. Al desacelerar en bajada y acelerar produce humo azul notorio. Válvula PCV nueva no corrigió el problema comprobándose sellos de válvulas gastados.", "COTIDIANO", "bajada_y_aceleracion", "consumo_1l_800km_aceite_grueso|humo_azul", "falla_valvula_pcv", "", "NO", "NO", "", "L3 PCV nueva no resuelve consumo por sellos de válvula.")
    agregar("G09-L3-12", CLASE_9, "L3", "Prueba de hermeticidad con detector de fugas: cilindro 1 fuga 28% con soplido audible a través de la boca de llenado de aceite en la tapa de balancines. No hay soplido hacia el radiador ni hacia el múltiple de escape.", "TECNICO", "prueba_hermeticidad", "fuga_28_porciento_hacia_tapa_balancines", "fuga_hacia_radiador|fuga_escape", "", "NO", "SI", CLASE_6, "L3 fuga audible hacia tapa de balancines descarta culata y escape.")
    agregar("G09-L3-13", CLASE_9, "L3", "El auto consume aceite de manera sostenida a razón de 1 litro cada 1000 km. La compresión en seco marcó 125 psi y la húmeda 165 psi. En aceleraciones fuertes en segunda y tercera marcha el tubo de escape suelta humo azul sin pérdida de potencia severa.", "TALLER", "segunda_tercera_marcha", "consumo_1l_1000km|seco_125_humedo_165|humo_azul", "falla_encendido", "", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L3 aros de compresión con humo azul en marchas cortas.")
    agregar("G09-L3-14", CLASE_9, "L3", "Buenas tardes, el carro bota humo azul al prender en frío en la mañana y consume 1 litro de aceite cada 15 días. Las bujías tienen aceite en las roscas y la presión de aceite marca 18 psi en ralentí caliente dentro de norma.", "WHATSAPP", "arranque_manana", "humo_azul_frio|consumo_1l_15dias|presion_18psi_ok", "baja_presion_aceite", "", "NO", "SI", CLASE_10, "L3 retenes en frío con presión 18 psi en ralentí caliente.")
    agregar("G09-L3-15", CLASE_9, "L3", "Consumo excesivo de aceite con diagnóstico diferencial completado: prueba de vacío de admisión arroja 19 inHg estables descartando guías de admisión, pero compresión húmeda incrementa 35 psi en todos los cilindros demostrando fatiga en aros de aceite.", "TECNICO", "diagnostico_diferencial", "vacio_19inhg_estable|compresion_humeda_sube_35psi", "falla_guias_admision", "", "NO", "NO", "", "L3 vacío 19 inHg descarta guías y confirma fatiga de aros.")

    # =========================================================================
    # CLASE 10: Baja presion de aceite o bomba de aceite defectuosa (40 casos: 10 L1, 15 L2, 15 L3)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G10-L1-01", CLASE_10, "L1", "Se me prende el foquito rojo de la aceitera en el tablero cuando freno en los semáforos.", "COTIDIANO", "ralenti_semaforo", "testigo_aceite_parpadea_parado", "", "", "SI", "NO", "", "L1 testigo de aceite en mínimo.")
    agregar("G10-L1-02", CLASE_10, "L1", "El motor suena como un cascabeleo de taqués metálico arriba.", "COTIDIANO", "ralenti", "ruido_taques_metalico", "", "", "SI", "NO", "", "L1 ruido de taqués por falta de presión.")
    agregar("G10-L1-03", CLASE_10, "L1", "Parpadea la luz del aceite en caliente pero la varilla marca lleno.", "WHATSAPP", "motor_caliente", "luz_aceite_parpadea|varilla_llena", "", "", "SI", "NO", "", "L1 testigo prende con nivel de aceite completo.")
    agregar("G10-L1-04", CLASE_10, "L1", "Escucho un traqueteo feo en la parte alta del motor al regular.", "TALLER", "ralenti", "traqueteo_parte_alta_motor", "", "", "SI", "NO", "", "L1 traqueteo en culata en ralentí.")
    agregar("G10-L1-05", CLASE_10, "L1", "Se encendió el testigo de aceite y el motor suena seco.", "COTIDIANO", "motor_caliente", "testigo_aceite_encendido|motor_suena_seco", "", "", "SI", "NO", "", "L1 motor ruidoso con testigo encendido.")
    agregar("G10-L1-06", CLASE_10, "L1", "La aguja de presión de aceite se cae al piso cuando el motor calienta en mínimo.", "TECNICO", "ralenti_caliente", "aguja_presion_cae_en_minimo", "", "", "SI", "NO", "", "L1 caída de manómetro de tablero en caliente.")
    agregar("G10-L1-07", CLASE_10, "L1", "En frío no suena nada, pero cuando calienta empieza a sonar un golpeteo de válvulas.", "COTIDIANO", "motor_caliente", "golpeteo_valvulas_en_caliente", "", "", "SI", "NO", "", "L1 ruido térmico por pérdida de viscosidad/presión.")
    agregar("G10-L1-08", CLASE_10, "L1", "Se me prendió la aceitera roja y pita la alarma del tablero.", "WHATSAPP", "marcha", "testigo_rojo_aceite|alarma_acustica", "", "", "SI", "NO", "", "L1 alarma crítica de baja presión.")
    agregar("G10-L1-09", CLASE_10, "L1", "Acelerando se apaga la luz del aceite, pero al soltar el pedal vuelve a prender.", "COTIDIANO", "ralenti_vs_aceleracion", "luz_aceite_apaga_al_acelerar", "", "", "SI", "NO", "", "L1 luz dependiente de rpm.")
    agregar("G10-L1-10", CLASE_10, "L1", "Parpadea el testigo de precion de aseite al frenar en las esquinas.", "ERROR_ORTOGRAFICO", "frenado_ralenti", "testigo_aceite_parpadea_frenar", "", "", "SI", "NO", "", "L1 parpadeo en esquinas con error ortográfico.")

    # --- L2 (15 casos) ---
    agregar("G10-L2-01", CLASE_10, "L2", "El testigo de aceite parpadea en rojo cuando el motor llega a temperatura de trabajo y queda en ralentí a 750 rpm, pero al acelerar a 1500 rpm se apaga de inmediato.", "TALLER", "ralenti_caliente", "testigo_aceite_ralenti_caliente|apaga_al_acelerar", "falta_aceite_varilla", "", "NO", "SI", CLASE_9, "L2 presión insuficiente en ralentí vs consumo de aceite.")
    agregar("G10-L2-02", CLASE_10, "L2", "La varilla marca el nivel de aceite en el punto máximo, pero en caliente suena un cascabeleo de botadores en la culata y titila la luz de lubricación.", "COTIDIANO", "motor_caliente", "nivel_maximo_varilla|ruido_botadores|luz_lubricacion_titila", "nivel_bajo_aceite", "", "NO", "SI", CLASE_9, "L2 nivel lleno con ruido de botadores descarta consumo.")
    agregar("G10-L2-03", CLASE_10, "L2", "En frío la presión de aceite sube normal a 40 psi, pero tras 20 minutos de marcha cae a 6 psi en mínimo y los taqués empiezan a sonar fuerte.", "TECNICO", "transicion_caliente", "presion_cae_40_a_6psi|taques_ruidosos_caliente", "ruido_en_frio", "", "NO", "NO", "", "L2 degradación de presión con la temperatura.")
    agregar("G10-L2-04", CLASE_10, "L2", "Hola maestro, cuando me detengo en los semáforos pita la aceitera roja. Ya le cambié el aceite y filtro nuevo ayer pero sigue haciendo lo mismo.", "WHATSAPP", "ralenti_semaforo", "alarma_aceite_semaforo|persiste_post_mantenimiento", "filtro_aceite_tapado", "", "NO", "NO", "", "L2 persistencia tras cambio de aceite y filtro.")
    agregar("G10-L2-05", CLASE_10, "L2", "Al calentar el motor se escucha un golpeteo metálico en la parte alta y el manómetro marca apenas 8 psi en ralentí, sin que el carro bote humo azul.", "COTIDIANO", "motor_caliente", "golpeteo_metalico_alta|presion_8psi_ralenti", "humo_azul", "", "NO", "SI", CLASE_9, "L2 presión 8 psi sin humo azul descarta aros.")
    agregar("G10-L2-06", CLASE_10, "L2", "La luz de aceite se queda encendida fija por diez segundos después del arranque en frío acompañada de un traqueteo seco hasta que carga la bomba.", "TALLER", "arranque_frio", "retraso_presion_10seg|traqueteo_seco_arranque", "falla_motor_arranque", "", "NO", "NO", "", "L2 descarga de circuito / válvula antirretorno de bomba.")
    agregar("G10-L2-07", CLASE_10, "L2", "Acelerando en carretera no molesta, pero al bajar a ralentí en el peaje parpadea la luz de aceite. El nivel está perfecto y el aceite no tiene olor a gasolina.", "COTIDIANO", "parada_peaje", "luz_aceite_en_peaje|apaga_en_carretera", "aceite_diluido_gasolina", "", "NO", "NO", "", "L2 presión cae solo a bajas rpm con aceite sin dilución.")
    agregar("G10-L2-08", CLASE_10, "L2", "Escáner reporta código P0524 por presión de aceite de motor demasiado baja. El bulbo de presión es nuevo y el cárter tiene su aceite 5W-30 completo.", "TECNICO", "ralenti", "dtc_p0524|bulbo_nuevo_persiste_falla", "sensor_presion_defectuoso", "P0524", "NO", "NO", "", "L2 código P0524 con bulbo nuevo comprobado.")
    agregar("G10-L2-09", CLASE_10, "L2", "El motor suena como matraca arriba cuando calienta y parpadea el foco de aceite. La varilla marca lleno pero el chupador del carter parece tapado.", "ERROR_ORTOGRAFICO", "motor_caliente", "sonido_matraca_arriba|foco_aceite_parpadea", "nivel_aceite_bajo", "", "NO", "SI", CLASE_9, "L2 sospecha de coladera tapada con nivel lleno y error ortográfico.")
    agregar("G10-L2-10", CLASE_10, "L2", "El testigo de presión de aceite titila al frenar bruscamente o doblar esquinas cerradas, indicando baja presión transitoria en ralentí.", "COTIDIANO", "frenada_giro", "testigo_titila_frenada_giro", "perdida_frenos", "", "NO", "NO", "", "L2 pérdida momentánea de cebado en coladera/cárter.")
    agregar("G10-L2-11", CLASE_10, "L2", "Buenas, el carro tiene el aceite recién cambiado pero en las subidas lentas se prende la aceitera y suenan los botadores hidráulicos.", "WHATSAPP", "subida_lenta", "aceitera_prendida_subida|ruido_botadores", "aceite_viejo", "", "NO", "NO", "", "L2 botadores ruidosos en baja rotación con aceite nuevo.")
    agregar("G10-L2-12", CLASE_10, "L2", "Presión en galería principal no supera 12 psi a 2500 rpm con motor a 90°C, cuando el manual especifica un mínimo de 35 psi.", "TECNICO", "2500rpm_caliente", "presion_12psi_a_2500rpm_deficiente", "presion_especificada_35psi", "", "NO", "NO", "", "L2 presión muy deficiente bajo régimen acelerado.")
    agregar("G10-L2-13", CLASE_10, "L2", "Los taqués hidráulicos suenan constante cla-cla-cla en ralentí caliente y la luz de aceite titila. Si acelero a 2000 rpm el ruido desaparece.", "TALLER", "ralenti_vs_2000rpm", "ruido_taques_en_ralenti|desaparece_a_2000rpm", "falla_mecanica_valvulas", "", "NO", "NO", "", "L2 ruido hidráulico desaparece al subir presión con rpm.")
    agregar("G10-L2-14", CLASE_10, "L2", "El testigo de presión se enciende al entrar en ralentí tras manejar en autopista. El aceite no tiene agua ni burbujas, el nivel está al máximo.", "COTIDIANO", "post_autopista_ralenti", "testigo_tras_autopista", "emulsion_agua|nivel_bajo", "", "NO", "SI", CLASE_6, "L2 post-autopista sin emulsión descarta culata.")
    agregar("G10-L2-15", CLASE_10, "L2", "Se midió presión con manómetro análogo registrando 7 psi en ralentí y 22 psi a 3000 rpm en caliente, evidenciando desgaste en engranajes de la bomba.", "TECNICO", "motor_caliente", "presion_7psi_ralenti_22psi_3000rpm", "falla_sensor", "", "NO", "NO", "", "L2 manometría analógica certifica bomba desgastada.")

    # --- L3 (15 casos) ---
    agregar("G10-L3-01", CLASE_10, "L3", "Testigo de presión de aceite parpadea en ralentí a 800 rpm tras 25 minutos de funcionamiento a 92°C de temperatura de refrigerante. El nivel en varilla está en la marca MAX con aceite 5W-30 sintético recién cambiado. Al conectar manómetro mecánico en el puerto del bulbo se registran 6.5 psi en ralentí (mínimo OEM 14 psi) y 26 psi a 3000 rpm (mínimo OEM 40 psi), con taqués sonando por despresurización.", "TECNICO", "ralenti_caliente", "testigo_aceite_800rpm|presion_6_5psi_ralenti|26psi_3000rpm|taques_despresurizados", "nivel_bajo_aceite|aceite_degradado", "P0524", "NO", "SI", CLASE_9, "L3 manómetro mecánico confirma 6.5 psi vs OEM 14 psi.")
    agregar("G10-L3-02", CLASE_10, "L3", "Al retirar el cárter tras reclamo de testigo de aceite intermitente en semáforos, se encontró la malla de la coladera de succión (chupador) obstruida en un 70% por restos de silicona de juntas y carbón solidificado. La varilla marcaba nivel lleno y no existía consumo de aceite entre cambios.", "TALLER", "inspeccion_carter", "chupador_obstruido_70_silicona|testigo_intermitente_ralenti", "consumo_aceite", "", "NO", "SI", CLASE_9, "L3 coladera de succión tapada con nivel lleno descarta consumo.")
    agregar("G10-L3-03", CLASE_10, "L3", "Escáner registra DTC P0524 permanente. Con el motor a 90°C el interruptor de presión de aceite conmuta a masa por debajo de 8 psi activando la advertencia del cuadro. Al medir con manómetro calibrado la presión no levanta de 8 psi a 900 rpm. El aceite no tiene contaminación de combustible ni refrigerante.", "TECNICO", "temperatura_operacion", "dtc_p0524|conmutacion_a_masa_8psi|presion_8psi_medida", "contaminacion_combustible|emulsion", "P0524", "NO", "SI", CLASE_6, "L3 DTC P0524 con confirmación de manómetro calibrado.")
    agregar("G10-L3-04", CLASE_10, "L3", "El cliente ingresa por golpeteo metálico de taqués en la culata que aparece exclusivamente cuando el motor calienta tras 15 minutos en tráfico. En frío la presión marca 45 psi pero cae drásticamente a 7 psi en caliente por juego axial excesivo en el rotor de la bomba de aceite verificado con galgas.", "TALLER", "trafico_caliente", "ruido_taques_en_caliente|presion_cae_a_7psi|juego_axial_bomba_excesivo", "ruido_en_frio", "", "NO", "NO", "", "L3 juego axial en rotor de bomba con galgas.")
    agregar("G10-L3-05", CLASE_10, "L3", "Buenas tardes maestro, la luz roja de la aceitera parpadea en mínimo pero acelero a 1500 y se apaga al toque. El nivel de aceite está en el máximo con aceite nuevo. Le midieron la presión con reloj y marca 6 libras en mínimo cuando debe tener 15. Suenan los botadores arriba.", "WHATSAPP", "ralenti_caliente", "luz_aceite_parpadea_minimo|presion_6_libras|botadores_suenan", "falta_aceite", "", "NO", "SI", CLASE_9, "L3 descripción coloquial WhatsApp con medición de 6 psi.")
    agregar("G10-L3-06", CLASE_10, "L3", "La válvula reguladora de alivio de la bomba de aceite se trabó en posición parcialmente abierta por sedimentos. Como consecuencia la presión en ralentí cae a 5 psi encendiendo la luz testigo, y a 3500 rpm no supera los 22 psi. La varilla marca nivel máximo y las bujías no presentan residuos de aceite quemado.", "TECNICO", "prueba_banco_bomba", "valvula_alivio_trabada_abierta|presion_5psi_ralenti", "humo_azul_aceite", "", "NO", "SI", CLASE_9, "L3 válvula de alivio trabada abierta con bujías limpias.")
    agregar("G10-L3-07", CLASE_10, "L3", "Ruido seco de taqués hidráulicos descargados al llegar a ralentí después de circular por autopista. El aceite tiene 1500 km de uso y nivel en línea superior. Medición mecánica confirma 8 psi en ralentí y 28 psi a 2500 rpm. Cojinetes de biela inspeccionados con plastigage arrojaron holgura excesiva de 0.075 mm.", "TALLER", "post_autopista", "taques_descargados_ralenti|holgura_cojinetes_plastigage_0_075mm", "aceite_bajo_nivel", "", "NO", "NO", "", "L3 holgura de cojinetes medida con plastigage.")
    agregar("G10-L3-08", CLASE_10, "L3", "Al encender el motor en frío la luz de presión de aceite tarda 12 segundos en apagarse produciendo traqueteo severo en la distribución. Se desarmó la bomba encontrándose la válvula de retención con resorte quebrado impidiendo retener la columna de lubricante al apagar.", "TALLER", "arranque_frio", "retraso_presion_12seg_arranque|resorte_valvula_retencion_roto", "baja_presion_en_caliente", "", "NO", "NO", "", "L3 resorte de válvula de retención quebrado.")
    agregar("G10-L3-09", CLASE_10, "L3", "El testigo de aceite prende al parar en semaforos en caliente. El bulbo de precion es nuevo y la varilla marca al maximo. En el taller conectaron manometro mecanico y marco 7 psi en ralenti sonando los taques por falta de presion en la culata.", "ERROR_ORTOGRAFICO", "semaforo_caliente", "testigo_aceite_parpadea_caliente|manometro_7psi|taques_suenan", "sensor_averiado|falta_aceite", "", "NO", "SI", CLASE_9, "L3 manómetro 7 psi con sensor nuevo y error ortográfico.")
    agregar("G10-L3-10", CLASE_10, "L3", "DTC P0520 y P0524 activos simultáneamente en módulo PCM. Con el motor a temperatura de régimen (94°C), el sensor digital reporta 7 psi a 780 rpm. El circuito eléctrico del sensor arrojó 5.0V de referencia y masa perfecta, confirmando que la caída de presión es mecánica e hidráulica real.", "TECNICO", "temperatura_regimen", "dtc_p0520_p0524|sensor_digital_7psi|circuito_electrico_conforme", "falla_arnes_sensor", "P0524", "NO", "NO", "", "L3 verificación eléctrica descarta arnés y confirma caída hidráulica.")
    agregar("G10-L3-11", CLASE_10, "L3", "El vehículo enciende el testigo de presión de aceite y la campana sonora tras 20 minutos de recorrido urbano. Se drenó el aceite encontrándose limpio y sin olor a combustible. El engranaje motriz de la bomba de aceite presenta desgaste por picaduras en los dientes.", "TALLER", "recorrido_urbano", "testigo_alarma_20min|engranajes_bomba_picados", "aceite_contaminado", "", "NO", "NO", "", "L3 engranajes de bomba picados con aceite limpio.")
    agregar("G10-L3-12", CLASE_10, "L3", "Presión de aceite en caliente no supera los 10 psi en ralentí y la culata emite ruido de taqués secos. El motor no gasta aceite ni echa humo azul por el escape. Al desmontar la bomba se encontró el cuerpo de aluminio con rayaduras profundas por limalla previa.", "TALLER", "motor_caliente", "cuerpo_bomba_rayado_aluminio|presion_10psi_ralenti", "consumo_aceite|humo_azul", "", "NO", "SI", CLASE_9, "L3 cuerpo de bomba rayado sin consumo de aceite.")
    agregar("G10-L3-13", CLASE_10, "L3", "Luz de lubricación parpadea a 800 rpm en detenciones con motor caliente. Se colocó manómetro en serie con el bulbo registrando 5.5 psi en caliente. Al subir las revoluciones a 2000 rpm la presión solo alcanza 20 psi (especificación 38 psi). Nivel de aceite en la marca superior con filtro de aceite original.", "TECNICO", "detencion_caliente", "presion_5_5psi_800rpm|20psi_2000rpm_deficiente", "filtro_no_original|nivel_bajo", "", "NO", "SI", CLASE_9, "L3 curva de presión insuficiente en 800 y 2000 rpm.")
    agregar("G10-L3-14", CLASE_10, "L3", "Hola, me prende la luz de la aceitera cuando freno y el carro queda regulando. Si piso el acelerador un poquito se apaga de una. Ya le medí el aceite y está lleno. El mecánico midió con reloj y tiene 7 psi en caliente, dice que la bomba perdió fuerza.", "WHATSAPP", "regulando", "luz_aceite_prende_regulando|apaga_al_acelerar|7psi_reloj", "nivel_bajo", "", "NO", "SI", CLASE_9, "L3 relato WhatsApp directo con 7 psi en manómetro.")
    agregar("G10-L3-15", CLASE_10, "L3", "Falla de baja presión en caliente con manómetro registrando 6 psi en ralentí. Se inspeccionó el tubo de succión de aceite encontrándose la junta tórica (O-ring) cuarteada y succionando aire hacia la bomba, provocando emulsión de microburbujas y pérdida de cebado sin registrar códigos de motor.", "TECNICO", "inspeccion_tubo_succion", "oring_tubo_succion_cuarteado|perdida_cebado_microburbujas", "desgaste_anillos", "", "NO", "SI", CLASE_9, "L3 junta tórica de chupador cuarteada genera cavitación.")

    return casos

def main():
    casos = generar_datos_lote02()
    print(f"Total registros generados: {len(casos)}")
    
    # Guardar en CSV
    out_file = Path("dataset_fase10_lote_02.csv")
    cols = [
        "id", "id_grupo", "clase_objetivo", "macro_sistema", "nivel_informacion",
        "texto_usuario", "tipo_lenguaje", "condicion_operacion", "sintomas_presentes",
        "sintomas_negados", "dtc", "requiere_pregunta", "es_contrastivo",
        "clase_contrastiva", "fuente", "observaciones"
    ]
    
    with open(out_file, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=cols)
        writer.writeheader()
        writer.writerows(casos)
        
    print(f"[OK] Archivo {out_file} guardado exitosamente con {len(casos)} registros.")

if __name__ == "__main__":
    main()
