"""
Generador y Validador del Lote 03 de Fase 10 para CarBot.
Genera exactamente 200 registros de alta fidelidad automotriz para las Clases 11 a 15:
- Clase 11: Faja o cadena de distribucion destensada o con salto de punto
- Clase 12: Falla en sistema de sincronizacion variable de valvulas (VVT / VVT-i / Valvetronic)
- Clase 13: Falla de descarbonizacion e inyeccion directa GDI (acumulacion de carbon en valvulas)
- Clase 14: Falla en actuador de turbocompresor o VGT en motores alemanes TSI / TFSI
- Clase 15: Fuga en mangueras de intercooler o turbocompresor danado

Estructura: 40 por clase (10 L1, 15 L2, 15 L3) = 200 registros.
"""

import csv
import re
import sys
from pathlib import Path
import pandas as pd

# Importar validaciones canónicas
sys.path.insert(0, str(Path("backend").resolve()))
from src.core.diagnostico.taxonomia_sistemas import FALLA_A_SISTEMA

CLASE_11 = "Faja o cadena de distribucion destensada o con salto de punto"
CLASE_12 = "Falla en sistema de sincronizacion variable de valvulas (VVT / VVT-i / Valvetronic)"
CLASE_13 = "Falla de descarbonizacion e inyeccion directa GDI (acumulacion de carbon en valvulas)"
CLASE_14 = "Falla en actuador de turbocompresor o VGT en motores alemanes TSI / TFSI"
CLASE_15 = "Fuga en mangueras de intercooler o turbocompresor danado"

def generar_datos_lote03():
    casos = []
    idx = 1

    def agregar(id_grupo, clase, nivel, texto, tipo_lenguaje, cond, sint_pres, sint_neg, dtc, req_preg, es_cont, cl_cont, obs):
        nonlocal idx
        reg_id = f"F10-L03-{idx:04d}"
        idx += 1
        casos.append({
            "id": reg_id,
            "id_grupo": id_grupo,
            "clase_objetivo": clase,
            "macro_sistema": "MOTOR",
            "nivel_informacion": nivel,
            "texto_usuario": texto.strip(),
            "tipo_lenguaje": tipo_lenguaje,
            "condicion_operacion": cond.strip(),
            "sintomas_presentes": sint_pres.strip(),
            "sintomas_negados": sint_neg.strip(),
            "dtc": dtc.strip(),
            "requiere_pregunta": req_preg.strip(),
            "es_contrastivo": es_cont.strip(),
            "clase_contrastiva": cl_cont.strip(),
            "fuente": "SINTETICO_IA",
            "observaciones": obs.strip()
        })

    # =========================================================================
    # CLASE 11: Faja o cadena de distribucion destensada o con salto de punto (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G11-L1-01", CLASE_11, "L1", "Se escucha un cascabeleo metálico por el lado de las correas al encender.", "COTIDIANO", "arranque_frio", "cascabeleo_metalico_correas", "", "", "SI", "NO", "", "L1 ruido metálico inicial en tapa de distribución.")
    agregar("G11-L1-02", CLASE_11, "L1", "Hola, el carro arranca pesado y no tiene nada de fuerza al salir.", "WHATSAPP", "arranque", "arranque_pesado|falta_potencia", "", "", "SI", "NO", "", "L1 motor pesado sin empuje.")
    agregar("G11-L1-03", CLASE_11, "L1", "Siento un ruido de sonajero de latas en la parte delantera del motor.", "COTIDIANO", "ralenti", "ruido_sonajero_delantero", "", "", "SI", "NO", "", "L1 ruido de sonajero de cadena floja.")
    agregar("G11-L1-04", CLASE_11, "L1", "El motor perdió sincronía y tiembla en ralentí después de una acelerada fuerte.", "TALLER", "post_aceleracion", "perdida_sincronia|temblor_ralenti", "", "", "SI", "NO", "", "L1 salto de sincronía tras estirada de marcha.")
    agregar("G11-L1-05", CLASE_11, "L1", "Tiene un traqueteo seco que dura unos tres segundos al arrancar por las mañanas.", "COTIDIANO", "arranque_manana", "traqueteo_3seg_arranque", "", "", "SI", "NO", "", "L1 traqueteo inicial por tensor hidráulico descargado.")
    agregar("G11-L1-06", CLASE_11, "L1", "El auto hace explosiones raras por la admisión cuando intento acelerar.", "TALLER", "aceleracion", "explosiones_admision", "", "", "SI", "NO", "", "L1 contraexplosión en admisión por desfase de levas.")
    agregar("G11-L1-07", CLASE_11, "L1", "Salió un zumbido y chillido raro dentro de las tapas plásticas del motor.", "WHATSAPP", "ralenti", "zumbido_tapas_motor", "", "", "SI", "NO", "", "L1 faja destensada rozando tapa.")
    agregar("G11-L1-08", CLASE_11, "L1", "El carro se apago de golpe al reducir cambio y ahora gira como si no tuviera compresion.", "ERROR_ORTOGRAFICO", "reduccion_cambio", "apagado_brusco|giro_sin_compresion", "", "", "SI", "NO", "", "L1 salto de faja en retención con error ortográfico.")
    agregar("G11-L1-09", CLASE_11, "L1", "Siento que el punto del motor se movió porque el escape suena disparejo.", "COTIDIANO", "ralenti", "escape_disparejo|sospecha_punto", "", "", "SI", "NO", "", "L1 sospecha empírica de desfase.")
    agregar("G11-L1-10", CLASE_11, "L1", "Discrepancia angular constante entre cigüeñal y árbol de levas detectada en marcha.", "TECNICO", "marcha", "discrepancia_angular_ckp_cmp", "", "", "SI", "NO", "", "L1 descripción técnica de desfase de sincronización.")

    # --- L2 (15 casos) ---
    agregar("G11-L2-01", CLASE_11, "L2", "La cadena suena como matraca suelta durante 5 segundos en el arranque en frío y luego se calma, pero al acelerar a 2500 rpm vuelve a raspar la tapa.", "COTIDIANO", "arranque_y_aceleracion", "sonido_matraca_arranque|roce_tapa_2500rpm", "falla_chispa", "", "NO", "SI", CLASE_12, "L2 cadena floja con tensor descargado vs VVT.")
    agregar("G11-L2-02", CLASE_11, "L2", "El motor perdió bastante fuerza en subida y al acelerar suena un chicotazo en la distribución; el punto parece haberse corrido un diente.", "TALLER", "subida", "perdida_fuerza_subida|chicotazo_distribucion", "falla_embrague", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L2 salto de un diente en subida vs embrague.")
    agregar("G11-L2-03", CLASE_11, "L2", "Al dar arranque el motor gira demasiado liviano y rápido sin encender tras haber sentido un golpe seco en la faja al desacelerar.", "TALLER", "arranque", "giro_liviano_sin_encender|golpe_faja_previo", "falla_bateria", "", "NO", "NO", "", "L2 rotura o pérdida de dientes en faja de distribución.")
    agregar("G11-L2-04", CLASE_11, "L2", "Check Engine encendido permanente con correlación CKP-CMP desfasada; el auto arranca con dificultad y el ralentí quedó inestable en todo momento.", "TECNICO", "ralenti", "dtc_correlacion_ckp_cmp|arranque_dificil|ralenti_inestable", "falla_inyector", "P0016", "NO", "SI", CLASE_12, "L2 código P0016 por desfase mecánico vs variador VVT.")
    agregar("G11-L2-05", CLASE_11, "L2", "Hola, siento un traqueteo metálico constante en la tapa de distribución que aumenta con las revoluciones y el carro perdió reprise.", "WHATSAPP", "aceleracion", "traqueteo_tapa_distribucion|falta_reprise", "ruido_caja", "", "NO", "NO", "", "L2 cadena estirada con roce constante en guías.")
    agregar("G11-L2-06", CLASE_11, "L2", "El auto produce pequeñas explosiones por el múltiple de admisión al pisar el acelerador en vacío, síntoma de válvulas desincronizadas por faja corrida.", "TALLER", "aceleracion_vacio", "explosiones_admision|valvulas_desincronizadas", "falla_bujias", "", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L2 salto de faja genera retornos de llama en admisión.")
    agregar("G11-L2-07", CLASE_11, "L2", "Al verificar con la lámpara estroboscópica la marca de la polea del cigüeñal no coincide con el cero de la tapa, estando atrasado 10 grados en reposo.", "TECNICO", "inspeccion_taller", "marca_ciguenal_atrasada_10_grados", "falla_sensor_ckp", "", "NO", "NO", "", "L2 comprobación óptica de desfase mecánico.")
    agregar("G11-L2-08", CLASE_11, "L2", "El motor vibra en mínimo y no desarrolla velocidad en autopista; la cadena de tiempo tiene holgura excesiva y golpea el patín guía superior.", "COTIDIANO", "autopista", "vibracion_minimo|golpe_patin_guia|falta_velocidad", "falla_bobina", "", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L2 cadena golpeando patines guía vs encendido.")
    agregar("G11-L2-09", CLASE_11, "L2", "Se siente un sonido a latas feo en la distribucion al arrancar en la mañana y el carro esta chancheado en salida.", "ERROR_ORTOGRAFICO", "arranque_manana", "sonido_latas_distribucion|carro_chancheado", "falla_frenos", "", "NO", "NO", "", "L2 cadena sonando en frío con pérdida de salida.")
    agregar("G11-L2-10", CLASE_11, "L2", "Tensión de la correa de distribución por debajo de especificación con deflexión de más de 20 mm entre piñones de leva, causando marcha áspera.", "TECNICO", "inspeccion_correa", "deflexion_correa_20mm|marcha_aspera", "falla_soportes_motor", "", "NO", "NO", "", "L2 deflexión física excesiva de correa.")
    agregar("G11-L2-11", CLASE_11, "L2", "Buenas, el carro se tironea feo y tiene un cascabeleo en la tapa frontal que no se quita ni acelerando. Ya cambié bujías y sigue igual.", "WHATSAPP", "marcha", "cascabeleo_tapa_frontal|tironeo_persistente", "falla_bujias_resuelto", "", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L2 persistencia tras cambio de bujías descarta encendido.")
    agregar("G11-L2-12", CLASE_11, "L2", "El motor arrancaba bien pero al hacer un rebaje brusco en bajada se sintió un crujido y quedó fallando como fuera de tiempo en todos los cilindros.", "COTIDIANO", "post_rebaje", "fallo_general_fuera_tiempo|crujido_previo", "falla_embrague", "", "NO", "NO", "", "L2 salto de punto inducido por rebaje brusco.")
    agregar("G11-L2-13", CLASE_11, "L2", "Ruido de golpeteo metálico en la carcasa de distribución en caliente; el tensor hidráulico perdió el trinquete y la cadena salta holgada.", "TALLER", "motor_caliente", "trinquete_tensor_roto|cadena_salta_holgada", "bomba_agua_ruidosa", "", "NO", "NO", "", "L2 rotura del trinquete de bloqueo del tensor.")
    agregar("G11-L2-14", CLASE_11, "L2", "Desfase fijo entre eje de levas y cigüeñal que no se corrige al acelerar, con pérdida de compresión uniforme en los 4 cilindros por apertura prematura.", "TECNICO", "prueba_compresion", "desfase_fijo_ckp_cmp|compresion_uniforme_baja", "perdida_compresion_cilindro_aislado", "", "NO", "SI", "Perdida de compresion en cilindro por valvulas pisadas o anillos desgastados", "L2 compresión baja homogénea por cruce valvular desfasado.")
    agregar("G11-L2-15", CLASE_11, "L2", "El auto arranca con dificultad demorando 5 segundos de marcha y suena un rastro metálico áspero detrás de la polea del dámper.", "COTIDIANO", "arranque", "arranque_largo_5seg|roce_detras_damper", "falla_motor_arranque", "", "NO", "SI", "Falla en motor de arranque o solenoide defectuoso (clac seco o carbones gastados)", "L2 roce en dámper vs motor de arranque.")

    # --- L3 (15 casos) ---
    agregar("G11-L3-01", CLASE_11, "L3", "Escáner reporta DTC P0016 de correlación entre sensor de cigüeñal y árbol de levas de admisión. En osciloscopio de dos canales la señal del sensor CMP se observa desplazada 22 grados respecto a los dientes del CKP de manera fija en todo el rango de revoluciones. Se inspeccionó la cadena y el tensor hidráulico se encuentra extendido al máximo sin retención.", "TECNICO", "prueba_osciloscopio", "dtc_p0016|desfase_fijo_22_grados_osciloscopio|tensor_extendido_maximo", "falla_solenoide_vvt", "P0016", "NO", "SI", CLASE_12, "L3 oscilograma dual confirma desfase fijo mecánico vs VVT.")
    agregar("G11-L3-02", CLASE_11, "L3", "Al dar arranque el motor gira liviano y a altas revoluciones sin arrancar. Al retirar la tapa plástica superior de distribución se constató que la faja perdió 14 dientes en la zona del piñón del cigüeñal por atasco de polea tensora. La prueba de compresión marcó 0 psi en los 4 cilindros por válvulas dobladas.", "TALLER", "inspeccion_distribucion", "faja_sin_14_dientes|compresion_0psi_valvulas_dobladas", "falla_motor_arranque|bateria_baja", "", "NO", "NO", "", "L3 pérdida de dientes de faja y daño valvular.")
    agregar("G11-L3-03", CLASE_11, "L3", "Sonajero metálico severo en la tapa frontal del motor durante el arranque en frío que disminuye a los 8 segundos. Se midió el desgaste de la cadena de tiempo registrando un estiramiento de 12 mm fuera de tolerancia OEM y los patines guía de teflón presentan surcos de 3 mm de profundidad con limalla en el colador.", "TALLER", "arranque_frio", "cadena_estirada_12mm|patines_surcos_3mm|limalla_colador", "ruido_bomba_aceite", "", "NO", "SI", "Baja presion de aceite o bomba de aceite defectuosa", "L3 metrología de estiramiento 12 mm en cadena.")
    agregar("G11-L3-04", CLASE_11, "L3", "El vehículo perdió potencia drásticamente tras reducir a tercera velocidad. El motor tiembla en ralentí, hace contraexplosiones por admisión y genera código P0017 en banco 1 escape. Al alinear las marcas con los útiles de bloqueo de calado, el árbol de escape quedó retrasado 2 dientes respecto al volante.", "TECNICO", "comprobacion_calado", "dtc_p0017|arbol_escape_retrasado_2_dientes|utiles_bloqueo", "falla_bobina_encendido", "P0017", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L3 verificación física con útiles de calado OEM.")
    agregar("G11-L3-05", CLASE_11, "L3", "Hola maestro, el carro arranca después de darle arranque largo y tiembla horrible. El mecánico metió escáner y sale P0016. Abrieron la tapa de la cadena y el templador hidráulico está reventado botando aceite, la cadena choca contra el fierro de la tapa.", "WHATSAPP", "arranque_dificil", "dtc_p0016|templador_reventado|cadena_choca_tapa", "falla_bomba_gasolina", "P0016", "NO", "NO", "", "L3 tensor reventado con código P0016.")
    agregar("G11-L3-06", CLASE_11, "L3", "Falla de encendido errática y pérdida de potencia general sin respuesta al acelerador. La señal del CMP presenta jitter y retraso constante respecto al punto muerto superior. Al desarmar la distribución se encontró la chaveta del piñón del cigüeñal degollada con juego angular libre de 15 grados.", "TECNICO", "inspeccion_damper", "chaveta_ciguenal_degollada|juego_angular_15_grados", "falla_sensor_ckp", "", "NO", "NO", "", "L3 chaveta del piñón de cigüeñal degollada.")
    agregar("G11-L3-07", CLASE_11, "L3", "El cliente reclama pérdida de fuerza y humo negro al acelerar. Se verificó el punto de distribución y la correa saltó un diente hacia el retraso. La presión de compresión cayó de 170 psi a 125 psi uniforme en todos los cilindros. Al reajustar el calado a sus marcas la compresión regresó a 170 psi.", "TALLER", "ajuste_calado", "correa_salto_un_diente|compresion_cayo_a_125_recupera_170", "desgaste_anillos", "", "NO", "SI", "Consumo de aceite por desgaste de anillos o retenes", "L3 salto de 1 diente recupera compresión tras calado.")
    agregar("G11-L3-08", CLASE_11, "L3", "Ruido de tableteo metálico frontal continuo. Se midió la presión de aceite encontrando 35 psi correcta pero la cadena golpea la carcasa. El tensor mecánico de trinquete se atascó en su primer diente por residuos de carbón, dejando la cadena completamente destensada en el ramal flojo.", "TALLER", "motor_en_marcha", "tensor_trinquete_atascado|cadena_ramal_flojo|presion_aceite_35psi", "falla_bomba_aceite", "", "NO", "SI", "Baja presion de aceite o bomba de aceite defectuosa", "L3 trinquete atascado con presión de aceite correcta.")
    agregar("G11-L3-09", CLASE_11, "L3", "DTC P0016 en motor 1.6 16v. El auto arranca pesado, no pasa de 80 km/h y tiene un cascabeleo en la distribucion. Se retiro la tapa y la faja perdio tres dientes consecutivos en el cigueñal estando a punto de cortarce del todo.", "ERROR_ORTOGRAFICO", "aceleracion_limitada", "dtc_p0016|faja_perdio_3_dientes|cascabeleo_distribucion", "falla_transmision", "P0016", "NO", "NO", "", "L3 dientes barridos en faja con error ortográfico.")
    agregar("G11-L3-10", CLASE_11, "L3", "Medición de avance de encendido con escáner muestra corrección máxima negativa de menos 15 grados en ralentí. El árbol de levas de admisión saltó 2 dientes por rotura de tensor secundario. Las válvulas no llegaron a colisionar con los pistones pero el cruce provoca vacío pobre de 11 inHg.", "TECNICO", "ralenti_vacio", "avance_menos_15_grados|salto_2_dientes|vacio_11inhg", "fuga_vacio_multiple", "", "NO", "SI", "Cuerpo de aceleracion o valvula IAC sucia", "L3 vacío pobre 11 inHg por desfase valvular.")
    agregar("G11-L3-11", CLASE_11, "L3", "Buenas tardes, el carro empezó a sonar como si tuviera piedras en la tapa delantera del motor. Al acelerar zumba y vibra. El mecánico revisó la cadena y el patín plástico se partió en dos pedazos cayendo pedazos al cárter.", "WHATSAPP", "ralenti_y_marcha", "patin_plastico_cadena_partido|pedazos_en_carter", "ruido_alternador", "", "NO", "NO", "", "L3 patín de teflón partido en el cárter.")
    agregar("G11-L3-12", CLASE_11, "L3", "Código P0340 y P0016. El motor arranca en modo de respaldo utilizando únicamente la señal del CKP tras 6 segundos de marcha continua. Se desmontó el frontal de la culata comprobando estiramiento de cadena del 2.5% superando el límite de servicio de 1.0%.", "TECNICO", "arranque_respaldo", "dtc_p0340_p0016|modo_respaldo_ckp|estiramiento_cadena_2_5_porciento", "falla_sensor_cmp", "P0016", "NO", "NO", "", "L3 arranque en modo de respaldo por estiramiento 2.5%.")
    agregar("G11-L3-13", CLASE_11, "L3", "El vehículo perdió potencia súbitamente en una reducción de marcha. Prueba de sincronización con barra de calado en árboles de levas demostró que la ranura trasera del árbol de admisión está desalineada 18 grados respecto al plano de culata por salto de faja dentada.", "TALLER", "inspeccion_calado", "ranura_calado_desalineada_18_grados|salto_faja_dentada", "falla_embrague", "", "NO", "NO", "", "L3 desalineación angular de ranura de calado.")
    agregar("G11-L3-14", CLASE_11, "L3", "Cascabeleo de cadena en desaceleración pronunciada. El tensor hidráulico no retiene presión en reposo por desgaste del pistón interno, provocando que la cadena golpee la tapa metálica en cada cambio de marcha. Al acelerar en vacío el sonido se agudiza.", "TALLER", "desaceleracion_y_vacio", "tensor_hidraulico_sin_retencion|golpe_cadena_tapa_cambios", "ruido_caja_cambios", "", "NO", "SI", "Rodajes de caja mecanica o diferencial gastados", "L3 tensor hidráulico sin retención vs caja de cambios.")
    agregar("G11-L3-15", CLASE_11, "L3", "Diagnóstico de desincronización mecánica: correlación de señales de sensores CKP inductivo y CMP Hall revela desfase permanente de 1.8 milisegundos a 850 rpm. El sistema VVT comanda avance pero la posición real no se mueve por cadena trabada en guías gastadas.", "TECNICO", "analisis_osciloscopio_850rpm", "desfase_1_8ms_ckp_cmp|vvt_comanda_sin_movimiento_real", "falla_actuador_vvt", "P0016", "NO", "SI", CLASE_12, "L3 desfase en milisegundos con VVT comandado al límite.")

    # =========================================================================
    # CLASE 12: Falla en sistema de sincronizacion variable de valvulas (VVT / VVT-i / Valvetronic) (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G12-L1-01", CLASE_12, "L1", "El carro se pone perezoso para acelerar cuando el motor calienta.", "COTIDIANO", "motor_caliente", "motor_perezoso_caliente", "", "", "SI", "NO", "", "L1 pérdida de agilidad térmica.")
    agregar("G12-L1-02", CLASE_12, "L1", "Se encendió el Check Engine y siento un cascabeleo al pasar las 2500 revoluciones.", "COTIDIANO", "media_alta_rpm", "check_engine|cascabeleo_2500rpm", "", "", "SI", "NO", "", "L1 ruido al acoplar distribución variable.")
    agregar("G12-L1-03", CLASE_12, "L1", "Hola, el motor pierde potencia en alta y gasta bastante combustible.", "WHATSAPP", "alta_rpm", "perdida_potencia_alta|consumo_alto", "", "", "SI", "NO", "", "L1 falta de avance en altas revoluciones.")
    agregar("G12-L1-04", CLASE_12, "L1", "El ralentí se vuelve inestable solo cuando el motor llega a su temperatura normal.", "TALLER", "ralenti_caliente", "ralenti_inestable_caliente", "", "", "SI", "NO", "", "L1 inestabilidad en ralentí caliente.")
    agregar("G12-L1-05", CLASE_12, "L1", "Siento como un tironcito suave cuando el carro debería pegar el estirón de potencia.", "COTIDIANO", "aceleracion_media", "tiron_transicion_potencia", "", "", "SI", "NO", "", "L1 falla en cruce de válvulas.")
    agregar("G12-L1-06", CLASE_12, "L1", "Aparece un sonido de claqueteo en el piñón de la leva al desacelerar.", "TALLER", "desaceleracion", "claqueteo_pinon_leva", "", "", "SI", "NO", "", "L1 ruido de piñón desfasador.")
    agregar("G12-L1-07", CLASE_12, "L1", "El escáner me arrojó falla en la sincronización del árbol de levas.", "TECNICO", "diagnostico", "falla_sincronizacion_arbol_levas", "", "", "SI", "NO", "", "L1 reporte genérico de árbol de levas.")
    agregar("G12-L1-08", CLASE_12, "L1", "Mi auto no tiene fuerza arriba y el testigo del motor parpadea cuando lo apuro.", "ERROR_ORTOGRAFICO", "aceleracion_fuerte", "falta_fuerza_alta|testigo_parpadea", "", "", "SI", "NO", "", "L1 falta de potencia en alta con error ortográfico.")
    agregar("G12-L1-09", CLASE_12, "L1", "Buenas, el carro tiembla en mínimo pero en carretera corre suave.", "WHATSAPP", "ralenti_vs_carretera", "tiembla_minimo|corre_suave_carretera", "", "", "SI", "NO", "", "L1 inestabilidad en mínimo con crucero normal.")
    agregar("G12-L1-10", CLASE_12, "L1", "Desviación intermitente del ángulo del variador de levas con retraso de respuesta.", "TECNICO", "marcha", "desviacion_angulo_variador_levas", "", "", "SI", "NO", "", "L1 técnico de retardo en variador.")

    # --- L2 (15 casos) ---
    agregar("G12-L2-01", CLASE_12, "L2", "El motor funciona perfecto en frío, pero al calentar y llegar a un semáforo el ralentí oscila entre 500 y 900 rpm y suena un traqueteo en el solenoide VVT.", "COTIDIANO", "ralenti_caliente", "ralenti_oscilante_caliente|traqueteo_solenoide_vvt", "falla_en_frio", "", "NO", "SI", "Cuerpo de aceleracion o valvula IAC sucia", "L2 VVT atascado en caliente vs IAC.")
    agregar("G12-L2-02", CLASE_12, "L2", "Código P0011 de sincronización avanzada en banco 1; el carro pierde agilidad arriba de 3000 rpm y el solenoide de levas tiene lodo de aceite pegado.", "TALLER", "alta_rpm", "dtc_p0011|solenoide_vvt_con_lodo|perdida_potencia_alta", "cadena_suelta", "P0011", "NO", "SI", CLASE_11, "L2 código P0011 con solenoide sucio vs cadena.")
    agregar("G12-L2-03", CLASE_12, "L2", "Al pisar a fondo el auto no da el segundo empuje de aceleración y se siente amarrado, consumiendo un 20 por ciento más de gasolina en autopista.", "COTIDIANO", "aceleracion_fondo", "falta_empuje_vvt|consumo_elevado", "humo_negro", "", "NO", "SI", "Inyectores sucios o filtro de combustible obstruido", "L2 falta de avance de levas en alta vs inyección.")
    agregar("G12-L2-04", CLASE_12, "L2", "El piñón de sincronización variable suena tac-tac-tac fuerte al soltar el pedal del acelerador por pérdida de presión hidráulica interna del engranaje.", "TALLER", "desaceleracion", "pinon_vvt_suena_tac_tac|perdida_presion_interna", "biela_golpeando", "", "NO", "SI", "Baja presion de aceite o bomba de aceite defectuosa", "L2 ruido de piñón desfasador vs cojinete de biela.")
    agregar("G12-L2-05", CLASE_12, "L2", "Hola maestro, el escáner bota P0012 por árbol de levas retrasado. La cadena de tiempo está tensa y en sus marcas pero la válvula de aceite del VVT no conmuta.", "WHATSAPP", "diagnostico", "dtc_p0012|cadena_tensa_en_marcas|valvula_vvt_no_conmuta", "cadena_fuera_punto", "P0012", "NO", "SI", CLASE_11, "L2 marcas de distribución OK descartan cadena saltada.")
    agregar("G12-L2-06", CLASE_12, "L2", "En subidas largas el motor se queda sin avance de válvulas encendiendo el check con DTC P0014, desapareciendo el tironeo cuando se baja a ralentí.", "TECNICO", "subida_sostenida", "dtc_p0014|sin_avance_valvulas|desaparece_en_ralenti", "misfire_cilindro", "P0014", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L2 VVT escape P0014 bajo esfuerzo vs misfire.")
    agregar("G12-L2-07", CLASE_12, "L2", "El microfiltro de malla del solenoide VVT ubicado en la culata estaba completamente tapado de sedimentos de aceite viejo, bloqueando el avance.", "TALLER", "inspeccion_filtro_vvt", "filtro_vvt_malla_tapado|bloqueo_avance", "falla_electrica_arnes", "", "NO", "NO", "", "L2 coladera de solenoide VVT tupida.")
    agregar("G12-L2-08", CLASE_12, "L2", "El carro calienta normal pero tiembla en parado y tira codigo P0011. El aceite tiene su nivel pero es un 20W-50 grueso que no deja cargar al variador.", "ERROR_ORTOGRAFICO", "ralenti_caliente", "dtc_p0011|aceite_muy_grueso_bloquea_vvt", "nivel_bajo_aceite", "P0011", "NO", "SI", "Baja presion de aceite o bomba de aceite defectuosa", "L2 viscosidad inadecuada bloquea sistema VVT con ortografía informal.")
    agregar("G12-L2-09", CLASE_12, "L2", "Sistema Valvetronic entra en modo degradado de emergencia limitando la velocidad a 60 km/h; el motor eléctrico de la excéntrica tiene resistencia elevada.", "TECNICO", "modo_emergencia", "valvetronic_modo_degradado|motor_excentrica_resistencia_alta", "falla_pedal_acelerador", "", "NO", "NO", "", "L2 Valvetronic en modo de emergencia.")
    agregar("G12-L2-10", CLASE_12, "L2", "Al desacelerar tras rodar a 80 km/h el motor casi se apaga y cabecea bruscamente porque el árbol de levas se queda pegado en posición avanzada.", "COTIDIANO", "desaceleracion_brusca", "cabeceo_al_desacelerar|arbol_pegado_en_avance", "falla_freno_motor", "", "NO", "SI", "Cuerpo de aceleracion o valvula IAC sucia", "L2 retorno lento de avance VVT causa ahogo al frenar.")
    agregar("G12-L2-11", CLASE_12, "L2", "Buenas, cambié de aceite a uno sintético limpio y ahora la aguja de potencia sube con vacíos arriba de 3500 rpm con la luz de motor prendida.", "WHATSAPP", "alta_rpm", "vacios_potencia_3500rpm|testigo_motor", "falla_embrague", "", "NO", "NO", "", "L2 desfasador VVT no sostiene presión tras cambio de fluido.")
    agregar("G12-L2-12", CLASE_12, "L2", "El actuador del árbol de levas presenta juego radial interno y fugas de presión de aceite por el retén frontal, provocando golpeteo al regular.", "TALLER", "ralenti", "juego_radial_actuador_vvt|fuga_presion_reten", "golpeteo_valvulas", "", "NO", "NO", "", "L2 desgaste interno de piñón variador.")
    agregar("G12-L2-13", CLASE_12, "L2", "Se midió la resistencia del solenoide VVT arrojando 45 ohms cuando la especificación OEM es de 7 a 12 ohms, indicando bobinado recalentado.", "TECNICO", "prueba_electrica", "resistencia_vvt_45_ohms_fuera_rango", "falla_computadora", "", "NO", "NO", "", "L2 solenoide VVT degradado eléctricamente.")
    agregar("G12-L2-14", CLASE_12, "L2", "El auto pierde pique en pendientes pronunciadas donde antes trepaba en cuarta; la computadora no logra modificar el cruce de válvulas en demanda de carga.", "COTIDIANO", "subida_carga", "falta_pique_subida|sin_modificacion_cruce_valvulas", "falla_bomba_gasolina", "", "NO", "SI", "Bomba de gasolina quemada o con baja presion", "L2 falta de avance variable en pendiente vs bomba de gasolina.")
    agregar("G12-L2-15", CLASE_12, "L2", "Ralentí muy inestable solo con motor caliente acompañado de DTC P0011; al desconectar la ficha eléctrica del solenoide VVT el motor empareja de inmediato.", "TALLER", "desconexion_prueba", "dtc_p0011|desconexion_vvt_empareja_motor", "falla_bujia", "P0011", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L2 prueba de desconexión directa descarta misfire.")

    # --- L3 (15 casos) ---
    agregar("G12-L3-01", CLASE_12, "L3", "Escáner en datos en vivo grafica 'Desired Camshaft Position' en 35 grados de avance a 3200 rpm mientras que 'Actual Camshaft Position' se queda estancado en 4 grados. Se registra DTC P0011 permanente. La presión de aceite de motor está en 45 psi correcta y la cadena de tiempo está perfectamente calada, comprobándose solenoide OCV trabado por carbón.", "TECNICO", "datos_en_vivo_3200rpm", "dtc_p0011|desired_35_actual_4_grados|solenoide_ocv_trabado", "cadena_saltada|baja_presion_aceite", "P0011", "NO", "SI", CLASE_11, "L3 telemetría de Target vs Actual en escáner descarta cadena.")
    agregar("G12-L3-02", CLASE_12, "L3", "El vehículo presenta ralentí inestable y cabeceo severo al detenerse tras 20 minutos de autopista con código P0012. Al desmontar la válvula de control de aceite VVT se halló el émbolo interno agarrotado por barniz de aceite degradado. Al suministrar 12V directos en banco de prueba el actuador no se desplaza ni emite clic.", "TALLER", "banco_prueba_vvt", "dtc_p0012|embolo_ocv_agarrotado_barniz|sin_desplazamiento_12v", "falla_iac", "P0012", "NO", "SI", "Cuerpo de aceleracion o valvula IAC sucia", "L3 prueba en banco de válvula OCV atascada.")
    agregar("G12-L3-03", CLASE_12, "L3", "En aceleración plena por encima de 4000 rpm el motor pierde rendimiento y emite DTC P0014 en levas de escape. Al medir con osciloscopio la señal PWM de control proveniente de la ECU tiene ciclo de trabajo del 80%, pero el árbol de levas responde con 600 milisegundos de retraso por desgaste interno en las paletas del piñón variador.", "TECNICO", "alta_rotacion_4000rpm", "dtc_p0014|pwm_80_porciento|retraso_600ms_paletas_pinon", "falla_computadora", "P0014", "NO", "NO", "", "L3 retardo de 600 ms por fuga en paletas de piñón desfasador.")
    agregar("G12-L3-04", CLASE_12, "L3", "Traqueteo metálico tipo cascabeleo al desacelerar de 3000 a 1000 rpm en caliente. Se desmontó el engranaje del variador VVT de admisión encontrándose el pasador de bloqueo interno desgastado y con holgura en su alojamiento, impidiendo que el engranaje enganche en posición cero al caer las revoluciones.", "TALLER", "desaceleracion", "pasador_bloqueo_vvt_desgastado|cascabeleo_al_desacelerar", "ruido_cadena_distribucion", "", "NO", "SI", CLASE_11, "L3 pasador de traba de engranaje VVT con holgura.")
    agregar("G12-L3-05", CLASE_12, "L3", "Hola maestro, el auto pierde fuerza arriba y prende el check con código P0016. Se revisaron las marcas mecánicas de calado con regla de fábrica y están exactas al milímetro. Lo que fallaba era el piñón de levas VVT que se trabó internamente y no gira sobre su eje.", "WHATSAPP", "diagnostico_calado", "dtc_p0016|marcas_calado_exactas|pinon_vvt_trabado_eje", "cadena_estirada", "P0016", "NO", "SI", CLASE_11, "L3 calado perfecto descarta cadena y señala piñón VVT.")
    agregar("G12-L3-06", CLASE_12, "L3", "Vehículo alemán con motor Valvetronic presenta código 2A67 y entra en modo de emergencia sin aceleración. El motor de accionamiento del eje excéntrico arroja cortocircuito a masa en su devanado interno y el sensor de ángulo de excéntrica no reconoce la posición de tope mínimo.", "TECNICO", "modo_emergencia_valvetronic", "valvetronic_dtc_2a67|motor_excentrico_corto|sin_tope_minimo", "falla_cuerpo_aceleracion", "", "NO", "SI", "Cuerpo de aceleracion o valvula IAC sucia", "L3 falla de servomotor excéntrico Valvetronic.")
    agregar("G12-L3-07", CLASE_12, "L3", "El motor tironea a 2800 rpm y el consumo subió a 14 litros cada 100 km. Al retirar el perno pasante del solenoide de distribución variable se encontró el tamiz de malla filtrante roto con partículas de carbón que trabaron la corredera en avance máximo continuo.", "TALLER", "inspeccion_solenoide", "tamiz_vvt_roto|corredera_trabada_avance_maximo", "inyectores_goteando", "", "NO", "SI", "Inyectores sucios o filtro de combustible obstruido", "L3 tamiz de filtro VVT roto con corredera trabada.")
    agregar("G12-L3-08", CLASE_12, "L3", "Prueba dinámica en carretera: a 100 km/h sostenidos se genera DTC P0011 intermitente. La señal del sensor de árbol de levas es nítida pero el desfase respecto al cigüeñal oscila erráticamente 8 grados por encima del objetivo por fuga de presión a través de los anillos de estanqueidad de la tapa de levas.", "TECNICO", "carretera_dinamica", "dtc_p0011|oscilacion_erratica_8_grados|anillos_estanqueidad_levas", "sensor_cmp_defectuoso", "P0011", "NO", "NO", "", "L3 fuga en anillos de teflón de lubricación de árbol.")
    agregar("G12-L3-09", CLASE_12, "L3", "El carro pierde potencia en subida y en mínimo tiembla en caliente arrojando P0012. El mecanico le midio la resistencia a la electrovalvula VVT y dio 50 ohmios cuando debe tener 8 ohmios. Al ponerle solenoide nuevo emparejo el motor de una.", "ERROR_ORTOGRAFICO", "subida_y_ralenti", "dtc_p0012|resistencia_vvt_50_ohmios|solenoide_nuevo_soluciona", "falla_bujias", "P0012", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L3 resistencia 50 ohms en solenoide con ortografía informal.")
    agregar("G12-L3-10", CLASE_12, "L3", "DTC P0026 referente a circuito de válvula solenoide de admisión banco 1. Prueba de osciloscopio en el conector de la válvula muestra señal de control con modulación de ancho de pulso normal pero consumo de corriente de 0 amperios por bobina cortada en el solenoide OCV.", "TECNICO", "diagnostico_electrico", "dtc_p0026|senal_pwm_ok|consumo_0_amperios_bobina_abierta", "falla_cableado_ecu", "", "NO", "NO", "", "L3 análisis osciloscópico de corriente en OCV.")
    agregar("G12-L3-11", CLASE_12, "L3", "El auto arranca bien y camina suave en frío pero a los 15 minutos de tráfico tiembla como si fallara una bujía y prende el check con P0011. Se cambiaron bobinas y bujías sin cambio alguno; la falla era el variador VVT que al licuarse el aceite se queda trabado en avance.", "TALLER", "post_cambio_bobinas", "dtc_p0011|persiste_tras_bobinas_bujias|variador_trabado_caliente", "falla_chispa", "P0011", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L3 persistencia tras cambio de bobinas descarta encendido.")
    agregar("G12-L3-12", CLASE_12, "L3", "Presión de aceite general marca 40 psi pero en el conducto específico de alimentación al piñón VVT cae a 10 psi por obturación del tornillo banjo con filtro integrado en la culata, provocando código P0012 por retardo severo de levas.", "TECNICO", "medicion_puerto_vvt", "dtc_p0012|presion_puerto_vvt_10psi|tornillo_banjo_obstruido", "bomba_aceite_defectuosa", "P0012", "NO", "SI", "Baja presion de aceite o bomba de aceite defectuosa", "L3 caída de presión localizada en tornillo banjo.")
    agregar("G12-L3-13", CLASE_12, "L3", "En desaceleración rápida el motor cae a 450 rpm y se apaga registrando código P0011. La electroválvula de control no retorna a su posición de reposo debido a rayaduras en el cilindro de la corredera producidas por contaminación metálica en el aceite.", "TALLER", "desaceleracion_apagado", "dtc_p0011|apagado_450rpm|corredera_ocv_rayada", "falla_cuerpo_mariposa", "P0011", "NO", "SI", "Cuerpo de aceleracion o valvula IAC sucia", "L3 corredera rayada por viruta no retorna a cero.")
    agregar("G12-L3-14", CLASE_12, "L3", "Hola maestro, el carro no tiene pique en alta y se siente frenado cuando paso de 3000 vueltas. En el taller revisaron la distribución y la cadena está perfecta, pero al medir la válvula VVT no abre el paso de aceite y el árbol se queda sin avance.", "WHATSAPP", "alta_rotacion", "sin_pique_alta_3000rpm|cadena_perfecta|valvula_vvt_no_abre_paso", "cadena_saltada", "", "NO", "SI", CLASE_11, "L3 cadena perfecta descarta distribución y confirma VVT.")
    agregar("G12-L3-15", CLASE_12, "L3", "Inspección de actuador VVT electromagnético en banco: el núcleo móvil presenta magnetización residual y deformación en el resorte de retroceso, provocando que el tiempo de recuperación de sincronía exceda los 1.2 segundos y active el DTC P0012.", "TECNICO", "prueba_banco_actuador", "dtc_p0012|magnetizacion_residual|tiempo_retorno_excede_1_2s", "falla_sensor_posicion", "P0012", "NO", "NO", "", "L3 retardo de 1.2 segundos por resorte deformado.")

    # =========================================================================
    # CLASE 13: Falla de descarbonizacion e inyeccion directa GDI (acumulacion de carbon en valvulas) (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G13-L1-01", CLASE_13, "L1", "El motor tiembla bastante durante el primer minuto al encender por las mañanas.", "COTIDIANO", "primer_minuto_manana", "temblor_primer_minuto", "", "", "SI", "NO", "", "L1 temblor en arranque en frío.")
    agregar("G13-L1-02", CLASE_13, "L1", "Hola, mi carro tiene inyección directa y perdió bastante pique en salida.", "WHATSAPP", "arranque_salida", "inyeccion_directa_sin_pique", "", "", "SI", "NO", "", "L1 pérdida de pique en motor GDI.")
    agregar("G13-L1-03", CLASE_13, "L1", "Siento tirones molestos al acelerar suave cuando el motor aún no calienta.", "COTIDIANO", "motor_semi_frio", "tirones_suaves_en_frio", "", "", "SI", "NO", "", "L1 tironeo suave en frío.")
    agregar("G13-L1-04", CLASE_13, "L1", "El ralentí está muy áspero y cabecea en frío pero al calentar empareja.", "TALLER", "frio_vs_caliente", "ralenti_aspero_frio|empareja_caliente", "", "", "SI", "NO", "", "L1 aspereza que cede con calor.")
    agregar("G13-L1-05", CLASE_13, "L1", "Se prende el Check Engine parpadeando en frío y luego se queda fijo.", "COTIDIANO", "arranque_frio", "check_parpadea_frio", "", "", "SI", "NO", "", "L1 misfire matutino intermitente.")
    agregar("G13-L1-06", CLASE_13, "L1", "Siento como una retención o bache de aire cuando piso el acelerador a fondo.", "TALLER", "aceleracion_fondo", "bache_de_aire_acelerar", "", "", "SI", "NO", "", "L1 restricción de flujo de admisión.")
    agregar("G13-L1-07", CLASE_13, "L1", "Mi auto consume más gasolina y se siente pesado como si estuviera atorado.", "COTIDIANO", "marcha", "consumo_alto|motor_atorado", "", "", "SI", "NO", "", "L1 motor atorado por flujo estrangulado.")
    agregar("G13-L1-08", CLASE_13, "L1", "El carro cabecea feo en frio en las mañanas y bota olor a mala combustion.", "ERROR_ORTOGRAFICO", "arranque_manana", "cabeceo_frio|olor_mala_combustion", "", "", "SI", "NO", "", "L1 cabeceo en frío con error ortográfico.")
    agregar("G13-L1-09", CLASE_13, "L1", "Buenas, me dijeron en el taller que a los motores turbo directos hay que descarbonizarlos.", "WHATSAPP", "consulta", "consulta_descarbonizacion_gdi", "", "", "SI", "NO", "", "L1 referencia directa a carbonilla GDI.")
    agregar("G13-L1-10", CLASE_13, "L1", "Falla de combustión estratificada en fase de calentamiento con pérdida de flujo volumétrico.", "TECNICO", "fase_calentamiento", "falla_combustion_estratificada", "", "", "SI", "NO", "", "L1 técnico de combustión estratificada deficiente.")

    # --- L2 (15 casos) ---
    agregar("G13-L2-01", CLASE_13, "L2", "En las mañanas el motor arranca temblando como si estuviera en tres cilindros durante dos minutos; al calentar se normaliza pero le falta fuerza al acelerar.", "COTIDIANO", "arranque_frio_manana", "temblor_frio_dos_minutos|falta_fuerza_acelerar", "falla_en_caliente", "", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L2 cold start misfire por carbonilla vs bobinas.")
    agregar("G13-L2-02", CLASE_13, "L2", "Motor de inyección directa GDI con 90 mil km; las bujías y bobinas son nuevas pero persiste el ralentí áspero en frío y los tirones en baja.", "TALLER", "baja_rpm_frio", "ralenti_aspero_frio|bujias_bobinas_nuevas", "falla_ignicion", "", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L2 componentes de encendido nuevos descartan misfire.")
    agregar("G13-L2-03", CLASE_13, "L2", "Se retiró el múltiple de admisión observándose gruesa capa de carbón negro tipo costra tapando las válvulas de admisión en los 4 cilindros.", "TECNICO", "inspeccion_multiple", "costra_carbon_valvulas_admision", "falla_inyector", "", "NO", "NO", "", "L2 inspección visual directa de carbón en válvulas.")
    agregar("G13-L2-04", CLASE_13, "L2", "Hola, mi auto tiene motor turbo inyección directa; en frío titila la luz de motor con fallos de encendido pero la presión de la bomba de alta está en 60 bar perfecta.", "WHATSAPP", "arranque_frio", "check_titila_frio|presion_bomba_alta_60bar_ok", "falla_bomba_combustible", "", "NO", "SI", "Bomba de gasolina quemada o con baja presion", "L2 presión de alta 60 bar normal descarta bomba de gasolina.")
    agregar("G13-L2-05", CLASE_13, "L2", "Pérdida notoria de potencia a partir de 3500 rpm; el motor no respira bien por acumulación de carbonilla en los puertos de admisión y conductos de culata.", "TALLER", "alta_rpm", "restriccion_respiracion_3500rpm|carbonilla_puertos_admision", "falla_escape", "", "NO", "NO", "", "L2 estrangulamiento de flujo de aire en alta rotación.")
    agregar("G13-L2-06", CLASE_13, "L2", "El vehículo da tirones al acelerar en frío con código P0300 múltiple; los inyectores se probaron en banco y pulverizan parejo a 120 bar.", "TECNICO", "aceleracion_frio", "tirones_frio_p0300|inyectores_banco_120bar_ok", "falla_inyectores", "P0300", "NO", "SI", "Inyectores sucios o filtro de combustible obstruido", "L2 inyectores testeados en banco descartan inyección sucia.")
    agregar("G13-L2-07", CLASE_13, "L2", "El auto arranca tosco y pesado en las mañanas; al acelerar suave entre 1500 y 2000 rpm cabecea hasta que el motor alcanza su temperatura de régimen.", "COTIDIANO", "1500_2000rpm_frio", "arranque_tosco|cabeceo_1500_2000rpm", "cabeceo_en_caliente", "", "NO", "NO", "", "L2 turbulencia deficiente en rango de bajo régimen.")
    agregar("G13-L2-08", CLASE_13, "L2", "Mi carro inyeccion directa cabecea feo en frio pero al calentar empareja bien. Ya le cambiaron filtro de gasolina y bujias pero el carbon de las balvulas sigue tapando.", "ERROR_ORTOGRAFICO", "arranque_frio", "cabeceo_frio|filtro_bujias_nuevas", "falla_filtro_combustible", "", "NO", "SI", "Inyectores sucios o filtro de combustible obstruido", "L2 persistencia tras filtro y bujías con error ortográfico.")
    agregar("G13-L2-09", CLASE_13, "L2", "Diagnóstico por boroscopio confirmó obstrucción del 40% del área de paso de aire en las válvulas de admisión por depósitos de vapores de aceite de la PCV.", "TECNICO", "boroscopia_admision", "obstruccion_40_porciento_boroscopio|depositos_pcv", "falla_valvulas_dobladas", "", "NO", "NO", "", "L2 confirmación boroscópica de restricción del 40%.")
    agregar("G13-L2-10", CLASE_13, "L2", "El motor no responde ágil al acelerador en baja y tiene un bache de aceleración; el consumo aumentó 2 litros cada 100 km en tráfico urbano.", "COTIDIANO", "trafico_urbano", "bache_aceleracion_baja|consumo_alto_urbano", "falla_transmision", "", "NO", "NO", "", "L2 bache en baja rotación y sobreconsumo urbano.")
    agregar("G13-L2-11", CLASE_13, "L2", "Buenas maestro, en frío el carro tironea como si fuera a apagarse. No pierde aceite ni refrigerante, el problema es que se siente atorado de aire al pisarlo.", "WHATSAPP", "arranque_frio", "tironeo_frio|motor_atorado_aire", "perdida_aceite|perdida_refrigerante", "", "NO", "SI", "Empaque de culata soplado o danado", "L2 motor atorado sin pérdidas de fluidos descarta culata.")
    agregar("G13-L2-12", CLASE_13, "L2", "Aceleraciones en marchas intermedias presentan titubeo; el sistema de turbulencia de admisión se traba por carbonilla espesa en los ejes de las mariposas flap.", "TALLER", "marchas_intermedias", "titubeo_aceleracion|mariposas_flap_trabadas_carbon", "falla_turbo", "", "NO", "SI", CLASE_14, "L2 flaps de admisión atascados por carbón vs turbo.")
    agregar("G13-L2-13", CLASE_13, "L2", "Falla de encendido aleatoria registrada únicamente durante los primeros 45 segundos de ralentí tras arranque a temperatura ambiente de 15°C.", "TECNICO", "ralenti_primeros_45seg", "misfire_aleatorio_primeros_45seg", "misfire_en_caliente", "P0300", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L2 ventana térmica exclusiva de 45 segundos.")
    agregar("G13-L2-14", CLASE_13, "L2", "El auto pierde pique y le cuesta levantar revoluciones en subida; no hay códigos de sensor de oxígeno y la presión de riel está perfecta a 140 bar.", "COTIDIANO", "subida", "falta_pique_subida|riel_140bar_ok", "falla_sensor_oxigeno", "", "NO", "SI", "Falla en sensor de oxigeno o mezcla rica", "L2 presión de riel 140 bar normal descarta mezcla y bomba.")
    agregar("G13-L2-15", CLASE_13, "L2", "Vehículo GDI con 110,000 km sin servicio de descarbonización previo; presenta temblores matutinos y pérdida de respuesta instantánea en el pedal.", "TALLER", "arranque_frio", "temblores_matutinos_gdi_alto_km|pedal_retardado", "falla_cuerpo_mariposa", "", "NO", "NO", "", "L2 antecedente de kilometraje sin descarbonización.")

    # --- L3 (15 casos) ---
    agregar("G13-L3-01", CLASE_13, "L3", "Inspección endoscópica a través del puerto de admisión en motor 2.0 TSI con 95,000 km revela acumulación severa de carbón de hasta 4 mm de espesor en el lomo y vástago de las 8 válvulas de admisión. El vehículo produce fallos de encendido aleatorios P0300 durante los primeros 60 segundos en frío pero la presión de la bomba de alta combustible marca 50 bar en ralentí.", "TECNICO", "endoscopia_admision_frio", "carbon_4mm_valvulas_admision|dtc_p0300_en_frio|bomba_alta_50bar_ok", "falla_bomba_combustible", "P0300", "NO", "SI", "Bomba de gasolina quemada o con baja presion", "L3 endoscopía 4 mm de carbón con bomba alta en 50 bar.")
    agregar("G13-L3-02", CLASE_13, "L3", "El cliente ingresa por tirones intensos en frío y falta de potencia arriba de 3500 rpm. Se verificó con escáner que las bujías, bobinas y catalizador están conformes. Se procedió a realizar limpieza mediante proyección de cáscara de nuez (walnut blasting) en los puertos de admisión, eliminando toda la carbonilla y recuperando suavidad en frío.", "TALLER", "post_walnut_blasting", "tirones_frio_resueltos_walnut_blasting|carbonilla_puertos", "falla_encendido", "", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L3 walnut blasting restaura marcha y confirma diagnóstico.")
    agregar("G13-L3-03", CLASE_13, "L3", "Arranque matutino con sacudidas violentas de motor y código P0301 y P0304 durante el régimen de calentamiento por mezcla estratificada deficiente. Al alcanzar 75°C de refrigerante el motor gira redondo sin fallos. El caudal y balance de los inyectores de inyección directa está dentro del 2% en banco de pruebas.", "TECNICO", "calentamiento_estratificado", "sacudidas_frio_p0301_p0304|empareja_a_75c|balance_inyectores_2_porciento", "falla_inyectores", "P0300", "NO", "SI", "Inyectores sucios o filtro de combustible obstruido", "L3 balance de inyectores al 2% descarta inyectores sucios.")
    agregar("G13-L3-04", CLASE_13, "L3", "Motor de inyección directa 1.6 GDI presenta bache de aceleración a 2200 rpm y aumento de consumo. Desmontado el múltiple de admisión se constata que las mariposas deflectoras de flujo (tumble flaps) tienen acumulación de resina de aceite carbonizado que restringe el paso de aire un 35 por ciento.", "TALLER", "inspeccion_flaps", "mariposas_tumble_carbonizadas|obstruccion_35_porciento", "falla_sensor_maf", "", "NO", "NO", "", "L3 flaps deflectoras tumble trabadas por carbonilla.")
    agregar("G13-L3-05", CLASE_13, "L3", "Hola maestro, el carro tiembla horrible en las mañanas cuando salgo a trabajar. Ya le cambiaron las 4 bujías de iridio y las 4 bobinas y sigue igualito. En el taller me metieron la cámara por la admisión y las válvulas están como con carbón de parrilla negro y pegajoso.", "WHATSAPP", "arranque_frio_bujias_nuevas", "valvulas_carbon_parrilla|persiste_post_bobinas_bujias", "falla_bujias_bobinas", "", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L3 relato WhatsApp directo confirmando válvulas carbonizadas.")
    agregar("G13-L3-06", CLASE_13, "L3", "Pérdida de flujo volumétrico en alta rotación registrada por el sensor MAF reportando solo 110 g/s a 5500 rpm en un motor turbo de 200 hp (especificación normal 160 g/s). La presión de sobrealimentación de turbo es correcta a 1.1 bar pero el aire no ingresa por estrangulamiento de carbón en válvulas.", "TECNICO", "prueba_flujo_maf_5500rpm", "flujo_maf_110gs_bajo|boost_1_1bar_ok|estrangulamiento_carbon", "fuga_turbo", "", "NO", "SI", CLASE_15, "L3 presión de turbo OK pero MAF bajo por estrangulamiento de carbón.")
    agregar("G13-L3-07", CLASE_13, "L3", "El vehículo ingresó con ralentí inestable en frío y quejas de falta de aceleración en subidas. Prueba de compresión estática dio 175 psi parejos descartando problemas mecánicos de culata o aros. La inspección óptica reveló carbonilla densa que altera el vórtice de aire de admisión en frío.", "TALLER", "prueba_compresion_estatica", "compresion_175psi_pareja|carbonilla_altera_vortice", "falla_culata|desgaste_anillos", "", "NO", "SI", "Empaque de culata soplado o danado", "L3 compresión 175 psi pareja descarta culata y anillos.")
    agregar("G13-L3-08", CLASE_13, "L3", "DTC P0300 aleatorio registrado en memoria de congelado a 1100 rpm con temperatura de refrigerante a 22°C. El contador de fallos de encendido se detiene totalmente una vez que la temperatura de motor supera los 60°C, comportamiento típico de turbulencia degradada por carbonilla GDI.", "TECNICO", "freezefram_dtc_p0300", "dtc_p0300_freeze_frame_22c|contador_fallos_detiene_60c", "misfire_constante_caliente", "P0300", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L3 freeze frame a 22°C descarta fallo eléctrico permanente.")
    agregar("G13-L3-09", CLASE_13, "L3", "Tengo un auto con inyeccion directa que jalonea en frio en las mañanas y gasta gasolina. Le pasaron el escaner y no hay fallas de bomba ni de chispa pero las balvulas de admision estan taponadas de carbon negro. Despues de limpiar con granalla de nuez quedo sedita.", "ERROR_ORTOGRAFICO", "post_limpieza_granalla", "jaloneo_frio|balvulas_taponadas_carbon|granalla_soluciona", "falla_bomba_gasolina", "", "NO", "SI", "Inyectores sucios o filtro de combustible obstruido", "L3 limpieza con granalla soluciona jaloneo con ortografía informal.")
    agregar("G13-L3-10", CLASE_13, "L3", "Prueba en dinamómetro muestra curva de par motor con depresión de 35 Nm entre 2000 y 3200 rpm en motor GDI con 80 mil km. Se retiró la rampa de inyección encontrándose inyectores con toberas limpias pero toberas de culata y asientos de válvulas recubiertos de carbonilla apelmazada.", "TECNICO", "dinamometro_curva_par", "depresion_35nm_curva_par|asientos_valvulas_carbonizados", "inyectores_obstruidos", "", "NO", "SI", "Inyectores sucios o filtro de combustible obstruido", "L3 dinamometría con caída de 35 Nm por válvulas carbonizadas.")
    agregar("G13-L3-11", CLASE_13, "L3", "El motor presenta titubeos al salir en frío y se apaga en maniobras de estacionamiento matutinas. El cuerpo de aceleración está completamente limpio y calibrado. El desarmado de admisión demostró que la carbonilla impide el sellado marginal de las válvulas en fase fría.", "TALLER", "maniobras_frio_matutinas", "titubeos_frio|cuerpo_aceleracion_limpio|sellado_marginal_carbon", "cuerpo_mariposa_sucio", "", "NO", "SI", "Cuerpo de aceleracion o valvula IAC sucia", "L3 cuerpo de mariposa limpio descarta IAC y confirma carbón en válvulas.")
    agregar("G13-L3-12", CLASE_13, "L3", "Análisis de gases de escape en frío arroja hidrocarburos no quemados altos (450 ppm) que caen a 25 ppm al calentar. El sensor de temperatura de motor ECT responde linealmente y el sistema de inyección directa pulveriza a 100 bar estables, originándose la mala mezcla en las válvulas obstruidas.", "TECNICO", "analisis_gases_frio", "hc_450ppm_frio_cae_25ppm|pulverizacion_100bar_ok", "falla_sensor_ect", "", "NO", "NO", "", "L3 HC elevado transitorio por mala atomización por carbón.")
    agregar("G13-L3-13", CLASE_13, "L3", "Auto turbo GDI con falta de respuesta en baja y bache de soplado. Se verificó el actuador del turbocompresor y no tiene holgura ni trabas. Al revisar las válvulas de admisión mediante boroscopio se encontraron pegotes de carbón de 3 mm reduciendo el conducto de aspiración.", "TALLER", "boroscopia_post_turbo", "valvulas_pegotes_3mm_carbon|actuador_turbo_ok", "falla_actuador_turbo", "", "NO", "SI", CLASE_14, "L3 actuador de turbo verificado descarta turbo y confirma carbón GDI.")
    agregar("G13-L3-14", CLASE_13, "L3", "Buenas, el carro ratea feo apenas lo prendo en el sótano y huele a nafta cruda. Le cambié bujías de platino y filtro de aire pero sigue fallando en frío. El mecánico le sacó el múltiple y las válvulas parecían carbón de leña. Las limpiaron con ultrasonido y walnut y se arregló.", "WHATSAPP", "arranque_sotano_frio", "rateo_frio_sotano|valvulas_carbon_lena|limpieza_resuelve", "falla_filtro_aire", "", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L3 relato WhatsApp de reparación exitosa de carbonilla.")
    agregar("G13-L3-15", CLASE_13, "L3", "Registro de contadores de fallos individuales en PCM muestra 80 eventos de misfire repartidos entre cilindros 1, 2 y 3 durante los primeros 90 segundos a 1200 rpm. Una vez alcanzada la temperatura de ciclo cerrado a 80°C el contador se clava en cero, descartando fallas permanentes de encendido o compresión.", "TECNICO", "monitoreo_pcm_frio", "misfire_primeros_90seg|contador_cero_en_caliente", "falla_permanente_chispa", "P0300", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L3 contadores de misfire temporalmente acotados a fase fría.")

    # =========================================================================
    # CLASE 14: Falla en actuador de turbocompresor o VGT en motores alemanes TSI / TFSI (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G14-L1-01", CLASE_14, "L1", "Se prendió la luz EPC en el tablero y el carro perdió fuerza de golpe.", "COTIDIANO", "aceleracion_autopista", "luz_epc|perdida_fuerza_subita", "", "", "SI", "NO", "", "L1 testigo EPC y corte súbito de turbo.")
    agregar("G14-L1-02", CLASE_14, "L1", "Hola, al acelerar fuerte en tercera se me corta la potencia y no pasa de 80.", "WHATSAPP", "tercera_marcha", "corte_potencia_tercera|no_pasa_80", "", "", "SI", "NO", "", "L1 corte de potencia en aceleración.")
    agregar("G14-L1-03", CLASE_14, "L1", "Siento un cascabeleo metálico al soltar el acelerador en el motor turbo.", "COTIDIANO", "desaceleracion", "cascabeleo_metalico_soltar_acelerador", "", "", "SI", "NO", "", "L1 cascabeleo de varilla/wastegate suelta.")
    agregar("G14-L1-04", CLASE_14, "L1", "El carro entra en modo de emergencia cuando le exijo en subida.", "TALLER", "subida_exigida", "modo_emergencia_subida", "", "", "SI", "NO", "", "L1 limp mode bajo carga en subida.")
    agregar("G14-L1-05", CLASE_14, "L1", "El turbo a veces sopla y a veces se queda completamente muerto.", "COTIDIANO", "marcha_variable", "turbo_sopla_intermitente", "", "", "SI", "NO", "", "L1 comportamiento errático de presión de turbo.")
    agregar("G14-L1-06", CLASE_14, "L1", "Aparece un código de sobrepresión o baja presión de turbo en el tablero.", "TECNICO", "diagnostico", "codigo_presion_turbo", "", "", "SI", "NO", "", "L1 reporte genérico de presión de turbo.")
    agregar("G14-L1-07", CLASE_14, "L1", "Apago el motor y lo vuelvo a prender y la fuerza regresa normal.", "WHATSAPP", "reinicio_motor", "reinicio_restaura_potencia", "", "", "SI", "NO", "", "L1 reinicio limpia transitoriamente el limp mode.")
    agregar("G14-L1-08", CLASE_14, "L1", "El auto tironea en alta y la varilla del turbo vibra con un sonido a lata.", "TALLER", "alta_rpm", "tironeo_alta|varilla_turbo_vibra", "", "", "SI", "NO", "", "L1 vibración de varilla de actuador.")
    agregar("G14-L1-09", CLASE_14, "L1", "Se prende el EPC y se queda sin turbo cuando paso un camion en pista.", "ERROR_ORTOGRAFICO", "adelantamiento", "epc_adelantamiento|sin_turbo", "", "", "SI", "NO", "", "L1 corte en sobrepaso con error ortográfico.")
    agregar("G14-L1-10", CLASE_14, "L1", "Desviación entre la presión de soplado especificada y la real del turbocompresor.", "TECNICO", "plena_carga", "desviacion_presion_soplado_turbo", "", "", "SI", "NO", "", "L1 técnico de divergencia de sobrealimentación.")

    # --- L2 (15 casos) ---
    agregar("G14-L2-01", CLASE_14, "L2", "En autopista al pisar a fondo en cuarta se prende el testigo EPC y el carro entra en modo de emergencia; apago y prendo el carro y vuelve a acelerar normal.", "COTIDIANO", "autopista_cuarta", "testigo_epc_acelerar|modo_emergencia|resetea_al_apagar", "falla_permanente", "P0299", "NO", "NO", "", "L2 corte de turbo reseteable con llave con DTC P0299.")
    agregar("G14-L2-02", CLASE_14, "L2", "Se escucha un sonido de sonajero metálico constante en la caracola de escape del turbo al soltar el gas entre 2000 y 3000 rpm por holgura del actuador de la wastegate.", "TALLER", "desaceleracion_2000_3000rpm", "sonajero_wastegate_desacelerar|holgura_actuador", "ruido_interno_motor", "", "NO", "SI", CLASE_11, "L2 cascabeleo de wastegate vs cadena de distribución.")
    agregar("G14-L2-03", CLASE_14, "L2", "Código P0299 por baja presión de turbo; las mangueras de intercooler no tienen fugas ni están rotas pero la varilla del actuador electrónico está dura y atascada.", "TECNICO", "inspeccion_varilla", "dtc_p0299|mangueras_intercooler_sanas|varilla_actuador_atascada", "fuga_manguera_intercooler", "P0299", "NO", "SI", CLASE_15, "L2 varilla trabada con mangueras sanas descarta fuga de intercooler.")
    agregar("G14-L2-04", CLASE_14, "L2", "Hola, mi Golf TSI corta la potencia al pasar los 120 km/h y prende EPC. No hay silbido de fuga de aire en el motor, simplemente el turbo deja de empujar.", "WHATSAPP", "velocidad_120kmh", "epc_corte_120kmh", "silbido_fuga_aire", "P0299", "NO", "SI", CLASE_15, "L2 corte de turbo sin silbido de aire descarta fuga de manguera.")
    agregar("G14-L2-05", CLASE_14, "L2", "El actuador eléctrico del turbocompresor no completa el ajuste básico con el escáner marcando error de adaptación por límite de recorrido excedido.", "TECNICO", "ajuste_basico_escaner", "error_ajuste_basico_turbo|limite_recorrido_excedido", "falla_sensor_map", "", "NO", "NO", "", "L2 fallo de calibración básica de actuador de turbo.")
    agregar("G14-L2-06", CLASE_14, "L2", "Al exigir en subida se genera código P0234 de sobrepresión porque la compuerta de alivio wastegate no abre a tiempo para descargar los gases de escape.", "TALLER", "subida_exigida", "dtc_p0234_sobrepresion|wastegate_no_abre", "fuga_presion", "P0234", "NO", "SI", CLASE_15, "L2 sobrepresión P0234 por wastegate trabada cerrada.")
    agregar("G14-L2-07", CLASE_14, "L2", "El motor anda perfecto en uso urbano tranquilo, pero en el momento en que acelero rápido para adelantar salta el EPC y queda sin fuerza de turbo.", "COTIDIANO", "adelantamiento_brusco", "salto_epc_adelantamiento|sin_fuerza_turbo", "falla_en_baja", "", "NO", "NO", "", "L2 fallo exclusivo bajo solicitación de alta carga.")
    agregar("G14-L2-08", CLASE_14, "L2", "Mi carro Audi TFSI prende el EPC al acelerar fuerte y en el escaner sale P0299. Las mangueras del turbo estan bien apretadas y no se escucha soplo de aire.", "ERROR_ORTOGRAFICO", "aceleracion_fuerte", "dtc_p0299_audi|mangueras_apretadas|sin_soplo_aire", "manguera_rota_intercooler", "P0299", "NO", "SI", CLASE_15, "L2 P0299 sin soplo con error ortográfico.")
    agregar("G14-L2-09", CLASE_14, "L2", "Inspección mecánica demostró holgura de 2 milímetros en el buje del eje de la wastegate, provocando pérdida de cierre hermético y presión tardía de soplado.", "TALLER", "inspeccion_buje", "holgura_2mm_buje_wastegate|cierre_no_hermetico", "falla_paletas_compresor", "", "NO", "NO", "", "L2 holgura de 2 mm en buje de wastegate.")
    agregar("G14-L2-10", CLASE_14, "L2", "DTC P2563 referente a señal fuera de rango del sensor de posición del actuador de la geometría variable en motor 2.0 TDI diésel.", "TECNICO", "diagnostico_vgt", "dtc_p2563_posicion_vgt|senal_fuera_rango", "falla_inyector_diesel", "P2563", "NO", "NO", "", "L2 código P2563 de sensor de posición VGT.")
    agregar("G14-L2-11", CLASE_14, "L2", "Buenas maestro, el carro acelera bien hasta medio pedal, pero si piso a fondo entra en modo tortuga y prende EPC. Lo apago cinco minutos y vuelve a acelerar.", "WHATSAPP", "aceleracion_plena", "modo_tortuga_fondo|epc_prendido|apaga_y_resetea", "falla_bomba_gasolina", "", "NO", "SI", "Bomba de gasolina quemada o con baja presion", "L2 limp mode transitorio vs bomba de gasolina.")
    agregar("G14-L2-12", CLASE_14, "L2", "El motor eléctrico del actuador de turbo presenta resistencia térmica; funciona frío pero al calentar la carcasa se bloquea mecánicamente.", "TALLER", "motor_caliente", "actuador_turbo_bloquea_en_caliente", "falla_en_frio", "", "NO", "NO", "", "L2 traba térmica en actuador eléctrico de turbo.")
    agregar("G14-L2-13", CLASE_14, "L2", "Al pisar el acelerador la presión de turbo solicitada por ECU es 1.3 bar pero el sensor MAP solo registra 0.6 bar estancado por varilla atascada.", "TECNICO", "plena_carga", "presion_solicitada_1_3_real_0_6|varilla_atascada", "fuga_conducto_admision", "P0299", "NO", "SI", CLASE_15, "L2 divergencia MAP 1.3 vs 0.6 bar por varilla atascada.")
    agregar("G14-L2-14", CLASE_14, "L2", "El auto pierde potencia de repente y no responde el turbo; el varillaje que conecta el motor eléctrico con la turbina está oxidado y agarrotado.", "COTIDIANO", "marcha", "varillaje_oxidado_agarrotado|sin_respuesta_turbo", "falla_ignicion", "", "NO", "NO", "", "L2 varillaje oxidado mecánicamente trabado.")
    agregar("G14-L2-15", CLASE_14, "L2", "Se genera código P0234 por sobrepresión de soplado; el motor tironea con violencia en tercera al llegar a 3500 rpm por cierre permanente de compuerta.", "TALLER", "3500rpm_tercera", "dtc_p0234_sobrepresion|tironeo_violento_3500rpm", "falla_caja", "P0234", "NO", "NO", "", "L2 tironeo violento por sobrepresión descontrolada.")

    # --- L3 (15 casos) ---
    agregar("G14-L3-01", CLASE_14, "L3", "En prueba de carretera bajo aceleración a fondo en 4ta marcha a 3500 rpm se enciende testigo EPC y el motor entra en modo de emergencia. Escáner reporta DTC P0299 (Underboost). La presión especificada de turbo es de 2100 mbar mientras que la real no supera los 1350 mbar. La prueba de humo en circuito de intercooler descartó fugas y se constató que la varilla del actuador de la wastegate presenta atasco mecánico por óxido en el pivote.", "TECNICO", "autopista_4ta_3500rpm", "dtc_p0299|presion_2100_vs_1350mbar|varilla_wastegate_atascada_oxido", "fuga_intercooler_humo_negativo", "P0299", "NO", "SI", CLASE_15, "L3 prueba de humo negativa descarta intercooler y confirma atasco de varilla.")
    agregar("G14-L3-02", CLASE_14, "L3", "Vehículo 1.8 TSI presenta cascabeleo metálico audible en desaceleración entre 2800 y 1800 rpm. Inspección en elevador desmontando el catalizador reveló holgura radial de 2.5 mm en el buje de la compuerta wastegate de la caracola de escape, impidiendo el cierre plano hermético y generando código P0299 intermitente sin ruidos en la cadena de distribución.", "TALLER", "desaceleracion_elevador", "holgura_2_5mm_buje_wastegate|dtc_p0299_intermitente", "ruido_cadena_distribucion", "P0299", "NO", "SI", CLASE_11, "L3 inspección interna de wastegate descarta cadena de distribución.")
    agregar("G14-L3-03", CLASE_14, "L3", "Al acelerar a plena carga en autopista se activa testigo EPC y código P0234 de sobrepresión. El manómetro de turbo registra pico de 1.8 bar superando el límite de seguridad de 1.2 bar. El actuador eléctrico V465 no logra retornar a la posición abierta debido a deformación interna en el sinfín de plástico del servomotor.", "TECNICO", "autopista_plena_carga", "dtc_p0234_overboost|pico_1_8bar|sinfin_plastico_v465_deformado", "falla_sensor_map", "P0234", "NO", "NO", "", "L3 engranaje sinfín de actuador V465 barrido.")
    agregar("G14-L3-04", CLASE_14, "L3", "El auto corta potencia abruptamente en adelantamientos a 100 km/h encendiendo EPC. En escáner el voltaje del sensor de posición del actuador de turbo marca 4.8V fijo fuera de tolerancia (rango válido 3.5V a 4.2V en reposo). Al intentar realizar el ajuste básico del canal de sobrealimentación el proceso es abortado por la ECU.", "TECNICO", "adelantamiento_100kmh", "epc_corte_100kmh|voltaje_actuador_4_8v_invalido|ajuste_basico_abortado", "falla_pedal_acelerador", "", "NO", "NO", "", "L3 voltaje fuera de rango 4.8V y ajuste básico abortado.")
    agregar("G14-L3-05", CLASE_14, "L3", "Hola maestro, tengo un Seat León TSI. En subida rápida se prende la luz EPC y el carro se muere, no acelera nada y tengo que orillarme, apagar el motor y prenderlo para que vuelva a jalar. En el taller revisaron y dicen que el actuador del turbo se queda pegado cuando calienta.", "WHATSAPP", "subida_rapida", "epc_se_muere_subida|apagar_y_prender_restaura|actuador_turbo_pegado_caliente", "falla_bomba_gasolina", "", "NO", "SI", "Bomba de gasolina quemada o con baja presion", "L3 relato WhatsApp de limp mode térmico de actuador.")
    agregar("G14-L3-06", CLASE_14, "L3", "Motor 2.0 TDI diésel genera DTC P2563 y testigo de espiral de precalentamiento parpadeando bajo carga. Se conectó bomba de vacío manual (Mityvac) al actuador neumático de geometría variable comprobándose que la membrana retiene 20 inHg pero la varilla no desplaza por carbón acumulado en los álabes variables de la turbina.", "TECNICO", "prueba_mityvac_vgt", "dtc_p2563|membrana_retiene_20inhg|alabes_vgt_trabados_carbon", "membrana_rota", "P2563", "NO", "NO", "", "L3 Mityvac retiene vacío confirmando traba mecánica en álabes VGT.")
    agregar("G14-L3-07", CLASE_14, "L3", "El cliente se queja de un cascabeleo tipo lámina suelta al soltar el acelerador y pérdida de pique. Se instaló clip de refuerzo de wastegate (anti-rattle clip) en la varilla del actuador eliminando el juego mecánico y restableciendo la respuesta inmediata del turbo sin cambiar mangueras de intercooler.", "TALLER", "instalacion_clip_wastegate", "sonajero_wastegate|clip_anti_rattle_soluciona|recupera_pique", "falla_mangueras_intercooler", "", "NO", "SI", CLASE_15, "L3 instalación de clip anti-rattle soluciona holgura mecánica.")
    agregar("G14-L3-08", CLASE_14, "L3", "DTC P0299 en motor 1.4 TSI. Al verificar con máquina de humo a 1 bar el circuito de admisión y mangueras de intercooler están 100% herméticos sin ninguna fuga. Al desacoplar la rótula del actuador eléctrico se comprobó que el brazo de la wastegate está trabado por herrumbre a medio abrir.", "TECNICO", "maquina_humo_1bar", "dtc_p0299|circuito_humo_100_hermetico|brazo_wastegate_trabado_medio_abrir", "fuga_intercooler", "P0299", "NO", "SI", CLASE_15, "L3 prueba de humo hermética confirma compuerta trabada.")
    agregar("G14-L3-09", CLASE_14, "L3", "Mi carro Audi corta el turbo en carretera y prende EPC arrojando P0299. Ya le revisaron todas las mangueras de aire y estan sanas. El mecanico le movio la varilla del turbo con la mano y esta dura trancada, no se mueve ni con alicate.", "ERROR_ORTOGRAFICO", "carretera_fondo", "dtc_p0299|mangueras_sanas|varilla_turbo_trancada_mano", "manguera_rajada", "P0299", "NO", "SI", CLASE_15, "L3 varilla trancada con mangueras sanas y error ortográfico.")
    agregar("G14-L3-10", CLASE_14, "L3", "En aceleración progresiva de 2000 a 4500 rpm el escáner muestra que la presión de sobrealimentación no sube de 0.4 bar relativo. El servomotor del actuador de turbo consume 1.8 amperios en reposo por motor eléctrico en cortocircuito parcial y el eje no ejecuta el autotesteo al dar contacto.", "TECNICO", "autotesteo_contacto", "boost_estancado_0_4bar|consumo_1_8a_reposo|sin_autotesteo", "falla_valvula_alivio_blowoff", "", "NO", "NO", "", "L3 servomotor con consumo excesivo y sin barrido de inicio.")
    agregar("G14-L3-11", CLASE_14, "L3", "Buenas tardes, el auto pierde potencia en autopista cuando quiero pasar a otro vehículo. Se prende la luz EPC y no pasa de 2500 rpm. Apago el contacto, saco la llave, vuelvo a encender y acelera bien un rato hasta que vuelvo a pisar a fondo.", "WHATSAPP", "autopista_rebase", "corte_epc_2500rpm|apagar_y_sacar_llave_resetea", "falla_caja_dsg", "", "NO", "NO", "", "L3 ciclo de llave limpia limp mode de sobrealimentación.")
    agregar("G14-L3-12", CLASE_14, "L3", "Registro de datos en tiempo real revela pico de sobrepresión de 2.3 bar absolutos a 3200 rpm seguido de corte abrupto por protección de motor con DTC P0234. La varilla del actuador no alcanza el tope de apertura máxima impidiendo evacuar el exceso de gases de escape hacia el catalizador.", "TECNICO", "corte_proteccion_p0234", "dtc_p0234|pico_2_3bar|sin_apertura_maxima_escape", "falla_sensor_map", "P0234", "NO", "NO", "", "L3 pico de sobrepresión 2.3 bar activa mapa de protección.")
    agregar("G14-L3-13", CLASE_14, "L3", "El vehículo ingresó con testigo EPC encendido y marcha en modo de emergencia. Se reemplazó el actuador electrónico de la wastegate por repuesto nuevo y se ejecutó la calibración guiada con escáner logrando voltaje de reposo de 3.85V. La presión de turbo se restableció en 1.1 bar en prueba de ruta.", "TALLER", "post_reemplazo_actuador", "reemplazo_actuador_nuevo|voltaje_3_85v_ok|boost_1_1bar_ruta", "dano_turbina", "", "NO", "NO", "", "L3 calibración a 3.85V normaliza presión a 1.1 bar.")
    agregar("G14-L3-14", CLASE_14, "L3", "Sonido de vibración metálica al desacelerar acompañado de pérdida de respuesta en baja. Se verificó con reloj comparador holgura axial de 1.8 mm en la articulación de la varilla de la wastegate. No se evidencian fugas de aceite en los sellos del turbo ni rozamiento de álabes.", "TALLER", "reloj_comparador_articulacion", "holgura_1_8mm_reloj_comparador|sin_fuga_aceite_sellos", "desgaste_eje_turbo", "", "NO", "SI", CLASE_15, "L3 reloj comparador 1.8 mm descarta daño interno de turbina.")
    agregar("G14-L3-15", CLASE_14, "L3", "Falla intermitente bajo temperatura extrema: tras 40 minutos en tráfico pesado el actuador de la compuerta de escape se dilata y queda trabado en 15% de apertura, activando código P0299 al salir a vía rápida. En frío la varilla se desplaza suavemente.", "TECNICO", "dilatacion_termica_trafico", "dtc_p0299|traba_15_porciento_en_caliente|varilla_suave_en_frio", "falla_valvula_n75", "P0299", "NO", "NO", "", "L3 dilatación térmica selectiva a 40 minutos en tráfico.")

    # =========================================================================
    # CLASE 15: Fuga en mangueras de intercooler o turbocompresor danado (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G15-L1-01", CLASE_15, "L1", "Se escucha un silbido fuerte como de aire escapando cuando acelero.", "COTIDIANO", "aceleracion", "silbido_fuerte_aire_escapando", "", "", "SI", "NO", "", "L1 silbido de aire bajo presión.")
    agregar("G15-L1-02", CLASE_15, "L1", "El carro perdió fuerza de golpe y sopla como una aspiradora adelante.", "WHATSAPP", "aceleracion_carga", "soplo_aspiradora_adelante|perdida_fuerza", "", "", "SI", "NO", "", "L1 sonido de soplido frontal con pérdida de empuje.")
    agregar("G15-L1-03", CLASE_15, "L1", "Siento un aullido agudo como sirena de policía al subir las revoluciones.", "COTIDIANO", "subida_revoluciones", "aullido_sirena_policia", "", "", "SI", "NO", "", "L1 sonido de sirena de turbo dañado.")
    agregar("G15-L1-04", CLASE_15, "L1", "Bota bastante humo negro por el tubo de escape cuando piso el acelerador.", "TALLER", "aceleracion_fuerte", "humo_negro_aceleracion", "", "", "SI", "NO", "", "L1 humo negro por pérdida de aire medido.")
    agregar("G15-L1-05", CLASE_15, "L1", "Encontré una manguera gruesa del frente manchada de aceite negro y suelta.", "COTIDIANO", "inspeccion_visual", "manguera_gruesa_aceite_suelta", "", "", "SI", "NO", "", "L1 manguera de intercooler desacoplada con aceite.")
    agregar("G15-L1-06", CLASE_15, "L1", "Se escuchó un estallido como un globo reventado y el auto se quedó sin fuerza.", "WHATSAPP", "aceleracion_autopista", "estallido_globo_reventado|sin_fuerza", "", "", "SI", "NO", "", "L1 desacople o rotura súbita de manguera bajo presión.")
    agregar("G15-L1-07", CLASE_15, "L1", "El turbo silba exageradamente y el motor no tiene empuje en subida.", "TALLER", "subida", "turbo_silba_exagerado|sin_empuje_subida", "", "", "SI", "NO", "", "L1 silbido excesivo sin rendimiento.")
    agregar("G15-L1-08", CLASE_15, "L1", "Sopla mucho aire por el parachoques delantero cuando entra el turbo.", "ERROR_ORTOGRAFICO", "entrada_turbo", "soplo_aire_parachoques", "", "", "SI", "NO", "", "L1 soplido en intercooler con ortografía informal.")
    agregar("G15-L1-09", CLASE_15, "L1", "Bota humo azul espeso y se siente juego en la turbina del motor.", "TALLER", "marcha", "humo_azul_espeso|juego_turbina", "", "", "SI", "NO", "", "L1 sello de turbo roto con humo azul.")
    agregar("G15-L1-10", CLASE_15, "L1", "Fuga masiva de aire comprimido en el circuito de sobrealimentación bajo carga.", "TECNICO", "bajo_carga", "fuga_masiva_aire_comprimido", "", "", "SI", "NO", "", "L1 técnico de pérdida de aire comprimido.")

    # --- L2 (15 casos) ---
    agregar("G15-L2-01", CLASE_15, "L2", "Al acelerar a más de 2000 rpm se escucha un fuerte soplido de aire a presión bajo el capó, el carro se queda sin potencia y empieza a botar humo negro por el escape.", "COTIDIANO", "aceleracion_2000rpm", "soplido_aire_presion|perdida_potencia|humo_negro", "humo_blanco", "P0299", "NO", "SI", CLASE_14, "L2 manguera rajada con soplido y humo negro vs actuador.")
    agregar("G15-L2-02", CLASE_15, "L2", "El turbocompresor emite un sonido agudo de sirena de policía al acelerar en vacío y la turbina presenta juego axial excesivo rozando contra la caracola.", "TALLER", "aceleracion_vacio", "aullido_sirena_policia|juego_axial_roce_caracola", "fuga_mangueras", "", "NO", "NO", "", "L2 turbo dañado con rozamiento de álabes.")
    agregar("G15-L2-03", CLASE_15, "L2", "La manguera de salida del intercooler tiene una raja longitudinal de 5 cm cubierta de aceite por donde escapa todo el aire de soplado al pisar el pedal.", "TALLER", "plena_carga", "manguera_intercooler_rajada_5cm|aceite_y_escape_aire", "falla_bomba_gasolina", "", "NO", "SI", "Bomba de gasolina quemada o con baja presion", "L2 manguera rajada 5 cm visible vs bomba de gasolina.")
    agregar("G15-L2-04", CLASE_15, "L2", "Código P0299 por baja presión de turbo; al acelerar se escucha un silbido continuo delante y la varilla del actuador de la wastegate se mueve perfectamente.", "TECNICO", "aceleracion_marcha", "dtc_p0299|silbido_aire_delantero|varilla_wastegate_mueve_bien", "actuador_turbo_trabado", "P0299", "NO", "SI", CLASE_14, "L2 silbido de fuga con actuador funcionando correctamente.")
    agregar("G15-L2-05", CLASE_15, "L2", "Hola maestro, sentí un estruendo como un tiro en la Panamericana y el carro se quedó sin fuerza botando humo negro y soplando aire como loco.", "WHATSAPP", "autopista_acelerada", "estruendo_desacople|humo_negro|soplido_loco", "falla_motor_electrico", "", "NO", "NO", "", "L2 manguera de intercooler reventada en autopista.")
    agregar("G15-L2-06", CLASE_15, "L2", "El panal del intercooler tiene una fisura en el tanque plástico inferior producida por un golpe de piedra y silba fuerte cada vez que entra la turbina.", "COTIDIANO", "marcha", "fisura_tanque_intercooler|silbido_fuerte_boost", "falla_radiador_agua", "", "NO", "SI", "Fuga en mangueras de refrigerante o radiador picado", "L2 intercooler perforado vs radiador de refrigerante.")
    agregar("G15-L2-07", CLASE_15, "L2", "Humo azul abundante por el escape al acelerar y el nivel de aceite bajó un litro en 300 km; el eje del turbo tiene holgura y pasa aceite al intercooler.", "TALLER", "aceleracion_caliente", "humo_azul_turbo|consumo_aceite_1l_300km|aceite_en_intercooler", "desgaste_anillos", "", "NO", "SI", "Consumo de aceite por desgaste de anillos o retenes", "L2 sellos de turbo pasados de aceite vs aros de pistón.")
    agregar("G15-L2-08", CLASE_15, "L2", "Al acelerar fuerte en subida silva como si tuviera una manguera suelta y el carro no avansa rapido echando humo negro oscuro por el escape.", "ERROR_ORTOGRAFICO", "subida_aceleracion", "silbido_manguera_suelta|humo_negro_oscuro", "falla_chispa", "", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L2 silbido de fuga y humo negro con ortografía informal.")
    agregar("G15-L2-09", CLASE_15, "L2", "Prueba de hermeticidad con máquina de humo a 1.0 bar demostró fuga activa en el acople rápido tipo bayoneta de la entrada del intercooler por sello gastado.", "TECNICO", "prueba_humo_1bar", "fuga_acople_bayoneta_intercooler|sello_gastado", "falla_valvula_alivio", "", "NO", "NO", "", "L2 O-ring de acople bayoneta soplado.")
    agregar("G15-L2-10", CLASE_15, "L2", "El motor tironea al exigir el turbo porque la mezcla se enriquece bruscamente al perder aire comprimido por una abrazadera floja en el tubo de carga.", "TALLER", "carga_turbo", "tironeo_mezcla_rica|aire_perdido_abrazadera_floja", "mezcla_pobre", "", "NO", "SI", "Falla en sensor de oxigeno o mezcla rica", "L2 mezcla rica por fuga post-MAF vs sensor de oxígeno.")
    agregar("G15-L2-11", CLASE_15, "L2", "Buenas, el carro pierde fuerza y silba como tetera caliente cuando acelero. Revisé abajo y la manguera negra gruesa está abierta por la mitad.", "WHATSAPP", "aceleracion", "silbido_tetera_caliente|manguera_abierta_mitad", "falla_transmision", "", "NO", "NO", "", "L2 silbido de tetera por raja en manguera de turbo.")
    agregar("G15-L2-12", CLASE_15, "L2", "El turbo aúlla muy fuerte desde las 1500 rpm; al soltar el conducto de admisión se encontró la propela del compresor con los álabes doblados por ingreso de cuerpo extraño.", "TECNICO", "inspeccion_alabes", "aullido_turbo_1500rpm|alabes_compresor_doblados_fOD", "fuga_manguera", "", "NO", "NO", "", "L2 daño por cuerpo extraño (FOD) en álabes de compresor.")
    agregar("G15-L2-13", CLASE_15, "L2", "Pérdida de potencia en carretera acompañada de soplido de viento en el habitáculo; la manguera acodada del intercooler se hinchó y reventó por fatiga.", "COTIDIANO", "carretera", "soplido_viento_habitaculo|manguera_acodada_reventada", "falla_compresor_ac", "", "NO", "NO", "", "L2 manguera acodada reventada en carretera.")
    agregar("G15-L2-14", CLASE_15, "L2", "Se genera código P0299 por falta de presión; el actuador neumático y la válvula N75 están perfectos, pero el intercooler tiene una fuga en el engrapado lateral.", "TECNICO", "diagnostico_p0299", "dtc_p0299|fuga_engrapado_intercooler|n75_conforme", "falla_actuador_vgt", "P0299", "NO", "SI", CLASE_14, "L2 intercooler fugando con válvula N75 conforme.")
    agregar("G15-L2-15", CLASE_15, "L2", "Al pisar el acelerador se escucha una fuga de aire continua en el frente y sale bocanada de humo negro; no hay fallas de encendido en bujías.", "COTIDIANO", "aceleracion", "fuga_aire_frente|humo_negro", "falla_bujias_encendido", "", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L2 fuga de aire y humo negro descarta bujías.")

    # --- L3 (15 casos) ---
    agregar("G15-L3-01", CLASE_15, "L3", "El vehículo pierde potencia súbitamente al superar 2200 rpm bajo carga, emitiendo un soplido ensordecedor de aire comprimido en la zona delantera derecha y densa humareda negra por el escape con DTC P0299. La prueba de presurización con tapones de 2.5 pulgadas a 1.2 bar reveló una rotura de 6 cm en la manguera inferior de silicona del intercooler empapada en aceite. El actuador del turbo calibra y se desplaza con normalidad.", "TECNICO", "presurizacion_intercooler_1_2bar", "dtc_p0299|rotura_6cm_manguera_silicona|humo_negro_denso|soplido_ensordecedor", "falla_actuador_turbo", "P0299", "NO", "SI", CLASE_14, "L3 rotura de 6 cm en manguera inferior con actuador OK.")
    agregar("G15-L3-02", CLASE_15, "L3", "El turbocompresor emite un silbido agudo continuo similar a sirena policial desde 1400 rpm. Al desmontar el tubo de aspiración se constató juego axial de 2.2 mm y juego radial severo en el eje de la turbina, con rozamiento evidente de los álabes del compresor contra la caracola de aluminio produciendo limalla en el intercooler y consumo de aceite.", "TALLER", "inspeccion_holgura_turbo", "aullido_sirena_policial|juego_axial_2_2mm|roce_alabes_caracola", "fuga_manguera_aire", "", "NO", "SI", CLASE_14, "L3 turbocompresor con holgura axial de 2.2 mm y rozamiento.")
    agregar("G15-L3-03", CLASE_15, "L3", "En plena aceleración en cuesta se escuchó una detonación sorda bajo el capó seguida de pérdida del 60% de la potencia y soplido de escape de aire libre. En el taller se encontró la manguera superior de carga desacoplada del cuerpo de mariposa por rotura de la presilla de retención metálica. El motor de la mariposa y el actuador de turbo están en perfecto estado.", "TALLER", "aceleracion_cuesta", "manguera_desacoplada_mariposa|presilla_rota|perdida_60_potencia", "falla_cuerpo_mariposa", "", "NO", "SI", "Cuerpo de aceleracion o valvula IAC sucia", "L3 desacople de manguera en mariposa con cuerpo OK.")
    agregar("G15-L3-04", CLASE_15, "L3", "Código P0299 (Underboost) y P0101 (MAF Range). La lectura del caudalímetro registra 140 g/s pero el sensor MAP en el colector solo mide 0.4 bar de sobrealimentación. Al inyectar humo a 1.5 bar se detectó fisura en el tanque plástico lateral del intercooler producida por impacto frontal en carretera. No hay daño en la geometría del turbo.", "TECNICO", "prueba_humo_1_5bar", "dtc_p0299_p0101|fisura_tanque_plastico_intercooler|humo_fuga", "falla_geometria_turbo", "P0299", "NO", "SI", CLASE_14, "L3 P0299 y P0101 fisura en tanque lateral de intercooler.")
    agregar("G15-L3-05", CLASE_15, "L3", "Hola maestro, sentí que algo reventó cuando aceleré en la carretera y el carro empezó a silbar como loco botando humo negro espeso por el tubo. Me metí abajo y la manguera que va al enfriador de aire tiene una rajadura grande por donde sale aire caliente con aceite.", "WHATSAPP", "aceleracion_carretera", "manguera_intercooler_rajadura_grande|silbido_loco|humo_negro", "falla_inyector", "", "NO", "SI", "Inyectores sucios o filtro de combustible obstruido", "L3 relato WhatsApp de manguera rajada con humo negro.")
    agregar("G15-L3-06", CLASE_15, "L3", "Humo azul copioso por el escape en aceleración y retención acompañado de silbido metálico áspero. El tubo de escape está bañado de aceite líquido. Al retirar la manguera inferior del intercooler se drenaron 400 ml de aceite de motor acumulado por falla destructiva de los sellos dinámicos del turbocompresor.", "TALLER", "drenaje_intercooler", "drenaje_400ml_aceite_intercooler|falla_sellos_turbo|humo_azul", "desgaste_anillos_motor", "", "NO", "SI", "Consumo de aceite por desgaste de anillos o retenes", "L3 400 ml de aceite en intercooler por sellos de turbo rotos.")
    agregar("G15-L3-07", CLASE_15, "L3", "Al acelerar a más de 2500 rpm el auto tironea con pérdida de boost y fuerte soplido en el frontal. La prueba con spray detector de fugas sobre el circuito presurizado demostró burbujeo continuo en la junta del sensor MAP en el tubo de intercooler por rotura del asiento de plástico.", "TECNICO", "prueba_spray_fugas", "fuga_asiento_sensor_map|burbujeo_spray|soplido_2500rpm", "falla_sensor_map_electrica", "", "NO", "NO", "", "L3 fuga física por asiento rajado de sensor MAP.")
    agregar("G15-L3-08", CLASE_15, "L3", "DTC P0299 en motor 2.0 TDI. Al exigir el acelerador se escucha soplo de aire y el vehículo arroja humo negro denso sin pasar de 90 km/h. Se constató abrazadera de manguera de intercooler partida por óxido, permitiendo que la manguera se infle y abra una brecha de escape de aire bajo 1 bar de presión.", "TALLER", "prueba_ruta_90kmh", "dtc_p0299|abrazadera_partida_oxido|brecha_aire_1bar|humo_negro", "falla_inyector_diesel", "P0299", "NO", "NO", "", "L3 abrazadera partida genera fuga bajo presión.")
    agregar("G15-L3-09", CLASE_15, "L3", "El turbo sopla durisimo como escape de aire y el carro no tiene fuerza en subida botando humo negro. En el taller le pusieron humo a precion y salio humo blanco por la manguera del intercooler que esta rajada abajo donde no se ve a simple vista.", "ERROR_ORTOGRAFICO", "prueba_humo_taller", "manguera_intercooler_rajada_abajo|humo_a_presion|humo_negro", "falla_turbo_interno", "", "NO", "SI", CLASE_14, "L3 manguera rajada en zona oculta con error ortográfico.")
    agregar("G15-L3-10", CLASE_15, "L3", "El cliente reclama falta de potencia y ruido aullante. En banco de flujo se comprobó que el turbocompresor tiene los álabes de la turbina de escape mellados y erosionados por impacto de carbonilla dura desprendida del motor, perdiendo un 40% de eficiencia de sobrealimentación.", "TECNICO", "banco_flujo_turbo", "alabes_turbina_escape_erosionados|perdida_40_porciento_eficiencia", "falla_valvula_wastegate", "", "NO", "SI", CLASE_14, "L3 álabes erosionados descarta actuador de wastegate.")
    agregar("G15-L3-11", CLASE_15, "L3", "Buenas maestro, cuando acelero a fondo para adelantar se escucha un shhhhh fuerte adelante y el carro no avanza, se pone pesadísimo y tira humo negro. Si acelero despacito no suena casi nada. El mecánico encontró la manguera del turbo cuarteada con una grieta.", "WHATSAPP", "aceleracion_fuerte_vs_suave", "shhhhh_fuerte_adelante|humo_negro|manguera_grieta", "falla_bomba_gasolina", "", "NO", "SI", "Bomba de gasolina quemada o con baja presion", "L3 relato WhatsApp de soplido dependiente de carga.")
    agregar("G15-L3-12", CLASE_15, "L3", "Inspección técnica: con el manómetro de presión de turbo conectado en el colector se alcanza apenas 0.3 bar cuando la computadora solicita 1.4 bar. Al mismo tiempo se detecta chorro de aire de alta velocidad saliendo por la junta de goma descolocada en el acople rápido del intercooler.", "TECNICO", "medicion_manometro_colector", "presion_0_3_vs_solicitada_1_4bar|junta_goma_acople_descolocada", "falla_wastegate", "P0299", "NO", "SI", CLASE_14, "L3 junta descolocada en acople rápido vs wastegate.")
    agregar("G15-L3-13", CLASE_15, "L3", "El vehículo emite un silbido estridente de alta frecuencia al acelerar y perdió velocidad punta en carretera. Se desmontó el tubo de salida del turbo comprobando que el silenciador de pulsaciones de plástico está agrietado longitudinalmente en su costura de soldadura.", "TALLER", "alta_frecuencia_carretera", "silenciador_pulsaciones_turbo_agrietado|perdida_velocidad_punta", "falla_eje_turbo", "", "NO", "NO", "", "L3 silenciador de pulsaciones agrietado en soldadura.")
    agregar("G15-L3-14", CLASE_15, "L3", "Humo negro denso bajo carga y DTC P0299. La prueba de presión neumática confirmó fuga en el panal central del intercooler de aire-agua integrado en el múltiple de admisión, permitiendo que el aire presurizado fugue y baje el rendimiento del motor.", "TECNICO", "prueba_intercooler_agua_aire", "dtc_p0299|fuga_panal_intercooler_agua_aire|humo_negro", "falla_actuador_vgt", "P0299", "NO", "SI", CLASE_14, "L3 fuga en intercooler aire-agua integrado.")
    agregar("G15-L3-15", CLASE_15, "L3", "El turbo presenta aullido de sirena de policía audible a más de 20 metros al acelerar en ralentí. Al inspeccionar el eje se verifica rotura del rodamiento hidrodinámico con 1.5 mm de holgura radial permitiendo paso de aceite hacia la admisión y escape sin fugas en mangueras.", "TALLER", "inspeccion_rodamiento_turbo", "aullido_sirena_20m|holgura_radial_1_5mm|rotura_rodamiento_turbo", "fuga_manguera_intercooler", "", "NO", "SI", CLASE_14, "L3 rotura de rodamiento de turbo con holgura radial 1.5 mm.")

    return casos

def main():
    casos = generar_datos_lote03()
    print(f"Total registros generados: {len(casos)}")
    
    out_file = Path("dataset_fase10_lote_03.csv")
    cols = [
        "id", "id_grupo", "clase_objetivo", "macro_sistema", "nivel_informacion",
        "texto_usuario", "tipo_lenguaje", "condicion_operacion", "sintomas_presentes",
        "sintomas_negados", "dtc", "requiere_pregunta", "es_contrastivo",
        "clase_contrastiva", "fuente", "observaciones"
    ]
    
    with open(out_file, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=cols)
        writer.writeheader()
        writer.writerows(casos)
        
    print(f"[OK] Archivo {out_file} guardado exitosamente con {len(casos)} registros.")

if __name__ == "__main__":
    main()
