"""
Generador de registros para Lote 08 de Fase 10 (SUSPENSION_CHASIS) - Parte 1.
Cubre exactamente 120 registros:
- Clase 42: Amortiguadores reventados o bujes de suspension gastados (40 casos: 10 L1, 15 L2, 15 L3)
- Clase 43: Juntas homocineticas o palieres danados (40 casos: 10 L1, 15 L2, 15 L3)
- Clase 44: Llantas desbalanceadas o desalineadas (40 casos: 10 L1, 15 L2, 15 L3)
IDs: F10-L08-0001 a F10-L08-0120.
"""

from typing import List, Dict

CLASE_42 = "Amortiguadores reventados o bujes de suspension gastados"
CLASE_43 = "Juntas homocineticas o palieres danados"
CLASE_44 = "Llantas desbalanceadas o desalineadas"
MACRO = "SUSPENSION_CHASIS"
FUENTE = "SINTETICO_IA"


def obtener_casos_42_44(offset: int = 1) -> List[Dict[str, str]]:
    casos = []
    idx = offset

    def agregar(id_grupo, clase, nivel, texto, lenguaje, condicion, presentes, negados, dtc, req_preg, es_cont, clase_cont, obs):
        nonlocal idx
        reg_id = f"F10-L08-{idx:04d}"
        casos.append({
            "id": reg_id,
            "id_grupo": id_grupo,
            "clase_objetivo": clase,
            "macro_sistema": MACRO,
            "nivel_informacion": nivel,
            "texto_usuario": texto,
            "tipo_lenguaje": lenguaje,
            "condicion_operacion": condicion,
            "sintomas_presentes": presentes,
            "sintomas_negados": negados,
            "dtc": dtc,
            "requiere_pregunta": req_preg,
            "es_contrastivo": es_cont,
            "clase_contrastiva": clase_cont,
            "fuente": FUENTE,
            "observaciones": obs
        })
        idx += 1

    # =========================================================================
    # CLASE 42: Amortiguadores reventados o bujes de suspension gastados (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G42-L1-01", CLASE_42, "L1", "Cada vez que paso por un bache o rompemuelles se siente un golpe seco en la parte de adelante.", "COTIDIANO", "paso_baches", "golpe_seco_adelante_en_baches", "", "", "SI", "NO", "", "L1 golpe seco en baches sin detalles.")
    agregar("G42-L1-02", CLASE_42, "L1", "Hola, siento que el carro rebota demasiado como si fuera una lancha después de pasar un desnivel.", "WHATSAPP", "desnivel_rebote", "rebote_excesivo_tipo_lancha", "", "", "SI", "NO", "", "L1 rebote continuo sin especificar amortiguador.")
    agregar("G42-L1-03", CLASE_42, "L1", "Tiene un golpeteo metálico en la rueda derecha cuando la pista está fea.", "COTIDIANO", "pista_irregular", "golpeteo_rueda_derecha_pista_fea", "", "", "SI", "NO", "", "L1 golpeteo en rueda con terreno irregular.")
    agregar("G42-L1-04", CLASE_42, "L1", "Mi auto cascabelea en la suspension delantera al andar por afirmado.", "COTIDIANO", "camino_afirmado", "cascabeleo_suspension_afirmado", "", "", "SI", "NO", "", "L1 cascabeleo en afirmado.")
    agregar("G42-L1-05", CLASE_42, "L1", "Siento la trompa suelta e inestable cuando paso por huecos de la pista.", "TALLER", "huecos_inestabilidad", "trompa_suelta_inestable_en_huecos", "", "", "SI", "NO", "", "L1 trompa suelta e inestable.")
    agregar("G42-L1-06", CLASE_42, "L1", "Buenas, rechina horrible como cama vieja cuando se mueve la carrocería.", "WHATSAPP", "balanceo_carroceria", "rechinido_cama_vieja_carroceria", "", "", "SI", "NO", "", "L1 crujido tipo cama vieja.")
    agregar("G42-L1-07", CLASE_42, "L1", "El carro se me va de lado y brinca feo en pista con ondulaciones.", "COTIDIANO", "ondulaciones_pista", "brinca_se_va_de_lado_ondulaciones", "", "", "SI", "NO", "", "L1 brinco e inestabilidad en ondulaciones.")
    agregar("G42-L1-08", CLASE_42, "L1", "Ayuda suena un cloc cloc en la llanta izquierda al pasar por piedras.", "ERROR_ORTOGRAFICO", "camino_empedrado", "cloc_cloc_llanta_izquierda_piedras", "", "", "SI", "NO", "", "L1 ruido cloc cloc en piedras.")
    agregar("G42-L1-09", CLASE_42, "L1", "Al frenar siento que la trompa del auto se clava demasiado hacia adelante.", "COTIDIANO", "frenada_hundimiento", "trompa_se_clava_al_frenar", "", "", "SI", "NO", "", "L1 clavado excesivo al frenar.")
    agregar("G42-L1-10", CLASE_42, "L1", "Se escucha un golpe sordo abajo en el piso cada vez que agarro un bache.", "COTIDIANO", "agarre_bache", "golpe_sordo_piso_en_bache", "", "", "SI", "NO", "", "L1 golpe sordo en el piso.")

    # --- L2 (15 casos) ---
    agregar("G42-L2-01", CLASE_42, "L2", "Al pasar baches a 30 km/h se siente un golpe sordo en el trapecio delantero derecho; en pista lisa a 100 km/h no vibra nada el volante.", "COTIDIANO", "baches_30kmh_vs_pista_lisa", "golpe_sordo_trapecio_derecho_baches", "vibracion_volante_100kmh", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L2 golpe en bache sin vibración en pista lisa descarta desbalanceo.")
    agregar("G42-L2-02", CLASE_42, "L2", "El amortiguador delantero izquierdo tiene aceite chorreado en el cuerpo metálico y al pasar rompemuelles el carro rebota 3 veces seguidas.", "TALLER", "rompemuelles_rebote_triple", "amortiguador_chorreado_aceite|rebote_triple_rompemuelles", "falla_frenos", "", "NO", "SI", "Caliper de freno trabado o mordaza pegada (piston agarrotado)", "L2 amortiguador reventado con fuga hidráulica visible y rebote.")
    agregar("G42-L2-03", CLASE_42, "L2", "Golpeteo seco al circular por calles empedradas a baja velocidad; al mover el timón en parado no hay holgura en la cremallera.", "COTIDIANO", "empedrado_baja_velocidad", "golpeteo_seco_empedrado", "holgura_cremallera_en_parado", "", "NO", "SI", "Cremallera de direccion asistida con holgura o fuga", "L2 golpeteo en empedrado sin juego en cremallera.")
    agregar("G42-L2-04", CLASE_42, "L2", "Bujes grandes de los trapecios delanteros completamente cuarteados y rajados; al frenar fuerte se escucha un clonk y la rueda se desplaza hacia atrás.", "TECNICO", "frenada_fuerte_desplazamiento_rueda", "bujes_trapecio_rajados|clonk_al_frenar_desplaza_rueda", "falla_disco_freno", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L2 bujes de trapecio rajados con desplazamiento longitudinal al frenar.")
    agregar("G42-L2-05", CLASE_42, "L2", "Hola maestro, cuando paso baches suena un cascabeleo metálico rápido en la suspensión delantera; no zumba en carretera recta a 90 km/h.", "WHATSAPP", "baches_cascabeleo_vs_carretera", "cascabeleo_metalico_en_baches", "zumbido_carretera_90kmh", "", "NO", "SI", "Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)", "L2 cascabeleo en bache descarta rodamiento de maza.")
    agregar("G42-L2-06", CLASE_42, "L2", "Bieletas de la barra estabilizadora con holgura perceptible con la mano; golpetean de forma continua en pavimento irregular y baches leves.", "TALLER", "pavimento_irregular_bieletas", "bieletas_con_holgura_manual|golpeteo_pavimento_irregular", "falla_semieje", "", "NO", "SI", "Juntas homocineticas o palieres danados", "L2 bieletas con juego manual en baches leves.")
    agregar("G42-L2-07", CLASE_42, "L2", "Inestabilidad y balanceo lateral de la carrocería en curvas a 70 km/h con rebote continuo de la parte trasera tras desniveles de puente.", "COTIDIANO", "curvas_70kmh_desnivel_puente", "balanceo_carroceria_curva|rebote_continuo_trasero", "falla_direccion", "", "NO", "SI", "Cremallera de direccion asistida con holgura o fuga", "L2 amortiguadores traseros descargados provocan cabeceo y balanceo.")
    agregar("G42-L2-08", CLASE_42, "L2", "Crujido áspero como goma reseca al girar el volante en parado o subir rampas; la copela superior del amortiguador tiene el rodamiento trabado.", "TECNICO", "giro_parado_rampas_copela", "crujido_goma_copela_superior|rodamiento_copela_trabado", "falla_cremallera", "", "NO", "SI", "Cremallera de direccion asistida con holgura o fuga", "L2 copela de suspensión cruje al torcer volante.")
    agregar("G42-L2-09", CLASE_42, "L2", "Golpe sordo en el piso del lado del copiloto cada vez que la rueda cae en un hueco; los neumáticos tienen desgaste parejo sin deformación.", "COTIDIANO", "rueda_cae_en_hueco", "golpe_sordo_piso_copiloto_hueco", "desgaste_deforme_neumaticos", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L2 golpe al caer en hueco con neumáticos parejos descarta alineación.")
    agregar("G42-L2-10", CLASE_42, "L2", "Amortiguadores traseros pierden gas y aceite; en carretera el vehículo pierde adherencia en el eje trasero al pasar juntas de dilatación.", "TECNICO", "juntas_dilatacion_adherencia", "perdida_gas_aceite_traseros|perdida_adherencia_eje_trasero", "falla_frenado", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L2 pérdida de gas/aceite trasero genera rebote en juntas de asfalto.")
    agregar("G42-L2-11", CLASE_42, "L2", "Buenas tardes, en pistas bacheadas la tijera izquierda golpea metálicamente; si acelero en recta suave no hay zumbidos ni vibraciones.", "WHATSAPP", "pistas_bacheadas_tijera", "tijera_golpea_en_baches", "zumbidos_vibraciones_recta", "", "NO", "SI", "Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)", "L2 tijera golpea en bache sin ruidos de rodadura en recta.")
    agregar("G42-L2-12", CLASE_42, "L2", "Tope de goma de rebote del vástago del amortiguador destrozado y desintegrado; el amortiguador hace tope de fondo metálico en baches profundos.", "TALLER", "tope_rebote_fondo_metalico", "tope_goma_desintegrado|tope_fondo_metalico_en_baches", "falla_chasis", "", "NO", "NO", "", "L2 tope de poliuretano desintegrado golpea vástago.")
    agregar("G42-L2-13", CLASE_42, "L2", "Silentblocks del puente trasero fisurados y desprendidos de su casquillo metálico; la cola del vehículo derrapa levemente en curvas bacheadas.", "TECNICO", "curvas_bacheadas_derrape_cola", "silentblocks_puente_trasero_fisurados|derrape_cola_en_curvas", "falla_frenos_abs", "", "NO", "SI", "Falla en sensor de velocidad de rueda ABS", "L2 silentblocks de eje trasero con desprendimiento causan deriva.")
    agregar("G42-L2-14", CLASE_42, "L2", "Rechina fuertemente al comprimir la suspensión al subir una vereda o loma; los bujes de la barra estabilizadora están secos y endurecidos.", "COTIDIANO", "subir_vereda_loma", "rechina_al_comprimir_suspension|bujes_estabilizadora_secos", "falla_homocinetica", "", "NO", "SI", "Juntas homocineticas o palieres danados", "L2 bujes de barra estabilizadora resecan crujido en compresión.")
    agregar("G42-L2-15", CLASE_42, "L2", "El tren delantero golpetea en calles adoquinadas; levantando el carro se comprobó juego libre de 5 mm en la rótula inferior de suspensión.", "TALLER", "calles_adoquinadas_juego_rotula", "golpeteo_adoquinado|juego_libre_5mm_rotula_inferior", "falla_llanta", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L2 rótula de suspensión con holgura de 5 mm en adoquín.")

    # --- L3 (15 casos) ---
    agregar("G42-L3-01", CLASE_42, "L3", "Evaluación de suspensión en banco dinamométrico de vibraciones (método Eusama): el amortiguador delantero izquierdo registra una eficacia de adherencia de solo 24% con desequilibrio del 52% respecto al derecho (76%). Inspección visual constata vástago cromado rayado longitudinalmente con fuga activa de aceite hidráulico SAE 5W impregnando el resorte helicoidal. Al descender del banco de prueba y circular sobre resaltos a 25 km/h la carrocería experimenta 4 oscilaciones verticales antes de estabilizarse.", "TECNICO", "banco_eusama_adherencia_24_porciento", "adherencia_eusama_24_porciento|desequilibrio_52_porciento|vastago_rayado_fuga_aceite|4_oscilaciones_resalto", "falla_frenos", "", "NO", "SI", "Caliper de freno trabado o mordaza pegada (piston agarrotado)", "L3 prueba Eusama 24% y fuga en vástago con 4 rebotes.")
    agregar("G42-L3-02", CLASE_42, "L3", "Inspección de tren delantero con barra de palanca en fosa de taller: el buje posterior de la tijera inferior izquierda (silentblock horizontal de caucho-metal) presenta desgarro perimetral completo del elastómero con juego radial de 6.2 mm. En prueba de carretera a 40 km/h al aplicar una frenada intempestiva se produce un golpe metálico de 86 dBA y la rueda se desplaza 15 mm hacia atrás dentro del guardabarros modificando el ángulo de avance temporalmente.", "TECNICO", "palanca_fosa_desgarro_buje_6_2mm", "desgarro_perimetral_silentblock|juego_radial_6_2mm|clonk_frenada_86dba|desplazamiento_15mm", "falla_frenado", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L3 buje de trapecio con desgarro total y juego radial de 6.2 mm.")
    agregar("G42-L3-03", CLASE_42, "L3", "Vehículo utilitario ingresa por cabeceo incontrolable en eje posterior bajo carga de 600 kg. En banco de amortiguadores los cilindros traseros registran 18% de eficacia; ambos amortiguadores monotubo perdieron la precarga de gas nitrógeno a 20 bar quedando únicamente con emulsión espumosa de aceite. En prueba de rebote manual vertical la cola oscila libremente sin amortiguamiento hidráulico.", "TALLER", "perdida_gas_nitrógeno_monotubo_18porciento", "eficacia_18_porciento_banco|perdida_gas_nitrogeno_20bar|emulsion_espumosa|oscilacion_libre", "falla_muelles", "", "NO", "NO", "", "L3 amortiguadores monotubo descargados con pérdida de 20 bar de nitrógeno.")
    agregar("G42-L3-04", CLASE_42, "L3", "Diagnóstico de ruido frontal en Toyota Hilux 4x4: en pista adoquinada a 35 km/h se genera un cascabeleo sordo constante. Se utilizó estetoscopio chasis inalámbrico con 4 pinzas piezoeléctricas: el canal 1 ubicado en la bieleta estabilizadora derecha registró picos de aceleración de 14.8 m/s2 a 180 Hz confirmando holgura de 2.8 mm en la rótula de la bieleta, mientras el canal 2 en la cremallera de dirección se mantuvo en niveles basales de 1.2 m/s2 descartando caja de dirección.", "TECNICO", "estetoscopio_chasis_bieleta_14_8ms2", "bieleta_holgura_2_8mm|picos_14_8ms2_a_180hz|cremallera_basal_1_2ms2", "holgura_cremallera", "", "NO", "SI", "Cremallera de direccion asistida con holgura o fuga", "L3 estetoscopio chasis discrimina bieleta (14.8 m/s2) vs cremallera (1.2 m/s2).")
    agregar("G42-L3-05", CLASE_42, "L3", "Hola maestro, tengo un Kia Rio. Cuando paso por pistas con huecos o asfalto roto suena como si la llanta derecha se fuera a desarmar con un traqueteo seco. En autopista lisa a 110 km/h el auto rueda parejito sin vibrar el timón y el motor no tiene ninguna falla. En el taller me dijeron que el amortiguador botó todo el líquido y el buje del trapecio está rajado.", "WHATSAPP", "rio_baches_vs_autopista_110kmh", "traqueteo_seco_en_asfalto_roto|amortiguador_boto_liquido|buje_rajado", "vibracion_timon_110kmh", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L3 relato WhatsApp de amortiguador sin líquido y buje rajado sin vibrar a 110.")
    agregar("G42-L3-06", CLASE_42, "L3", "Desmontaje de puntal MacPherson delantero: la copela superior con rodamiento axial de bolas se encuentra gripada por corrosión con pérdida del 80% de las bolas de acero. Al girar la dirección con el vehículo detenido el muelle helicoidal se torsionaba y saltaba bruscamente emitiendo crujidos metálicos de 92 dBA que reverberaban en la torreta del chasis.", "TALLER", "desarme_macpherson_copela_gripada", "copela_gripada_corrosion|perdida_bolas_acero|muelle_torsiona_y_salta|crujido_92dba", "falla_cremallera", "", "NO", "SI", "Cremallera de direccion asistida con holgura o fuga", "L3 copela MacPherson gripada hace saltar el muelle con crujido.")
    agregar("G42-L3-07", CLASE_42, "L3", "Medición de holguras en bujes de barra estabilizadora delantera: diámetro interior del elastómero deformado a 24.8 mm frente al diámetro nominal de la barra estabilizadora de 21.0 mm (holgura radial de 3.8 mm). La barra golpea contra la abrazadera metálica de fijación al subchasis generando ruidos secos de baja frecuencia (65 Hz) al ingresar desfasadamente en cunetas o badenes.", "TECNICO", "metrologia_bujes_estabilizadora_3_8mm", "buje_diametro_24_8mm_vs_21_0mm|holgura_3_8mm|impacto_contra_abrazadera_65hz", "falla_caja_cambios", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L3 holgura de 3.8 mm en bujes de estabilizadora genera impacto en subchasis.")
    agregar("G42-L3-08", CLASE_42, "L3", "Mi carro ase un golpe seco y feo adelante cuando agarro un bache en la pista. El amortiguador derecho ta todo chorreao de aceite negro y el carro sigue rebotando tres veses despues de pasar un rompemuelle. El timon no tiembla nada cuando ando en pista lisa a noventa.", "ERROR_ORTOGRAFICO", "baches_rompemuelles_chorreado", "golpe_seco_en_bache|amortiguador_chorreao_aceite|rebota_tres_veses", "vibracion_timon_pista_lisa", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L3 amortiguador chorreado con ortografía informal y descarte de vibración.")
    agregar("G42-L3-09", CLASE_42, "L3", "Análisis con pirómetro infrarrojo de amortiguadores traseros tras 20 km de recorrido por carretera sinuosa con desniveles: el amortiguador trasero derecho registra 28°C (temperatura ambiente, inerte hidráulicamente por fuga total de fluido), mientras el izquierdo registra 58°C (temperatura normal de disipación de energía viscosa). Esto provoca desbalance dinámico del eje trasero con sobreviraje imprevisto.", "TECNICO", "termografia_amortiguadores_28c_vs_58c", "amortiguador_derecho_28c_inerte|izquierdo_58c_normal|fuga_total_fluido|desbalance_eje_trasero", "falla_diferencial", "", "NO", "SI", "Rodajes de caja mecanica o diferencial gastados", "L3 termometría 28°C inerte vs 58°C funcional confirma amortiguador reventado.")
    agregar("G42-L3-10", CLASE_42, "L3", "Inspección de bujes de brazo oscilante trasero en suspensión multibrazo independiente: fisura completa del buje de control de convergencia con holgura angular de 4 grados; bajo frenadas moderadas a 80 km/h la geometría del eje trasero varía dinámicamente induciendo una guiñada lateral de 12 cm sin que exista bloqueo de ruedas ni código ABS.", "TECNICO", "suspension_multibrazo_buje_convergencia", "buje_convergencia_fisurado|holgura_angular_4_grados|guiñada_lateral_12cm_al_frenar", "falla_abs", "", "NO", "SI", "Falla en sensor de velocidad de rueda ABS", "L3 buje de convergencia trasero roto provoca guiñada lateral en frenada.")
    agregar("G42-L3-11", CLASE_42, "L3", "Vástago de amortiguador delantero derecho doblado 1.5 mm tras impacto severo contra bache en alcantarilla; el retén de estanqueidad fue cortado provocando vaciado instantáneo del aceite y atascamiento mecánico del émbolo a mitad de carrera con ruido de traba metálica.", "TALLER", "vastago_doblado_1_5mm_alcantarilla", "vastago_doblado_1_5mm|vaciado_aceite_reten_cortado|atascamiento_embolo", "falla_homocinetica", "", "NO", "SI", "Juntas homocineticas o palieres danados", "L3 vástago doblado 1.5 mm con trabamiento mecánico.")
    agregar("G42-L3-12", CLASE_42, "L3", "Ensayo en banco de rigidez elastomérica: bujes de horquilla delantera con módulo de elasticidad degradado en un 65% debido a contaminación por aceite de motor fugado del retén de cigüeñal. El caucho natural hinchado perdió su capacidad de centrado permitiendo que la horquilla golpee contra el chasis en aceleraciones bruscas desde cero.", "TECNICO", "banco_rigidez_buje_contaminado_aceite", "modulo_elasticidad_degradado_65porciento|caucho_hinchado_por_aceite|horquilla_golpea_chasis", "falla_soportes_motor", "", "NO", "SI", "Juntas homocineticas o palieres danados", "L3 bujes ablandados por aceite de motor golpean contra chasis.")
    agregar("G42-L3-13", CLASE_42, "L3", "Rótula de suspensión delantera con juego axial de 3.2 mm y juego radial de 2.1 mm medido con micrómetro comparador; guardapolvo de caucho cuarteado con ingreso de arena y pérdida total de grasa de litio; genera golpeteo sordo seco de 80 dBA al circular sobre adoquines a 20 km/h.", "TECNICO", "metrologia_rotula_juego_3_2mm", "rotula_juego_axial_3_2mm_radial_2_1mm|arena_en_grasa|golpeteo_adoquines_80dba", "falla_rodaje_rueda", "", "NO", "SI", "Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)", "L3 rótula con juego medido de 3.2 mm en adoquines.")
    agregar("G42-L3-14", CLASE_42, "L3", "Sustitución de amortiguadores defectuosos: amortiguadores de gas bitubo instalados presentan válvula de rebote interna desprendida; al extender el vástago manualmente no ofrece resistencia hidráulica en la carrera de tracción emitiendo gorgoteo de aire con burbujas.", "TALLER", "valvula_rebote_interna_desprendida", "valvula_rebote_desprendida|sin_resistencia_hidraulica_traccion|gorgoteo_aire", "falla_muelle", "", "NO", "NO", "", "L3 válvula de rebote desprendida sin amortiguamiento en tracción.")
    agregar("G42-L3-15", CLASE_42, "L3", "Evaluación vibratoria de habitáculo con acelerómetro triaxial en asiento del conductor: al superar badenes a 30 km/h la aceleración vertical Z alcanza 7.8 m/s2 con amortiguamiento crítico zeta de 0.12 (especificación zeta 0.30-0.40) debido a agotamiento de los 4 amortiguadores originales con 180,000 km.", "TECNICO", "acelerometro_triaxial_amortiguamiento_0_12", "aceleracion_vertical_7_8ms2|amortiguamiento_zeta_0_12_vs_0_35|4_amortiguadores_agotados", "falla_chasis", "", "NO", "NO", "", "L3 acelerometría calcula amortiguamiento zeta en 0.12 confirmando agotamiento.")

    # =========================================================================
    # CLASE 43: Juntas homocineticas o palieres danados (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G43-L1-01", CLASE_43, "L1", "Cuando doblo cerrado hacia la derecha con el acelerador pisado suena un trac trac trac rápido.", "COTIDIANO", "giro_cerrado_derecha", "trac_trac_trac_al_girar_derecha", "", "", "SI", "NO", "", "L1 trac-trac al girar a la derecha.")
    agregar("G43-L1-02", CLASE_43, "L1", "Hola, al doblar en las esquinas acelerando se escucha un chasquido continuo en la rueda delantera.", "WHATSAPP", "doblar_esquinas_acelerando", "chasquido_continuo_doblar_esquinas", "", "", "SI", "NO", "", "L1 chasquido al doblar en esquinas.")
    agregar("G43-L1-03", CLASE_43, "L1", "Siento una vibración fuerte en la trompa del auto cuando acelero en subida.", "COTIDIANO", "aceleracion_subida", "vibracion_trompa_al_acelerar_subida", "", "", "SI", "NO", "", "L1 vibración bajo aceleración.")
    agregar("G43-L1-04", CLASE_43, "L1", "Hace un sonido de matraca metálica cada vez que giro el timón para estacionar.", "COTIDIANO", "maniobra_estacionar", "matraca_metalica_al_girar_timon", "", "", "SI", "NO", "", "L1 matraca al girar timón.")
    agregar("G43-L1-05", CLASE_43, "L1", "El carro tironea y vibra de lado a lado cuando piso el acelerador en carretera.", "TALLER", "aceleracion_carretera", "tironea_vibra_lado_a_lado_acelerar", "", "", "SI", "NO", "", "L1 tironeo y vibración transversal al acelerar.")
    agregar("G43-L1-06", CLASE_43, "L1", "Buenas, vi grasa negra botada en la parte de adentro del aro de la llanta delantera.", "WHATSAPP", "inspeccion_aro", "grasa_negra_botada_aro_delantero", "", "", "SI", "NO", "", "L1 grasa expulsada en aro.")
    agregar("G43-L1-07", CLASE_43, "L1", "Se siente un clac al arrancar en primera y al cambiar a segunda marcha.", "COTIDIANO", "arranque_primera_segunda", "clac_al_arrancar_y_cambiar", "", "", "SI", "NO", "", "L1 clac al traccionar en cambios bajos.")
    agregar("G43-L1-08", CLASE_43, "L1", "Ayuda ase un click click click bien feo cuando doy la buelta en u.", "ERROR_ORTOGRAFICO", "vuelta_en_u", "click_click_click_vuelta_en_u", "", "", "SI", "NO", "", "L1 click en vuelta en U con ortografía informal.")
    agregar("G43-L1-09", CLASE_43, "L1", "La parte delantera tiembla únicamente cuando mantengo el pie en el acelerador.", "COTIDIANO", "pie_en_acelerador", "trompa_tiembla_solo_al_acelerar", "", "", "SI", "NO", "", "L1 temblor delantero bajo carga de pedal.")
    agregar("G43-L1-10", CLASE_43, "L1", "Suena un traqueteo en la rueda izquierda cuando salgo doblando de un semáforo.", "COTIDIANO", "salida_doblando_semaforo", "traqueteo_rueda_izquierda_doblar", "", "", "SI", "NO", "", "L1 traqueteo al salir doblando.")

    # --- L2 (15 casos) ---
    agregar("G43-L2-01", CLASE_43, "L2", "Sonido de matraca metálica de 5 a 6 clics por segundo al girar cerrado a la izquierda en 2da marcha acelerando; con volante recto en recta no suena nada.", "COTIDIANO", "giro_cerrado_izquierda_acelerando", "matraca_5_a_6_clics_giro_izq_acelerando", "ruido_en_recta_volante_centrado", "", "NO", "SI", "Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)", "L2 clic en giro bajo aceleración descarta zumbido de rodamiento.")
    agregar("G43-L2-02", CLASE_43, "L2", "Fuelle de goma de la homocinética exterior derecha rajado con pérdida total de grasa negra grafitada; las bolas de acero trabajan en seco con chasquido al girar.", "TALLER", "inspeccion_fuelle_roto", "fuelle_homocinetica_rajado|grasa_grafitada_perdida|chasquido_al_girar", "falla_frenos", "", "NO", "SI", "Amortiguadores reventados o bujes de suspension gastados", "L2 guardapolvo roto de homocinética con chasquido al torcer.")
    agregar("G43-L2-03", CLASE_43, "L2", "Vibración transversal severa en la carrocería entre 70 y 90 km/h al pisar a fondo el acelerador; al soltar el pedal y rodar en neutro la vibración desaparece instantáneamente.", "TECNICO", "aceleracion_70_90kmh_vs_neutro", "vibracion_transversal_al_acelerar_70_90kmh", "vibracion_en_neutro_inercia", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L2 junta trípode vibra solo en aceleración y desaparece en neutro descartando llantas.")
    agregar("G43-L2-04", CLASE_43, "L2", "Chasquido clac-clac-clac rítmico en rueda delantera derecha al hacer giros en U hacia la izquierda; no produce zumbidos continuos en autopista recta.", "COTIDIANO", "giro_u_izquierda", "clac_clac_clac_en_giro_u", "zumbido_continuo_autopista", "", "NO", "SI", "Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)", "L2 clac-clac en giro en U descarta rodamiento de maza.")
    agregar("G43-L2-05", CLASE_43, "L2", "Junta trípode interior izquierda con pistas del tulipán marcadas con escalones de desgaste; el semieje tiene holgura rotacional excesiva y vibra en subidas.", "TALLER", "inspeccion_tulipan_subida", "tulipan_con_escalones_desgaste|holgura_rotacional_semieje|vibracion_subidas", "falla_caja_cambios", "", "NO", "SI", "Rodajes de caja mecanica o diferencial gastados", "L2 tulipán interior desgastado produce vibración bajo carga.")
    agregar("G43-L2-06", CLASE_43, "L2", "Hola maestro, cuando salgo doblando en las esquinas acelerando suena un trac trac trac; si doblo despacito con el embrague pisado sin acelerar no suena casi nada.", "WHATSAPP", "doblar_acelerando_vs_sin_traccion", "trac_trac_al_doblar_con_gas", "silencio_al_doblar_sin_traccion", "", "NO", "SI", "Amortiguadores reventados o bujes de suspension gastados", "L2 homocinética exterior suena con par motor y calla sin tracción.")
    agregar("G43-L2-07", CLASE_43, "L2", "Palier delantero derecho con juego axial y radial perceptible al sacudirlo con la mano en elevador; al acelerar en recta la dirección cabecea lateralmente.", "TALLER", "prueba_manual_elevador_palier", "juego_axial_radial_palier_manual|direccion_cabecea_acelerando", "falla_cremallera", "", "NO", "SI", "Cremallera de direccion asistida con holgura o fuga", "L2 palier con holgura manual cabecea dirección al acelerar.")
    agregar("G43-L2-08", CLASE_43, "L2", "Crujido metálico repetitivo al dar marcha atrás con la dirección doblada a tope; en marcha adelante en línea recta el vehículo avanza en silencio.", "COTIDIANO", "reversa_tope_direccion", "crujido_repetitivo_reversa_tope_giro", "silencio_recta_marcha_adelante", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L2 crujido en reversa a tope de dirección descarta embrague.")
    agregar("G43-L2-09", CLASE_43, "L2", "Campana y trípode del semieje con holgura en el estriado de acople a la maza de rueda; produce un chasquido metálico seco al invertir la marcha entre 1ra y reversa.", "TECNICO", "inversion_marcha_1ra_reversa", "chasquido_seco_invertir_marcha|holgura_estriado_semieje_maza", "falla_diferencial", "", "NO", "SI", "Rodajes de caja mecanica o diferencial gastados", "L2 holgura en estriado de semieje chasquea al invertir marcha.")
    agregar("G43-L2-10", CLASE_43, "L2", "Semieje largo con apoyo intermedio cuyo rodamiento de soporte está zumbando y la junta homocinética exterior tiene la jaula de bolas fisurada.", "TECNICO", "semieje_largo_soporte_intermedio", "jaula_bolas_fisurada_exterior|rodamiento_soporte_intermedio_zumba", "falla_caja_manual", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L2 semieje partido con jaula fisurada y rodaje de apoyo.")
    agregar("G43-L2-11", CLASE_43, "L2", "Buenas, al entrar a rotondas acelerando la rueda derecha hace clac clac clac continuo; no vibra al frenar desde 100 km/h.", "WHATSAPP", "rotonda_acelerando_derecha", "clac_clac_clac_rotonda_acelerando", "vibracion_al_frenar_100kmh", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L2 clac en rotonda sin vibración al frenar descarta discos alabeados.")
    agregar("G43-L2-12", CLASE_43, "L2", "Abrazadera metálica del guardapolvo de palier suelta; entró arena y agua de lluvia lavando la grasa y rayando la pista esférica de la copa homocinética.", "TALLER", "guardapolvo_abrazadera_suelta", "abrazadera_suelta_ingreso_arena|grasa_lavada_pista_rayada", "falla_amortiguador", "", "NO", "NO", "", "L2 ingreso de arena por abrazadera suelta raya homocinética.")
    agregar("G43-L2-13", CLASE_43, "L2", "Tironeo violento en aceleraciones fuertes entre 50 y 80 km/h en 3ra marcha; se comprobaron llantas perfectamente balanceadas a cero gramos.", "COTIDIANO", "aceleracion_50_80kmh_3ra", "tironeo_violento_al_acelerar_3ra", "llantas_balanceadas_cero_gramos", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L2 tironeo en aceleración con llantas balanceadas a cero confirma palier/trípode.")
    agregar("G43-L2-14", CLASE_43, "L2", "Rotura parcial de la jaula porta-esferas de la junta fija exterior; las bolas se montan una sobre otra provocando trabamiento momentáneo de la rueda en giros.", "TECNICO", "giro_trabamiento_rueda", "jaula_portaesferas_rota|bolas_se_montan|trabamiento_en_giro", "falla_freno_mordaza", "", "NO", "SI", "Caliper de freno trabado o mordaza pegada (piston agarrotado)", "L2 jaula rota de homocinética monta bolas y traba rueda en giro.")
    agregar("G43-L2-15", CLASE_43, "L2", "Al doblar en esquina a la derecha suena un clac clac rítmico proporcional a la velocidad de giro de la rueda; al enderezar el timón se silencia.", "COTIDIANO", "esquina_derecha_ritmico", "clac_clac_ritmico_giro_derecha|se_silencia_al_enderezar", "falla_cremallera", "", "NO", "SI", "Cremallera de direccion asistida con holgura o fuga", "L2 clac proporcional a giro que silencia en recta descarta cremallera.")

    # --- L3 (15 casos) ---
    agregar("G43-L3-01", CLASE_43, "L3", "Inspección técnica de semieje delantero derecho en vehículo de tracción delantera: guardapolvo exterior de termoplástico desgarrado con fuga radial de grasa de bisulfuro de molibdeno salpicada en la cara interior de la llanta. En prueba dinámica en circuito cerrado realizando virajes en círculo cerrado a la izquierda con radio de 5.5 metros a 15 km/h bajo par motor de 120 Nm se registra un golpeteo metálico rítmico de 84 dBA a frecuencia de 4.8 Hz (frecuencia de paso de las 6 bolas sobre la pista ranurada). Con la dirección en línea recta y rodando a la misma velocidad el nivel sonoro decae a 46 dBA descartando rodamiento de maza.", "TECNICO", "viraje_circulo_5_5m_par_120nm", "fuelle_desgarrado_grasa_moly|chasquido_84dba_a_4_8hz_giro|decae_a_46dba_en_recta", "falla_rodaje_maza", "", "NO", "SI", "Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)", "L3 viraje en círculo 15 km/h a 120 Nm acusa 84 dBA a 4.8 Hz confirmando homocinética exterior.")
    agregar("G43-L3-02", CLASE_43, "L3", "Diagnóstico de sacudida transversal de carrocería en aceleración: en recta lisa a 80 km/h al presionar el acelerador al 100% de carga el vehículo experimenta una oscilación lateral de 2.4 mm en la trompa a frecuencia de 18 Hz; en el instante exacto en que se suelta el acelerador o se engrana punto muerto a la misma velocidad de 80 km/h la oscilación cesa instantáneamente (0.1 mm). Se desmontó el semieje izquierdo constatando que el tulipán de la junta trípode interior presenta 3 surcos de desgaste por fatiga de 1.1 mm de profundidad en las pistas de rodillos.", "TECNICO", "oscilacion_lateral_2_4mm_carga_vs_neutro", "oscilacion_lateral_2_4mm_a_18hz_bajo_carga|cesa_a_0_1mm_al_soltar_gas|surcos_tulipan_1_1mm", "desbalanceo_ruedas", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L3 oscilación lateral de 2.4 mm que cesa en neutro confirma trípode interior vs desbalanceo.")
    agregar("G43-L3-03", CLASE_43, "L3", "Desarme en banco de junta homocinética fija de 6 bolas tipo Rzeppa: la jaula porta-bolas de acero templado presenta fractura transversal limpia en dos de las ventanas de alojamiento. Dos bolas de acero de 19.05 mm muestran aplastamiento superficial y craterización por trabajar desalineadas con holgura angular de 14 grados. Al realizar giros de prueba en banco a 30 grados de deflexión el conjunto se bloquea mecánicamente impidiendo la rotación suave.", "TALLER", "desarme_banco_rzeppa_jaula_fracturada", "jaula_rzeppa_fracturada_dos_ventanas|bolas_con_craterizacion|holgura_angular_14_grados|bloqueo_en_banco", "falla_caja_cambios", "", "NO", "SI", "Rodajes de caja mecanica o diferencial gastados", "L3 banco confirma fractura de jaula Rzeppa con holgura de 14 grados.")
    agregar("G43-L3-04", CLASE_43, "L3", "Hola maestro, tengo un Honda Civic. Cuando volteo en las esquinas acelerando suena un trac-trac-trac rápido como matraca en la rueda izquierda, pero si paso por la misma curva sin acelerar en neutro no suena nada. En recta a 120 km/h el auto rueda parejito sin vibrar el volante. En la serviteca me dijeron que el fuelle de la homocinética está rajado y botó toda la grasa.", "WHATSAPP", "civic_esquinas_acelerando_vs_neutro", "trac_trac_en_esquina_acelerando|silencio_en_neutro|fuelle_rajado_sin_grasa", "vibracion_120kmh_recta", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L3 relato WhatsApp de trac-trac en esquina bajo tracción que calla en neutro.")
    agregar("G43-L3-05", CLASE_43, "L3", "Análisis con acelerómetros de vibración en semieje delantero derecho: bajo aceleración de par máximo en 3ra marcha (240 Nm a 2200 rpm) se registra aceleración RMS de 6.8 m/s2 en el soporte del palier intermedio. La junta trípode articulada presenta juego radial de 1.4 mm en los rodillos de agujas del trípode por pérdida de lubricante termorresistente NLGI 1.5, provocando desalineación cinemática del árbol de transmisión.", "TECNICO", "acelerometria_palier_6_8ms2_a_240nm", "aceleracion_6_8ms2_a_240nm|juego_radial_tripode_1_4mm|perdida_grasa_nlgi", "falla_soporte_motor", "", "NO", "SI", "Amortiguadores reventados o bujes de suspension gastados", "L3 acelerómetro registra 6.8 m/s2 bajo 240 Nm por holgura de 1.4 mm en trípode.")
    agregar("G43-L3-06", CLASE_43, "L3", "Verificación de palier en torno con reloj comparador de carátula: el semieje macizo de acero forjado presenta un alabeo residual de 1.85 mm en el centro del eje (tolerancia máxima OEM 0.25 mm) debido a golpe contra piedra en trocha. Al circular a más de 60 km/h el desbalance geométrico induce vibración sinusoidal que varía linealmente con la velocidad de giro de la rueda pero no con las RPM del motor.", "TECNICO", "torno_reloj_comparador_alabeo_1_85mm", "alabeo_palier_1_85mm_vs_0_25mm|vibracion_sinusoidal_con_velocidad_rueda", "falla_embrague", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L3 torno confirma alabeo de palier de 1.85 mm tras impacto.")
    agregar("G43-L3-07", CLASE_43, "L3", "Mi carro ase un trac trac trac muy fuerte cuando doblo a la derecha pa entrar a mi cochera acelerando despacito. Si me meto a la cochera en neutro con el vuelito no suena nada. El mecanico le bajo el palier y la copa taba con las canastillas partidas y llena de tierra por el fuelle roto.", "ERROR_ORTOGRAFICO", "cochera_acelerando_vs_neutro", "trac_trac_al_doblar_acelerando|silencio_en_neutro_con_vuelito|copa_canastillas_partidas_tierra", "falla_caja", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L3 palier con canastillas partidas en cochera con ortografía informal.")
    agregar("G43-L3-08", CLASE_43, "L3", "Rotura por fatiga de chaveta de seguridad y desprendimiento de retén de estrías de semieje dentro del planetario del diferencial: el palier izquierdo experimenta desplazamiento axial libre de 14 mm provocando que la junta homocinética trabaje en su límite de extensión angular (45 grados) con golpeteo seco y roce metálico contra la maza al comprimir la suspensión en baches pronunciados.", "TECNICO", "desplazamiento_axial_palier_14mm", "desplazamiento_axial_14mm|extension_angular_limite_45grados|roce_contra_maza", "falla_diferencial_interno", "", "NO", "SI", "Rodajes de caja mecanica o diferencial gastados", "L3 desplazamiento de 14 mm en palier por retén suelto.")
    agregar("G43-L3-09", CLASE_43, "L3", "Termografía infrarroja de semiejes tras 30 minutos de conducción urbana: la copa homocinética exterior delantera izquierda alcanza 112°C con humo tenue de grasa calcinada (temperatura de copa derecha normal 48°C). La junta homocinética sufrió gripado por falta de lubricación tras romperse el guardapolvo, provocando fricción acero contra acero en las pistas de contacto.", "TECNICO", "termografia_homocinetica_112c_vs_48c", "temperatura_copa_112c_vs_48c|grasa_calcinada|gripado_friccion_acero_acero", "falla_mordaza_freno", "", "NO", "SI", "Caliper de freno trabado o mordaza pegada (piston agarrotado)", "L3 termografía acusa 112°C en copa homocinética calcinada.")
    agregar("G43-L3-10", CLASE_43, "L3", "Evaluación de holgura circunferencial en banco de torsión: el semieje delantero derecho registra un juego angular libre de 18.5 grados entre la entrada del tulipán y la maza de rueda (especificación máxima 3.0 grados). Al realizar ensayos de aceleración y desaceleración rápida en 1ra marcha se genera un impacto acústico seco de 88 dBA perceptible en la palanca de cambios.", "TECNICO", "banco_torsion_holgura_angular_18_5grados", "juego_angular_18_5_grados_vs_3_0_grados|impacto_acustico_88dba|aceleracion_desaceleracion", "falla_caja_cambios", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L3 banco de torsión registra 18.5° de juego angular libre en semieje.")
    agregar("G43-L3-11", CLASE_43, "L3", "Cliente reclama sacudida delantera al incorporarse a autopista en 3ra y 4ta velocidad. Se colocaron cámaras de inspección en los bajos del chasis enfocando ambos semiejes: durante la aceleración a 2800 rpm el palier derecho experimenta flexión y cabeceo elíptico de 8 mm provocado por desgaste asimétrico de los 3 rodillos del trípode interior en su guía de deslizamiento.", "TALLER", "camara_chasis_cabeceo_eliptico_8mm", "cabeceo_eliptico_8mm_palier|desgaste_asimetrico_3_rodillos_tripode|sacudida_autopista", "falla_llantas", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L3 cámara en chasis constata cabeceo de 8 mm en palier bajo aceleración.")
    agregar("G43-L3-12", CLASE_43, "L3", "Sustitución de semieje completo tras fractura por corte del eje estriado de la homocinética exterior: la rotura ocurrió exactamente en el entalle de fijación de la tuerca de maza debido a fatiga por microfisuras originadas por torque excesivo de apriete (420 Nm vs especificado 220 Nm) en un cambio de rodamiento previo.", "TECNICO", "fractura_eje_estriado_sobretorque", "fractura_por_corte_eje_estriado|sobretorque_420nm_vs_220nm|fatiga_microfisuras", "falla_rodamiento", "", "NO", "SI", "Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)", "L3 fractura de punta de palier por sobretorque de 420 Nm.")
    agregar("G43-L3-13", CLASE_43, "L3", "Inspección de guardapolvo interior de palier (lado caja de cambios): abrazadera Oetiker de acero inoxidable rota con desprendimiento del labio del fuelle sobre el retén del diferencial; pérdida de 180 ml de valvulina 75W-90 de la transmisión manual que empapó el palier provocando chasquido y golpeteo bajo carga.", "TALLER", "abrazadera_oetiker_rota_fuga_valvulina", "abrazadera_oetiker_rota|fuga_valvulina_75w90_180ml|chasquido_bajo_carga", "falla_aceite_caja", "", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L3 abrazadera rota de fuelle interior fuga aceite de caja con chasquido.")
    agregar("G43-L3-14", CLASE_43, "L3", "Prueba de esfuerzo en rampa con 18% de pendiente con dirección girada 35 grados: al aplicar embrague y acelerador para arranque en pendiente la homocinética exterior emite chasquidos metálicos violentos de 94 dBA con salto cinemático en el volante; en rampa recta el arranque se produce sin ningún chasquido.", "TECNICO", "rampa_pendiente_18porciento_giro_35grados", "chasquido_94dba_rampa_con_giro_35grados|salto_cinematico_volante|silencio_en_rampa_recta", "falla_disco_embrague", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L3 rampa al 18% con giro a 35° dispara chasquido de 94 dBA.")
    agregar("G43-L3-15", CLASE_43, "L3", "Metrología de rodillos de agujas en trípode de palier: 12 agujas fracturadas y pulverizadas en el rodillo número 2; las partículas de acero templado destruyeron la superficie tratada térmicamente de la cazoleta provocando juego radial de 2.2 mm y sacudida transversal al transferir torque en marchas 2da y 3ra.", "TECNICO", "metrologia_agujas_tripode_pulverizadas", "12_agujas_pulverizadas_en_rodillo|juego_radial_2_2mm|sacudida_al_transferir_torque", "falla_caja_cambios", "", "NO", "SI", "Rodajes de caja mecanica o diferencial gastados", "L3 rodillo de trípode con 12 agujas pulverizadas genera sacudida en 2da y 3ra.")

    # =========================================================================
    # CLASE 44: Llantas desbalanceadas o desalineadas (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G44-L1-01", CLASE_44, "L1", "El volante empieza a temblar fuerte cuando voy a más de 80 km/h en la carretera.", "COTIDIANO", "carretera_80kmh", "volante_tiembla_a_mas_de_80kmh", "", "", "SI", "NO", "", "L1 volante tiembla a 80 km/h sin detalles.")
    agregar("G44-L1-02", CLASE_44, "L1", "Hola, si suelto el timón en pista recta el carro se jala de inmediato hacia la derecha.", "WHATSAPP", "pista_recta_soltar_timon", "se_jala_hacia_la_derecha_en_recta", "", "", "SI", "NO", "", "L1 jaloneo hacia la derecha al soltar timón.")
    agregar("G44-L1-03", CLASE_44, "L1", "Siento una vibración en el piso y en el asiento a cierta velocidad.", "COTIDIANO", "cierta_velocidad_piso", "vibracion_piso_y_asiento_velocidad", "", "", "SI", "NO", "", "L1 vibración en asiento a cierta velocidad.")
    agregar("G44-L1-04", CLASE_44, "L1", "Las llantas delanteras se están gastando disparejas por el borde de adentro.", "COTIDIANO", "desgaste_borde_interno", "llantas_gastando_disparejas_borde_adentro", "", "", "SI", "NO", "", "L1 desgaste disparejo interior.")
    agregar("G44-L1-05", CLASE_44, "L1", "Para llevar el auto recto tengo que mantener el timón un poco chueco hacia un lado.", "COTIDIANO", "timon_chueco_en_recta", "timon_chueco_para_ir_recto", "", "", "SI", "NO", "", "L1 volante descentrado en recta.")
    agregar("G44-L1-06", CLASE_44, "L1", "Buenas tardes, vibra todo el carro entre 90 y 100 por hora y luego se calma.", "WHATSAPP", "rango_90_100_kmh", "vibra_entre_90_y_100_luego_calma", "", "", "SI", "NO", "", "L1 ventana de vibración 90-100 km/h.")
    agregar("G44-L1-07", CLASE_44, "L1", "Noto que el carro se desvía solo hacia el lado del copiloto en la autopista.", "TALLER", "desvio_autopista", "desvio_hacia_copiloto_autopista", "", "", "SI", "NO", "", "L1 desvío lateral en autopista.")
    agregar("G44-L1-08", CLASE_44, "L1", "El timon tiembla orrible entre ochenta y cien por hora.", "ERROR_ORTOGRAFICO", "velocidad_80_100", "timon_tiembla_entre_ochenta_y_cien", "", "", "SI", "NO", "", "L1 temblor de timón con ortografía informal.")
    agregar("G44-L1-09", CLASE_44, "L1", "Se escucha un zumbido ondulante de llantas como si el neumático estuviera deformado.", "COTIDIANO", "rodaje_ondulante", "zumbido_ondulante_llanta_deformada", "", "", "SI", "NO", "", "L1 zumbido ondulante de neumático.")
    agregar("G44-L1-10", CLASE_44, "L1", "Al soltar las manos del volante el coche se cruza hacia el carril izquierdo.", "COTIDIANO", "soltar_manos_desvio_izq", "se_cruza_al_carril_izquierdo_al_soltar", "", "", "SI", "NO", "", "L1 deriva a la izquierda al soltar manos.")

    # --- L2 (15 casos) ---
    agregar("G44-L2-01", CLASE_44, "L2", "Vibración oscilatoria en el volante exactamente entre 85 y 105 km/h en pista lisa; no vibra al frenar ni vibra por debajo de 70 km/h.", "COTIDIANO", "ventana_85_105kmh_pista_lisa", "vibracion_volante_85_a_105kmh", "vibracion_al_frenar|vibracion_bajo_70kmh", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L2 vibración en ventana 85-105 km/h sin frenar descarta disco alabeado.")
    agregar("G44-L2-02", CLASE_44, "L2", "En autopista nivelada a 100 km/h al soltar el volante el vehículo deriva 2 metros a la derecha en 5 segundos; el volante queda torcido 10 grados a la izquierda para ir derecho.", "TALLER", "deriva_autopista_100kmh", "deriva_2m_a_derecha_en_5s|volante_descentrado_10_grados", "falla_frenos", "", "NO", "SI", "Caliper de freno trabado o mordaza pegada (piston agarrotado)", "L2 deriva lateral y volante descentrado descarta mordaza trabada.")
    agregar("G44-L2-03", CLASE_44, "L2", "Neumáticos delanteros con desgaste pronunciado en diente de sierra (feathering) en la banda de rodadura por exceso de convergencia; los amortiguadores no tienen fuga.", "TECNICO", "inspeccion_diente_de_sierra", "desgaste_diente_sierra_feathering|convergencia_incorrecta", "fuga_amortiguadores", "", "NO", "SI", "Amortiguadores reventados o bujes de suspension gastados", "L2 desgaste en diente de sierra por mala convergencia descarta amortiguadores.")
    agregar("G44-L2-04", CLASE_44, "L2", "Pérdida de plomo de contrapeso exterior de 35 gramos en aro delantero izquierdo; genera vibración rítmica en el volante que se activa a partir de 90 km/h.", "TALLER", "plomo_contrapeso_perdido_35g", "plomo_perdido_35g|vibracion_ritmica_volante_a_partir_90kmh", "falla_homocinetica", "", "NO", "SI", "Juntas homocineticas o palieres danados", "L2 pérdida de contrapeso de 35g produce vibración a 90 km/h.")
    agregar("G44-L2-05", CLASE_44, "L2", "Hola maestro, vibra el asiento y el piso entre 90 y 110 km/h pero el volante no vibra nada; me dijeron que son las llantas traseras desbalanceadas.", "WHATSAPP", "vibracion_asiento_piso_traseras", "vibracion_asiento_y_piso_90_110kmh", "vibracion_en_el_volante", "", "NO", "SI", "Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)", "L2 desbalanceo trasero vibra asiento/piso sin vibrar volante descarta rodamiento.")
    agregar("G44-L2-06", CLASE_44, "L2", "Ambos neumáticos delanteros tienen el hombro interior liso en los alambres mientras el exterior conserva 5 mm de huella por caída negativa excesiva.", "TECNICO", "desgaste_hombro_interior_camber", "hombro_interior_en_alambres|exterior_5mm_huella|caida_negativa_excesiva", "falla_suspension", "", "NO", "SI", "Amortiguadores reventados o bujes de suspension gastados", "L2 hombro interior liso por exceso de caída negativa.")
    agregar("G44-L2-07", CLASE_44, "L2", "Al circular a 95 km/h con acelerador pisado o en neutro la vibración del timón se mantiene idéntica; si freno suavemente el auto frena parejo sin pulsaciones.", "COTIDIANO", "crucero_95kmh_gas_vs_neutro", "vibracion_identica_gas_y_neutro_95kmh", "pulsaciones_al_frenar", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L2 vibración constante en neutro y sin pulsación al frenar descarta discos.")
    agregar("G44-L2-08", CLASE_44, "L2", "Aro de aleación con deformación y salto radial de 2 mm por impacto contra bache; al balancear la rueda exige 60 gramos de contrapeso.", "TALLER", "aro_deformado_salto_radial_2mm", "aro_deformado_salto_radial_2mm|exige_60g_balanceo", "falla_rodaje", "", "NO", "SI", "Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)", "L2 aro abollado con salto radial de 2 mm exige 60g.")
    agregar("G44-L2-09", CLASE_44, "L2", "Vehículo jala fuertemente hacia la izquierda tras caer en una zanja; en el taller comprobaron que la rueda izquierda tiene 1 grado de divergencia abierta.", "TALLER", "zanja_divergencia_abierta_1grado", "jala_a_izquierda_por_zanja|divergencia_abierta_1_grado", "falla_cremallera", "", "NO", "SI", "Cremallera de direccion asistida con holgura o fuga", "L2 divergencia abierta de 1° tras zanja jala a la izquierda.")
    agregar("G44-L2-10", CLASE_44, "L2", "Zumbido y rumorosidad de rodadura ondulante en autopista; al pasar la mano por la banda de rodadura del neumático se siente escalonada en los tacos.", "COTIDIANO", "tacto_escalonado_banda", "zumbido_ondulante_rodadura|tacos_escalonados_al_tacto", "falla_rodamiento_maza", "", "NO", "SI", "Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)", "L2 taqueado escalonado en neumáticos zumba en autopista descarta rodamiento.")
    agregar("G44-L2-11", CLASE_44, "L2", "Buenas tardes, cuando viajo a 100 km/h vibra el volante; si acelero a 130 km/h la vibración se apaga por completo, solo lo hace en ese rango.", "WHATSAPP", "rango_100_apaga_130", "vibracion_a_100kmh|apaga_a_130kmh", "vibracion_a_alta_velocidad", "", "NO", "SI", "Juntas homocineticas o palieres danados", "L2 vibración en ventana que apaga a 130 descarta palier.")
    agregar("G44-L2-12", CLASE_44, "L2", "Volante girado 15 grados a la derecha en trayectoria recta; el vehículo no presenta ruidos ni juego en la barra de dirección.", "COTIDIANO", "volante_descentrado_15_grados", "volante_girado_15_grados_en_recta", "ruido_juego_barra_direccion", "", "NO", "SI", "Cremallera de direccion asistida con holgura o fuga", "L2 volante desfasado 15 grados sin juego en cremallera.")
    agregar("G44-L2-13", CLASE_44, "L2", "Llanta trasera derecha con deformación estructural en la carcasa interna (huevo o chichón lateral); produce bamboleo vertical a baja velocidad.", "TALLER", "chichon_lateral_bamboleo", "chichon_lateral_carcasa_deformada|bamboleo_baja_velocidad", "falla_amortiguador", "", "NO", "SI", "Amortiguadores reventados o bujes de suspension gastados", "L2 chichón en carcasa produce bamboleo rítmico.")
    agregar("G44-L2-14", CLASE_44, "L2", "Tendencia direccional a la derecha que obliga a ejercer fuerza constante de 15 N en el timón para mantener el carril; discos no calientan de forma dispar.", "TECNICO", "fuerza_constante_timon_15n", "fuerza_constante_15n_en_timon|tendencia_direccional_derecha", "temperatura_dispar_discos", "", "NO", "SI", "Caliper de freno trabado o mordaza pegada (piston agarrotado)", "L2 fuerza continua de 15 N por alineación descarta mordaza pegada.")
    agregar("G44-L2-15", CLASE_44, "L2", "Vibración en el volante que comenzó justo después de parchar una llanta y no volver a balancearla; antes del pinchazo andaba perfecto.", "COTIDIANO", "parche_sin_balanceo", "vibracion_tras_parchar_llanta_sin_balanceo", "falla_mecanica_previa", "", "NO", "NO", "", "L2 vibración surgida tras parchado sin contrapesos.")

    # --- L3 (15 casos) ---
    agregar("G44-L3-01", CLASE_44, "L3", "Diagnóstico de vibración en banco de balanceo dinámico computarizado: rueda delantera derecha registra desbalance dinámico de 45 gramos en el plano exterior y 25 gramos en el plano interior a 850 rpm (simulando 100 km/h). Al colocar contrapesos de zinc de 45 g y 25 g el desbalance residual se reduce a 0 gramos. En prueba de pista a 100 km/h la vibración del volante disminuye de una amplitud de aceleración RMS de 3.8 m/s2 a 0.2 m/s2. Se descartan discos alabeados dado que al frenar no existe modulación de presión hidráulica ni pulsación.", "TECNICO", "balanceadora_dinamica_45g_25g", "desbalance_45g_exterior_25g_interior|reduccion_a_cero_gramos|amplitud_cae_3_8_a_0_2ms2", "pulsacion_frenado", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L3 balanceo computarizado 45g/25g elimina vibración de 3.8 m/s2 a 100 km/h.")
    agregar("G44-L3-02", CLASE_44, "L3", "Medición en alineadora computarizada 3D con cámaras CCD y dianas de alta definición: el eje delantero registra divergencia total de -0°54' (especificación OEM +0°06' a +0°14' de convergencia positiva), ángulo de caída (camber) izquierdo en -2°18' vs derecho en -0°30' (desequilibrio de caída de 1°48') y avance (caster) simétrico en +3°45'. En carretera esto provoca que el vehículo derive lateralmente 3.5 metros en 100 metros hacia el lado derecho y presente desgaste acelerado en el hombro interno del neumático izquierdo.", "TECNICO", "alineadora_3d_divergencia_menos_0_54", "divergencia_menos_0_54_grados|desequilibrio_camber_1_48_grados|deriva_3_5m_en_100m|desgaste_hombro_interno", "falla_cremallera", "", "NO", "SI", "Cremallera de direccion asistida con holgura o fuga", "L3 alineadora 3D constata divergencia de -0°54' y delta camber de 1°48'.")
    agregar("G44-L3-03", CLASE_44, "L3", "Evaluación de excentricidad y fuerza radial con balanceadora Road Force (rodillo de carga de 550 kg): el neumático delantero izquierdo presenta variación de fuerza radial (RFV) de 145 N (límite máximo 75 N) debido a superposición irregular de lonas de poliéster internas. Esto induce una fuerza vertical oscilante a 11.2 Hz a 90 km/h que hace vibrar el volante a pesar de que el balanceo estático de masas marque cero gramos.", "TECNICO", "road_force_rfv_145n", "variacion_fuerza_radial_rfv_145n_vs_75n|vibracion_a_11_2hz_a_90kmh|balanceo_estatico_cero", "falla_palier", "", "NO", "SI", "Juntas homocineticas o palieres danados", "L3 Road Force mide 145 N de RFV por defecto de carcasa vibrando a 90 km/h.")
    agregar("G44-L3-04", CLASE_44, "L3", "Hola maestro, tengo un Toyota Corolla. En pista lisa a 90 km/h el volante tiembla como un celular en vibrador, pero si bajo a 70 o subo a 120 km/h el temblor desaparece casi por completo. Al pisar el freno el carro frena suavecito sin vibrar nada. En la llantería le pusieron la rueda a la máquina y faltaban 35 gramos en un lado y 20 en el otro.", "WHATSAPP", "corolla_90kmh_vs_frenado_suave", "volante_tiembla_a_90kmh|desaparece_a_70_y_120|frena_suave_sin_vibrar|faltaban_35g_y_20g", "vibracion_al_frenar", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L3 relato WhatsApp de desbalanceo a 90 km/h con descarte explícito de frenado.")
    agregar("G44-L3-05", CLASE_44, "L3", "Inspección de desgaste con profundímetro digital de banda de rodamiento: neumático delantero derecho registra 1.8 mm en el hombro interior, 4.2 mm en el centro y 6.1 mm en el hombro exterior (desgaste cónico asimétrico de 4.3 mm); prueba de alineación confirma ángulo de caída negativa de -2°42' debido a deformación del anclaje del amortiguador tras colisión con berma.", "TECNICO", "profundimetro_desgaste_conico_4_3mm", "profundimetro_1_8mm_vs_6_1mm|desgaste_conico_4_3mm|camber_menos_2_42_grados", "falla_buje_trapecio", "", "NO", "SI", "Amortiguadores reventados o bujes de suspension gastados", "L3 profundímetro mide delta de 4.3 mm en hombros por caída de -2°42'.")
    agregar("G44-L3-06", CLASE_44, "L3", "Análisis con goniómetro digital de centrado de volante: con el vehículo circulando en línea recta a 80 km/h en carril plano sin peralte el volante requiere un desfase angular permanente de 14.5 grados a la izquierda para mantener la trayectoria. La alineadora 3D constata que las barras axiales de dirección fueron reguladas asimétricamente (+0°28' en rueda izquierda y -0°32' en rueda derecha).", "TECNICO", "goniometro_volante_desfase_14_5_grados", "desfase_volante_14_5_grados_en_recta|barras_axiales_asimetricas|alineacion_descompensada", "falla_cremallera", "", "NO", "SI", "Cremallera de direccion asistida con holgura o fuga", "L3 goniómetro mide desfase de 14.5° por regulación asimétrica de axiales.")
    agregar("G44-L3-07", CLASE_44, "L3", "Mi carro ase una vibrasion muy fuerte en el timon cuando voy a noventa en la panamericana. Si suelto el acelerador en neutro sigue vibrando igualito a noventa. Pero cuando freno no tiembla nada de nada. El de la llanteria me mostro que el aro de fierro taba golpeao y le faltaba 40 gramos de plomo.", "ERROR_ORTOGRAFICO", "vibrasion_90_panamericana_neutro", "vibrasion_en_el_timon_a_noventa|sigue_en_neutro|no_tiembla_al_frenar|falta_40g_plomo", "vibracion_frenado", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L3 vibración a 90 km/h que sigue en neutro y no vibra al frenar con ortografía informal.")
    agregar("G44-L3-08", CLASE_44, "L3", "Inspección de runout radial y lateral de rueda completa montada en buje con reloj comparador de carátula: salto radial del neumático de 1.9 mm (especificación máxima 0.8 mm) y alabeo lateral del aro de 1.4 mm. Esto genera vibración de primer armónico a 13.5 Hz a 100 km/h provocando fatiga en la columna de dirección.", "TECNICO", "reloj_comparador_salto_radial_1_9mm", "salto_radial_neumatico_1_9mm|alabeo_aro_1_4mm|primer_armonico_13_5hz_a_100kmh", "falla_rodaje_maza", "", "NO", "SI", "Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)", "L3 reloj comparador mide salto radial de 1.9 mm en neumático.")
    agregar("G44-L3-09", CLASE_44, "L3", "Vehículo presenta arrastre direccional hacia la derecha con ángulo de empuje (thrust angle) del eje trasero desfasado en +0°38' respecto al eje geométrico central. El eje trasero rígido se encuentra desalineado por impacto lateral contra bordillo provocando que el auto circule 'de costado' (dog tracking) con desgaste prematuro en los hombros externos de ambas llantas derechas.", "TECNICO", "angulo_empuje_thrust_angle_0_38", "thrust_angle_trasero_mas_0_38_grados|dog_tracking_de_costado|desgaste_hombros_derechos", "falla_amortiguadores", "", "NO", "SI", "Amortiguadores reventados o bujes de suspension gastados", "L3 thrust angle trasero de +0°38' produce efecto dog tracking y deriva.")
    agregar("G44-L3-10", CLASE_44, "L3", "Sonometría diferencial de rumorosidad de rodadura: el habitáculo registra 74 dBA a 90 km/h con modulación cíclica de 7 Hz debida a desgaste en facetas poligonales (cupping) en los neumáticos traseros provocado por rodar 40,000 km sin rotación. Al rotar las ruedas a llantas de prueba lisas nuevas el nivel sonoro decae a 58 dBA descartando daño en rodamientos de maza.", "TECNICO", "sonometria_cupping_74dba_vs_58dba", "ruido_74dba_modulacion_7hz_cupping|decae_a_58dba_con_llantas_nuevas|rodamientos_ok", "falla_rodamiento_rueda", "", "NO", "SI", "Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)", "L3 cupping en neumáticos genera 74 dBA que cae a 58 dBA con gomas nuevas descartando rodamientos.")
    agregar("G44-L3-11", CLASE_44, "L3", "Desbalanceo dinámico en ruedas traseras: balanceadora acusa 50 gramos de desbalance estático en rueda trasera izquierda. En carretera abierta entre 95 y 115 km/h el volante permanece completamente quieto pero los respaldos de los asientos delanteros oscilan visiblemente con amplitud de 5 mm y el espejo retrovisor interior vibra empañando la visión trasera.", "TALLER", "desbalance_trasero_50g_oscilacion_asientos", "desbalance_trasero_50g|volante_quieto|respaldos_oscilan_5mm|retrovisor_vibra", "falla_palier", "", "NO", "SI", "Juntas homocineticas o palieres danados", "L3 desbalanceo trasero de 50g vibra asientos y espejo manteniendo volante firme.")
    agregar("G44-L3-12", CLASE_44, "L3", "Comprobación de alineación de dirección tras sustitución de terminales: convergencia delantera descalibrada a +1°12' (exceso de convergencia cerrada de 12 mm en regla métrica). El vehículo presenta una dirección hipersensible en curvas y chirrido continuo de neumáticos en giros a baja velocidad (20 km/h) sobre asfalto pulido de estacionamiento.", "TECNICO", "convergencia_cerrada_1_12_grados", "convergencia_cerrada_mas_1_12_grados|exceso_12mm_convergencia|chirrido_a_20kmh_estacionamiento", "falla_cremallera", "", "NO", "SI", "Cremallera de direccion asistida con holgura o fuga", "L3 convergencia cerrada de +1°12' genera chirrido en maniobras.")
    agregar("G44-L3-13", CLASE_44, "L3", "Medición de concentricidad y balanceo de conjunto aro-neumático: neumático montado con rotación de 180 grados desalineada respecto al punto amarillo de mínima masa del neumático con la válvula del aro; la máquina acusa 65 gramos de desbalance; tras desinflar, rotar la cubierta alineando punto amarillo con válvula el desbalance se reduce naturalmente a 15 gramos.", "TALLER", "optimizacion_match_mounting_punto_amarillo", "desalineacion_punto_amarillo_65g|match_mounting_reduce_a_15g|vibracion_eliminada", "falla_disco_freno", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L3 match mounting con punto amarillo reduce desbalance de 65g a 15g.")
    agregar("G44-L3-14", CLASE_44, "L3", "Evaluación de deriva dinámica con dinamómetro de volante: en pista con 0% de pendiente transversal a 100 km/h el vehículo requiere 2.2 Nm de torque corrector continuo hacia la izquierda para contrarrestar ángulo de avance (caster) desparejo (rueda derecha con +2°10' vs izquierda con +3°40', delta de 1°30' por brazo doblado).", "TECNICO", "torque_corrector_2_2nm_delta_caster", "torque_corrector_2_2nm|delta_caster_1_30_grados|deriva_continua_hacia_derecha", "falla_mordaza_freno", "", "NO", "SI", "Caliper de freno trabado o mordaza pegada (piston agarrotado)", "L3 torque corrector de 2.2 Nm por delta de caster de 1°30'.")
    agregar("G44-L3-15", CLASE_44, "L3", "Vibración armónica de alta frecuencia a 105 km/h analizada con acelerómetro FFT en volante: pico de aceleración de 2.8 m/s2 centrado exactamente en 14.1 Hz correspondiente a 1X velocidad de rotación de rueda (105 km/h con neumático 205/55R16 = 14.1 rps); la balanceadora confirmó 35 gramos de desbalance en rueda delantera izquierda.", "TECNICO", "acelerometria_fft_14_1hz_a_105kmh", "pico_fft_14_1hz_a_105kmh_2_8ms2|frecuencia_1x_rotacion_rueda|desbalance_35g", "falla_palier", "", "NO", "SI", "Juntas homocineticas o palieres danados", "L3 acelerometría FFT confirma pico en 14.1 Hz (1X rueda) por 35g de desbalance.")

    return casos
