"""
Casos de entrenamiento para Fase 10 Lote 07 (TRANSMISIÓN - Parte 2):
- Clase 38: Sobrecalentamiento o solenoides en caja automatica CVT / DSG (40 casos: 10 L1, 15 L2, 15 L3)
- Clase 39: Falla en caja robotizada Dualogic / I-Motion / Easytronic (Fiat / VW) (40 casos: 10 L1, 15 L2, 15 L3)
- Clase 40: Desgaste en collarin de empuje o crapodina de embrague (40 casos: 10 L1, 15 L2, 15 L3)
- Clase 41: Rodajes de transmision manual o eje primario gastados (40 casos: 10 L1, 15 L2, 15 L3)

Total: 160 registros (IDs F10-L07-0161 a F10-L07-0320).
"""

CLASE_38 = "Sobrecalentamiento o solenoides en caja automatica CVT / DSG"
CLASE_39 = "Falla en caja robotizada Dualogic / I-Motion / Easytronic (Fiat / VW)"
CLASE_40 = "Desgaste en collarin de empuje o crapodina de embrague"
CLASE_41 = "Rodajes de transmision manual o eje primario gastados"


def obtener_casos_38_41(offset=161):
    casos = []
    idx = offset

    def agregar(id_grupo, clase, nivel, texto, tipo_lenguaje, cond, sint_pres, sint_neg, dtc, req_preg, es_cont, cl_cont, obs):
        nonlocal idx
        reg_id = f"F10-L07-{idx:04d}"
        idx += 1
        casos.append({
            "id": reg_id,
            "id_grupo": id_grupo,
            "clase_objetivo": clase,
            "macro_sistema": "TRANSMISION",
            "nivel_informacion": nivel,
            "texto_usuario": texto.strip(),
            "tipo_lenguaje": tipo_lenguaje,
            "condicion_operacion": cond.strip(),
            "sintomas_presentes": sint_pres.strip(),
            "sintomas_negados": sint_neg.strip(),
            "dtc": dtc.strip(),
            "requiere_pregunta": req_preg.strip(),
            "es_contrastivo": es_cont.strip(),
            "clase_contrastiva": cl_cont.strip(),
            "fuente": "SINTETICO_IA",
            "observaciones": obs.strip()
        })

    # =========================================================================
    # CLASE 38: Sobrecalentamiento o solenoides en caja automatica CVT / DSG (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G38-L1-01", CLASE_38, "L1", "Aparece un mensaje en la pantalla de temperatura de transmisión alta.", "COTIDIANO", "trafico_denso", "mensaje_temperatura_transmision_alta", "", "", "SI", "NO", "", "L1 aviso térmico en transmisión automática.")
    agregar("G38-L1-02", CLASE_38, "L1", "Hola, la caja automática da tirones muy secos al pasar los cambios.", "WHATSAPP", "marcha_urbana", "tirones_secos_cambios_automaticos", "", "", "SI", "NO", "", "L1 tirones en cambios.")
    agregar("G38-L1-03", CLASE_38, "L1", "El carro se queda sin fuerza en subida y las revoluciones oscilan solas.", "COTIDIANO", "subida", "falta_fuerza_subida|rpm_oscilan", "", "", "SI", "NO", "", "L1 oscilación de relación de transmisión.")
    agregar("G38-L1-04", CLASE_38, "L1", "Se prendió la llave inglesa amarilla y la caja no pasa de segunda marcha.", "TALLER", "marcha", "llave_amarilla|caja_trabada_segunda", "", "", "SI", "NO", "", "L1 modo protección limp-mode.")
    agregar("G38-L1-05", CLASE_38, "L1", "Fallo de presión hidráulica por mal funcionamiento de electroválvula proporcional.", "TECNICO", "diagnostico", "fallo_presion_electrovalvula", "", "", "SI", "NO", "", "L1 reporte técnico de solenoide.")
    agregar("G38-L1-06", CLASE_38, "L1", "Al acelerar fuerte la caja resbala como si no enganchara bien la marcha.", "COTIDIANO", "aceleracion_fuerte", "caja_resbala_sin_enganchar", "", "", "SI", "NO", "", "L1 deslizamiento en CVT/DSG.")
    agregar("G38-L1-07", CLASE_38, "L1", "La reversa entra con un golpe fuerte y a veces no quiere entrar.", "COTIDIANO", "maniobra_reversa", "reversa_golpe_fuerte", "", "", "SI", "NO", "", "L1 acople violento de reversa.")
    agregar("G38-L1-08", CLASE_38, "L1", "Mi caja automatica patea feo en frio y parpadea la letra D en el tablero.", "ERROR_ORTOGRAFICO", "arranque_frio", "caja_patea_en_frio|letra_d_parpadea", "", "", "SI", "NO", "", "L1 parpadeo de D con ortografía informal.")
    agregar("G38-L1-09", CLASE_38, "L1", "Buenas, en tráfico lento sale olor a quemado y el carro empieza a vibrar.", "WHATSAPP", "trafico_lento", "olor_quemado_trafico|vibracion_arranque", "", "", "SI", "NO", "", "L1 sobrecalentamiento de embragues en tráfico.")
    agregar("G38-L1-10", CLASE_38, "L1", "Pérdida de presión en mecatrónica de transmisión de doble embrague.", "TECNICO", "inspeccion", "perdida_presion_mecatronica", "", "", "SI", "NO", "", "L1 reporte técnico de módulo mecatrónico.")

    # --- L2 (15 casos) ---
    agregar("G38-L2-01", CLASE_38, "L2", "En transmisión CVT de Nissan Sentra salta aviso de sobrecalentamiento de fluido tras 30 minutos de subida en carretera; el auto se limita a 50 km/h en modo seguro.", "COTIDIANO", "subida_prolongada_cvt", "aviso_sobrecalentamiento_cvt|modo_seguro_50kmh", "falla_motor_calor", "", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L2 sobrecalentamiento térmico característico en CVT.")
    agregar("G38-L2-02", CLASE_38, "L2", "Caja DSG de 7 velocidades DQ200 con DTC P17BF; la bomba hidráulica de la mecatrónica trabaja de forma continua por fisura en el soporte del acumulador de presión.", "TECNICO", "diagnostico_mecatronica_dq200", "dtc_p17bf|bomba_mecatronica_continua|fisura_soporte_acumulador", "falla_caja_robotizada", "P17BF", "NO", "SI", "Falla en caja robotizada Dualogic / I-Motion / Easytronic (Fiat / VW)", "L2 código P17BF en DSG DQ200 vs caja robotizada mono-embrague.")
    agregar("G38-L2-03", CLASE_38, "L2", "Tirones y patinamiento en aceleración en caja CVT con DTC P0746 referente a solenoide de control de presión de línea atascado en posición baja.", "TALLER", "aceleracion_cvt", "dtc_p0746|solenoide_presion_linea_atascado|tirones_patinamiento", "falla_cuerpo_aceleracion", "P0746", "NO", "SI", "Cuerpo de aceleracion o valvula IAC sucia", "L2 código P0746 por solenoide de presión de poleas en CVT.")
    agregar("G38-L2-04", CLASE_38, "L2", "Hola, en mi auto con caja DSG las marchas pares (2da, 4ta y 6ta) no entran; solo funcionan las impares 1ra, 3ra y 5ta tras encenderse el testigo de caja.", "WHATSAPP", "perdida_marchas_pares", "marchas_pares_inoperativas|solo_impares_1_3_5|testigo_caja", "falla_sincronizadores", "", "NO", "SI", "Falla en caja robotizada Dualogic / I-Motion / Easytronic (Fiat / VW)", "L2 desconexión de submódulo de marchas pares en DSG.")
    agregar("G38-L2-05", CLASE_38, "L2", "En transmisión automática de doble embrague mojado (DQ250) la temperatura del aceite alcanza 135°C en embotellamiento con mensaje de advertencia de embragues calientes.", "TECNICO", "telemetria_temperatura_135c", "aceite_alcanza_135c_dq250|aviso_embragues_calientes|trafico", "falla_radiador", "", "NO", "NO", "", "L2 sobrecalentamiento en embrague multidisco húmedo.")
    agregar("G38-L2-06", CLASE_38, "L2", "DTC P0841 en caja CVT referente a rango del sensor de presión de fluido de la polea secundaria; las RPM oscilan entre 2000 y 3500 rpm sin aceleración lineal.", "TALLER", "lectura_dtc_p0841", "dtc_p0841|sensor_presion_polea_secundaria|rpm_oscilan_2000_3500", "falla_sensor_ckp", "P0841", "NO", "SI", "Falla en sensor de posicion de cigueñal (CKP) o arbol de levas (CMP)", "L2 código P0841 por presión errática en polea CVT.")
    agregar("G38-L2-07", CLASE_38, "L2", "Golpe metálico seco al pasar de Neutro a Drive en transmisión DSG; el solenoide de embrague K1 tiene acumulación de viruta metálica en su malla de entrada.", "TECNICO", "inspeccion_solenoide_k1", "golpe_n_a_d|solenoide_k1_viruta_malla", "falla_soporte_caja", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L2 electroválvula K1 obstruida genera acople violento.")
    agregar("G38-L2-08", CLASE_38, "L2", "Mi carro con caja CVT ace un zumbido como licuadora al acelerar y se jalonea feo cuando pasa los 60 km por hora con codigo P0746.", "ERROR_ORTOGRAFICO", "aceleracion_60kmh", "zumbido_licuadora_cvt|jaloneo_60kmh|dtc_p0746", "falla_motor", "P0746", "NO", "NO", "", "L2 zumbido y jaloneo en CVT con ortografía informal.")
    agregar("G38-L2-09", CLASE_38, "L2", "Buenas maestro, en mi Vento DSG parpadea la llave en el tablero y no agarra reversa; me dicen que la bomba de la mecatrónica perdió presión de aceite.", "WHATSAPP", "falla_reversa_dsg", "llave_parpadea_dsg|reversa_no_entra|bomba_mecatronica_sin_presion", "falla_bomba_embrague", "", "NO", "SI", "Falla en bombin o bomba hidraulica de embrague", "L2 mecatrónica DSG sin presión inactiva reversa.")
    agregar("G38-L2-10", CLASE_38, "L2", "Degradación térmica severa de fluido CVT NS-3 con más de 120,000 km sin servicio; el contador de deterioro de aceite de la TCM supera las 210,000 unidades.", "TECNICO", "contador_deterioro_tcm", "contador_deterioro_210000_unidades|fluido_ns3_degradado|patinamiento", "falta_aceite_caja", "", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L2 contador de degradación de aceite CVT excedido.")
    agregar("G38-L2-11", CLASE_38, "L2", "DTC P189C por restricción de funcionamiento debido a aumento insuficiente de presión en acumulador hidráulico de caja automática de doble embrague.", "TECNICO", "diagnostico_p189c", "dtc_p189c|presion_acumulador_insuficiente|perdida_traccion", "falla_bomba_gasolina", "P189C", "NO", "NO", "", "L2 código P189C por despresurización de mecatrónica.")
    agregar("G38-L2-12", CLASE_38, "L2", "En semáforos la transmisión CVT patina de 0 a 20 km/h demorando 4 segundos en acoplar el variador; la presión primaria marca solo 0.3 MPa (especificación 0.7 MPa).", "TALLER", "salida_parado_0_a_20kmh", "demora_4s_acople_cvt|presion_primaria_0_3mpa_baja", "disco_desgastado", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L2 presión primaria baja a 0.3 MPa en variador CVT.")
    agregar("G38-L2-13", CLASE_38, "L2", "Pérdida súbita de tracción a velocidad de crucero con DTC P0962 referente a circuito bajo del solenoide de control de presión de embrague de avance.", "TECNICO", "diagnostico_p0962", "dtc_p0962|solenoide_presion_embrague_avance_bajo|perdida_traccion", "falla_inyeccion", "P0962", "NO", "NO", "", "L2 código P0962 de solenoide de embrague de avance.")
    agregar("G38-L2-14", CLASE_38, "L2", "Vibración severa en carrocería al salir en primera en caja DSG en caliente; los discos del embrague doble seco tienen desgaste irregular por recalentamiento.", "COTIDIANO", "salida_en_caliente", "vibracion_carroceria_primera_caliente|embrague_seco_degradado", "falla_soportes_motor", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L2 alabeo térmico en paquete de doble embrague seco.")
    agregar("G38-L2-15", CLASE_38, "L2", "Caja automática CVT queda bloqueada en relación de transmisión alta fija tras sobrecalentamiento de poleas; al enfriarse durante 1 hora recupera modulación.", "TALLER", "bloqueo_relacion_alta_cvt", "bloqueo_relacion_alta_fija|recupera_al_enfriar_1hora", "falla_motor", "", "NO", "NO", "", "L2 histéresis térmica en paso de poleas variables.")

    # --- L3 (15 casos) ---
    agregar("G38-L3-01", CLASE_38, "L3", "Volkswagen Golf 1.4 TSI con transmisión DSG DQ200 de 7 velocidades presenta pérdida repentina de tracción y mensaje en cuadro 'Error: caja de cambios'. Con escáner ODIS se lee DTC P17BF (Hydraulic Pump Play Protection) y P189C (Function Restriction due to Insufficient Pressure). En línea de datos en vivo la presión hidráulica de la mecatrónica cae de 60 bar a 35 bar en menos de 2 segundos tras apagarse la electrobomba, arrancando la bomba cíclicamente cada 4 segundos. Se desmontó la mecatrónica constatándose fisura circunferencial en la brida roscada de aluminio donde se acopla el acumulador de presión de nitrógeno.", "TECNICO", "diagnostico_odis_p17bf_mecatronica", "dtc_p17bf_p189c|presion_cae_60_a_35bar_en_2s|bomba_activa_cada_4s|fisura_brida_acumulador", "falla_caja_robotizada", "P17BF", "NO", "SI", "Falla en caja robotizada Dualogic / I-Motion / Easytronic (Fiat / VW)", "L3 ODIS confirma P17BF y caída de presión por fisura de carcasa mecatrónica DSG.")
    agregar("G38-L3-02", CLASE_38, "L3", "Nissan X-Trail 2.5 con transmisión CVT Jatco JF011E ingresa en modo de protección tras circular en pendiente de montaña. Al escanear el módulo TCM se registra DTC P0746 (Pressure Control Solenoid 'A' Performance) y P0841 (Transmission Fluid Pressure Sensor/Switch 'A' Circuit). Con manómetro de 50 bar conectado en el puerto de prueba de la polea secundaria se observa presión inestable oscilando entre 12 y 28 bar (consigna estable 38 bar). Al desmontar el cárter inferior se constata la válvula de control de flujo de la bomba de alta presión atascada con marcas de cizallamiento y rayaduras en las caras de las poleas cónicas.", "TALLER", "manometro_50bar_puerto_secundario_cvt", "dtc_p0746_p0841|presion_oscila_12_a_28bar_vs_38bar|valvula_bomba_atascada|rayaduras_poleas", "falla_bomba_aceite_motor", "P0746", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L3 manómetro de 50 bar revela presión oscilante y válvula trabada en CVT.")
    agregar("G38-L3-03", CLASE_38, "L3", "Audi A3 con transmisión S-Tronic / DSG de 6 marchas en baño de aceite (DQ250): el vehículo tironea violentamente en reducciones de 3ra a 2da marcha y salta aviso de sobretemperatura de embrague a los 142°C. El escáner registra DTC P0730 (Incorrect Gear Ratio) y P2714 (Pressure Control Solenoid 'D' Performance). Se analizó el aceite pentosín DSG saliendo con coloración marrón oscura y fuerte olor a quemado; la electroválvula proporcional N216 encargada del embrague K2 presenta resistencia de 14.8 ohms (especificación 4.5 a 6.0 ohms) por degradación del devanado por calor.", "TECNICO", "resistencia_solenoide_n216_14_8ohm", "dtc_p0730_p2714|solenoide_n216_14_8ohm_vs_5ohm|aceite_quemado_142c|tirones_3_a_2", "falla_embrague_mecanico", "P0730", "NO", "SI", "Disco de embrague desgastado o patinando", "L3 resistencia de solenoide N216 en 14.8 ohms por sobrecalentamiento térmico.")
    agregar("G38-L3-04", CLASE_38, "L3", "En vehículo con transmisión CVT tras 140,000 km sin reemplazo de fluido se manifiesta deslizamiento severo bajo aceleración en carretera: el motor se revoluciona a 4500 rpm pero el vehículo acelera de 80 a 90 km/h en 9 segundos con código P0846. La lectura del sensor de temperatura de aceite acusa 128°C continuos; al desarmar la transmisión se evidencia que la correa metálica articulada (Pushbelt) sufrió desgaste abrasivo en los bloques de guiado de acero maraging dejando estrías de 0.2 mm en la polea motriz.", "TECNICO", "inspeccion_pushbelt_acero_maraging", "dtc_p0846|temperatura_fluido_128c|desgaste_pushbelt_estrias_0_2mm|deslizamiento_4500rpm", "falla_motor_potencia", "P0846", "NO", "NO", "", "L3 desgaste abrasivo en correa Pushbelt y temperatura de 128°C con P0846.")
    agregar("G38-L3-05", CLASE_38, "L3", "Hola maestro, tengo un Jetta con caja DSG. Cuando manejo en el tráfico de Lima más de media hora el carro empieza a cabecear feo al salir en primera y sale un cartel en el tablero que dice que la caja está caliente y que frene. Si lo dejo enfriar 20 minutos el carro vuelve a andar normal hasta que vuelve a agarrar tráfico.", "WHATSAPP", "trafico_lima_sobrecalentamiento_dsg", "cabeceo_primera_en_trafico|cartel_caja_caliente|normaliza_al_enfriar_20min", "falla_soportes_motor", "", "NO", "SI", "Falla en caja robotizada Dualogic / I-Motion / Easytronic (Fiat / VW)", "L3 sobrecalentamiento de embragues en tráfico urbano en caja DSG.")
    agregar("G38-L3-06", CLASE_38, "L3", "Evaluación de tiempo de respuesta de electroválvulas en cuerpo de válvulas de CVT: el solenoide PWM de modulación de polea primaria acusa retardo de histéresis hidráulica de 480 milisegundos (especificación máxima 120 ms) con DTC P0962. La corriente de comando medida con pinza amperimétrica muestra rizado parásito de 250 mA debido a cortocircuito parcial entre espiras del actuador magnético provocado por alta temperatura sostenida.", "TECNICO", "analisis_retardo_histeresis_480ms", "dtc_p0962|retardo_histeresis_480ms_vs_120ms|corriente_rizado_250ma_solenoide", "falla_computadora_tcm", "P0962", "NO", "NO", "", "L3 retardo de histéresis de 480 ms en solenoide primario con DTC P0962.")
    agregar("G38-L3-07", CLASE_38, "L3", "Caja automática DSG DQ200 presenta bloqueo total del cambio tras detenerse en pendiente: la mecatrónica no logra desacoplar el embrague K1 quedando el motor calado al frenar a cero. En escáner se registra DTC P176F (Clutch 1 Clutched Unintentionally); la horquilla de accionamiento del embrague 1 presenta el pistón hidráulico interno agarrotado por deformación de su junta de teflón tras pico térmico de 150°C.", "TALLER", "diagnostico_p176f_k1_calado", "dtc_p176f|embrague_k1_no_desacopla_cala_motor|piston_horquilla_agarrotado", "falla_disco_embrague", "P176F", "NO", "SI", "Disco de embrague desgastado o patinando", "L3 código P176F por pistón de horquilla K1 atascado tras pico térmico.")
    agregar("G38-L3-08", CLASE_38, "L3", "Mi carro Nissan Sentra con caja CVT se calento en la subida a Ticlio y en la pantalla salio aviso de caja caliente. El carro no pasaba de 40 por hora y la aguja de las revoluciones saltaba como loca con codigo P0746.", "ERROR_ORTOGRAFICO", "subida_ticlio_cvt", "aviso_caja_caliente|no_pasa_40kmh|rpm_saltaban|dtc_p0746", "falla_motor", "P0746", "NO", "NO", "", "L3 sobrecalentamiento en altura con código P0746 con ortografía informal.")
    agregar("G38-L3-09", CLASE_38, "L3", "Prueba en banco de flujo hidráulico de cuerpo de válvulas de transmisión automática CVT: a 80°C de temperatura de ensayo la fuga de presión interna en el canal de descarga de la polea motriz supera los 1.8 litros por minuto (tolerancia máxima 0.4 L/min) debido a desgaste por fricción del émbolo de aluminio anodizado sobre el cuerpo de aleación.", "TECNICO", "banco_flujo_hidraulico_fuga_1_8lmin", "fuga_canal_polea_1_8lmin_vs_0_4|desgaste_embolo_anodizado|perdida_presion", "falla_bomba_aceite", "", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L3 fuga volumétrica de 1.8 L/min en cuerpo de válvulas CVT.")
    agregar("G38-L3-10", CLASE_38, "L3", "Buenas tardes, en mi Seat León DSG parpadea la letra D en el tablero y no pasa de 2da marcha. En el taller me diagnosticaron la mecatrónica y me mostraron que el motorcito eléctrico que bombea el aceite hidráulico se quemó por trabajar sin parar porque el acumulador no retenía la presión.", "WHATSAPP", "diagnostico_seat_leon_dsg", "d_parpadea_no_pasa_segunda|motor_electrico_mecatronica_quemado|acumulador_sin_presion", "falla_caja_robotizada", "", "NO", "SI", "Falla en caja robotizada Dualogic / I-Motion / Easytronic (Fiat / VW)", "L3 motor de mecatrónica quemado por ciclado continuo en DSG.")
    agregar("G38-L3-11", CLASE_38, "L3", "Desgaste del sensor de carrera del embrague G617 en transmisión DSG de 7 marchas: el sensor Hall acusa desplazamiento estático de 18.5 mm con embrague totalmente cerrado (especificación 12.0 mm) debido a desgaste de los forros de fricción orgánicos del paquete de embrague seco K1, provocando patinamiento a plena aceleración en 3ra y 5ta velocidad.", "TECNICO", "analisis_sensor_carrera_g617_18_5mm", "sensor_g617_18_5mm_vs_12mm|forros_k1_desgastados|patinamiento_3ra_5ta", "falla_embrague_convencional", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L3 cota de sensor G617 en 18.5 mm acusa desgaste de embrague K1.")
    agregar("G38-L3-12", CLASE_38, "L3", "Termometría de radiador auxiliar de aceite de transmisión CVT: delta de temperatura entre entrada y salida de apenas 2°C (temperatura de entrada 112°C y salida 110°C) comprobándose obstrucción parcial del serpentín por lodo metálico de desgaste que impide disipar el calor generado por el variador en régimen de carretera.", "TALLER", "termometria_radiador_auxiliar_delta_2c", "delta_temperatura_radiador_2c|obstruccion_serpentin_lodo|aceite_cvt_a_112c", "falla_radiador_motor", "", "NO", "NO", "", "L3 serpentín obstruido genera delta térmico nulo de 2°C y recalentamiento.")
    agregar("G38-L3-13", CLASE_38, "L3", "DTC P0776 (Pressure Control Solenoid 'B' Performance/Stuck Off) en transmisión automática variable: la electroválvula proporcional no modula la contrapresión de la polea secundaria provocando deslizamiento brusco de la cadena de eslabones basculantes que genera limalla visible en el imán de cárter.", "TECNICO", "diagnostico_dtc_p0776_solenoide_b", "dtc_p0776|solenoide_b_stuck_off|deslizamiento_cadena_variador|limalla_carter", "falla_caja_cambios", "P0776", "NO", "NO", "", "L3 código P0776 por solenoide secundario trabado con generación de limalla.")
    agregar("G38-L3-14", CLASE_38, "L3", "Incompatibilidad de adaptación de embragues tras sustitución de mecatrónica en caja DSG: el procedimiento de ajuste básico canal 060 con herramienta VCDS aborta repetidamente en el paso 255 por falta de presión hidráulica mínima (requiere 45 bar continuos y la bomba entrega 32 bar por desgaste interno de engranajes).", "TALLER", "ajuste_basico_canal_060_aborta", "ajuste_basico_vcds_aborta_paso_255|presion_32bar_insuficiente_vs_45bar", "falla_programacion", "", "NO", "NO", "", "L3 ajuste básico VCDS aborta por déficit de presión hidráulica a 32 bar.")
    agregar("G38-L3-15", CLASE_38, "L3", "Registro de parámetros de transmisión CVT bajo prueba de dinamómetro: con acelerador al 80% las poleas del variador presentan un tiempo de transición de relación corta a relación larga de 3.8 segundos (especificación menor a 1.2 s) acompañado de pico térmico en el líquido de 115°C debido a fugas en los retenes de teflón del pistón de la polea motriz.", "TECNICO", "dinamometro_transicion_variador_3_8s", "transicion_variador_3_8s_vs_1_2s|pico_termico_115c|fuga_retenes_teflon_polea", "falla_motor", "", "NO", "NO", "", "L3 retardo de 3.8s en transición de poleas por fuga en sellos de teflón.")

    # =========================================================================
    # CLASE 39: Falla en caja robotizada Dualogic / I-Motion / Easytronic (Fiat / VW) (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G39-L1-01", CLASE_39, "L1", "La caja robotizada se salta a neutro sola cuando me detengo en el semáforo.", "COTIDIANO", "parada_semaforo", "salto_a_neutro_involuntario", "", "", "SI", "NO", "", "L1 caída espontánea a Neutral en robotizada.")
    agregar("G39-L1-02", CLASE_39, "L1", "Hola, sale un aviso de 'Hacer controlar cambio' y el carro no quiere arrancar.", "WHATSAPP", "contacto", "aviso_controlar_cambio|no_arranca", "", "", "SI", "NO", "", "L1 mensaje típico de falla en robotizada Fiat.")
    agregar("G39-L1-03", CLASE_39, "L1", "Al abrir la puerta del conductor no se escucha el zumbido de la bomba de la caja.", "COTIDIANO", "apertura_puerta", "sin_zumbido_bomba_apertura_puerta", "", "", "SI", "NO", "", "L1 ausencia de precarga electrohidráulica.")
    agregar("G39-L1-04", CLASE_39, "L1", "El auto da tirones bruscos y cabecea feo como si fuera un chofer novato.", "COTIDIANO", "salida_primera", "tirones_bruscos_cabeceo_robotizada", "", "", "SI", "NO", "", "L1 descalibración de embrague robotizado.")
    agregar("G39-L1-05", CLASE_39, "L1", "Pérdida de presión en el acumulador electrohidráulico del grupo robotizado.", "TECNICO", "diagnostico", "perdida_presion_acumulador_robotizado", "", "", "SI", "NO", "", "L1 reporte técnico de robotizada.")
    agregar("G39-L1-06", CLASE_39, "L1", "No entran los cambios y en el tablero parpadea la letra N sin responder.", "TALLER", "marcha", "no_entran_cambios|parpadea_letra_n", "", "", "SI", "NO", "", "L1 bloqueo en Neutro.")
    agregar("G39-L1-07", CLASE_39, "L1", "Gotea un líquido verde clarito por debajo del robot de la caja de cambios.", "COTIDIANO", "estacionamiento", "goteo_liquido_verde_robot", "", "", "SI", "NO", "", "L1 fuga de fluido Tutela CS Speed.")
    agregar("G39-L1-08", CLASE_39, "L1", "Mi carro robotisado no ase los cambios y pita una alarma fea en el tablero.", "ERROR_ORTOGRAFICO", "marcha", "no_hace_cambios|alarma_pitido_tablero", "", "", "SI", "NO", "", "L1 fallo de cambio con ortografía informal.")
    agregar("G39-L1-09", CLASE_39, "L1", "Buenas, en frío funciona pero al calentar se traba y no entra la marcha atrás.", "WHATSAPP", "caliente", "en_frio_ok|caliente_no_entra_reversa", "", "", "SI", "NO", "", "L1 falla térmica en actuador robotizado.")
    agregar("G39-L1-10", CLASE_39, "L1", "Fallo de correlación de potenciómetro de selección o inserción de marchas.", "TECNICO", "inspeccion", "fallo_correlacion_potenciometro_seleccion", "", "", "SI", "NO", "", "L1 reporte técnico de sensor de posición.")

    # --- L2 (15 casos) ---
    agregar("G39-L2-01", CLASE_39, "L2", "En un Fiat Palio con caja Dualogic el cambio cae a Neutral de golpe al detenerse en esquinas; la electrobomba hidráulica del robot no arranca al abrir la puerta del chofer.", "COTIDIANO", "detencion_esquinas", "salto_a_neutro_dualogic|electrobomba_no_arranca_puerta", "falla_caja_automatica", "", "NO", "SI", "Sobrecalentamiento o solenoides en caja automatica CVT / DSG", "L2 caída a Neutral por electrobomba inactiva en Dualogic.")
    agregar("G39-L2-02", CLASE_39, "L2", "Volkswagen Gol I-Motion con DTC P0840 referente a sensor de presión hidráulica del grupo robotizado; la presión se desploma de 45 bar a 22 bar en un solo cambio.", "TECNICO", "diagnostico_i_motion", "dtc_p0840|presion_desploma_45_a_22bar|grupo_robotizado_imotion", "falla_dsg", "P0840", "NO", "SI", "Sobrecalentamiento o solenoides en caja automatica CVT / DSG", "L2 despresurización de acumulador en VW I-Motion vs DSG.")
    agregar("G39-L2-03", CLASE_39, "L2", "Fuga visible de aceite hidráulico verde específico (Tutela CS Speed) por el retén del pistón de acople del embrague del robot Dualogic; nivel en reservorio vacío.", "TALLER", "inspeccion_robot_dualogic", "fuga_tutela_cs_speed|reten_piston_embrague_robot|deposito_vacio", "fuga_aceite_caja", "", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L2 fuga de fluido hidráulico específico del robot vs valvulina.")
    agregar("G39-L2-04", CLASE_39, "L2", "Hola maestro, tengo un Fiat Punto Dualogic. Al acelerar en primera da un zapateo terrible y salta aviso 'Hacer controlar cambio'; me dijeron que el robot está descalibrado.", "WHATSAPP", "salida_primera_dualogic", "zapateo_salida_primera|aviso_hacer_controlar_cambio|descalibrado", "disco_patina", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L2 descalibración de embrague en Dualogic vs disco patinando.")
    agregar("G39-L2-05", CLASE_39, "L2", "Acumulador de presión esférico del sistema robotizado desinflado (membrana de nitrógeno rota); la bomba eléctrica arranca cada vez que se realiza un cambio de marcha.", "TECNICO", "prueba_ciclado_electrobomba", "acumulador_esferico_desinflado|bomba_arranca_cada_cambio", "falla_bomba_embrague", "", "NO", "SI", "Falla en bombin o bomba hidraulica de embrague", "L2 membrana de nitrógeno rota cicla bomba en cada cambio.")
    agregar("G39-L2-06", CLASE_39, "L2", "En Chevrolet Corsa Easytronic el motor no arranca y en el tablero parpadea una letra 'F'; el actuador electromecánico de embrague tiene los carbones gastados.", "TALLER", "diagnostico_easytronic_letra_f", "letra_f_parpadea_easytronic|motor_no_arranca|carbones_actuador_gastados", "falla_motor_arranque", "", "NO", "NO", "", "L2 fallo 'F' clásico en Easytronic por carbones de actuador.")
    agregar("G39-L2-07", CLASE_39, "L2", "DTC P0914 referente a circuito de posición del cambio de marchas en caja robotizada; el potenciómetro de selección de pasillo tiene pistas de carbón gastadas.", "TECNICO", "diagnostico_p0914", "dtc_p0914|potenciometro_seleccion_pistas_gastadas|bloqueo_robot", "falla_selectora_mecanica", "P0914", "NO", "NO", "", "L2 código P0914 de sensor de posición de robot.")
    agregar("G39-L2-08", CLASE_39, "L2", "Mi carro Fiat con caja robotisada pitó una chicharra en marcha y se quedo en neutro sin poder meter cambios en medio de la pista.", "ERROR_ORTOGRAFICO", "bloqueo_en_marcha", "chicharra_alarma|quedo_en_neutro_sin_cambios|caja_robotizada", "falla_caja_automatica", "", "NO", "SI", "Sobrecalentamiento o solenoides en caja automatica CVT / DSG", "L2 alarma y caída a Neutro con ortografía informal.")
    agregar("G39-L2-09", CLASE_39, "L2", "Buenas, el carro arranca bien en frío pero cuando calienta el motor en tráfico la caja I-Motion no engrana la reversa ni la primera velocidad.", "WHATSAPP", "temperatura_trafico_imotion", "imotion_falla_en_caliente|no_engrana_reversa_ni_primera", "falla_embrague", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L2 falla térmica en actuador robotizado I-Motion.")
    agregar("G39-L2-10", CLASE_39, "L2", "Relé de potencia de la electrobomba de la caja robotizada con contactos quemados; la bomba no recibe corriente de 12V y el sistema no levanta presión.", "TALLER", "inspeccion_rele_electrobomba", "rele_electrobomba_quemado|sin_12v_bomba|sin_presion_robot", "falla_fusible", "", "NO", "NO", "", "L2 relé quemado anula accionamiento de bomba.")
    agregar("G39-L2-11", CLASE_39, "L2", "DTC P1818 en sistema Dualogic por falla de control de embrague; el vástago del cilindro de empuje no alcanza la posición de reposo calibrada.", "TECNICO", "diagnostico_dtc_p1818", "dtc_p1818|vastago_cilindro_no_alcanza_reposo|falla_control_embrague", "desgaste_embrague", "P1818", "NO", "SI", "Disco de embrague desgastado o patinando", "L2 código P1818 por desalineación de vástago de embrague.")
    agregar("G39-L2-12", CLASE_39, "L2", "Contaminación del fluido hidráulico del robot con agua por condensación; el líquido está turbio y las electroválvulas proporcionales se traban mecánicamente.", "TALLER", "fluido_tutela_contaminado", "fluido_robot_turbio_agua|electrovalvulas_trabadas", "falta_aceite_caja", "", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L2 fluido del robot contaminado traba electroválvulas.")
    agregar("G39-L2-13", CLASE_39, "L2", "Al desacelerar para doblar en una esquina la transmisión robotizada mete rebaje violento de 3ra a 1ra directamente saltándose la segunda marcha.", "COTIDIANO", "rebaje_brusco_esquina", "rebaje_violento_3ra_a_1ra|se_salta_segunda_marcha", "falla_caja_sincronizadores", "", "NO", "NO", "", "L2 error de lógica de salto de pasillo en robot.")
    agregar("G39-L2-14", CLASE_39, "L2", "Procedimiento de calibración de fin de línea aborta repetidamente por temperatura de embrague calculada superior a 110°C en escáner multimarca.", "TECNICO", "calibracion_fin_de_linea_aborta", "calibracion_aborta_embrague_110c|sobrecalentamiento_robot", "falla_embrague", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L2 calibración de robot abortada por cálculo térmico.")
    agregar("G39-L2-15", CLASE_39, "L2", "Palanca selectora electrónica en consola central no envía señal de cambio manual +/-; la placa de contactos resistivos tiene pistas sucias con sulfato.", "TALLER", "inspeccion_palanca_consola", "palanca_consola_no_envia_senal|contactos_sulfatados", "falla_palanca_varillas", "", "NO", "NO", "", "L2 placa de palanca selectora sulfatada.")

    # --- L3 (15 casos) ---
    agregar("G39-L3-01", CLASE_39, "L3", "En un Fiat Grand Siena 1.6 con transmisión robotizada Dualogic Plus se activa alarma sonora continua con mensaje en pantalla 'Hacer controlar cambio' al quedar en ralentí en semáforos, pasando la caja espontáneamente a Neutral (N). Con escáner se lee DTC P0845 (Transmission Fluid Pressure Sensor) y P1773 (Hydraulic Circuit Pressure Low). En línea de datos la presión hidráulica decae de 48 bar a 28 bar en apenas 6 segundos sin realizar cambios; al abrir la puerta del chofer la electrobomba arranca durante 18 segundos con sonido forzado. Se comprobó que el acumulador esférico de nitrógeno (pulmón de presión) perdió la precarga de 30 bar y tiene fuga por el diafragma.", "TECNICO", "diagnostico_dualogic_pulmon_desinflado", "dtc_p0845_p1773|presion_cae_48_a_28bar_en_6s|pulmon_nitrogeno_sin_precarga|salto_a_neutro", "falla_caja_automatica", "P0845", "NO", "SI", "Sobrecalentamiento o solenoides en caja automatica CVT / DSG", "L3 código P0845 y P1773 por pulmón de presión desinflado en Dualogic.")
    agregar("G39-L3-02", CLASE_39, "L3", "Volkswagen Fox 1.6 con caja robotizada I-Motion presenta trepidación violenta y tirones incontrolables al arrancar en primera velocidad tras 20 minutos de marcha. Con el escáner se evaluó el índice de degradación de embrague arrojando valor de 9200 unidades (límite de adaptación 6000 unidades) y la posición del vástago de embrague acusa oscilaciones de +/- 3.5 mm durante la fase de modulación. Se ejecutó el ajuste básico de adaptación del punto de contacto (Kiss Point) con software VCDS pero el procedimiento arroja 'Error 07' debido a que el retén del actuador de embrague rezuma fluido hidráulico contaminando el forro del disco.", "TALLER", "ajuste_basico_kiss_point_vcds_error07", "degradacion_embrague_9200_unidades|ajuste_kiss_point_error07|actuador_rezuma_fluido", "falla_disco_patina", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L3 ajuste básico Kiss Point falla por contaminación de actuador en I-Motion.")
    agregar("G39-L3-03", CLASE_39, "L3", "Falla de encendido en Chevrolet Meriva con caja robotizada Easytronic: en el cuadro de instrumentos destella la letra 'F' y el motor de arranque no gira. Con escáner se diagnostica DTC P1607 (Clutch Actuator Position Control Error). Al desmontar el actuador electrohidráulico integrado en la caja se constató que los carbones del motor eléctrico de accionamiento del vástago de embrague se desgastaron por completo quedando en 3 mm, bloqueando el émbolo en posición intermedia y dejando la ECU de transmisión en estado de bloqueo por seguridad.", "TECNICO", "diagnostico_easytronic_p1607_carbones", "dtc_p1607_letra_f_easytronic|carbones_motor_embrague_3mm|bloqueo_arranque", "falla_motor_arranque", "P1607", "NO", "NO", "", "L3 código P1607 y letra F por carbones gastados en actuador Easytronic.")
    agregar("G39-L3-04", CLASE_39, "L3", "En un Fiat Palio Dualogic el vehículo arranca bien en frío pero al alcanzar 85°C el sistema se rehúsa a insertar la marcha atrás y la 5ta velocidad emitiendo 3 pitidos de alarma. Con escáner multimarca se lee DTC P0914 (Gear Shift Position Circuit); la medición de voltaje en el potenciómetro de selección de pasillo registra salto abrupto de 1.2V a 4.9V al llegar a la posición del pasillo de reversa debido a desgaste de la pista resistiva por vibración térmica del cuerpo del robot.", "TECNICO", "analisis_potenciometro_seleccion_p0914", "dtc_p0914|potenciometro_pasillo_salto_1_2_a_4_9v|no_entra_reversa_ni_quinta_85c", "falla_caja_sincronizadores", "P0914", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L3 código P0914 por salto de voltaje en potenciómetro a 85°C.")
    agregar("G39-L3-05", CLASE_39, "L3", "Hola maestro, tengo un Fiat Linea Dualogic. En el tráfico cuando me paro en una luz roja el carro se pone solo en neutro y empieza a pitar el tablero con aviso de 'Hacer controlar cambio'. Para que vuelva a andar tengo que apagar el carro, abrir y cerrar la puerta del chofer para que suene el motorcito de la caja y recién me deja poner primera.", "WHATSAPP", "diagnostico_linea_dualogic_semaforo", "salto_a_neutro_en_roja|aviso_controlar_cambio|apagar_abrir_puerta_reactiva", "falla_caja_automatica", "", "NO", "SI", "Sobrecalentamiento o solenoides en caja automatica CVT / DSG", "L3 relato WhatsApp de ciclo de puerta para reactivar bomba Dualogic.")
    agregar("G39-L3-06", CLASE_39, "L3", "Inspección de grupo electrohidráulico Dualogic: el depósito de aceite específico Tutela CS Speed de 0.7 litros se encuentra con nivel en cero; el fluido se derramó en su totalidad a través del retén del sensor de posición de inserción hacia el interior de la campana de la caja, provocando que la electrobomba trabaje en vacío a más de 8000 rpm hasta quemar el bobinado con DTC P0942 (Hydraulic Pressure Unit).", "TALLER", "desarme_robot_tutela_cero_p0942", "dtc_p0942|nivel_tutela_cero|electrobomba_quemada_en_vacio|fuga_reten_posicion", "falta_aceite_caja", "P0942", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L3 código P0942 por bomba quemada en seco tras fuga de Tutela CS Speed.")
    agregar("G39-L3-07", CLASE_39, "L3", "DTC P1773 en Volkswagen Voyage I-Motion; la electrobomba hidráulica del grupo de cambio tarda 32 segundos en presurizar el acumulador desde 35 bar hasta 50 bar (especificación OEM menor a 8 segundos). Al desarmar la bomba de engranajes acoplada al motor eléctrico se verificó desgaste por cavitación en los piñones internos de bombeo provocado por uso de líquido de frenos común en lugar de aceite sintético hidráulico ISO VG 32.", "TECNICO", "tiempo_presurizacion_32s_vs_8s", "dtc_p1773|presurizacion_tarda_32s_vs_8s|desgaste_cavitacion_pinones_bomba", "falla_liquido_frenos", "P1773", "NO", "SI", "Falla en bombin o bomba hidraulica de embrague", "L3 presurización demora 32s vs 8s por cavitación con fluido incorrecto.")
    agregar("G39-L3-08", CLASE_39, "L3", "Mi carro Fiat Palio robotisado ase un sonido de pito agudo cuando boy a doblar y se queda en neutro botando un liquido verde claro aceitoso por debajo del parachoque del lado de la caja con codigo P0845.", "ERROR_ORTOGRAFICO", "fuga_liquido_verde_p0845", "pito_agudo|queda_en_neutro|gotea_liquido_verde_claro|dtc_p0845", "fuga_refrigerante", "P0845", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L3 código P0845 con goteo verde Tutela con ortografía informal.")
    agregar("G39-L3-09", CLASE_39, "L3", "Falla en la electroválvula proporcional de modulación de embrague EV0 en caja Dualogic: la válvula presenta resistencia eléctrica de 2.8 ohms correcta pero al aplicarse modulación PWM de 800 mA el vástago se traba mecánicamente por acumulación de barniz ferroso, impidiendo la apertura suave y provocando que el auto se cale violentamente al detenerse.", "TECNICO", "inspeccion_electrovalvula_ev0_dualogic", "electrovalvula_ev0_trabada_barniz|auto_se_cala_al_frenar|resistencia_2_8ohm_ok", "falla_embrague_mecanico", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L3 electroválvula EV0 trabada mecánicamente cala el motor al detenerse.")
    agregar("G39-L3-10", CLASE_39, "L3", "Buenas tardes, en mi VW Fox I-Motion los cambios pasan a los golpes como si soltara el embrague de golpe. Lo escanearon y salieron códigos P0840 y P0914. Me dijeron que el robot perdió el aprendizaje de las marchas y que el sensor de presión de la caja está marcando cualquier cosa por falso contacto en la ficha.", "WHATSAPP", "diagnostico_fox_imotion_golpes", "cambios_a_los_golpes|dtc_p0840_p0914|perdida_aprendizaje_marchas|falso_contacto_ficha", "falla_caja_sincronizadores", "P0840", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L3 códigos P0840 y P0914 por pérdida de aprendizaje en I-Motion.")
    agregar("G39-L3-11", CLASE_39, "L3", "Análisis con osciloscopio automotriz de la señal del sensor de posición del actuador de embrague: la señal analógica entrega saltos de ruido de 1.5 Vpp superpuestos a la rampa de desplazamiento debido a rotura del blindaje del cableado en el paso de rueda delantero izquierdo, provocando tirones espasmódicos del motor paso a paso.", "TECNICO", "oscilograma_ruido_1_5vpp_posicion", "ruido_1_5vpp_senal_posicion_embrague|blindaje_roto_paso_rueda|tirones_espamodicos", "falla_sensor_ckp", "", "NO", "NO", "", "L3 ruido electromagnético de 1.5 Vpp desestabiliza actuador de embrague.")
    agregar("G39-L3-12", CLASE_39, "L3", "El cliente reclama que el vehículo no permite seleccionar ninguna marcha permaneciendo el indicador de tablero en 'N' parpadeante. Se comprobó que el interruptor de freno de doble circuito montado en la pedalera tiene el contacto secundario abierto (línea de datos del robot no recibe confirmación de freno pisado), bloqueando la orden de inserción de 1ra por enclavamiento de seguridad.", "TALLER", "diagnostico_interruptor_freno_doble_circuito", "n_parpadea_bloqueada|interruptor_freno_contacto_abierto|sin_confirmacion_pedal", "falla_interruptor_stop", "", "NO", "NO", "", "L3 interlock de seguridad: interruptor de pedalier bloquea robot en N.")
    agregar("G39-L3-13", CLASE_39, "L3", "Medición de consumo eléctrico de la electrobomba de grupo robotizado: al activar con escáner el motor consume 28 amperios en arranque y se mantiene en 22 amperios sostenidos (especificación 10 a 14 A) debido a desgaste de cojinetes del inducido eléctrico que provocan sobrecalentamiento del fusible de 30A y disparo térmico.", "TECNICO", "amperaje_electrobomba_22a_vs_12a", "consumo_bomba_22a_vs_12a|cojinetes_inducido_gastados|sobrecalentamiento_fusible_30a", "falla_alternador", "", "NO", "NO", "", "L3 consumo excesivo de 22 A en bomba del robot por cojinetes dañados.")
    agregar("G39-L3-14", CLASE_39, "L3", "Desgaste del pasador mecánico de acoplamiento entre el pistón hidráulico del robot y la horquilla de desembrague de la caja manual: holgura de 4.2 mm en el perno esférico genera un juego muerto que la TCM interpreta como desgaste excesivo del disco, limitando la salida y activando mensaje de advertencia en tablero.", "TALLER", "holgura_perno_esferico_4_2mm", "holgura_perno_esferico_4_2mm|juego_muerto_horquilla|tcm_limita_salida", "falla_collarin", "", "NO", "SI", "Desgaste en collarin de empuje o crapodina de embrague", "L3 juego de 4.2 mm en perno esférico del robot descalibra lectura.")
    agregar("G39-L3-15", CLASE_39, "L3", "Prueba de hermeticidad con nitrógeno a 50 bar en bloque hidráulico robotizado: caída de presión de 15 bar en 3 minutos a través de la válvula antirretorno interna de la bomba de alta presión, obligando a ciclar la bomba eléctrica cada 12 segundos y agotando la batería auxiliar de 12V.", "TECNICO", "prueba_estanqueidad_nitrogeno_50bar", "caida_15bar_en_3min_valvula_antirretorno|bomba_cicla_cada_12s|agota_bateria", "falla_bateria", "", "NO", "NO", "", "L3 caída de 15 bar en 3 min por válvula antirretorno cicla bomba a 12s.")

    # =========================================================================
    # CLASE 40: Desgaste en collarin de empuje o crapodina de embrague (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G40-L1-01", CLASE_40, "L1", "Suena un chillido metálico fuerte cada vez que piso el pedal del embrague.", "COTIDIANO", "pedal_pisado", "chillido_al_pisar_embrague", "", "", "SI", "NO", "", "L1 ruido exclusivo al pisar embrague.")
    agregar("G40-L1-02", CLASE_40, "L1", "Hola, al pisar el embrague siento como un grillo o raspado en el pie.", "WHATSAPP", "desembrague", "grillo_raspado_al_pisar_embrague", "", "", "SI", "NO", "", "L1 vibración y grillo al pisar pedal.")
    agregar("G40-L1-03", CLASE_40, "L1", "Con el pedal suelto no suena nada, pero apoyo el pie en el embrague y chilla.", "COTIDIANO", "apoyo_pie_embrague", "chilla_al_apoyar_pie_embrague", "", "", "SI", "NO", "", "L1 ruido al hacer contacto con diafragma.")
    agregar("G40-L1-04", CLASE_40, "L1", "Se escucha un zumbido agudo en la campana que se quita al soltar el embrague.", "TALLER", "ralenti", "zumbido_campana_desaparece_al_soltar", "", "", "SI", "NO", "", "L1 collarín bajo carga acusa ruido.")
    agregar("G40-L1-05", CLASE_40, "L1", "Desgaste abrasivo y pérdida de grasa en rodamiento de desembrague axial.", "TECNICO", "diagnostico", "desgaste_rodamiento_desembrague_axial", "", "", "SI", "NO", "", "L1 reporte técnico de cojinete de empuje.")
    agregar("G40-L1-06", CLASE_40, "L1", "Siento una vibración pulsante en la planta del pie al apretar el embrague.", "COTIDIANO", "accionamiento", "vibracion_pulsante_pie_al_apretar", "", "", "SI", "NO", "", "L1 pulsación transmitida por pista picada.")
    agregar("G40-L1-07", CLASE_40, "L1", "El collarín de embrague chilla durísimo cuando meto primera para salir.", "TALLER", "primera_marcha", "collarin_chilla_al_meter_primera", "", "", "SI", "NO", "", "L1 chillido en maniobra de salida.")
    agregar("G40-L1-08", CLASE_40, "L1", "Mi carro ase un rechinido como cama vieja cuando aprieto el pedal del cloch.", "ERROR_ORTOGRAFICO", "accionamiento", "rechinido_cama_vieja_al_apretar_cloch", "", "", "SI", "NO", "", "L1 rechinido al pisar con ortografía informal.")
    agregar("G40-L1-09", CLASE_40, "L1", "Buenas, gotea líquido por la campana de caja y chilla feo al desembragar.", "WHATSAPP", "desembrague", "gotea_campana|chilla_al_desembragar", "", "", "SI", "NO", "", "L1 crapodina hidráulica CSC rota.")
    agregar("G40-L1-10", CLASE_40, "L1", "Gripado de rodamiento axial de contacto angular por fatiga superficial de bolas.", "TECNICO", "inspeccion", "gripado_rodamiento_axial_bolas", "", "", "SI", "NO", "", "L1 reporte técnico de crapodina gripada.")

    # --- L2 (15 casos) ---
    agregar("G40-L2-01", CLASE_40, "L2", "Chillido agudo de rodamiento seco que aparece exactamente al presionar el pedal de embrague a fondo; al soltar el pedal en punto muerto el motor queda en silencio absoluto.", "COTIDIANO", "embrague_a_fondo_vs_suelto", "chillido_al_pisar_embrague|silencio_al_soltar", "rodaje_eje_primario", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L2 ruido al pisar y silencio al soltar descarta eje primario.")
    agregar("G40-L2-02", CLASE_40, "L2", "Vibración áspera en el pie al pisar el embrague en ralentí; el cojinete de empuje mecánico tiene las bolas picadas y la pista de rodadura sin lubricación.", "TALLER", "ralenti_pedal_pisado", "vibracion_aspera_en_el_pie|cojinete_empuje_sin_lubricacion", "falla_plato_opresor", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L2 aspereza en pedal por rodamiento de empuje seco.")
    agregar("G40-L2-03", CLASE_40, "L2", "Crapodina hidráulica (CSC) emite zumbido chirriante al desacoplar marchas y rezuma líquido DOT 4 por el orificio de ventilación inferior de la campana de embrague.", "TECNICO", "inspeccion_csc_fuga", "csc_zumbido_al_desacoplar|goteo_dot4_campana", "fuga_aceite_caja", "", "NO", "SI", "Falla en bombin o bomba hidraulica de embrague", "L2 crapodina hidráulica con ruido y fuga de fluido.")
    agregar("G40-L2-04", CLASE_40, "L2", "Hola maestro, con el carro parado en neutro no suena nada, pero apenas piso el embrague para meter cambio empieza un chiiii metálico que ensordece.", "WHATSAPP", "neutro_vs_pedal_pisado", "silencio_en_neutro|chiii_metalico_al_pisar", "rodajes_caja", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L2 silencio en neutro y chillido al pisar descarta caja.")
    agregar("G40-L2-05", CLASE_40, "L2", "El collarín de empuje se quedó pegado y girando torcido, desgastando y cortando las puntas de los dedos del diafragma de la prensa de embrague.", "TECNICO", "desarme_embrague_dedos", "collarin_torcido|dedos_diafragma_cortados_friccion", "falla_prensa_embrague", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L2 collarín atascado corta dedos del diafragma.")
    agregar("G40-L2-06", CLASE_40, "L2", "Chirrido estridente que aumenta su volumen conforme se pisa con mayor fuerza el pedal de embrague; no hay patinamiento del disco ni pérdida de tracción.", "COTIDIANO", "accionamiento_progresivo", "chirrido_aumenta_con_fuerza_pedal|sin_patinamiento_disco", "disco_desgastado", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L2 chillido proporcional a carga sin patinamiento de disco.")
    agregar("G40-L2-07", CLASE_40, "L2", "Guía tubular del collarín de empuje rayada y con óxido; el cojinete se traba al deslizar provocando pedal duro y chirrido de fricción seca.", "TALLER", "inspeccion_guia_tubular", "guia_tubular_rayada_oxido|cojinete_se_traba|pedal_duro", "falla_bomba_embrague", "", "NO", "SI", "Falla en bombin o bomba hidraulica de embrague", "L2 guía tubular rayada traba deslizamiento del collarín.")
    agregar("G40-L2-08", CLASE_40, "L2", "Mi auto ase un grillo que chilla durisimo solo cuando meto el pie al cloch; si saco el pie se apaga el grillo al tiro.", "ERROR_ORTOGRAFICO", "accionamiento_pie", "grillo_solo_al_meter_pie_cloch|apaga_al_sacar_pie", "rodaje_primario", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L2 grillo exclusivo al pisar con ortografía informal.")
    agregar("G40-L2-09", CLASE_40, "L2", "Buenas, el mecánico me dijo que la crapodina se recalentó porque anduve con el pie apoyado en el pedal del embrague en el tráfico de la ciudad.", "WHATSAPP", "habito_pie_apoyado", "crapodina_recalentada_pie_apoyado|ruido_al_pisar", "desgaste_pastillas", "", "NO", "NO", "", "L2 crapodina dañada por mal hábito de pie apoyado.")
    agregar("G40-L2-10", CLASE_40, "L2", "Rodamiento de desembrague con juego axial de 2.5 mm y jaula porta-bolas partida; al desmontar caen las bolas de acero sueltas dentro de la campana.", "TECNICO", "desarme_campana_bolas_sueltas", "juego_axial_2_5mm_collarin|jaula_partida_bolas_sueltas", "falla_caja_interna", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L2 jaula de bolas partida en collarín de empuje.")
    agregar("G40-L2-11", CLASE_40, "L2", "Silbido agudo constante al pisar el embrague en semáforos; el disco de embrague y la prensa tienen solo 10,000 km pero no cambiaron el collarín viejo.", "COTIDIANO", "semaforo_pedal_a_fondo", "silbido_al_pisar_semaforo|embrague_nuevo_collarin_viejo", "embrague_patina", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L2 collarín no reemplazado en kit previo emite silbido.")
    agregar("G40-L2-12", CLASE_40, "L2", "Horquilla de embrague con desgaste por rozamiento en los apoyos del collarín; el cojinete apoya cruzado provocando zumbido y dureza de pedal.", "TALLER", "inspeccion_horquilla_apoyos", "horquilla_desgastada_apoyos|collarin_apoya_cruzado|zumbido", "falla_bombin", "", "NO", "SI", "Falla en bombin o bomba hidraulica de embrague", "L2 horquilla desgastada cruza collarín.")
    agregar("G40-L2-13", CLASE_40, "L2", "Al pisar el pedal a medio recorrido suena un zumbido áspero que se agudiza al llegar al fondo; los cambios entran perfectamente sin rascar.", "COTIDIANO", "medio_recorrido_pedal", "zumbido_medio_recorrido_agudo_al_fondo|cambios_entran_bien", "falla_caja_cambios", "", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L2 ruido progresivo con cambios suaves descarta sincronizadores.")
    agregar("G40-L2-14", CLASE_40, "L2", "Crapodina de empuje con pista de contacto cónica azulada por sobrecalentamiento por encima de 250°C; la grasa interna se carbonizó totalmente.", "TECNICO", "inspeccion_termica_crapodina", "pista_conica_azulada_250c|grasa_carbonizada_crapodina", "falla_disco_friccion", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L2 grasa carbonizada a 250°C en crapodina.")
    agregar("G40-L2-15", CLASE_40, "L2", "Pulsación y traqueteo rítmico en el pedal de embrague al presionarlo; el rodamiento de empuje perdió tres bolas de un lado generando desequilibrio.", "TALLER", "prueba_tactil_pedalier", "pulsacion_ritmica_al_pisar|perdida_tres_bolas_collarin", "falla_volante_bimasa", "", "NO", "NO", "", "L2 pérdida de bolas genera pulsación en pedal.")

    # --- L3 (15 casos) ---
    agregar("G40-L3-01", CLASE_40, "L3", "Toyota Hilux 1GD con transmisión manual de 6 marchas ingresa por ruido estridente en la zona de la campana. En ralentí con vehículo detenido en punto muerto y pedal de embrague suelto el motor opera en silencio a 48 dBA. En el instante exacto en que el conductor apoya el pie en el pedal con 50 N de carga el nivel sonoro se dispara a 82 dBA con un chillido metálico agudo de 3.4 kHz característico de rodamiento seco; al pisar el pedal a fondo el ruido se intensifica y transmite vibración de alta frecuencia a la suela del zapato. Al soltar nuevamente el pedal a neutro el ruido desaparece de inmediato descartando rodamientos de la caja de cambios.", "TECNICO", "sonometria_diferencial_pedal_suelto_vs_pisado", "silencio_48dba_pedal_suelto|chillido_82dba_al_pisar|frecuencia_3_4khz|vibracion_suela", "rodajes_eje_primario", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L3 sonometría diferencial: 48 dBA suelto vs 82 dBA pisado confirma collarín vs primario.")
    agregar("G40-L3-02", CLASE_40, "L3", "Vehículo presenta fallo de desacoplamiento tras chirrido intenso de dos semanas de evolución. Al desmontar la caja se constató que el cojinete de empuje de embrague se gripó totalmente por desintegración de la jaula de retención de poliamida; al no girar libremente el collarín friccionó de forma continua contra las lengüetas del diafragma de la prensa hasta desgastarlas y cortar 4 dedos de acero, dejando el pedal con carrera muerta y trabando la marcha atrás.", "TALLER", "desarme_campana_dedos_cortados", "cojinete_gripado_jaula_poliamida|friccion_continua_corta_4_dedos_prensa|reversa_trabada", "disco_desgastado", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L3 collarín gripado corta 4 dedos del diafragma de prensa.")
    agregar("G40-L3-03", CLASE_40, "L3", "Inspección de actuador concéntrico de desembrague hidráulico (CSC) en Ford Focus: goteo de fluido DOT 4 por la junta inferior de la campana con pérdida de nivel en el reservorio. Además de la fuga hidráulica, el rodamiento de contacto angular integrado en la cabeza del CSC presenta juego axial de 1.8 mm y juego radial de 1.2 mm; al girar la pista con la mano se aprecian asperezas rugosas y retención mecánica por falta de grasa.", "TECNICO", "metrologia_csc_holgura_y_fuga", "csc_gotea_dot4|juego_axial_1_8mm_radial_1_2mm|aspereza_manual_rodamiento", "falla_bomba_maestra", "", "NO", "SI", "Falla en bombin o bomba hidraulica de embrague", "L3 crapodina CSC con fuga de fluido y holgura axial de 1.8 mm.")
    agregar("G40-L3-04", CLASE_40, "L3", "Conductor refiere sonido de amoladora metálica exclusivamente al pisar el pedal de embrague para realizar cambios de marcha en carretera. En prueba con estetoscopio de taller se comprobó que la campana de caja amplifica el sonido en la zona frontal donde apoya la horquilla sobre el collarín. Se desmontó el conjunto verificándose que la guía tubular deslizante de acero sobre la cual corre el collarín carecía de grasa de bisulfuro de molibdeno, sufriendo rozamiento seco con microsoldaduras que rayaron la guía con surcos de 0.5 mm.", "TALLER", "inspeccion_guia_deslizante_bisulfuro", "ruido_amoladora_al_pisar|guia_tubular_sin_grasa_moly|surcos_0_5mm|microsoldaduras", "falla_disco_patina", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L3 guía tubular con surcos de 0.5 mm por falta de grasa de molibdeno.")
    agregar("G40-L3-05", CLASE_40, "L3", "Hola maestro, tengo un Suzuki Swift. Cuando el auto está en neutro sin tocar nada el motor suena parejito y silencioso, pero apenas piso el pedal del embrague para meter primera suena un silbido horrible como si un rodaje estuviera triturándose. Si saco el pie del pedal el ruido se corta en seco.", "WHATSAPP", "diagnostico_swift_neutro_vs_pisado", "silencioso_en_neutro|silbido_horrible_al_pisar|se_corta_en_seco_al_soltar", "rodaje_primario", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L3 relato WhatsApp de silbido al pisar que corta al soltar descartando caja.")
    agregar("G40-L3-06", CLASE_40, "L3", "Análisis con cámara termográfica infrarroja tras 15 minutos de maniobras de estacionamiento continuo con embrague acoplado y desacoplado: el cojinete de empuje registra 165°C de temperatura concentrada en el anillo interior de contacto (temperatura ambiente de campana 55°C). La grasa sintética de litio de alta temperatura se licuó y fugó por el retén de caucho NBR, dejando las 14 bolas de acero trabajando en seco.", "TECNICO", "termografia_cojinete_165c", "termografia_cojinete_165c_vs_55c|grasa_litio_licuada_fugada|14_bolas_en_seco", "falla_disco_embrague", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L3 termografía registra 165°C en collarín con pérdida total de grasa.")
    agregar("G40-L3-07", CLASE_40, "L3", "Evaluación vibratoria de pedalier de embrague con acelerómetro piezoeléctrico: en reposo se registra aceleración RMS de 0.2 m/s2; al pisar el pedal a fondo la aceleración se multiplica a 4.8 m/s2 a frecuencia de 125 Hz correspondiente al paso de bolas del collarín de desembrague picado. El disco de embrague tiene 7.5 mm de espesor y el volante bimasa no presenta juego angular anómalo.", "TECNICO", "analisis_acelerometro_pedalier_4_8ms2", "aceleracion_pedal_4_8ms2_vs_0_2ms2|frecuencia_125hz_paso_bolas|disco_7_5mm_ok", "falla_bimasa", "", "NO", "NO", "", "L3 acelerómetro registra pico de 4.8 m/s2 a 125 Hz en pedal al desembragar.")
    agregar("G40-L3-08", CLASE_40, "L3", "Mi carro ase un chillido estridente como pito de tren cuando meto el pie al embrague para pasar de cambio en la pista. Si suelto el pedal el carro anda calladito sin ningun ruido. El mecanico le bajo la caja y la crapodina taba agarrada y las bolitas no giraban con la mano.", "ERROR_ORTOGRAFICO", "desarme_crapodina_agarrada", "chillido_pito_tren_al_pisar|calladito_al_soltar|crapodina_agarrada_no_gira", "falla_caja_cambios", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L3 crapodina agarrada con silencio al soltar con ortografía informal.")
    agregar("G40-L3-09", CLASE_40, "L3", "Falla de concentricidad en el montaje del collarín de empuje tras sustitución de embrague: la horquilla de mando fue instalada con deformación plástica de 3.5 mm en el brazo derecho, provocando empuje asimétrico del cojinete sobre el diafragma de la prensa. Esto genera desgaste oblicuo de la pista de rozamiento con salto lateral de 0.35 mm y ruido vibratorio oscilante al presionar el pedal.", "TALLER", "montaje_asimetrico_horquilla_deformada", "horquilla_deformada_3_5mm|empuje_asimetrico_collarin|salto_0_35mm_ruido", "falla_prensa", "", "NO", "NO", "", "L3 horquilla torcida deforma empuje de collarín con salto de 0.35 mm.")
    agregar("G40-L3-10", CLASE_40, "L3", "Buenas tardes, en mi Renault Duster se siente una vibración áspera en el pedal cada vez que piso el embrague para cambiar de marcha y suena un grillo agudo. El disco no patina nada en subida y los cambios entran suaves, solo es ese chillido desagradable que se prende únicamente mientras mantengo el pedal pisado.", "WHATSAPP", "diagnostico_duster_pedal_pisado", "vibracion_aspera_pedal_al_pisar|grillo_agudo_mientras_pisa|disco_no_patina", "disco_patina", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L3 grillo exclusivo bajo presión sin patinamiento de disco.")
    agregar("G40-L3-11", CLASE_40, "L3", "Desmontaje de conjunto de embrague de vehículo utilitario: el collarín de desembrague presenta holgura angular de 8 grados y marcas de fricción circular por contacto descentrado sobre los dedos de la prensa. La pista interior de acero templado tiene decoloración violeta por temperatura y el labio del guardapolvo de caucho está calcinado.", "TECNICO", "metrologia_collarin_holgura_8_grados", "holgura_angular_8_grados|decoloracion_violeta_collarin|guardapolvo_calcinado", "falla_eje_primario", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L3 holgura de 8° y pista violeta calcinada en collarín.")
    agregar("G40-L3-12", CLASE_40, "L3", "Ensayo en banco de pruebas acústico: al aplicar 350 N de carga axial sobre el collarín girando a 2500 rpm el nivel de presión sonora alcanza 88 dBA con espectro armónico centrado en 4.2 kHz; al retirar la carga axial a 0 N girando a las mismas revoluciones el nivel sonoro decae instantáneamente a 42 dBA (ruido de fondo normal).", "TECNICO", "banco_acustico_carga_350n_vs_0n", "ruido_88dba_a_350n_carga|decae_a_42dba_sin_carga|armonicos_4_2khz", "falla_rodaje_caja", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L3 banco acústico confirma 88 dBA con 350 N de carga vs 42 dBA sin carga.")
    agregar("G40-L3-13", CLASE_40, "L3", "El cliente reclama que el embrague suena como si raspara metal con metal únicamente al estacionar o meter reversa con el pedal a fondo. Se inspeccionó el cojinete comprobándose que el sello metálico de protección se soltó de su encastre y quedó rozando contra la carcasa del volante de inercia al avanzar el actuador hidráulico.", "TALLER", "sello_metalico_suelto_roza_volante", "sello_collarin_suelto_roza_volante|raspado_pedal_a_fondo|estacionamiento", "falla_disco_friccion", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L3 sello metálico de collarín rozando contra volante al pisar a fondo.")
    agregar("G40-L3-14", CLASE_40, "L3", "Rotura catastrófica de collarín de desembrague: tras 300 km de advertencia acústica desatendida el cojinete se trabó en seco soldándose a la pista del diafragma, provocando que los dedos de la prensa se cortaran en bloque y el pedal se fuera hasta el fondo sin retorno ni posibilidad de desacople.", "TALLER", "rotura_catastrofica_collarin_soldado", "collarin_soldado_a_diafragma|dedos_prensa_cortados_en_bloque|pedal_al_fondo", "falla_bombin_embrague", "", "NO", "SI", "Falla en bombin o bomba hidraulica de embrague", "L3 gripado total de collarín destruye diafragma y vacía pedal.")
    agregar("G40-L3-15", CLASE_40, "L3", "Medición de concentricidad y rugosidad en pista de empuje de crapodina: rugosidad Ra de 3.8 micrómetros (especificación Ra menor a 0.4 um) por arrastre y microgripado repetido; la rotación manual del rodamiento presenta saltos duros cada 30 grados provocando trepidación en el pedalier de desembrague.", "TECNICO", "metrologia_rugosidad_ra_3_8um", "rugosidad_ra_3_8um_vs_0_4um|saltos_duros_cada_30_grados|trepidacion_pedal", "falla_disco_embrague", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L3 rugosidad Ra de 3.8 um y saltos mecánicos en rotación de crapodina.")

    # =========================================================================
    # CLASE 41: Rodajes de transmision manual o eje primario gastados (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G41-L1-01", CLASE_41, "L1", "La caja zumba feo en neutro y el ruido se apaga cuando piso el embrague.", "COTIDIANO", "ralenti_neutro", "zumba_en_neutro_apaga_al_pisar_embrague", "", "", "SI", "NO", "", "L1 patrón canónico de rodamiento de eje primario.")
    agregar("G41-L1-02", CLASE_41, "L1", "Hola, con el carro parado suena como una licuadora que se calla al apretar el embrague.", "WHATSAPP", "ralenti_parado", "sonido_licuadora_se_calla_al_embragar", "", "", "SI", "NO", "", "L1 ruido en neutro que desaparece al desembragar.")
    agregar("G41-L1-03", CLASE_41, "L1", "Se escucha un ronquido sordo en la transmisión con el pedal de embrague suelto.", "COTIDIANO", "pedal_suelto_neutro", "ronquido_sordo_pedal_suelto", "", "", "SI", "NO", "", "L1 rugido constante en vacío.")
    agregar("G41-L1-04", CLASE_41, "L1", "Al pisar el embrague hasta el fondo el motor queda serenito sin ningún ruido.", "TALLER", "desembrague_completo", "silencio_al_pisar_embrague_a_fondo", "", "", "SI", "NO", "", "L1 cese de ruido al detener eje primario.")
    agregar("G41-L1-05", CLASE_41, "L1", "Desgaste y picadura en pistas de rodamiento delantero del eje primario de entrada.", "TECNICO", "diagnostico", "desgaste_rodamiento_eje_primario", "", "", "SI", "NO", "", "L1 reporte técnico de rodaje de directa.")
    agregar("G41-L1-06", CLASE_41, "L1", "Suena como un engranaje seco en neutro que se quita apenas piso el cloch.", "COTIDIANO", "ralenti", "engranaje_seco_neutro_quita_al_pisar_cloch", "", "", "SI", "NO", "", "L1 ruido de primario en ralentí.")
    agregar("G41-L1-07", CLASE_41, "L1", "En primera y segunda marcha zumba al compás de las revoluciones del motor.", "TALLER", "marchas_cortas", "zumbido_con_rpm_primera_segunda", "", "", "SI", "NO", "", "L1 zumbido proporcional a RPM en marchas bajas.")
    agregar("G41-L1-08", CLASE_41, "L1", "Mi caja ase un cascabeleo en neutro que cuando piso el embrague se le pasa todito.", "ERROR_ORTOGRAFICO", "neutro", "cascabeleo_neutro_se_pasa_al_pisar", "", "", "SI", "NO", "", "L1 cascabeleo en neutro con ortografía informal.")
    agregar("G41-L1-09", CLASE_41, "L1", "Buenas, al soltar el embrague en neutro empieza a sonar un traqueteo en la caja.", "WHATSAPP", "suelta_embrague_neutro", "traqueteo_al_soltar_embrague_neutro", "", "", "SI", "NO", "", "L1 traqueteo al girar eje de entrada.")
    agregar("G41-L1-10", CLASE_41, "L1", "Holgura radial excesiva en apoyo de rodamiento de bolas del árbol primario.", "TECNICO", "inspeccion", "holgura_radial_arbol_primario", "", "", "SI", "NO", "", "L1 reporte técnico de juego radial en directa.")

    # --- L2 (15 casos) ---
    agregar("G41-L2-01", CLASE_41, "L2", "Con el vehículo detenido en ralentí y la palanca en neutro se escucha un zumbido sordo en la transmisión; al pisar el pedal de embrague hasta el fondo el zumbido desaparece por completo tras 1 segundo.", "COTIDIANO", "parado_neutro_vs_embrague_pisado", "zumbido_en_neutro|desaparece_al_pisar_embrague", "falla_collarin", "", "NO", "SI", "Desgaste en collarin de empuje o crapodina de embrague", "L2 zumbido en neutro que desaparece al pisar descarta collarín.")
    agregar("G41-L2-02", CLASE_41, "L2", "Ruido de rodamiento picado en la caja de cambios que varía con las RPM del motor al acelerar en punto muerto con el embrague acoplado; al desembragar se hace el silencio.", "TALLER", "aceleracion_neutro_embragado", "ruido_varia_con_rpm_en_neutro|silencio_al_desembragar", "rodajes_diferencial", "", "NO", "SI", "Rodajes de caja mecanica o diferencial gastados", "L2 ruido con auto detenido descarta diferencial.")
    agregar("G41-L2-03", CLASE_41, "L2", "El rodamiento delantero del eje primario tiene juego radial de 0.8 mm; provoca desalineación del disco de embrague y dificultad ocasional para engranar primera.", "TECNICO", "inspeccion_juego_primario", "juego_radial_0_8mm_primario|desalineacion_disco", "falla_disco_patina", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L2 juego radial en primario desalinea embrague.")
    agregar("G41-L2-04", CLASE_41, "L2", "Hola, en carretera zumba en 1ra, 2da, 3ra y 5ta pero en 4ta marcha (directa) el ruido baja muchísimo casi a nada; me dijeron que es el eje primario de la caja.", "WHATSAPP", "comparativa_marchas_cuarta_directa", "zumba_1_2_3_5|silencio_en_cuarta_directa", "rodajes_diferencial", "", "NO", "SI", "Rodajes de caja mecanica o diferencial gastados", "L2 silenciamiento en 4ta directa confirma eje primario vs diferencial.")
    agregar("G41-L2-05", CLASE_41, "L2", "Al drenar el aceite de la transmisión se encuentra limalla plateada fina en el imán; el rodamiento posterior del árbol primario presenta picaduras en la pista exterior.", "TECNICO", "drenaje_valvulina_pitting_primario", "limalla_plateada_iman|pitting_pista_exterior_primario", "falta_aceite_caja", "", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L2 limalla de rodamiento con lubricante a nivel.")
    agregar("G41-L2-06", CLASE_41, "L2", "Ronroneo continuo en la parte delantera que se escucha al estar estacionado esperando pasajeros; al apoyar el pie y hundir el embrague se corta instantáneamente.", "COTIDIANO", "estacionado_pasajeros_ralenti", "ronroneo_estacionado_ralenti|corta_al_hundir_embrague", "ruido_motor_bielas", "", "NO", "NO", "", "L2 ronroneo en reposo que corta al desembragar descarta motor.")
    agregar("G41-L2-07", CLASE_41, "L2", "Rodamiento central del eje intermediario de la transmisión manual con jaula de bolas rota; produce cascabeleo metálico al soltar el embrague en neutro.", "TALLER", "inspeccion_desarme_caja", "jaula_bolas_rota_intermediario|cascabeleo_embrague_suelto", "falla_collarin", "", "NO", "SI", "Desgaste en collarin de empuje o crapodina de embrague", "L2 cascabeleo con pedal suelto descarta collarín.")
    agregar("G41-L2-08", CLASE_41, "L2", "Mi carro ase un zumbido en neutro como si algo raspase adentro de la caja y cuando meto el cloch a fondo se le kita todo el ruido.", "ERROR_ORTOGRAFICO", "neutro_vs_cloch", "zumbido_en_neutro|se_quita_al_meter_cloch", "falla_crapodina", "", "NO", "SI", "Desgaste en collarin de empuje o crapodina de embrague", "L2 zumbido en neutro que quita al meter cloch con ortografía informal.")
    agregar("G41-L2-09", CLASE_41, "L2", "Buenas maestro, en el semáforo suena un cloc-cloc suave en la caja que desaparece apenas piso el embrague para meter primera; el disco no patina para nada.", "WHATSAPP", "semaforo_ralenti", "cloc_cloc_suave_caja|desaparece_al_pisar_embrague|no_patina", "disco_desgastado", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L2 golpeteo en neutro sin patinamiento de disco.")
    agregar("G41-L2-10", CLASE_41, "L2", "Holgura axial del eje primario de 0.65 mm medida con comparador; provoca que el retén frontal del eje gotee aceite hacia la campana de embrague.", "TECNICO", "medicion_holgura_axial_primario", "holgura_axial_0_65mm_primario|fuga_reten_frontal", "falla_bomba_embrague", "", "NO", "SI", "Falla en bombin o bomba hidraulica de embrague", "L2 juego axial de primario daña retén frontal de caja.")
    agregar("G41-L2-11", CLASE_41, "L2", "Al rodar en neutro a 60 km/h por inercia el zumbido desaparece si el motor está en ralentí y el pedal de embrague pisado; descarta rodamiento de maza de rueda.", "COTIDIANO", "rodada_inercia_60kmh", "desaparece_al_pisar_embrague_a_60kmh", "rodamiento_rueda", "", "NO", "SI", "Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)", "L2 silencio a 60 km/h al pisar embrague descarta maza de rueda.")
    agregar("G41-L2-12", CLASE_41, "L2", "Casquillo de agujas de apoyo de la punta del eje primario en el cigüeñal (rodaje de guía piloto) engranado en seco; produce chirrido agudo al desacoplar.", "TECNICO", "inspeccion_rodaje_piloto", "rodaje_piloto_ciguenal_seco|chirrido_al_desacoplar", "falla_collarin", "", "NO", "SI", "Desgaste en collarin de empuje o crapodina de embrague", "L2 rodamiento piloto de cigüeñal vs collarín de empuje.")
    agregar("G41-L2-13", CLASE_41, "L2", "Zumbido que aumenta al acelerar en 1ra, 2da y 3ra marcha y se apaga en neutro pisando el embrague; el nivel de aceite de la caja de cambios está al máximo.", "TALLER", "aceleracion_marchas_bajas", "zumbido_1_2_3_aumenta_con_rpm|apaga_al_pisar|aceite_al_maximo", "falta_aceite_caja", "", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L2 zumbido dependiente de RPM con aceite lleno.")
    agregar("G41-L2-14", CLASE_41, "L2", "Pistas de rodadura del rodamiento de entrada con picado severo por contaminación con agua vieja; zumbido de frecuencia constante en neutro.", "TECNICO", "desarme_rodamiento_entrada", "picado_severo_pistas_agua|zumbido_frecuencia_constante_neutro", "falla_diferencial", "", "NO", "SI", "Rodajes de caja mecanica o diferencial gastados", "L2 picado en pista de entrada con zumbido en neutro vs diferencial.")
    agregar("G41-L2-15", CLASE_41, "L2", "Ruido de rozamiento metálico que inicia suave al arrancar el motor y se incrementa al acelerar en vacío; pisando el embrague a fondo se silencia por completo.", "COTIDIANO", "aceleracion_vacio_estacionado", "ruido_rozamiento_acelerar_vacio|silencio_al_pisar_fondo", "falla_motor_bielas", "", "NO", "NO", "", "L2 prueba en vacío: acelerar en neutro zumba, desembragar silencia.")

    # --- L3 (15 casos) ---
    agregar("G41-L3-01", CLASE_41, "L3", "En un Toyota Yaris con transmisión manual de 5 velocidades se manifiesta un ruido áspero de rodadura en neutro con el motor encendido a 750 rpm de ralentí. Al aplicar el pedal de embrague hasta el fondo, tras 1.2 segundos el eje primario se detiene por inercia y el ruido desaparece al 100% dejando el motor en silencio total. Al soltar nuevamente el pedal en neutro el ruido reaparece de inmediato. Con estetoscopio colocado en la carcasa frontal de la caja junto a la campana se miden 76 dB en neutro que caen a 44 dB al desembragar. Se desmontó la caja encontrándose el rodamiento de bolas del eje primario (referencia 6205) con la pista de rodadura picada con desprendimiento de material de 3 mm.", "TECNICO", "estetoscopio_76db_neutro_vs_44db_pisado", "76db_en_neutro_cae_a_44db_al_pisar_embrague|eje_primario_se_detiene_silencio|rodamiento_6205_picado", "falla_collarin_empuje", "", "NO", "SI", "Desgaste en collarin de empuje o crapodina de embrague", "L3 estetoscopio: 76 dB en neutro cae a 44 dB al pisar confirmando eje primario vs collarín.")
    agregar("G41-L3-02", CLASE_41, "L3", "Conductor reporta zumbido en la transmisión que acompaña a las revoluciones del motor en 1ra, 2da, 3ra y 5ta marcha, pero que disminuye drásticamente en 4ta velocidad (marcha directa 1:1 donde el tren secundario no transmite par). Con el auto detenido y la palanca en neutro, el zumbido se escucha claramente con el embrague suelto y desaparece al pisar el pedal. Se midió el juego radial del eje primario con reloj comparador registrándose 0.62 mm de holgura (tolerancia máxima 0.05 mm) por fatiga de bolas en el rodamiento frontal.", "TALLER", "prueba_cuarta_directa_vs_otras", "zumbido_1_2_3_5_cae_en_cuarta_directa|juego_radial_primario_0_62mm|silencio_al_pisar_en_neutro", "rodajes_diferencial", "", "NO", "SI", "Rodajes de caja mecanica o diferencial gastados", "L3 silenciamiento en 4ta directa y juego de 0.62 mm en primario descarta diferencial.")
    agregar("G41-L3-03", CLASE_41, "L3", "Análisis con analizador de vibraciones FFT en ralentí con vehículo estacionado: con embrague acoplado en neutro se registra pico dominante de 38 mm/s a frecuencia de 12.5 Hz (coincidente exactamente con 1x velocidad de rotación del motor a 750 rpm) y armónicos en 112 Hz (frecuencia cinemática BPFI de pista interior del rodamiento de directa). Al pisar el pedal de embrague ambos picos colapsan instantáneamente a nivel de ruido base de 1.8 mm/s. El collarín de empuje fue inspeccionado encontrándose nuevo y sin holguras.", "TECNICO", "analisis_fft_bpfi_112hz_primario", "pico_fft_112hz_bpfi_primario|colapsa_al_pisar_embrague|collarin_nuevo_ok", "desgaste_collarin", "", "NO", "SI", "Desgaste en collarin de empuje o crapodina de embrague", "L3 análisis FFT confirma frecuencia BPFI de 112 Hz del rodamiento primario.")
    agregar("G41-L3-04", CLASE_41, "L3", "Vehículo presenta rumorosidad áspera al rodar que muchos atribuyeron a rodamientos de maza de rueda. En prueba de carretera a 80 km/h se colocó la palanca en neutro y se pisó el pedal de embrague manteniendo el auto rodando por inercia: el ruido desapareció al 100% a pesar de que las ruedas giraban a 80 km/h (descartando de forma absoluta rodamientos de rueda y diferencial). Al soltar el embrague con el motor en marcha a 80 km/h el zumbido regresó de inmediato confirmando avería en el tren de engranajes del primario.", "TALLER", "prueba_inercia_80kmh_descarta_ruedas", "silencio_a_80kmh_inercia_pedal_pisado|ruido_vuelve_al_soltar|descarta_ruedas_diferencial", "rodamiento_rueda", "", "NO", "SI", "Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)", "L3 prueba de inercia a 80 km/h con embrague pisado descarta ruedas y diferencial.")
    agregar("G41-L3-05", CLASE_41, "L3", "Hola maestro, tengo un Nissan Tiida mecánico. Cuando estoy parado en el semáforo con el carro en neutro suena un traqueteo feo como si tuviera piedritas adentro de la caja. Apenas piso el embrague para meter primera el ruido desaparece por completo como por arte de magia. El embrague no patina y corta bien.", "WHATSAPP", "diagnostico_tiida_traqueteo_neutro", "traqueteo_neutro_como_piedritas|desaparece_al_pisar_embrague|no_patina", "disco_desgastado", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L3 relato WhatsApp de traqueteo en neutro que desaparece al pisar embrague.")
    agregar("G41-L3-06", CLASE_41, "L3", "Desmontaje de transmisión manual de 5 velocidades: el rodamiento de bolas blindado de entrada del eje primario tiene la pista exterior suelta girando sobre el propio alojamiento de aluminio de la carcasa, habiendo desgastado el asiento en 0.45 mm. El retén frontal de aceite sufrió deformación por la excentricidad del eje permitiendo que 300 ml de valvulina fugaran hacia la campana sin llegar a empapar el disco.", "TECNICO", "inspeccion_alojamiento_carcasa_desgastado_0_45mm", "pista_exterior_gira_en_carcasa|alojamiento_desgastado_0_45mm|excentricidad_eje_primario", "falta_aceite_caja", "", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L3 pista exterior gira en carcasa desgastando alojamiento 0.45 mm.")
    agregar("G41-L3-07", CLASE_41, "L3", "Inspección de rodamiento guía piloto de agujas montado en el extremo posterior del cigüeñal: los rodillos de agujas se destruyeron por falta de lubricación quedando el muñón del primario apoyando metal con metal. A diferencia del rodamiento de caja que suena en neutro con pedal suelto, este rodaje piloto emite un chillido agudo exclusivamente cuando se pisa el embrague a fondo con marcha puesta y motor girando.", "TALLER", "diagnostico_rodamiento_piloto_ciguenal", "rodamiento_piloto_agujas_destruido|chillido_al_desembragar_con_marcha|primario_sano", "collarin_embrague", "", "NO", "SI", "Desgaste en collarin de empuje o crapodina de embrague", "L3 rodamiento piloto de agujas destruido en cigüeñal vs rodaje de primario.")
    agregar("G41-L3-08", CLASE_41, "L3", "Mi carro ase una tembladera y zumbido en neutro cuando esta prendido parado en la vereda. Si le piso el pedal del cloch se caya todito y no suena nada. El mecanico le desarmo la caja y el rodaje grande de la directa taba con las bolas comidas y sueltas.", "ERROR_ORTOGRAFICO", "desarme_rodaje_directa", "zumbido_en_neutro_parado|se_calla_al_pisar_cloch|rodaje_directa_bolas_comidas", "crapodina", "", "NO", "SI", "Desgaste en collarin de empuje o crapodina de embrague", "L3 rodaje de directa con bolas comidas con ortografía informal.")
    agregar("G41-L3-09", CLASE_41, "L3", "Comprobación con estetoscopio de taller en 4 puntos de la transmisión con motor en marcha a 800 rpm: punto 1 (carcasa de diferencial) registra 35 dB; punto 2 (tapa trasera de 5ta) registra 38 dB; punto 3 (campana frontal junto a retén de directa) registra 79 dB; al accionar el pedal de embrague el punto 3 cae inmediatamente a 34 dB confirmando origen en rodamiento delantero de primario.", "TECNICO", "estetoscopio_4_puntos_79db_vs_35db", "punto_campana_79db_cae_a_34db|diferencial_35db_silencioso|rodamiento_directa_danado", "rodajes_diferencial", "", "NO", "SI", "Rodajes de caja mecanica o diferencial gastados", "L3 estetoscopio en 4 puntos aísla ruido en directa (79 dB) y descarta diferencial.")
    agregar("G41-L3-10", CLASE_41, "L3", "Buenas tardes maestro, tengo un Gol 1.6. Cuando el carro está prendido en neutro suena un siseo constante shhh-shhh en el motor que parece de faja. Le sacamos las fajas de accesorios y seguía sonando igualito; pero al pisar el embrague el siseo se apaga al segundo exacto. Los cambios entran perfectos y no rascan.", "WHATSAPP", "diagnostico_gol_siseo_neutro", "siseo_constante_neutro|persiste_sin_fajas_accesorios|apaga_al_pisar_embrague", "falla_faja_distribucion", "", "NO", "SI", "Desgaste en collarin de empuje o crapodina de embrague", "L3 siseo en neutro descartado de accesorios que apaga al pisar embrague.")
    agregar("G41-L3-11", CLASE_41, "L3", "Desgaste por fatiga de contacto con desprendimiento laminar en pista interior de rodamiento de contacto angular del eje secundario/primario: holgura axial resultante de 0.55 mm provoca que al acelerar en 2da y 3ra marcha los engranajes helicoidales sufran empuje axial descentrado provocando zumbido de engrane proporcional al torque.", "TECNICO", "desprendimiento_laminar_holgura_0_55mm", "desprendimiento_laminar_pista|holgura_0_55mm|zumbido_engrane_segunda_tercera", "falta_aceite_caja", "", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L3 holgura axial de 0.55 mm por desprendimiento laminar en pista interior.")
    agregar("G41-L3-12", CLASE_41, "L3", "Prueba de calado acústico en taller: con vehículo detenido y motor a 2000 rpm en neutro el nivel sonoro en habitáculo es de 68 dBA con pedal suelto; al desembragar cae a 52 dBA. Al realizar la prueba en marcha rodando a 50 km/h en neutro el ruido se mantiene al embragar y se extingue al desembragar demostrando que el ruido depende del giro del primario y no de las ruedas.", "TALLER", "prueba_calado_acustico_neutro_rodando", "68dba_suelto_vs_52dba_desembragado|mismo_patron_rodando_a_50kmh|descarta_ruedas", "rodamiento_rueda", "", "NO", "SI", "Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)", "L3 calado acústico a 50 km/h demuestra dependencia exclusiva del eje primario.")
    agregar("G41-L3-13", CLASE_41, "L3", "Rotura de la jaula remachada de retención de bolas en rodamiento de árbol primario: dos bolas contiguas entraron en contacto directo provocando rozamiento severo con microfisuras superficiales y viruta de acero de 1.5 mm adherida al imán de drenaje. El pedal de embrague no transmite pulsaciones y desacopla con suavidad.", "TECNICO", "jaula_remachada_rota_viruta_1_5mm", "jaula_remachada_rota|bolas_en_contacto_directo|viruta_1_5mm_iman|pedal_suave_ok", "falla_crapodina", "", "NO", "SI", "Desgaste en collarin de empuje o crapodina de embrague", "L3 jaula remachada de bolas rota con pedal suave descarta collarín.")
    agregar("G41-L3-14", CLASE_41, "L3", "El cliente reclama que el auto suena feo al detenerse en los peajes pero al poner primera y salir el ruido disminuye. Se inspeccionó el primario comprobándose juego radial de 0.40 mm que produce vibración armónica en el tren fijo de engranajes en ralentí (Gear Rattle) que se silencia por completo al desacoplar el embrague.", "TALLER", "gear_rattle_ralenti_peaje", "gear_rattle_ralenti_peaje|juego_radial_0_40mm|silencio_al_desacoplar", "desgaste_embrague", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L3 gear rattle en ralentí silenciado al desacoplar embrague.")
    agregar("G41-L3-15", CLASE_41, "L3", "Medición metrológica de rugosidad en pista exterior de rodamiento de directa: rugosidad superficial Ra de 2.9 micrómetros (especificación OEM Ra menor a 0.2 um) con microcráteres de cavitación mecánica provocados por partículas abrasivas suspendidas en lubricante degradado.", "TECNICO", "metrologia_rugosidad_ra_2_9um_primario", "rugosidad_ra_2_9um_vs_0_2um|microcrateres_cavitacion|zumbido_neutro", "falta_aceite_caja", "", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L3 rugosidad Ra de 2.9 um por microcráteres en pista de directa.")

    return casos
