"""
Casos de entrenamiento para Fase 10 Lote 06 (FRENOS - Parte 2):
- Clase 30: Fuga hidraulica o aire en el sistema de frenos (40 casos: 10 L1, 15 L2, 15 L3)
- Clase 31: Falla en sensor de velocidad de rueda ABS (40 casos: 10 L1, 15 L2, 15 L3)
- Clase 32: Falla en sistema de frenado regenerativo (EV / Hibridos) (40 casos: 10 L1, 15 L2, 15 L3)
- Clase 33: Caliper de freno trabado o mordaza pegada (piston agarrotado) (40 casos: 10 L1, 15 L2, 15 L3)

Total: 160 registros (IDs F10-L06-0121 a F10-L06-0280).
"""

CLASE_30 = "Fuga hidraulica o aire en el sistema de frenos"
CLASE_31 = "Falla en sensor de velocidad de rueda ABS"
CLASE_32 = "Falla en sistema de frenado regenerativo (EV / Hibridos)"
CLASE_33 = "Caliper de freno trabado o mordaza pegada (piston agarrotado)"


def obtener_casos_30_33(offset=121):
    casos = []
    idx = offset

    def agregar(id_grupo, clase, nivel, texto, tipo_lenguaje, cond, sint_pres, sint_neg, dtc, req_preg, es_cont, cl_cont, obs):
        nonlocal idx
        reg_id = f"F10-L06-{idx:04d}"
        idx += 1
        casos.append({
            "id": reg_id,
            "id_grupo": id_grupo,
            "clase_objetivo": clase,
            "macro_sistema": "FRENOS",
            "nivel_informacion": nivel,
            "texto_usuario": texto.strip(),
            "tipo_lenguaje": tipo_lenguaje,
            "condicion_operacion": cond.strip(),
            "sintomas_presentes": sint_pres.strip(),
            "sintomas_negados": sint_neg.strip(),
            "dtc": dtc.strip(),
            "requiere_pregunta": req_preg.strip(),
            "es_contrastivo": es_cont.strip(),
            "clase_contrastiva": cl_cont.strip(),
            "fuente": "SINTETICO_IA",
            "observaciones": obs.strip()
        })

    # =========================================================================
    # CLASE 30: Fuga hidraulica o aire en el sistema de frenos (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G30-L1-01", CLASE_30, "L1", "El pedal del freno se siente esponjoso y se va hasta el fondo.", "COTIDIANO", "frenado", "pedal_esponjoso_se_hunde", "", "", "SI", "NO", "", "L1 pedal esponjoso con recorrido al piso.")
    agregar("G30-L1-02", CLASE_30, "L1", "Hola, prendió la luz roja de freno en el tablero y encontré un charquito aceitoso.", "WHATSAPP", "estacionamiento", "luz_freno_roja|charco_aceitoso", "", "", "SI", "NO", "", "L1 testigo de líquido y goteo visible.")
    agregar("G30-L1-03", CLASE_30, "L1", "Tengo que bombear dos o tres veces el pedal para que recién agarre freno.", "COTIDIANO", "frenado_urbano", "bombear_pedal_para_frenar", "", "", "SI", "NO", "", "L1 necesidad de bombear delata aire.")
    agregar("G30-L1-04", CLASE_30, "L1", "Estando parado en el semáforo el pedal se va bajando despacito contra el piso.", "TALLER", "parada_semaforo", "pedal_hundiendose_lentamente", "", "", "SI", "NO", "", "L1 bypass interno en cilindro maestro.")
    agregar("G30-L1-05", CLASE_30, "L1", "Pérdida de presión hidráulica estática y carrera muerta excesiva del actuador.", "TECNICO", "diagnostico", "perdida_presion_hidraulica|carrera_muerta", "", "", "SI", "NO", "", "L1 reporte técnico de despresurización.")
    agregar("G30-L1-06", CLASE_30, "L1", "El depósito del líquido de frenos se vació por completo de un día para otro.", "COTIDIANO", "revision_niveles", "deposito_liquido_vacio", "", "", "SI", "NO", "", "L1 pérdida total de fluido hidráulico.")
    agregar("G30-L1-07", CLASE_30, "L1", "Se siente un tacto gomoso elástico en el pie y frena muy abajo casi al suelo.", "COTIDIANO", "frenado_rutina", "tacto_gomoso_elastico|frena_muy_abajo", "", "", "SI", "NO", "", "L1 compresibilidad por aire en cañerías.")
    agregar("G30-L1-08", CLASE_30, "L1", "Mi pedal de freno se ba al piso y tengo que bombiar para que frene algo.", "ERROR_ORTOGRAFICO", "frenado", "pedal_al_piso|bombear_para_frenar", "", "", "SI", "NO", "", "L1 pedal al piso con ortografía informal.")
    agregar("G30-L1-09", CLASE_30, "L1", "Buenas, cambiaron pastillas y desde ahí el pedal quedó aguado sin fuerza.", "WHATSAPP", "post_cambio_pastillas", "pedal_aguado_post_servicio", "", "", "SI", "NO", "", "L1 purga incompleta tras mantenimiento.")
    agregar("G30-L1-10", CLASE_30, "L1", "Compresibilidad volumétrica de fluido hidráulico por presencia de burbujas de gas.", "TECNICO", "inspeccion", "compresibilidad_fluido|burbujas_gas", "", "", "SI", "NO", "", "L1 reporte técnico de aire en circuito.")

    # --- L2 (15 casos) ---
    agregar("G30-L2-01", CLASE_30, "L2", "Pedal de freno esponjoso que se hunde hasta la alfombra al mantenerlo pisado en semáforo; al bombear 3 veces recupera altura firme por unos segundos.", "COTIDIANO", "parada_prolongada", "pedal_hunde_alfombra|recupera_al_bombear", "pedal_duro_booster", "", "NO", "SI", "Falla en servofreno (booster) o linea de vacio", "L2 recuperación por bombeo confirma aire o fuga interna vs booster.")
    agregar("G30-L2-02", CLASE_30, "L2", "Mancha aceitosa de líquido de frenos DOT 4 en la cara interna del neumático trasero derecho; el guardapolvo del bombín de rueda está rezumando fluido.", "TALLER", "inspeccion_elevador", "mancha_liquido_dot4_neumatico|bombin_rezumando", "fuga_grasa_rodamiento", "", "NO", "SI", "Caliper de freno trabado o mordaza pegada (piston agarrotado)", "L2 bombín con fuga visible en freno de tambor.")
    agregar("G30-L2-03", CLASE_30, "L2", "El nivel de líquido en el reservorio cae por debajo del mínimo cada semana; la manguera flexible de freno delantera izquierda tiene una hernia que se infla.", "TECNICO", "inspeccion_flexibles", "nivel_bajo_semanal|hernia_manguera_flexible", "desgaste_pastillas", "", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L2 manguera flexible deformada dilata volumen.")
    agregar("G30-L2-04", CLASE_30, "L2", "Hola maestro, ayer le purgaron los frenos a mi carro pero el pedal sigue gomoso y frena muy abajo; no hay fuga en ninguna rueda y el nivel no baja.", "WHATSAPP", "post_purga_incompleta", "pedal_gomoso_post_purga|frena_abajo|sin_fuga_nivel_ok", "falla_pastillas", "", "NO", "SI", "Falla en servofreno (booster) o linea de vacio", "L2 aire atrapado en módulo de válvulas o cañería.")
    agregar("G30-L2-05", CLASE_30, "L2", "Cilindro maestro de frenos con copela primaria dañada; el líquido recircula internamente entre cámaras provocando que el pedal se desplace lentamente al fondo.", "TECNICO", "prueba_estatica_bomba", "copela_primaria_danada|bypass_interno_liquido|pedal_al_fondo", "falla_servofreno", "", "NO", "SI", "Falla en servofreno (booster) o linea de vacio", "L2 bypass interno sin fuga externa visible.")
    agregar("G30-L2-06", CLASE_30, "L2", "En frenada de emergencia el pedal se fue hasta el tope con encendido del testigo rojo de advertencia de frenos; se localizó tubo metálico de freno picado por óxido.", "COTIDIANO", "frenada_emergencia", "pedal_al_tope|testigo_rojo_frenos|tubo_metalico_picado", "falla_abs", "", "NO", "NO", "", "L2 rotura de cañería rígida por corrosión.")
    agregar("G30-L2-07", CLASE_30, "L2", "Al mantener presionado el pedal con 20 kg de fuerza constante con el motor encendido, el pedal cede 60 mm en 10 segundos confirmando pérdida de estanqueidad.", "TALLER", "prueba_fuerza_constante", "pedal_cede_60mm_10seg|perdida_estanqueidad", "pastillas_desgastadas", "", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L2 prueba metrológica de carrera de pedal.")
    agregar("G30-L2-08", CLASE_30, "L2", "Mi carro casi no frena y el pedal se ba al suelo blandito. En la llanta de atras gotea liquido transparente con olor dulzon penetrante.", "ERROR_ORTOGRAFICO", "goteo_rueda_trasera", "pedal_al_suelo_blandito|gotea_liquido_dulzon", "falla_booster", "", "NO", "SI", "Falla en servofreno (booster) o linea de vacio", "L2 fuga de fluido con ortografía informal.")
    agregar("G30-L2-09", CLASE_30, "L2", "Buenas, cambié los calipers traseros y no usaron escáner para purgar el módulo ABS; el pedal quedó completamente esponjoso y sin mordida inicial.", "WHATSAPP", "purga_sin_escaner_abs", "pedal_esponjoso_falta_purga_abs|sin_mordida", "falla_sensor_abs", "", "NO", "SI", "Falla en sensor de velocidad de rueda ABS", "L2 aire atrapado en acumulador secundario de ABS.")
    agregar("G30-L2-10", CLASE_30, "L2", "Arandela de cobre de unión banjo en la pinza delantera con fuga por falta de apriete; rezuma burbujas diminutas al presionar el pedal con fuerza.", "TECNICO", "inspeccion_union_banjo", "arandela_cobre_rezuma|burbujas_al_pisar_freno", "caliper_trabado", "", "NO", "SI", "Caliper de freno trabado o mordaza pegada (piston agarrotado)", "L2 fuga por unión banjo con entrada de aire.")
    agregar("G30-L2-11", CLASE_30, "L2", "Testigo luminoso de freno de mano y nivel bajo de fluido encendido intermitente en aceleraciones y curvas; nivel de líquido al ras del sensor de flotador.", "COTIDIANO", "curvas_y_aceleracion", "testigo_freno_parpadea_curvas|nivel_ras_flotador", "freno_mano_activado", "", "NO", "NO", "", "L2 sensor de nivel bajo activado en curvas.")
    agregar("G30-L2-12", CLASE_30, "L2", "Tornillo de purga (sangrador) de la mordaza trasera derecha barrido en su rosca; permite entrada de aire por depresión al soltar el pedal de freno.", "TALLER", "inspeccion_sangrador", "sangrador_rosca_barrida|entrada_aire_depresion", "falla_pastillas", "", "NO", "NO", "", "L2 sangrador defectuoso ingresa aire al retornar pedal.")
    agregar("G30-L2-13", CLASE_30, "L2", "Pérdida de presión en circuito diagonal secundario en prueba de doble circuito; el pedal baja 70% de su carrera antes de lograr frenada de emergencia.", "TECNICO", "prueba_circuito_diagonal", "circuito_diagonal_sin_presion|pedal_baja_70_porciento", "falla_servofreno", "", "NO", "SI", "Falla en servofreno (booster) o linea de vacio", "L2 falla de un circuito hidráulico tándem.")
    agregar("G30-L2-14", CLASE_30, "L2", "Líquido de frenos con contenido de humedad superior al 4% medido con tester óptico; vapor lock en descenso de montaña provocó pedal al piso repentino.", "COTIDIANO", "descenso_montana", "vapor_lock_pedal_al_piso|humedad_liquido_mayor_4_porciento", "desgaste_pastillas", "", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L2 ebullición de líquido degradado con vapor lock.")
    agregar("G30-L2-15", CLASE_30, "L2", "Retén del pistón de la mordaza delantera cuarteado; gotea líquido directamente sobre la pastilla de freno dejándola empapada e inoperativa.", "TALLER", "desarme_pinza_delantera", "reten_piston_cuarteado_goteo|pastilla_empapada_liquido", "caliper_pegado", "", "NO", "SI", "Caliper de freno trabado o mordaza pegada (piston agarrotado)", "L2 fuga por sello de émbolo con contaminación de ferodo.")

    # --- L3 (15 casos) ---
    agregar("G30-L3-01", CLASE_30, "L3", "Vehículo ingresa con pedal de frenos esponjoso que desciende progresivamente hasta el tope al mantener 15 bar de presión estática en detención. Se conectaron manómetros en las 4 ruedas comprobándose que al pisar el pedal la presión sube a 40 bar pero cae lentamente a 8 bar sin que exista ninguna gota de líquido de frenos exterior. Al desmontar el cilindro maestro tándem se constató que la copela primaria de caucho EPDM presenta fisuras longitudinales permitiendo bypass de fluido hacia el reservorio.", "TECNICO", "diagnostico_manometros_4_ruedas", "presion_cae_40_a_8bar_sin_fuga_exterior|copela_epdm_fisurada|bypass_cilindro_maestro", "falla_servofreno_booster", "", "NO", "SI", "Falla en servofreno (booster) o linea de vacio", "L3 manómetros revelan caída de 40 a 8 bar por bypass interno en bomba.")
    agregar("G30-L3-02", CLASE_30, "L3", "Conductor reporta pérdida súbita de frenado al salir de la autopista con pedal al piso y encendido del testigo de falla en el tablero. Al elevar el auto se encontró el latiguillo flexible delantero derecho reventado longitudinalmente con malla textil expuesta y deshilachada. El depósito de líquido quedó completamente seco en la cámara primaria mientras que la cámara secundaria del tándem mantuvo 15 mm de líquido residual de seguridad.", "TALLER", "inspeccion_latiguillo_reventado", "latiguillo_reventado_longitudinal|deposito_primario_seco|pedal_al_piso", "falla_caliper", "", "NO", "NO", "", "L3 rotura de flexible de goma por fatiga de material.")
    agregar("G30-L3-03", CLASE_30, "L3", "Camioneta presenta pedal gomoso tras reemplazo de módulo hidráulico ABS. Se realizó purga manual convencional bombeando 5 veces por rueda sin obtener mejora en la firmeza. Se procedió a conectar escáner automotriz activando la función de purga automatizada de válvulas solenoides y bomba de recirculación del ABS durante 60 segundos por ciclo; expulsó gran cantidad de microburbujas atrapadas en los acumuladores de baja presión recuperando pedal rígido a los 25 mm.", "TECNICO", "purga_automatizada_escaner_abs", "purga_automatizada_abs_microburbujas|acumuladores_baja_presion|pedal_rigido_25mm", "falla_sensor_abs", "", "NO", "SI", "Falla en sensor de velocidad de rueda ABS", "L3 purga automatizada con escáner desaloja aire de válvulas ABS.")
    agregar("G30-L3-04", CLASE_30, "L3", "Inspección de freno de tambor trasero en vehículo de carga ligera: el bombín hidráulico de rueda izquierda tiene los guardapolvos inflados de líquido y gotea hacia la parte inferior del plato portafrenos. El líquido de frenos empapó completamente las zapatas de fricción reduciendo la fuerza de frenado de esa rueda a solo 180 N (rueda derecha frena a 1250 N), generando un desequilibrio en frenómetro del 85% inaceptable.", "TALLER", "frenometro_desequilibrio_85_porciento", "bombin_rezuma_zapatas_empapadas|desequilibrio_frenometro_85|fuerza_180n_vs_1250n", "falla_desgaste_zapatas", "", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L3 desequilibrio del 85% en frenómetro por contaminación con fluido.")
    agregar("G30-L3-05", CLASE_30, "L3", "Hola maestro, tengo un Honda Civic. El pedal se me fue hasta abajo de golpe y se prendió el testigo del freno de mano. Encontraron que la cañería de fierro que va por debajo del chasis rozó con el protector de escape hasta que se abrió un huequito chiquito y por ahí salía un chorro a presión cada vez que pisaba el freno.", "WHATSAPP", "cañeria_metalica_rozada_chasis", "pedal_abajo_de_golpe|testigo_freno_prendido|cañeria_fierro_perforada_chorro", "falla_caliper", "", "NO", "NO", "", "L3 cañería de acero perforada por fricción contra protector.")
    agregar("G30-L3-06", CLASE_30, "L3", "Prueba de estanqueidad estática a 100 bar con manómetro en toma de cilindro maestro: tras aislar los 4 calipers con pinzas especiales de manguera, la aguja del manómetro desciende a razón de 4 bar por minuto con motor apagado. Al desmontar el cilindro maestro se encontró ralladura longitudinal profunda de 0.05 mm en el cilindro interno de aluminio mecanizado causada por viruta metálica proveniente de fábrica.", "TECNICO", "prueba_manometro_100bar_aislamiento", "caida_4bar_minuto_aislado|ralladura_cilindro_maestro_0_05mm|fuga_interna", "falla_servofreno", "", "NO", "SI", "Falla en servofreno (booster) o linea de vacio", "L3 aislamiento con pinzas demuestra fuga interna en cilindro maestro.")
    agregar("G30-L3-07", CLASE_30, "L3", "Fenómeno de 'vapor lock' severo en descenso de puerto de montaña: el pedal de frenos se fue a la tabla sin resistencia mecánica. Se extrajo muestra del líquido de frenos registrando punto de ebullición húmedo de 128°C con refractómetro digital (norma DOT 4 exige mínimo 155°C) debido a 5.2% de contaminación por agua absorbida por higroscopía tras 4 años sin reemplazo de fluido.", "TECNICO", "analisis_refractometro_ebullicion_128c", "vapor_lock_pedal_a_tabla|ebullicion_128c_bajo_155c|5_2_porciento_agua_dot4", "desgaste_pastillas", "", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L3 vapor lock por 5.2% de agua en DOT 4 con ebullición a 128°C.")
    agregar("G30-L3-08", CLASE_30, "L3", "Mi carro se quedo sin frenos y el pedal se batió hasta el piso. El mecanico saco la llanta delantera y la manguera flexible de jebe tenia un huevo soplado que revento y boto todo el liquido de frenos en la pista.", "ERROR_ORTOGRAFICO", "manguera_reventada", "pedal_al_piso_sin_freno|manguera_jebe_huevo_soplado_revento", "falla_pastillas", "", "NO", "NO", "", "L3 hernia en flexible de goma con ortografía informal.")
    agregar("G30-L3-09", CLASE_30, "L3", "Evaluación de carrera muerta de pedal en banco de rodillos: se registra carrera libre de 45 mm antes de comenzar el aumento de presión en el circuito hidráulico (especificación máxima 15 mm). Al purgar con máquina presurizadora a 1.5 bar se extraen 3 bolsas de aire de aproximadamente 4 ml cada una desde la pinza trasera izquierda.", "TALLER", "purga_presurizadora_1_5bar", "carrera_muerta_45mm_vs_15mm|extraccion_3_bolsas_aire_4ml|purga_1_5bar", "desgaste_pastillas", "", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L3 extracción de bolsas de aire de 4 ml con equipo presurizador.")
    agregar("G30-L3-10", CLASE_30, "L3", "Buenas tardes, en mi camioneta Hilux el pedal de freno se siente blando y esponjoso; si bombeo dos veces frena arriba perfecto pero a los 10 segundos vuelve a caerse. En el taller revisaron y el bombín de la rueda trasera derecha tiene el sello roto y estaba llenando la campana de aceite de frenos.", "WHATSAPP", "diagnostico_hilux_bombin", "pedal_blando_esponjoso|bombeo_dos_veces_frena|bombin_sello_roto_campana", "caliper_trabado", "", "NO", "SI", "Caliper de freno trabado o mordaza pegada (piston agarrotado)", "L3 fuga en bombín trasero con recuperación momentánea al bombear.")
    agregar("G30-L3-11", CLASE_30, "L3", "Falla de estanqueidad en válvula moduladora de presión de ABS: la electroválvula de descarga de la rueda trasera izquierda quedó parcialmente atascada en posición abierta por acumulación de sedimento gelatinoso de líquido de frenos degradado, permitiendo que la presión hidráulica escape hacia el acumulador de retorno durante el frenado normal.", "TECNICO", "analisis_electrovalvula_abs_abierta", "valvula_descarga_abs_abierta_sedimento|presion_escapa_acumulador", "falla_sensor_abs", "", "NO", "SI", "Falla en sensor de velocidad de rueda ABS", "L3 sedimento atasca electroválvula de descarga en módulo ABS.")
    agregar("G30-L3-12", CLASE_30, "L3", "Conector roscado de tubo rígido en la entrada de la pinza delantera izquierda falseado por sobretorque previo; al aplicar 60 bar de presión con el pedal el líquido sale pulverizado en forma de niebla fina provocando caída instantánea de presión en el circuito primario.", "TALLER", "prueba_presion_niebla_fuga", "sobretorque_rosca_falseada|niebla_pulverizada_liquido_60bar|caida_presion", "caliper_pegado", "", "NO", "SI", "Caliper de freno trabado o mordaza pegada (piston agarrotado)", "L3 pulverización a 60 bar por rosca barrida en cáliper.")
    agregar("G30-L3-13", CLASE_30, "L3", "Medición de rigidez volumétrica de mangueras flexibles de freno con manómetro de precisión: dilatación volumétrica de 0.45 cm3 a 100 bar (especificación OEM menor a 0.15 cm3) en mangueras envejecidas tras 120,000 km, absorbiendo el recorrido del pedal sin generar fuerza de frenado efectiva.", "TECNICO", "dilatacion_volumetrica_mangueras", "dilatacion_0_45cm3_vs_0_15cm3|absorcion_recorrido_pedal|mangueras_envejecidas", "falla_servofreno", "", "NO", "SI", "Falla en servofreno (booster) o linea de vacio", "L3 dilatación volumétrica excesiva de mangueras simula pedal esponjoso.")
    agregar("G30-L3-14", CLASE_30, "L3", "El cliente ingresa indicando que el testigo del freno se encendió y el pedal se hunde al pisar. Se constató pérdida de líquido a través del sensor de presión diferencial del distribuidor de frenos (válvula dosificadora), el cual presenta fuga por el conector eléctrico plástico despegado.", "TALLER", "fuga_valvula_dosificadora", "perdida_sensor_presion_diferencial|conector_despegado|pedal_hunde", "falla_interruptor_freno", "", "NO", "NO", "", "L3 fuga por cuerpo de válvula dosificadora de presión.")
    agregar("G30-L3-15", CLASE_30, "L3", "Doble falla de circuito hidráulico: pérdida total del circuito delantero por corte de flexible con respuesta exclusiva del circuito trasero al 30% de capacidad; pedal desciende hasta el interruptor de stop con encendido del indicador de avería de frenos en cuadro de instrumentos.", "TECNICO", "analisis_doble_circuito_remanente", "corte_flexible_delantero|remanente_trasero_30_porciento|pedal_hasta_tope", "falla_bomba_vacio", "", "NO", "SI", "Falla en servofreno (booster) o linea de vacio", "L3 aislamiento de falla de circuito delantero con remanente trasero.")

    # =========================================================================
    # CLASE 31: Falla en sensor de velocidad de rueda ABS (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G31-L1-01", CLASE_31, "L1", "Se prendió la luz amarilla del ABS en el tablero y no se apaga.", "COTIDIANO", "contacto", "testigo_abs_encendido", "", "", "SI", "NO", "", "L1 testigo ABS encendido.")
    agregar("G31-L1-02", CLASE_31, "L1", "Hola, cuando freno despacito antes de parar el pedal empieza a temblar como loco.", "WHATSAPP", "baja_velocidad", "pedal_tiembla_baja_velocidad", "", "", "SI", "NO", "", "L1 falso disparo de ABS en seco.")
    agregar("G31-L1-03", CLASE_31, "L1", "Aparecen prendidos juntos el foco del ABS y el carrito derrapando.", "COTIDIANO", "marcha", "testigo_abs_y_control_traccion", "", "", "SI", "NO", "", "L1 ABS y control de tracción inhabilitados.")
    agregar("G31-L1-04", CLASE_31, "L1", "El velocímetro a veces se cae a cero mientras voy andando en la pista.", "COTIDIANO", "velocidad_crucero", "velocimetro_cae_a_cero", "", "", "SI", "NO", "", "L1 señal de rueda perdida afecta odómetro.")
    agregar("G31-L1-05", CLASE_31, "L1", "Código de falla de sensor de velocidad de rueda activo en módulo de frenos.", "TECNICO", "diagnostico", "falla_sensor_velocidad_rueda", "", "", "SI", "NO", "", "L1 reporte técnico de sensor WSS.")
    agregar("G31-L1-06", CLASE_31, "L1", "Siento un zapateo en el freno al doblar despacio en las esquinas.", "TALLER", "giro_baja_velocidad", "zapateo_freno_al_doblar", "", "", "SI", "NO", "", "L1 cable con falso contacto en giro.")
    agregar("G31-L1-07", CLASE_31, "L1", "Se desactivó el control de estabilidad y el asistente de arranque en pendiente.", "COTIDIANO", "arranque", "control_estabilidad_desactivado", "", "", "SI", "NO", "", "L1 funciones ESP dependientes de WSS inoperativas.")
    agregar("G31-L1-08", CLASE_31, "L1", "Prendio el foco del ABS y el pedal patea feo al frenar en el semaforo.", "ERROR_ORTOGRAFICO", "detencion", "foco_abs_prendido|pedal_patea", "", "", "SI", "NO", "", "L1 foco ABS y pataleo con ortografía informal.")
    agregar("G31-L1-09", CLASE_31, "L1", "Buenas, cambiaron el rodamiento de rueda y al salir del taller se prendió el ABS.", "WHATSAPP", "post_cambio_rodamiento", "abs_prendido_post_rodamiento", "", "", "SI", "NO", "", "L1 rodaje colocado al revés sin pista magnética.")
    agregar("G31-L1-10", CLASE_31, "L1", "Pérdida de señal de frecuencia alterna en captador magnético de rueda delantera.", "TECNICO", "inspeccion", "perdida_senal_captador_magnetico", "", "", "SI", "NO", "", "L1 reporte técnico de pérdida de pulso inductivo.")

    # --- L2 (15 casos) ---
    agregar("G31-L2-01", CLASE_31, "L2", "Luz de ABS encendida fija con DTC C0035 en escáner; al frenar a más de 40 km/h los frenos funcionan con normalidad pero sin antibloqueo en piso húmedo.", "COTIDIANO", "frenado_mojado", "testigo_abs_dtc_c0035|freno_convencional_ok", "falla_hidraulica_frenos", "C0035", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L2 DTC C0035 sensor delantero izquierdo con hidráulica sana.")
    agregar("G31-L2-02", CLASE_31, "L2", "Activación intempestiva del sistema ABS justo antes de detenerse a menos de 15 km/h en asfalto seco; la punta del sensor de rueda está saturada de limalla de hierro.", "TALLER", "frenado_15kmh_seco", "activacion_abs_baja_velocidad|punta_sensor_limalla_hierro", "falla_discos_freno", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L2 limalla en captador inductivo distorsiona señal a baja velocidad.")
    agregar("G31-L2-03", CLASE_31, "L2", "DTC C0040 referente a circuito del sensor de velocidad delantero derecho; el cableado del sensor se peló por roce contra la llanta en virajes cerrados.", "TECNICO", "inspeccion_cableado", "dtc_c0040|cable_sensor_pelado_roce_llanta", "falla_pastillas", "C0040", "NO", "NO", "", "L2 código C0040 por daño mecánico en cableado.")
    agregar("G31-L2-04", CLASE_31, "L2", "Hola, me cambiaron la bocina de rueda trasera y se prendió el ABS; el mecánico puso el rodaje con la banda magnética hacia afuera y el sensor no lee nada.", "WHATSAPP", "post_cambio_bocina_rueda", "abs_prendido_banda_magnetica_al_reves", "falla_sensor_abs_quemado", "", "NO", "NO", "", "L2 rodamiento con pista de ferrita montado invertido.")
    agregar("G31-L2-05", CLASE_31, "L2", "Lectura de escáner en línea de datos en vivo: la rueda trasera izquierda marca 0 km/h constantes mientras las otras tres ruedas marcan 60 km/h coherentes.", "TECNICO", "linea_datos_velocidad_rueda", "rueda_trasera_0kmh_vs_60kmh_otras|dtc_c0045", "falla_tablero", "C0045", "NO", "SI", "Discos de freno alabeados o desgastados", "L2 rueda a 0 km/h en escáner con DTC C0045.")
    agregar("G31-L2-06", CLASE_31, "L2", "El pedal de freno vibra con un zumbido eléctrico en frenadas suaves; los discos y pastillas son nuevos y no tienen alabeo, pero la luz del ABS parpadea.", "COTIDIANO", "frenada_suave", "pedal_vibra_zumbido_electrico|luz_abs_parpadea", "discos_alabeados", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L2 trepidación eléctrica ABS vs vibración mecánica de disco.")
    agregar("G31-L2-07", CLASE_31, "L2", "Aro reluctor dentado de la junta homocinética fisurado y con dos dientes doblados por impacto de piedra; provoca señal errática de velocidad de rueda.", "TALLER", "inspeccion_homocinetica", "aro_dentado_fisurado_impacto|dientes_doblados", "falla_semieje", "", "NO", "NO", "", "L2 aro fónico roto altera frecuencia de pulsos.")
    agregar("G31-L2-08", CLASE_31, "L2", "Mi camioneta prendio la luz del ABS y el control de traccion derrapando. Al escanear salio codigo C0050 del sensor de rueda trasera derecha.", "ERROR_ORTOGRAFICO", "lectura_escaner", "luz_abs_control_traccion|dtc_c0050_sensor_trasero", "falla_4x4", "C0050", "NO", "NO", "", "L2 código C0050 con ortografía informal.")
    agregar("G31-L2-09", CLASE_31, "L2", "Buenas maestro, en lluvia al frenar suave el carro patalea el pedal y sale aviso de revisar sistema de frenos; los discos están lisitos sin desgaste.", "WHATSAPP", "frenado_lluvia", "pataleo_pedal_lluvia|aviso_revisar_frenos|discos_lisos", "falla_pastillas", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L2 falso disparo ABS en piso húmedo con discos lisos.")
    agregar("G31-L2-10", CLASE_31, "L2", "Sensor de velocidad tipo Hall con resistencia interna abierta infinita medida con multímetro en sus pines; tensión de alimentación de 12V desde el módulo ABS correcta.", "TECNICO", "medicion_resistencia_multimetro", "resistencia_infinita_sensor|alimentacion_12v_ok", "falla_modulo_abs", "", "NO", "NO", "", "L2 sensor de rueda abierto con alimentación de 12V presente.")
    agregar("G31-L2-11", CLASE_31, "L2", "El testigo ABS enciende únicamente al girar la dirección a la izquierda a tope; el ramal de cable del sensor se tensa en exceso y abre el circuito.", "COTIDIANO", "giro_direccion_tope", "testigo_abs_enciende_al_girar_izquierda|cable_tenso", "falla_caja_direccion", "", "NO", "NO", "", "L2 falla posicional por cable corto en suspensión.")
    agregar("G31-L2-12", CLASE_31, "L2", "Entrehierro (gap) entre el sensor de rueda y la corona dentada en 2.4 mm excesivo (tolerancia 0.5 a 1.2 mm) por corrosión que levantó el asiento del sensor.", "TALLER", "medicion_entrehierro_galgas", "entrehierro_2_4mm_excesivo|asiento_levantado_oxido", "falla_caliper", "", "NO", "NO", "", "L2 entrehierro de 2.4 mm atenúa amplitud de señal.")
    agregar("G31-L2-13", CLASE_31, "L2", "El control de crucero adaptativo se desconecta solo y acusa código de incoherencia de velocidad de rueda en el eje delantero; pastillas y líquido en buen estado.", "COTIDIANO", "crucero_autopista", "control_crucero_desconecta|incoherencia_velocidad_rueda", "falla_pastillas_liquido", "", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L2 control crucero afectado por lectura falsa de WSS.")
    agregar("G31-L2-14", CLASE_31, "L2", "Conector de 2 pines del sensor ABS delantero izquierdo sulfatado por ingreso de agua; resistencia de contacto de 450 ohms distorsiona la forma de onda.", "TECNICO", "inspeccion_conector_sulfatado", "conector_2_pines_sulfatado_agua|resistencia_contacto_450ohm", "falla_fusible", "", "NO", "NO", "", "L2 sulfatación en conector genera caída de tensión.")
    agregar("G31-L2-15", CLASE_31, "L2", "El velocímetro digital oscila de forma errática entre 40 y 90 km/h al circular en autopista constante; la rueda fónica trasera tiene acumulación de barro y gravilla.", "COTIDIANO", "autopista_constante", "velocimetro_oscila_erratico|rueda_fonica_barro_gravilla", "falla_velocimetro", "", "NO", "NO", "", "L2 barro en rueda fónica descalibra señal al cuadro.")

    # --- L3 (15 casos) ---
    agregar("G31-L3-01", CLASE_31, "L3", "En un Ford Focus con testigo ABS y ESP encendidos se registra DTC C0035 (Left Front Wheel Speed Sensor Circuit). Se conectó osciloscopio automotriz en los pines 1 y 2 del sensor captando señal en prueba de rodaje a 30 km/h: la onda cuadrada de corriente del sensor activo tipo magnetoresistivo entrega solo 4 mA en nivel bajo y 8 mA en nivel alto (especificación OEM 7 mA bajo y 14 mA alto). Al desmontar el sensor se constató fisura en la carcasa plástica con ingreso de agua y sales que degradaron el circuito integrado de detección.", "TECNICO", "osciloscopio_sensor_activo_4_a_8ma", "dtc_c0035|onda_cuadrada_corriente_4_a_8ma_baja|sensor_activo_fisurado", "falla_modulo_bcm", "C0035", "NO", "NO", "", "L3 oscilograma de sensor activo de 4 a 8 mA vs 7 a 14 mA nominal.")
    agregar("G31-L3-02", CLASE_31, "L3", "Vehículo presenta activación indeseada del pedal de freno con trepidación violenta a menos de 10 km/h en pavimento seco, deteniéndose 4 metros más largo de lo normal. En el escáner se graficaron las 4 ruedas en simultáneo: a 8 km/h la señal de la rueda delantera derecha colapsa a 0 km/h prematuramente mientras las otras 3 mantienen lectura decreciente lineal correcta. Se inspeccionó el sensor inductivo comprobándose acumulación de 3 mm de polvo ferroso magnético en la punta que amortigua la inducción a baja velocidad.", "TALLER", "grafica_4_ruedas_escaner_8kmh", "trepidacion_frenado_10kmh|rueda_derecha_cae_a_0kmh|polvo_ferroso_sensor", "discos_freno_alabeados", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L3 gráfica de 4 ruedas delata caída prematura a 0 km/h por polvo ferroso.")
    agregar("G31-L3-03", CLASE_31, "L3", "Chevrolet Cruze ingresa tras reemplazo de rodamiento delantero con DTC C0040 y C0035. Con tarjeta detectora de polaridad magnética se verificó el rodamiento nuevo de rueda, constatándose que el taller instaló un rodamiento genérico sin encoder magnético integrado (60 polos magnéticos ausentes en el sello). Al cambiar por el rodaje con pista codificada original el módulo ABS reconoció la señal instantáneamente borrando el código permanente.", "TECNICO", "prueba_tarjeta_detectora_polos", "dtc_c0040|rodamiento_sin_encoder_magnetico|60_polos_ausentes", "falla_modulo_abs", "C0040", "NO", "NO", "", "L3 tarjeta reveladora confirma ausencia de encoder de 60 polos en rodamiento.")
    agregar("G31-L3-04", CLASE_31, "L3", "Conductor reporta que al frenar a alta velocidad el timón no vibra pero el pedal zapatea erráticamente con la luz de frenos destellando. Se midió el alabeo de discos arrojando 0.02 mm perfecto. Al inspeccionar el semieje delantero se descubrió que el aro reluctor fónico de 48 dientes tiene una fisura por fatiga que ensanchó el espacio entre dos dientes a 4.2 mm (paso normal 2.1 mm), generando un pulso faltante periódico que la ECU interpreta como bloqueo ficticio de rueda.", "TALLER", "inspeccion_aro_fonico_fisurado", "aro_reluctor_fisurado_paso_4_2mm|pulso_faltante_bloqueo_falso|disco_0_02mm_ok", "discos_alabeados", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L3 fisura en aro fónico de 48 dientes simula bloqueo ficticio de rueda.")
    agregar("G31-L3-05", CLASE_31, "L3", "Hola maestro, tengo un Sentra. En las mañanas arranco y todo bien, pero apenas paso los 50 km/h se prende el testigo del ABS y el de derrape. El mecánico le metió escáner y sale sensor de rueda trasera izquierda C0045; le midió la señal con una pantallita y la onda se corta cada vez que agarro un bache porque el cable estaba quebrado por dentro.", "WHATSAPP", "diagnostico_sentra_bache", "abs_derrape_a_50kmh|dtc_c0045_sensor_trasero|onda_se_corta_en_bache|cable_quebrado", "falla_amortiguadores", "C0045", "NO", "NO", "", "L3 código C0045 por cable con quiebre interno intermitente en baches.")
    agregar("G31-L3-06", CLASE_31, "L3", "Análisis con osciloscopio digital automotriz de sensor inductivo pasivo de rueda delantera: a 40 km/h la señal senoidal entrega 1.8 Vpp (especificación 1.5 a 2.5 Vpp) pero presenta una modulación de amplitud sinusoidal de 0.6 Vpp a 3.2 Vpp por cada vuelta completa de la rueda. La medición de concentricidad del aro fónico montado en la homocinética reveló descentramiento radial de 0.85 mm por golpe en el palier.", "TECNICO", "osciloscopio_modulacion_amplitud_radial", "amplitud_oscila_0_6_a_3_2vpp|descentramiento_radial_0_85mm_aro_fonico", "falla_homocinetica", "", "NO", "NO", "", "L3 modulación de amplitud de 0.6 a 3.2 Vpp por descentramiento de 0.85 mm.")
    agregar("G31-L3-07", CLASE_31, "L3", "DTC C0050 y C0226 en camioneta 4x4; el sensor de velocidad de rueda trasera derecha presenta voltaje de polarización de 11.8V desde el calculador ABS pero no genera conmutación de corriente al girar la rueda a mano. Se midió el entrehierro con galgas de bronce encontrando 3.1 mm debido a que el soporte de fijación en el puente rígido se deformó por impacto contra una roca en camino de trocha.", "TALLER", "medicion_entrehierro_3_1mm_trocha", "dtc_c0050_c0226|entrehierro_3_1mm_vs_1_0mm|soporte_deformado_roca", "falla_diferencial", "C0050", "NO", "NO", "", "L3 soporte deformado genera entrehierro de 3.1 mm con DTC C0050.")
    agregar("G31-L3-08", CLASE_31, "L3", "Mi carro prendio el foco del ABS y el velocimetro se volvio loco subiendo y bajando. Le pusieron el escaner y salio codigo C0035 de rueda delantera. El mecanico saco el sensor y la punta estaba rajada y llena de oxido que no dejaba pasar la corriente.", "ERROR_ORTOGRAFICO", "escaner_c0035_velocimetro", "foco_abs_prendido|velocimetro_loco|dtc_c0035|punta_rajada_oxido", "falla_velocimetro", "C0035", "NO", "NO", "", "L3 DTC C0035 con punta dañada con ortografía informal.")
    agregar("G31-L3-09", CLASE_31, "L3", "Interferencias electromagnéticas por inducción en la línea del sensor de rueda ABS: el cable blindado de señal perdió la malla de conexión a masa en el conector del pasamuros. En aceleración fuerte las descargas de alta tensión del sistema de encendido generan picos parásitos de 4V en la señal de rueda disparando falsamente el control de tracción TCS.", "TECNICO", "analisis_ruido_electromagnetico_tcs", "picos_parasitos_4v_encendido|malla_blindaje_abierta|tcs_disparo_falso", "falla_bujias_encendido", "", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L3 picos parásitos de 4V por blindaje roto activan falso control de tracción.")
    agregar("G31-L3-10", CLASE_31, "L3", "Buenas tardes, en el concesionario me diagnosticaron código C0040. Me dijeron que el módulo ABS está perfecto y que el problema es el sensor de la rueda derecha delantera que se quemó por recalentamiento de frenos cuando bajé la cordillera. Las pastillas se habían cristalizado por exceso de calor.", "WHATSAPP", "diagnostico_concesionario_calor", "dtc_c0040_sensor_quemado_calor|modulo_abs_ok|pastillas_cristalizadas", "desgaste_pastillas", "C0040", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L3 sensor dañado térmicamente por recalentamiento de pastillas.")
    agregar("G31-L3-11", CLASE_31, "L3", "Prueba de coherencia dinámica de velocidad de ruedas a 80 km/h: ruedas delanteras marcan 80.2 km/h y 80.5 km/h, pero la rueda trasera derecha registra saltos instantáneos de 80 a 35 km/h cada 12 segundos. Se desmontó el cubo de rueda detectándose que la pista magnética de neodimio se desprendió parcialmente en un arco de 40 grados del sello elastomérico.", "TECNICO", "analisis_coherencia_pista_neodimio", "saltos_80_a_35kmh|desprendimiento_neodimio_40_grados|rueda_trasera", "falla_diferencial", "", "NO", "NO", "", "L3 desprendimiento de pista de neodimio genera caída de 80 a 35 km/h.")
    agregar("G31-L3-12", CLASE_31, "L3", "DTC C0045 y C1201 con inhabilitación de ABS y reparto electrónico EBD; la tensión de alimentación de 12V al sensor trasero izquierdo se cae a 3.2V bajo carga por corrosión sulfatada en el pin 14 del conector intermedio de chasis bajo el asiento trasero, impidiendo la polarización del elemento Hall.", "TECNICO", "caida_tension_pin14_conector_chasis", "dtc_c0045_c1201|alimentacion_cae_12_a_3_2v|sulfatacion_pin14", "falla_cableado_general", "C0045", "NO", "NO", "", "L3 caída de tensión a 3.2V por corrosión en conector de chasis con C0045.")
    agregar("G31-L3-13", CLASE_31, "L3", "Comportamiento anómalo en frenado sobre calzada seca: al frenar de 20 a 0 km/h el pedal patea y la distancia de parada se alarga 3 metros con sonido de carraca de la bomba ABS. Los discos no presentan alabeo (0.015 mm) y las pastillas tienen 9 mm; el sensor delantero izquierdo acusa pérdida de dientes por óxido exfoliado en la corona homocinética.", "TALLER", "prueba_frenado_seco_alargado", "parada_alargada_3m|carraca_bomba_abs|discos_ok_0_015mm|corona_oxido_exfoliado", "discos_alabeados", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L3 parada alargada 3m por carraca de ABS provocada por corona oxidada.")
    agregar("G31-L3-14", CLASE_31, "L3", "Incompatibilidad de señal de velocidad tras instalar neumático de diferente perfil en el eje trasero: neumático derecho 205/55R16 y neumático izquierdo 205/60R16 (diferencia de diámetro de 3.2%). El módulo ABS detecta diferencia continua de velocidad superior al umbral del 3% encendiendo el testigo por código de correlación de rueda.", "TECNICO", "diferencia_diametro_neumatico_3_2", "neumaticos_diferente_perfil_3_2_porciento|diferencia_velocidad_umbral_3|codigo_correlacion", "llantas_desbalanceadas", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L3 diferencia de rodadura del 3.2% simula falla de sensor de rueda.")
    agregar("G31-L3-15", CLASE_31, "L3", "Señal en rampa de sensor magneto-resistivo bidireccional (con detección de sentido de giro): el flanco de subida tarda 12 microsegundos en alcanzar nivel alto (especificación menor a 2 us) debido a degradación de capacitancia parásita en el cable de señal apantallado que se dobló en ángulo recto en el trapecio inferior.", "TECNICO", "analisis_flanco_subida_12us", "flanco_subida_12us_lento|capacitancia_parasita_cable|degradacion_apantallado", "falla_sensor_rueda", "", "NO", "NO", "", "L3 degradación de flanco a 12 microsegundos por pinzamiento de cable.")

    # =========================================================================
    # CLASE 32: Falla en sistema de frenado regenerativo (EV / Hibridos) (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G32-L1-01", CLASE_32, "L1", "En mi auto híbrido el indicador de carga ya no regenera energía al levantar el pie.", "COTIDIANO", "desaceleracion", "sin_regeneracion_energia", "", "", "SI", "NO", "", "L1 pérdida de recarga regenerativa.")
    agregar("G32-L1-02", CLASE_32, "L1", "Hola, apareció un aviso en la pantalla de frenado regenerativo deshabilitado.", "WHATSAPP", "marcha", "aviso_frenado_regenerativo_deshabilitado", "", "", "SI", "NO", "", "L1 mensaje en cuadro de instrumentos.")
    agregar("G32-L1-03", CLASE_32, "L1", "El carro eléctrico se siente suelto al frenar y no desacelera con la fuerza de antes.", "COTIDIANO", "frenado_urbano", "carro_suelto_no_desacelera", "", "", "SI", "NO", "", "L1 ausencia de frenado de un solo pedal.")
    agregar("G32-L1-04", CLASE_32, "L1", "Se siente un tirón tosco y feo justo cuando pasa del freno eléctrico al de disco.", "TALLER", "transicion_frenado", "tiron_tosco_transicion_freno", "", "", "SI", "NO", "", "L1 fallo en mezcla blending de frenado.")
    agregar("G32-L1-05", CLASE_32, "L1", "Código de falla en la unidad de control de freno electrohidráulico del sistema híbrido.", "TECNICO", "diagnostico", "falla_freno_electrohidraulico_hibrido", "", "", "SI", "NO", "", "L1 reporte técnico de ECB.")
    agregar("G32-L1-06", CLASE_32, "L1", "La bomba eléctrica de los frenos suena zumbando cada 5 segundos sin parar.", "COTIDIANO", "contacto", "bomba_frenos_zumba_cada_5seg", "", "", "SI", "NO", "", "L1 acumulador perdiendo presión en híbrido.")
    agregar("G32-L1-07", CLASE_32, "L1", "Aparece un triángulo rojo con alarma de avería en el sistema de frenos híbrido.", "COTIDIANO", "encendido", "triangulo_rojo_frenos_hibrido", "", "", "SI", "NO", "", "L1 aviso de alerta maestra híbrida.")
    agregar("G32-L1-08", CLASE_32, "L1", "Mi carro hibrido no frena con el motor y el pedal ase un click estraño.", "ERROR_ORTOGRAFICO", "desaceleracion", "no_frena_con_motor|click_extranno_pedal", "", "", "SI", "NO", "", "L1 frenado regenerativo con ortografía informal.")
    agregar("G32-L1-09", CLASE_32, "L1", "Buenas, el pedal de mi auto eléctrico se siente artificial y como desconectado.", "WHATSAPP", "frenado", "pedal_freno_artificial_desconectado", "", "", "SI", "NO", "", "L1 simulador de carrera de pedal defectuoso.")
    agregar("G32-L1-10", CLASE_32, "L1", "Fallo de comunicación entre el inversor de tracción y el módulo de gestión de frenada regenerativa.", "TECNICO", "inspeccion", "fallo_comunicacion_inversor_frenos", "", "", "SI", "NO", "", "L1 reporte técnico de bus CAN híbrido.")

    # --- L2 (15 casos) ---
    agregar("G32-L2-01", CLASE_32, "L2", "En un Toyota Prius con batería al 50% de carga no hay recuperación de energía en desaceleración; la barra de CHG no sube y salta el aviso 'Check Brake System'.", "COTIDIANO", "desaceleracion_50_soc", "sin_recuperacion_energia_50soc|aviso_check_brake_system", "bateria_100_soc", "", "NO", "SI", "Degradacion o falla en paquete de bateria de alto voltaje (EV / Hibridos)", "L2 falla con batería al 50% descarta limitación por batería llena.")
    agregar("G32-L2-02", CLASE_32, "L2", "DTC C1391 referente a pérdida anormal de presión en el acumulador del actuador de frenos de un Lexus híbrido; la bomba eléctrica trabaja continuamente cada 8 segundos.", "TECNICO", "diagnostico_actuador_frenos", "dtc_c1391|perdida_presion_acumulador|bomba_activa_cada_8seg", "falla_sensor_abs", "C1391", "NO", "SI", "Falla en sensor de velocidad de rueda ABS", "L2 código C1391 por fuga interna en actuador electrohidráulico.")
    agregar("G32-L2-03", CLASE_32, "L2", "Transición brusca con golpe seco en el pedal al frenar suave de 30 a 10 km/h; el sistema no logra sincronizar el freno de regeneración con las pastillas hidráulicas.", "TALLER", "transicion_30_a_10kmh", "golpe_seco_pedal_transicion|falla_sincronizacion_blending", "discos_alabeados", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L2 fallo de blending entre frenado eléctrico y mecánico.")
    agregar("G32-L2-04", CLASE_32, "L2", "Hola, en mi auto eléctrico Nissan Leaf el modo e-Pedal dejó de retener el carro; al soltar el acelerador se va libre como si estuviera en neutro.", "WHATSAPP", "conduccion_epedal", "epedal_dejo_de_retener|rueda_libre_en_neutro", "falla_pastillas_freno", "", "NO", "NO", "", "L2 modo One-Pedal inoperativo por fallo en regeneración.")
    agregar("G32-L2-05", CLASE_32, "L2", "DTC C1203 en módulo de control de frenado por falla de comunicación CAN con la ECU del inversor híbrido; el vehículo solo frena mediante el circuito hidráulico de emergencia.", "TECNICO", "red_can_inversor", "dtc_c1203|sin_comunicacion_can_inversor|frenado_hidraulico_emergencia", "falla_bomba_frenos", "C1203", "NO", "NO", "", "L2 código C1203 de enlace entre freno y control de potencia.")
    agregar("G32-L2-06", CLASE_32, "L2", "Sensor de carrera del pedal de freno (Stroke Sensor) descalibrado con voltaje fuera de rango de 0.8V a 3.8V; el calculador no determina la demanda del conductor.", "TECNICO", "calibracion_stroke_sensor", "stroke_sensor_voltaje_fuera_rango|demanda_desconocida", "falla_interruptor_freno", "", "NO", "NO", "", "L2 sensor de carrera de pedal descalibrado.")
    agregar("G32-L2-07", CLASE_32, "L2", "Al frenar en bajada en un híbrido el motor térmico se enciende a altas revoluciones sin acelerar; el sistema intenta frenar por compresión porque la regeneración eléctrica falló.", "COTIDIANO", "bajada_hibrido", "motor_termico_ruge_sin_acelerar|sin_frenado_electrico", "falla_transmision_cvt", "", "NO", "NO", "", "L2 motor ruge frenando por motor ante fallo regenerativo.")
    agregar("G32-L2-08", CLASE_32, "L2", "Mi carro hibrido no recarga nada la bateria al frenar y sale codigo C1256 en la computadora. El pedal se siente mas duro que antes.", "ERROR_ORTOGRAFICO", "lectura_escaner", "no_recarga_bateria_frenar|dtc_c1256|pedal_duro", "falla_servofreno", "C1256", "NO", "SI", "Falla en servofreno (booster) o linea de vacio", "L2 código C1256 con baja presión en acumulador con ortografía informal.")
    agregar("G32-L2-09", CLASE_32, "L2", "Buenas maestro, en mi Prius se prendieron las luces de ABS, VSC y freno juntas; me dicen que el actuador de freno de regeneración no retiene presión.", "WHATSAPP", "cuadro_luces_prius", "luces_abs_vsc_freno_juntas|actuador_freno_sin_presion", "falla_sensor_abs", "", "NO", "SI", "Falla en sensor de velocidad de rueda ABS", "L2 terna de testigos en Prius por actuador de freno averiado.")
    agregar("G32-L2-10", CLASE_32, "L2", "Válvula solenoide lineal de corte de presión regenerativa atascada con limalla; no permite el paso de líquido hacia el simulador de carrera del pedal.", "TALLER", "desarme_bloque_hidraulico", "valvula_lineal_corte_atascada|simulador_carrera_bloqueado", "caliper_trabado", "", "NO", "SI", "Caliper de freno trabado o mordaza pegada (piston agarrotado)", "L2 electroválvula lineal de mezcla de frenada bloqueada.")
    agregar("G32-L2-11", CLASE_32, "L2", "El freno regenerativo se desactiva bruscamente al tocar un desnivel en el pavimento; no hay códigos de sensor de rueda y la batería de tracción está al 60%.", "COTIDIANO", "bache_desnivel", "regenerativo_desactiva_bache|sin_dtc_sensor_rueda|bateria_60_soc", "falla_sensor_velocidad", "", "NO", "SI", "Falla en sensor de velocidad de rueda ABS", "L2 desconexión intempestiva de regeneración en desniveles.")
    agregar("G32-L2-12", CLASE_32, "L2", "DTC C1345 referente a falta de aprendizaje del desplazamiento de la válvula lineal del actuador de freno tras cambio de pastillas en vehículo híbrido.", "TECNICO", "aprendizaje_lineal_c1345", "dtc_c1345|falta_aprendizaje_valvula_lineal_freno", "falla_pastillas_nuevas", "C1345", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L2 código C1345 de calibración de válvula lineal.")
    agregar("G32-L2-13", CLASE_32, "L2", "Consumo excesivo de pastillas de freno en vehículo eléctrico (duraron solo 15,000 km); la frenada regenerativa nunca entra y frena exclusivamente por fricción.", "TALLER", "inspeccion_desgaste_ev", "pastillas_agotadas_15000km_ev|sin_regeneracion_electrica", "caliper_pegado", "", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L2 pastillas consumidas prematuramente por inoperancia regenerativa.")
    agregar("G32-L2-14", CLASE_32, "L2", "Mensaje en pantalla central 'Potencia de frenado reducida' en híbrido enchufable; la bomba de precarga eléctrica no alcanza los 15 MPa de consigna.", "COTIDIANO", "arranque_hibrido", "mensaje_potencia_frenado_reducida|bomba_no_alcanza_15mpa", "falla_liquido_frenos", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L2 presión de acumulador por debajo de 15 MPa.")
    agregar("G32-L2-15", CLASE_32, "L2", "DTC C1241 por voltaje bajo de alimentación en la ECU de frenado asistido de control electrónico (ECB); la regeneración queda deshabilitada por seguridad.", "TECNICO", "tension_bateria_auxiliar_12v", "dtc_c1241|voltaje_bajo_ecu_ecb|regeneracion_inhabilitada", "falla_bateria_alta_tension", "C1241", "NO", "NO", "", "L2 código C1241 por alimentación auxiliar deficiente.")

    # --- L3 (15 casos) ---
    agregar("G32-L3-01", CLASE_32, "L3", "En un Toyota Prius 2018 con 145,000 km se encienden simultáneamente los testigos de ABS, VSC y el símbolo de exclamación de frenos acompañado de DTC C1391 (Abnormal Leak of Accumulator Pressure). Con la herramienta de diagnóstico Techstream se monitorea la presión del acumulador hidráulico: la bomba de presurización arranca cada 6 segundos durante 2.5 segundos para elevar la presión de 12.2 MPa a 15.5 MPa, cayendo inmediatamente sin pisar el pedal. Las pinzas de freno mecánicas no presentan fugas y las pastillas tienen 6 mm; el fallo se debe a fuga interna en la electroválvula de retención del Brake Actuator.", "TECNICO", "diagnostico_techstream_c1391", "dtc_c1391|presion_cae_15_5_a_12_2mpa_cada_6seg|fuga_interna_brake_actuator", "fuga_hidraulica_frenos", "C1391", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L3 Techstream confirma ciclo de bomba cada 6s y DTC C1391 en actuador híbrido.")
    agregar("G32-L3-02", CLASE_32, "L3", "Vehículo eléctrico Kia Niro EV presenta pérdida completa del frenado regenerativo regenerando 0 kW tanto en modo e-Pedal como al aplicar el pedal de freno. La batería de alto voltaje se encuentra al 55% de SoC y temperatura de 24°C nominales (descartando limitación por batería llena o frío extremo). En escáner se registra código C1203 por fallo de coherencia en el sensor de carrera del pedal (Stroke Sensor): el potenciómetro 1 marca 1.15V mientras el canal 2 marca 3.82V en reposo (discrepancia de correlación superior al 15% de tolerancia).", "TECNICO", "analisis_stroke_sensor_doble_canal", "dtc_c1203|0kw_regeneracion_55_soc|discrepancia_stroke_sensor_canales|temperatura_24c_ok", "degradacion_bateria_alta_tension", "C1203", "NO", "SI", "Degradacion o falla en paquete de bateria de alto voltaje (EV / Hibridos)", "L3 correlación de doble canal fallida en stroke sensor con 55% SoC.")
    agregar("G32-L3-03", CLASE_32, "L3", "El cliente reclama que su auto híbrido tironea violentamente al frenar entre 25 y 15 km/h como si el freno se trabara por un instante. Se realizó registro de datos en tiempo real: en el momento exacto de la transición de frenado regenerativo a freno de fricción hidráulica la presión en las pinzas delanteras salta de 0 a 38 bar en 40 milisegundos debido a calibración defectuosa de la válvula lineal de presurización SLA tras cambio de líquido de frenos sin el procedimiento de purga y aprendizaje de cero lineal.", "TALLER", "registro_transicion_blending_38bar", "salto_presion_0_a_38bar_en_40ms|tiron_frenado_25_a_15kmh|falta_aprendizaje_cero_lineal", "discos_alabeados", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L3 salto brusco de 38 bar en 40 ms por falta de aprendizaje de válvula lineal.")
    agregar("G32-L3-04", CLASE_32, "L3", "DTC C1345 (Linear Solenoid Valve Offset Learning Incomplete) y C1256 (Accumulator Low Pressure) en Lexus CT200h tras intentar sustituir pastillas de freno en taller multimarca sin poner el sistema en modo mantenimiento 'Pad Replacement'. El motor de la bomba presurizadora fue desconectado mientras el acumulador estaba bajo presión, perdiendo la memorización de los offsets de las válvulas lineales de control de frenada regenerativa.", "TECNICO", "diagnostico_offset_learning_c1345", "dtc_c1345_c1256|modo_pad_replacement_no_usado|perdida_offsets_lineales", "desgaste_pastillas", "C1345", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L3 código C1345 y C1256 por omisión de modo de servicio en híbrido.")
    agregar("G32-L3-05", CLASE_32, "L3", "Hola maestro, tengo un Corolla Hybrid. Cuando freno en bajadas la aguja de carga CHG no se mueve nada y el pedal se puso duro y esponjoso al final. En el escáner me dicen que salió código C1391 y que la bomba que carga la presión de los frenos suena zumbando a cada rato en el motor aunque no toque el freno.", "WHATSAPP", "diagnostico_corolla_hybrid", "aguja_chg_no_mueve|dtc_c1391|bomba_zumba_continuo_sin_tocar_freno", "falla_servofreno", "C1391", "NO", "SI", "Falla en servofreno (booster) o linea de vacio", "L3 relato WhatsApp de bomba zumbando y código C1391 en Corolla Hybrid.")
    agregar("G32-L3-06", CLASE_32, "L3", "Frenada regenerativa intermitente en Tesla Model 3 durante desaceleraciones de autopista: el inversor de tracción del eje trasero aborta la regeneración enviando trama CAN de desconexión. La lectura de temperatura de los módulos IGBT del inversor marca 98°C excesiva (consigna máxima 75°C) debido a que la bomba eléctrica de refrigeración del circuito de baja temperatura de electrónica de potencia tiene el impulsor partido.", "TECNICO", "telemetria_inversor_temperatura_98c", "temperatura_inversor_98c_aborto_regen|bomba_refrigeracion_rota|desconexion_can", "falla_motor_electrico", "", "NO", "NO", "", "L3 sobrecalentamiento de inversor a 98°C aborta regeneración.")
    agregar("G32-L3-07", CLASE_32, "L3", "Inspección de actuador de freno de control electrónico (ECB) en banco de pruebas: el sensor de presión de la cámara del acumulador acusa 14.8 MPa correcto, pero la válvula electromagnética de simulación de carrera de pedal no abre al aplicar 200 N de fuerza sobre el pedal, provocando que el pedal se sienta como un bloque sólido sin retroalimentación sensorial ergonómica.", "TALLER", "prueba_banco_simulador_carrera", "valvula_simulador_carrera_no_abre|pedal_bloque_solido_200n|acumulador_14_8mpa_ok", "falla_servofreno_vacio", "", "NO", "SI", "Falla en servofreno (booster) o linea de vacio", "L3 simulador de carrera bloqueado simula pedal rígido con presión correcta.")
    agregar("G32-L3-08", CLASE_32, "L3", "Mi carro hibrido se le prendio el triangulo rojo y no regenera corriente cuando bajo pendientes con codigo C1256. El pedal tiembla al pisar y la bomba de abajo del capot no para de sonar ta-ta-ta-ta cada 10 segundos.", "ERROR_ORTOGRAFICO", "alerta_triangulo_rojo", "triangulo_rojo|dtc_c1256|sin_regeneracion_pendientes|bomba_suena_cada_10s", "falla_bateria", "C1256", "NO", "SI", "Degradacion o falla en paquete de bateria de alto voltaje (EV / Hibridos)", "L3 código C1256 y ciclo continuo de presurización con ortografía informal.")
    agregar("G32-L3-09", CLASE_32, "L3", "DTC C1203 y U0100 en vehículo híbrido; pérdida de comunicación en el bus CAN dedicado de alta velocidad (500 kbps) entre el módulo de frenado regenerativo y el controlador del motor generador MG2. La medición de resistencia con osciloscopio en los pines CAN-H y CAN-L arrojó 120 ohms en lugar de los 60 ohms nominales por apertura de la resistencia de terminación interna del actuador.", "TECNICO", "analisis_resistencia_can_120ohm", "dtc_c1203_u0100|resistencia_can_120ohm_vs_60ohm|resistencia_terminacion_abierta", "falla_red_can_general", "C1203", "NO", "NO", "", "L3 resistencia CAN de 120 ohms por falla en terminador del actuador de freno.")
    agregar("G32-L3-10", CLASE_32, "L3", "Buenas tardes, tengo un Hyundai Ioniq Híbrido. En ciudad frena con un ruido de roce metálico espantoso y no carga la batería en desaceleración. Lo revisaron en el taller y me dicen que el sistema de frenada regenerativa se desconectó por código C1241 de bajo voltaje y todo el esfuerzo lo están haciendo las pastillas mecánicas que ya se gastaron al fierro.", "WHATSAPP", "diagnostico_ioniq_hibrido", "dtc_c1241|pastillas_al_fierro|sin_carga_bateria_desaceleracion|roce_metalico", "desgaste_pastillas", "C1241", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L3 código C1241 inactiva regeneración provocando desgaste total de pastillas.")
    agregar("G32-L3-11", CLASE_32, "L3", "Prueba de dinamómetro con regeneración activa a 70 km/h: el par de frenado eléctrico generado por el motor MG2 oscila erráticamente entre 20 Nm y 180 Nm debido a fallo en el sensor resolver de posición angular del rotor del generador, provocando que la ECU de frenado corte la regeneración por seguridad y aplique bruscamente el circuito hidráulico de fricción.", "TECNICO", "dinamometro_par_mg2_oscilante", "par_mg2_oscila_20_a_180nm|falla_sensor_resolver_mg2|corte_seguridad_friccion", "falla_motor_electrico", "", "NO", "NO", "", "L3 fallo de resolver en motor generador desestabiliza par de frenado.")
    agregar("G32-L3-12", CLASE_32, "L3", "Incompatibilidad de par de frenado en vehículo híbrido tras actualización de software de ECU de control de tracción: el integrador de regeneración solicita 220 Nm al MG2 pero la batería híbrida de níquel-metal hidruro limita la corriente de carga a 18 amperios por sobretemperatura en celda 6 (52°C) disparando DTC C1259 de inhibición del sistema regenerativo.", "TECNICO", "telemetria_celda_52c_dtc_c1259", "dtc_c1259|limite_carga_18a_celda6_52c|demanda_220nm_rechazada", "degradacion_bateria_alta_tension", "C1259", "NO", "SI", "Degradacion o falla en paquete de bateria de alto voltaje (EV / Hibridos)", "L3 código C1259 por rechazo de carga ante sobretemperatura de celda.")
    agregar("G32-L3-13", CLASE_32, "L3", "Desgaste asimétrico severo en pinzas de freno de disco de un Toyota Prius con solo 25,000 km: la falta de uso de los frenos mecánicos por conducción suave urbana provocó agarrotamiento por óxido en las guías flotantes del caliper, impidiendo que el pistón se desplace libremente cuando el sistema requiere asistencia de fricción tras desconectar la regeneración a menos de 10 km/h.", "TALLER", "oxido_guias_por_desuso_hibrido", "guias_oxidadas_desuso_urbano|freno_mecanico_no_desplaza_10kmh|25000km", "caliper_pegado", "", "NO", "SI", "Caliper de freno trabado o mordaza pegada (piston agarrotado)", "L3 agarrotamiento de guías por desuso característico en híbridos.")
    agregar("G32-L3-14", CLASE_32, "L3", "Pérdida de calibración del sensor de ángulo de pedal de freno tras cambio de interruptor de stop: el voltaje de reposo quedó en 1.45V (especificación 0.70 a 0.95V), lo que provoca que la computadora interprete que el pedal está permanentemente presionado, impidiendo la aceleración normal y anulando la transición fluida a frenado regenerativo.", "TECNICO", "calibracion_voltaje_reposo_1_45v", "voltaje_reposo_1_45v_alto|freno_interpretado_presionado|sin_transicion_fluida", "falla_interruptor_freno", "", "NO", "NO", "", "L3 voltaje en reposo de 1.45V por mal reglaje de sensor de freno.")
    agregar("G32-L3-15", CLASE_32, "L3", "Evaluación de recuperación energética en ciclo WLTP urbano: vehículo híbrido recupera solo 0.08 kWh por cada 10 km (valor de referencia OEM 0.42 kWh/10 km) con DTC C1391 en memoria. La prueba de hermeticidad demostró fuga interna en el bloque de electroválvulas proporcional del actuador hidráulico que despresuriza el acumulador.", "TECNICO", "analisis_recuperacion_wltp_0_08kwh", "recuperacion_0_08kwh_vs_0_42kwh|dtc_c1391|fuga_bloque_electrovalvulas", "falla_inversor", "C1391", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L3 recuperación de 0.08 kWh vs 0.42 kWh con DTC C1391 por fuga en actuador.")

    # =========================================================================
    # CLASE 33: Caliper de freno trabado o mordaza pegada (piston agarrotado) (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G33-L1-01", CLASE_33, "L1", "Una sola de las ruedas delanteras se calienta tanto que quema al tocar el aro.", "COTIDIANO", "post_recorrido", "rueda_quema_muy_caliente", "", "", "SI", "NO", "", "L1 calor abrasador en una sola rueda.")
    agregar("G33-L1-02", CLASE_33, "L1", "Hola, siento un olor muy fuerte a quemado saliendo de la llanta derecha.", "WHATSAPP", "marcha", "olor_quemado_llanta_derecha", "", "", "SI", "NO", "", "L1 olor a ferodo quemado continuo.")
    agregar("G33-L1-03", CLASE_33, "L1", "El carro se jala para el lado izquierdo cuando manejo en línea recta.", "COTIDIANO", "linea_recta", "carro_jala_a_la_izquierda", "", "", "SI", "NO", "", "L1 desvío de trayectoria por arrastre.")
    agregar("G33-L1-04", CLASE_33, "L1", "Siento el auto pesado y aguantado como si anduviera con el freno puesto.", "TALLER", "rodadura", "auto_pesado_aguantado", "", "", "SI", "NO", "", "L1 resistencia mecánica al avance.")
    agregar("G33-L1-05", CLASE_33, "L1", "El pistón del caliper de freno no retrocede al liberar la presión hidráulica.", "TECNICO", "inspeccion", "piston_caliper_no_retrocede", "", "", "SI", "NO", "", "L1 reporte técnico de émbolo agarrotado.")
    agregar("G33-L1-06", CLASE_33, "L1", "Una pastilla se gastó todita en un mes y la del otro lado está nueva.", "COTIDIANO", "inspeccion_ruedas", "desgaste_pastilla_desparejo", "", "", "SI", "NO", "", "L1 desgaste asimétrico extremo.")
    agregar("G33-L1-07", CLASE_33, "L1", "Sale humo blanco y caliente del disco de freno al parar en la cochera.", "COTIDIANO", "parada", "humo_blanco_caliente_disco", "", "", "SI", "NO", "", "L1 humo por sobrecalentamiento de mordaza pegada.")
    agregar("G33-L1-08", CLASE_33, "L1", "Mi rueda delantera se calienta que pela y el carro jala para la derecha al rodar.", "ERROR_ORTOGRAFICO", "marcha", "rueda_calienta_pela|jala_derecha", "", "", "SI", "NO", "", "L1 rueda caliente y desvío con ortografía informal.")
    agregar("G33-L1-09", CLASE_33, "L1", "Buenas, al soltar el freno el carro no rueda libre en bajaditas ligeras.", "WHATSAPP", "pendiente_ligera", "carro_no_rueda_libre_en_bajada", "", "", "SI", "NO", "", "L1 falta de desahogo de frenos.")
    agregar("G33-L1-10", CLASE_33, "L1", "Fuerza de fricción residual permanente por bloqueo cinemático de pinza deslizante.", "TECNICO", "inspeccion", "friccion_residual_permanente", "", "", "SI", "NO", "", "L1 reporte técnico de arrastre de mordaza.")

    # --- L2 (15 casos) ---
    agregar("G33-L2-01", CLASE_33, "L2", "Rueda delantera derecha extremadamente caliente tras 15 minutos de recorrido; el aro de aluminio no se puede tocar con la mano y desprende olor a forro quemado.", "COTIDIANO", "post_15min_conduccion", "rueda_derecha_hirviendo|olor_forro_quemado", "desgaste_pastillas", "", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L2 rueda caliente con olor a ferodo descarta desgaste normal.")
    agregar("G33-L2-02", CLASE_33, "L2", "El vehículo tira hacia la izquierda al soltar el volante en línea recta; al levantar el auto en elevador la rueda delantera izquierda está frenada y no gira a mano.", "TALLER", "elevador_giro_manual", "tira_izquierda_linea_recta|rueda_no_gira_a_mano", "desalineacion_ruedas", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L2 rueda bloqueada a mano en elevador descarta alineación.")
    agregar("G33-L2-03", CLASE_33, "L2", "Pistón del cáliper delantero agarrotado por corrosión severa tras romperse el guardapolvo de goma; el émbolo no retrae ni con prensa hidráulica de taller.", "TECNICO", "inspeccion_caliper_desarmado", "piston_agarrotado_corrosion|guardapolvo_roto|no_retrae_prensa", "falla_bomba_frenos", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L2 émbolo oxidado clavado físicamente.")
    agregar("G33-L2-04", CLASE_33, "L2", "Hola maestro, cambié pastillas y la rueda trasera izquierda empezó a humear feo en la carretera. Los pernos de guía de la mordaza estaban secos y pegados sin grasa.", "WHATSAPP", "post_cambio_pastillas_humo", "rueda_trasera_humea_carretera|pernos_guia_pegados_secos", "falla_pastillas_nuevas", "", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L2 pernos guía secos traban mordaza flotante.")
    agregar("G33-L2-05", CLASE_33, "L2", "Desgaste en cuña y pastilla interior gastada al 100% en el soporte metálico mientras la exterior conserva 8 mm intactos; pasadores de la pinza flotante doblados.", "TECNICO", "inspeccion_desgaste_asimetrico", "pastilla_interior_al_hierro|exterior_8mm_intacta|pasadores_doblados", "desgaste_normal_pastillas", "", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L2 desgaste asimétrico 100% interior vs 8 mm exterior.")
    agregar("G33-L2-06", CLASE_33, "L2", "Consumo de gasolina aumentó 1.5 litros por cada 100 km; el auto no rueda libre en neutro y el disco delantero izquierdo adquirió color azul por temperatura.", "COTIDIANO", "consumo_elevado", "consumo_alto_1_5l|no_rueda_en_neutro|disco_azul_calor", "falla_inyectores", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L2 disco azul y resistencia al avance elevan consumo.")
    agregar("G33-L2-07", CLASE_33, "L2", "Al aflojar el tornillo purgador del cáliper atascado no sale chorro a presión y la rueda sigue frenada; se descarta manguera estrangulada y confirma pistón trabado.", "TALLER", "prueba_despresurizacion_sangrador", "rueda_sigue_frenada_aflojar_sangrador|piston_clavado_mecanico", "falla_manguera_freno", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L2 purga sin presión confirma traba mecánica del pistón.")
    agregar("G33-L2-08", CLASE_33, "L2", "Mi carro jala para la derecha feo y el aro de adelante bota un calor que no se puede ni arrimar la cara del olor a quemado.", "ERROR_ORTOGRAFICO", "marcha_calor_aro", "jala_derecha_feo|aro_bota_calor_olor_quemado", "desalineacion", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L2 jaloneo y calor abrasador con ortografía informal.")
    agregar("G33-L2-09", CLASE_33, "L2", "Buenas, el freno de mano electrónico de mi camioneta quedó clavado en la rueda derecha trasera; el motor del cáliper eléctrico zumba pero el mecanismo no suelta.", "WHATSAPP", "freno_mano_electrico_trabado", "freno_mano_electrico_clavado|motor_caliper_zumba_no_suelta", "falla_modulo_abs", "", "NO", "NO", "", "L2 cáliper EPB trabado mecánicamente en rueda trasera.")
    agregar("G33-L2-10", CLASE_33, "L2", "Manguera flexible de freno con delaminación interna que actúa como válvula check; retiene 20 bar de presión en el cáliper impidiendo el retroceso de las pastillas.", "TECNICO", "diagnostico_valvula_check_flexible", "manguera_delaminada_actua_check|retiene_20bar_caliper", "caliper_agarrotado", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L2 delaminación de flexible retiene presión en cáliper.")
    agregar("G33-L2-11", CLASE_33, "L2", "El auto se frena solo progresivamente conforme avanza en la pista; tras enfriarse 30 minutos el vehículo vuelve a rodar libre hasta que vuelve a calentar.", "COTIDIANO", "frenado_termico_progresivo", "auto_se_frena_solo_al_rodar|suelta_al_enfriarse", "falla_caja_cambios", "", "NO", "NO", "", "L2 dilatación térmica cíclica traba el émbolo.")
    agregar("G33-L2-12", CLASE_33, "L2", "Perno guía superior del cáliper gripado por utilizar grasa inadecuada con base de petróleo que hinchó los fuelles de caucho trabando el pasador.", "TALLER", "inspeccion_grasa_inadecuada", "perno_guia_gripado_grasa_petroleo|fuelles_hinchados", "falla_pastillas", "", "NO", "NO", "", "L2 incompatibilidad química de grasa traba pasadores.")
    agregar("G33-L2-13", CLASE_33, "L2", "En prueba de desaceleración libre de 80 a 0 km/h en punto muerto el vehículo recorre solo 180 metros (especificación 350 m) por resistencia de rodadura en eje delantero.", "TECNICO", "prueba_desaceleracion_libre_coastdown", "coastdown_180m_vs_350m|resistencia_rodadura_delantera", "llantas_bajas", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L2 prueba de coastdown acusa resistencia de 170 metros perdidos.")
    agregar("G33-L2-14", CLASE_33, "L2", "Disco de freno delantero derecho alabeado por sobrecalentamiento extremo continuo; se constató que la mordaza no retrocedía quemando el rotor.", "COTIDIANO", "inspeccion_taller", "disco_alabeado_sobrecalentamiento|mordaza_no_retrocede", "falla_pastillas_freno", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L2 cáliper trabado causa alabeo consecutivo en disco.")
    agregar("G33-L2-15", CLASE_33, "L2", "Fuerza residual de frenado de 380 N registrada en frenómetro en la rueda delantera izquierda sin aplicar presión sobre el pedal de freno.", "TECNICO", "frenometro_fuerza_residual", "fuerza_residual_380n_sin_pedal|arrastre_caliper", "desgaste_pastillas", "", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L2 fuerza residual de 380 N en frenómetro sin tocar pedal.")

    # --- L3 (15 casos) ---
    agregar("G33-L3-01", CLASE_33, "L3", "Vehículo ingresa con humo blanco y fuerte olor a quemado en la rueda delantera derecha tras circular 20 km en autopista. Se midió la temperatura con termómetro infrarrojo: el disco delantero derecho registra 245°C mientras que el disco izquierdo marca solo 48°C normal. Al elevar el auto en el puente la rueda derecha no gira ni aplicando 50 Nm de torque manual. Se retiró la pinza constatándose que el fuelle guardapolvo del pistón estaba desgarrado y el émbolo cromado presenta óxido y picaduras profundas de 0.3 mm que lo clavaron contra el cuerpo de hierro nodular.", "TECNICO", "termografia_pirrometro_245c_vs_48c", "disco_derecho_245c_vs_izquierdo_48c|rueda_bloqueada_50nm|piston_oxidado_picaduras_0_3mm", "falla_rodamiento_rueda", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L3 pirómetro registra 245°C vs 48°C y émbolo picado a 0.3 mm.")
    agregar("G33-L3-02", CLASE_33, "L3", "Conductor refiere desvío constante de la dirección hacia la derecha y vibración en el volante a 90 km/h. En la inspección se desmontó la mordaza delantera derecha encontrando que los dos pernos guía flotantes se quedaron completamente soldados por corrosión galvánica y falta de lubricación. La pastilla interior se desgastó por completo hasta el soporte de acero (0.0 mm) rayando el disco, mientras que la pastilla exterior se mantiene con 7.5 mm intactos, comprobando bloqueo del desplazamiento flotante.", "TALLER", "inspeccion_pernos_guia_soldados", "pernos_guia_soldados_corrosion|pastilla_interior_0mm_exterior_7_5mm|desvio_derecha", "desgaste_pastillas_y_zapatas", "", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L3 pernos guía soldados generan desgaste 0.0 mm interior vs 7.5 mm exterior.")
    agregar("G33-L3-03", CLASE_33, "L3", "Evaluación de resistencia al avance en prueba de desaceleración por inercia (Coastdown test): el auto se detiene 150 metros antes de lo normal. Se desmontó la rueda trasera derecha y se conectó manómetro en el purgador del cáliper marcando 0 bar de presión estática, descartando presión hidráulica atrapada por flexible estrangulado. Con el cáliper fuera del disco se intentó comprimir el pistón con sargento de 1 tonelada sin lograr ningún retroceso, confirmando agarrotamiento mecánico por deformación del cilindro.", "TECNICO", "prueba_manometro_0bar_sargento_1ton", "presion_0bar_descarta_flexible|sargento_1_tonelada_no_retrae|agarrotamiento_mecanico", "fuga_hidraulica_frenos", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L3 sargento de 1 tonelada no retrae pistón con 0 bar descartando flexible.")
    agregar("G33-L3-04", CLASE_33, "L3", "Falla de caliper con freno de estacionamiento electromecánico (EPB) integrado en rueda trasera izquierda de Volkswagen Tiguan. El actuador eléctrico gira pero el tornillo sinfín interno se trabó por rotura de los engranajes planetarios plásticos, dejando el pistón bloqueado en compresión continua contra el disco. La temperatura del disco alcanzó 210°C cocinando el retén de sellado y provocando encendido del testigo EPB con DTC C100D en el módulo de freno de mano.", "TECNICO", "diagnostico_epb_sinfin_roto", "dtc_c100d|sinfin_epb_trabado_engranajes_rotos|disco_210c_piston_bloqueado", "falla_modulo_abs", "C100D", "NO", "SI", "Falla en sensor de velocidad de rueda ABS", "L3 código C100D por engranajes de actuador EPB rotos con disco a 210°C.")
    agregar("G33-L3-05", CLASE_33, "L3", "Hola maestro, tengo un Sentra. Cuando manejo en pista recta el timón jala para la derecha y sale un olor a quemado insoportable de la rueda delantera. Le revisaron el disco derecho y estaba de color morado hirviendo. Desarmaron la mordaza y el pistón tenía óxido con barro pegado porque se le había roto el jebecito protector.", "WHATSAPP", "diagnostico_sentra_mordaza_oxido", "timon_jala_derecha|olor_quemado|disco_morado_hirviendo|piston_oxido_guardapolvo_roto", "llantas_desalineadas", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L3 relato WhatsApp de pistón oxidado por guardapolvo roto y disco morado.")
    agregar("G33-L3-06", CLASE_33, "L3", "Fenómeno de frenada retenida por delaminación interna de manguera flexible delantera izquierda: tras aplicar el freno con 60 bar de fuerza el pedal retorna suavemente pero la rueda izquierda permanece completamente trabada. Al abrir el purgador del caliper brota un chorro de líquido a 18 bar de presión retenida y la rueda se libera inmediatamente, demostrando efecto de válvula check por solapa interna de goma desprendida.", "TALLER", "diagnostico_valvula_check_flexible_18bar", "chorro_18bar_al_abrir_purgador|rueda_libera_al_despresurizar|solapa_goma_manguera", "caliper_agarrotado_mecanico", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L3 chorro de 18 bar al purgar confirma flexible delaminado y no pistón oxidado.")
    agregar("G33-L3-07", CLASE_33, "L3", "Inspección termográfica de caliper de 4 pistones opuestos en vehículo de alto rendimiento: pistones superiores operan normalmente pero los dos pistones inferiores del lado interior se encuentran agarrotados por acumulación de barniz de líquido de frenos recalentado y polvillo cerámico. La pastilla presenta desgaste oblicuo de 1.8 mm en zona inferior y 5.5 mm en zona superior.", "TECNICO", "inspeccion_caliper_4_pistones_opuestos", "2_pistones_inferiores_agarrotados|barniz_liquido_polvillo|desgaste_oblicuo_1_8_vs_5_5mm", "desgaste_pastillas", "", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L3 cáliper de 4 pistones con 2 inferiores agarrotados y desgaste oblicuo.")
    agregar("G33-L3-08", CLASE_33, "L3", "Mi carro se jalonea para la izquierda y la rueda delantera izquierda esta que pela de caliente con olor a ferodo. El mecanico le saco la mordaza y los pernos pasadores taban doblados y secos de grasa que no dejaban correr la pastilla de freno.", "ERROR_ORTOGRAFICO", "mordaza_pernos_doblados", "jalonea_izquierda|rueda_pela_caliente|olor_ferodo|pernos_doblados_secos", "desalineacion", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L3 pernos doblados sin grasa con ortografía informal.")
    agregar("G33-L3-09", CLASE_33, "L3", "Medición de fuerza residual en frenómetro computarizado: rueda delantera derecha marca 420 N de fricción parasitaria en vacío (especificación máxima admitida 50 N). Se desmontó el conjunto encontrándose que el sello cuadrangular de goma (square-cut seal) perdió su elasticidad de retroceso por envejecimiento térmico, impidiendo la retracción nominal de 0.15 mm del pistón al soltar el freno.", "TECNICO", "perdida_elasticidad_square_cut_seal", "fuerza_residual_420n_vs_50n|sello_cuadrangular_sin_retroceso_0_15mm", "desgaste_pastillas", "", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L3 pérdida de retracción elastomérica de 0.15 mm en sello square-cut.")
    agregar("G33-L3-10", CLASE_33, "L3", "Buenas tardes, en mi Tucson la rueda trasera derecha huele a quemado y el disco está azul oscuro. En el taller me dijeron que el caliper se quedó pegado porque la leva del freno de mano mecánico no regresa al resorte por suciedad de óxido y deja la zapata interna apretando el disco en todo momento.", "WHATSAPP", "leva_freno_mano_oxido_pegada", "rueda_trasera_huele_quemado|disco_azul_oscuro|leva_freno_mano_pegada_oxido", "desgaste_pastillas", "", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L3 leva de freno de mano trabada en cáliper trasero.")
    agregar("G33-L3-11", CLASE_33, "L3", "Análisis con pirómetro infrarrojo de precisión tras 10 km de conducción urbana moderada: rueda delantera izquierda en 195°C, rueda delantera derecha en 42°C, rueda trasera izquierda en 38°C y rueda trasera derecha en 39°C. La pinza izquierda presenta holgura radial en los bujes de teflón de los pernos guía que provocan trabamiento cruzado por torsión al soltar el pedal.", "TECNICO", "analisis_pirometrico_4_ruedas_195c", "rueda_izquierda_195c_vs_40c_otras|trabamiento_cruzado_bujes_teflon", "llantas_desbalanceadas", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L3 gradiente térmico de 195°C vs 40°C por trabamiento cruzado en bujes.")
    agregar("G33-L3-12", CLASE_33, "L3", "El cliente reclama que el vehículo no desciende por gravedad en pendientes del 5% al soltar el pedal de freno. Se constató que las láminas de acero inoxidable anti-ruido (shims) del portacaliper tenían acumulación de óxido debajo de ellas que redujo el canal de deslizamiento de las pastillas a 14.2 mm (orejeta de pastilla mide 14.8 mm), aprisionando mecánicamente la pastilla contra el disco.", "TALLER", "oxido_debajo_laminas_acero_aprieta", "auto_no_cae_en_pendiente_5|oxido_debajo_shims|pastilla_aprisionada_mecanicamente", "falla_caja_cambios", "", "NO", "NO", "", "L3 óxido bajo las láminas shims aprisiona pastillas.")
    agregar("G33-L3-13", CLASE_33, "L3", "Degradación extrema de líquido de frenos por ebullición localizada dentro del caliper delantero derecho trabado: el calor transmitido por el pistón agarrotado superó los 260°C carbonizando el líquido en la cámara de la pinza y formando una costra de brea negra que bloqueó el orificio de alimentación hidráulica.", "TECNICO", "carbonizacion_liquido_camara_caliper", "calor_supero_260c_costra_brea|piston_agarrotado|orificio_bloqueado", "fuga_hidraulica_frenos", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L3 carbonización de fluido a más de 260°C dentro de cáliper trabado.")
    agregar("G33-L3-14", CLASE_33, "L3", "Desgaste prematuro de disco ventilado delantero: espesor reducido de 24.0 mm a 20.1 mm en solo 8,000 km en la rueda derecha con alabeo de 0.18 mm originado por el roce ininterrumpido del caliper trabado; la rueda izquierda mantiene disco en 23.6 mm con 0.02 mm de salto.", "TALLER", "desgaste_prematuro_disco_20_1mm", "disco_reducido_24_a_20_1mm_8000km|alabeo_0_18mm_caliper_pegado|rueda_sana_23_6mm", "discos_alabeados", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L3 cáliper trabado reduce disco a 20.1 mm con 0.18 mm de alabeo.")
    agregar("G33-L3-15", CLASE_33, "L3", "Prueba de tracción en dinamómetro: resistencia pasiva de rodadura de 650 N en rueda delantera izquierda debida a agarrotamiento de émbolo por ingreso de barro calcáreo tras vadear río; se requirió prensa de banco de 5 toneladas para extraer el pistón del cáliper constatándose deformación por corrosión por picadura.", "TECNICO", "resistencia_dinamometro_650n_barro", "resistencia_650n_dinamometro|ingreso_barro_calcareo_vadeo|prensa_5_toneladas_extraccion", "falla_traccion_4x4", "", "NO", "NO", "", "L3 resistencia de 650 N por ingreso de barro calcáreo en émbolo.")

    return casos
