"""
Generador de registros para Lote 09 de Fase 10 (ELECTRICO) - Parte 2.
Cubre exactamente 160 registros:
- Clase 50: Fallo en inversor de corriente IGBT o motor electrico (EV) (40 casos: 10 L1, 15 L2, 15 L3)
- Clase 51: Foco o falla en sistema de refrigeracion de bateria/inversor (EV) (40 casos: 10 L1, 15 L2, 15 L3)
- Clase 52: Falla en motor de arranque o solenoide defectuoso (clac seco o carbones gastados) (40 casos: 10 L1, 15 L2, 15 L3)
- Clase 53: Fuga parasita de corriente en reposo (consumo nocturno de bateria) (40 casos: 10 L1, 15 L2, 15 L3)
IDs: F10-L09-0121 a F10-L09-0280.
"""

from typing import List, Dict

CLASE_50 = "Fallo en inversor de corriente IGBT o motor electrico (EV)"
CLASE_51 = "Foco o falla en sistema de refrigeracion de bateria/inversor (EV)"
CLASE_52 = "Falla en motor de arranque o solenoide defectuoso (clac seco o carbones gastados)"
CLASE_53 = "Fuga parasita de corriente en reposo (consumo nocturno de bateria)"

# Clases contrastivas canónicas
CLASE_21 = "Falla en sensor de posicion de cigueñal (CKP) o arbol de levas (CMP)"
CLASE_32 = "Falla en sistema de frenado regenerativo (EV / Hibridos)"
CLASE_47 = "Alternador defectuoso o placa de diodos quemada"
CLASE_48 = "Bateria descargada o bornes sulfatados"
CLASE_49 = "Degradacion o falla en paquete de bateria de alto voltaje (EV / Hibridos)"
CLASE_55 = "Falla electrica del cierre centralizado o actuador de puerta"

MACRO = "ELECTRICO"
FUENTE = "SINTETICO_IA"


def obtener_casos_50_53(offset: int = 121) -> List[Dict[str, str]]:
    casos = []
    idx = offset

    def agregar(id_grupo, clase, nivel, texto, lenguaje, condicion, presentes, negados, dtc, req_preg, es_cont, clase_cont, obs):
        nonlocal idx
        reg_id = f"F10-L09-{idx:04d}"
        casos.append({
            "id": reg_id,
            "id_grupo": id_grupo,
            "clase_objetivo": clase,
            "macro_sistema": MACRO,
            "nivel_informacion": nivel,
            "texto_usuario": texto,
            "tipo_lenguaje": lenguaje,
            "condicion_operacion": condicion,
            "sintomas_presentes": presentes,
            "sintomas_negados": negados,
            "dtc": dtc,
            "requiere_pregunta": req_preg,
            "es_contrastivo": es_cont,
            "clase_contrastiva": clase_cont,
            "fuente": FUENTE,
            "observaciones": obs
        })
        idx += 1

    # =========================================================================
    # CLASE 50: Fallo en inversor de corriente IGBT o motor electrico (EV) (40 casos: 10 L1, 15 L2, 15 L3)
    # =========================================================================
    # L1 (10 casos)
    agregar("G-09-50-01", CLASE_50, "L1", "El carro electrico perdio fuerza de golpe y no quiere acelerar.", "COLOQUIAL", "EN_MARCHA", "perdida_potencia, no_acelera", "NO_REPORTA", "", "SI", "NO", "", "L1 baja especificidad propulsion EV")
    agregar("G-09-50-02", CLASE_50, "L1", "Me sale una advertencia en el tablero del EV y se apago el motor.", "COLOQUIAL", "EN_MARCHA", "alerta_tablero, motor_apagado", "NO_REPORTA", "", "SI", "NO", "", "L1 advertencia tablero EV")
    agregar("G-09-50-03", CLASE_50, "L1", "Siento un tiron fuerte y el vehiculo electrico ya no avanza nada.", "COLOQUIAL", "EN_MARCHA", "tiron, sin_traccion", "NO_REPORTA", "", "SI", "NO", "", "L1 perdida repentina de traccion EV")
    agregar("G-09-50-04", CLASE_50, "L1", "En el tablero me prendio un triangulo amarillo con signo de exclamacion en mi auto electrico.", "COLOQUIAL", "CONTACTO", "testigo_maestro, aviso_averia", "NO_REPORTA", "", "SI", "NO", "", "L1 testigo generico EV")
    agregar("G-09-50-05", CLASE_50, "L1", "Iba manejando y de pronto se corto la traccion por completo.", "COLOQUIAL", "EN_MARCHA", "corte_traccion", "NO_REPORTA", "", "SI", "NO", "", "L1 corte de potencia en marcha EV")
    agregar("G-09-50-06", CLASE_50, "L1", "El coche electrico no responde al pedal del acelerador.", "COLOQUIAL", "EN_MARCHA", "acelerador_sin_respuesta", "NO_REPORTA", "", "SI", "NO", "", "L1 pedal sin respuesta EV")
    agregar("G-09-50-07", CLASE_50, "L1", "Aparecio un aviso de comprobar sistema hibrido y no se mueve.", "COLOQUIAL", "ARRANQUE", "aviso_sistema_hibrido, inmovil", "NO_REPORTA", "", "SI", "NO", "", "L1 aviso generico hibrido")
    agregar("G-09-50-08", CLASE_50, "L1", "Se encendio el testigo de averia del tren motriz electrico.", "TECNICO", "CONTACTO", "testigo_tren_motriz", "NO_REPORTA", "", "SI", "NO", "", "L1 indicador tren motriz EV")
    agregar("G-09-50-09", CLASE_50, "L1", "El carro electrico hace un chillido agudo al intentar avanzar y se bloquea.", "COLOQUIAL", "EN_MARCHA", "chillido_agudo, bloqueo", "NO_REPORTA", "", "SI", "NO", "", "L1 sonido anormal e inmovilidad")
    agregar("G-09-50-10", CLASE_50, "L1", "No entra la marcha en mi carro a baterias, se queda neutral.", "COLOQUIAL", "CONTACTO", "sin_traccion, selector_neutral", "NO_REPORTA", "", "SI", "NO", "", "L1 fallo de transmision electrica EV")

    # L2 (15 casos)
    agregar("G-09-50-11", CLASE_50, "L2", "Al acelerar a fondo en subida se escucho un chasquido sordo y el EV entro en modo tortuga. La bateria de traccion marca 70% de carga pero no entrega torque a las ruedas.", "TECNICO", "SUBIDA_FUERTE", "modo_tortuga, chasquido, sin_torque", "bateria_descargada", "", "NO", "SI", CLASE_49, "L2 contraste con paquete de bateria HV")
    agregar("G-09-50-12", CLASE_50, "L2", "En plena autopista sono una detonacion leve bajo el capot frontal y el auto electrico perdio propulsion de golpe, tablero indica fallo de sistema motriz con luz READY parpadeando.", "COLOQUIAL", "CARRETERA", "detonacion_leve, perdida_propulsion, ready_parpadea", "falla_mecanica_frenos", "", "NO", "NO", "", "L2 fallo subito de etapa inversora")
    agregar("G-09-50-13", CLASE_50, "L2", "El vehiculo hibrido arranca con motor termico pero al acoplar el motor generador electrico MG2 tironea violentamente y salta mensaje de error en transmision electrica.", "TECNICO", "CONMUTACION_HIBRIDA", "tirones_mg2, error_transmision_electrica", "falla_motor_combustion", "", "NO", "SI", CLASE_32, "L2 contraste con frenado regenerativo")
    agregar("G-09-50-14", CLASE_50, "L2", "Vehiculo electrico enciende accesorios de 12V y pone contacto, pero al pasar a Drive el motor electrico produce un zumbido aspero sin girar y regresa a Parking.", "TECNICO", "INTENTO_MARCHA", "zumbido_aspero, sin_rotacion, bloqueo_parking", "bateria_12v_descargada", "", "NO", "SI", CLASE_48, "L2 contraste con bateria 12V")
    agregar("G-09-50-15", CLASE_50, "L2", "En aceleraciones medias el inversor silba muy fuerte y corta la corriente a las ruedas; la temperatura de bateria esta normal pero el inversor corta por proteccion.", "TECNICO", "ACELERACION", "silbido_inversor, corte_corriente", "alta_temperatura_bateria", "", "NO", "SI", CLASE_51, "L2 contraste con refrigeracion de bateria")
    agregar("G-09-50-16", CLASE_50, "L2", "Al acelerar fuerte el auto electrico corta la potencia de tiron, arrojando codigo P0A78 en el inversor del motor principal, sin caida en voltaje de paquete de 12V.", "TECNICO", "ACELERACION_FUERTE", "corte_potencia, codigo_inversor", "falla_bateria_12v", "P0A78", "NO", "NO", "", "L2 codigo P0A78 en inversor")
    agregar("G-09-50-17", CLASE_50, "L2", "El utilitario electrico no tracciona marcha atras ni adelante; el escaner detecta codigo P0A94 relacionado al convertidor DC/DC e inversor de traccion.", "TECNICO", "CONTACTO", "sin_traccion_adelante_atras, codigo_p0a94", "rueda_bloqueada", "P0A94", "NO", "NO", "", "L2 fallo convertidor e inversor P0A94")
    agregar("G-09-50-18", CLASE_50, "L2", "El motor electrico de traccion produce una vibracion pesada y olor a barniz caliente en la zona del tren delantero al intentar avanzar a baja velocidad.", "TECNICO", "BAJA_VELOCIDAD", "vibracion_pesada, olor_barniz_quemado", "olor_combustible", "", "NO", "NO", "", "L2 indicio de devanado recalentado")
    agregar("G-09-50-19", CLASE_50, "L2", "El tablero muestra fallo de traccion electrica y limita velocidad a 25 km/h. La bateria HV tiene carga optima y el refrigerante esta a nivel, apuntando a dano de potencia interna.", "TECNICO", "MARCHA_URBANA", "modo_reducido_25kmh, falla_traccion", "bajo_nivel_refrigerante, bateria_agotada", "", "NO", "SI", CLASE_51, "L2 contraste con refrigeracion")
    agregar("G-09-50-20", CLASE_50, "L2", "Se corto la propulsion en seco en plena marcha urbana; la bateria de alto voltaje marca 360 voltios estables pero las fases U, V, W del motor no reciben senal.", "TECNICO", "MARCHA_URBANA", "corte_propulsion, tension_bateria_normal, sin_salida_fases", "falla_bateria_hv", "", "NO", "SI", CLASE_49, "L2 contraste con bateria HV")
    agregar("G-09-50-21", CLASE_50, "L2", "Auto 100% electrico bloqueado en modo tortuga permanente con DTC P0A1B en el modulo de control del motor de accionamiento, acelerador electronico sin respuesta motriz.", "TECNICO", "CONTACTO", "modo_tortuga_permanente, dtc_p0a1b", "falla_pedal_acelerador", "P0A1B", "NO", "NO", "", "L2 modulo control motor P0A1B")
    agregar("G-09-50-22", CLASE_50, "L2", "El furgon electrico enciende el testigo READY pero al pisar el pedal de marcha tiembla y desconecta el contactor principal por cortocircuito en el inversor.", "TECNICO", "SALIDA_DESDE_CERO", "temblor_al_pisar, desconexion_contactor", "falla_arranque_termico", "", "NO", "NO", "", "L2 desconexion contactores por corto")
    agregar("G-09-50-23", CLASE_50, "L2", "Presenta codigo P0A79 en escaner automotriz tras apagarse en marcha, indicando bajo rendimiento en inversor del motor B, baterias de 12V y traccion con carga correcta.", "TECNICO", "EN_MARCHA", "dtc_p0a79, apagado_en_marcha", "descarga_bateria_12v, descarga_bateria_hv", "P0A79", "NO", "SI", CLASE_49, "L2 contraste con baterias")
    agregar("G-09-50-24", CLASE_50, "L2", "Al exigir recuperacion de energia o acelerar fuerte en carretera se enciende alerta de alta tension en inversor, sin problemas mecanicos en calipers o frenos.", "TECNICO", "CARRETERA_REGENERACION", "alerta_alta_tension_inversor", "freno_mecanico_danado", "", "NO", "SI", CLASE_32, "L2 contraste con frenado regenerativo")
    agregar("G-09-50-25", CLASE_50, "L2", "Hibrido enchufable no conmuta a modo EV puro; al forzarlo arroja advertencia de fallo en motor electrico de propulsion, manteniendo funcionamiento exclusivo a gasolina.", "TECNICO", "CAMBIO_MODO_EV", "modo_ev_inhabilitado, falla_motor_electrico", "falla_motor_gasolina", "", "NO", "NO", "", "L2 imposibilidad modo electrico puro")

    # L3 (15 casos)
    agregar("G-09-50-26", CLASE_50, "L3", "Inspeccion tecnica en taller EV: medicion de aislamiento con megohmetro a 500V DC entre devanados de fase del motor electrico y chasis registra 0.15 Megaohmios, valor inferior a norma OEM (minimo 2 Megaohmios). Cortocircuito a masa en estator con DTC P0AA6.", "TECNICO", "TALLER_BANCO", "aislamiento_0_15_mohm, corto_a_masa, dtc_p0aa6", "falla_aislamiento_bateria", "P0AA6", "NO", "SI", CLASE_49, "L3 aislamiento estator a masa P0AA6")
    agregar("G-09-50-27", CLASE_50, "L3", "Diagnostico en banco de potencia de inversor: modulo IGBT de fase V con transistores en cortocircuito franco. Al aplicar 380V DC de bus, la corriente de reposo se dispara a 42A sin pulso PWM disparando proteccion de sobrecorriente P0A78.", "TECNICO", "TALLER_BANCO", "igbt_fase_v_en_corto, sobrecorriente_42a, dtc_p0a78", "falla_bateria_hv", "P0A78", "NO", "NO", "", "L3 modulo IGBT en cortocircuito")
    agregar("G-09-50-28", CLASE_50, "L3", "Analisis con osciloscopio en lineas de compuerta Gate de transistores IGBT: fase U carece de modulacion PWM de 10 kHz proveniente del driver de disparo. El motor sincrono de imanes permanentes se queda trabado sin rotacion trifasica simetrica.", "TECNICO", "TALLER_OSCILOSCOPIO", "sin_modulacion_pwm_fase_u, motor_trabado", "falla_mecanica_transmision", "", "NO", "NO", "", "L3 osciloscopio driver compuerta IGBT")
    agregar("G-09-50-29", CLASE_50, "L3", "Medicion con pinza amperimetrica de efecto Hall en cables trifasicos de traccion: Fase U registra 62A pico, Fase V registra 0A y Fase W registra 59A bajo demanda de torque en banco. Desequilibrio de fase severo por modulo inversor abierto, DTC P0A79.", "TECNICO", "TALLER_BANCO", "desequilibrio_fase_u_62a_v_0a_w_59a, dtc_p0a79", "falla_bateria", "P0A79", "NO", "NO", "", "L3 desbalance trifasico pinza Hall")
    agregar("G-09-50-30", CLASE_50, "L3", "Prueba de aislamiento en laboratorio de alta tension: ensayo de hipot a 1000V DC en motor de traccion arroja fuga de corriente de 12 mA a tierra por degradacion de aislacion en cabezal de bobinado, impidiendo cierre de contactores SMR con codigo P0AA6.", "TECNICO", "TALLER_HIPOT", "fuga_12ma_1000vdc, dtc_p0aa6, bloqueo_smr", "falla_celdas_bateria", "P0AA6", "NO", "SI", CLASE_49, "L3 hipot test motor traccion P0AA6")
    agregar("G-09-50-31", CLASE_50, "L3", "Monitoreo de datos en vivo de unidad de control de traccion (MCU): sensor de temperatura de modulo de potencia IGBT marca 138°C en reposo frio (sensor en corto interno), forzando parada de emergencia del convertidor DC/AC con codigo P0A94 registrado.", "TECNICO", "TALLER_SCANNER", "temperatura_ficticia_138c, sensor_igbt_corto, dtc_p0a94", "sobrecalentamiento_real_refrigerante", "P0A94", "NO", "SI", CLASE_51, "L3 sensor temp IGBT en corto vs refrigeracion")
    agregar("G-09-50-32", CLASE_50, "L3", "Verificacion de resistencia de devanados con microohmetro en motor de iman permanente: Fase U-V 0.042 Ohm, V-W 0.041 Ohm, W-U 0.043 Ohm dentro de tolerancia, pero prueba con generador de senal de resolver arroja desfase angular de 45 grados por resolver defectuoso.", "TECNICO", "TALLER_BANCO", "resistencia_fases_balanceada, error_resolver_45_grados", "falla_bobinado", "", "NO", "NO", "", "L3 microohmetro devanados y sensor resolver")
    agregar("G-09-50-33", CLASE_50, "L3", "El vehiculo electrico presenta bloqueo motriz; medicion en bus DC de entrada a inversor marca 395V estables desde bateria HV, pero tension eficaz AC de salida en bornes de motor es 0V RMS al comandar acelerador, confirmando destruccion de etapa inversora.", "TECNICO", "TALLER_MEDICION", "bus_dc_395v_ok, salida_ac_0v_rms, inversor_destruido", "bateria_hv_descargada", "", "NO", "SI", CLASE_49, "L3 tension bus DC vs salida AC inversor")
    agregar("G-09-50-34", CLASE_50, "L3", "Lectura con escaner de fabrica en bus de traccion: DTC P0A78 presente, freeze frame indica temperatura de disipador de inversor a 125°C con corriente de fase pico de 280A justo antes del bloqueo de conmutacion de potencia en el convertidor elevador boost.", "TECNICO", "TALLER_SCANNER", "dtc_p0a78, freeze_frame_125c_280a, bloqueo_boost", "falla_bomba_refrigerante", "P0A78", "NO", "SI", CLASE_51, "L3 freeze frame sobrecorriente inversor")
    agregar("G-09-50-35", CLASE_50, "L3", "Prueba con miliohmetro Kelvin de cuatro hilos en bornes de estator del motor EV: medicion de resistencia balanceada a 38 miliohmios por fase, sin embargo prueba de descarga inductiva revela cortocircuito entre espiras en fase W, generando zumbido magnetico asimetrico.", "TECNICO", "TALLER_BANCO", "resistencia_38mohm, corto_entre_espiras_fase_w", "desbalance_de_celdas", "", "NO", "NO", "", "L3 miliohmetro Kelvin y corto entre espiras")
    agregar("G-09-50-36", CLASE_50, "L3", "Diagnostico de sistema motriz EV: bateria de alto voltaje presenta 94% de SOH y 375V DC sin anomalias en celdas, pero al cerrar SMR se registra caida de bus DC a 40V por corto en capacitor de enlace DC link de 800 uF en interior de modulo inversor.", "TECNICO", "TALLER_BANCO", "bateria_94_soh_375v, corto_capacitor_dc_link_800uf", "falla_paquete_bateria", "", "NO", "SI", CLASE_49, "L3 corto en DC link capacitor de inversor")
    agregar("G-09-50-37", CLASE_50, "L3", "Lectura de parametros de MCU en banco dinamometrico: senal PWM de excitacion a compuertas de potencia presenta tiempo de subida distorsionado superior a 800 nanosegundos en modulo IGBT superior de fase W, generando saturacion termica y proteccion de sobrecorriente.", "TECNICO", "TALLER_BANCO", "tiempo_subida_pwm_800ns, saturacion_igbt_fase_w", "refrigeracion_obstruida", "", "NO", "NO", "", "L3 tiempo de subida y conmutacion IGBT")
    agregar("G-09-50-38", CLASE_50, "L3", "Comprobacion tecnica en taller certificado: se mide resistencia de aislamiento con megohmetro entre carcasa de motor electrico y devanado de traccion obteniendo 0.28 Megaohmios a 500V. DTC P0AA6 y P0A1B activos, requiriendo reemplazo o rebobinado del motor.", "TECNICO", "TALLER_MEGOHMETRO", "aislamiento_0_28_mohm_500v, dtc_p0aa6, dtc_p0a1b", "falla_aislamiento_cableado_12v", "P0AA6, P0A1B", "NO", "NO", "", "L3 megohmetro motor traccion P0AA6 P0A1B")
    agregar("G-09-50-39", CLASE_50, "L3", "Analisis de fallas en convertidor de traccion: transistores SiC MOSFET del inversor registran resistencia inversa de 0.8 Ohm entre drenador y fuente, confirmando perforacion dielectrica por sobretension transitoria en desaceleracion regenerativa brusca.", "TECNICO", "TALLER_BANCO", "perforacion_dielectrica_sic_mosfet, resistencia_0_8_ohm", "falla_calipers_freno", "", "NO", "SI", CLASE_32, "L3 ruptura de transistores SiC en frenado")
    agregar("G-09-50-40", CLASE_50, "L3", "Evaluacion de etapa de potencia de vehiculo hibrido: circuito inversor de MG2 presenta diodo de retorno antiparalelo quemado en circuito abierto; al solicitar traccion electrica se genera arco interno en modulo de potencia y activacion inmediata de interlock.", "TECNICO", "TALLER_BANCO", "diodo_antiparalelo_abierto, disparo_interlock", "falla_motor_combustion", "", "NO", "NO", "", "L3 diodo de libre circulacion abierto")

    # =========================================================================
    # CLASE 51: Foco o falla en sistema de refrigeracion de bateria/inversor (EV) (40 casos: 10 L1, 15 L2, 15 L3)
    # =========================================================================
    # L1 (10 casos)
    agregar("G-09-51-01", CLASE_51, "L1", "El ventilador del carro hibrido suena fuertisimo atras todo el tiempo.", "COLOQUIAL", "EN_MARCHA", "ventilador_ruidoso, zumbido_trasero", "NO_REPORTA", "", "SI", "NO", "", "L1 ventilador ruidoso hibrido")
    agregar("G-09-51-02", CLASE_51, "L1", "Se prendio un foco de temperatura en mi carro hibrido y pierde fuerza.", "COLOQUIAL", "EN_MARCHA", "foco_temperatura, perdida_fuerza", "NO_REPORTA", "", "SI", "NO", "", "L1 foco temperatura hibrido")
    agregar("G-09-51-03", CLASE_51, "L1", "Me salio una alerta de sobrecalentamiento del sistema electrico.", "COLOQUIAL", "EN_MARCHA", "alerta_sobrecalentamiento", "NO_REPORTA", "", "SI", "NO", "", "L1 sobrecalentamiento generico EV")
    agregar("G-09-51-04", CLASE_51, "L1", "El auto electrico no quiere cargar rapido porque dice que esta caliente.", "COLOQUIAL", "CARGA_DETENIDO", "carga_rechazada, temperatura_alta", "NO_REPORTA", "", "SI", "NO", "", "L1 temperatura en carga EV")
    agregar("G-09-51-05", CLASE_51, "L1", "Siento que el ventilador de la bateria no se apaga nunca.", "COLOQUIAL", "CONTACTO", "ventilador_continuo", "NO_REPORTA", "", "SI", "NO", "", "L1 ventilador encendido permanente")
    agregar("G-09-51-06", CLASE_51, "L1", "Aparece un mensaje de revisar refrigeracion en el tablero del EV.", "COLOQUIAL", "CONTACTO", "aviso_revisar_refrigeracion", "NO_REPORTA", "", "SI", "NO", "", "L1 mensaje aviso refrigeracion EV")
    agregar("G-09-51-07", CLASE_51, "L1", "El carro electrico huele a caliente por la zona delantera y baja la potencia.", "COLOQUIAL", "EN_MARCHA", "olor_caliente, reduccion_potencia", "NO_REPORTA", "", "SI", "NO", "", "L1 olor calor y corte potencia")
    agregar("G-09-51-08", CLASE_51, "L1", "Se escucha un zumbido forzado de soplador bajo los asientos traseros.", "COLOQUIAL", "EN_MARCHA", "zumbido_soplador, ruido_trasero", "NO_REPORTA", "", "SI", "NO", "", "L1 soplador trasero forzado")
    agregar("G-09-51-09", CLASE_51, "L1", "En el tablero me marca aviso de temperatura alta en bateria de traccion.", "TECNICO", "CONTACTO", "temperatura_alta_bateria", "NO_REPORTA", "", "SI", "NO", "", "L1 aviso temperatura bateria")
    agregar("G-09-51-10", CLASE_51, "L1", "El liquido de enfriamiento del sistema electrico esta hirviendo.", "COLOQUIAL", "DETENIDO_RALENTI", "liquido_hirviendo, burbujeo", "NO_REPORTA", "", "SI", "NO", "", "L1 ebullicion refrigerante electrico")

    # L2 (15 casos)
    agregar("G-09-51-11", CLASE_51, "L2", "En vehiculo hibrido con refrigeracion por aire en paquete de bateria NiMH, la turbina de enfriamiento trasera funciona a maxima velocidad constante y el tablero advierte reduccion de potencia tras circular 20 minutos en calor.", "TECNICO", "MARCHA_URBANA_CALOR", "turbina_maxima_velocidad, reduccion_potencia_hibrido", "degradacion_celdas_quimica", "", "NO", "SI", CLASE_49, "L2 refrigeracion aire vs fallo celdas")
    agregar("G-09-51-12", CLASE_51, "L2", "Al circular por autopista en dia caluroso el vehiculo electrico reduce potencia a la mitad; el deposito de refrigerante del circuito del inversor no muestra turbulencia ni flujo circulante.", "TECNICO", "CARRETERA_CALOR", "deposito_sin_flujo, reduccion_potencia", "dano_igbt_inversor", "", "NO", "SI", CLASE_50, "L2 falta de flujo refrigerante vs fallo IGBT")
    agregar("G-09-51-13", CLASE_51, "L2", "Aparece testigo de falla en sistema hibrido con codigo P0A93 en escaner; el circuito de enfriamiento del inversor no mueve liquido y el deposito auxiliar se calienta en exceso.", "TECNICO", "MARCHA_URBANA", "dtc_p0a93, sin_flujo_refrigerante_inversor", "falla_motor_combustion", "P0A93", "NO", "NO", "", "L2 DTC P0A93 bomba inversor")
    agregar("G-09-51-14", CLASE_51, "L2", "La rejilla de toma de aire del ventilador de bateria de traccion bajo el asiento trasero estaba tapada con polvo y pelos de mascota; el ventilador vibra atorado y salta alerta termica.", "COLOQUIAL", "EN_MARCHA", "rejilla_tapada_polvo, ventilador_atorado, alerta_termica", "dano_modulo_bateria", "", "NO", "SI", CLASE_49, "L2 obstruccion aire vs dano quimico")
    agregar("G-09-51-15", CLASE_51, "L2", "En subidas prolongadas el inversor se sobrecalienta y enciende foco de temperatura; la bomba electrica de refrigerante de la unidad de control de potencia no se activa.", "TECNICO", "SUBIDA_PROLONGADA", "sobrecalentamiento_inversor, bomba_electrica_inoperante", "falla_motor_traccion", "", "NO", "SI", CLASE_50, "L2 bomba inoperante vs fallo motor EV")
    agregar("G-09-51-16", CLASE_51, "L2", "El escaner arroja codigo P0A82 indicando problema de rendimiento en ventilador de enfriamiento 1 del paquete de bateria hibrida, operando de forma intermitente.", "TECNICO", "CONTACTO", "dtc_p0a82, ventilador_bateria_intermitente", "desbalance_de_celdas", "P0A82", "NO", "NO", "", "L2 DTC P0A82 ventilador paquete")
    agregar("G-09-51-17", CLASE_51, "L2", "Vehiculo 100% electrico cancela la recarga rapida en corriente continua DC a los 10 minutos debido a que el circuito chiller de refrigeracion liquida de bateria no logra abatir la temperatura.", "TECNICO", "CARGA_RAPIDA_DC", "carga_dc_cancelada, sobretemperatura_bateria, chiller_inoperante", "falla_estacion_carga", "", "NO", "SI", CLASE_49, "L2 enfriamiento carga DC vs estado bateria")
    agregar("G-09-51-18", CLASE_51, "L2", "El deposito de refrigerante rosado exclusivo del inversor de potencia esta vacio por fuga en abrazadera inferior; se enciende aviso de parada segura por alta temperatura de electronica.", "TECNICO", "DETENIDO_REVISION", "deposito_vacio_fuga, aviso_parada_segura", "falla_refrigerante_motor_termico", "", "NO", "NO", "", "L2 fuga de refrigerante de inversor")
    agregar("G-09-51-19", CLASE_51, "L2", "Durante el frenado regenerativo intenso en descenso de montana la temperatura del inversor se dispara a zona roja por falta de enfriamiento en el radiador auxiliar.", "TECNICO", "DESCENSO_MONTANA", "alta_temperatura_inversor, radiador_auxiliar_inoperante", "desgaste_pastillas_freno", "", "NO", "SI", CLASE_32, "L2 enfriamiento vs frenos regenerativos")
    agregar("G-09-51-20", CLASE_51, "L2", "El ventilador soplador centrifugo de la bateria de alto voltaje hace ruido de roce mecanico con sus aspas y no entrega caudal de aire suficiente hacia los modulos centrales.", "TECNICO", "EN_MARCHA", "roce_mecanico_aspas, bajo_caudal_aire", "falla_quimica_bateria", "", "NO", "NO", "", "L2 soplador centrifugo con roce")
    agregar("G-09-51-21", CLASE_51, "L2", "Se registra codigo P0A93 tras conducir 15 minutos en ciudad; el motor electrico y la transmision operan normalmente pero el inversor alcanza el limite termico por bomba trabada.", "TECNICO", "MARCHA_URBANA", "dtc_p0a93, limite_termico_inversor, bomba_trabada", "dano_igbt_interno", "P0A93", "NO", "SI", CLASE_50, "L2 P0A93 bomba trabada vs dano IGBT")
    agregar("G-09-51-22", CLASE_51, "L2", "El sistema termico del paquete de bateria de litio no activa la valvula de tres vias del circuito refrigerante, reteniendo calor en el nucleo central de celdas.", "TECNICO", "CARRETERA", "valvula_3_vias_trabada, retencion_calor_celdas", "falla_modulo_bms", "", "NO", "NO", "", "L2 electrovalvula termica de bateria")
    agregar("G-09-51-23", CLASE_51, "L2", "Auto hibrido desactiva el modo electrico y enciende testigo maestro; el sensor de temperatura en la entrada del ducto de aire de la bateria marca 48°C con flujo de aire bloqueado.", "TECNICO", "EN_MARCHA", "modo_electrico_desactivado, ducto_bloqueado, 48c", "bateria_agotada", "", "NO", "SI", CLASE_49, "L2 flujo aire bloqueado vs bateria agotada")
    agregar("G-09-51-24", CLASE_51, "L2", "Bomba electrica de agua de 12V dedicada al enfriamiento del inversor y convertidor boost emite chillido intermitente y se detiene repentinamente al calentarse.", "TECNICO", "RALENTI_CONTACTO", "chillido_bomba_inversor, detencion_termica", "bomba_agua_motor_termico", "", "NO", "NO", "", "L2 bomba 12V enfriamiento inversor")
    agregar("G-09-51-25", CLASE_51, "L2", "El paquete de bateria HV retiene 85% de capacidad util pero en dias calurosos el sistema recorta el paso de corriente debido a falta de disipacion en su circuito termico.", "TECNICO", "CALOR_AMBIENTE", "recorte_corriente_calor, disipacion_deficiente", "degradacion_soh_bateria", "", "NO", "SI", CLASE_49, "L2 disipacion deficiente vs degradacion SOH")

    # L3 (15 casos)
    agregar("G-09-51-26", CLASE_51, "L3", "Diagnostico de sistema termico en taller especializado: escaneo OBD arroja DTC P0A93 (Inverter Cooling System Performance). Con ignicion en ON, la bomba de refrigerante del inversor consume 0.0A por circuito abierto en inducido; temperatura de refrigerante de inversor alcanza 88°C con motor termico frio a 35°C.", "TECNICO", "TALLER_MEDICION", "dtc_p0a93, bomba_0_0a_abierta, temp_inversor_88c", "falla_termostato_motor_combustion", "P0A93", "NO", "SI", CLASE_50, "L3 bomba inversor abierta P0A93 temp 88C")
    agregar("G-09-51-27", CLASE_51, "L3", "Monitoreo de datos en vivo de BMS en vehiculo hibrido refrigerado por aire: termistores de modulo central marcan 56°C (umbral maximo seguro 45°C). Comando de activacion de ventilador al 100% de PWM desde escaner registra turbina girando a solo 620 RPM por obstruccion severa de pelusa en ducto de admision, generando DTC P0A82.", "TECNICO", "TALLER_SCANNER", "termistores_56c, ventilador_620rpm_obstruido, dtc_p0a82", "degradacion_irreversible_bateria", "P0A82", "NO", "SI", CLASE_49, "L3 termistores 56C ventilador 620RPM P0A82")
    agregar("G-09-51-28", CLASE_51, "L3", "Evaluacion de circuito de enfriamiento de inversor: comprobacion de flujo en deposito de expansion revela ausencia total de turbulencia. Medicion de alimentacion en conector de bomba electrica: 12.4V presentes y masa a chasis 0.02 Ohm; rotor de bomba trabado mecanicamente por impurezas en refrigerante OEM.", "TECNICO", "TALLER_COMPROBACION", "alimentacion_12_4v_ok, rotor_bomba_trabado, sin_turbulencia", "falla_cableado_alimentacion", "", "NO", "NO", "", "L3 bomba inversor trabada con 12.4V")
    agregar("G-09-51-29", CLASE_51, "L3", "Prueba de circuito termico de bateria de traccion en EV con refrigeracion liquida: sensor de temperatura de entrada de refrigerante registra 28°C y salida a 52°C. Caudalimetro de lazo termico mide 1.1 L/min frente al valor nominal de 8.5 L/min debido a bloqueo en electrovalvula proporcional de distribucion a celdas.", "TECNICO", "TALLER_MEDICION", "caudal_1_1_l_min_bloqueado, salto_termico_24c, electrovalvula_trabada", "falla_quimica_celdas", "", "NO", "SI", CLASE_49, "L3 caudal 1.1 L/min vs 8.5 nominal electrovalvula")
    agregar("G-09-51-30", CLASE_51, "L3", "Lectura de parametros en tiempo real durante prueba de ruta: la temperatura de semiconductores IGBT escala de 42°C a 115°C en 90 segundos al acelerar a 80 km/h; conector de retorno de refrigerante frio al tacto, confirmando aire entrampado o purga deficiente en circuito secundario con DTC P0A93.", "TECNICO", "PRUEBA_RUTA", "temperatura_igbt_115c_90s, aire_en_circuito, dtc_p0a93", "dano_modulo_igbt", "P0A93", "NO", "SI", CLASE_50, "L3 purga deficiente temp 115C P0A93")
    agregar("G-09-51-31", CLASE_51, "L3", "Inspeccion con camara termografica en bahia de bateria de alto voltaje: gradiente termico de 22°C entre modulos extremos (32°C) y centrales (54°C). El ducto de escape de aire forzado presenta compuerta de alivio trabada en posicion cerrada, impidiendo ventilacion convectiva.", "TECNICO", "TALLER_TERMOGRAFIA", "gradiente_termico_22c, compuerta_alivio_trabada, modulos_54c", "desbalance_interno_celdas", "", "NO", "SI", CLASE_49, "L3 termografia gradiente 22C compuerta cerrada")
    agregar("G-09-51-32", CLASE_51, "L3", "Auditoria electrica en conector de soplador de refrigeracion de bateria HV: senal de control PWM de 250 Hz presente con ciclo de trabajo de 85%, pero linea de retorno de tacometro (sensor Hall) permanece en 0 Hz; motor sin escobillas del soplador con bobinado de estator quemado, DTC P0A82.", "TECNICO", "TALLER_OSCILOSCOPIO", "pwm_85_ok, tacometro_0hz, estator_soplador_quemado, dtc_p0a82", "falla_controlador_bms", "P0A82", "NO", "NO", "", "L3 soplador PWM 85% tacometro 0Hz P0A82")
    agregar("G-09-51-33", CLASE_51, "L3", "Prueba de banco de bomba de refrigeracion de modulo de traccion electrica: al aplicar 12V directos la bomba consume corriente anormal de 6.8A (nominal 1.5A-2.2A) produciendo recalentamiento de devanado y disparo del fusible de proteccion de 15A tras 10 segundos de marcha.", "TECNICO", "TALLER_BANCO", "consumo_anormal_6_8a, fusible_15a_quemado, devanado_recalentado", "cortocircuito_en_arnes", "", "NO", "NO", "", "L3 sobreconsumo bomba inversor 6.8A")
    agregar("G-09-51-34", CLASE_51, "L3", "Evaluacion en estacion de carga rapida DC (50 kW): la sesion se interrumpe al llegar a 38% de SOC con codigo de error de sobretemperatura en paquete. Temperatura interna de pack medida por BMS a 58°C por falla en compresor electrico del circuito chiller de refrigeracion liquida.", "TECNICO", "ESTACION_CARGA", "interrupcion_38_soc, pack_58c, falla_compresor_chiller", "falla_quimica_pack", "", "NO", "SI", CLASE_49, "L3 corte carga rapida pack 58C chiller")
    agregar("G-09-51-35", CLASE_51, "L3", "Diagnostico con escaner automotriz en bus hibrido: DTC P0A93 confirmado en historial de fallas; parametros congelados registran temperatura de inversor a 108°C a 2100 RPM con radiador de inversor completamente frio por descebado de bomba y cavitacion en circuito cerrado.", "TECNICO", "TALLER_SCANNER", "dtc_p0a93, temp_108c_freeze_frame, cavitacion_bomba", "falla_propulsion_motor", "P0A93", "NO", "SI", CLASE_50, "L3 P0A93 cavitacion y radiador frio")
    agregar("G-09-51-36", CLASE_51, "L3", "Medicion con multimetro automotriz en sensor de temperatura de refrigerante de inversor (termistor NTC): resistencia medida a 20°C ambiente es 185 kiloohmios (valor fuera de rango segun manual OEM: 2.2 a 2.7 kiloohmios), enviando senal erronea de congelamiento e impidiendo arranque de bomba.", "TECNICO", "TALLER_MULTIMETRO", "sensor_ntc_185_kohm_descalibrado, lectura_falsa_frio", "falla_mecanica_bomba", "", "NO", "NO", "", "L3 sensor NTC inversor descalibrado 185k")
    agregar("G-09-51-37", CLASE_51, "L3", "Analisis de telemetria termica de pack de litio: la resistencia interna de las celdas esta pareja a 1.2 miliohmios (bateria en optimo estado quimico), pero ante demanda continua de 120A la temperatura sube sin disiparse a razon de 1.8°C/min por radiador de refrigeracion auxiliar obstruido con insectos.", "TECNICO", "PRUEBA_DINAMOMETRICA", "resistencia_1_2mohm_ok, subida_1_8c_min, radiador_auxiliar_tapado", "degradacion_celdas", "", "NO", "SI", CLASE_49, "L3 celdas 1.2 mOhm ok disipacion tapada")
    agregar("G-09-51-38", CLASE_51, "L3", "Verificacion de funcionamiento de electroventilador de radiador de inversor: actuador no responde a test bidireccional desde escaner. Rele de control RLY_INV_FAN con contactos carbonizados presenta caida de tension interna de 8.2V entre terminal 30 y 87.", "TECNICO", "TALLER_BIDIRECCIONAL", "test_bidireccional_falla, caida_8_2v_contactos_rele", "motor_ventilador_quemado", "", "NO", "NO", "", "L3 rele electroventilador con caida 8.2V")
    agregar("G-09-51-39", CLASE_51, "L3", "Prueba de hermeticidad y presion con manometro en circuito de refrigerante de alta tension: presion cae de 1.2 bar a 0.2 bar en 3 minutos. Se localiza fisura en manguera de retorno de placa disipadora del inversor de corriente, con acumulacion de liquido desionizado en bandeja inferior.", "TECNICO", "TALLER_PRESION", "perdida_presion_1_2_a_0_2bar, fisura_manguera_retorno", "fuga_aceite_transmision", "", "NO", "NO", "", "L3 prueba presion circuito desionizado")
    agregar("G-09-51-40", CLASE_51, "L3", "Control de soplador centrifugo de bateria NiMH: desmontaje de turbina revela 140 gramos de pelusa compactada entre los alabes; con canal despejado el consumo electrico del motor baja de 4.1A a 1.6A y la temperatura de celdas disminuye de 52°C a 34°C en 8 minutos de marcha urbana.", "TECNICO", "TALLER_MANTENIMIENTO", "pelusa_compactada_turbina, consumo_baja_4_1_a_1_6a, delta_temp_18c", "falla_pack_baterias", "", "NO", "SI", CLASE_49, "L3 mantenimiento turbina soplador NiMH")

    # =========================================================================
    # CLASE 52: Falla en motor de arranque o solenoide defectuoso (clac seco o carbones gastados) (40 casos: 10 L1, 15 L2, 15 L3)
    # =========================================================================
    # L1 (10 casos)
    agregar("G-09-52-01", CLASE_52, "L1", "Giro la llave para encender el auto y no hace nada de nada.", "COLOQUIAL", "INTENTO_ARRANQUE", "sin_arranque, silencio_total", "NO_REPORTA", "", "SI", "NO", "", "L1 no hace nada al dar llave")
    agregar("G-09-52-02", CLASE_52, "L1", "Le doy marcha y solo se escucha un clac seco debajo del motor.", "COLOQUIAL", "INTENTO_ARRANQUE", "clac_seco, no_gira", "NO_REPORTA", "", "SI", "NO", "", "L1 clac seco bajo el motor")
    agregar("G-09-52-03", CLASE_52, "L1", "El carro no quiere dar arranque hoy en la manana.", "COLOQUIAL", "ARRANQUE_FRIO", "no_da_arranque", "NO_REPORTA", "", "SI", "NO", "", "L1 no da arranque en la manana")
    agregar("G-09-52-04", CLASE_52, "L1", "Pongo la llave en posicion de arranque y el motor ni se entera.", "COLOQUIAL", "INTENTO_ARRANQUE", "sin_giro_motor", "NO_REPORTA", "", "SI", "NO", "", "L1 motor no responde a llave")
    agregar("G-09-52-05", CLASE_52, "L1", "A veces enciende a la primera y a veces le doy a la llave diez veces hasta que arranca.", "COLOQUIAL", "INTENTO_ARRANQUE", "arranque_intermitente, multiples_intentos", "NO_REPORTA", "", "SI", "NO", "", "L1 intermitencia en llavazos")
    agregar("G-09-52-06", CLASE_52, "L1", "Presiono el boton de encendido y no gira el motor.", "COLOQUIAL", "INTENTO_ARRANQUE", "no_gira_motor, pulsador_start", "NO_REPORTA", "", "SI", "NO", "", "L1 boton start no gira motor")
    agregar("G-09-52-07", CLASE_52, "L1", "Se escucha un golpe metalico unico al intentar prenderlo pero no gira.", "COLOQUIAL", "INTENTO_ARRANQUE", "golpe_metalico_unico, sin_giro", "NO_REPORTA", "", "SI", "NO", "", "L1 golpe metalico unico")
    agregar("G-09-52-08", CLASE_52, "L1", "El motor de mi camioneta no hace ningun intento por girar.", "COLOQUIAL", "INTENTO_ARRANQUE", "sin_intento_giro", "NO_REPORTA", "", "SI", "NO", "", "L1 sin intento de rotacion")
    agregar("G-09-52-09", CLASE_52, "L1", "Le doy encendido, suena un clic y todo queda en silencio.", "COLOQUIAL", "INTENTO_ARRANQUE", "clic_solenoide, silencio", "NO_REPORTA", "", "SI", "NO", "", "L1 clic y silencio")
    agregar("G-09-52-10", CLASE_52, "L1", "Para que prenda tengo que darle varios llavazos seguidos.", "COLOQUIAL", "INTENTO_ARRANQUE", "insistencia_llave, arranque_dificil", "NO_REPORTA", "", "SI", "NO", "", "L1 insistencia de varios llavazos")

    # L2 (15 casos)
    agregar("G-09-52-11", CLASE_52, "L2", "Pongo contacto, las luces del tablero encienden con buen brillo, pero al girar la llave a start solo se escucha un clac metalico seco y el ciguenal no gira absolutamente nada.", "COLOQUIAL", "INTENTO_ARRANQUE", "clac_metalico_seco, luces_tablero_brillantes, no_crank", "luces_tenues, traqueteo_bateria", "", "NO", "SI", CLASE_48, "L2 no-crank con luces buenas vs bateria")
    agregar("G-09-52-12", CLASE_52, "L2", "El motor no gira en lo absoluto (no-crank); no es que gire rapido y no encienda como cuando falla el sensor de ciguenal CKP, aqui el motor de arranque esta completamente mudo.", "TECNICO", "INTENTO_ARRANQUE", "no_crank_absoluto, arrancador_mudo", "crank_normal_no_start", "", "NO", "SI", CLASE_21, "L2 NO-CRANK estricto vs CKP crank-no-start")
    agregar("G-09-52-13", CLASE_52, "L2", "Al presionar el boton start se escucha un zumbido electrico rapido pero el motor de combustion no se mueve, el bendix patina sin engranar en la corona dentada del volante.", "TECNICO", "INTENTO_ARRANQUE", "bendix_patina, zumbido_rapido, ciguenal_inmovil", "traba_mecanica_motor", "", "NO", "NO", "", "L2 bendix patinando en vacio")
    agregar("G-09-52-14", CLASE_52, "L2", "La bateria tiene carga suficiente y las luces altas alumbran perfecto, pero al dar marcha el solenoide hace un solo chasquido y no se produce giro de arranque.", "COLOQUIAL", "INTENTO_ARRANQUE", "luces_altas_fuertes, solo_un_chasquido, sin_giro", "bateria_muerta", "", "NO", "SI", CLASE_48, "L2 bateria fuerte chasquido unico vs bateria")
    agregar("G-09-52-15", CLASE_52, "L2", "Falla intermitente en arranque en caliente: tras apagar el auto luego de viajar, le doy arranque y no gira; tras golpear suavemente el cuerpo del motor de arranque con una llave enciende al instante.", "COLOQUIAL", "ARRANQUE_CALIENTE", "no_gira_en_caliente, arranca_al_golpear_cuerpo", "falla_bomba_gasolina", "", "NO", "NO", "", "L2 carbones pegados arrancan con golpe")
    agregar("G-09-52-16", CLASE_52, "L2", "Al accionar la llave no hay traqueteo rapido de bateria descargada; se oye un unico 'tac' en el solenoide y el voltimetro del tablero apenas baja, motor completamente inmovil.", "TECNICO", "INTENTO_ARRANQUE", "tac_unico_solenoide, voltimetro_estable, no_crank", "traqueteo_ametralladora_reles", "", "NO", "SI", CLASE_48, "L2 tac unico sin traqueteo rapido vs 48")
    agregar("G-09-52-17", CLASE_52, "L2", "El auto se apago y ahora al dar marcha se escucha el rele bajo el volante pero el motor de arranque no emite ningun sonido, motor termico totalmente detenido sin girar.", "COLOQUIAL", "INTENTO_ARRANQUE", "rele_activa, arrancador_sin_sonido, sin_giro", "giro_normal_sin_encendido", "", "NO", "SI", CLASE_21, "L2 arrancador mudo vs falla CKP giro normal")
    agregar("G-09-52-18", CLASE_52, "L2", "Se conecta escaner y se observa codigo P0615 por circuito de rele de motor de arranque abierto; al puentear manualmente el conector el motor de arranque no reacciona.", "TECNICO", "TALLER_REVISION", "dtc_p0615, puente_sin_reaccion", "falla_sensor_ckp", "P0615", "NO", "NO", "", "L2 DTC P0615 circuito rele arranque")
    agregar("G-09-52-19", CLASE_52, "L2", "El vehiculo no da arranque por llave; la bateria es completamente nueva y el alternador cargaba a 14.1V antes de apagarlo, pero el arrancador quedo trabado sin girar.", "TECNICO", "INTENTO_ARRANQUE", "bateria_nueva, alternador_cargaba_14_1v, arrancador_trabado", "falla_carga_alternador", "", "NO", "SI", CLASE_47, "L2 alternador ok bateria ok vs 47")
    agregar("G-09-52-20", CLASE_52, "L2", "Girando la llave a posicion de marcha el tablero no se apaga ni titilan los testigos, pero el motor no gira ni medio milimetro; el solenoide no empuja la horquilla.", "COLOQUIAL", "INTENTO_ARRANQUE", "tablero_no_parpadea, sin_giro_motor, solenoide_no_desplaza", "luces_muertas", "", "NO", "SI", CLASE_48, "L2 tablero no colapsa vs bateria baja")
    agregar("G-09-52-21", CLASE_52, "L2", "El vehiculo quedo varado: el conductor intento encenderlo y tras un clic seco no hubo respuesta; se intento puente con cables pasa-corriente y el comportamiento fue exactamente identico, motor inmovil.", "COLOQUIAL", "INTENTO_ARRANQUE", "puente_con_cables_mismo_fallo, clic_seco, motor_inmovil", "arranca_con_cables", "", "NO", "SI", CLASE_48, "L2 cables auxilio no resuelven vs bateria")
    agregar("G-09-52-22", CLASE_52, "L2", "Al dar encendido el motor de arranque gira a altas revoluciones en vacio emitiendo un zumbido agudo continuo, sin acoplar el pinon a la corona del volante motor.", "TECNICO", "INTENTO_ARRANQUE", "arranque_gira_en_vacio, zumbido_agudo, sin_acople_corona", "motor_girando_con_compresion", "", "NO", "NO", "", "L2 bendix no engrana horquilla o resorte")
    agregar("G-09-52-23", CLASE_52, "L2", "Arranque intermitente en frio: hace cinco intentos con clac seco sin giro de ciguenal, y en el sexto intento gira con fuerza y arranca de inmediato, sintoma clasico de carbones en su limite.", "COLOQUIAL", "ARRANQUE_FRIO", "clac_sin_giro_5_veces, arranca_con_fuerza_despues", "bateria_agotandose", "", "NO", "NO", "", "L2 carbones en limite con contacto intermitente")
    agregar("G-09-52-24", CLASE_52, "L2", "Diferencia de sintoma clara: cuando fallo el sensor CKP el motor giraba alegremente pero no arrancaba; ahora al girar la llave hay silencio total en el vano motor, no-crank total.", "TECNICO", "INTENTO_ARRANQUE", "silencio_total, no_crank_total", "crank_normal_sin_chispa", "", "NO", "SI", CLASE_21, "L2 contraste explicito silencio vs CKP")
    agregar("G-09-52-25", CLASE_52, "L2", "En vehiculo con transmision manual, empujandolo en segunda velocidad arranca al instante con compresion normal, pero por llave el motor de arranque no gira.", "COLOQUIAL", "ARRANQUE_EMPUJE", "arranca_al_empujar, no_gira_por_llave", "falla_distribucion, falla_inyeccion", "", "NO", "NO", "", "L2 arranca empujado vs motor trabado")

    # L3 (15 casos)
    agregar("G-09-52-26", CLASE_52, "L3", "Diagnostico de condicion NO-CRANK en taller automotriz: bateria en reposo marca 12.65V. Al accionar llave a START, se miden 12.2V en borne de control Terminal 50 del solenoide, pero en borne de salida Terminal M hacia carbones hay 0.0V con caida de tension de 12.1V entre contactos principales del solenoide por pletina interna fogueada.", "TECNICO", "TALLER_VOLTIMETRO", "no_crank, terminal_50_12_2v, terminal_m_0v, caida_pletina_12_1v", "bateria_descargada", "", "NO", "SI", CLASE_48, "L3 caida de tension en pletina de solenoide")
    agregar("G-09-52-27", CLASE_52, "L3", "Prueba de caida de tension en circuito de arranque: entre poste positivo de bateria y borne Terminal 30 del arrancador se registra caida de solo 0.08V. Al dar arranque la bateria cae a 12.35V (sin consumo de corriente motriz) y la pinza amperimetrica marca 1.2A correspondientes unicamente a bobina de solenoide; carbones positivos gastados sin contacto en conmutador.", "TECNICO", "TALLER_AMPERIMETRO", "caida_borne_30_0_08v, consumo_1_2a_solo_solenoide, carbones_gastados", "consumo_arranque_200a", "", "NO", "NO", "", "L3 solo consumo de solenoide 1.2A carbones abiertos")
    agregar("G-09-52-28", CLASE_52, "L3", "Verificacion de condicion de no arranque mecanico: el ciguenal gira libremente con palanca de fuerza en perno de polea (sin traba mecanica de motor). Al girar llave a marcha, el inducido del motor de arranque no rota a pesar de recibir 12.4V en terminales 30 y 50; desmontaje confirma colector del inducido fogueado y resortes de carbones vencidos.", "TECNICO", "TALLER_MECANICO", "ciguenal_gira_manual_libre, terminal_30_y_50_12_4v, colector_fogueado", "motor_fundido_o_amarrado", "", "NO", "NO", "", "L3 descarte de traba mecanica de motor")
    agregar("G-09-52-29", CLASE_52, "L3", "Analisis de corriente con pinza amperimetrica osciloscopica en cable de alimentacion principal: pico de corriente transitoria al dar marcha es de 0 amperios mas alla de los 8A de activacion de bobina retenedora del automatico. Diagnostico confirma escobillas totalmente desgastadas con separacion fisica respecto a delgas.", "TECNICO", "TALLER_OSCILOSCOPIO", "corriente_motriz_0a, pulso_solenoide_8a, escobillas_separadas", "sobreconsumo_por_corto", "", "NO", "SI", CLASE_48, "L3 corriente motriz 0A con pinza osciloscopica")
    agregar("G-09-52-30", CLASE_52, "L3", "Diferenciacion tecnica estricta frente a falla de bateria: la bateria arroja 12.72V de circuito abierto y entrega 620 CCA en probador digital Midtronics (estado de salud 98%). Al conmutar contacto a arranque, la tension de bateria solo desciende a 12.40V con un unico chasquido metalico en el solenoide y 0 RPM de giro en ciguenal.", "TECNICO", "TALLER_MIDTRONICS", "bateria_12_72v_620cca_98soh, tension_cae_a_12_40v, chasquido_unico_0rpm", "bateria_en_mal_estado", "", "NO", "SI", CLASE_48, "L3 Midtronics 98% SOH descarte total bateria")
    agregar("G-09-52-31", CLASE_52, "L3", "Caso contrastivo frente a sensor CKP: con escaner conectado se verifica estado de arranque en datos en vivo: senal 'Starter Relay Command' activa en ON, pero RPM de motor permanece en 0 RPM fijas por inmovilidad fisica de arrancador. En falla de CKP el motor gira a 220-280 RPM por marcha pero no sincroniza inyeccion.", "TECNICO", "TALLER_SCANNER", "starter_relay_on, motor_0_rpm, inmovilidad_arrancador", "giro_250_rpm_sin_arranque", "", "NO", "SI", CLASE_21, "L3 0 RPM arranque vs 250 RPM giro en CKP")
    agregar("G-09-52-32", CLASE_52, "L3", "Prueba de alimentacion y masa en motor de arranque: caida de tension en linea de masa entre carcasa de arrancador y borne negativo de bateria es de 0.04V durante intento de encendido. Terminal 50 recibe 11.9V bajo carga pero el embolo del solenoide se traba mecanicamente a mitad de carrera sin empujar horquilla ni cerrar contactos.", "TECNICO", "TALLER_CAIDA_TENSION", "caida_masa_0_04v_ok, term50_11_9v, embolo_solenoide_trabado", "masa_deficiente", "", "NO", "NO", "", "L3 embolo trabado con masa perfecta 0.04V")
    agregar("G-09-52-33", CLASE_52, "L3", "Escaneo electronico y mediciones: DTC P0615 (Starter Relay Circuit) almacenado en BCM; prueba de continuidad en rele de arranque confirma circuito de control integro, pero medicion de resistencia en bobina de atraccion del solenoide marca infinito (circuito abierto por hilo fundido en borne de conexion).", "TECNICO", "TALLER_SCANNER", "dtc_p0615, bobina_atraccion_infinita_abierta", "falla_rele_bcm", "P0615", "NO", "NO", "", "L3 bobina atraccion abierta DTC P0615")
    agregar("G-09-52-34", CLASE_52, "L3", "Evaluacion en banco de pruebas de arrancador: al aplicar 12V directos con bateria de prueba de 700 CCA, el motor gira a 6500 RPM en vacio pero el pinon de ataque (bendix) patina sobre su embrague unidireccional de rodillos al aplicarle freno mecanico, impidiendo transferir par a la corona del volante.", "TECNICO", "TALLER_BANCO", "arrancador_6500rpm_vacio, bendix_patina_bajo_freno", "carbones_gastados", "", "NO", "NO", "", "L3 embrague unidireccional de bendix safado")
    agregar("G-09-52-35", CLASE_52, "L3", "Ensayo de rotor trabado en vehiculo: al girar la llave a start se escucha un 'clac' sordo y la tension de bateria se desploma bruscamente de 12.6V a 7.2V con corriente instantanea de 480A sin rotacion de ciguenal; bujes de bronce sinterizado del arrancador desalineados produciendo rozamiento y bloqueo mecanico de inducido contra piezas polares.", "TECNICO", "TALLER_MEDICION", "caida_a_7_2v, corriente_480a_rotor_trabado, bujes_desalineados", "bateria_agotada_en_vacio", "", "NO", "SI", CLASE_48, "L3 corriente 480A rotor trabado vs bateria seca")
    agregar("G-09-52-36", CLASE_52, "L3", "Diagnostico electrico: vehiculo con alternador operativo a 14.3V antes de falla; bateria con tension de reposo de 12.58V. Al conectar voltimetro entre borne Terminal 50 y masa de motor se comprueba llegada de 12.1V al accionar switch, pero conmutador de arranque presenta delgas del colector carbonizadas en sector de apoyo.", "TECNICO", "TALLER_VOLTIMETRO", "alternador_14_3v_ok, bateria_12_58v_ok, term50_12_1v, delgas_carbonizadas", "alternador_averiado", "", "NO", "SI", CLASE_47, "L3 alternador y bateria descartados conmutador sucio")
    agregar("G-09-52-37", CLASE_52, "L3", "Medicion con osciloscopio automotriz en linea de corriente de arranque: rampa de corriente muestra ausencia de ondulacion caracteristica de compresion de cilindros; consumo constante de solo 11A atribuible unicamente al solenoide sin conexion de la bobina de serie del motor de campo.", "TECNICO", "TALLER_OSCILOSCOPIO", "sin_ondulacion_compresion, consumo_constante_11a, motor_campo_abierto", "falla_compresion_cilindros", "", "NO", "NO", "", "L3 oscilograma plano de arranque 11A")
    agregar("G-09-52-38", CLASE_52, "L3", "Prueba en rampa de taller: con llave en contacto se realiza puente directo entre borne positivo directo (Terminal 30) y terminal de excitacion (Terminal 50) con cable de 4 mm2; solo salta chispa pequena de control sin ningun intento de giro del motor de arranque, confirmando falla interna de escobillas.", "TECNICO", "TALLER_PRUEBA_DIRECTA", "puente_term30_term50_sin_giro, chispa_control, escobillas_internas_danadas", "falla_switch_encendido", "", "NO", "NO", "", "L3 puente directo 30-50 sin giro")
    agregar("G-09-52-39", CLASE_52, "L3", "Desmontaje y metrologia de motor de arranque: medicion con calibrador pie de rey de longitud de carbones de arranque arroja 4.2 mm (limite de servicio OEM minimo 9.5 mm). Los cables flexibles trenzados hacen tope en la guia impidiendo que los resortes presionen el conmutador.", "TECNICO", "TALLER_METROLOGIA", "carbones_4_2mm_limite_9_5mm, tope_cables_trenzados", "desgaste_rotor", "", "NO", "NO", "", "L3 metrologia pie de rey carbones 4.2mm")
    agregar("G-09-52-40", CLASE_52, "L3", "Prueba de aislamiento y cortocircuito en bobinado de estator e inducido en inductor Growler: bobina de campo de cuatro polos presenta aislamiento superior a 10 Megaohmios a masa, pero inducido presenta cortocircuito entre delgas 14 y 15 por limaduras de cobre acumuladas en ranuras de mica.", "TECNICO", "TALLER_GROWLER", "inductor_growler_corto_delgas_14_15, aislamiento_campo_10mohm", "falla_solenoide", "", "NO", "NO", "", "L3 prueba inductiva en Growler corto inducido")

    # =========================================================================
    # CLASE 53: Fuga parasita de corriente en reposo (consumo nocturno de bateria) (40 casos: 10 L1, 15 L2, 15 L3)
    # =========================================================================
    # L1 (10 casos)
    agregar("G-09-53-01", CLASE_53, "L1", "Si dejo el carro parado dos dias amanece sin nada de bateria.", "COLOQUIAL", "ESTACIONADO_PROLONGADO", "descarga_dos_dias, bateria_vacia", "NO_REPORTA", "", "SI", "NO", "", "L1 descarga tras dos dias parado")
    agregar("G-09-53-02", CLASE_53, "L1", "Todas las mananas tengo que pedir puente para que prenda mi auto.", "COLOQUIAL", "ARRANQUE_MANANA", "requiere_puente_diario, no_prende_manana", "NO_REPORTA", "", "SI", "NO", "", "L1 requiere puente cada manana")
    agregar("G-09-53-03", CLASE_53, "L1", "La bateria se me muere sola durante la noche.", "COLOQUIAL", "REPOSO_NOCTURNO", "bateria_muere_noche", "NO_REPORTA", "", "SI", "NO", "", "L1 bateria se muere de noche")
    agregar("G-09-53-04", CLASE_53, "L1", "Compre bateria nueva la semana pasada y ya se volvio a descargar parada.", "COLOQUIAL", "ESTACIONADO", "bateria_nueva_descargada_parada", "NO_REPORTA", "", "SI", "NO", "", "L1 bateria nueva descargada parada")
    agregar("G-09-53-05", CLASE_53, "L1", "Si uso el carro a diario anda bien, pero el lunes despues del fin de semana no prende.", "COLOQUIAL", "FIN_DE_SEMANA", "falla_tras_fin_de_semana, diario_bien", "NO_REPORTA", "", "SI", "NO", "", "L1 falla fin de semana uso diario ok")
    agregar("G-09-53-06", CLASE_53, "L1", "Tengo un consumo que me agota la bateria con el motor apagado.", "COLOQUIAL", "MOTOR_APAGADO", "consumo_motor_apagado, bateria_agotada", "NO_REPORTA", "", "SI", "NO", "", "L1 consumo con motor apagado")
    agregar("G-09-53-07", CLASE_53, "L1", "El carro amanece totalmente muerto sin luces ni tablero.", "COLOQUIAL", "ARRANQUE_MANANA", "amanece_muerto, sin_luces_tablero", "NO_REPORTA", "", "SI", "NO", "", "L1 amanece totalmente muerto")
    agregar("G-09-53-08", CLASE_53, "L1", "Se me descarga la bateria cuando el auto esta estacionado en la cochera.", "COLOQUIAL", "ESTACIONADO", "descarga_en_cochera", "NO_REPORTA", "", "SI", "NO", "", "L1 descarga estacionado en cochera")
    agregar("G-09-53-09", CLASE_53, "L1", "De noche algo se queda prendido y en la manana no da ni un giro de arranque.", "COLOQUIAL", "REPOSO_NOCTURNO", "algo_prendido_de_noche, sin_giro_manana", "NO_REPORTA", "", "SI", "NO", "", "L1 algo encendido de noche")
    agregar("G-09-53-10", CLASE_53, "L1", "Bateria amanece descargada aunque de dia funciona normal.", "COLOQUIAL", "REPOSO_NOCTURNO", "amanece_descargada, dia_funciona_normal", "NO_REPORTA", "", "SI", "NO", "", "L1 contraste diario vs noche")

    # L2 (15 casos)
    agregar("G-09-53-11", CLASE_53, "L2", "El vehiculo funciona impecable todo el dia en ruta, pero al quedar estacionado en la noche por mas de 8 horas, a la manana siguiente la bateria esta en 10.5V y no enciende.", "COLOQUIAL", "REPOSO_NOCTURNO", "descarga_8_horas_noche, bateria_10_5v, dia_impecable", "descarga_en_marcha", "", "NO", "SI", CLASE_47, "L2 descarga nocturna vs descarga en marcha")
    agregar("G-09-53-12", CLASE_53, "L2", "La bateria tiene solo tres semanas de comprada y fue probada con densimetro al 100%, pero tras dejar el auto parado de viernes a lunes amanece completamente descargada.", "TECNICO", "FIN_DE_SEMANA", "bateria_nueva_probada_100, descarga_viernes_a_lunes", "bateria_defectuosa_fabrica", "", "NO", "SI", CLASE_48, "L2 bateria verificada 100% vs bateria danada")
    agregar("G-09-53-13", CLASE_53, "L2", "Al apagar el motor y cerrar con llave, se nota que la luz interna de la guantera o maletero queda encendida por interruptor descalibrado, drenando la bateria en reposo.", "COLOQUIAL", "REPOSO_NOCTURNO", "luz_maletero_o_guantera_encendida, drenado_en_reposo", "fallo_alternador", "", "NO", "NO", "", "L2 luz de maletero/guantera encendida")
    agregar("G-09-53-14", CLASE_53, "L2", "Se instala radio multimedia aftermarket; durante el dia el alternador mantiene 14.2V de carga en marcha, pero tras apagar el auto la pantalla no entra en modo sleep y vacia la carga en 12 horas.", "TECNICO", "REPOSO_NOCTURNO", "radio_aftermarket_sin_sleep, vaciado_12_horas, alternador_14_2v_ok", "fallo_carga_alternador", "", "NO", "SI", CLASE_47, "L2 radio aftermarket no duerme vs alternador")
    agregar("G-09-53-15", CLASE_53, "L2", "Si desconecto el borne negativo durante la noche, al dia siguiente lo conecto y arranca al primer toque con 12.6V, demostrando que la perdida ocurre por consumo del circuito con el auto apagado.", "TECNICO", "PRUEBA_DESCONEXION", "borne_desconectado_mantiene_carga_12_6v, fuga_circuito_vehiculo", "autodescarga_bateria", "", "NO", "SI", CLASE_48, "L2 prueba borne desconectado vs autodescarga")
    agregar("G-09-53-16", CLASE_53, "L2", "El cierre centralizado de la puerta del copiloto hace un chasquido ciclico cada 20 segundos con el vehiculo cerrado, impidiendo que los modulos de carroceria pasen a modo reposo.", "TECNICO", "VEHICULO_BLOQUEADO", "chasquido_ciclico_cierre, modulos_no_duermen, consumo_permanente", "falla_mecanica_chapa", "", "NO", "SI", CLASE_55, "L2 actuador ciclico despierta red vs cierre")
    agregar("G-09-53-17", CLASE_53, "L2", "Tras apagar el motor y esperar 30 minutos a que duerma la red CAN, se conecta multimetro y se observa un consumo sostenido de 450 miliamperios con todas las luces apagadas.", "TECNICO", "REPOSO_RED_CAN", "consumo_450ma_reposo, can_dormida, luces_apagadas", "consumo_normal_menos_35ma", "", "NO", "NO", "", "L2 medicion 450mA en reposo")
    agregar("G-09-53-18", CLASE_53, "L2", "El alternador carga perfectamente a 14.3V con luces y aire acondicionado encendidos; no hay problema de carga en marcha, la falla es exclusivamente descarga nocturna en estacionamiento.", "TECNICO", "COMPARACION_OPERACIONAL", "alternador_14_3v_carga_ok, descarga_exclusiva_nocturna", "falla_regulador_alternador", "", "NO", "SI", CLASE_47, "L2 alternador 14.3V perfecto vs alternador")
    agregar("G-09-53-19", CLASE_53, "L2", "El rele de los faros antiniebla o desempanador trasero queda con sus contactos pegados aun con el interruptor apagado, calentandose levemente en la fusiblera durante la noche.", "TECNICO", "REPOSO_NOCTURNO", "rele_pegado_caliente_fusiblera, consumo_apagado", "cortocircuito_franco", "", "NO", "NO", "", "L2 rele pegado templado en reposo")
    agregar("G-09-53-20", CLASE_53, "L2", "Se cambio bateria pensando que estaba rota, pero la bateria nueva se descargo a cero tras 48 horas de reposo; la bateria anterior estaba en buen estado.", "COLOQUIAL", "ESTACIONADO_48H", "bateria_nueva_descargada_48h, cambio_bateria_inutil", "bateria_danada", "", "NO", "SI", CLASE_48, "L2 cambio erroneo de bateria vs consumo")
    agregar("G-09-53-21", CLASE_53, "L2", "Alarma no original instalada presenta falla en sensor de impacto volumetrico y mantiene activo el consumo de corriente en la linea de bateria constante en reposo.", "TECNICO", "VEHICULO_ESTACIONADO", "alarma_aftermarket_consumo_linea_constante", "fallo_bateria", "", "NO", "NO", "", "L2 consumo alarma aftermarket")
    agregar("G-09-53-22", CLASE_53, "L2", "Con el vehiculo cerrado y bloqueado, el modulo de control de carroceria BCM no reduce su consumo y mantiene la red despierta, agotando la carga cada manana.", "TECNICO", "VEHICULO_BLOQUEADO", "bcm_no_reduce_consumo, red_despierta, vaciado_manana", "bateria_envejece", "", "NO", "NO", "", "L2 BCM mantiene red despierta")
    agregar("G-09-53-23", CLASE_53, "L2", "Diferencia de sintoma clara: en marcha el voltimetro marca 14.1V constantes sin parpadeo de luces, pero tras 10 horas de estacionamiento la bateria cae de 12.6V a 11.2V.", "TECNICO", "ESTACIONADO_10H", "voltimetro_marcha_14_1v_ok, caida_a_11_2v_en_10h", "alternador_defectuoso", "", "NO", "SI", CLASE_47, "L2 contraste voltajes marcha vs 10h reposo")
    agregar("G-09-53-24", CLASE_53, "L2", "El actuador electrico de la cerradura del maletero no reporta el estado cerrado, provocando que la computadora de confort permanezca en vigilia consumiendo energia.", "TECNICO", "VEHICULO_BLOQUEADO", "maletero_no_reporta_cerrado, computadora_vigilia_consumo", "mecanismo_chapa_trabado", "", "NO", "SI", CLASE_55, "L2 microswitch maletero vigilia vs cerradura")
    agregar("G-09-53-25", CLASE_53, "L2", "El auto se utiliza diariamente para reparto sin problema; si queda guardado sabado y domingo, el lunes el motor de arranque no gira por falta de energia en bateria.", "COLOQUIAL", "FIN_DE_SEMANA", "uso_diario_sin_falla, descarga_sabado_domingo, lunes_sin_energia", "arrancador_danado", "", "NO", "SI", CLASE_52, "L2 lunes sin energia vs motor arranque 52")

    # L3 (15 casos)
    agregar("G-09-53-26", CLASE_53, "L3", "Diagnostico de consumo parasito en reposo en taller: medicion con pinza amperimetrica DC de baja corriente en borne negativo tras 45 minutos de cierre y bloqueo con red CAN dormida registra 680 mA continuos (especificacion maxima OEM: 35 mA). Al extraer fusible F24 de 15A correspondiente a sistema de audio infotainment el consumo desciende a 22 mA.", "TECNICO", "TALLER_AMPERIMETRO", "consumo_reposo_680ma, extraccion_fusible_f24_baja_a_22ma, red_can_dormida", "falla_bateria", "", "NO", "NO", "", "L3 pinza DC 680mA fusible F24 baja a 22mA")
    agregar("G-09-53-27", CLASE_53, "L3", "Localizacion de fuga parasita mediante medicion de caida de tension en milivoltios (mV) a traves de fusibles tipo mini: en fusible F12 (10A) se registran 3.8 mV de caida con voltimetro digital en escala de mV DC. Segun tabla de conversion para fusible de 10A, esto equivale a 490 mA de corriente drenandose de forma permanente por modulo de telematica.", "TECNICO", "TALLER_MILIVOLTIOS", "caida_3_8mv_fusible_10a, corriente_calculada_490ma, telematica", "falla_alternador", "", "NO", "NO", "", "L3 caida mV en fusible tabla conversion 490mA")
    agregar("G-09-53-28", CLASE_53, "L3", "Comprobacion de estado de bateria y alternador: probador Midtronics certifica bateria de 12V con 100% de salud (SOH) y 580 CCA reales; alternador entrega 14.35V en ralenti con ondulacion de rizado AC de solo 0.04V. Sin embargo, con llave fuera y reposo de 60 minutos se registra corriente parasita de 820 mA atribuible a rele de calefaccion auxiliar trabado.", "TECNICO", "TALLER_INTEGRAL", "midtronics_100_soh_580cca, alternador_14_35v_0_04v_ripple, fuga_820ma_rele_calefaccion", "bateria_agotada, diodo_alternador_abierto", "", "NO", "SI", CLASE_47, "L3 Midtronics 100% alternador 14.35V fuga 820mA")
    agregar("G-09-53-29", CLASE_53, "L3", "Evaluacion de corriente en reposo: con osciloscopio y pinza amperimetrica acoplada en DC, se evidencia que la red CAN-Bus intenta entrar en sleep mode cada 3 minutos pero se despierta inmediatamente por pulsos espurios del actuador de cerradura de puerta trasera izquierda, manteniendo consumo medio de 520 mA.", "TECNICO", "TALLER_OSCILOSCOPIO", "red_can_despierta_cada_3min, pulsos_actuador_cerradura, consumo_520ma", "falla_mecanica_puerta", "", "NO", "SI", CLASE_55, "L3 CAN despierta por actuador puerta 520mA")
    agregar("G-09-53-30", CLASE_53, "L3", "Procedimiento de rastreo de consumo nocturno segun manual de servicio: vehiculo cerrado con pestillos y capo simulado cerrado. Medicion inicial en serie: 1.1A; a los 25 minutos cae a 750 mA y se estabiliza ahi. Al retirar el rele RLY_ACC el consumo baja bruscamente a 18 mA, confirmando puenteo resistivo interno de 16 Ohmios entre contactos 30 y 87.", "TECNICO", "TALLER_PROCEDIMIENTO", "medicion_serie_750ma_estable, retiro_rele_acc_baja_a_18ma, puenteo_16_ohm", "consumo_normal", "", "NO", "NO", "", "L3 medicion serie 750mA rele ACC baja a 18mA")
    agregar("G-09-53-31", CLASE_53, "L3", "Diagnostico diferencial estricto frente a bateria defectuosa: bateria con tension en reposo de 12.68V tras carga independiente. Instalada en vehiculo sin conectar bornes mantiene 12.65V tras 48 horas. Conectada al automovil con consumo parasito medido de 550 mA cae a 11.40V en 14 horas, confirmando drenaje externo del circuito electrico y no autodescarga de celdas.", "TECNICO", "TALLER_PRUEBA_AISLADA", "bateria_aislada_12_65v_48h, conectada_cae_a_11_40v_14h, fuga_550ma", "autodescarga_quimica", "", "NO", "SI", CLASE_48, "L3 prueba bateria aislada vs conectada 550mA")
    agregar("G-09-53-32", CLASE_53, "L3", "Medicion con multimetro Fluke en serie en polo negativo: corriente parasitaria fija de 380 mA tras 40 minutos de espera. Monitoreo termico con camara infrarroja en fusiblera del habitaculo ubica punto caliente a 36°C en fusible F38 (modulo de control de carroceria BCM), causado por diodo zener de proteccion en fuga interna.", "TECNICO", "TALLER_TERMOGRAFIA", "multimetro_serie_380ma, punto_caliente_36c_fusible_f38_bcm, zener_fuga", "falla_aislamiento_cableado", "", "NO", "NO", "", "L3 termografia fusible F38 36C fuga 380mA")
    agregar("G-09-53-33", CLASE_53, "L3", "Verificacion de circuito de carga y descarga: tension de carga con motor en marcha a 2000 RPM es 14.28V con 35A entregados hacia bateria. Tras apagar motor, apagar luces y bloquear puertas, el consumo residual es de 440 mA sostenidos; desconectando el conector del amplificador de sonido de fabrica el consumo cae a 19 mA conformes a norma.", "TECNICO", "TALLER_COMPROBACION", "carga_14_28v_35a_ok, consumo_residual_440ma, amplificador_desconectado_19ma", "alternador_baja_carga", "", "NO", "SI", CLASE_47, "L3 alternador 14.28V 35A ok amplificador 440mA")
    agregar("G-09-53-34", CLASE_53, "L3", "Prueba de caida de tension en fusibles maxi en vano motor: fusible de 50A de alimentacion a modulo de puerta del conductor muestra 0.6 mV de caida continua. Calculo segun formula de resistencia de fusible arroja corriente parasitaria de 390 mA por microinterruptor de cerradura sulfatado que impide reposo del procesador.", "TECNICO", "TALLER_MILIVOLTIOS", "maxifusible_50a_0_6mv, corriente_calculada_390ma, microinterruptor_sulfatado", "fallo_bateria", "", "NO", "SI", CLASE_55, "L3 maxifusible 50A 0.6mV microinterruptor puerta")
    agregar("G-09-53-35", CLASE_53, "L3", "Protocolo de busqueda de drenaje nocturno: corriente de reposo registrada de 920 mA con todas las cargas desconectadas. Al desconectar alternador (borne B+) la fuga se mantiene en 920 mA (descartando puente rectificador); al desconectar modulo de rastreo GPS satelital no original el consumo desciende a 25 mA.", "TECNICO", "TALLER_DESCONEXION", "corriente_reposo_920ma, descarte_borne_b_alternador, gps_satelital_baja_a_25ma", "diodos_alternador_en_fuga", "", "NO", "SI", CLASE_47, "L3 descarte borne B+ alternador GPS 920mA")
    agregar("G-09-53-36", CLASE_53, "L3", "Inspeccion tecnica en vehiculo de 12V: la bateria amanecia en 10.9V cada dos dias. Se mide corriente en reposo arrojando 610 mA continuos; analisis con punta logica en bus LIN detecta comunicacion continua sin transicion a estado de baja potencia por parte del sensor de lluvia y luz del parabrisas.", "TECNICO", "TALLER_OSCILOSCOPIO", "bateria_10_9v_dos_dias, corriente_reposo_610ma, bus_lin_despierto_sensor_lluvia", "bateria_sulfatada", "", "NO", "SI", CLASE_48, "L3 bus LIN sensor lluvia despierto 610mA")
    agregar("G-09-53-37", CLASE_53, "L3", "Medicion con registrador de datos de corriente (Datalogger) durante 8 horas de estacionamiento: la corriente se mantiene constante entre 430 mA y 470 mA durante toda la madrugada, totalizando un consumo acumulado de 3.6 Ah que deja a la bateria de 45 Ah por debajo de su umbral de arranque en frio.", "TECNICO", "TALLER_DATALOGGER", "datalogger_8h_450ma_constante, consumo_acumulado_3_6ah, umbral_arranque_superado", "falla_motor_arranque", "", "NO", "SI", CLASE_52, "L3 datalogger 8h 450mA acumulado 3.6Ah")
    agregar("G-09-53-38", CLASE_53, "L3", "Localizacion de fuga parasita en circuito de confort: se registra caida de tension de 2.4 mV en fusible F19 de 7.5A (iluminacion interior). Inspeccion visual con espejo confirma que el interruptor de mercurio de iluminacion de maletero no abre al bajar el porton, manteniendo lampara de 5W encendida consumiendo 410 mA.", "TECNICO", "TALLER_INSPECCION", "caida_2_4mv_fusible_7_5a, lampara_5w_maletero_encendida, consumo_410ma", "falla_alternador", "", "NO", "NO", "", "L3 fusible F19 2.4mV lampara maletero 5W 410mA")
    agregar("G-09-53-39", CLASE_53, "L3", "Prueba de aislamiento de circuitos secundarios: corriente de fuga residual en borne positivo de 780 mA en reposo con llave fuera. Desconexion individual de fusibles en compartimento de motor: el retiro del fusible F08 (unidad de control de traccion y sensor de angulo) reduce el consumo a 28 mA por condensador ceramico SMD en cortocircuito de fuga.", "TECNICO", "TALLER_DESCONEXION", "fuga_residual_780ma, retiro_f08_baja_a_28ma, condensador_smd_fuga", "falla_bateria", "", "NO", "NO", "", "L3 desconexion fusible F08 780mA a 28mA")
    agregar("G-09-53-40", CLASE_53, "L3", "Evaluacion de consumo parasitario tras queja de bateria descargada al tercer dia de inactividad: consumo medido en reposo con red CAN dormida es de 310 mA (limite OEM 40 mA). Inspeccion revela conector del enganche de remolque con entrada de agua y sulfatacion interna generando puente resistivo de 38 Ohmios hacia masa.", "TECNICO", "TALLER_INSPECCION", "consumo_reposo_310ma, enganche_remolque_sulfatado, puente_38_ohm_a_masa", "autodescarga_bateria", "", "NO", "SI", CLASE_48, "L3 enganche remolque sulfatado 38 ohm 310mA")

    return casos
