"""
Generador de registros de Lote 05 - Parte 1: Clases 21 a 23.
- Clase 21: Falla en sensor de posicion de cigueñal (CKP) o arbol de levas (CMP)
- Clase 22: Falla en sistema de control de emisiones evaporativas EVAP (canister o valvula de purga)
- Clase 23: Convertidor catalitico ineficiente u obstruido (DTC P0420 / P0430)

Total: 120 registros (40 por clase: 10 L1, 15 L2, 15 L3).
"""

CLASE_21 = "Falla en sensor de posicion de cigueñal (CKP) o arbol de levas (CMP)"
CLASE_22 = "Falla en sistema de control de emisiones evaporativas EVAP (canister o valvula de purga)"
CLASE_23 = "Convertidor catalitico ineficiente u obstruido (DTC P0420 / P0430)"

def obtener_casos_21_23(offset=1):
    casos = []
    idx = offset

    def agregar(id_grupo, clase, nivel, texto, tipo_lenguaje, cond, sint_pres, sint_neg, dtc, req_preg, es_cont, cl_cont, obs):
        nonlocal idx
        reg_id = f"F10-L05-{idx:04d}"
        idx += 1
        casos.append({
            "id": reg_id,
            "id_grupo": id_grupo,
            "clase_objetivo": clase,
            "macro_sistema": "MOTOR",
            "nivel_informacion": nivel,
            "texto_usuario": texto.strip(),
            "tipo_lenguaje": tipo_lenguaje,
            "condicion_operacion": cond.strip(),
            "sintomas_presentes": sint_pres.strip(),
            "sintomas_negados": sint_neg.strip(),
            "dtc": dtc.strip(),
            "requiere_pregunta": req_preg.strip(),
            "es_contrastivo": es_cont.strip(),
            "clase_contrastiva": cl_cont.strip(),
            "fuente": "SINTETICO_IA",
            "observaciones": obs.strip()
        })

    # =========================================================================
    # CLASE 21: Sensor CKP / CMP (40 casos: 10 L1, 15 L2, 15 L3)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G21-L1-01", CLASE_21, "L1", "El carro se apaga de golpe cuando calienta y luego no quiere prender.", "COTIDIANO", "motor_caliente", "apagado_caliente_no_enciende", "", "", "SI", "NO", "", "L1 corte súbito térmico.")
    agregar("G21-L1-02", CLASE_21, "L1", "Hola, doy arranque con la llave, el motor gira normal pero no arranca nada.", "WHATSAPP", "arranque", "gira_no_arranca", "", "", "SI", "NO", "", "L1 arranque infructuoso con giro normal.")
    agregar("G21-L1-03", CLASE_21, "L1", "La aguja de las revoluciones se queda muerta en cero mientras intento encender.", "COTIDIANO", "arranque", "aguja_tacometro_en_cero", "", "", "SI", "NO", "", "L1 tacómetro sin lectura en marcha.")
    agregar("G21-L1-04", CLASE_21, "L1", "El motor tironea con cortes secos en autopista como si le quitaran la corriente.", "TALLER", "autopista", "cortes_secos_corriente", "", "", "SI", "NO", "", "L1 tirones de ignición intermitentes.")
    agregar("G21-L1-05", CLASE_21, "L1", "Se prendió el Check Engine y demora varios segundos de giro en arrancar.", "COTIDIANO", "arranque_largo", "check_engine|arranque_prolongado", "", "", "SI", "NO", "", "L1 arranque largo con testigo.")
    agregar("G21-L1-06", CLASE_21, "L1", "El escáner arrojó falla en el circuito del sensor de posición del motor.", "TECNICO", "diagnostico", "falla_circuito_sensor_posicion", "", "", "SI", "NO", "", "L1 reporte genérico de sensor de posición.")
    agregar("G21-L1-07", CLASE_21, "L1", "Se apaga al llegar a temperatura de trabajo y a los 20 minutos vuelve a encender.", "COTIDIANO", "ciclo_termico", "apaga_temperatura_trabajo|enciende_enfriar", "", "", "SI", "NO", "", "L1 corte dependiente de enfriamiento.")
    agregar("G21-L1-08", CLASE_21, "L1", "Mi auto se para de la nada en el semaforo y no hay chispa en las bujias.", "ERROR_ORTOGRAFICO", "ralenti_caliente", "se_para_semaforo|sin_chispa", "", "", "SI", "NO", "", "L1 apagado sin chispa con error ortográfico.")
    agregar("G21-L1-09", CLASE_21, "L1", "Buenas, el carro gira alegre con la batería pero parece que no le llega corriente.", "WHATSAPP", "arranque", "gira_alegre_sin_arrancar", "", "", "SI", "NO", "", "L1 giro vigoroso sin ignición.")
    agregar("G21-L1-10", CLASE_21, "L1", "Pérdida momentánea de sincronismo angular entre volante y tren de válvulas.", "TECNICO", "marcha", "perdida_sincronismo_angular", "", "", "SI", "NO", "", "L1 reporte técnico de sincronismo angular.")

    # --- L2 (15 casos) ---
    agregar("G21-L2-01", CLASE_21, "L2", "El motor gira con buena velocidad de arranque pero no enciende; se verificó y no hay chispa en bujías ni pulso en inyectores porque el sensor CKP no emite señal.", "COTIDIANO", "arranque", "sin_chispa|sin_pulso_inyectores|ckp_sin_senal", "falla_bateria", "", "NO", "SI", "Bomba de gasolina quemada o con baja presion", "L2 ausencia simultánea de chispa e inyección vs bomba de gasolina.")
    agregar("G21-L2-02", CLASE_21, "L2", "Código P0335 referente al sensor de cigüeñal; el auto se apaga repentinamente tras rodar 25 minutos y no vuelve a prender hasta que el bloque de motor se enfría.", "TECNICO", "marcha_caliente", "dtc_p0335|apaga_25min|enciende_al_enfriar", "falla_bomba_combustible", "P0335", "NO", "SI", "Bomba de gasolina quemada o con baja presion", "L2 DTC P0335 con corte térmico repetitivo.")
    agregar("G21-L2-03", CLASE_21, "L2", "Al dar marcha el motor de arranque gira perfecto pero la aguja del tacómetro no se mueve de cero; la bomba de gasolina funciona con puente pero no por comando de la ECU.", "TALLER", "arranque", "tacometro_cero_arranque|bomba_ok_puente", "falla_motor_arranque", "", "NO", "SI", "Falla en motor de arranque o solenoide defectuoso (clac seco o carbones gastados)", "L2 tacómetro en cero con motor de arranque girando fuerte.")
    agregar("G21-L2-04", CLASE_21, "L2", "Hola maestro, el escáner arroja P0340 en el sensor de levas CMP. El auto arranca después de 6 segundos de insistir y se siente sin fuerza al acelerar.", "WHATSAPP", "arranque_largo", "dtc_p0340|arranque_6_segundos|falta_fuerza", "falla_cadena", "P0340", "NO", "SI", "Faja o cadena de distribucion destensada o con salto de punto", "L2 arranque en modo degradado por CMP vs cadena.")
    agregar("G21-L2-05", CLASE_21, "L2", "El sensor de cigüeñal inductivo tiene la bobina interna degradada; en frío mide 900 ohms dentro de rango pero al calentar a 80°C sube a circuito abierto infinito.", "TECNICO", "prueba_resistencia_termica", "resistencia_900_a_infinito_caliente", "falla_bobinas", "", "NO", "NO", "", "L2 bobina de CKP abre circuito por temperatura.")
    agregar("G21-L2-06", CLASE_21, "L2", "En autopista se siente un corte abrupto de encendido de un segundo y prende Check Engine con P0339; el cable blindado del CKP tiene la malla rota rozando el escape.", "TALLER", "autopista_corte", "corte_un_segundo|dtc_p0339|cable_blindado_ckp_roce", "falla_bujia", "P0339", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L2 corte total P0339 por apantallamiento vs bujía.")
    agregar("G21-L2-07", CLASE_21, "L2", "El carro arranca al toque en la mañana pero si lo apago después de manejar una hora ya no prende; le echo agua fría al sensor detrás de la polea y arranca de una.", "COTIDIANO", "choque_termico_sensor", "no_prende_en_caliente|agua_fria_sensor_enciende", "falla_motor_arranque", "", "NO", "SI", "Falla en motor de arranque o solenoide defectuoso (clac seco o carbones gastados)", "L2 prueba empírica de agua en sensor CKP descarta motor de arranque.")
    agregar("G21-L2-08", CLASE_21, "L2", "Mi carro da vueltas el motor pero no arranca y en el tablero sale codigo P0335. Revisaron la faja y esta en su punto pero el captador de cigueñal no lee los dientes.", "ERROR_ORTOGRAFICO", "arranque_fallido", "dtc_p0335|faja_en_punto|captador_no_lee_dientes", "faja_saltada", "P0335", "NO", "SI", "Faja o cadena de distribucion destensada o con salto de punto", "L2 faja en punto descarta distribución corrida.")
    agregar("G21-L2-09", CLASE_21, "L2", "Sensor de árbol de levas CMP tipo Hall genera señal plana de 5V fijos sin conmutar a masa al girar la rueda fónica por falla en el circuito integrado interno.", "TECNICO", "comprobacion_voltaje_hall", "senal_5v_plana_sin_conmutar|circuito_hall_averiado", "falla_computadora", "", "NO", "NO", "", "L2 sensor Hall bloqueado en nivel alto.")
    agregar("G21-L2-10", CLASE_21, "L2", "El motor tironea fuerte a 2500 rpm y pierde sincronismo con código P0016; el calado mecánico está perfecto y el juego axial del dámper no existe, siendo el sensor CMP el defectuoso.", "TALLER", "2500rpm_tironeo", "dtc_p0016|calado_mecanico_perfecto|sensor_cmp_defectuoso", "cadena_estirada", "P0016", "NO", "SI", "Faja o cadena de distribucion destensada o con salto de punto", "L2 calado perfecto descarta cadena y confirma sensor CMP.")
    agregar("G21-L2-11", CLASE_21, "L2", "Buenas maestro, el carro se me apagó rodando. Pensé que era la bomba pero el mecánico me dice que la bomba manda gasolina y lo que no hay es chispa por sensor de cigueñal.", "WHATSAPP", "marcha_apagado", "apago_rodando|bomba_manda_gasolina|sin_chispa_sensor_cigueñal", "falla_bomba_gasolina", "", "NO", "SI", "Bomba de gasolina quemada o con baja presion", "L2 bomba manda combustible descartando bomba de gasolina.")
    agregar("G21-L2-12", CLASE_21, "L2", "DTC P0341 de rango y rendimiento del sensor de posición del árbol de levas; el conector tiene la traba rota y vibra desconectándose en caminos irregulares.", "TECNICO", "inspeccion_conector_cmp", "dtc_p0341|conector_traba_rota|falso_contacto_vibracion", "falla_vvt", "P0341", "NO", "SI", "Falla en sistema de sincronizacion variable de valvulas (VVT / VVT-i / Valvetronic)", "L2 código P0341 por conector flojo vs sistema VVT.")
    agregar("G21-L2-13", CLASE_21, "L2", "El motor tose y cabecea al intentar arrancar en caliente; el sensor CKP tiene acumulación de viruta metálica del embrague en la punta imantada que deforma la lectura.", "TALLER", "inspeccion_punta_sensor", "viruta_metalica_punta_imantada_ckp|deformacion_lectura", "falla_motor_arranque", "", "NO", "NO", "", "L2 viruta imantada en punta de sensor CKP.")
    agregar("G21-L2-14", CLASE_21, "L2", "El auto arranca pero no pasa de 3000 rpm funcionando en estrategia de emergencia; el sensor CMP no entrega pulsos y la ECU sincroniza solo por flancos del CKP.", "COTIDIANO", "limp_mode_3000rpm", "modo_emergencia_3000rpm|cmp_sin_pulsos|sincroniza_solo_ckp", "falla_cuerpo_mariposa", "", "NO", "NO", "", "L2 modo de emergencia por ausencia de CMP.")
    agregar("G21-L2-15", CLASE_21, "L2", "DTC P0335 intermitente en aceleración fuerte; el entrehierro entre el sensor de cigüeñal y la rueda fónica es excesivo con 1.8 mm (tolerancia 0.5 a 1.0 mm).", "TECNICO", "medicion_entrehierro", "dtc_p0335|entrehierro_1_8mm_excesivo|tolerancia_1mm", "falla_rueda_fonica", "P0335", "NO", "NO", "", "L2 entrehierro excesivo de 1.8 mm en sensor CKP.")

    # --- L3 (15 casos) ---
    agregar("G21-L3-01", CLASE_21, "L3", "En prueba de osciloscopio automotriz de dos canales se monitorea la señal analógica del sensor de cigüeñal inductivo CKP y la señal digital cuadrada de 5V del CMP. Al calentar el motor a 92°C de refrigerante la amplitud pico a pico del CKP colapsa de 4.2V a 0.3V por cortocircuito térmico entre espiras internas de la bobina, apagando el motor de golpe con DTC P0335. La presión de gasolina se mantiene en 3.8 bar y la compresión es de 165 psi pareja.", "TECNICO", "analisis_osciloscopio_dos_canales", "dtc_p0335|ckp_colapsa_4_2_a_0_3v_termico|presion_combustible_3_8bar_ok", "falla_bomba_gasolina_electrica", "P0335", "NO", "SI", "Bomba de gasolina quemada o con baja presion", "L3 oscilograma dual demuestra colapso de amplitud a 0.3V descartando bomba.")
    agregar("G21-L3-02", CLASE_21, "L3", "El vehículo ingresa en grúa por no encender tras apagarse en marcha. El motor de arranque gira vigorosamente a 260 rpm pero el escáner reporta 'Engine Speed: 0 RPM' en datos en vivo y DTC P0335. Se conectó lámpara de prueba noid en los 4 conectores de inyectores y no hay destello de masa, ni tampoco salto de chispa en las bobinas COP. Se midió la resistencia del sensor CKP marcando circuito abierto infinito en lugar de 850 ohms especificados.", "TALLER", "diagnostico_linea_ckp_noid", "dtc_p0335|engine_speed_0rpm|sin_chispa_sin_noid|resistencia_ckp_infinita", "falla_motor_arranque", "P0335", "NO", "SI", "Falla en motor de arranque o solenoide defectuoso (clac seco o carbones gastados)", "L3 RPM en cero con lámpara noid inactiva y resistencia infinita.")
    agregar("G21-L3-03", CLASE_21, "L3", "Código P0340 referente al sensor CMP del árbol de levas de escape. El motor demora 8 segundos de marcha para arrancar y se enciende el Check Engine. Al medir con osciloscopio la señal de salida del sensor Hall se observa que la tensión de nivel bajo no cae a 0V sino que se queda estancada en 1.8V debido a degradación de la etapa de drenador abierto, impidiendo que la PCM reconozca el flanco de bajada de sincronización.", "TECNICO", "diagnostico_flanco_hall_cmp", "dtc_p0340|nivel_bajo_estancado_1_8v|pcm_no_detecta_flanco_bajada", "falla_computadora_pcm", "P0340", "NO", "NO", "", "L3 nivel bajo Hall en 1.8V impide reconocimiento de flanco.")
    agregar("G21-L3-04", CLASE_21, "L3", "Vehículo presenta tironeos violentos en aceleración y código P0016. Se desmontó la tapa de distribución y se verificó con útil de calado OEM que las marcas de árbol de levas y cigüeñal coinciden al milímetro con cadena tensa. Al revisar el sensor CMP se constató que la carcasa plástica está fisurada y rozaba contra la rueda fónica, habiendo desgastado el núcleo captador magnético.", "TALLER", "inspeccion_calado_vs_sensor", "dtc_p0016|marcas_calado_exactas_cadena_tensa|sensor_cmp_fisurado_roce", "cadena_saltada", "P0016", "NO", "SI", "Faja o cadena de distribucion destensada o con salto de punto", "L3 útil de calado perfecto descarta cadena corrida y confirma CMP fisurado.")
    agregar("G21-L3-05", CLASE_21, "L3", "Hola maestro, el carro se me apaga después de manejar media hora y tengo que esperar que se enfríe para que vuelva a encender. En el taller le cambiaron bujías, bobinas y bomba de nafta pero seguía con la falla. Le pusieron el osciloscopio al sensor del cigueñal que va abajo y cuando calienta la señal se vuelve una raya recta; le cambiaron el sensor CKP y se arregló.", "WHATSAPP", "historial_piezas_cambiadas_ckp", "apaga_media_hora|piezas_cambiadas_persiste|senal_ckp_se_vuelve_recta", "falla_bujias_bobinas", "", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L3 piezas de encendido y bomba nuevas descartan rivales.")
    agregar("G21-L3-06", CLASE_21, "L3", "DTC P0336 referente al rendimiento del sensor de cigüeñal. En captura de osciloscopio se detecta que el diente de referencia faltante (gap de 60-2 dientes) presenta ruido eléctrico parásito de alta frecuencia inducido por el alternador, borrando la ventana de sincronización para la computadora cada vez que se encienden las luces altas.", "TECNICO", "ruido_parasito_diente_faltante", "dtc_p0336|ruido_parasito_gap_60_menos_2|interferencia_alternador", "falla_bateria", "P0336", "NO", "NO", "", "L3 ruido parásito en diente faltante gap 60-2.")
    agregar("G21-L3-07", CLASE_21, "L3", "El motor arranca con dificultad presentando contraexplosiones por el múltiple de admisión. Se conectó escáner mostrando DTC P0341 en sensor CMP. La prueba con multímetro arrojó alimentación de 5.0V correcta y masa de 0.02V impecable, pero la señal de salida no conmuta debido a fractura del imán permanente interno en el cabezal del sensor.", "TALLER", "alimentacion_y_masa_cmp", "dtc_p0341|alimentacion_5v_ok_masa_ok|iman_fracturado_cabezal", "falla_cableado_alimentacion", "P0341", "NO", "NO", "", "L3 alimentaciones perfectas con imán interno fracturado.")
    agregar("G21-L3-08", CLASE_21, "L3", "Mi auto se apaga de golpe en carretera con codigo P0335 y no arranca mas hasta que enfria. En el taller le midieron con tester la resistencia al sensor de cigueñal y en caliente dio infinito cortado. Le pusieron sensor nuevo original y no volvio a fallar en subidas ni en trafico.", "ERROR_ORTOGRAFICO", "corte_carretera_tester", "dtc_p0335|resistencia_infinita_cortado_caliente|sensor_nuevo_resuelve", "falla_modulo_ignicion", "P0335", "NO", "NO", "", "L3 resistencia infinita en caliente comprobada con tester y ortografía informal.")
    agregar("G21-L3-09", CLASE_21, "L3", "Corte súbito de encendido bajo vibración a 3500 rpm con código P0339. Al inspeccionar el conector del sensor CKP de 3 pines se halló el pin hembra de señal ensanchado sin tensión mecánica, provocando microdesconexiones de 5 milisegundos que resetean el contador de sincronización del PCM.", "TECNICO", "inspeccion_pin_conector_ckp", "dtc_p0339|pin_hembra_ensanchado|microdesconexiones_5ms", "falla_bobina_encendido", "P0339", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L3 microdesconexiones de 5 ms por pin hembra ensanchado.")
    agregar("G21-L3-10", CLASE_21, "L3", "DTC P0017 en motor VVT de 4 cilindros. Se verificó con manómetro hidráulico que la presión de aceite llega a 45 psi a los variadores y el solenoide OCV actúa linealmente. Al intercambiar los sensores CMP de admisión y escape el código migró a P0016, comprobándose que la falla residía en el sensor Hall y no en el sistema mecánico de avance variable.", "TALLER", "intercambio_sensores_cmp", "dtc_p0017_migra_a_p0016|presion_aceite_45psi_ok|solenoide_ocv_lineal", "falla_solenoide_vvt", "P0017", "NO", "SI", "Falla en sistema de sincronizacion variable de valvulas (VVT / VVT-i / Valvetronic)", "L3 prueba cruzada de sensores CMP migra el código de falla.")
    agregar("G21-L3-11", CLASE_21, "L3", "Buenas tardes, el carro tiembla en mínimo y a veces se apaga cuando piso el freno en un semáforo. En el escáner sale código de árbol de levas pero la distribución es nueva y la pusieron con trabas originales de fábrica. Le sacaron el sensor CMP y estaba partido en la punta porque rozaba.", "WHATSAPP", "distribucion_nueva_con_trabas", "dtc_arbol_levas|distribucion_nueva_con_trabas|sensor_cmp_partido_punta", "cadena_destensada", "", "NO", "SI", "Faja o cadena de distribucion destensada o con salto de punto", "L3 distribución nueva calada con trabas descarta salto de faja.")
    agregar("G21-L3-12", CLASE_21, "L3", "Medición de tensión de referencia del sensor Hall del árbol de levas: al dar contacto la línea de pull-up entrega 5.0V normales provenientes de la ECU. Al girar el motor manualmente el voltaje conmuta entre 0.1V y 4.9V correctamente pero al superar las 1200 rpm la frecuencia de salida se desconfigura por histéresis térmica del integrado.", "TECNICO", "prueba_histeresis_termica_hall", "pull_up_5v_ok|conmuta_manual_falla_a_1200rpm|histeresis_termica", "falla_ecu", "", "NO", "NO", "", "L3 fallo de conmutación dependiente de frecuencia por histéresis térmica.")
    agregar("G21-L3-13", CLASE_21, "L3", "El motor arranca tras 10 segundos de marcha únicamente en modo de respaldo utilizando la señal de CMP con código P0335 activo. Al revisar el sensor CKP detrás del volante de inercia se encontró que el cable sufrió aprisionamiento contra la carcasa de la caja durante el cambio de embrague cortando la línea a masa.", "TALLER", "modo_respaldo_cmp", "dtc_p0335|modo_respaldo_arranque_10seg|cable_ckp_aprisionado_caja", "falla_embrague", "P0335", "NO", "SI", "Disco de embrague desgastado o patinando", "L3 cable aprisionado en montaje de embrague causa P0335.")
    agregar("G21-L3-14", CLASE_21, "L3", "DTC P0340 recurrente en motor 1.6 16v. La señal del sensor CMP presenta flancos de subida redondeados con tiempo de transición de más de 80 microsegundos (especificación menor a 5 us) debido a condensador interno en fuga, impidiendo que el microprocesador sincronice el encendido secuencial.", "TECNICO", "analisis_tiempo_transicion_flancos", "dtc_p0340|tiempo_transicion_80us_redondeado|condensador_interno_fuga", "falla_inyectores", "P0340", "NO", "NO", "", "L3 flancos redondeados a 80 us por condensador en fuga.")
    agregar("G21-L3-15", CLASE_21, "L3", "Al exigir el motor en subida se producen tirones severos seguidos de apagado total de inyección con código P0335. Se comprobó que al calentar el motor el entrehierro del sensor CKP se incrementa por dilatación térmica de la pletina de soporte de chapa doblada, cayendo el voltaje inducido por debajo del umbral de detección.", "TALLER", "dilatacion_soporte_ckp", "dtc_p0335|dilatacion_soporte_chapa|entrehierro_aumenta_caliente", "falla_bomba_gasolina", "P0335", "NO", "SI", "Bomba de gasolina quemada o con baja presion", "L3 dilatación de soporte incrementa entrehierro en caliente.")

    # =========================================================================
    # CLASE 22: Sistema EVAP (40 casos: 10 L1, 15 L2, 15 L3)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G22-L1-01", CLASE_22, "L1", "El carro se pone muy pesado para arrancar justo después de tanquear gasolina.", "COTIDIANO", "post_tanqueo", "dificultad_arranque_post_tanqueo", "", "", "SI", "NO", "", "L1 arranque pesado tras llenar tanque.")
    agregar("G22-L1-02", CLASE_22, "L1", "Hola, siento un olor fuerte a gasolina cruda dentro del carro al manejar.", "WHATSAPP", "marcha", "olor_gasolina_habitaculo", "", "", "SI", "NO", "", "L1 olor a vapores de nafta en habitáculo.")
    agregar("G22-L1-03", CLASE_22, "L1", "Se encendió el Check Engine y me dijeron que hay una fuga pequeña de vapores.", "COTIDIANO", "diagnostico", "check_engine|fuga_pequena_vapores", "", "", "SI", "NO", "", "L1 aviso de fuga menor de emisiones.")
    agregar("G22-L1-04", CLASE_22, "L1", "Al abrir la tapa de la gasolina suena como si destapara una gaseosa con mucha presión.", "COTIDIANO", "apertura_tapa", "succion_fuerte_tapa_gasolina", "", "", "SI", "NO", "", "L1 despresurización audible en tapa.")
    agregar("G22-L1-05", CLASE_22, "L1", "El ralentí se vuelve inestable y tiembla solo cuando el tanque está completamente lleno.", "TALLER", "tanque_lleno_ralenti", "ralenti_inestable_tanque_lleno", "", "", "SI", "NO", "", "L1 inestabilidad asociada a nivel de combustible.")
    agregar("G22-L1-06", CLASE_22, "L1", "Aparece un código de purga incorrecta del sistema de emisiones en el escáner.", "TECNICO", "diagnostico", "codigo_purga_incorrecta_evap", "", "", "SI", "NO", "", "L1 código genérico de purga EVAP.")
    agregar("G22-L1-07", CLASE_22, "L1", "Siento un ruidito como de golpeteo rápido tac-tac-tac cerca del motor al acelerar suave.", "COTIDIANO", "aceleracion_suave", "ruido_tac_tac_rapido_valvula", "", "", "SI", "NO", "", "L1 conmutación audible de válvula de purga.")
    agregar("G22-L1-08", CLASE_22, "L1", "Se prendio la luz del motor y huele a nafta por la llanta trasera derecha.", "ERROR_ORTOGRAFICO", "inspeccion_trasera", "luz_motor|olor_nafta_llanta_trasera", "", "", "SI", "NO", "", "L1 olor en zona de canister con ortografía informal.")
    agregar("G22-L1-09", CLASE_22, "L1", "Buenas, llené el tanque a tope y cuando salí del grifo el carro casi se apaga.", "WHATSAPP", "salida_grifo", "casi_se_apaga_post_llenado", "", "", "SI", "NO", "", "L1 ahogo inmediato post-llenado.")
    agregar("G22-L1-10", CLASE_22, "L1", "Presurización o depresión fuera de rango detectada en el depósito de combustible.", "TECNICO", "monitoreo_evap", "presion_deposito_fuera_rango", "", "", "SI", "NO", "", "L1 reporte técnico de presión en tanque.")

    # --- L2 (15 casos) ---
    agregar("G22-L2-01", CLASE_22, "L2", "Tras llenar el tanque en el grifo el motor demora 10 segundos en arrancar tosiendo y ahogado; la válvula de purga de canister se quedó trabada abierta succionando vapores crudos.", "COTIDIANO", "post_tanqueo_completo", "arranque_largo_ahogado|valvula_purga_trabada_abierta", "falla_bomba_combustible", "", "NO", "SI", "Falla en regulador de presion de combustible o diafragma roto", "L2 válvula de purga abierta ahoga tras tanquear vs regulador.")
    agregar("G22-L2-02", CLASE_22, "L2", "Código P0441 por flujo incorrecto de purga EVAP; al desconectar la manguera de la válvula en ralentí se siente succión constante cuando el solenoide debería estar cerrado.", "TECNICO", "prueba_succion_valvula_purga", "dtc_p0441|succion_constante_ralenti|solenoide_deberia_cerrar", "falla_iac", "P0441", "NO", "SI", "Cuerpo de aceleracion o valvula IAC sucia", "L2 succión constante en ralentí con P0441.")
    agregar("G22-L2-03", CLASE_22, "L2", "Olor penetrante a vapores de gasolina en el habitáculo; se inspeccionó el canister de carbón activado ubicado sobre el eje trasero encontrándose la carcasa plástica rajada por impacto de piedra.", "TALLER", "inspeccion_canister_trasero", "olor_vapores_gasolina|canister_carcasa_rajada_piedra", "fuga_linea_freno", "", "NO", "NO", "", "L2 canister perforado por piedra genera olor.")
    agregar("G22-L2-04", CLASE_22, "L2", "DTC P0455 de fuga grande detectada en el sistema de emisiones evaporativas; la tapa del tanque de combustible tiene la junta de goma cuarteada y no logra sellar herméticamente.", "COTIDIANO", "inspeccion_tapa_gasolina", "dtc_p0455|tapa_gasolina_junta_cuarteada|sin_sello_hermetico", "fuga_tanque_combustible", "P0455", "NO", "NO", "", "L2 código P0455 por junta de tapa cuarteada.")
    agregar("G22-L2-05", CLASE_22, "L2", "Hola maestro, el auto tiembla en ralentí y el escáner muestra ajuste de combustible negativo en -18%; al estrangular la manguera que viene del canister el motor empareja de inmediato.", "WHATSAPP", "prueba_estrangulamiento_manguera", "ltft_menos_18|estrangular_manguera_canister_empareja", "inyectores_goteando", "", "NO", "SI", "Inyectores sucios o filtro de combustible obstruido", "L2 prueba de pinzamiento de manguera EVAP empareja motor.")
    agregar("G22-L2-06", CLASE_22, "L2", "DTC P0442 de pequeña fuga en el sistema EVAP; la prueba con máquina de humo a 0.5 psi reveló escape leve de humo por la válvula de ventilación vent valve del canister.", "TECNICO", "prueba_humo_evap", "dtc_p0442|fuga_humo_vent_valve_canister", "falla_sensor_oxigeno", "P0442", "NO", "SI", "Falla en sensor de oxigeno o mezcla rica", "L2 fuga pequeña P0442 localizada con máquina de humo.")
    agregar("G22-L2-07", CLASE_22, "L2", "El auto arranca bien en frío pero si cargo combustible con el motor apagado luego no enciende hasta el tercer intento botando humo negro y olor a nafta cruda.", "COTIDIANO", "arranque_post_llenado", "no_enciende_post_tanqueo|humo_negro_olor_nafta", "falla_motor_arranque", "", "NO", "SI", "Falla en sistema Flex / Bi-combustible (Alcohol/Etanol)", "L2 ahogo exclusivo post-tanqueo vs sistema Flex.")
    agregar("G22-L2-08", CLASE_22, "L2", "Mi carro jalonea en minimo y sale codigo P0440 en el escaner. La tapa de gasolina esta bien apretada pero huele a gasolina fresca por la cajuela cuando hace calor.", "ERROR_ORTOGRAFICO", "dias_calurosos", "dtc_p0440|jaloneo_minimo|olor_gasolina_cajuela_calor", "falla_bomba_gasolina", "P0440", "NO", "NO", "", "L2 código P0440 con olor en cajuela en días de calor.")
    agregar("G22-L2-09", CLASE_22, "L2", "La válvula solenoide de purga tiene la bobina eléctrica en cortocircuito arrojando código P0443; al medir resistencia con multímetro marca 0.5 ohms (especificación 25 a 35 ohms).", "TECNICO", "medicion_resistencia_valvula_purga", "dtc_p0443|resistencia_0_5_ohms_corto|especificacion_30_ohms", "falla_inyector", "P0443", "NO", "NO", "", "L2 bobina de válvula de purga en corto P0443.")
    agregar("G22-L2-10", CLASE_22, "L2", "Al retirar la tapa del tanque de gasolina se escucha un fuerte soplido de vacío que hace crujir el tanque de chapa; la válvula de alivio bidireccional del canister está obstruida.", "TALLER", "inspeccion_tanque_deformado", "vacio_excesivo_crujido_tanque|valvula_alivio_canister_tapada", "falla_bomba_tanque", "", "NO", "NO", "", "L2 colapso por vacío excesivo en tanque de combustible.")
    agregar("G22-L2-11", CLASE_22, "L2", "Buenas maestro, en el taller me dijeron que tengo código P0446. Revisaron el filtro de carbón que va abajo y está lleno de carbón suelto que se metió a las mangueras de aire.", "WHATSAPP", "inspeccion_carbón_suelto", "dtc_p0446|canister_carbon_desgranado_mangueras", "falla_filtro_gasolina", "P0446", "NO", "NO", "", "L2 carbón activado desgranado viaja por las líneas EVAP.")
    agregar("G22-L2-12", CLASE_22, "L2", "El sensor de presión del tanque de combustible FTP reporta voltaje fijo de 4.8V; el módulo PCM no puede ejecutar la prueba automática de estanqueidad nocturna.", "TECNICO", "diagnostico_sensor_ftp", "sensor_ftp_4_8v_fijo|no_ejecuta_monitor_estanqueidad", "falla_sensor_map", "", "NO", "NO", "", "L2 sensor de presión de tanque FTP averiado.")
    agregar("G22-L2-13", CLASE_22, "L2", "Ralentí muy acelerado a 1200 rpm en caliente con código P0171; al desconectar la manguera de purga del múltiple y taponarla con el dedo el motor baja inmediatamente a 750 rpm.", "TALLER", "prueba_tapon_dedo_purga", "dtc_p0171|ralenti_1200_cae_750rpm_taponando_purga", "fuga_multiple_admision", "P0171", "NO", "SI", "Falla en sensor de oxigeno o mezcla rica", "L2 entrada falsa de aire a través de purga EVAP.")
    agregar("G22-L2-14", CLASE_22, "L2", "El cliente reclama que el surtidor de gasolina se dispara y corta a cada rato al intentar tanquear; la línea de ventilación de recarga del canister está taponada con lodo de carretera.", "COTIDIANO", "carga_combustible_corta", "surtidor_dispara_continuo|linea_ventilacion_taponada_lodo", "falla_aforador", "", "NO", "NO", "", "L2 surtidor de gasolina dispara por ventilación tapada.")
    agregar("G22-L2-15", CLASE_22, "L2", "DTC P0456 de fuga muy pequeña; prueba de vacío manual en la válvula de purga demuestra que fuga 2 inHg en 30 segundos debido a asiento de goma endurecido.", "TECNICO", "prueba_vacio_valvula_purga", "dtc_p0456|valvula_purga_fuga_2inhg|asiento_endurecido", "falla_sensor_map", "P0456", "NO", "NO", "", "L2 fuga de vacío marginal en asiento de purga con P0456.")

    # --- L3 (15 casos) ---
    agregar("G22-L3-01", CLASE_22, "L3", "Vehículo ingresa con queja de dificultad severa de encendido tras cargar combustible en la estación de servicio. El motor arranca ahogado con fuerte olor a nafta cruda y cabeceo prolongado de 2 minutos. Escáner registra DTC P0441 (Incorrect Purge Flow). En prueba de banco con bomba de vacío manual (Mityvac) la electroválvula de purga EVAP desenergizada no retiene vacío fugando libremente por asiento trabado con granos de carbón del canister. Al desconectar la manguera hacia el múltiple y sellarla el arranque es instantáneo.", "TECNICO", "prueba_mityvac_banco_purga", "dtc_p0441|valvula_purga_no_retiene_vacio|granos_carbon_asiento|arranque_ahogado_post_tanqueo", "falla_regulador_presion", "P0441", "NO", "SI", "Falla en regulador de presion de combustible o diafragma roto", "L3 Mityvac confirma válvula de purga trabada abierta por granos de carbón.")
    agregar("G22-L3-02", CLASE_22, "L3", "DTC P0455 (Gross EVAP Leak Detected). Se presurizó el sistema de combustible con máquina de humo y nitrógeno a 0.5 psi según procedimiento OEM. Se observó densa columna de humo escapando por la boca de llenado debido a fisura longitudinal en el gollete plástico del cuello de tanque y sello de la tapa deformado. Los inyectores pulverizan conforme y la presión de rampa se mantiene en 3.5 bar estables sin caídas.", "TALLER", "maquina_humo_nitrogeno_0_5psi", "dtc_p0455|humo_escapa_cuello_tanque_fisurado|sello_tapa_deformado|presion_combustible_3_5bar_ok", "falla_bomba_gasolina", "P0455", "NO", "SI", "Bomba de gasolina quemada o con baja presion", "L3 máquina de humo confirma fuga masiva en gollete con presión de combustible OK.")
    agregar("G22-L3-03", CLASE_22, "L3", "El cliente ingresa por ralentí oscilante entre 600 y 1100 rpm y código P0172 (System Too Rich). Los valores de corrección de combustible a corto plazo STFT marcan -22% fijo en ralentí pero al desconectar la electroválvula de purga de canister y obturar la toma del múltiple de admisión los trims se normalizan a +1.5%. La prueba de resistencia eléctrica de la electroválvula arrojó 31 ohms normal pero la corredera interna está atascada abierta.", "TECNICO", "evaluacion_trims_stft_purga", "dtc_p0172|stft_menos_22_corrige_a_mas_1_5_obturando|corredera_purga_atascada", "inyectores_goteando", "P0172", "NO", "SI", "Inyectores sucios o filtro de combustible obstruido", "L3 normalización de STFT de -22% a +1.5% al obturar purga descarta inyectores.")
    agregar("G22-L3-04", CLASE_22, "L3", "Olor penetrante a hidrocarburos en la parte trasera izquierda tras estacionar el vehículo bajo el sol. Se desmontó el canister de carbón activado encontrándose la carcasa saturada de gasolina líquida pesando 2.8 kg (peso de referencia 1.1 kg) debido a que el cliente acostumbra llenar el tanque hasta el rebose forzado, habiendo inundado el lecho de carbón.", "TALLER", "pesaje_canister_inundado", "canister_pesa_2_8kg_vs_1_1kg|inundado_gasolina_liquida|rebose_tanque", "fuga_tanque_combustible", "", "NO", "NO", "", "L3 canister inundado pesa 2.8 kg por llenar hasta el rebose.")
    agregar("G22-L3-05", CLASE_22, "L3", "Hola maestro, cada vez que lleno el tanque en el grifo el carro no quiere prender, tose feo y tira humo negro. Le cambiaron la bomba de gasolina y las bujías pero sigue igualito. En el taller me desconectaron la manguera que va de una válvula del motor al tanque y el carro prendió al toque. Me dijeron que la válvula de purga se quedó pegada abierta.", "WHATSAPP", "arranque_fallido_post_tanqueo_bomba_nueva", "no_prende_al_tanquear|bomba_bujias_nuevas_persiste|desconectar_purga_prende", "falla_bomba_gasolina", "", "NO", "SI", "Bomba de gasolina quemada o con baja presion", "L3 bomba y bujías nuevas no resuelven; desconectar purga soluciona.")
    agregar("G22-L3-06", CLASE_22, "L3", "DTC P0442 (Small Leak Detected). La prueba de caída de presión con nitrógeno a 14 inH2O mostró pérdida de 5 inH2O en 45 segundos. Utilizando detector ultrasónico de fugas y máquina de humo se localizó una microfisura en la manguera de teflón corrugada que conecta el canister con la válvula de purga justo en la curva sobre el puente trasero.", "TECNICO", "prueba_caida_presion_nitrogeno", "dtc_p0442|caida_5inh2o_45seg|microfisura_manguera_corrugada", "falla_sensor_oxigeno", "P0442", "NO", "SI", "Falla en sensor de oxigeno o mezcla rica", "L3 caída de presión en inH2O localiza microfisura con detector ultrasónico.")
    agregar("G22-L3-07", CLASE_22, "L3", "Ralentí inestable con DTC P0440. Se monitoreó con escáner el sensor de presión del tanque de combustible FTP durante la prueba de purga forzada: el sensor permanece fijo en 2.45V sin registrar la depresión de -1.5 kPa generada por la apertura de purga. La comprobación física con manómetro digital constató que el tanque sí genera depresión de -1.6 kPa, diagnosticándose sensor FTP dañado.", "TECNICO", "monitoreo_sensor_ftp_vs_manometro", "dtc_p0440|sensor_ftp_2_45v_fijo|depresion_real_menos_1_6kpa", "falla_valvula_purga", "P0440", "NO", "NO", "", "L3 manómetro confirma depresión real en tanque mientras sensor FTP marca fijo.")
    agregar("G22-L3-08", CLASE_22, "L3", "Mi carro jalonea en parado y prende el check con codigo P0441. En el taller probaron la valvulita que va en el multiple y le soplaron aire apagada y pasa el aire derechito sin corriente. Le pusieron valvula nueva que no deja pasar aire y se borro la falla quedando el minimo parejito.", "ERROR_ORTOGRAFICO", "prueba_soplado_valvula", "dtc_p0441|valvula_sopla_derechito_apagada|valvula_nueva_sella", "falla_cuerpo_aceleracion", "P0441", "NO", "SI", "Cuerpo de aceleracion o valvula IAC sucia", "L3 prueba de soplado confirma válvula permeable sin corriente con ortografía informal.")
    agregar("G22-L3-09", CLASE_22, "L3", "Deformación plástica severa del tanque de combustible con reducción de capacidad de 55 a 42 litros. La válvula de ventilación de ventilación (Canister Vent Valve) quedó atascada en posición cerrada por barro acumulado en el filtro atmosférico, provocando que la succión del motor colapsara el tanque hacia adentro por vacío descontrolado.", "TALLER", "colapso_tanque_combustible", "tanque_colapsado_55_a_42l|vent_valve_trabada_cerrada_barro|vacio_extremo", "falla_aforador_combustible", "", "NO", "NO", "", "L3 tanque colapsado por succión descontrolada con vent valve trabada.")
    agregar("G22-L3-10", CLASE_22, "L3", "DTC P0456 (Very Small Leak) recurrente en vehículo sedán. Al aplicar prueba de humo de alta densidad con tinte fluorescente UV se detectó pérdida microscópica en el puerto de prueba de servicio Schrader de la línea EVAP en el vano motor por junta tórica de vitón mordida y envejecida.", "TECNICO", "tinte_fluorescente_uv_evap", "dtc_p0456|puerto_schrader_fuga_uv|junta_viton_mordida", "falla_sensor_oxigeno", "P0456", "NO", "SI", "Falla en sensor de oxigeno o mezcla rica", "L3 luz UV detecta fuga microscópica en puerto Schrader con P0456.")
    agregar("G22-L3-11", CLASE_22, "L3", "Buenas tardes, cada vez que le pongo nafta al carro tengo que pisar el acelerador a fondo para que prenda y bota una humareda negra que huele a pura nafta. Me revisaron el regulador de presión de nafta y está perfecto sin nafta en el vacío. El problema era la purga del canister que chupa gasolina al llenar el tanque.", "WHATSAPP", "arranque_acelerador_fondo_post_tanqueo", "humo_negro_post_tanqueo|regulador_presion_vacio_seco|purga_canister_chupa", "falla_regulador_presion", "", "NO", "SI", "Falla en regulador de presion de combustible o diafragma roto", "L3 vacío de regulador seco descarta diafragma roto y confirma purga EVAP.")
    agregar("G22-L3-12", CLASE_22, "L3", "DTC P0443 referente al circuito del solenoide de purga EVAP. La prueba osciloscópica en el terminal de control revela ausencia de pico inductivo de colapso de campo magnético (flyback voltage de 0V en lugar de 45V habituales), confirmando diodo interno en cortocircuito dentro de la electroválvula.", "TECNICO", "analisis_flyback_osciloscopio", "dtc_p0443|flyback_0v_sin_pico_inductivo|diodo_interno_corto", "falla_cableado_ecu", "P0443", "NO", "NO", "", "L3 análisis osciloscópico de flyback voltage en solenoide de purga.")
    agregar("G22-L3-13", CLASE_22, "L3", "El motor presenta tironeos y mezcla pobre P0171 a velocidad constante de 90 km/h. La computadora activa el ciclo de trabajo de la válvula de purga al 40% pero el caudalímetro MAF no detecta el incremento de masa correspondiente debido a que la línea de purga se taponó por fragmentos de carbón del filtro canister.", "TALLER", "linea_purga_obstruida_carbon", "dtc_p0171|linea_purga_obstruida_carbon|duty_40_sin_flujo_maf", "falla_sensor_maf", "P0171", "NO", "SI", "Falla en sensor de oxigeno o mezcla rica", "L3 línea de purga taponada de carbón genera divergencia en MAF.")
    agregar("G22-L3-14", CLASE_22, "L3", "DTC P0455 intermitente. La prueba de actuación guiada de la válvula de ventilación vent valve con escáner muestra que consume 0.9 amperios correctos pero no cierra herméticamente el conducto debido a que una pequeña piedra quedó atrapada en el asiento del obturador plástico.", "TECNICO", "prueba_actuador_vent_valve", "dtc_p0455|consumo_0_9a_ok|asiento_obturador_piedra_atrapada", "falla_valvula_purga", "P0455", "NO", "NO", "", "L3 consumo eléctrico normal pero traba mecánica por piedra en vent valve.")
    agregar("G22-L3-15", CLASE_22, "L3", "Al realizar prueba de emisiones de escape en ralentí el analizador de 4 gases reporta hidrocarburos no quemados HC en 380 ppm excesivos. Al desconectar la manguera de purga del canister el valor de HC cae instantáneamente a 28 ppm dentro de norma técnica, comprobándose enriquecimiento parasitario por purga defectuosa.", "TALLER", "analisis_4_gases_hc_purga", "hc_380ppm_cae_a_28ppm_desconectando_purga|enriquecimiento_parasitario", "falla_catalizador", "", "NO", "SI", "Convertidor catalitico ineficiente u obstruido (DTC P0420 / P0430)", "L3 analizador de gases demuestra caída de HC de 380 a 28 ppm al desconectar purga.")

    # =========================================================================
    # CLASE 23: Convertidor catalítico P0420 / P0430 (40 casos: 10 L1, 15 L2, 15 L3)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G23-L1-01", CLASE_23, "L1", "Se prendió la luz del motor en el tablero pero el carro anda normal y no falla.", "COTIDIANO", "marcha_normal", "check_engine|marcha_normal", "", "", "SI", "NO", "", "L1 testigo de motor encendido sin pérdida de potencia.")
    agregar("G23-L1-02", CLASE_23, "L1", "Hola, el carro no tiene fuerza en subida y huele a azufre o huevo podrido.", "WHATSAPP", "subida", "falta_fuerza_subida|olor_huevo_podrido", "", "", "SI", "NO", "", "L1 olor a azufre y pérdida de fuerza.")
    agregar("G23-L1-03", CLASE_23, "L1", "Siento un cascabel o piedritas sueltas sonando dentro del tubo de escape al acelerar.", "COTIDIANO", "aceleracion", "cascabel_piedritas_escape", "", "", "SI", "NO", "", "L1 cerámica desprendida en escape.")
    agregar("G23-L1-04", CLASE_23, "L1", "El auto está atorado y no pasa de 80 km/h por más que pise a fondo el pedal.", "COTIDIANO", "velocidad_maxima", "auto_atorado|no_pasa_80kmh", "", "", "SI", "NO", "", "L1 restricción severa de escape.")
    agregar("G23-L1-05", CLASE_23, "L1", "Se prende el Check Engine por baja eficiencia del catalizador en banco 1.", "TECNICO", "diagnostico", "baja_eficiencia_catalizador_banco1", "", "", "SI", "NO", "", "L1 reporte técnico de eficiencia de catalizador.")
    agregar("G23-L1-06", CLASE_23, "L1", "El múltiple de escape se pone rojo vivo cuando manejo de noche en carretera.", "TALLER", "carretera_nocturna", "multiple_rojo_vivo", "", "", "SI", "NO", "", "L1 sobrecalentamiento por contrapresión.")
    agregar("G23-L1-07", CLASE_23, "L1", "Reboté en la revisión técnica por exceso de monóxido de carbono e hidrocarburos.", "COTIDIANO", "inspeccion_tecnica", "rechazo_gases_co_hc", "", "", "SI", "NO", "", "L1 reprobación de gases de escape.")
    agregar("G23-L1-08", CLASE_23, "L1", "Mi carro perdio fuerza de golpe y el escape suena ahogado shhhhh.", "ERROR_ORTOGRAFICO", "aceleracion", "perdida_fuerza|escape_ahogado_shhh", "", "", "SI", "NO", "", "L1 escape ahogado con ortografía informal.")
    agregar("G23-L1-09", CLASE_23, "L1", "Buenas, cambié el sensor de oxígeno de abajo y a los dos días volvió a prender la luz del check.", "WHATSAPP", "post_cambio_sensor", "luz_check_vuelve_tras_sensor_nuevo", "", "", "SI", "NO", "", "L1 persistencia de testigo tras sensor O2.")
    agregar("G23-L1-10", CLASE_23, "L1", "Contrapresión de gases de escape por encima de la tolerancia admisible.", "TECNICO", "plena_carga", "contrapresion_escape_elevada", "", "", "SI", "NO", "", "L1 reporte técnico de contrapresión.")

    # --- L2 (15 casos) ---
    agregar("G23-L2-01", CLASE_23, "L2", "Código P0420 encendido permanente; el auto no pierde nada de potencia ni tironea, pero en datos en vivo la sonda posterior oscila al mismo ritmo que la delantera indicando catalizador ineficiente.", "COTIDIANO", "marcha_velocidad_crucero", "dtc_p0420|potencia_normal|sonda_posterior_oscila_igual", "falla_potencia", "P0420", "NO", "SI", "Falla en sensor de oxigeno o mezcla rica", "L2 catalizador ineficiente sin pérdida de potencia vs sensor O2.")
    agregar("G23-L2-02", CLASE_23, "L2", "El motor no supera las 3000 rpm en autopista y se siente completamente ahogado; al soltar el sensor de oxígeno frontal para que el escape respire el motor acelera libremente.", "TALLER", "prueba_desahogo_sensor", "no_supera_3000rpm|ahogado|respira_retirando_sensor_o2", "falla_turbo", "", "NO", "SI", "Fuga en mangueras de intercooler o turbocompresor danado", "L2 desahogo retirando sonda frontal confirma obstrucción de catalizador.")
    agregar("G23-L2-03", CLASE_23, "L2", "Fuerte olor a huevo podrido (ácido sulfhídrico) por el tubo de escape al acelerar en subida y sonido de latas sueltas en la petaca del catalizador al golpear con la mano.", "COTIDIANO", "aceleracion_subida", "olor_huevo_podrido|latas_sueltas_petaca_catalizador", "falla_silenciador_escape", "", "NO", "NO", "", "L2 olor sulfuroso y cascabel cerámico suelto.")
    agregar("G23-L2-04", CLASE_23, "L2", "Código P0430 en banco 2 de motor V6; la temperatura medida con pirómetro a la salida del catalizador es inferior a la entrada (220°C salida vs 280°C entrada), indicando nula reacción química.", "TECNICO", "termometria_infrarroja_catalizador", "dtc_p0430|temperatura_salida_menor_entrada|sin_reaccion_quimica", "falla_sensor_oxigeno", "P0430", "NO", "SI", "Falla en sensor de oxigeno o mezcla rica", "L2 termometría infrarroja confirma catalizador inactivo.")
    agregar("G23-L2-05", CLASE_23, "L2", "Hola maestro, el carro perdió fuerza en carretera y el múltiple de escape se puso al rojo vivo en la noche. En el taller me dicen que el panal cerámico del catalizador se derritió tapando el tubo.", "WHATSAPP", "carretera_nocturna", "multiple_rojo_vivo|panal_ceramico_derretido_tapado", "falla_bomba_gasolina", "", "NO", "SI", "Bomba de gasolina quemada o con baja presion", "L2 catalizador fundido al rojo vivo vs bomba de gasolina.")
    agregar("G23-L2-06", CLASE_23, "L2", "Prueba de contrapresión de escape conectando manómetro en el puerto de la sonda O2 delantera: marca 4.0 psi a 2500 rpm superando el límite máximo permitido de 1.25 psi.", "TECNICO", "medicion_contrapresion_escape", "contrapresion_4_0psi|limite_maximo_1_25psi|ahogo_motor", "falla_escape_perforado", "", "NO", "NO", "", "L2 contrapresión medida de 4.0 psi en catalizador tapado.")
    agregar("G23-L2-07", CLASE_23, "L2", "El auto tironea al acelerar a fondo y el vacío del múltiple de admisión cae progresivamente de 18 inHg a 8 inHg al mantener acelerado a 3000 rpm por taponamiento del escape.", "TALLER", "prueba_vacio_admision_3000rpm", "vacio_cae_18_a_8inhg|escape_taponado|tironeo", "falla_valvula_iac", "", "NO", "SI", "Cuerpo de aceleracion o valvula IAC sucia", "L2 decaimiento de vacío a 8 inHg por contrapresión.")
    agregar("G23-L2-08", CLASE_23, "L2", "Mi carro no pasa de 70 km por hora en subida y en el tablero tiene la luz del motor con P0420. Le cambiaron bujias y filtro de nafta pero sigue atorado el tubo.", "ERROR_ORTOGRAFICO", "subida_autopista", "no_pasa_70kmh|dtc_p0420|atorado_post_bujias_filtro", "falla_filtro_nafta", "P0420", "NO", "SI", "Inyectores sucios o filtro de combustible obstruido", "L2 P0420 atorado tras bujías y filtro con ortografía informal.")
    agregar("G23-L2-09", CLASE_23, "L2", "Inspección boroscópica a través del orificio del sensor O2 superior: se observa la colmena cerámica frontal del catalizador fundida y vitrificada por exceso de combustible tras fallos de encendido.", "TECNICO", "boroscopia_catalizador", "colmena_ceramica_fundida_vitrificada|misfires_previos", "falla_valvulas_escape", "", "NO", "SI", "Perdida de compresion en cilindro por valvulas pisadas o anillos desgastados", "L2 boroscopía confirma fusión de colmena cerámica.")
    agregar("G23-L2-10", CLASE_23, "L2", "Al dar golpes con un mazo de goma en la petaca del convertidor catalítico suena un sonajero seco de trozos cerámicos desprendidos que obstruyen la salida de gases.", "COTIDIANO", "inspeccion_bajos", "sonajero_trozos_ceramicos_catalizador|mazo_goma", "ruido_suspension", "", "NO", "NO", "", "L2 fractura interna del sustrato cerámico.")
    agregar("G23-L2-11", CLASE_23, "L2", "Buenas, el carro anda suave y no falla nada pero no pasa la inspección técnica por gases altos y tiene el P0420 prendido. Los sensores de oxígeno son nuevos.", "WHATSAPP", "revision_tecnica_gases", "p0420_gases_altos|sensores_oxigeno_nuevos|marcha_suave", "falla_sensor_oxigeno", "P0420", "NO", "SI", "Falla en sensor de oxigeno o mezcla rica", "L2 catalizador ineficiente con sensores nuevos.")
    agregar("G23-L2-12", CLASE_23, "L2", "DTC P0420 y P0430 simultáneos en motor en V; la tasa de almacenamiento de oxígeno calculada por la ECU es del 12% (especificación mínima eficiente 60%).", "TECNICO", "calculo_almacenamiento_oxigeno", "dtc_p0420_p0430|almacenamiento_oxigeno_12_porciento", "falla_sensor_map", "P0420", "NO", "NO", "", "L2 capacidad de almacenamiento de O2 degradada al 12%.")
    agregar("G23-L2-13", CLASE_23, "L2", "El motor perdió repris de golpe y sopla aire con esfuerzo por la boca del escape; se desmontó el tramo intermedio y el monolito del catalizador se partió en bloques bloqueando el cono.", "TALLER", "desarme_escape_intermedio", "monolito_partido_en_bloques|cono_bloqueado|perdida_repris", "falla_embrague", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L2 monolito fracturado bloquea cono de salida.")
    agregar("G23-L2-14", CLASE_23, "L2", "El vehículo consume un 15% más de combustible con código P0420; no hay fugas de vacío en admisión y las bujías queman parejo pero los gases salen con olor picante.", "COTIDIANO", "consumo_elevado", "consumo_alto_15|dtc_p0420|olor_picante_escape", "falla_inyectores", "P0420", "NO", "SI", "Inyectores sucios o filtro de combustible obstruido", "L2 sobreconsumo con olor picante y P0420.")
    agregar("G23-L2-15", CLASE_23, "L2", "Temperatura de gases antes del catalizador marca 450°C pero la petaca exterior no supera los 150°C por pérdida total de metales nobles catalíticos en vehículo con 230,000 km.", "TECNICO", "temperatura_pirómetro_laser", "temp_entrada_450c_petaca_150c|agotamiento_metales_nobles", "falla_escape_roto", "P0420", "NO", "NO", "", "L2 agotamiento químico de metales nobles por kilometraje.")

    # --- L3 (15 casos) ---
    agregar("G23-L3-01", CLASE_23, "L3", "Vehículo ingresa con luz de Check Engine encendida y código DTC P0420 (Catalyst System Efficiency Below Threshold Bank 1). El cliente no percibe pérdida de potencia ni tironeos en ningún régimen de marcha. En escáner automotriz a 2500 rpm en crucero la sonda de oxígeno preconversor B1S1 oscila normalmente entre 0.15V y 0.85V con ciclo rápido de 1.2 Hz, pero la sonda postconversor B1S2 oscila de forma idéntica en fase con amplitud de 0.2V a 0.8V reflejando nula capacidad de retención de oxígeno del convertidor. No existen fugas en el múltiple de escape.", "TECNICO", "analisis_oscilograma_b1s1_vs_b1s2", "dtc_p0420|sonda_post_oscila_igual_a_pre_sonda|potencia_normal|sin_fugas_escape", "falla_sensor_oxigeno", "P0420", "NO", "SI", "Falla en sensor de oxigeno o mezcla rica", "L3 oscilograma downstream en espejo con upstream confirma catalizador ineficiente.")
    agregar("G23-L3-02", CLASE_23, "L3", "El vehículo no supera los 65 km/h ni las 2800 rpm en subida sintiéndose severamente estrangulado. Se conectó manómetro de contrapresión calibrado en la rosca del sensor de oxígeno superior registrando 3.8 psi en ralentí y disparándose a 8.5 psi al acelerar a 2500 rpm (especificación máxima admitida 1.25 psi). Al retirar el catalizador y observar a contraluz se constató que las celdas cerámicas centrales están fundidas y selladas en un bloque vidrioso compacto por detonaciones previas de combustible.", "TALLER", "medicion_contrapresion_8_5psi", "contrapresion_8_5psi_a_2500rpm|celdas_fundidas_bloque_vidrioso|no_supera_65kmh", "falla_actuador_turbo", "", "NO", "SI", "Falla en actuador de turbocompresor o VGT en motores alemanes TSI / TFSI", "L3 manómetro marca 8.5 psi confirmando obstrucción física total del panal.")
    agregar("G23-L3-03", CLASE_23, "L3", "Toyota Corolla con 190,000 km presenta DTC P0420. La prueba termográfica con pirómetro infrarrojo en carretera estabilizada a 80 km/h muestra 380°C en el cono de entrada y 350°C en el cono de salida del catalizador. En un convertidor eficiente la reacción exotérmica de oxidación debe generar un gradiente positivo de al menos 40°C a 70°C mayor en la salida (esperado >420°C), demostrándose agotamiento químico del sustrato de platino y rodio.", "TECNICO", "termografia_gradiente_exotermico", "dtc_p0420|temp_entrada_380c_salida_350c|gradiente_negativo_agotado", "falla_sensor_oxigeno_deficiente", "P0420", "NO", "SI", "Falla en sensor de oxigeno o mezcla rica", "L3 gradiente térmico negativo descarta reacción exotérmica y confirma P0420.")
    agregar("G23-L3-04", CLASE_23, "L3", "Sonido de cascabeleo metálico agudo audible en el piso central bajo desaceleración a 2000 rpm. Al desmontar el catalizador cayeron trozos triangulares de cerámica fragmentada equivalentes al 40% del núcleo que taponaban el cono de salida hacia el silenciador intermedio. El sensor de oxígeno posterior tiene la puntera golpeada por fragmentos cerámicos.", "TALLER", "desprendimiento_ceramica_cono", "cascabeleo_piso_desaceleracion|fragmentos_ceramica_cono_salida|puntera_o2_golpeada", "ruido_caja_cambios", "", "NO", "SI", "Rodajes de caja mecanica o diferencial gastados", "L3 40% de cerámica fracturada tapona cono de escape.")
    agregar("G23-L3-05", CLASE_23, "L3", "Hola maestro, tengo un Nissan Tiida. En carretera de noche el múltiple de escape se puso al rojo vivo y el carro no pasaba de 80 km/h sintiéndose pesadísimo. En el taller me sacaron el catalizador y parecía un tapón de vidrio quemado por dentro. Le pusieron catalizador nuevo y recuperó toda la fuerza al acelerar.", "WHATSAPP", "multiple_rojo_vivo_tiida", "multiple_rojo_vivo|no_pasa_80kmh|catalizador_tapon_vidrio_derretido", "falla_bomba_gasolina", "", "NO", "SI", "Bomba de gasolina quemada o con baja presion", "L3 relato WhatsApp de múltiple al rojo vivo por panal vitrificado.")
    agregar("G23-L3-06", CLASE_23, "L3", "DTC P0430 en banco 2 de motor V8 4.6L. Se verificó con analizador de gases de escape de 4 componentes: en banco 1 los hidrocarburos marcan 18 ppm y CO 0.08%, mientras que en banco 2 los hidrocarburos trepan a 220 ppm y CO a 1.2% a temperatura de régimen. La prueba de balance de cilindros y compresión no arrojó fallos en banco 2 descartándose misfire de cilindro.", "TECNICO", "analisis_4_gases_banco1_vs_banco2", "dtc_p0430|hc_220ppm_co_1_2_en_banco2|balance_cilindros_ok", "falla_misfire_cilindros", "P0430", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L3 analizador de 4 gases compara banco 1 vs banco 2 confirmando catalizador.")
    agregar("G23-L3-07", CLASE_23, "L3", "Pérdida de potencia en pendiente pronunciada con olor intenso a gas sulfhídrico. Se midió vacío en el múltiple de admisión: en ralentí marca 19 inHg normal pero al mantener el motor acelerado a 2500 rpm el vacío decae continuamente hasta 9 inHg por contrapresión acumulada en el catalizador obstruido. Al desacoplar la brida de escape previa al catalizador el vacío se mantuvo en 20 inHg sostenidos.", "TALLER", "prueba_vacio_sostenido_desacople", "vacio_decae_19_a_9inhg|desacople_escape_mantiene_20inhg|olor_sulfhidrico", "falla_valvula_iac", "", "NO", "SI", "Cuerpo de aceleracion o valvula IAC sucia", "L3 desacople de brida restaura vacío de 9 a 20 inHg descartando motor.")
    agregar("G23-L3-08", CLASE_23, "L3", "Mi auto no acelera en subida botando codigo P0420 y en el taller le sacaron el primer sensor de oxigeno para probar. Con el hueco del sensor destapado el carro volvio a tener pique y acelerar bien porque salio todo el aire ahogado que el catalizador tapado no dejaba escapar.", "ERROR_ORTOGRAFICO", "desahogo_por_hueco_sensor", "dtc_p0420|desahogo_hueco_sensor_recupera_pique|catalizador_tapado", "falla_cuerpo_mariposa", "P0420", "NO", "SI", "Cuerpo de aceleracion o valvula IAC sucia", "L3 desahogo por orificio de sensor O2 confirma taponamiento con ortografía informal.")
    agregar("G23-L3-09", CLASE_23, "L3", "DTC P0420 recurrente tras sustitución de ambas sondas lambda delantera y trasera con repuestos originales OEM. La prueba de enriquecimiento forzado con spray en admisión provocó salto a 0.9V en ambas sondas con respuesta inmediata de 80 ms, confirmando que los sensores son perfectamente funcionales y que el catalizador no almacena oxígeno.", "TECNICO", "prueba_enriquecimiento_forzado_o2", "dtc_p0420|sondas_oem_nuevas_responden_80ms|catalizador_no_almacena_oxigeno", "falla_sensor_oxigeno_defectuoso", "P0420", "NO", "SI", "Falla en sensor de oxigeno o mezcla rica", "L3 respuesta de 80 ms en sondas nuevas descarta sensores y confirma P0420.")
    agregar("G23-L3-10", CLASE_23, "L3", "El vehículo ingresó tras circular 300 km con bobina de encendido del cilindro 2 fallando (código P0302 previo). Aunque se cambió la bobina nueva el auto quedó sin fuerza en subida. Al inspeccionar el convertidor catalítico con endoscopio se constató que la gasolina cruda del cilindro 2 se quemó dentro del catalizador fundiendo el centro de la colmena cerámica.", "TALLER", "endoscopia_post_misfire_bobina", "catalizador_fundido_post_misfire_p0302|sin_fuerza_post_bobina_nueva", "falla_bobinas_encendido", "P0420", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L3 endoscopía constata catalizador fundido por misfire previo de bobina.")
    agregar("G23-L3-11", CLASE_23, "L3", "Buenas tardes, en el taller me dijeron que tengo código P0420. El carro corre normal en pista lisa pero no pasa de 80 en subida y huele a huevo podrido. El mecánico midió la presión en el caño de escape y dice que marca 5 libras de contrapresión cuando no debe pasar de libra y media.", "WHATSAPP", "medicion_5_libras_contrapresion", "dtc_p0420|contrapresion_5_libras_vs_1_5|olor_huevo_podrido|no_pasa_80", "falla_turbo", "P0420", "NO", "SI", "Fuga en mangueras de intercooler o turbocompresor danado", "L3 5 libras de contrapresión vs 1.5 límite descarta turbo.")
    agregar("G23-L3-12", CLASE_23, "L3", "Análisis de tiempo de respuesta de monitor de catalizador en PCM: el valor de correlación cruzada entre sensor 1 y sensor 2 alcanza 0.88 (catalizador agotado) cuando en condición óptima debe ser inferior a 0.20. La compresión del motor está en 170 psi y el consumo de aceite es nulo, descartando envenenamiento por fósforo de aceite.", "TECNICO", "correlacion_cruzada_monitores_pcm", "dtc_p0420|correlacion_cruzada_0_88_vs_0_20|compresion_170psi_ok", "desgaste_anillos_aceite", "P0420", "NO", "SI", "Consumo de aceite por desgaste de anillos o retenes", "L3 correlación cruzada 0.88 con motor sin consumo de aceite.")
    agregar("G23-L3-13", CLASE_23, "L3", "El catalizador emite un zumbido sibilante de alta frecuencia al acelerar a 3000 rpm. Se desmontó el catalizador y al soplar aire a presión con pistola neumática por la entrada el manómetro registró taponamiento del 70% del área de flujo por carbonilla y residuo cerámico desgranado.", "TALLER", "prueba_flujo_pistola_neumatica", "zumbido_sibilante_3000rpm|taponamiento_70_flujo_aire", "fuga_escape", "", "NO", "NO", "", "L3 prueba de flujo neumático detecta 70% de área obstruida.")
    agregar("G23-L3-14", CLASE_23, "L3", "DTC P0420 con parámetros congelados a 98 km/h en autopista con motor a temperatura de régimen. La prueba de estanqueidad de escape con máquina de humo descartó fisuras en el colector o juntas antes de las sondas, garantizando que no existe ingreso de aire ambiente que falsee la lectura de las sondas lambda.", "TECNICO", "prueba_humo_colector_estanqueidad", "dtc_p0420|estanqueidad_colector_ok_sin_fugas|sondas_sin_aire_falso", "fuga_multiple_escape", "P0420", "NO", "NO", "", "L3 prueba de humo descarta tomas de aire parásitas previas a sondas.")
    agregar("G23-L3-15", CLASE_23, "L3", "El vehículo ingresó por olor nauseabundo a azufre y pérdida del 50% de rendimiento dinámico. Se constató que el convertidor catalítico secundario bajo el piso sufrió colapso estructural interno por impacto en el protector inferior, aprisionando el sustrato cerámico contra la pared exterior de acero.", "TALLER", "impacto_bajos_colapso_catalizador", "impacto_protector_inferior|colapso_sustrato_ceramico|perdida_50_potencia", "dano_silenciador", "", "NO", "NO", "", "L3 impacto mecánico en bajos colapsa sustrato cerámico.")

    return casos
