"""
Generador de registros de Lote 05 - Parte 2: Clases 24 a 26.
- Clase 24: Falla en regulador de presion de combustible o diafragma roto
- Clase 25: Falla en circuito o solenoide de inyector individual (DTC P0201 - P0208)
- Clase 26: Perdida de compresion en cilindro por valvulas pisadas o anillos desgastados

Total: 120 registros (40 por clase: 10 L1, 15 L2, 15 L3).
"""

CLASE_24 = "Falla en regulador de presion de combustible o diafragma roto"
CLASE_25 = "Falla en circuito o solenoide de inyector individual (DTC P0201 - P0208)"
CLASE_26 = "Perdida de compresion en cilindro por valvulas pisadas o anillos desgastados"

def obtener_casos_24_26(offset=121):
    casos = []
    idx = offset

    def agregar(id_grupo, clase, nivel, texto, tipo_lenguaje, cond, sint_pres, sint_neg, dtc, req_preg, es_cont, cl_cont, obs):
        nonlocal idx
        reg_id = f"F10-L05-{idx:04d}"
        idx += 1
        casos.append({
            "id": reg_id,
            "id_grupo": id_grupo,
            "clase_objetivo": clase,
            "macro_sistema": "MOTOR",
            "nivel_informacion": nivel,
            "texto_usuario": texto.strip(),
            "tipo_lenguaje": tipo_lenguaje,
            "condicion_operacion": cond.strip(),
            "sintomas_presentes": sint_pres.strip(),
            "sintomas_negados": sint_neg.strip(),
            "dtc": dtc.strip(),
            "requiere_pregunta": req_preg.strip(),
            "es_contrastivo": es_cont.strip(),
            "clase_contrastiva": cl_cont.strip(),
            "fuente": "SINTETICO_IA",
            "observaciones": obs.strip()
        })

    # =========================================================================
    # CLASE 24: Regulador de presión de combustible (40 casos: 10 L1, 15 L2, 15 L3)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G24-L1-01", CLASE_24, "L1", "El carro bota mucho humo negro por el escape y gasta demasiada gasolina.", "COTIDIANO", "marcha", "humo_negro_exceso_consumo", "", "", "SI", "NO", "", "L1 exceso de consumo y humo negro.")
    agregar("G24-L1-02", CLASE_24, "L1", "Hola, al apagar el motor y querer prenderlo a los diez minutos le cuesta un montón arrancar.", "WHATSAPP", "arranque_caliente_10min", "arranque_dificil_caliente", "", "", "SI", "NO", "", "L1 ahogo térmico en reposo.")
    agregar("G24-L1-03", CLASE_24, "L1", "Siento un olor penetrante a nafta cruda saliendo por la admisión del motor.", "COTIDIANO", "ralenti", "olor_nafta_admision", "", "", "SI", "NO", "", "L1 olor a gasolina en admisión.")
    agregar("G24-L1-04", CLASE_24, "L1", "Las bujías salen completamente negras llenas de hollín y el motor cabecea.", "TALLER", "inspeccion_bujias", "bujias_negras_hollin|cabeceo", "", "", "SI", "NO", "", "L1 bujías ahogadas de hollín.")
    agregar("G24-L1-05", CLASE_24, "L1", "Se encendió el Check Engine y el auto tironea en subida como si le faltara fuerza.", "COTIDIANO", "subida", "check_engine|tironeo_subida", "", "", "SI", "NO", "", "L1 tironeo bajo demanda.")
    agregar("G24-L1-06", CLASE_24, "L1", "El escáner arroja código de mezcla rica permanente en todos los cilindros.", "TECNICO", "diagnostico", "mezcla_rica_permanente", "", "", "SI", "NO", "", "L1 reporte genérico de mezcla rica.")
    agregar("G24-L1-07", CLASE_24, "L1", "La presión de combustible en la rampa no se mantiene y se cae al apagar.", "TALLER", "apagado", "perdida_presion_residual_rampa", "", "", "SI", "NO", "", "L1 pérdida de presión residual.")
    agregar("G24-L1-08", CLASE_24, "L1", "Mi auto tose feo en minimo y moja las bujias de gasolina.", "ERROR_ORTOGRAFICO", "ralenti", "tose_minimo|moja_bujias_gasolina", "", "", "SI", "NO", "", "L1 bujías empapadas con ortografía informal.")
    agregar("G24-L1-09", CLASE_24, "L1", "Buenas, cambié la bomba de gasolina y la presión sigue subiendo demasiado alta.", "WHATSAPP", "post_cambio_bomba", "presion_demasiado_alta_post_bomba", "", "", "SI", "NO", "", "L1 sobrepresión tras bomba nueva.")
    agregar("G24-L1-10", CLASE_24, "L1", "Sobrealimentación no controlada de combustible a través de la línea neumática de vacío.", "TECNICO", "marcha", "combustible_en_linea_vacio", "", "", "SI", "NO", "", "L1 reporte técnico de fuga por vacío.")

    # --- L2 (15 casos) ---
    agregar("G24-L2-01", CLASE_24, "L2", "Al retirar la manguera de vacío del regulador de presión de combustible montado en el riel brota gasolina líquida continua; el diafragma interno está roto inundando el múltiple.", "COTIDIANO", "inspeccion_manguera_vacio", "gasolina_brota_manguera_vacio|diafragma_roto", "falla_bomba_gasolina", "", "NO", "SI", "Bomba de gasolina quemada o con baja presion", "L2 gasolina en manguera de vacío confirma diafragma roto vs bomba.")
    agregar("G24-L2-02", CLASE_24, "L2", "El auto arranca bien frío pero en caliente demora 15 segundos tosiendo con humo negro; la presión residual del riel se cae de 3.2 bar a 0 bar en 10 segundos tras apagar el motor.", "TALLER", "prueba_presion_residual", "arranque_largo_caliente_humo_negro|presion_cae_a_cero_10seg", "falla_inyectores", "", "NO", "SI", "Inyectores sucios o filtro de combustible obstruido", "L2 caída de presión residual ahoga en caliente vs inyectores sucios.")
    agregar("G24-L2-03", CLASE_24, "L2", "Código P0172 (System Too Rich); la presión de gasolina en el riel marca 5.8 bar cuando la especificación es de 3.0 bar debido a que el regulador se trabó cerrado.", "TECNICO", "medicion_manometro_riel", "dtc_p0172|presion_5_8bar_vs_3_0bar|regulador_trabado_cerrado", "falla_sensor_oxigeno", "P0172", "NO", "SI", "Falla en sensor de oxigeno o mezcla rica", "L2 sobrepresión a 5.8 bar genera código P0172.")
    agregar("G24-L2-04", CLASE_24, "L2", "Hola maestro, el carro tironea en subida y le falta fuerza. Medimos presión y tiene solo 1.5 bar; ahorcamos la manguera de retorno y la presión salta a 5 bar confirmando regulador vencido.", "WHATSAPP", "prueba_ahorcamiento_retorno", "presion_1_5bar|ahorcar_retorno_sube_5bar|falta_fuerza_subida", "bomba_gasolina_agotada", "", "NO", "SI", "Bomba de gasolina quemada o con baja presion", "L2 pinzado de retorno descarta bomba y señala regulador vencido.")
    agregar("G24-L2-05", CLASE_24, "L2", "Las 4 bujías salen completamente empapadas de gasolina cruda al sacar el contacto; el combustible se escurre por el conducto de vacío directo a las válvulas de admisión.", "TALLER", "bujias_empapadas_contacto", "4_bujias_empapadas_gasolina|combustible_por_vacio", "falla_bobinas_encendido", "", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L2 combustible por toma de vacío empapa bujías vs bobinas.")
    agregar("G24-L2-06", CLASE_24, "L2", "DTC P0171 por mezcla pobre bajo aceleración plena; el regulador no incrementa la presión al caer el vacío del motor quedándose estancado en 2.0 bar.", "TECNICO", "aceleracion_vacio_regulador", "dtc_p0171|sin_compensacion_vacio|presion_estancada_2bar", "falla_sensor_maf", "P0171", "NO", "SI", "Falla en sensor de oxigeno o mezcla rica", "L2 falta de enriquecimiento por vacío causa P0171.")
    agregar("G24-L2-07", CLASE_24, "L2", "El nivel de aceite de motor aumentó y huele intensamente a gasolina; el diafragma perforado del regulador descarga combustible que escurre por los cilindros al cárter.", "COTIDIANO", "aceite_contaminado_gasolina", "nivel_aceite_subio_olor_gasolina|diafragma_perforado", "desgaste_anillos", "", "NO", "SI", "Consumo de aceite por desgaste de anillos o retenes", "L2 dilución de aceite por diafragma perforado vs aros.")
    agregar("G24-L2-08", CLASE_24, "L2", "Mi carro jalonea feo y bota humo negro en relenti con codigo P0172. Desconecte la manguerita de aire del regulador y salio un chorrito de nafta con presion.", "ERROR_ORTOGRAFICO", "chorro_manguerita_vacio", "dtc_p0172|humo_negro_relenti|chorrito_nafta_manguerita", "falla_sensor_map", "P0172", "NO", "NO", "", "L2 chorro de gasolina por manguera de vacío con ortografía informal.")
    agregar("G24-L2-09", CLASE_24, "L2", "Presión de combustible oscila erráticamente entre 1.0 y 4.0 bar al compás de las pulsaciones de inyección por rotura del resorte interno del amortiguador de rampa.", "TECNICO", "oscilacion_manometro_amortiguador", "presion_oscila_1_a_4bar|resorte_interno_roto", "falla_bomba_combustible", "", "NO", "NO", "", "L2 oscilación de presión por rotura de resorte interno.")
    agregar("G24-L2-10", CLASE_24, "L2", "El motor se ahoga y se apaga al llegar a un semáforo; al desconectar la manguera de vacío del regulador el ralentí se estabiliza de golpe al cesar el ingreso de gasolina cruda.", "TALLER", "desconexion_prueba_ralenti", "ahogo_ralenti|desconectar_vacio_estabiliza_motor", "falla_cuerpo_aceleracion", "", "NO", "SI", "Cuerpo de aceleracion o valvula IAC sucia", "L2 desconexión de manguera de vacío estabiliza el ralentí.")
    agregar("G24-L2-11", CLASE_24, "L2", "Buenas maestro, el carro huele fuertísimo a gasolina cruda y tira humo negro. Le cambiaron los inyectores pensando que estaban goteando pero el diafragma del riel estaba roto.", "WHATSAPP", "post_cambio_inyectores", "inyectores_nuevos_persiste_humo_negro|diafragma_riel_roto", "inyectores_defectuosos", "", "NO", "SI", "Inyectores sucios o filtro de combustible obstruido", "L2 inyectores nuevos no resolvieron; diafragma roto era la causa.")
    agregar("G24-L2-12", CLASE_24, "L2", "Prueba de hermeticidad de rampa de inyección: al aplicar vacío de 15 inHg con bomba manual al puerto de control del regulador, el diafragma no retiene y cae a cero de inmediato.", "TECNICO", "prueba_vacio_regulador_mityvac", "diafragma_no_retiene_15inhg|cae_a_cero_inmediato", "falla_sensor_map", "", "NO", "NO", "", "L2 prueba de bomba de vacío confirma diafragma perforado.")
    agregar("G24-L2-13", CLASE_24, "L2", "En autopista el carro se queda sin empuje al pasar de 80 km/h; la presión de combustible cae a 1.2 bar porque la válvula de retorno del regulador tiene el asiento desgastado.", "COTIDIANO", "autopista_alta_velocidad", "perdida_empuje_80kmh|presion_cae_1_2bar|asiento_retorno_gastado", "falla_filtro_gasolina", "", "NO", "SI", "Inyectores sucios o filtro de combustible obstruido", "L2 caída de presión en alta por asiento desgastado vs filtro.")
    agregar("G24-L2-14", CLASE_24, "L2", "DTC P0172 constante con valores de corrección LTFT en -25% al tope negativo; el motor quema tanta gasolina que los gases pican los ojos en el taller.", "TALLER", "gases_escape_pican_ojos", "dtc_p0172|ltft_menos_25_tope|gases_pican_ojos", "falla_sensor_oxigeno", "P0172", "NO", "SI", "Falla en sensor de oxigeno o mezcla rica", "L2 saturación de LTFT a -25% por combustible parásito.")
    agregar("G24-L2-15", CLASE_24, "L2", "Al dar marcha tras 20 minutos de reposo el motor hace explosiones sordas por exceso de combustible acumulado en el colector de admisión proveniente del regulador.", "COTIDIANO", "arranque_post_reposo_20min", "explosiones_sordas_colector|exceso_combustible_reposo", "falla_distribucion", "", "NO", "SI", "Faja o cadena de distribucion destensada o con salto de punto", "L2 acumulación de gasolina en reposo vs distribución.")

    # --- L3 (15 casos) ---
    agregar("G24-L3-01", CLASE_24, "L3", "Vehículo ingresa con queja de dificultad extrema de arranque en caliente tras 10 a 30 minutos de estar apagado, requiriendo hasta 20 segundos de marcha y expulsando densa humareda negra por el escape. Se conectó manómetro de combustible en el riel registrando 3.2 bar en marcha pero al apagar el motor la presión cae a 0 bar en 8 segundos. Al desconectar la manguera de vacío del regulador de presión se constató goteo constante de combustible líquido por el pezón de vacío hacia el múltiple. Los inyectores fueron probados en banco a 4 bar confirmando estanqueidad absoluta sin goteo.", "TECNICO", "diagnostico_caida_presion_goteo_vacio", "presion_cae_3_2_a_0bar_8seg|gasolina_por_pezon_vacio|inyectores_estancos_banco", "inyectores_goteando", "P0172", "NO", "SI", "Inyectores sucios o filtro de combustible obstruido", "L3 inyectores estancos en banco confirman que la fuga de presión es por el vacío del regulador.")
    agregar("G24-L3-02", CLASE_24, "L3", "DTC P0172 permanente con correcciones de combustible a corto plazo STFT en -25% y largo plazo LTFT en -24.2%. Se midió la presión en la rampa de inyectores registrándose 6.2 bar continuos (presión nominal OEM 3.0 bar con vacío y 3.5 bar sin vacío). La línea de retorno al tanque se verificó soplando con aire a presión encontrándose 100% permeable sin obstrucciones, diagnosticándose válvula de retorno del regulador trabada mecánicamente en posición cerrada.", "TALLER", "medicion_sobrepresion_6_2bar", "dtc_p0172|presion_6_2bar_vs_3_5bar_oem|retorno_tanque_libre|regulador_trabado_cerrado", "retorno_tanque_obstruido", "P0172", "NO", "NO", "", "L3 retorno al tanque libre descarta cañería taponada y confirma regulador trabado a 6.2 bar.")
    agregar("G24-L3-03", CLASE_24, "L3", "En subida pronunciada a 3000 rpm el vehículo tironea severamente y pierde el 40% de potencia con DTC P0171 (System Too Lean). El manómetro conectado al riel marca solo 1.4 bar bajo aceleración a fondo (especificación 3.5 bar). Se realizó la prueba de pinzamiento momentáneo de la manguera de retorno de combustible y la presión saltó instantáneamente a 5.5 bar con empuje vigoroso de la electrobomba, demostrando que la bomba y el filtro están en óptimo estado y que el resorte del regulador está vencido.", "TECNICO", "prueba_pinzado_retorno_5_5bar", "dtc_p0171|presion_1_4bar_salta_5_5bar_pinzando_retorno|bomba_filtro_ok", "bomba_gasolina_agotada", "P0171", "NO", "SI", "Bomba de gasolina quemada o con baja presion", "L3 pinzamiento salta a 5.5 bar descartando bomba quemada y confirmando resorte vencido.")
    agregar("G24-L3-04", CLASE_24, "L3", "El cliente reclama que el cárter se llenó de gasolina, habiendo subido el nivel de aceite en la varilla 3 centímetros por encima del máximo con viscosidad degradada. La compresión de los 4 cilindros se midió registrando 165 psi parejos descartando fuga por aros. Al aplicar 15 inHg de vacío con bomba Mityvac en el regulador de presión de combustible la aguja cae instantáneamente a cero y el diafragma aspiró 30 ml de gasolina al interior de la bomba de vacío.", "TALLER", "prueba_mityvac_aspiracion_combustible", "aceite_contaminado_gasolina|compresion_165psi_ok|mityvac_aspira_gasolina_diafragma", "desgaste_anillos_piston", "", "NO", "SI", "Consumo de aceite por desgaste de anillos o retenes", "L3 Mityvac aspira nafta líquida y compresión de 165 psi descarta desgaste de anillos.")
    agregar("G24-L3-05", CLASE_24, "L3", "Hola maestro, tengo un Honda Civic. El carro me ahogaba en caliente y gastaba un tanque en dos días tirando humo negro. Le cambiaron sensor de oxígeno y sensor de temperatura pero seguía la falla. El mecánico desconectó la manguerita chiquita que va del riel al múltiple de admisión y estaba chorreando gasolina para adentro del motor; le cambiaron el regulador de presión y quedó sedita.", "WHATSAPP", "chorro_gasolina_multiple_civic", "humo_negro_ahogo|sensores_nuevos_persiste|manguerita_chorreando_gasolina", "falla_sensor_oxigeno", "", "NO", "SI", "Falla en sensor de oxigeno o mezcla rica", "L3 relato WhatsApp de manguerita de vacío chorreando nafta tras cambio de sensores.")
    agregar("G24-L3-06", CLASE_24, "L3", "DTC P0172 en banco 1 y 2. En analizador de 4 gases el monóxido de carbono marca 5.8% y los hidrocarburos 650 ppm con factor lambda en 0.82. Se obturó la manguera de vacío del regulador de presión y se limpió el múltiple de admisión, normalizándose el factor lambda a 1.00 y CO a 0.15% inmediatamente tras sustituir el regulador de diafragma perforado.", "TECNICO", "analizador_gases_lambda_0_82", "dtc_p0172|co_5_8_lambda_0_82_corrige_a_1_00|diafragma_perforado", "falla_sensor_temperatura", "P0172", "NO", "SI", "Falla en sensor de oxigeno o mezcla rica", "L3 analizador de gases verifica corrección de lambda 0.82 a 1.00 tras cambiar regulador.")
    agregar("G24-L3-07", CLASE_24, "L3", "Prueba de respuesta dinámica de presión de combustible: al desconectar la manguera de vacío en ralentí la presión debe incrementarse de 2.8 a 3.5 bar (diferencial de 0.7 bar). El regulador instalado no produce variación alguna manteniéndose clavado en 2.1 bar en todo momento debido a incrustaciones de barniz gomoso que trabaron mecánicamente el vástago de la válvula interna.", "TALLER", "prueba_diferencial_vacio_regulador", "sin_variacion_presion_desconectando_vacio|clavado_2_1bar|vastago_trabado_barniz", "falla_bomba_combustible", "", "NO", "NO", "", "L3 prueba de desacople de vacío sin respuesta diferencial confirma vástago atascado.")
    agregar("G24-L3-08", CLASE_24, "L3", "Mi carro jalonea feo en subida y prende el check con codigo P0171 por mezcla pobre. En el taller le midieron la presion de gasolina y no subia de 20 libras; le ahorcaron el retorno con una pinza de presion y subio a 80 libras al toque. Con regulador de nafta nuevo quedo en 45 libras parejitas.", "ERROR_ORTOGRAFICO", "pinza_presion_retorno_80libras", "dtc_p0171|presion_20_sube_a_80libras_ahorcando|regulador_nuevo_45libras", "falla_bomba_gasolina", "P0171", "NO", "SI", "Bomba de gasolina quemada o con baja presion", "L3 prueba de pinza sube a 80 libras con ortografía informal.")
    agregar("G24-L3-09", CLASE_24, "L3", "Al acelerar de golpe en vacío el manómetro de combustible registra una caída instantánea de 3.2 a 1.1 bar con titubeo severo del motor. El diafragma de goma del regulador de presión presenta fatiga elástica con deformación permanente y microfisuras que no toleran los picos de caudal de los inyectores.", "TECNICO", "caida_transitoria_aceleracion_vacio", "caida_instantanea_3_2_a_1_1bar|fatiga_elastica_diafragma|microfisuras", "falla_filtro_combustible", "", "NO", "SI", "Inyectores sucios o filtro de combustible obstruido", "L3 fatiga elástica del diafragma provoca colapso de presión en transitorios.")
    agregar("G24-L3-10", CLASE_24, "L3", "Arranque muy pesado tras 15 minutos de estacionado. Al desmontar el múltiple de admisión se encontraron 40 ml de gasolina líquida acumulada en el fondo del plenum proveniente del tubo de vacío del regulador. Las bujías de los cilindros 2 y 3 (los más cercanos a la toma de vacío) se hallaron negras de carbón mientras las de los cilindros 1 y 4 quemaban marrón claro.", "TALLER", "gasolina_liquida_plenum_admision", "40ml_gasolina_plenum|bujias_2_y_3_negras_cercanas_toma|diafragma_roto", "falla_inyectores_goteo", "", "NO", "SI", "Inyectores sucios o filtro de combustible obstruido", "L3 bujías negras focalizadas en cilindros adyacentes a la toma de vacío confirman diafragma.")
    agregar("G24-L3-11", CLASE_24, "L3", "Buenas tardes, el carro pierde fuerza en autopista como si se quedara sin nafta. Me querían cambiar el módulo FSCM de la bomba pero medimos corriente y le llegan sus 12V perfectos a la bomba. El problema era el regulador de presión mecánico en la rampa que se venció el resorte y manda toda la nafta de vuelta al tanque.", "WHATSAPP", "descarte_modulo_fscm_vs_regulador", "corriente_12v_bomba_ok|fscm_ok|regulador_mecanico_resorte_vencido", "falla_modulo_bomba_fscm", "", "NO", "SI", "Falla en modulo de bomba de gasolina FSCM / PEM (Ford / Chevrolet)", "L3 voltaje y módulo FSCM OK descartan control electrónico y confirman regulador mecánico.")
    agregar("G24-L3-12", CLASE_24, "L3", "DTC P0172 constante. Medición osciloscópica de la señal del sensor de oxígeno preconversor: permanece clavada en 0.92V fija (mezcla ultra rica) y no conmuta ni desconectando los inyectores por el combustible líquido que sigue entrando desde el puerto de vacío del regulador averiado.", "TECNICO", "sonda_lambda_clavada_0_92v", "dtc_p0172|sonda_clavada_0_92v_incluso_sin_pulso|combustible_por_vacio", "falla_sensor_oxigeno", "P0172", "NO", "SI", "Falla en sensor de oxigeno o mezcla rica", "L3 sonda O2 clavada en 0.92V incluso sin pulso de inyección por combustible en vacío.")
    agregar("G24-L3-13", CLASE_24, "L3", "El motor tose y ratea al arrancar con fuerte olor a nafta. Se retiró el regulador de presión y se sometió a prueba de presión hidrostática en banco: a 1.0 bar de presión ya fuga combustible por la cámara de vacío neumática confirmando perforación completa de la membrana de caucho nitrilo NBR.", "TALLER", "prueba_hidrostatica_banco_1bar", "fuga_por_camara_vacio_a_1bar|perforacion_membrana_nbr", "falla_bomba_gasolina", "", "NO", "NO", "", "L3 banco hidrostático constata perforación de membrana NBR a 1 bar.")
    agregar("G24-L3-14", CLASE_24, "L3", "DTC P0171 por mezcla magra a 3500 rpm. El escáner muestra tiempo de inyección en 16 milisegundos al límite máximo de compensación pero la presión en el riel desciende progresivamente de 3.0 bar a 1.6 bar por asiento de bola del regulador descalibrado.", "TECNICO", "tiempo_inyeccion_16ms_presion_1_6bar", "dtc_p0171|tiempo_inyeccion_16ms_maximo|presion_cae_3_a_1_6bar|asiento_bola_descalibrado", "falla_inyectores", "P0171", "NO", "SI", "Inyectores sucios o filtro de combustible obstruido", "L3 tiempo de inyección en 16 ms no compensa caída a 1.6 bar en riel.")
    agregar("G24-L3-15", CLASE_24, "L3", "Al exigir el motor en subida de montaña se enciende Check Engine y el vehículo pierde reprís. La prueba de presión con manómetro glicerina conectado en derivación muestra oscilaciones violentas de la aguja con amplitud de 2.0 bar debido a resonancia y rotura de la lámina amortiguadora del regulador de presión.", "TALLER", "manometro_glicerina_oscilacion", "oscilacion_2_0bar_manometro_glicerina|lamina_amortiguadora_rota|perdida_repris", "falla_turbo", "", "NO", "SI", "Fuga en mangueras de intercooler o turbocompresor danado", "L3 oscilaciones de 2.0 bar en manómetro de glicerina descartan turbo.")

    # =========================================================================
    # CLASE 25: Circuito / solenoide de inyector individual (40 casos: 10 L1, 15 L2, 15 L3)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G25-L1-01", CLASE_25, "L1", "El motor tiembla muy fuerte en ralentí como si estuviera trabajando en 3 cilindros.", "COTIDIANO", "ralenti", "temblor_fuerte_motor_cojo", "", "", "SI", "NO", "", "L1 motor cojo en 3 cilindros.")
    agregar("G25-L1-02", CLASE_25, "L1", "Hola, se prendió el Check Engine y un inyector dejó de hacer el sonido de tic-tic.", "WHATSAPP", "marcha", "check_engine|inyector_sin_tic_tic", "", "", "SI", "NO", "", "L1 ausencia de conmutación acústica de inyector.")
    agregar("G25-L1-03", CLASE_25, "L1", "El carro perdió fuerza de golpe y el motor vibra en todo momento sin empuje.", "COTIDIANO", "marcha", "perdida_fuerza_vibracion_constante", "", "", "SI", "NO", "", "L1 fallo de potencia y vibración fija.")
    agregar("G25-L1-04", CLASE_25, "L1", "El escáner arrojó código de falla de circuito abierto en el inyector del cilindro.", "TECNICO", "diagnostico", "codigo_circuito_abierto_inyector", "", "", "SI", "NO", "", "L1 reporte genérico de circuito de inyector.")
    agregar("G25-L1-05", CLASE_25, "L1", "Tengo chispa perfecta en las 4 bujías pero un cilindro no está quemando nada.", "TALLER", "inspeccion_taller", "chispa_perfecta|cilindro_no_quema", "", "", "SI", "NO", "", "L1 cilindro inactivo con chispa OK.")
    agregar("G25-L1-06", CLASE_25, "L1", "Aparece un fallo de encendido que no se quita cambiando la bobina ni la bujía.", "COTIDIANO", "post_cambio_encendido", "falla_persiste_post_bobina_bujia", "", "", "SI", "NO", "", "L1 fallo persistente tras encendido.")
    agregar("G25-L1-07", CLASE_25, "L1", "Siento olor a combustible desparejo y el motor cabecea en subida.", "COTIDIANO", "subida", "cabeceo_subida|marcha_dispareja", "", "", "SI", "NO", "", "L1 cabeceo bajo carga.")
    agregar("G25-L1-08", CLASE_25, "L1", "Mi carro tiembla feo y prende la luz del motor en el tablero sin fuerza al acelerar.", "ERROR_ORTOGRAFICO", "aceleracion", "tiembla_feo|luz_motor|sin_fuerza", "", "", "SI", "NO", "", "L1 temblor y luz de motor con ortografía informal.")
    agregar("G25-L1-09", CLASE_25, "L1", "Buenas maestro, le desconecto la ficha a un inyector y el motor no hace ningún cambio.", "WHATSAPP", "prueba_desconexion_ficha", "desconectar_ficha_sin_cambio", "", "", "SI", "NO", "", "L1 desconexión de ficha no altera marcha.")
    agregar("G25-L1-10", CLASE_25, "L1", "Interrupción eléctrica en el circuito primario del actuador electromagnético de inyección.", "TECNICO", "diagnostico", "interrupcion_circuito_electromagnetico", "", "", "SI", "NO", "", "L1 reporte técnico de interrupción en solenoide.")

    # --- L2 (15 casos) ---
    agregar("G25-L2-01", CLASE_25, "L2", "Código P0201 de circuito de inyector 1 abierto; el motor tiembla severamente en 3 cilindros pero la bujía y la bobina del cilindro 1 tienen chispa potente.", "COTIDIANO", "ralenti", "dtc_p0201|circuito_inyector1_abierto|chispa_cilindro1_ok", "falla_chispa", "P0201", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L2 P0201 con chispa perfecta descarta fallo de encendido.")
    agregar("G25-L2-02", CLASE_25, "L2", "Al conectar la lámpara de prueba NOID en el conector del inyector 3 la luz no destella al dar arranque, mientras que en los otros 3 inyectores destella con normalidad.", "TALLER", "prueba_lampara_noid", "noid_no_destella_cilindro3|noid_otros_tres_ok", "falla_bomba_gasolina", "P0203", "NO", "SI", "Bomba de gasolina quemada o con baja presion", "L2 lámpara noid sin pulso en cilindro 3 vs bomba de gasolina.")
    agregar("G25-L2-03", CLASE_25, "L2", "Se midió la resistencia de la bobina del inyector del cilindro 2 arrojando circuito abierto infinito (especificación 12 a 16 ohms) confirmando solenoide cortado internamente.", "TECNICO", "medicion_resistencia_inyector", "resistencia_infinita_inyector2|especificacion_14_ohms", "inyector_sucio", "P0202", "NO", "SI", "Inyectores sucios o filtro de combustible obstruido", "L2 resistencia infinita confirma solenoide cortado vs inyector sucio.")
    agregar("G25-L2-04", CLASE_25, "L2", "Hola maestro, el escáner arroja P0204. Cambiamos bujías y bobinas nuevas pero el cilindro 4 sigue completamente muerto; al mover el cable del inyector 4 a veces agarra.", "WHATSAPP", "inspeccion_cableado_inyector4", "dtc_p0204|bujias_bobinas_nuevas_persiste|mover_cable_inyector4_conecta", "falla_bobinas", "P0204", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L2 falso contacto en cableado de inyector 4 con P0204.")
    agregar("G25-L2-05", CLASE_25, "L2", "DTC P0202 en motor 4 cilindros; el inyector 2 funciona bien en frío pero al alcanzar 85°C la bobina se dilata térmicamente y corta la continuidad eléctrica.", "TECNICO", "corte_termico_inyector", "dtc_p0202|corte_termico_85c_bobina_inyector", "falla_compresion", "P0202", "NO", "SI", "Perdida de compresion en cilindro por valvulas pisadas o anillos desgastados", "L2 corte térmico exclusivo del solenoide a 85°C vs compresión.")
    agregar("G25-L2-06", CLASE_25, "L2", "El conector plástico del inyector del cilindro 1 tiene la traba rota y los terminales sulfatados provocando caída de tensión y fallo permanente con código P0201.", "TALLER", "inspeccion_conector_inyector1", "dtc_p0201|conector_traba_rota_sulfatado|caida_tension", "falla_bujia", "P0201", "NO", "NO", "", "L2 conector roto y sulfatado genera código P0201.")
    agregar("G25-L2-07", CLASE_25, "L2", "El motor cabecea en marcha y pierde fuerza; se intercambiaron los inyectores 1 y 2 entre sí y el código de falla migró de P0201 a P0202 demostrando que la falla es el inyector.", "COTIDIANO", "prueba_intercambio_inyectores", "dtc_migra_p0201_a_p0202_intercambio", "falla_computadora", "P0202", "NO", "NO", "", "L2 prueba cruzada de inyectores migra el DTC.")
    agregar("G25-L2-08", CLASE_25, "L2", "Mi carro cojea feo en tres cilindros y en el escaner sale codigo P0203 de inyector. Le sacaron la bujia del tres y sale limpiecita y seca porque no le entra ni gota de nafta.", "ERROR_ORTOGRAFICO", "inspeccion_bujia_cilindro3", "dtc_p0203|bujia_cilindro3_limpia_seca|sin_nafta", "falla_chispa", "P0203", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L2 bujía seca confirma falta de inyección con ortografía informal.")
    agregar("G25-L2-09", CLASE_25, "L2", "DTC P0204 referente a circuito del inyector 4; al medir voltaje en el conector llegan 12V de batería correctos pero la línea de control a masa no conmuta desde la ECU.", "TECNICO", "medicion_voltajes_inyector4", "dtc_p0204|12v_bateria_ok|linea_masa_no_conmuta", "falla_rele_principal", "P0204", "NO", "NO", "", "L2 12V presentes pero sin pulso de masa desde ECU.")
    agregar("G25-L2-10", CLASE_25, "L2", "El inyector del cilindro 3 presenta resistencia de solo 1.2 ohms en cortocircuito parcial; la ECU entra en protección desactivando el banco de inyección por sobrecorriente.", "TALLER", "resistencia_1_2_ohms_corto", "resistencia_1_2_ohms_corto|proteccion_sobrecorriente_ecu", "falla_bomba_gasolina", "P0203", "NO", "SI", "Bomba de gasolina quemada o con baja presion", "L2 inyector en corto a 1.2 ohms desactiva banco por protección.")
    agregar("G25-L2-11", CLASE_25, "L2", "Buenas maestro, el carro tiembla como licuadora y prende Check con P0202. La compresión del motor está en 170 psi parejita en los 4 cilindros pero el inyector 2 no dispara.", "WHATSAPP", "compresion_170psi_ok_p0202", "dtc_p0202|compresion_170psi_pareja|inyector2_no_dispara", "falla_valvula_pisada", "P0202", "NO", "SI", "Perdida de compresion en cilindro por valvulas pisadas o anillos desgastados", "L2 compresión perfecta de 170 psi descarta válvula pisada.")
    agregar("G25-L2-12", CLASE_25, "L2", "DTC P0201 intermitente que aparece únicamente al pasar sobre baches o adoquines; el arnés de cables del inyector 1 rozaba contra la chapa del soporte del alternador.", "TECNICO", "inspeccion_roce_arnes", "dtc_p0201_baches|roce_arnes_soporte_alternador", "falla_sensor_ckp", "P0201", "NO", "NO", "", "L2 rozamiento de arnés de inyector 1 en baches.")
    agregar("G25-L2-13", CLASE_25, "L2", "El motor ratea con violencia en aceleración fuerte; al probar con multímetro la bobina del inyector 4 marca 48 ohms fuera de tolerancia de 12 a 16 ohms impidiendo la apertura.", "TALLER", "resistencia_48_ohms_elevada", "resistencia_48_ohms_elevada|no_abre_inyector4|rateo", "falla_inyector_sucio", "P0204", "NO", "SI", "Inyectores sucios o filtro de combustible obstruido", "L2 resistencia elevada a 48 ohms impide apertura del solenoide.")
    agregar("G25-L2-14", CLASE_25, "L2", "Al dar contacto el inyector del cilindro 1 se queda pegado abierto eléctricamente por transistor MOSFET de la ECU en cortocircuito a masa permanente inundando el cilindro.", "TECNICO", "mosfet_ecu_corto_masa", "inyector1_pegado_abierto_continuo|mosfet_corto_masa", "regulador_presion_roto", "P0201", "NO", "SI", "Falla en regulador de presion de combustible o diafragma roto", "L2 transistor de ECU en corto mantiene inyector abierto.")
    agregar("G25-L2-15", CLASE_25, "L2", "Vehículo pierde un cilindro en caliente con código P0203; al enfriar el inyector con aire a presión el motor empareja de inmediato confirmando fallo térmico en el devanado.", "COTIDIANO", "enfriamiento_inyector_aire", "dtc_p0203_caliente|aire_enfria_inyector_empareja", "falla_bobina", "P0203", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L2 enfriamiento con aire reanima devanado de inyector 3.")

    # --- L3 (15 casos) ---
    agregar("G25-L3-01", CLASE_25, "L3", "Vehículo ingresa con marcha en 3 cilindros y vibración severa en ralentí con DTC P0201 (Injector Circuit Open - Cylinder 1) y P0301 (Misfire Cylinder 1). Se realizaron pruebas de encendido con osciloscopio constatando que la bobina COP del cilindro 1 entrega 32 kV con tiempo de quemado de 1.4 ms normal y bujía en buen estado. Se conectó pinza amperimétrica en el cable de control del inyector 1 registrando 0.0 amperios durante el intento de arranque mientras que el inyector 2 consume 1.1 amperios con pico inductivo de 65V. La resistencia interna del solenoide del inyector 1 arrojó circuito abierto infinito en multímetro.", "TECNICO", "osciloscopio_y_pinza_amperimetrica_inyector1", "dtc_p0201_p0301|chispa_32kv_tiempo_1_4ms_ok|consumo_0_0a_pinza|resistencia_infinita_inyector1", "falla_bobina_encendido", "P0201", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L3 oscilograma y pinza confirman 0 amperios y circuito abierto con chispa de 32 kV impecable.")
    agregar("G25-L3-02", CLASE_25, "L3", "El cliente ingresa por motor cojo en caliente tras 20 minutos de autopista con código P0203. Se midió la compresión mecánica de los 4 cilindros arrojando 175 psi parejos en todos los cilindros. Al retirar la rampa de inyección y medir la resistencia de los 4 inyectores a 20°C todos marcan 14.2 ohms; sin embargo al calentar el inyector 3 con pistola de calor a 80°C su resistencia se dispara a infinito cortando el circuito interno. Al enfriarse recupera los 14 ohms.", "TALLER", "prueba_termica_resistencia_inyector3", "dtc_p0203|compresion_175psi_pareja|resistencia_14_ohms_sube_a_infinito_a_80c", "falla_compresion_valvulas", "P0203", "NO", "SI", "Perdida de compresion en cilindro por valvulas pisadas o anillos desgastados", "L3 compresión 175 psi descarta válvulas; prueba térmica demuestra apertura de bobina a 80°C.")
    agregar("G25-L3-03", CLASE_25, "L3", "DTC P0204 referente a circuito del inyector del cilindro 4. En prueba con lámpara NOID conectada en el arnés se constató ausencia total de destello. Se midió tensión con multímetro en el pin de alimentación del conector registrando 12.4V de batería correctos; la comprobación de continuidad en el cable de masa controlada desde el pin 2 del conector del inyector hasta el pin 45 del conector de la ECU arrojó cable cortado por fricción bajo el tubo de admisión.", "TECNICO", "rastreo_continuidad_arnes_ecu", "dtc_p0204|noid_inactiva|12_4v_alimentacion_ok|cable_masa_ecu_cortado", "falla_computadora_pcm", "P0204", "NO", "NO", "", "L3 12.4V presentes pero continuidad cortada en cable de masa hacia ECU.")
    agregar("G25-L3-04", CLASE_25, "L3", "Motor 4 cilindros tiembla fuertemente con códigos P0202 y P0302. Se intercambió la bobina 2 al cilindro 1 y la bujía 2 al cilindro 4 manteniéndose el fallo firme en el cilindro 2 con P0202 activo. Se midió la resistencia del inyector 2 registrando 0.8 ohms en cortocircuito entre espiras en lugar de 14.5 ohms normales, provocando que el circuito de protección de corriente de la ECU inhiba el disparo de ese canal.", "TALLER", "intercambio_bobinas_bujias_p0202", "dtc_p0202_p0302|falla_firme_en_cilindro2_tras_intercambio|resistencia_0_8_ohms_corto", "falla_bobinas_encendido", "P0202", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L3 rotación cruzada de bobinas y bujías descarta encendido y confirma inyector en 0.8 ohms.")
    agregar("G25-L3-05", CLASE_25, "L3", "Hola maestro, tengo un Toyota Yaris. El carro empezó a temblar feo en tres cilindros de la nada y no tiene fuerza. En el taller le cambiaron bujías nuevas de iridio y la bobina del cilindro 1 pero seguía temblando igualito. Le pusieron el foco noid al enchufe del inyector 1 y no prendía la luz; el mecánico encontró el cable del inyector pelado y quebrado por las ratas debajo del plástico.", "WHATSAPP", "cable_inyector_mordido_yaris", "tiembla_en_3_cilindros|bujias_bobina_nueva_persiste|noid_no_prende|cable_mordido_ratas", "falla_bobinas_encendido", "", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L3 relato WhatsApp de lámpara noid inactiva por cable quebrado tras cambio de encendido.")
    agregar("G25-L3-06", CLASE_25, "L3", "Captura de forma de onda de corriente y tensión del inyector 2 con osciloscopio: al recibir el comando de masa la corriente alcanza 1.05 amperios pero el pico de fuerza contraelectromotriz (back-EMF flyback) al cortar el circuito alcanza solo 12V en lugar de los 60V a 80V esperados, confirmando cortocircuito parcial en las espiras del solenoide que debilita el campo magnético y no logra levantar la aguja.", "TECNICO", "analisis_flyback_voltaje_inyector2", "back_emf_solo_12v_vs_70v|cortocircuito_parcial_espiras|no_levanta_aguja", "falla_inyector_sucio", "P0202", "NO", "SI", "Inyectores sucios o filtro de combustible obstruido", "L3 flyback de solo 12V confirma cortocircuito entre espiras en solenoide.")
    agregar("G25-L3-07", CLASE_25, "L3", "El vehículo ingresó con vibración permanente y código P0203. Se desmontaron los 4 inyectores y se colocaron en banco de pruebas: al alimentar los inyectores 1, 2 y 4 emiten un chasquido nítido de apertura y atomizan a 3.5 bar, pero el inyector 3 no emite sonido ni abre la tobera. La medición eléctrica constató terminal positivo del solenoide desprendido interiormente bajo el encapsulado plástico.", "TALLER", "prueba_banco_inyeccion_4_inyectores", "dtc_p0203|inyector3_no_abre_banco|terminal_positivo_desprendido_encapsulado", "inyectores_obstruidos", "P0203", "NO", "SI", "Inyectores sucios o filtro de combustible obstruido", "L3 prueba en banco demuestra inyector 3 inerte por terminal desprendido bajo encapsulado.")
    agregar("G25-L3-08", CLASE_25, "L3", "Mi carro jalonea horrible y cojea en tres cilindros con codigo P0201 en el escaner. Le midieron con tester los ohmios al inyector uno y dio abierto total sin marcar nada mientras los otros tenian 15 ohmios. Le pusieron un inyector nuevo y se emparejo el motor al tiro.", "ERROR_ORTOGRAFICO", "medicion_ohmios_tester_p0201", "dtc_p0201|abierto_total_sin_marcar|otros_15_ohmios|inyector_nuevo_empareja", "falla_bujias", "P0201", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L3 circuito abierto total con tester comprobado frente a 15 ohms con ortografía informal.")
    agregar("G25-L3-09", CLASE_25, "L3", "DTC P0204 acompañado de olor a gasolina por cilindro no combustionado. La prueba de aislamiento con megóhmetro a 250V entre el devanado del inyector 4 y la masa de carrocería arrojó resistencia de aislamiento de 0.05 megaohms (especificación mayor a 10 Mohms), confirmando fuga de corriente a masa a través de la carcasa metálica del inyector.", "TECNICO", "prueba_aislamiento_megohmetro", "dtc_p0204|aislamiento_0_05_mohm_bajo|fuga_corriente_a_masa_carcasa", "falla_cableado_aislamiento", "P0204", "NO", "NO", "", "L3 megóhmetro detecta fuga de aislamiento a masa en solenoide de inyector 4.")
    agregar("G25-L3-10", CLASE_25, "L3", "Pérdida súbita de potencia con motor en 3 cilindros tras lavar el vano motor con hidrolavadora con código P0202. Al retirar la ficha del inyector 2 se encontró la cavidad sellada llena de agua con jabón que provocó cortocircuito entre los dos pines y quemó el diodo supresor de transitorios en la placa de la ECU.", "TALLER", "lavado_vano_motor_conector_inyector2", "dtc_p0202|agua_jabon_conector_inyector2|cortocircuito_entre_pines", "falla_bobina_encendido", "P0202", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L3 agua en conector de inyector tras lavado provoca cortocircuito con P0202.")
    agregar("G25-L3-11", CLASE_25, "L3", "Buenas tardes, el carro pierde fuerza y tiembla. En el escáner sale código P0203 de circuito de inyector 3. La presión de la bomba de nafta está perfecta en 48 psi y la compresión en 160 parejos. El mecánico le sacó el inyector y la bobina interna está cortada, no marca nada de resistencia.", "WHATSAPP", "descarte_presion_y_compresion_p0203", "dtc_p0203|presion_48psi_ok|compresion_160psi_ok|bobina_inyector_cortada", "bomba_gasolina_baja_presion", "P0203", "NO", "SI", "Bomba de gasolina quemada o con baja presion", "L3 presión de bomba 48 psi y compresión 160 psi descartan bomba y culata.")
    agregar("G25-L3-12", CLASE_25, "L3", "Análisis de tiempo de retardo de inyección con osciloscopio: el tiempo entre el flanco de comando de masa y el punto de cierre mecánico (inflexión de corriente) en el inyector 1 es de 3.2 milisegundos (especificación OEM 1.1 a 1.4 ms) debido a degradación del resorte de retorno y magnetización residual del núcleo.", "TECNICO", "analisis_inflexion_corriente_retardo", "retardo_inflexion_3_2ms_vs_1_2ms|magnetizacion_residual_nucleo", "falla_computadora", "P0201", "NO", "NO", "", "L3 retardo de 3.2 ms en inflexión de corriente por degradación del núcleo.")
    agregar("G25-L3-13", CLASE_25, "L3", "Motor falla intermitentemente en aceleraciones bruscas con código P0204. Se comprobó con voltímetro de aguja que durante la torsión del motor sobre sus soportes de goma el arnés principal se tensa y abre una microfractura interna en el hilo de cobre del inyector 4.", "TALLER", "torsion_motor_rotura_cable", "dtc_p0204_en_aceleracion|torsion_motor_tensa_arnes|microfractura_hilo_cobre", "falla_soporte_motor", "P0204", "NO", "NO", "", "L3 torsión de motor tensa arnés y abre microfractura en cable de inyector 4.")
    agregar("G25-L3-14", CLASE_25, "L3", "DTC P0201 con motor marchando en 3 cilindros. La prueba de caída de tensión en el terminal de alimentación positivo arrojó 3.8 voltios de caída debido a corrosión por sulfato en el empalme de alimentación común del riel dentro de la canaleta plástica de protección.", "TECNICO", "caida_tension_3_8v_alimentacion", "dtc_p0201|caida_tension_3_8v_positivo|corrosion_empalme_comun_riel", "falla_bomba_combustible", "P0201", "NO", "SI", "Bomba de gasolina quemada o con baja presion", "L3 caída de tensión de 3.8V en positivo de inyector 1 por corrosión en empalme.")
    agregar("G25-L3-15", CLASE_25, "L3", "El vehículo ingresó con temblor constante y código P0202. Se verificó con lámpara NOID que el pulso de conmutación de masa llega nítido y la bujía 2 está seca y con chispa. La prueba con multímetro arrojó 120 ohms en el inyector 2 (ocho veces su valor normal) impidiendo que circule la corriente suficiente para vencer la fuerza del resorte y levantar la tobera.", "TALLER", "resistencia_120_ohms_inyector2", "dtc_p0202|resistencia_120_ohms_vs_15_oem|noid_destella_chispa_ok|bujia_seca", "falla_bujias_misfire", "P0202", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L3 resistencia de 120 ohms impide apertura pese a tener pulso de masa y chispa.")

    # =========================================================================
    # CLASE 26: Pérdida de compresión por válvulas pisadas o anillos (40 casos: 10 L1, 15 L2, 15 L3)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G26-L1-01", CLASE_26, "L1", "El motor tiembla en ralentí y suena desparejo cuando gira en el arranque.", "COTIDIANO", "arranque_y_ralenti", "temblor_ralenti|arranque_desparejo", "", "", "SI", "NO", "", "L1 giro desparejo al arrancar.")
    agregar("G26-L1-02", CLASE_26, "L1", "Hola, un cilindro no está funcionando y ya cambié bujía, cable y bobina.", "WHATSAPP", "post_cambio_encendido", "cilindro_no_funciona_post_piezas", "", "", "SI", "NO", "", "L1 cilindro inactivo persistente.")
    agregar("G26-L1-03", CLASE_26, "L1", "Siento que el carro perdió fuerza en subida y tose por el tubo de escape.", "COTIDIANO", "subida", "falta_fuerza_subida|tose_escape", "", "", "SI", "NO", "", "L1 tos por escape y falta de compresión.")
    agregar("G26-L1-04", CLASE_26, "L1", "Al sacar la varilla del aceite sale bastante humo blanco y salpica gotitas.", "COTIDIANO", "inspeccion_varilla", "humo_salpica_varilla_aceite", "", "", "SI", "NO", "", "L1 presión de blow-by en cárter.")
    agregar("G26-L1-05", CLASE_26, "L1", "El motor tiene un fallo de cilindro constante que empeora cuando calienta.", "TALLER", "motor_caliente", "fallo_constante_empeora_caliente", "", "", "SI", "NO", "", "L1 empeoramiento térmico por dilatación valvular.")
    agregar("G26-L1-06", CLASE_26, "L1", "Aparece un código de fallo de combustión en el cilindro 3 en el escáner.", "TECNICO", "diagnostico", "falla_combustion_cilindro3", "", "", "SI", "NO", "", "L1 reporte de misfire persistente.")
    agregar("G26-L1-07", CLASE_26, "L1", "El auto vibra como tractor en mínimo y consume bastante combustible.", "COTIDIANO", "ralenti", "vibracion_tractor_minimo|consumo_alto", "", "", "SI", "NO", "", "L1 vibración constante y sobreconsumo.")
    agregar("G26-L1-08", CLASE_26, "L1", "Mi carro cojea en baja y el mecanico dice que no tiene presion en un piston.", "ERROR_ORTOGRAFICO", "baja_rpm", "cojea_en_baja|sin_presion_un_piston", "", "", "SI", "NO", "", "L1 pistón sin compresión con ortografía informal.")
    agregar("G26-L1-09", CLASE_26, "L1", "Buenas, cambiaron inyectores y sigue fallando el mismo cilindro de siempre.", "WHATSAPP", "post_cambio_inyectores", "falla_mismo_cilindro_post_inyectores", "", "", "SI", "NO", "", "L1 persistencia tras cambio de inyectores.")
    agregar("G26-L1-10", CLASE_26, "L1", "Presión manométrica de compresión en cámara de combustión por debajo de especificación.", "TECNICO", "medicion", "compresion_camara_bajo_especificacion", "", "", "SI", "NO", "", "L1 reporte técnico de compresión insuficiente.")

    # --- L2 (15 casos) ---
    agregar("G26-L2-01", CLASE_26, "L2", "El cilindro 3 marca solo 40 psi de compresión mientras los otros tres marcan 165 psi; al agregar una cucharada de aceite en el cilindro la compresión no sube, confirmando válvula pisada.", "COTIDIANO", "prueba_compresion_humeda", "compresion_40psi_no_sube_con_aceite|valvula_pisada", "falla_anillos", "", "NO", "SI", "Consumo de aceite por desgaste de anillos o retenes", "L2 prueba húmeda sin incremento confirma válvula vs anillos.")
    agregar("G26-L2-02", CLASE_26, "L2", "Prueba de compresión seca arrojó 70 psi en el cilindro 2 y 160 psi en el resto; al realizar la prueba húmeda con 10 ml de aceite la compresión subió a 135 psi demostrando anillos desgastados.", "TALLER", "prueba_humeda_sube_compresion", "compresion_70_sube_a_135psi_con_aceite|anillos_desgastados", "valvula_quemada", "", "NO", "SI", "Consumo de aceite por desgaste de anillos o retenes", "L2 prueba húmeda que sube de 70 a 135 psi confirma aros desgastados.")
    agregar("G26-L2-03", CLASE_26, "L2", "Código P0304 persistente; se cambiaron bujías, bobinas e inyectores sin ningún cambio. La prueba de fuga de cilindros reveló que el aire presurizado se escapa directamente por el tubo de escape.", "TECNICO", "prueba_fuga_escape", "dtc_p0304|aire_escapa_por_tubo_escape|fuga_valvula_escape", "falla_bobinas", "P0304", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L2 aire escapando por tubo de escape confirma válvula de escape.")
    agregar("G26-L2-04", CLASE_26, "L2", "Hola maestro, el carro tiembla en mínimo y al dar arranque gira con un sonido disparejo chuc-chuc-raápido. El mecánico midió compresión y el pistón 1 no tiene nada de libras.", "WHATSAPP", "arranque_sonido_disparejo", "arranque_disparejo_chuc_rapido|piston1_sin_libras", "falla_motor_arranque", "", "NO", "SI", "Falla en motor de arranque o solenoide defectuoso (clac seco o carbones gastados)", "L2 cadencia de arranque despareja por cilindro sin compresión.")
    agregar("G26-L2-05", CLASE_26, "L2", "En motor a gas GLP las válvulas de escape del cilindro 4 se quedaron sin holgura (luz de válvula en 0.00 mm por recesión de asiento) provocando que la válvula no cierre al dilatar en caliente.", "TECNICO", "medicion_holgura_taques", "luz_valvula_0_00mm|recesion_asiento_glp|no_cierra_en_caliente", "falla_vvt", "", "NO", "SI", "Falla en sistema de sincronizacion variable de valvulas (VVT / VVT-i / Valvetronic)", "L2 recesión de asiento a 0.00 mm en motor GLP vs VVT.")
    agregar("G26-L2-06", CLASE_26, "L2", "Al retirar la tapa de llenado de aceite con el motor en marcha sopla fuerte viento con humo blanco y salpica aceite por soplado de compresión hacia el cárter por anillos rotos.", "TALLER", "inspeccion_blowby_tapa", "viento_humo_blanco_tapa_aceite|blowby_carter|anillos_rotos", "falla_valvula_pcv", "", "NO", "NO", "", "L2 blow-by severo en tapa de aceite por rotura de aros.")
    agregar("G26-L2-07", CLASE_26, "L2", "El auto perdió compresión en el cilindro 1 tras recalentamiento previo; no mezcla agua con aceite ni burbujea el radiador pero la válvula de admisión quedó deformada.", "COTIDIANO", "post_recalentamiento", "cilindro1_sin_compresion|sin_agua_en_aceite|sin_burbujas_radiador", "culata_soplada", "", "NO", "SI", "Empaque de culata soplado o danado", "L2 sin agua en aceite ni burbujas descarta junta de culata soplada.")
    agregar("G26-L2-08", CLASE_26, "L2", "Mi auto vibra feo en subida y en el taller le midieron compresion saliendo 50 libras en el cuatro y 160 en los demas. Le cambiaron la bobina y sigue temblando porque no hay compresion mecanica.", "ERROR_ORTOGRAFICO", "medicion_50_libras_cilindro4", "50_libras_cilindro4_vs_160|bobina_nueva_persiste", "falla_bobina", "P0304", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L2 50 psi persistente tras bobina nueva con ortografía informal.")
    agregar("G26-L2-09", CLASE_26, "L2", "Prueba de estanqueidad neumática de cilindros: al aplicar 80 psi en el cilindro 3 en punto muerto superior se registra 65% de fuga con silbido audible en el cuerpo de mariposa de admisión.", "TECNICO", "fuga_aire_cuerpo_mariposa", "fuga_65_porciento|silbido_cuerpo_mariposa|valvula_admision_fuga", "fuga_multiple_admision", "", "NO", "NO", "", "L2 fuga de aire por mariposa confirma válvula de admisión pisada.")
    agregar("G26-L2-10", CLASE_26, "L2", "DTC P0301; la bujía sale negra y carbonizada pero el osciloscopio muestra pulso de inyección correcto y arco de chispa de 18 kV en la bobina descartando fallas electrónicas.", "TALLER", "diagnostico_chispa_inyeccion_ok", "dtc_p0301|chispa_18kv_ok|pulso_inyeccion_ok|compresion_baja", "falla_circuito_inyector", "P0301", "NO", "SI", "Falla en circuito o solenoide de inyector individual (DTC P0201 - P0208)", "L2 chispa 18 kV e inyección OK descartan circuito de inyector y encendido.")
    agregar("G26-L2-11", CLASE_26, "L2", "Buenas, el carro tose en mínimo y bota bocanadas de humo azul al acelerar fuerte; el cilindro 2 tiene los aros pegados por carbón y pierde compresión.", "WHATSAPP", "humo_azul_acelerar", "tose_minimo|humo_azul_acelerar|aros_pegados_carbon", "falla_turbo", "", "NO", "SI", "Fuga en mangueras de intercooler o turbocompresor danado", "L2 aros pegados con humo azul y falta de compresión vs turbo.")
    agregar("G26-L2-12", CLASE_26, "L2", "Diferencia de compresión mayor al 25% entre cilindros: cilindro 1 (160 psi), cilindro 2 (155 psi), cilindro 3 (95 psi) y cilindro 4 (160 psi), originando cabeceo en ralentí.", "TECNICO", "desbalance_compresion_cilindro3", "desbalance_compresion_cilindro3_95psi|tolerancia_max_10", "falla_soportes_motor", "", "NO", "NO", "", "L2 desbalance de compresión superior a tolerancia del 10%.")
    agregar("G26-L2-13", CLASE_26, "L2", "Al sacar la bujía del cilindro afectado se observa con boroscopio la cabeza del pistón lavada y rayaduras verticales profundas en la pared de la camisa de cilindro.", "TALLER", "boroscopia_cilindro_rayado", "rayaduras_camisa_cilindro|piston_lavado|perdida_compresion", "falla_inyector_goteando", "", "NO", "SI", "Inyectores sucios o filtro de combustible obstruido", "L2 cilindro rayado constatado por boroscopía.")
    agregar("G26-L2-14", CLASE_26, "L2", "El auto arranca pero no sostiene el ralentí en frío apagándose a menos que se acelere; la compresión en los 4 cilindros está uniformemente baja en 90 psi por desgaste severo de aros.", "COTIDIANO", "compresion_baja_4_cilindros", "no_sostiene_ralenti_frio|compresion_90psi_pareja", "falla_valvula_iac", "", "NO", "SI", "Cuerpo de aceleracion o valvula IAC sucia", "L2 compresión baja homogénea a 90 psi por desgaste general.")
    agregar("G26-L2-15", CLASE_26, "L2", "DTC P0303 en motor 16 válvulas; el taqué hidráulico del cilindro 3 se quedó descargado o trabado abierto manteniendo la válvula ligeramente pisada y perdiendo estanqueidad.", "TECNICO", "taque_hidraulico_trabado", "dtc_p0303|taque_hidraulico_trabado_abierto|valvula_pisada", "falla_solenoide_vvt", "P0303", "NO", "SI", "Falla en sistema de sincronizacion variable de valvulas (VVT / VVT-i / Valvetronic)", "L2 taqué hidráulico trabado abierto vs variador VVT.")

    # --- L3 (15 casos) ---
    agregar("G26-L3-01", CLASE_26, "L3", "Vehículo ingresa con fallo de encendido permanente en el cilindro 3 acompañado de DTC P0303. Se realizaron pruebas de encendido con osciloscopio: la bobina del cilindro 3 genera arco voltaico de 28 kV y el inyector tiene pulso de 2.5 ms con resistencia de 14.5 ohms normal y bujía seca. Se ejecutó la prueba de compresión manométrica en seco: cilindro 1 (165 psi), cilindro 2 (160 psi), cilindro 3 (45 psi) y cilindro 4 (165 psi). Al realizar la prueba húmeda inyectando 10 ml de aceite de motor en el cilindro 3 la presión se mantuvo inalterada en 45 psi, y la prueba de fuga neumática con 90 psi al 80% reveló escape de aire audible por el múltiple de escape, confirmando válvula de escape quemada.", "TECNICO", "prueba_seca_humeda_fuga_escape", "dtc_p0303|compresion_seca_45_humeda_45psi|fuga_aire_escape|chispa_28kv_ok|inyector_ok", "falla_bobina_encendido", "P0303", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L3 prueba húmeda sin cambio (45 psi) y fuga por escape descarta bobina y aros.")
    agregar("G26-L3-02", CLASE_26, "L3", "Toyota Yaris con motor 1NZ-FE convertido a gas GNV presenta vibración intensa en ralentí y DTC P0301. Se midió la holgura de válvulas con galgas de espesor encontrándose luz de 0.00 mm en ambas válvulas de escape del cilindro 1 (especificación 0.25 a 0.35 mm) por recesión severa de asientos provocada por la alta temperatura del gas seco. La compresión en frío marca 60 psi y al calentar cae a 25 psi debido a que la dilatación térmica del vástago impide el cierre valvular.", "TALLER", "metrologia_galgas_gnv_1nz", "dtc_p0301|luz_valvulas_0_00mm_gnv|compresion_60_cae_25psi_caliente", "falla_cadena_distribucion", "P0301", "NO", "SI", "Faja o cadena de distribucion destensada o con salto de punto", "L3 metrología con galgas a 0.00 mm confirma recesión de asientos por GNV.")
    agregar("G26-L3-03", CLASE_26, "L3", "El vehículo presenta consumo excesivo de aceite (1 litro cada 400 km) y humo azul denso por el escape con temblor en aceleración. Prueba de compresión seca: cilindro 1 (80 psi), cilindro 2 (85 psi), cilindro 3 (75 psi) y cilindro 4 (80 psi). Al realizar la prueba húmeda con aceite la compresión salta inmediatamente a 145 psi en los 4 cilindros. La prueba de fuga con aire a 80 psi expulsó aire con violencia por el orificio de la varilla medidora de aceite y tapón de cárter, confirmando desgaste destructivo de los aros de compresión.", "TECNICO", "prueba_humeda_salta_a_145psi_blowby", "compresion_seca_80_humeda_145psi|blowby_varilla_aceite|consumo_1l_400km", "desgaste_retenes_valvula", "", "NO", "SI", "Consumo de aceite por desgaste de anillos o retenes", "L3 prueba húmeda que sube a 145 psi y fuga por varilla descarta retenes y confirma aros.")
    agregar("G26-L3-04", CLASE_26, "L3", "DTC P0302 en motor 2.0 16v tras evento de sobre-revolución en reducción de marcha. La compresión en el cilindro 2 marca 0 psi absolutos mientras el resto tiene 170 psi. Se introdujo cámara boroscópica por el orificio de la bujía observándose marca de impacto circular de la cabeza de la válvula de admisión contra la cabeza del pistón y la válvula trabada chueca en su guía de bronce, sin deformación en el resto de los cilindros.", "TALLER", "boroscopia_valvula_doblada_piston", "dtc_p0302|compresion_0psi|impacto_valvula_piston_boroscopio|valvula_chueca_guia", "falla_distribucion_total", "P0302", "NO", "SI", "Faja o cadena de distribucion destensada o con salto de punto", "L3 boroscopía constata válvula doblada individual por sobrerrégimen vs cadena.")
    agregar("G26-L3-05", CLASE_26, "L3", "Hola maestro, el carro me empezó a temblar feo en tres cilindros. En el taller le cambiaron bujías, cables y le limpiaron los 4 inyectores con ultrasonido pero seguía igualito el temblor. Le pusieron el reloj de compresión y el cilindro 4 tiene solo 30 libras; le echaron aceite y no subió nada. Tuvieron que sacar la culata y la válvula de escape estaba rajada como una empanada.", "WHATSAPP", "valvula_rajada_post_ultrasonido", "tiembla_en_3_cilindros|piezas_nuevas_persiste|compresion_30_libras_no_sube|valvula_rajada", "falla_inyectores", "", "NO", "SI", "Inyectores sucios o filtro de combustible obstruido", "L3 relato WhatsApp de compresión 30 psi con válvula rajada tras limpiar inyectores.")
    agregar("G26-L3-06", CLASE_26, "L3", "Prueba de hermeticidad de cilindro con transductor de presión en el cilindro 1 (in-cylinder pressure transducer con osciloscopio pico-scope): el pico máximo de compresión alcanza apenas 2.8 bar relativos en ralentí (especificación 11 bar). La rampa de escape muestra fuga continua de presión durante la carrera de expansión confirmando pérdida de estanqueidad por asiento de válvula desgastado sin problemas de chispa.", "TECNICO", "transductor_presion_incilindro_picoscope", "pico_compresion_2_8bar_vs_11bar|rampa_expansion_fuga|picoscope", "falla_bujias_bobinas", "P0301", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L3 transductor in-cylinder en osciloscopio grafica compresión en 2.8 bar.")
    agregar("G26-L3-07", CLASE_26, "L3", "Motor de 4 cilindros con temblor constante y código P0304. Se realizó prueba comparativa: la bobina entrega chispa de 25 kV, el inyector marca 14 ohms y destella lámpara noid, pero al medir compresión el cilindro 4 arroja 55 psi frente a 160 psi en el resto. La prueba húmeda con 5 ml de aceite sube la compresión a 140 psi, y la inspección boroscópica detectó ranura de pistón partida con anillo de fuego quebrado.", "TALLER", "boroscopia_anillo_fuego_roto", "dtc_p0304|chispa_25kv_ok|noid_ok|compresion_55_sube_140psi|anillo_fuego_quebrado", "falla_circuito_inyector", "P0304", "NO", "SI", "Falla en circuito o solenoide de inyector individual (DTC P0201 - P0208)", "L3 salto de 55 a 140 psi y boroscopía confirma anillo partido vs inyector.")
    agregar("G26-L3-08", CLASE_26, "L3", "Mi carro vibra como batidora en minimo y prende el check con codigo P0302. Le probaron chispa y hay buena chispa azul, le probaron inyector y chisguetea bien, pero al medirle las libras con el reloj el piston 2 dio 40 libras y los otros 165. Le sacaron la tapa de balancines y la valvula no tiene luz de luz de galga.", "ERROR_ORTOGRAFICO", "medicion_libras_sin_luz_galga", "dtc_p0302|chispa_azul_ok|inyector_ok|reloj_40_libras|sin_luz_galga", "falla_chispa", "P0302", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L3 chispa e inyección comprobadas; 40 psi por válvula sin luz con ortografía informal.")
    agregar("G26-L3-09", CLASE_26, "L3", "DTC P0303 en vehículo con 260,000 km. Al realizar la prueba de compresión dinámica con osciloscopio (amperaje del motor de arranque durante el giro): los cilindros 1, 2 y 4 demandan picos de 145 amperios pero en el cilindro 3 la corriente cae a 45 amperios por ausencia total de resistencia mecánica al comprimir, confirmando pérdida de estanqueidad.", "TECNICO", "compresion_relativa_amperimetrica", "dtc_p0303|amperaje_cae_145_a_45a_cilindro3|compresion_relativa_baja", "falla_motor_arranque", "P0303", "NO", "SI", "Falla en motor de arranque o solenoide defectuoso (clac seco o carbones gastados)", "L3 pinza amperimétrica en motor de arranque muestra caída a 45A en cilindro 3.")
    agregar("G26-L3-10", CLASE_26, "L3", "El vehículo ingresó tras recalentamiento severo por rotura de manguera de refrigerante. El motor tiembla y presenta compresión de 50 psi en el cilindro 4. No hay burbujas de combustión en el vaso de expansión ni emulsión mayonesa en la tapa de aceite descartando empaque soplado a galerías; la causa fue deformación de la culata en la zona del asiento de válvula de escape 4.", "TALLER", "descarte_empaque_vs_asiento_culata", "compresion_50psi_cilindro4|sin_burbujas_refrigerante|sin_mayonesa_aceite|asiento_deformado", "empaque_culata_soplado", "", "NO", "SI", "Empaque de culata soplado o danado", "L3 ausencia de mayonesa y burbujas descarta empaque soplado y confirma asiento.")
    agregar("G26-L3-11", CLASE_26, "L3", "Buenas tardes, el auto perdió fuerza y humea por la tapa del aceite. El mecánico le metió el manómetro de compresión y dice que el cilindro 1 tiene 60 libras y los otros 160. Le echó un chorrito de aceite de motor por el hueco de la bujía y volvió a medir y subió a 130 libras; me dijo que son los aros del pistón que se pegaron.", "WHATSAPP", "prueba_chorrito_aceite_60_a_130", "compresion_60_sube_a_130_con_chorrito|humea_tapa_aceite|aros_pegados", "desgaste_retenes", "", "NO", "SI", "Consumo de aceite por desgaste de anillos o retenes", "L3 relato WhatsApp de prueba húmeda subiendo de 60 a 130 confirmando aros.")
    agregar("G26-L3-12", CLASE_26, "L3", "Prueba de fugas neumática con 100 psi en cilindro 2: se constata 70% de pérdida con salida masiva de aire sibilante a través del múltiple de admisión. Se desmontó el eje de balancines y al quedar ambas levas en reposo la válvula de admisión sigue sin asentar herméticamente por acumulación de carbonilla dura compactada en el chaflán del asiento.", "TECNICO", "fuga_aire_multiple_admision_70", "fuga_70_porciento_admision|valvula_no_asienta_balancines_libres|carbonilla_chaflan", "falla_descarbonizacion_gdi", "", "NO", "SI", "Falla de descarbonizacion e inyeccion directa GDI (acumulacion de carbon en valvulas)", "L3 fuga del 70% por admisión con balancines libres confirma válvula que no asienta.")
    agregar("G26-L3-13", CLASE_26, "L3", "DTC P0301 en motor de 3 cilindros. La compresión en cilindro 1 arroja 35 psi y 160 psi en los cilindros 2 y 3. Al retirar la bujía 1 y aplicar aire a presión se descartan fugas hacia el cárter y hacia el radiador; el aire escapa exclusivamente por el tubo de escape confirmando fisura en el plato de la válvula de escape 1.", "TALLER", "fuga_exclusiva_tubo_escape", "dtc_p0301|compresion_35psi|aire_escapa_solo_por_escape|fisura_plato_valvula", "falla_sensor_ckp", "P0301", "NO", "NO", "", "L3 aire escapa exclusivamente por tubo de escape confirmando fisura en plato.")
    agregar("G26-L3-14", CLASE_26, "L3", "El motor presenta marcha tosca en frío que mejora ligeramente al calentar. Se midió compresión en frío: cilindro 1 (90 psi), cilindro 2 (165 psi), cilindro 3 (165 psi) y cilindro 4 (165 psi). La prueba de caída de vacío en admisión con vacuómetro marca oscilación rápida de la aguja de 4 inHg al ritmo del cilindro 1 por pérdida de sello valvular.", "TECNICO", "vacuometro_oscilacion_4inhg", "vacuometro_oscila_4inhg_ritmo_cilindro1|compresion_90psi_frio", "falla_valvula_iac", "", "NO", "SI", "Cuerpo de aceleracion o valvula IAC sucia", "L3 vacuómetro oscila 4 inHg al ritmo de cilindro descompresionado.")
    agregar("G26-L3-15", CLASE_26, "L3", "Al exigir el motor en autopista se siente pérdida súbita de potencia y olor a aceite quemado. La prueba manométrica en cilindro 4 marcó 0 psi; al desmontar la culata se comprobó que el pistón 4 tiene un orificio de 12 mm perforado en el centro por detonación severa continua, comunicando la cámara directamente con el cárter.", "TALLER", "piston_perforado_12mm_detonacion", "compresion_0psi|piston_perforado_12mm_detonacion|comunica_carter", "falla_bielas_motor", "", "NO", "NO", "", "L3 pistón perforado de 12 mm por detonación genera 0 psi.")

    return casos
