"""
Casos de entrenamiento para Fase 10 Lote 06 (FRENOS - Parte 1):
- Clase 27: Desgaste de pastillas y zapatas de freno (40 casos: 10 L1, 15 L2, 15 L3)
- Clase 28: Discos de freno alabeados o desgastados (40 casos: 10 L1, 15 L2, 15 L3)
- Clase 29: Falla en servofreno (booster) o linea de vacio (40 casos: 10 L1, 15 L2, 15 L3)

Total: 120 registros (IDs F10-L06-0001 a F10-L06-0120).
"""

CLASE_27 = "Desgaste de pastillas y zapatas de freno"
CLASE_28 = "Discos de freno alabeados o desgastados"
CLASE_29 = "Falla en servofreno (booster) o linea de vacio"


def obtener_casos_27_29(offset=1):
    casos = []
    idx = offset

    def agregar(id_grupo, clase, nivel, texto, tipo_lenguaje, cond, sint_pres, sint_neg, dtc, req_preg, es_cont, cl_cont, obs):
        nonlocal idx
        reg_id = f"F10-L06-{idx:04d}"
        idx += 1
        casos.append({
            "id": reg_id,
            "id_grupo": id_grupo,
            "clase_objetivo": clase,
            "macro_sistema": "FRENOS",
            "nivel_informacion": nivel,
            "texto_usuario": texto.strip(),
            "tipo_lenguaje": tipo_lenguaje,
            "condicion_operacion": cond.strip(),
            "sintomas_presentes": sint_pres.strip(),
            "sintomas_negados": sint_neg.strip(),
            "dtc": dtc.strip(),
            "requiere_pregunta": req_preg.strip(),
            "es_contrastivo": es_cont.strip(),
            "clase_contrastiva": cl_cont.strip(),
            "fuente": "SINTETICO_IA",
            "observaciones": obs.strip()
        })

    # =========================================================================
    # CLASE 27: Desgaste de pastillas y zapatas de freno (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G27-L1-01", CLASE_27, "L1", "Suena un chillido agudo cada vez que piso el pedal del freno.", "COTIDIANO", "frenado_suave", "chillido_agudo_frenar", "", "", "SI", "NO", "", "L1 chillido típico de lámina avisadora.")
    agregar("G27-L1-02", CLASE_27, "L1", "Hola, siento como un raspado de fierro con fierro cuando me detengo.", "WHATSAPP", "detencion", "raspado_fierro_con_fierro", "", "", "SI", "NO", "", "L1 pastilla gastada al soporte metálico.")
    agregar("G27-L1-03", CLASE_27, "L1", "El freno de mano sube casi hasta el tope y no aguanta el carro en bajada.", "COTIDIANO", "estacionamiento", "freno_mano_muy_largo", "", "", "SI", "NO", "", "L1 zapatas traseras con excesiva holgura.")
    agregar("G27-L1-04", CLASE_27, "L1", "Aparece mucho polvo negro oscuro pegado en los aros delanteros.", "COTIDIANO", "inspeccion_visual", "polvo_negro_aros", "", "", "SI", "NO", "", "L1 desprendimiento de material de fricción.")
    agregar("G27-L1-05", CLASE_27, "L1", "Testigo de desgaste de forros de freno encendido en el panel de instrumentos.", "TECNICO", "contacto", "testigo_desgaste_forros", "", "", "SI", "NO", "", "L1 sensor de desgaste activado.")
    agregar("G27-L1-06", CLASE_27, "L1", "El carro frena largo y siento que tengo que hundir más el pie para que pare.", "TALLER", "frenada", "frenado_largo|pedal_recorrido_mayor", "", "", "SI", "NO", "", "L1 pérdida de mordida y mayor carrera.")
    agregar("G27-L1-07", CLASE_27, "L1", "Se escucha un chirrido constante en la rueda que se apaga un poquito al frenar.", "COTIDIANO", "rodadura", "chirrido_constante_rueda", "", "", "SI", "NO", "", "L1 testigo acústico rozando disco.")
    agregar("G27-L1-08", CLASE_27, "L1", "Mi auto ase un chillido horrible al frenar y bota polvo negro en los aros.", "ERROR_ORTOGRAFICO", "frenado", "chillido_horrible|polvo_negro", "", "", "SI", "NO", "", "L1 chillido con ortografía informal.")
    agregar("G27-L1-09", CLASE_27, "L1", "Buenas tardes, al retroceder y frenar suena un golpe seco en las ruedas de atrás.", "WHATSAPP", "retroceso_frenado", "golpe_seco_atras_retroceso", "", "", "SI", "NO", "", "L1 zapatas descalibradas en tambor.")
    agregar("G27-L1-10", CLASE_27, "L1", "Reducción perceptible del coeficiente de fricción estático y dinámico en eje delantero.", "TECNICO", "frenado_rutina", "reduccion_coeficiente_friccion", "", "", "SI", "NO", "", "L1 reporte técnico de pérdida de coeficiente mu.")

    # --- L2 (15 casos) ---
    agregar("G27-L2-01", CLASE_27, "L2", "Chillido metálico agudo en la rueda delantera izquierda al frenar suave; el sonido cesa al pisar a fondo y el volante no vibra en absoluto.", "COTIDIANO", "frenado_suave", "chillido_metalico_suave", "vibracion_volante", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L2 chivato acústico descarta alabeo de discos.")
    agregar("G27-L2-02", CLASE_27, "L2", "Ruido de roce abrasivo metal contra metal al frenar fuerte en bajadas; a través del aro se observa la pastilla exterior con menos de 1.5 mm de forro.", "TALLER", "frenado_fuerte_bajada", "roce_abrasivo_metal|espesor_menor_1_5mm", "falla_liquido_frenos", "", "NO", "SI", "Caliper de freno trabado o mordaza pegada (piston agarrotado)", "L2 pastilla al soporte sin afectación de líquido.")
    agregar("G27-L2-03", CLASE_27, "L2", "Freno de mano mecánico requiere 11 clics para frenar y las ruedas traseras de tambor chirrían al frenar en caliente; zapatas desgastadas al remache.", "TECNICO", "freno_mano_y_servicio", "freno_mano_11_clics|chirrido_tambor_caliente|zapatas_al_remache", "falla_cable_freno", "", "NO", "NO", "", "L2 desgaste en zapatas traseras por exceso de recorrido.")
    agregar("G27-L2-04", CLASE_27, "L2", "Hola maestro, cuando freno suena como lija gruesa raspando latón en las ruedas de adelante; el pedal no se hunde y tiene buen tacto firme.", "WHATSAPP", "frenado_urbano", "sonido_lija_gruesa_raspado|pedal_firme", "pedal_esponjoso", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L2 fricción agotada con pedal firme descarta aire.")
    agregar("G27-L2-05", CLASE_27, "L2", "Aviso en tablero de desgaste de frenos en BMW Serie 3; el sensor de contacto del caliper delantero rozó contra el disco cerrando el circuito a masa.", "TECNICO", "contacto_encendido", "aviso_desgaste_frenos|sensor_contacto_cerrado", "falla_modulo_abs", "", "NO", "NO", "", "L2 sensor de desgaste electrónico OEM.")
    agregar("G27-L2-06", CLASE_27, "L2", "Al pisar el freno a 60 km/h se escucha rechinido agudo continuo; al soltar el freno el ruido desaparece y la trayectoria del vehículo se mantiene derecha.", "COTIDIANO", "frenado_60kmh", "rechinido_continuo_frenar", "desviacion_direccion", "", "NO", "SI", "Caliper de freno trabado o mordaza pegada (piston agarrotado)", "L2 rechinido sin desvío descarta mordaza trabada.")
    agregar("G27-L2-07", CLASE_27, "L2", "Pastillas traseras cristalizadas tras bajar pendiente prolongada; al frenar emiten silbido sordo y la distancia de frenado aumentó notablemente.", "TALLER", "post_pendiente", "pastillas_cristalizadas|silbido_sordo|mayor_distancia_frenado", "falla_servofreno", "", "NO", "SI", "Falla en servofreno (booster) o linea de vacio", "L2 cristalización térmica de ferodo.")
    agregar("G27-L2-08", CLASE_27, "L2", "Mi camioneta ase un chillido insoportable en las 4 ruedas al frenar y las llantas de adelante tan llenas de tizne negro.", "ERROR_ORTOGRAFICO", "frenado", "chillido_4_ruedas|tizne_negro_aros", "falla_abs", "", "NO", "NO", "", "L2 chillido y hollín con ortografía informal.")
    agregar("G27-L2-09", CLASE_27, "L2", "Buenas, me cambiaron líquido de frenos pero sigue sonando un chillido seco al parar en semáforos. Las pastillas tienen ya 45,000 kilómetros sin cambio.", "WHATSAPP", "detencion_semaforo", "chillido_seco_parar|pastillas_45000km", "aire_circuito", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L2 45,000 km sin cambio de pastillas descarta hidráulica.")
    agregar("G27-L2-10", CLASE_27, "L2", "Inspección de zapatas en freno de tambor: espesor de material de fricción en 1.0 mm (límite de servicio 1.5 mm) con surcos concéntricos en el forro.", "TECNICO", "inspeccion_tambor", "espesor_zapata_1_0mm|surcos_forro", "fuga_bombin", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L2 medición de zapata a 1.0 mm sin fuga de bombín.")
    agregar("G27-L2-11", CLASE_27, "L2", "Chirrido estridente al frenar a muy baja velocidad antes de detenerse por completo; el nivel de líquido de frenos en el depósito bajó por compensación de desgaste.", "COTIDIANO", "baja_velocidad", "chirrido_estridente_baja_velocidad|nivel_liquido_bajo_desgaste", "fuga_liquido", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L2 descenso normal de nivel por desgaste de pastillas.")
    agregar("G27-L2-12", CLASE_27, "L2", "El freno emite chasquido metálico al aplicar marcha atrás tras frenar hacia adelante; holgura excesiva de las pastillas en las guías del portacaliper.", "TALLER", "cambio_sentido_frenado", "chasquido_metalico_marcha_atras|holgura_pastillas_guias", "falla_rotulas", "", "NO", "NO", "", "L2 holgura en clips de pastilla por desgaste.")
    agregar("G27-L2-13", CLASE_27, "L2", "Inspección visual muestra pastillas delanteras al 10% de vida útil rozando la lengüeta metálica elástica de advertencia sobre la pista del disco.", "TECNICO", "inspeccion_elevador", "pastillas_10_porciento|lengueta_rozando_pista", "desgaste_irregular", "", "NO", "NO", "", "L2 lengüeta acústica rozando al 10% de vida.")
    agregar("G27-L2-14", CLASE_27, "L2", "Ruido de raspón seco en el eje trasero al frenar fuerte cargado; el tambor presenta polvo acumulado y zapatas con desgaste disparejo superior e inferior.", "COTIDIANO", "frenado_carga", "raspon_seco_trasero|zapatas_desgaste_disparejo", "falla_cojinetes", "", "NO", "NO", "", "L2 desgaste asimétrico de zapatas por autoajuste trabado.")
    agregar("G27-L2-15", CLASE_27, "L2", "Sonido chirriante metálico agudo en rueda delantera derecha; no hay pulsación en el pedal de freno y los calipers deslizan libremente en sus pasadores.", "TALLER", "prueba_ruta", "sonido_chirriante_rueda_derecha", "pulsacion_pedal|caliper_agarrotado", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L2 chirrido sin pulsación descarta alabeo.")

    # --- L3 (15 casos) ---
    agregar("G27-L3-01", CLASE_27, "L3", "Vehículo ingresa por chirrido estridente al frenar a velocidades urbanas. Se desmontan ruedas delanteras constatándose que las pastillas exteriores tienen 2.0 mm y las interiores 1.2 mm (límite OEM 3.0 mm). La chapa de aviso acústico está en contacto permanente con el borde exterior del disco de freno provocando el chillido, mientras que el disco mantiene espesor nominal de 24.2 mm sin rebaba excesiva.", "TALLER", "desarme_eje_delantero", "chirrido_estridente_urbano|pastillas_1_2mm|chapa_aviso_contacto|disco_nominal_24_2mm", "falla_discos_alabeados", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L3 medición con micrómetro de pastillas a 1.2 mm y disco nominal OK.")
    agregar("G27-L3-02", CLASE_27, "L3", "Conductor reporta ruido áspero de amoladora al frenar en bajadas pronunciadas. En la inspección se verificó que la pastilla interior de la rueda delantera izquierda consumió el 100% del compuesto de fricción, trabajando el plato metálico de respaldo directamente contra el rotor. El líquido de frenos está en nivel correcto y el pedal mantiene presión hidráulica constante sin hundimiento.", "TECNICO", "inspeccion_desgaste_total", "ruido_amoladora_bajada|soporte_metalico_contra_rotor|liquido_ok_pedal_firme", "falla_bomba_frenos", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L3 plato de respaldo metálico rozando disco con hidráulica firme.")
    agregar("G27-L3-03", CLASE_27, "L3", "Medición de espesor de forros en frenos traseros de tambor: zapatas primarias en 1.1 mm y secundarias en 0.8 mm (mínimo de seguridad 1.6 mm), con remaches rozando el tambor y produciendo surcos de 0.4 mm. El cilindro de rueda bombín no presenta fuga de líquido y el mecanismo autoajustador de trinquete llegó al final de su recorrido dentado.", "TECNICO", "metrologia_tambor_trasero", "zapatas_0_8mm_remaches_rozando|surcos_tambor_0_4mm|bombin_seco|autoajustador_tope", "fuga_bombin_frenos", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L3 zapatas a 0.8 mm rozando remache con bombines secos.")
    agregar("G27-L3-04", CLASE_27, "L3", "Testigo luminoso ámbar de desgaste de pastillas encendido fijo en Audi A4. La lectura con escáner no arroja fallas en módulo ABS pero el sensor resistivo del lado izquierdo se cortó al hacer masa con el disco tras llegar al 15% de espesor residual (2.2 mm). Los pernos guía flotantes se encuentran perfectamente lubricados con grasa de silicona.", "TECNICO", "diagnostico_sensor_desgaste_oem", "testigo_desgaste_ambar|sensor_cortado_2_2mm|pernos_guia_ok", "falla_sensor_abs", "", "NO", "SI", "Falla en sensor de velocidad de rueda ABS", "L3 sensor resistivo cortado descarta falla en sensores ABS.")
    agregar("G27-L3-05", CLASE_27, "L3", "Hola maestro, en mi Yaris suena un silbido bien feo al frenar despacio en el tráfico. Le revisaron el espesor de las pastillas y tienen menos de 2 milímetros, casi en el fierro. Al frenar no tiembla el timón para nada y el pedal no se va al fondo, solo es el chillido feo.", "WHATSAPP", "frenado_trafico_yaris", "silbido_feo_frenar_despacio|pastillas_menos_2mm|timon_no_tiembla|pedal_firme", "discos_alabeados", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L3 relato WhatsApp de pastillas a 2 mm sin vibración de timón.")
    agregar("G27-L3-06", CLASE_27, "L3", "Prueba en frenómetro de rodillos arroja fuerza de frenado deficiente en eje trasero con desequilibrio del 8% aceptable pero eficacia total en 42% (mínimo legal 50%). Al desmontar tambores traseros se evidencia cristalización severa del material de fricción de zapatas con textura vidriosa y polvo negro apelmazado por sobrecalentamiento.", "TECNICO", "frenometro_rodillos_42_porciento", "eficacia_42_porciento_baja|cristalizacion_vidriosa_zapatas|polvo_apelmazado", "falla_repartidor_frenado", "", "NO", "NO", "", "L3 frenómetro con 42% de eficacia por zapatas cristalizadas.")
    agregar("G27-L3-07", CLASE_27, "L3", "Al descender de la sierra se percibe pérdida progresiva de mordida de freno (fade térmico) con olor penetrante a material de fricción carbonizado. Al enfriarse el vehículo a temperatura ambiente el pedal recupera firmeza pero las pastillas emiten un chillido constante debido a la alteración química de la resina fenólica del compuesto cerámico.", "TALLER", "post_descenso_sierra", "perdida_mordida_fade|olor_ferodo_carbonizado|chillido_post_enfriamiento", "falla_liquido_ebullicion", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L3 fade térmico con daño de resina fenólica en pastillas.")
    agregar("G27-L3-08", CLASE_27, "L3", "Mi carro ase un rechinido como fierro viejo cuando piso el freno despacito. El mecanico le midio las pastillas delanteras y le quedan 1.5 milimetros de espesor. El disco esta planito y no tiembla nada al frenar en autopista.", "ERROR_ORTOGRAFICO", "frenado_despacio", "rechinido_fierro_viejo|pastillas_1_5mm|disco_plano_sin_temblor", "discos_alabeados", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L3 pastillas a 1.5 mm con disco plano sin temblor con ortografía informal.")
    agregar("G27-L3-09", CLASE_27, "L3", "Inspección de zapatas de freno de estacionamiento integradas en campana interior de disco ventilado (Drum-in-Hat): forro desgastado a 0.5 mm en el extremo inferior, provocando que la leva expansora gire a 85 grados sin lograr retención en pendiente del 18%. El cable de acero mantiene tensión y recorrido nominal.", "TECNICO", "inspeccion_drum_in_hat", "forro_0_5mm_drum_in_hat|leva_85_grados_sin_retencion|cable_tension_ok", "falla_cable_freno_mano", "", "NO", "NO", "", "L3 desgaste de zapatas drum-in-hat con cable OK.")
    agregar("G27-L3-10", CLASE_27, "L3", "Buenas tardes, cuando freno suave en mi Corolla suena un silbido chillón en la rueda derecha. El mecánico sacó la rueda y me mostró que la chapita de fierro que avisa el desgaste ya estaba pegada al disco raspando la orilla, pero el disco todavía tiene buen grosor.", "WHATSAPP", "inspeccion_taller_corolla", "silbido_chillon_frenar_suave|chapita_aviso_rozando_disco|disco_buen_grosor", "caliper_pegado", "", "NO", "SI", "Caliper de freno trabado o mordaza pegada (piston agarrotado)", "L3 chapa indicadora rozando disco en buen estado.")
    agregar("G27-L3-11", CLASE_27, "L3", "Inspección micrométrica en 4 puntos de pastillas delanteras: espesores de 2.1 mm, 2.0 mm, 1.9 mm y 2.1 mm demostrando desgaste homogéneo perfecto. El testigo acústico de acero inoxidable genera contacto a los 2.0 mm con la cara periférica del disco generando frecuencia de resonancia de 2.8 kHz en frenado a 30 km/h.", "TECNICO", "analisis_acustico_frecuencia", "espesor_homogeneo_2_0mm|resonancia_2_8khz|contacto_testigo_acero", "desgaste_irregular", "", "NO", "NO", "", "L3 desgaste parejo a 2.0 mm con resonancia acústica de aviso.")
    agregar("G27-L3-12", CLASE_27, "L3", "Frenado esponjoso inicial con necesidad de mayor recorrido de pedal en vehículo con frenos traseros de tambor. Se verificó que la distancia entre zapata y tambor excede los 1.8 mm (especificación 0.4 a 0.6 mm) debido a desgaste del forro a 1.2 mm y trinquete regulador trabado por suciedad de polvillo seco.", "TALLER", "ajuste_tambores_traseros", "distancia_zapata_tambor_1_8mm|forro_1_2mm|trinquete_trabado_polvillo", "aire_circuito_frenos", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L3 holgura de 1.8 mm por desgaste y trinquete sucio simula pedal largo.")
    agregar("G27-L3-13", CLASE_27, "L3", "Desgaste acelerado de pastillas semi-metálicas a los 12,000 km por uso en servicio urbano severo. El material residual mide 2.5 mm y presenta fisuras superficiales por choque térmico pero los calipers no presentan agarrotamiento y retraen libremente al aplicar 10 Nm de fuerza con el compresor de pistones.", "TECNICO", "inspeccion_retraccion_caliper", "pastillas_2_5mm_12000km|fisuras_termicas|caliper_retrae_libremente_10nm", "falla_caliper_pegado", "", "NO", "SI", "Caliper de freno trabado o mordaza pegada (piston agarrotado)", "L3 pistón retrae con 10 Nm descartando cáliper agarrotado.")
    agregar("G27-L3-14", CLASE_27, "L3", "El cliente reclama que al frenar fuerte se escucha raspado áspero y huele a quemado adelante. Se constató que la pastilla interior derecha perdió completamente la lámina de forro por desprendimiento del adhesivo de vulcanizado, quedando el metal desnudo rayando el disco con surcos de 0.8 mm de profundidad.", "TALLER", "desprendimiento_forro_vulcanizado", "desprendimiento_forro_adhesivo|metal_desnudo_surcos_0_8mm|raspado_aspero", "falla_caliper", "", "NO", "NO", "", "L3 desprendimiento de lámina de forro vulcanizada.")
    agregar("G27-L3-15", CLASE_27, "L3", "Evaluación de pastillas cerámicas tras 35,000 km: espesor en 2.8 mm cercano a la ranura de desahogo de gases (ranura casi borrada). El disco no presenta alabeo lateral medido con reloj comparador (salto en 0.02 mm) pero el coeficiente de frenada cayó 25% exigiendo mayor presión sobre el pedal.", "TECNICO", "inspeccion_ranura_desahogo", "ranura_desahogo_borrada_2_8mm|salto_disco_0_02mm_ok|coeficiente_frenada_bajo", "discos_alabeados", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L3 ranura borrada y salto lateral 0.02 mm descarta alabeo.")

    # =========================================================================
    # CLASE 28: Discos de freno alabeados o desgastados (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G28-L1-01", CLASE_28, "L1", "El volante me vibra bastante fuerte únicamente cuando piso el pedal del freno a velocidad.", "COTIDIANO", "frenado_velocidad", "vibracion_volante_al_frenar", "", "", "SI", "NO", "", "L1 vibración de timón exclusiva al frenar.")
    agregar("G28-L1-02", CLASE_28, "L1", "Hola, siento como un zapateo o pulsaciones en el pedal del freno al frenar en bajada.", "WHATSAPP", "bajada", "pulsacion_pedal_freno", "", "", "SI", "NO", "", "L1 zapateo de pedal al frenar.")
    agregar("G28-L1-03", CLASE_28, "L1", "Al pasar la mano por el disco de freno se siente una ceja o borde muy levantado.", "COTIDIANO", "inspeccion_tactil", "ceja_borde_disco_pronunciado", "", "", "SI", "NO", "", "L1 rebaba pronunciada por desgaste de disco.")
    agregar("G28-L1-04", CLASE_28, "L1", "El carro tiembla entero al frenar fuerte de 100 a 60 km/h en la carretera.", "TALLER", "frenada_carretera", "temblor_general_frenar_100kmh", "", "", "SI", "NO", "", "L1 vibración de carrocería en desaceleración.")
    agregar("G28-L1-05", CLASE_28, "L1", "Variación cíclica del par de frenado y pulsación hidráulica en línea delantera.", "TECNICO", "desaceleracion", "variacion_par_frenado|pulsacion_hidraulica", "", "", "SI", "NO", "", "L1 reporte técnico de DTV.")
    agregar("G28-L1-06", CLASE_28, "L1", "Siento que el freno frena a tirones como si agarrara y soltara rápidamente.", "COTIDIANO", "frenado_intermedio", "frenado_a_tirones_intermitente", "", "", "SI", "NO", "", "L1 frenado ondulante.")
    agregar("G28-L1-07", CLASE_28, "L1", "Los discos de freno se ven con manchas azules y violetas por todos lados.", "COTIDIANO", "inspeccion_visual", "manchas_azules_violetas_disco", "", "", "SI", "NO", "", "L1 manchas térmicas de cementita en disco.")
    agregar("G28-L1-08", CLASE_28, "L1", "Mi timon vibra feo cuando freno en pista rapida pero si no freno anda lisito.", "ERROR_ORTOGRAFICO", "frenado_autopista", "timon_vibra_al_frenar|lisito_sin_freno", "", "", "SI", "NO", "", "L1 vibración exclusiva con ortografía informal.")
    agregar("G28-L1-09", CLASE_28, "L1", "Buenas, cambié pastillas nuevas y ahora el pedal patea hacia arriba al frenar.", "WHATSAPP", "post_cambio_pastillas", "pedal_patea_post_pastillas_nuevas", "", "", "SI", "NO", "", "L1 pulsación evidenciada tras pastillas planas.")
    agregar("G28-L1-10", CLASE_28, "L1", "Desviación lateral de superficie de fricción del rotor fuera de especificación de taller.", "TECNICO", "inspeccion", "desviacion_lateral_rotor_fuera_rango", "", "", "SI", "NO", "", "L1 reporte técnico de runout excesivo.")

    # --- L2 (15 casos) ---
    agregar("G28-L2-01", CLASE_28, "L2", "Vibración severa en el volante al frenar entre 80 y 110 km/h; al soltar el freno el auto rueda suavemente a 100 km/h sin vibración alguna en la dirección.", "COTIDIANO", "frenado_80_110kmh", "vibracion_volante_al_frenar|suave_sin_frenar", "llantas_desbalanceadas", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L2 vibración exclusiva al frenar descarta balanceo de ruedas.")
    agregar("G28-L2-02", CLASE_28, "L2", "El pedal de freno late con pulsaciones rítmicas al detenerse en bajadas; los discos delanteros presentan rebaba perimetral de 2 mm y surcos profundos.", "TALLER", "frenada_bajada", "pulsaciones_ritmicas_pedal|rebaba_disco_2mm|surcos", "falla_pastillas_freno", "", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L2 pulsación y rebaba severa en discos.")
    agregar("G28-L2-03", CLASE_28, "L2", "Alabeo en disco ventilado delantero tras pasar por charco de agua con frenos calientes; el reloj palpador acusa deformación térmica visible al girar la maza.", "TECNICO", "choque_termico_charco", "deformacion_termica_charco|alabeo_girar_maza", "falla_rodamiento", "", "NO", "NO", "", "L2 choque térmico por enfriamiento brusco.")
    agregar("G28-L2-04", CLASE_28, "L2", "Hola, cuando voy a 90 km/h y toco apenas el freno el timón tironea de lado a lado; si acelero a 120 km/h sin pisar freno el timón está quietecito.", "WHATSAPP", "frenado_90kmh", "timon_tironea_al_tocar_freno|quieto_a_120kmh_sin_freno", "desalineacion_ruedas", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L2 volante tiembla solo con freno descarta alineación.")
    agregar("G28-L2-05", CLASE_28, "L2", "Medición de espesor de disco con micrómetro exterior marca 19.4 mm; el grabado mínimo del fabricante (Min TH) especifica 20.0 mm de descarte.", "TECNICO", "metrologia_disco_micrometro", "espesor_19_4mm_bajo_min_th_20mm", "falla_caliper", "", "NO", "NO", "", "L2 disco por debajo del espesor mínimo de seguridad.")
    agregar("G28-L2-06", CLASE_28, "L2", "Frenada ondulante a baja velocidad antes de llegar a cero; el auto frena por impulsos cíclicos sincronizados con el giro de la rueda delantera derecha.", "COTIDIANO", "detencion_cero", "frenada_ondulante_impulsos_ciclicos", "falla_sensor_abs", "", "NO", "SI", "Falla en sensor de velocidad de rueda ABS", "L2 variación de espesor de disco genera frenada a tirones.")
    agregar("G28-L2-07", CLASE_28, "L2", "Discos de freno con puntos duros de cementita azulada por sobrecalentamiento; la pastilla no muerde uniforme provocando trepidación en el pedal.", "TALLER", "frenada_severa", "puntos_cemento_azulada|trepidacion_pedal", "pastillas_vidriadas", "", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L2 manchas de cementita en pista de fricción.")
    agregar("G28-L2-08", CLASE_28, "L2", "Mi carro tironea el pedal del freno como si pataleara al frenar de 80 a 40 km/h en la panamericana. Si no piso el freno rueda sedita sin vibradera.", "ERROR_ORTOGRAFICO", "frenada_panamericana", "pedal_patalea_frenar_80_40|rueda_sedita_sin_freno", "llantas_desbalanceadas", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L2 pataleo en pedal exclusivo con freno con ortografía informal.")
    agregar("G28-L2-09", CLASE_28, "L2", "Buenas maestro, le cambiaron las pastillas a mi auto y ahora vibra el volante al frenar. En el taller me dicen que los discos están pandeados y debieron rectificarlos.", "WHATSAPP", "post_cambio_sin_rectificar", "vibra_volante_frenar|discos_pandeados_sin_rectificar", "pastillas_defectuosas", "", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L2 pastilla plana sobre disco alabeado delata vibración.")
    agregar("G28-L2-10", CLASE_28, "L2", "Reloj comparador colocado en la maza delantera izquierda registra alabeo lateral de 0.12 mm (tolerancia máxima OEM 0.05 mm); maza de rueda sin descentramiento.", "TECNICO", "medicion_reloj_comparador", "alabeo_0_12mm_tolerancia_0_05mm|maza_sin_salto", "falla_maza_rodaje", "", "NO", "NO", "", "L2 alabeo de 0.12 mm en disco con maza correcta.")
    agregar("G28-L2-11", CLASE_28, "L2", "Fuerte zumbido y vibración en toda la carrocería en desaceleraciones bruscas desde 120 km/h; los discos presentan fisuras radiales diminutas en la pista.", "COTIDIANO", "desaceleracion_120kmh", "zumbido_vibracion_carroceria|fisuras_radiales_disco", "falla_amortiguadores", "", "NO", "NO", "", "L2 fisuras por fatiga térmica en disco gastado.")
    agregar("G28-L2-12", CLASE_28, "L2", "Vibración al frenar no atribuible a tren delantero; bujes de trapecio y rótulas sin holgura pero la pista del disco tiene variación de espesor de 0.03 mm.", "TALLER", "inspeccion_suspension_frenos", "bujes_rotulas_ok|variacion_espesor_disco_0_03mm", "holgura_suspension", "", "NO", "NO", "", "L2 DTV de 0.03 mm con suspensión impecable.")
    agregar("G28-L2-13", CLASE_28, "L2", "El pedal de freno tiembla bajo el pie en frenadas moderadas pero el testigo ABS permanece apagado y no hay códigos de sensor de rueda en memoria.", "COTIDIANO", "frenada_moderada", "pedal_tiembla_frenada_moderada|testigo_abs_apagado", "falla_sistema_abs", "", "NO", "SI", "Falla en sensor de velocidad de rueda ABS", "L2 temblor mecánico de disco vs falso disparo ABS.")
    agregar("G28-L2-14", CLASE_28, "L2", "Inspección de disco ventilado: aletas interiores de ventilación corroídas y partidas por óxido provocando deformación térmica asimétrica bajo carga.", "TECNICO", "inspeccion_aletas_ventiladas", "aletas_ventilacion_partidas_oxido|deformacion_termica", "falla_pastillas", "", "NO", "NO", "", "L2 rotura de aletas de ventilación internas.")
    agregar("G28-L2-15", CLASE_28, "L2", "Pulsación rítmica en el pedal que incrementa su frecuencia proporcionalmente a la velocidad del vehículo al frenar; calipers flotantes deslizan sin traba.", "TALLER", "prueba_proporcional_velocidad", "pulsacion_proporcional_velocidad|caliper_desliza_bien", "caliper_agarrotado", "", "NO", "SI", "Caliper de freno trabado o mordaza pegada (piston agarrotado)", "L2 frecuencia proporcional al giro descarta mordaza trabada.")

    # --- L3 (15 casos) ---
    agregar("G28-L3-01", CLASE_28, "L3", "Toyota Hilux ingresa por vibración violenta en el volante y pedal al descender cuestas a 80 km/h aplicando frenos. Se montó reloj comparador con base magnética en la mangueta: el disco delantero derecho acusa un salto lateral (runout) de 0.14 mm (límite OEM 0.04 mm), mientras que el descentramiento de la brida de la maza es de apenas 0.01 mm normal. El espesor del disco es de 26.8 mm (mínimo 26.0 mm), procediéndose a rectificado sobre maza.", "TECNICO", "metrologia_reloj_comparador_mangueta", "runout_0_14mm_disco|descentramiento_maza_0_01mm_ok|vibracion_80kmh_bajada", "llantas_desbalanceadas", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L3 runout de 0.14 mm con maza en 0.01 mm descarta llantas.")
    agregar("G28-L3-02", CLASE_28, "L3", "Vehículo presenta sacudidas cíclicas en el pedal de freno en frenadas suaves de 50 a 0 km/h sin que el volante vibre. Se midió la variación de espesor del disco (DTV - Disc Thickness Variation) con micrómetro digital en 8 puntos equidistantes de la pista, registrándose espesor máximo de 22.045 mm y mínimo de 22.015 mm (delta de 0.030 mm, superando el límite de 0.012 mm). Las pastillas son nuevas y los bujes de horquilla no tienen juego.", "TECNICO", "medicion_dtv_8_puntos", "dtv_0_030mm_excesivo|espesor_variable_8puntos|sacudida_pedal_50_a_0", "holgura_bujes_horquilla", "", "NO", "NO", "", "L3 DTV de 0.030 mm en 8 puntos con micrómetro digital.")
    agregar("G28-L3-03", CLASE_28, "L3", "Conductor refiere que al frenar a más de 100 km/h el volante tiembla tanto que parece salirse. Se descartó desbalanceo rodando el auto a 120 km/h con acelerador constante donde la dirección no presenta ninguna vibración. Al aplicar apenas 15 bar de presión de frenado el timón entra en resonancia; los discos delanteros muestran zonas alternadas de pulido espejo y áreas oscuras de cementita provocadas por torque disparejo en pernos de rueda.", "TALLER", "descarte_balanceo_120kmh_crucero", "crucero_120kmh_sin_vibracion|resonancia_15bar_frenado|manchas_cementita_torque", "llantas_desbalanceadas", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L3 crucero a 120 km/h perfecto descarta balanceo; tiembla solo a 15 bar.")
    agregar("G28-L3-04", CLASE_28, "L3", "Medición metrológica en disco de freno macizo trasero: espesor residual de 8.2 mm en la zona de pista (límite del fabricante estampado en el lomo MIN TH 9.0 mm) con labio exterior perimetral cortante de 1.8 mm de altura. El disco presenta una microfisura radial pasante de 12 mm de longitud desde el borde periférico hacia el centro originada por fatiga térmica.", "TECNICO", "inspeccion_micrometro_fisura", "espesor_8_2mm_bajo_min_9_0mm|rebaba_1_8mm|microfisura_radial_12mm", "falla_pastillas_freno", "", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L3 espesor 8.2 mm por debajo de Min TH 9.0 mm con fisura radial.")
    agregar("G28-L3-05", CLASE_28, "L3", "Hola maestro, tengo un Sentra 2019. Cuando manejo en pista lisa a 100 va suave como seda, pero piso el freno y el pedal zapatea feo y el timón vibra de lado a lado. En la llantería balancearon las 4 ruedas y alinearon pero sigue exactamente igual; me dicen que los discos se torcieron porque lavé el carro saliendo de la carretera.", "WHATSAPP", "post_lavado_caliente_sentra", "suave_a_100_sin_freno|zapateo_pedal_frenar|balanceo_alineacion_descartado", "llantas_desbalanceadas", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L3 choque térmico en lavado post-carretera tras descartar balanceo.")
    agregar("G28-L3-06", CLASE_28, "L3", "Evaluación de vibración de frenado con acelerómetro triaxial montado en la pinza de freno: pico de aceleración de 3.2 G en eje longitudinal a frecuencia de 18 Hz (coincidente con 1x velocidad de giro de rueda a 80 km/h). Al desmontar el disco se encontró óxido acumulado de 0.08 mm entre la cara interior de la campana del disco y la superficie de apoyo de la maza de rueda.", "TECNICO", "analisis_acelerometro_oxido_maza", "aceleracion_3_2g_a_18hz|oxido_0_08mm_cara_maza|pico_frecuencia_rueda", "falla_rodamiento_rueda", "", "NO", "NO", "", "L3 óxido entre disco y maza de 0.08 mm genera runout inducido.")
    agregar("G28-L3-07", CLASE_28, "L3", "Discos delanteros ventilados ranurados y perforados presentan decoloración térmica azul en 360 grados y combado de 0.16 mm en periferia tras sesión de pista. Las pastillas de competición tienen 7 mm pero el disco perdió planitud dimensional; al aplicar frenos suaves a 60 km/h la presión hidráulica oscila entre 12 y 22 bar rítmicamente en el manómetro de prueba.", "TALLER", "oscilacion_presion_hidraulica_manometro", "alabeo_0_16mm_periferia|presion_oscila_12_a_22bar|manchas_azules", "falla_bomba_frenos", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L3 oscilación manométrica de 12 a 22 bar por alabeo de 0.16 mm.")
    agregar("G28-L3-08", CLASE_28, "L3", "Mi camioneta tiembla horrible el volante cuando freno de golpe en la bajada de San Bartolo. En linea recta corre a 110 sin soltar el timon y no tiembla nada de nada. El mecanico puso un reloj con aguja en el disco y la aguja bailaba casi 15 lineas de milimetro.", "ERROR_ORTOGRAFICO", "bajada_san_bartolo", "tiembla_al_frenar_bajada|110_recto_sin_temblor|reloj_aguja_baila_15_lineas", "llantas_desbalanceadas", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L3 reloj palpador confirma alabeo tras descartar tren delantero.")
    agregar("G28-L3-09", CLASE_28, "L3", "Alabeo térmico en disco ventilado izquierdo por torque desigual en tuercas de rueda: tuercas ajustadas entre 75 Nm y 160 Nm con pistola neumática sin torquímetro (especificación 110 Nm uniforme). Tras 1,500 km la brida del disco adoptó deformación elástica permanente de 0.11 mm provocando pulsación en pedal.", "TECNICO", "torque_desigual_pernos", "torque_desigual_75_a_160nm|deformacion_permanente_0_11mm|pulsacion", "falla_maza", "", "NO", "NO", "", "L3 deformación por apriete disparejo con pistola neumática.")
    agregar("G28-L3-10", CLASE_28, "L3", "Buenas tardes, tengo una Tucson 2017. Al frenar en autopista el pedal me patea el pie como si el ABS entrara pero el foco del ABS no prende en el tablero. En el taller escanearon y no hay códigos de sensor de rueda; midieron los discos con micrómetro y están ovalados con desgaste desparejo en la cara interna.", "WHATSAPP", "diagnostico_escaner_abs_ok", "pedal_patea_pie|foco_abs_apagado_sin_dtc|discos_ovalados_micrometro", "falla_sistema_abs", "", "NO", "SI", "Falla en sensor de velocidad de rueda ABS", "L3 zapateo mecánico en pedal con escáner ABS en 0 DTC.")
    agregar("G28-L3-11", CLASE_28, "L3", "Prueba de frenado a 100 km/h: desaceleración longitudinal inestable oscilando entre 0.45 G y 0.65 G sin modular el pedal. La inspección termográfica con cámara infrarroja revela bandas térmicas circunferenciales a 420°C alternadas con bandas frías a 210°C en la pista del rotor debido a contacto discontinuo de la pastilla sobre el disco deformado.", "TECNICO", "termografia_infrarroja_rotores", "desaceleracion_oscilante_0_45_0_65g|bandas_termicas_420c_210c", "falla_servofreno", "", "NO", "SI", "Falla en servofreno (booster) o linea de vacio", "L3 termografía revela gradiente térmico de 210°C por contacto discontinuo.")
    agregar("G28-L3-12", CLASE_28, "L3", "Rectificado de discos en torno paralelo: se constata espesor inicial de 21.2 mm; para eliminar el alabeo de 0.13 mm y los surcos se requiere maquinar 1.4 mm en total, lo cual dejaría el disco en 19.8 mm por debajo de la cota mínima de 20.4 mm. Se dictamina descarte y sustitución obligatoria por límite de desgaste estructural alcanzado.", "TALLER", "proceso_rectificado_torno", "salto_0_13mm_requiere_1_4mm|quedaria_19_8mm_bajo_min_20_4|descarte", "falla_pastillas", "", "NO", "NO", "", "L3 descarte técnico por cota mínima excedida en rectificado.")
    agregar("G28-L3-13", CLASE_28, "L3", "Vibración de alta frecuencia en el pedal de freno al frenar suavemente en pendientes: la medición con rugosímetro arroja rugosidad Ra de 4.8 micrómetros (especificación OEM Ra 0.8 a 1.5 um) debido a mecanizado previo defectuoso con avance de herramienta excesivo, provocando efecto de rosca sobre el forro de la pastilla.", "TECNICO", "metrologia_rugosimetro", "rugosidad_ra_4_8um_excesiva|efecto_rosca_forro|vibracion_alta_frecuencia", "falla_pastillas_freno", "", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L3 rugosidad Ra de 4.8 um por mecanizado defectuoso.")
    agregar("G28-L3-14", CLASE_28, "L3", "El cliente reclama que después de cambiar rótulas y terminales el auto sigue vibrando al frenar fuerte. Se montó comparador en el disco izquierdo registrándose 0.10 mm de alabeo en disco y 0.005 mm en maza; al rotar el disco 180 grados sobre la maza el alabeo se mantiene en 0.10 mm confirmando deformación intrínseca del rotor y no de montaje.", "TALLER", "prueba_rotacion_180_grados", "alabeo_0_10mm_persiste_rotacion_180|maza_0_005mm_ok", "falla_suspension_rotulas", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L3 prueba de rotación a 180° confirma alabeo del disco y no de maza.")
    agregar("G28-L3-15", CLASE_28, "L3", "Rotor de freno ventilado de 320 mm presenta alabeo lateral de 0.09 mm y variación de grosor periférico de 0.022 mm. En dinamómetro de chasis la fuerza de frenado presenta ondulación senoidal de 450 N a 70 km/h con presión hidráulica constante de 25 bar en la línea principal de freno.", "TECNICO", "dinamometro_chasis_fuerza_frenado", "ondulacion_senoidal_450n|salto_0_09mm_dtv_0_022mm|presion_25bar_constante", "falla_bomba_frenos", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L3 fuerza de frenado ondulante senoidal de 450 N en dinamómetro.")

    # =========================================================================
    # CLASE 29: Falla en servofreno (booster) o linea de vacio (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G29-L1-01", CLASE_29, "L1", "El pedal de freno se puso durísimo como una piedra y tengo que pararme con fuerza.", "COTIDIANO", "frenado", "pedal_duro_como_piedra", "", "", "SI", "NO", "", "L1 pedal duro por falta de asistencia.")
    agregar("G29-L1-02", CLASE_29, "L1", "Hola, cada vez que piso el pedal del freno suena como un soplido de aire adentro.", "WHATSAPP", "ralenti", "soplido_aire_al_pisar_freno", "", "", "SI", "NO", "", "L1 silbido de diafragma de booster.")
    agregar("G29-L1-03", CLASE_29, "L1", "Al pisar el freno en ralentí el motor empieza a temblar y se quiere apagar.", "COTIDIANO", "ralenti_frenado", "motor_tiembla_al_pisar_freno", "", "", "SI", "NO", "", "L1 fuga de vacío que descalibra ralentí.")
    agregar("G29-L1-04", CLASE_29, "L1", "El carro frena muy poco y el pedal casi no baja nada al apretarlo.", "TALLER", "frenado", "frena_poco|pedal_no_baja", "", "", "SI", "NO", "", "L1 falta de amplificación de fuerza.")
    agregar("G29-L1-05", CLASE_29, "L1", "Pérdida de presión de vacío en el acumulador neumático del servofreno.", "TECNICO", "diagnostico", "perdida_vacio_servofreno", "", "", "SI", "NO", "", "L1 reporte técnico de depresión insuficiente.")
    agregar("G29-L1-06", CLASE_29, "L1", "Siento que el pedal está tieso desde la mañana y no cede nada al dar arranque.", "COTIDIANO", "arranque_manana", "pedal_tieso_no_cede_al_arranque", "", "", "SI", "NO", "", "L1 falla en prueba de retención de vacío.")
    agregar("G29-L1-07", CLASE_29, "L1", "Se escucha un silbido continuo debajo del tablero en la zona de los pedales.", "COTIDIANO", "marcha", "silbido_continuo_zona_pedales", "", "", "SI", "NO", "", "L1 fuga en retén o fuelle del émbolo de entrada.")
    agregar("G29-L1-08", CLASE_29, "L1", "El freno se puso como un palo de duro y el carro no se detiene rapido.", "ERROR_ORTOGRAFICO", "detencion", "freno_como_palo_duro|no_detiene_rapido", "", "", "SI", "NO", "", "L1 pedal duro con ortografía informal.")
    agregar("G29-L1-09", CLASE_29, "L1", "Buenas, pisando el freno se acelera el motor a 1500 revoluciones solo.", "WHATSAPP", "ralenti", "motor_se_acelera_al_pisar_freno", "", "", "SI", "NO", "", "L1 entrada masiva de aire no medido.")
    agregar("G29-L1-10", CLASE_29, "L1", "Ausencia de amplificación neumática de fuerza en el actuador tándem de frenos.", "TECNICO", "inspeccion", "ausencia_amplificacion_neumatica", "", "", "SI", "NO", "", "L1 reporte técnico de vacío.")

    # --- L2 (15 casos) ---
    agregar("G29-L2-01", CLASE_29, "L2", "Pedal de freno extremadamente rígido que exige esfuerzo físico excesivo; al apagar el motor y bombear no se siente ninguna diferencia de dureza.", "COTIDIANO", "frenado_urbano", "pedal_rigido_esfuerzo_excesivo|sin_cambio_al_bombear", "pedal_esponjoso", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L2 pedal duro constante vs pedal esponjoso.")
    agregar("G29-L2-02", CLASE_29, "L2", "Silbido fuerte de fuga de aire en la cabina al pisar el pedal de freno en ralentí; el motor se desestabiliza con DTC P0171 por entrada de aire pirata.", "TALLER", "ralenti_frenado", "silbido_cabina_al_pisar|motor_inestable_dtc_p0171", "falla_sensor_oxigeno", "P0171", "NO", "SI", "Falla en sensor de oxigeno o mezcla rica", "L2 diafragma perforado ingresa aire falso con P0171.")
    agregar("G29-L2-03", CLASE_29, "L2", "La manguera de vacío del booster al múltiple de admisión está cuarteada y colapsada por aplastamiento térmico, anulando el vacío hacia el servofreno.", "TECNICO", "inspeccion_vano_motor", "manguera_vacio_cuarteada_colapsada|sin_vacio_booster", "falla_bomba_vacio", "", "NO", "NO", "", "L2 colapso físico de manguera de succión.")
    agregar("G29-L2-04", CLASE_29, "L2", "Hola, mi carro frena bien una sola vez, pero si tengo que frenar dos veces seguidas el pedal se pone como roca y ya no frena nada.", "WHATSAPP", "frenadas_sucesivas", "pedal_roca_segunda_frenada|no_retiene_vacio", "falla_pastillas", "", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L2 incapacidad de mantener vacío en frenadas seguidas.")
    agregar("G29-L2-05", CLASE_29, "L2", "Válvula check antirretorno del servofreno atascada en posición cerrada; no permite generar depresión en la cámara de vacío del servofreno.", "TECNICO", "prueba_valvula_check", "valvula_check_atascada_cerrada|sin_depresion_camara", "falla_cilindro_maestro", "", "NO", "NO", "", "L2 válvula antirretorno bloqueada.")
    agregar("G29-L2-06", CLASE_29, "L2", "Al pisar el freno a fondo el pedal se mantiene arriba durísimo; el nivel de líquido en el depósito está al máximo y no hay fugas en las ruedas.", "COTIDIANO", "frenado_emergencia", "pedal_arriba_durisimo|nivel_liquido_maximo_sin_fugas", "fuga_liquido", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L2 pedal duro con nivel OK descarta fuga.")
    agregar("G29-L2-07", CLASE_29, "L2", "Motor diésel 2.5 con bomba de vacío en el alternador; la paleta interna se rompió entregando solo 5 inHg de vacío en lugar de los 20 inHg requeridos.", "TALLER", "medicion_bomba_vacio", "bomba_vacio_5inhg_baja|paleta_rota", "falla_alternador", "", "NO", "NO", "", "L2 déficit de vacío por depresor mecánico.")
    agregar("G29-L2-08", CLASE_29, "L2", "Mi auto ase pssss cada ves que piso el freno y el pedal se puso como piedra para frenar en los semaforos.", "ERROR_ORTOGRAFICO", "detencion_semaforo", "sonido_pssss_freno|pedal_como_piedra", "pedal_esponjoso", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L2 silbido pssss con pedal rígido con ortografía informal.")
    agregar("G29-L2-09", CLASE_29, "L2", "Buenas maestro, en frío el pedal tiene buena asistencia pero al calentar el motor se endurece totalmente y el motor ratea al frenar.", "WHATSAPP", "motor_caliente", "pedal_endurece_en_caliente|motor_ratea_al_frenar", "falla_bobinas", "", "NO", "SI", "Falla en bujias o bobinas de encendido (misfire)", "L2 fuga térmica en servofreno altera mezcla en caliente.")
    agregar("G29-L2-10", CLASE_29, "L2", "Prueba de hermeticidad de servofreno: la depresión cae de 18 inHg a 0 inHg en menos de 5 segundos tras cortar el contacto del motor.", "TECNICO", "prueba_vacuometro", "depresion_cae_18_a_0inhg_5seg|fuga_interna_booster", "falla_valvula_purgado", "", "NO", "NO", "", "L2 caída abrupta de vacío en prueba de retención.")
    agregar("G29-L2-11", CLASE_29, "L2", "DTC C1246 referente a presión baja del sensor del servofreno en vehículo con start-stop; el motor no se apaga en paradas por falta de asistencia de vacío.", "TECNICO", "diagnostico_start_stop", "dtc_c1246|presion_baja_sensor_booster|start_stop_inhabilitado", "falla_bateria", "C1246", "NO", "NO", "", "L2 código C1246 por baja presión de servofreno.")
    agregar("G29-L2-12", CLASE_29, "L2", "El pedal de freno no baja al dar arranque con el pie apoyado; prueba estándar de servofreno fallida confirmando nula amplificación por vacío.", "TALLER", "prueba_arranque_pie_apoyado", "pedal_no_baja_al_arrancar|falla_prueba_servofreno", "falla_bomba_frenos", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L2 prueba clásica de encendido con pie en pedal fallida.")
    agregar("G29-L2-13", CLASE_29, "L2", "Fuelle protector del émbolo de mando roto permitiendo ingreso de polvo y desgaste prematuro del retén de estanqueidad de la válvula de aire atmosférico.", "TECNICO", "inspeccion_fuelle_embolo", "fuelle_roto_polvo|desgaste_reten_valvula_atmosferica", "falla_cilindro_maestro", "", "NO", "NO", "", "L2 degradación de sello atmosférico en pedal.")
    agregar("G29-L2-14", CLASE_29, "L2", "Al pisar el freno en bajada pronunciada el vehículo casi no desacelera requiriendo activar el freno de mano; las pastillas y discos están nuevos.", "COTIDIANO", "frenado_emergencia_bajada", "no_desacelera_pedal_duro|pastillas_discos_nuevos", "falla_pastillas", "", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L2 componentes de fricción nuevos pero pedal tieso.")
    agregar("G29-L2-15", CLASE_29, "L2", "Presencia de aceite de motor dentro de la cámara de vacío del servofreno proveniente de la manguera de respiradero del depresor de vacío.", "TALLER", "desarme_booster", "aceite_motor_camara_booster|diafragma_degradado_aceite", "fuga_liquido_frenos", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L2 diafragma degradado por absorción de aceite de motor.")

    # --- L3 (15 casos) ---
    agregar("G29-L3-01", CLASE_29, "L3", "En un Toyota Yaris el cliente reclama que el pedal de freno se puso durísimo y el motor ratea cada vez que frena en los cruces. Se conectó vacuómetro con conector en 'T' entre el múltiple y el booster: el múltiple genera 19 inHg estables en ralentí, pero al pisar el pedal de freno el vacío colapsa instantáneamente a 4 inHg mientras se escucha un silbido continuo por debajo del pedalier. El escáner registra STFT en +25% y DTC P0171 provocado por la entrada masiva de aire no medido a través del diafragma roto del servofreno.", "TECNICO", "diagnostico_vacuometro_en_t", "vacio_colapsa_19_a_4inhg_frenar|silbido_pedalier|stft_mas_25_dtc_p0171|diafragma_roto", "falla_sensor_maf", "P0171", "NO", "SI", "Falla en sensor de oxigeno o mezcla rica", "L3 vacuómetro en T acusa caída a 4 inHg y P0171 por diafragma roto.")
    agregar("G29-L3-02", CLASE_29, "L3", "Camioneta Nissan Navara 2.5 Diésel ingresa con pedal de frenos rígido como un bloque de cemento. Se midió la depresión generada por la bomba de vacío mecánica adosada al alternador con vacuómetro directo marcando solo 4 inHg (especificación OEM 21 a 24 inHg). Al desarmar la bomba de vacío se constató que la paleta rotativa de grafito se partió en tres pedazos bloqueando el canal de lubricación. Tras reemplazar la bomba de vacío el sistema recuperó 22 inHg y el pedal retornó a su suavidad original.", "TALLER", "medicion_depresor_navara", "depresion_4inhg_baja_vs_22inhg|paleta_grafito_rota|bomba_vacio_alternador", "falla_servofreno_vacio", "", "NO", "NO", "", "L3 rotura de paleta de grafito en depresor con 4 inHg vs 22 inHg.")
    agregar("G29-L3-03", CLASE_29, "L3", "Prueba secuencial de retención de vacío en servofreno: 1) Con motor en marcha se alcanza régimen térmico normal; 2) Se apaga el motor y se espera 15 minutos; 3) Al aplicar el pedal por primera vez se encuentra completamente rígido sin ningún recorrido de asistencia residual. Se desmontó la válvula antirretorno plástica de la manguera y al soplar por ambos lados el aire pasa libremente en ambos sentidos debido a rotura del asiento cónico interno de goma.", "TECNICO", "prueba_retencion_15min_valvula_check", "sin_asistencia_residual_15min|valvula_check_pasa_aire_ambos_lados|asiento_roto", "falla_cilindro_maestro", "", "NO", "NO", "", "L3 válvula antirretorno no retiene vacío tras 15 minutos.")
    agregar("G29-L3-04", CLASE_29, "L3", "Vehículo con motor turbo 1.4 TSI presenta pedal de freno duro exclusivamente durante aceleraciones y subidas prolongadas. El sistema utiliza una bomba de vacío eléctrica auxiliar para compensar la falta de vacío del motor en fase de sobrealimentación positiva. Con el escáner se registró código P0556 referente a rango del sensor de vacío del booster; la bomba eléctrica auxiliar no arranca debido a que el relé de accionamiento en caja de fusibles tiene los contactos quemados.", "TECNICO", "diagnostico_bomba_electrica_tsi", "dtc_p0556|bomba_electrica_no_arranca|rele_contactos_quemados|presion_turbo_positiva", "falla_turbo_valvula", "P0556", "NO", "NO", "", "L3 P0556 y relé quemado en bomba de vacío eléctrica para motor turbo.")
    agregar("G29-L3-05", CLASE_29, "L3", "Hola maestro, tengo un Kia Rio. Cuando freno en una esquina suena un zumbido de aire chhhh por los pedales y el motor empieza a temblar feo como si se fuera a apagar. El mecánico le desconectó la manguera del booster y le tapó la entrada al motor con un corcho y el motor emparejó perfecto en ralentí.", "WHATSAPP", "prueba_desconexion_booster", "silbido_chhhh_pedales|motor_tiembla_frenar|tapar_manguera_empareja_motor", "falla_cuerpo_mariposa", "", "NO", "SI", "Cuerpo de aceleracion o valvula IAC sucia", "L3 aislamiento de manguera de booster estabiliza motor descartando IAC.")
    agregar("G29-L3-06", CLASE_29, "L3", "Pérdida súbita de asistencia de frenado a velocidad crucero. Al inspeccionar la línea de vacío se encontró que la manguera rígida de poliamida rozó contra el soporte de la batería hasta perforarse con un orificio de 5 mm. El cilindro maestro no presenta fugas de líquido hidráulico, las pastillas tienen 8 mm de espesor y el circuito hidráulico se encuentra completamente purgado sin burbujas.", "TALLER", "inspeccion_linea_poliamida_perforada", "manguera_poliamida_perforada_5mm|liquido_ok_pastillas_8mm|sin_burbujas_purga", "fuga_hidraulica_frenos", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L3 orificio de 5 mm en línea de vacío con hidráulica 100% sana.")
    agregar("G29-L3-07", CLASE_29, "L3", "DTC C1246 y C1256 en vehículo con servofreno activo y sensor de presión de vacío integrado en el booster. La lectura en línea de datos acusa presión atmosférica permanente de 101 kPa en la cámara del servofreno aún con motor a 3000 rpm. La inspección física reveló que el diafragma de goma elastomérica se despegó perimetralmente de la carcasa metálica engrapada.", "TECNICO", "linea_datos_presion_101kpa", "dtc_c1246_c1256|presion_101kpa_sin_depresion|diafragma_despegado_carcasa", "falla_modulo_abs", "C1246", "NO", "SI", "Falla en sensor de velocidad de rueda ABS", "L3 código C1246 con presión de 101 kPa por diafragma despegado.")
    agregar("G29-L3-08", CLASE_29, "L3", "Mi carro ase un soplido horrible por los pedales cuando piso el freno y se pone duro como fierro solido. El mecanico le puso la pistola de bacio y la aguja no sube nada de nada porque la bolsa de adentro del tambor negro esta rota.", "ERROR_ORTOGRAFICO", "prueba_pistola_vacio", "soplido_pedales|duro_fierro_solido|pistola_vacio_no_retiene|bolsa_rota", "falla_liquido_frenos", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L3 pistola Mityvac no genera vacío por diafragma roto con ortografía informal.")
    agregar("G29-L3-09", CLASE_29, "L3", "Inspección de servofreno de doble diafragma en vehículo pesado: al aplicar fuerza de 40 kg sobre el pedal la presión hidráulica generada en la salida del cilindro maestro alcanza apenas 35 bar (especificación con asistencia normal 95 a 110 bar). El vacío de alimentación desde el múltiple mide 22 inHg correcto, diagnosticándose rotura del sello interno del émbolo de reacción.", "TECNICO", "banco_pruebas_presion_hidraulica", "fuerza_40kg_genera_solo_35bar_vs_100bar|vacio_22inhg_ok|sello_embolo_roto", "falla_bomba_principal", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L3 presión de salida 35 bar vs 100 bar con vacío OK descarta bomba.")
    agregar("G29-L3-10", CLASE_29, "L3", "Buenas, en mi camioneta Ford el freno se puso duro y no frena casi nada. En el taller revisaron y la bomba de vacío mecánica que va pegada al motor se amarró y partió la faja chica que la mueve. Las 4 ruedas tienen pastillas con media vida y no hay fuga de líquido.", "WHATSAPP", "bomba_vacio_amarrada_faja_rota", "freno_duro_no_frena|bomba_vacio_amarrada|faja_rota|pastillas_media_vida_sin_fuga", "desgaste_pastillas", "", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L3 gripado de depresor mecánico con faja rota descartando pastillas.")
    agregar("G29-L3-11", CLASE_29, "L3", "Evaluación de tiempo de respuesta de asistencia neumática: tras soltar el pedal de freno el tiempo de restablecimiento de vacío en la cámara posterior tarda 4.8 segundos (especificación menor a 0.5 s) debido a colapso parcial de la válvula de aireación atmosférica con filtro de fieltro colmatado de lodo seco bajo el pedalier.", "TECNICO", "tiempo_restablecimiento_vacio", "tiempo_4_8s_vs_0_5s|filtro_fieltro_colmatado_lodo|valvula_aireacion_lenta", "falla_caliper_pegado", "", "NO", "SI", "Caliper de freno trabado o mordaza pegada (piston agarrotado)", "L3 filtro de fieltro sucio demora restablecimiento de vacío a 4.8s.")
    agregar("G29-L3-12", CLASE_29, "L3", "DTC P0555 en vehículo con motor EcoBoost; el sensor de presión del servofreno registra voltaje fijo de 0.2V indicando circuito abierto en línea de 5V de referencia. Al corregir el cableado el sensor mide 28 kPa absolutos confirmando que la asistencia mecánica de vacío está operativa y el pedal responde suavemente.", "TECNICO", "diagnostico_linea_5v_p0555", "dtc_p0555|voltaje_0_2v_referencia_abierta|presion_28kpa_operativa", "falla_booster_mecanico", "P0555", "NO", "NO", "", "L3 código P0555 por circuito eléctrico del sensor con vacío OK.")
    agregar("G29-L3-13", CLASE_29, "L3", "El cliente ingresa manifestando que para frenar el vehículo debe apoyarse contra el respaldo del asiento con toda su fuerza. Se midió carrera de pedal encontrando solo 25 mm de desplazamiento rígido sin rebote elástico. Al desmontar el booster se descubrió corrosión severa en el resorte de retorno interior y oxidación en las paredes del cilindro por ingreso de agua de lluvia por el torpedo.", "TALLER", "desarme_booster_oxido_torpedo", "fuerza_extrema_apoyo_respaldo|carrera_25mm_rigida|resorte_oxidado_agua_torpedo", "falla_bomba_frenos", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L3 corrosión interna por ingreso de agua de torpedo.")
    agregar("G29-L3-14", CLASE_29, "L3", "Frenos endurecidos en motor diésel Common Rail tras cambio de alternador. Se verificó que el tubo de retorno de aceite de la bomba de vacío mecánica quedó estrangulado por mala posición, provocando contrapresión de lubricación que trabó las paletas rotativas del depresor impidiendo generar más de 2 inHg de vacío.", "TECNICO", "tubo_retorno_estrangulado_depresor", "tubo_retorno_aceite_estrangulado|contrapresion_traba_paletas|vacio_2inhg", "falla_alternador", "", "NO", "NO", "", "L3 estrangulamiento de retorno de aceite anula depresor a 2 inHg.")
    agregar("G29-L3-15", CLASE_29, "L3", "Prueba de esfuerzo en pedal dinamométrico: para alcanzar desaceleración de 0.6 G se requieren 680 N de fuerza sobre el pedal (especificación con servofreno operativo 180 a 220 N). La línea de vacío registra 0 inHg debido a que el eyector venturi montado en la admisión se taponó con residuos carbonosos del sistema PCV.", "TALLER", "pedal_dinamometrico_680n_fuerza", "fuerza_680n_vs_200n|desaceleracion_0_6g|eyector_venturi_taponado_pcv", "desgaste_pastillas", "", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L3 pedal dinamométrico requiere 680 N por eyector venturi taponado.")

    return casos
