"""
Generador de registros para Lote 10 de Fase 10 - Clases 55 a 58 (CARROCERIA_NEUMATICA).
Cubre exactamente 160 registros:
- Clase 55: Falla electrica del cierre centralizado o actuador de puerta (40 casos: 10 L1, 15 L2, 15 L3)
- Clase 56: Cerradura, chapa o pestillo mecanico de puerta trabado o desalineado (40 casos: 10 L1, 15 L2, 15 L3)
- Clase 57: Elevalunas electrico o guaya de alzacristales rota o trabada (40 casos: 10 L1, 15 L2, 15 L3)
- Clase 58: Limpiaparabrisas o motor pluma quemado (40 casos: 10 L1, 15 L2, 15 L3)
IDs: F10-L10-0041 a F10-L10-0200.
Macro: CARROCERIA_NEUMATICA.
"""

from typing import List, Dict

CLASE_55 = "Falla electrica del cierre centralizado o actuador de puerta"
CLASE_56 = "Cerradura, chapa o pestillo mecanico de puerta trabado o desalineado"
CLASE_57 = "Elevalunas electrico o guaya de alzacristales rota o trabada"
CLASE_58 = "Limpiaparabrisas o motor pluma quemado"

# Contrastivas
CLASE_47 = "Alternador defectuoso o placa de diodos quemada"
CLASE_48 = "Bateria descargada o bornes sulfatados"
CLASE_53 = "Fuga parasita de corriente en reposo (consumo nocturno de bateria)"

MACRO_CARROCERIA = "CARROCERIA_NEUMATICA"
FUENTE = "SINTETICO_IA"


def obtener_casos_55_58(offset: int = 41) -> List[Dict[str, str]]:
    casos = []
    idx = offset

    def agregar(id_grupo, clase, nivel, texto, lenguaje, condicion, presentes, negados, dtc, req_preg, es_cont, clase_cont, obs):
        nonlocal idx
        reg_id = f"F10-L10-{idx:04d}"
        casos.append({
            "id": reg_id,
            "id_grupo": id_grupo,
            "clase_objetivo": clase,
            "macro_sistema": MACRO_CARROCERIA,
            "nivel_informacion": nivel,
            "texto_usuario": texto,
            "tipo_lenguaje": lenguaje,
            "condicion_operacion": condicion,
            "sintomas_presentes": presentes,
            "sintomas_negados": negados,
            "dtc": dtc,
            "requiere_pregunta": req_preg,
            "es_contrastivo": es_cont,
            "clase_contrastiva": clase_cont,
            "fuente": FUENTE,
            "observaciones": obs
        })
        idx += 1

    # =========================================================================
    # CLASE 55: Falla electrica del cierre centralizado o actuador de puerta
    # =========================================================================
    # L1 (10 casos)
    agregar("G-10-55-01", CLASE_55, "L1", "Una de las puertas no echa seguro cuando aprieto el control.", "COLOQUIAL", "BLOQUEO_REMOTO", "puerta_no_asegura_control", "NO_REPORTA", "", "SI", "NO", "", "L1 no asegura con control")
    agregar("G-10-55-02", CLASE_55, "L1", "El pestillo de la puerta del chofer no se mueve con el boton central.", "COLOQUIAL", "BOTON_INTERIOR", "pestillo_inmovil_boton", "NO_REPORTA", "", "SI", "NO", "", "L1 pestillo inmovil por boton")
    agregar("G-10-55-03", CLASE_55, "L1", "Se escucha un zumbido debil en la puerta pero el seguro no sube.", "COLOQUIAL", "ACCIONAMIENTO", "zumbido_sin_apertura", "NO_REPORTA", "", "SI", "NO", "", "L1 zumbido actuador debil")
    agregar("G-10-55-04", CLASE_55, "L1", "El cierre de las puertas se volvio loco, abre y cierra solo.", "COLOQUIAL", "REPOSO", "cierre_ciclico_espasmico", "NO_REPORTA", "", "SI", "NO", "", "L1 apertura ciclica erratica")
    agregar("G-10-55-05", CLASE_55, "L1", "No bajan los seguros de atras con la llave ni con el mando.", "COLOQUIAL", "BLOQUEO_PUERTAS", "seguros_traseros_inmoviles", "NO_REPORTA", "", "SI", "NO", "", "L1 seguros traseros no responden")
    agregar("G-10-55-06", CLASE_55, "L1", "El seguro del copiloto no reacciona electricamente al cerrar el auto.", "COLOQUIAL", "BLOQUEO_PUERTAS", "sin_reaccion_electrica_copiloto", "NO_REPORTA", "", "SI", "NO", "", "L1 seguro copiloto sin reaccion")
    agregar("G-10-55-07", CLASE_55, "L1", "A veces traba el seguro y a veces no hace nada cuando presiono la alarma.", "COLOQUIAL", "MANDO_DISTANCIA", "traba_intermitente", "NO_REPORTA", "", "SI", "NO", "", "L1 intermitencia electrica de traba")
    agregar("G-10-55-08", CLASE_55, "L1", "La compuerta del maletero no abre con el boton electrico.", "COLOQUIAL", "APERTURA_MALETERO", "boton_maletero_sin_accion", "NO_REPORTA", "", "SI", "NO", "", "L1 actuador maletero inerte")
    agregar("G-10-55-09", CLASE_55, "L1", "Le doy al switch de seguros y solo suena un rele pero ninguna puerta traba.", "COLOQUIAL", "ACCIONAMIENTO", "suena_rele_sin_traba", "NO_REPORTA", "", "SI", "NO", "", "L1 rele suena sin accion de seguros")
    agregar("G-10-55-10", CLASE_55, "L1", "Tengo que cerrar la puerta del acompanante manualmente por dentro porque electricamente no responde.", "COLOQUIAL", "CIERRE_MANUAL", "cierre_manual_obligado", "NO_REPORTA", "", "SI", "NO", "", "L1 obligatoriedad manual copiloto")

    # L2 (15 casos)
    agregar("G-10-55-11", CLASE_55, "L2", "Al presionar el boton de bloqueo en el control remoto tres puertas aseguran de inmediato, pero la puerta trasera derecha no hace ningun ruido electrico ni baja el pestillo.", "TECNICO", "BLOQUEO_REMOTO", "actuador_trasero_mudo, tres_puertas_aseguran", "traba_mecanica_puerta", "", "NO", "SI", CLASE_56, "L2 actuador trasero mudo vs traba mecanica")
    agregar("G-10-55-12", CLASE_55, "L2", "Con la llave manual la cerradura gira suave y abre el cerrojo sin resistencia, pero el microswitch electrico interno del actuador no envia la senal para activar las otras tres puertas.", "TECNICO", "LLAVE_MANUAL", "apertura_manual_suave, microswitch_electrico_falla", "chapa_trabada", "", "NO", "SI", CLASE_56, "L2 apertura manual suave vs traba de chapa")
    agregar("G-10-55-13", CLASE_55, "L2", "El actuador de la puerta del conductor emite un chasquido continuo cada 15 segundos con el auto apagado, descargando la bateria en reposo por mantener la red de confort despierta.", "TECNICO", "VEHICULO_ESTACIONADO", "actuador_chasquido_continuo, descarga_reposo", "bateria_defectuosa", "", "NO", "SI", CLASE_53, "L2 actuador con consumo continuo vs bateria")
    agregar("G-10-55-14", CLASE_55, "L2", "Al pasar de 20 km/h el cierre automatico intenta traba tres veces consecutivas emitiendo zumbido rapido en la puerta del piloto sin lograr retener el seguro electrico.", "TECNICO", "CIERRE_AUTOMATICO_VELOCIDAD", "reintento_tres_veces_traba, zumbido_rapido_piloto", "pestillo_desalineado", "", "NO", "SI", CLASE_56, "L2 reintento de traba automatica vs pestillo")
    agregar("G-10-55-15", CLASE_55, "L2", "Los seguros electricos funcionan con fuerza si el motor esta encendido a 14V, pero con el motor apagado no tienen fuerza para mover la varilla debido a micromotor con carbones gastados.", "TECNICO", "COMPARACION_TENSION", "actuador_debil_con_bateria, motor_encendido_funciona", "bateria_muerta", "", "NO", "SI", CLASE_48, "L2 micromotor con perdida de torque vs bateria")
    agregar("G-10-55-16", CLASE_55, "L2", "Escaneo del modulo de carroceria BCM detecta codigo B1300 indicando fallo en circuito del rele o actuador de bloqueo de puertas, sin anomalias en llaves codificadas.", "TECNICO", "SCANNER_BCM", "dtc_b1300_circuito_bloqueo, bcm_error", "falla_transponder_llave", "B1300", "NO", "NO", "", "L2 DTC B1300 circuito actuador")
    agregar("G-10-55-17", CLASE_55, "L2", "Al abrir la puerta del conductor el muelle de goma pasacables del pilar A presenta tres cables cortados por fatiga de flexion, interrumpiendo la linea de 12V del solenoide de cierre.", "TECNICO", "INSPECCION_PASACABLES", "cables_cortados_pilar_a, corte_alimentacion_12v", "cerradura_oxidada", "", "NO", "NO", "", "L2 arnes cortado en fuelle de puerta")
    agregar("G-10-55-18", CLASE_55, "L2", "El pestillo sube y baja perfectamente con el dedo sin ninguna traba fisica, pero al comandarlo desde la botonera maestra de la puerta no recibe pulso electrico.", "COLOQUIAL", "PRUEBA_MANUAL", "varilla_manual_libre_sin_traba, sin_pulso_botonera", "chapa_atorada", "", "NO", "SI", CLASE_56, "L2 varilla manual suave vs chapa trabada")
    agregar("G-10-55-19", CLASE_55, "L2", "La cerradura electrica del porton trasero no destraba con el mando a distancia ni con el pulsador exterior; fusible de 15A del sistema de cierre se quemo por solenoide en cortocircuito.", "TECNICO", "REVISION_FUSIBLE", "fusible_15a_quemado, solenoide_en_corto", "falla_chapa_mecanica", "", "NO", "NO", "", "L2 solenoide porton trasero quema fusible")
    agregar("G-10-55-20", CLASE_55, "L2", "Al cerrar con control remoto las luces direccionales destellan dos veces pero los seguros no reaccionan; con multimetro se comprueba que el rele interno de la BCM no conmuta salida.", "TECNICO", "TALLER_ELECTRICO", "destello_luces_ok, seguros_no_reaccionan, rele_bcm_inoperante", "falla_mecanica_puertas", "", "NO", "NO", "", "L2 BCM recibe mando pero rele no commuta")
    agregar("G-10-55-21", CLASE_55, "L2", "El motor electrico integrado en la cerradura del copiloto patina internamente sobre su pinon de plastico sin desplazar el cerrojo, emitiendo un chirrido de engranaje barrido.", "TECNICO", "ACCIONAMIENTO_CIERRE", "pinon_plastico_barrido_actuador, chirrido_interno", "desalineacion_pestillo", "", "NO", "SI", CLASE_56, "L2 pinon sinfin de actuador barrido")
    agregar("G-10-55-22", CLASE_55, "L2", "La alarma original no se arma porque el actuador de la puerta trasera izquierda no confirma la posicion de bloqueado a traves de su linea de retorno de masa.", "TECNICO", "ARMADO_ALARMA", "sin_confirmacion_bloqueo_masa, alarma_no_arma", "puerta_abierta_fisicamente", "", "NO", "NO", "", "L2 falta senal retorno retorno switch actuador")
    agregar("G-10-55-23", CLASE_55, "L2", "Falla intermitente: cuando el vehiculo esta frio en la manana los seguros no responden, pero tras circular 30 minutos y calentarse el habitaculo el sistema comienza a trabar.", "COLOQUIAL", "TEMPERATURA_CABINA", "falla_en_frio_opera_al_calentar, falso_contacto_actuador", "bateria_descargada", "", "NO", "SI", CLASE_48, "L2 dilatacion termica soldadura actuador vs bateria")
    agregar("G-10-55-24", CLASE_55, "L2", "Se reemplazo la cerradura mecanica completa pero el problema persiste identico: la linea positiva de control no entrega los 12V al accionar el comando desde la llave.", "TECNICO", "TALLER_REEMPLAZO", "cerradura_nueva_mismo_fallo, sin_alimentacion_12v", "falla_mecanica_cerradura", "", "NO", "SI", CLASE_56, "L2 descarte total de falla mecanica")
    agregar("G-10-55-25", CLASE_55, "L2", "El seguro electrico del maletero funciona de forma intermitente: al mover la tapa abre y cierra por cable trenzado pelado haciendo falso contacto en la bisagra izquierda.", "TECNICO", "MOVIMIENTO_COMPUERTA", "falso_contacto_bisagra, apertura_intermitente", "cerradura_descalibrada", "", "NO", "NO", "", "L2 cable partido en articulacion bisagra")

    # L3 (15 casos)
    agregar("G-10-55-26", CLASE_55, "L3", "Diagnostico de sistema de cierre centralizado con osciloscopio automotriz: al pulsar el comando de bloqueo en la llave, se registra pulso de activacion de 12.4V y 250 ms en conector de puerta, pero la corriente consumida por el micromotor Mabuchi del actuador es de 0.0A por escobillas internas carbonizadas y colector abierto.", "TECNICO", "OSCILOSCOPIO_PULSO_12V", "pulso_12_4v_250ms_ok, corriente_0_0a, escobillas_actuador_abiertas", "falla_mecanica_cerrojo", "", "NO", "SI", CLASE_56, "L3 pulso 12.4V 250ms presente corriente 0A")
    agregar("G-10-55-27", CLASE_55, "L3", "Medicion de caida de tension en circuito de masa de actuadores de puerta: con punta logica y voltimetro en escala DC se miden 4.8V de perdida en la linea de masa comun del pilar B durante el pulso de cierre (especificacion menor a 0.2V), impidiendo que los motores alcancen el torque de desplazamiento mecanico.", "TECNICO", "VOLTIMETRO_CAIDA_MASA", "caida_masa_4_8v_excesiva, torque_insuficiente_motores", "traba_mecanica", "", "NO", "NO", "", "L3 caida de masa de 4.8V en pilar B")
    agregar("G-10-55-28", CLASE_55, "L3", "Evaluacion de consumo electrico de modulo de cierre: al accionar el bloqueo de puerta delantera derecha la pinza amperimetrica acusa pico anormal de 8.4A sostenido por 2 segundos (nominal 1.8A a 2.5A) antes de que el modulo BCM corte por proteccion termica contra sobrecorriente por motor trabado electricamente.", "TECNICO", "PINZA_AMPERIMETRICA_DC", "sobrecorriente_8_4a, proteccion_bcm_corte, micromotor_trabado", "varillaje_doblado", "", "NO", "SI", CLASE_56, "L3 sobreconsumo 8.4A vs varillaje mecanico")
    agregar("G-10-55-29", CLASE_55, "L3", "Lectura de parametros de carroceria con escaner: DTC B1312 activo por cortocircuito a positivo en linea de desbloqueo de puerta del pasajero. Al desconectar la ficha de la cerradura el cortocircuito desaparece en el mazo principal, confirmando falla interna del modulo actuador integrado.", "TECNICO", "SCANNER_PARAMETROS", "dtc_b1312, corto_a_positivo_desbloqueo, falla_interna_actuador", "falla_chapa_exterior", "B1312", "NO", "NO", "", "L3 DTC B1312 corto en linea desbloqueo")
    agregar("G-10-55-30", CLASE_55, "L3", "Prueba de aislamiento en arnes pasacables de puerta del conductor: ensayo con megohmetro a 250V arroja resistencia de aislamiento de solo 150 kiloohmios entre cable de senal LOCK y cable de masa por aislamiento cuarteado y humedad marina acumulada en el pasamuros.", "TECNICO", "MEGOHMETRO_ARNES", "aislamiento_150kohm_fuelle, cables_cuarteados_humedad", "falla_mecanismo_llave", "", "NO", "NO", "", "L3 aislamiento degradado 150k en pasacables")
    agregar("G-10-55-31", CLASE_55, "L3", "Comprobacion de actuador de compuerta de maletero: al presionar boton remoto se comprueba pulso de 12.1V con duracion de 300 ms en conector; bobina de solenoide presenta resistencia de 0.8 Ohm (especificacion de manual de servicio: 5.5 a 6.5 Ohm), provocando fundicion instantanea del fusible F18 de 10A.", "TECNICO", "MULTIMETRO_BOBINA_SOLENOIDE", "resistencia_bobina_0_8ohm_en_corto, fusible_10a_fundido, pulso_12_1v", "traba_mecanica_gancho", "", "NO", "NO", "", "L3 bobina solenoide en corto a 0.8 ohm")
    agregar("G-10-55-32", CLASE_55, "L3", "Analisis de comunicacion en bus LIN de red de confort: nodo esclavo de puerta delantera derecha no responde a peticiones de diagnostico (DTC U0199: Lost Communication with Door Control Module A); tension de bus LIN colapsada a 1.2V fijos por transceptor en corto en modulo de puerta.", "TECNICO", "OSCILOSCOPIO_BUS_LIN", "dtc_u0199, bus_lin_colapsado_1_2v, modulo_puerta_en_corto", "falla_bateria", "U0199", "NO", "SI", CLASE_48, "L3 bus LIN colapsado a 1.2V DTC U0199")
    agregar("G-10-55-33", CLASE_55, "L3", "Diagnostico de actuador de cierre en banco: alimentado directamente con fuente regulada de 12V 5A, el motor consume 2.1A y gira con torque adecuado pero el engranaje sinfin de nylon presenta tres dientes arrancados, impidiendo transmitir desplazamiento axial a la cremallera de traba.", "TECNICO", "BANCO_PRUEBAS_ACTUADOR", "fuente_12v_ok_2_1a, engranaje_nylon_sinfin_dientes_rotos", "desalineacion_puerta", "", "NO", "SI", CLASE_56, "L3 banco confirma motor electrico ok sinfin roto")
    agregar("G-10-55-34", CLASE_55, "L3", "Verificacion de microinterruptores de posicion en cerradura: en reposo cerrado el contacto de confirmacion a masa marca 850 Ohmios por sulfatacion interna en vez de 0.0 Ohm; la computadora de confort interpreta que la puerta quedo abierta y cancela el ciclo de cierre con rebote electrico.", "TECNICO", "MULTIMETRO_MICROSWITCH", "microswitch_850ohm_sulfatado, lectura_falsa_puerta_abierta", "desgaste_mecanico_pestillo", "", "NO", "SI", CLASE_56, "L3 microswitch de puerta con 850 ohm sulfatado")
    agregar("G-10-55-35", CLASE_55, "L3", "Inspeccion tecnica en vehiculo con cerraduras de doble bloqueo (Deadlock): el motor primario de cierre opera con normalidad, pero el motor secundario de bloqueo antirrobo permanece trabado electricamente con codigo B1335 en BCM, impidiendo abrir la puerta incluso tirando de la manija interior.", "TECNICO", "TALLER_SPECIALIZADO", "dtc_b1335, motor_deadlock_bloqueado_electrico, doble_cierre", "chapa_amarrada_mecanica", "B1335", "NO", "SI", CLASE_56, "L3 motor de doble bloqueo Deadlock B1335")
    agregar("G-10-55-36", CLASE_55, "L3", "Prueba de continuidad en mazo de cables entre modulo BCM y actuador de puerta piloto: resistencia de linea de control de 42 Ohmios (debe ser menor a 0.3 Ohm) localizada en terminal hembra sulfatado del conector X102 en panel de instrumentos; caida de tension impide mover solenoide.", "TECNICO", "MULTIMETRO_RESISTENCIA_LINEA", "resistencia_linea_42ohm_sulfato, caida_tension_terminal_x102", "falla_mecanica_varillaje", "", "NO", "NO", "", "L3 terminal hembra sulfatado 42 ohm")
    agregar("G-10-55-37", CLASE_55, "L3", "Medicion de corriente en reposo de actuador: tras bloquear el vehiculo y entrar la red CAN en modo sleep, el actuador de la tapa de combustible retiene 320 mA continuos por falla en el transistor de corte de salida de la fusiblera inteligente, descargando la bateria en 48 horas.", "TECNICO", "PINZA_AMPERIMETRICA_REPOSO", "consumo_parasito_320ma_tapa_combustible, transistor_fuga", "autodescarga_bateria", "", "NO", "SI", CLASE_53, "L3 actuador tapa combustible consume 320mA en reposo")
    agregar("G-10-55-38", CLASE_55, "L3", "Comprobacion con generador de senales en receptor de radiofrecuencia (433 MHz) del cierre centralizado: la senal de la llave es recibida con amplitud optima de -45 dBm, pero la linea de salida de datos serie hacia la ECU de carroceria permanece en nivel logico bajo 0V continuo.", "TECNICO", "ANALIZADOR_ESPECTRO_RF", "senal_rf_433mhz_ok, salida_serie_bloqueada_0v", "pila_mando_agotada", "", "NO", "NO", "", "L3 receptor RF 433 MHz salida serie muerta")
    agregar("G-10-55-39", CLASE_55, "L3", "Prueba de esfuerzo en actuador de cerrojo: fuerza de traccion dinamica medida con dinamometro de traccion arroja 4.2 N (especificacion OEM minimo 14.0 N); degradacion de imanes permanentes de ferrita en micromotor por ingreso de agua provoca perdida de torque magnetico.", "TECNICO", "DINAMOMETRO_TRACCION", "fuerza_4_2n_vs_14_0n_minimo, perdida_torque_ferrita", "chapa_oxidada", "", "NO", "SI", CLASE_56, "L3 fuerza de empuje 4.2N insuficiente")
    agregar("G-10-55-40", CLASE_55, "L3", "Escaneo de red de carroceria: codigo DTC B1228 presente por circuito abierto en motor de cerradura de puerta corrediza lateral; medicion en conector de contacto deslizante de marco revela pines cargados por resorte carbonizados con resistencia de contacto de 180 Ohmios.", "TECNICO", "SCANNER_PUERTA_CORREDIZA", "dtc_b1228, contactos_deslizantes_carbonizados_180ohm", "desgaste_rieles_mecanicos", "B1228", "NO", "NO", "", "L3 contactos deslizantes puerta corrediza B1228")

    # =========================================================================
    # CLASE 56: Cerradura, chapa o pestillo mecanico de puerta trabado o desalineado
    # =========================================================================
    # L1 (10 casos)
    agregar("G-10-56-01", CLASE_56, "L1", "La puerta del chofer rebota cuando la intento cerrar suave.", "COLOQUIAL", "INTENTO_CIERRE", "puerta_rebota_al_cerrar", "NO_REPORTA", "", "SI", "NO", "", "L1 puerta rebota al cerrar")
    agregar("G-10-56-02", CLASE_56, "L1", "Tengo que tirar la puerta con muchisima fuerza para que enganche la traba.", "COLOQUIAL", "INTENTO_CIERRE", "cierre_con_fuerza_excesiva", "NO_REPORTA", "", "SI", "NO", "", "L1 requiere portazo fuerte")
    agregar("G-10-56-03", CLASE_56, "L1", "La manija exterior de la puerta se siente suelta y no abre nada.", "COLOQUIAL", "APERTURA_EXTERIOR", "manija_suelta_sin_apertura", "NO_REPORTA", "", "SI", "NO", "", "L1 manija exterior suelta")
    agregar("G-10-56-04", CLASE_56, "L1", "La llave fisica no gira en la cerradura, esta totalmente trabada.", "COLOQUIAL", "USO_LLAVE_FISICA", "llave_no_gira_trabada", "NO_REPORTA", "", "SI", "NO", "", "L1 llave fisica atorada")
    agregar("G-10-56-05", CLASE_56, "L1", "Se cayo la puerta y raspa abajo en el marco al cerrar.", "COLOQUIAL", "INTENTO_CIERRE", "puerta_caida_raspa_marco", "NO_REPORTA", "", "SI", "NO", "", "L1 puerta caida desalineada")
    agregar("G-10-56-06", CLASE_56, "L1", "La chapa de la maletera se quedo atascada y no abre con la llave.", "COLOQUIAL", "APERTURA_MALETERO", "chapa_maletera_atascada", "NO_REPORTA", "", "SI", "NO", "", "L1 chapa maletero atascada")
    agregar("G-10-56-07", CLASE_56, "L1", "El pestillo mecanico esta durisimo, no lo puedo mover ni con la mano.", "COLOQUIAL", "MANIPULACION_PESTILLO", "pestillo_mecanico_duro", "NO_REPORTA", "", "SI", "NO", "", "L1 pestillo mecanico endurecido")
    agregar("G-10-56-08", CLASE_56, "L1", "La puerta trasera quedo entreabierta y no termina de trabar en el segundo clic.", "COLOQUIAL", "ENGANCHE_PUERTA", "sin_segundo_clic_enganche", "NO_REPORTA", "", "SI", "NO", "", "L1 no entra segundo clic de enganche")
    agregar("G-10-56-09", CLASE_56, "L1", "Jalo la palanquita interior para salir y no destraba la puerta.", "COLOQUIAL", "APERTURA_INTERIOR", "manija_interior_sin_destrabe", "NO_REPORTA", "", "SI", "NO", "", "L1 manija interior no destraba")
    agregar("G-10-56-10", CLASE_56, "L1", "Siento un ruido a lata suelta adentro de la puerta cuando intento abrirla.", "COLOQUIAL", "ACCIONAMIENTO", "ruido_varilla_suelta", "NO_REPORTA", "", "SI", "NO", "", "L1 varilla suelta en puerta")

    # L2 (15 casos)
    agregar("G-10-56-11", CLASE_56, "L2", "El pestillo electrico acciona y suena con fuerza al presionar el mando, pero la puerta rebota contra el parante porque la boca de la chapa golpea desfasada 5 mm abajo del perno cerradero.", "TECNICO", "INTENTO_CIERRE", "actuador_electrico_fuerte_ok, puerta_rebota_desalineada_5mm", "falla_electrica_cierre", "", "NO", "SI", CLASE_55, "L2 actuador ok pero desalineacion mecanica 5mm")
    agregar("G-10-56-12", CLASE_56, "L2", "La cerradura quedo totalmente bloqueada mecanicamente por grasa solidificada y polvo acumulado; la llave gira solo 10 grados y se traba en seco sin mover el pestillo.", "COLOQUIAL", "USO_LLAVE", "grasa_solidificada_polvo, llave_traba_10_grados", "fallo_actuador_electrico", "", "NO", "SI", CLASE_55, "L2 bloqueo por grasa y suciedad en mecanismo")
    agregar("G-10-56-13", CLASE_56, "L2", "Al tirar de la manija exterior de la puerta se siente que no ofrece resistencia; tras retirar el tapiz se observa que la varilla metalica se solto del retenedor de plastico de la cerradura.", "TECNICO", "DESARME_TAPIZ", "varilla_suelta_de_grapa_plastica, manija_sin_resistencia", "falla_solenoide", "", "NO", "SI", CLASE_55, "L2 varilla mecanica desenganchada de grapa")
    agregar("G-10-56-14", CLASE_56, "L2", "Las bisagras de la puerta del conductor presentan holgura severa; al cerrar hay que levantar la puerta desde la manilla hacia arriba para que el pestillo calce en el cerradero.", "COLOQUIAL", "CIERRE_PUERTA", "holgura_bisagras_puerta_caida, levantar_para_cerrar", "falla_electrica", "", "NO", "NO", "", "L2 bisagras vencidas desalinean pestillo")
    agregar("G-10-56-15", CLASE_56, "L2", "El perno cerradero (striker) del pilar B se aflojo y se desplazo hacia adentro; la puerta queda suelta vibrando en marcha y requiere portazo violento para trabar en el primer seguro.", "TECNICO", "INSPECCION_STRIKER", "perno_striker_suelto_desplazado, vibracion_puerta_marcha", "actuador_quemado", "", "NO", "SI", CLASE_55, "L2 perno cerradero striker aflojado")
    agregar("G-10-56-16", CLASE_56, "L2", "El seguro para ninos (child lock) quedo atascado mecanicamente a mitad de carrera; la puerta no se puede abrir desde adentro pero desde afuera abre con normalidad.", "TECNICO", "PRUEBA_MECANICA", "child_lock_trabado_mitad, sin_apertura_interior", "falla_cierre_centralizado", "", "NO", "SI", CLASE_55, "L2 traba mecanica seguro ninos")
    agregar("G-10-56-17", CLASE_56, "L2", "El pestillo de la chapa tiene el muelle espiral interno de retorno roto; la unas de traba no regresan a su posicion de reposo y la puerta no retiene al empujarla contra el marco.", "TECNICO", "INSPECCION_CHAPA", "resorte_retorno_roto, unas_no_retienen", "falla_solenoide", "", "NO", "NO", "", "L2 resorte de retorno de unas roto")
    agregar("G-10-56-18", CLASE_56, "L2", "El bombin de la cerradura mecanica fue forzado con destornillador; las laminillas internas de combinacion estan dobladas y bloquean el giro de la llave original.", "COLOQUIAL", "REVISION_BOMBIN", "bombin_forzado_laminillas_dobladas, llave_no_entra", "falla_alarma", "", "NO", "NO", "", "L2 bombin forzado con laminillas dobladas")
    agregar("G-10-56-19", CLASE_56, "L2", "La compuerta trasera de carga presenta descuadre tras un golpe leve en el parachoques; el pestillo mecanico hace tope de metal contra metal sin permitir que el gancho cierre.", "TECNICO", "INSPECCION_CARROCERIA", "descuadre_porton_trasero_choque, gancho_hace_tope_metal", "falla_cierre_electrico", "", "NO", "SI", CLASE_55, "L2 descuadre estructural de porton tras colision")
    agregar("G-10-56-20", CLASE_56, "L2", "La cerradura de la puerta del copiloto abre y cierra electricamente con el boton, pero la chapa mecanica tiene juego excesivo y la puerta hace ruido de sonajero en caminos de tierra.", "COLOQUIAL", "MARCHA_CAMINO_TIERRA", "chapa_juego_excesivo_sonajero, cierre_electrico_ok", "falla_amortiguador", "", "NO", "NO", "", "L2 holgura en pestillo produce ruido en baches")
    agregar("G-10-56-21", CLASE_56, "L2", "Al accionar el mando central se escucha el motor trabajar con vigor, pero el cerrojo mecanico no traba porque el brazo de plastico que conecta con la cerradura esta partido en dos.", "TECNICO", "DESARME_INTERIOR", "brazo_plastico_partido, motor_trabaja_con_fuerza", "falla_motor_cierre", "", "NO", "SI", CLASE_55, "L2 brazo plastico de enlace quebrado")
    agregar("G-10-56-22", CLASE_56, "L2", "El pestillo de la puerta del conductor se traba al intentar destrabar manualmente con la varilla interior; se aprecia oxido denso en los ejes de articulacion de la cerradura.", "TECNICO", "INSPECCION_VISUAL", "oxido_denso_articulacion, varilla_interior_durisima", "falla_electrica_bcm", "", "NO", "SI", CLASE_55, "L2 oxidacion severa en mecanismos de chapa")
    agregar("G-10-56-23", CLASE_56, "L2", "El cerrojo de seguridad de la guantera se quedo trabado en posicion cerrada; la manija de plastico gira libre sin retraer los pestillos laterales de enganche.", "COLOQUIAL", "CABINA", "cerrojo_guantera_trabado, manija_gira_en_falso", "falla_electrica", "", "NO", "NO", "", "L2 traba mecanica cerrojo guantera")
    agregar("G-10-56-24", CLASE_56, "L2", "La puerta trasera no abre desde el exterior porque el cable Bowden de traccion tiene el tope de plomo zafado en la corredera de la manilla.", "TECNICO", "INSPECCION_MANILLA", "cable_bowden_tope_plomo_zafado, manilla_exterior_inutil", "falla_actuador", "", "NO", "SI", CLASE_55, "L2 cable Bowden desenganchado de manija")
    agregar("G-10-56-25", CLASE_56, "L2", "Tras pintar la puerta se montaron las cerraduras sin calibrar el centrado del cerradero; la puerta queda salida 4 mm respecto a la aleta trasera y filtra aire a alta velocidad.", "TECNICO", "CARRETERA_VIENTO", "puerta_salida_4mm_filtra_aire, cerradero_mal_calibrado", "falla_burlete_goma", "", "NO", "NO", "", "L2 mala calibracion de cerradero post pintura")

    # L3 (15 casos)
    agregar("G-10-56-26", CLASE_56, "L3", "Evaluacion metrologica de alineacion de carroceria y cerradura: el perno cerradero (striker) del pilar B presenta un descentramiento vertical de 6.2 mm respecto al eje central de la traba de la chapa, provocando que la uña de doble enganche golpee la cabeza del perno y rebote sin cerrar; holgura en perno de bisagra superior medida en 1.8 mm.", "TECNICO", "METROLOGIA_ALINEACION", "descentramiento_striker_6_2mm, holgura_bisagra_1_8mm, puerta_rebota", "falla_actuador_electrico", "", "NO", "SI", CLASE_55, "L3 descentramiento vertical striker 6.2mm")
    agregar("G-10-56-27", CLASE_56, "L3", "Diagnostico mecanico de cerradura de puerta: desmontaje de conjunto de chapa revela resorte espiral de torsion fracturado en dos secciones (resorte de retorno del trinquete de retencion). Al accionar manualmente la leva, el trinquete no vuelve por gravedad ni muelle, quedando en posicion abierta y requiriendo reemplazo mecanico del cerrojo.", "TECNICO", "DESARME_BANCO_CHAPA", "resorte_torsion_fracturado, trinquete_no_retorna, chapa_abierta", "falla_solenoide_electrico", "", "NO", "SI", CLASE_55, "L3 resorte espiral de torsion partido en dos")
    agregar("G-10-56-28", CLASE_56, "L3", "Metrologia de esfuerzo de cierre de puerta con dinamometro push-pull: la fuerza de impacto requerida para alcanzar el enganche secundario es de 145 Newtons (especificacion OEM normal: 35 a 45 N). Ajuste de posicion del cerradero en ranuras colisas de pilar reduce la fuerza requerida a 40 N con alineacion perfecta de linea de moldura.", "TECNICO", "DINAMOMETRO_PUSH_PULL", "fuerza_cierre_145n_vs_45n_oem, ajuste_colisas_cerradero_40n", "falla_cierre_centralizado", "", "NO", "SI", CLASE_55, "L3 dinamometro 145N de fuerza de cierre")
    agregar("G-10-56-29", CLASE_56, "L3", "Inspeccion de cerradura mecanica con microscopio de taller: el bombin de tambor de llave de encendido/puerta presenta cinco wafers (laminas de combinacion de laton) atascados con rebaba metalica de 0.3 mm por uso de llave clonada de perfil incorrecto, impidiendo el giro de 90 grados hacia posicion de desbloqueo.", "TECNICO", "MICROSCOPIO_LAMINILLAS", "wafers_atascados_rebaba_0_3mm, bombin_trabado, llave_perfil_falso", "falla_alarma_inmovilizador", "", "NO", "NO", "", "L3 cinco wafers de bombin con rebaba 0.3mm")
    agregar("G-10-56-30", CLASE_56, "L3", "Comprobacion de varillaje mecanico de puerta: la varilla de traccion entre manija exterior y chapa tiene una deformacion angular por flexion de 28 grados tras forzamiento de puerta; la carrera util de tiro se redujo de 14 mm a solo 6 mm, siendo insuficiente para liberar la leva de desenganche del pestillo.", "TECNICO", "BANCO_VARILLAJE", "varilla_doblada_28_grados, carrera_util_6mm_vs_14mm", "actuador_danado", "", "NO", "SI", CLASE_55, "L3 varilla doblada carrera reducida a 6mm")
    agregar("G-10-56-31", CLASE_56, "L3", "Desarme de cerradura de porton trasero: leva de accionamiento de zamak presenta fractura limpia por fatiga en la espiga de articulacion con el tirador manual; el micromotor electrico actua a la perfeccion enviando su recorrido pero la conexion fisica hacia el gancho se encuentra totalmente desvinculada.", "TECNICO", "INSPECCION_FRACTURA_ZAMAK", "espiga_zamak_fracturada_fatiga, motor_electrico_ok, gancho_desvinculado", "falla_motor_cierre", "", "NO", "SI", CLASE_55, "L3 espiga de zamak quebrada con motor ok")
    agregar("G-10-56-32", CLASE_56, "L3", "Prueba de ajuste de luz de puerta y enrase de carroceria: medicion con galga de espesores cónica revela holgura de holgura superior de 8.5 mm e inferior de 2.0 mm (descuadre trapezoidal de 6.5 mm); pasador de bisagra inferior de acero cementado presenta desgaste de 1.4 mm con juego axial pronunciado.", "TECNICO", "GALGA_CONICA_CARROCERIA", "descuadre_luz_6_5mm, desgaste_pasador_bisagra_1_4mm", "falla_cerradura_electrica", "", "NO", "NO", "", "L3 galga conica holgura trapezoidal 6.5mm")
    agregar("G-10-56-33", CLASE_56, "L3", "Analisis de falla en cerrojo de puerta corrediza: el tope de bloqueo inferior de nylon se encuentra desgastado en 4 mm y lleno de tierra; al cerrar la corredera la guia metalica hace tope seco sin permitir que el pestillo gire los 45 grados necesarios para el enganche de seguridad.", "TECNICO", "TALLER_CARROCERIA", "tope_nylon_desgastado_4mm, pestillo_no_gira_45_grados", "falla_sensor_puerta", "", "NO", "NO", "", "L3 tope nylon gastado impide giro 45 grados")
    agregar("G-10-56-34", CLASE_56, "L3", "Inspeccion de cable Bowden de manija interior: funda exterior de acero enrollado presenta aplastamiento por tornillo autorroscante de parlante aftermarket colocado incorrectamente; cable interior acerado de 1.5 mm aprisionado sin desplazamiento axial bajo traccion manual de 80 N.", "TECNICO", "INSPECCION_CABLE_BOWDEN", "funda_cable_aplastada_tornillo, cable_1_5mm_aprisionado", "falla_botonera_electrica", "", "NO", "NO", "", "L3 cable Bowden aplastado por tornillo")
    agregar("G-10-56-35", CLASE_56, "L3", "Verificacion de geometria de cerradura: el striker presenta surco de desgaste mecanico de 2.2 mm de profundidad producido por roce continuo durante 80,000 km; el trinquete de retencion se desliza fuera del surco en curvas fuertes a la izquierda, abriendose la puerta en primer seguro.", "TECNICO", "METROLOGIA_STRIKER", "surco_desgaste_striker_2_2mm, puerta_abre_en_curva", "falla_actuador_electrico", "", "NO", "SI", CLASE_55, "L3 surco de desgaste 2.2mm en perno cerradero")
    agregar("G-10-56-36", CLASE_56, "L3", "Evaluacion de sistema de traba de capot: el pestillo de seguridad secundario tiene el eje de articulacion oxidado y pegado en posicion abierta por sulfatacion salina; al soltar la palanca de cabina el gancho principal libera pero el segundo gancho no traba de forma segura ante viento frontal.", "TECNICO", "INSPECCION_CAPOT", "pestillo_secundario_capot_oxidado_pegado, riesgo_apertura", "falla_cable_traccion", "", "NO", "NO", "", "L3 pestillo secundario capot oxidado pegado")
    agregar("G-10-56-37", CLASE_56, "L3", "Desarme de conjunto cerradura en camioneta: uña de retencion principal recubierta de goma plastisol presenta desprendimiento del elastomero; el juego radial metal con metal de 3.5 mm provoca cascabeleo sordo en el pilar B a 60 km/h sobre asfalto rugoso con puerta firmemente asegurada.", "TECNICO", "TALLER_CHAPA", "desprendimiento_plastisol_una, juego_3_5mm_cascabeleo", "ruido_suspension", "", "NO", "NO", "", "L3 desprendimiento plastisol cascabeleo 3.5mm")
    agregar("G-10-56-38", CLASE_56, "L3", "Medicion de par de giro en bombin de cerradura con torquimetro de precision: torque para girar llave en sentido horario supera los 4.8 Nm (especificacion de esfuerzo suave menor a 0.6 Nm) debido a contaminacion por grafito en polvo humedecido con aceite vegetal que formo pasta abrasiva.", "TECNICO", "TORQUIMETRO_BOMBIN", "par_giro_4_8nm_vs_0_6nm, pasta_grafito_aceite_obstruccion", "falla_electrica_llave", "", "NO", "NO", "", "L3 torquimetro en bombin 4.8 Nm por pasta")
    agregar("G-10-56-39", CLASE_56, "L3", "Comprobacion de chapa de maletero en vehiculo sedan: cerradero montado sobre travesano trasero deformado hacia adelante 8 mm tras impacto de estacionamiento; al accionar apertura remota el solenoide dispara pero la presion de precarga de los burletes impide liberar el diente mecanico.", "TECNICO", "REVISION_TRAVESANO", "travesano_deformado_8mm_choque, precarga_excesiva_burletes", "falla_solenoide_maletero", "", "NO", "SI", CLASE_55, "L3 travesano deformado 8mm precarga burletes")
    agregar("G-10-56-40", CLASE_56, "L3", "Inspeccion tecnica de mecanismo de seguro infantil: selector rotativo de cerradura presenta la lengueta plastica selectora quebrada internamente a 90 grados; el trinquete de desbloqueo interior permanece desconectado de forma permanente sin posibilidad de abrir desde cabina.", "TECNICO", "DESARME_MECANISMO_CHILD", "lengueta_selectora_quebrada, trinquete_interior_desconectado", "falla_cierre_electrico", "", "NO", "SI", CLASE_55, "L3 lengueta de seguro infantil quebrada a 90 grados")

    # =========================================================================
    # CLASE 57: Elevalunas electrico o guaya de alzacristales rota o trabada
    # =========================================================================
    # L1 (10 casos)
    agregar("G-10-57-01", CLASE_57, "L1", "El vidrio de la ventana del conductor no quiere subir.", "COLOQUIAL", "INTENTO_SUBIDA", "vidrio_no_sube", "NO_REPORTA", "", "SI", "NO", "", "L1 ventana no sube")
    agregar("G-10-57-02", CLASE_57, "L1", "Se escucho un golpe seco dentro de la puerta y la luna se cayo sola.", "COLOQUIAL", "CAIDA_VIDRIO", "golpe_puerta, luna_caida", "NO_REPORTA", "", "SI", "NO", "", "L1 vidrio se cayo solo")
    agregar("G-10-57-03", CLASE_57, "L1", "Presiono el boton de la ventana y solo suena un crujido de cables adentro.", "COLOQUIAL", "ACCIONAMIENTO", "crujido_cables_puerta", "NO_REPORTA", "", "SI", "NO", "", "L1 crujido de cables en puerta")
    agregar("G-10-57-04", CLASE_57, "L1", "La ventana del copiloto sube muy chueca y se frena a mitad de camino.", "COLOQUIAL", "SUBIDA_VIDRIO", "ventana_chueca_frenada", "NO_REPORTA", "", "SI", "NO", "", "L1 ventana sube chueca y frena")
    agregar("G-10-57-05", CLASE_57, "L1", "El motor del alzacristales suena pero el vidrio no se mueve ni un centimetro.", "COLOQUIAL", "ACCIONAMIENTO", "motor_suena_sin_movimiento", "NO_REPORTA", "", "SI", "NO", "", "L1 motor suena vidrio quieto")
    agregar("G-10-57-06", CLASE_57, "L1", "No funciona la ventana trasera derecha con ningun interruptor.", "COLOQUIAL", "COMANDO_BOTON", "ventana_trasera_inoperante", "NO_REPORTA", "", "SI", "NO", "", "L1 ventana trasera inoperante")
    agregar("G-10-57-07", CLASE_57, "L1", "Tengo que agarrar el vidrio con las dos manos y jalarlo hacia arriba para cerrarlo.", "COLOQUIAL", "CIERRE_FORZADO", "jalar_vidrio_manos", "NO_REPORTA", "", "SI", "NO", "", "L1 ayuda manual obligada")
    agregar("G-10-57-08", CLASE_57, "L1", "La ventana baja rapido pero para subir le cuesta una eternidad.", "COLOQUIAL", "VELOCIDAD_VENTANA", "subida_lenta_pesada", "NO_REPORTA", "", "SI", "NO", "", "L1 subida extremadamente lenta")
    agregar("G-10-57-09", CLASE_57, "L1", "El boton del elevalunas en la consola se siente suelto y no hace contacto.", "COLOQUIAL", "BOTONERA", "boton_suelto_sin_contacto", "NO_REPORTA", "", "SI", "NO", "", "L1 interruptor de vidrio suelto")
    agregar("G-10-57-10", CLASE_57, "L1", "Se cayo el vidrio dentro de la puerta y suena que raspa todo al andar.", "COLOQUIAL", "EN_MARCHA", "vidrio_caido_raspa_puerta", "NO_REPORTA", "", "SI", "NO", "", "L1 vidrio dentro de puerta raspa")

    # L2 (15 casos)
    agregar("G-10-57-11", CLASE_57, "L2", "Al presionar el boton del alzacristales se escucha claramente el giro del motor electrico dentro de la puerta, pero el cristal se fue al fondo de la cavidad debido a rotura de la guaya de acero.", "TECNICO", "ACCIONAMIENTO_BOTON", "motor_gira_ok, guaya_rota, cristal_caido", "falla_motor_electrico", "", "NO", "NO", "", "L2 motor gira pero guaya rota cristal al fondo")
    agregar("G-10-57-12", CLASE_57, "L2", "La ventana del conductor sube torcida hacia adelante y se atasca a 10 cm del marco superior; la grapa plastica deslizadera del riel vertical se quebro por resecamiento.", "TECNICO", "SUBIDA_CRISTAL", "ventana_torcida_atasco, grapa_plastica_riel_quebrada", "falla_bateria", "", "NO", "SI", CLASE_48, "L2 grapa plastica de riel rota cristal torcido")
    agregar("G-10-57-13", CLASE_57, "L2", "Al operar el comando del alzacristales se produce un sonido de triturado metalico dentro de la puerta; el cable acerado se salio de la polea y se enredo en el tambor de bobinado.", "TECNICO", "PRUEBA_OPERATIVA", "sonido_triturado_cable, cable_enredado_tambor", "falla_cerradura_puerta", "", "NO", "SI", CLASE_55, "L2 cable acerado enredado en carril tambor")
    agregar("G-10-57-14", CLASE_57, "L2", "Con el vehiculo en marcha a 14V la ventana sube a velocidad normal, pero con motor apagado a 12.5V el cristal sube extremadamente lento por suciedad en colisas y carbones de motor desgastados.", "TECNICO", "COMPARACION_TENSION", "subida_lenta_motor_apagado, colisas_sucias_carbones", "bateria_defectuosa", "", "NO", "SI", CLASE_48, "L2 consumo elevado por roce de guias vs bateria")
    agregar("G-10-57-15", CLASE_57, "L2", "La ventana del pasajero baja sin problemas pero al darle a subir no hay reaccion; el interruptor individual del copiloto tiene los platinos internos carbonizados sin paso de 12V.", "TECNICO", "PRUEBA_INTERRUPTOR", "baja_ok_no_sube, platinos_carbonizados_interruptor", "falla_motor_alzacristal", "", "NO", "NO", "", "L2 platinos de contacto carbonizados en switch")
    agregar("G-10-57-16", CLASE_57, "L2", "El sistema antipinzamiento (anti-pinch) se activa automaticamente cuando el cristal llega al 70% de su recorrido invirtiendo la marcha, debido a resistencia por colisa de goma hinchada.", "TECNICO", "SUBIDA_AUTOMATICA", "antipinch_activa_rebota, resistencia_colisa_goma", "falla_motor_quemado", "", "NO", "NO", "", "L2 activacion erronea de antipinch por roce")
    agregar("G-10-57-17", CLASE_57, "L2", "Al desmontar el panel de la puerta se constata que el cable flexible de acero de 1.5 mm se deshilacho, trabando la corredera en el riel de aluminio e impidiendo el movimiento manual.", "TECNICO", "DESARME_TAPIZ", "cable_deshilachado_trabado, corredera_inmovil", "falla_electrica_cableado", "", "NO", "NO", "", "L2 cable deshilachado traba corredera")
    agregar("G-10-57-18", CLASE_57, "L2", "El cristal delantero derecho quedo suelto: se puede empujar hacia abajo con la palma de la mano con facilidad porque los pernos de fijacion de la mordaza inferior del vidrio se aflojaron.", "COLOQUIAL", "EMPUJE_MANUAL", "vidrio_baja_con_palma_mano, mordaza_aflojada", "motor_quemado", "", "NO", "NO", "", "L2 mordaza inferior de vidrio aflojada")
    agregar("G-10-57-19", CLASE_57, "L2", "La botonera principal del conductor no opera ningun cristal pero las botoneras individuales de cada puerta si funcionan; fusible termico o pista de alimentacion de la botonera maestra danada.", "TECNICO", "REVISION_BOTONERA_MASTER", "botonera_maestra_inoperante, botoneras_individuales_ok", "falla_fusible_general", "", "NO", "NO", "", "L2 botonera maestra del piloto inoperante")
    agregar("G-10-57-20", CLASE_57, "L2", "El motor del alzacristales calienta excesivamente tras tres intentos de subida y se apaga por proteccion bimetalica interna; el riel central carece totalmente de lubricacion y tiene oxido.", "TECNICO", "TALLER_REVISION", "motor_calienta_corte_termico, riel_sin_lubricacion_oxido", "falla_alternador", "", "NO", "SI", CLASE_47, "L2 corte termico de motor por falta lubricacion")
    agregar("G-10-57-21", CLASE_57, "L2", "Al activar la funcion de confort para subir lunas desde la llave el cristal trasero izquierdo no se mueve; en la puerta delantera el cierre centralizado opera con normalidad.", "TECNICO", "MODO_CONFORT_LLAVE", "confort_lunas_trasera_falla, cierre_centralizado_ok", "falla_cierre_centralizado", "", "NO", "SI", CLASE_55, "L2 falla elevalunas confort vs cierre centralizado")
    agregar("G-10-57-22", CLASE_57, "L2", "El vidrio llega arriba del todo pero emite un traqueteo tipo ametralladora continua sin detener el motor; el engranaje reductor de nylon tiene la corona dentada comida.", "COLOQUIAL", "TOPE_SUPERIOR", "traqueteo_corona_reductora_barrida, no_detiene_motor", "falla_motor_quemado", "", "NO", "NO", "", "L2 corona reductora de nylon barrida en tope")
    agregar("G-10-57-23", CLASE_57, "L2", "DTC B1402 registrado en BCM referente a circuito de motor de elevalunas delantero izquierdo; medicion confirma cable de masa quebrado en el fuelle de goma de union a la carroceria.", "TECNICO", "SCANNER_CARROCERIA", "dtc_b1402, masa_quebrada_fuelle_puerta", "falla_bateria", "B1402", "NO", "SI", CLASE_48, "L2 DTC B1402 masa quebrada en fuelle")
    agregar("G-10-57-24", CLASE_57, "L2", "La guaya metalica se salio de la polea superior de reenvio y corto la carcasa plastica del soporte; el vidrio se balancea hacia los costados dentro del marco de la puerta.", "TECNICO", "INSPECCION_POLEA", "guaya_fuera_polea_superior, vidrio_balancea_costados", "falla_chapa_puerta", "", "NO", "SI", CLASE_56, "L2 guaya salida de polea y soporte quebrado")
    agregar("G-10-57-25", CLASE_57, "L2", "El motor alzacristales trasero hace clic pero no gira; al golpear levemente el panel interior con el puno el cristal baja de golpe, senal de escobillas pegadas por polvo.", "COLOQUIAL", "GOLPE_PANEL", "clic_sin_giro, arranca_con_golpe_puno, escobillas", "falla_cierre_electrico", "", "NO", "SI", CLASE_55, "L2 escobillas de motor alzacristales pegadas")

    # L3 (15 casos)
    agregar("G-10-57-26", CLASE_57, "L3", "Diagnostico de consumo de corriente en motor alzacristales: pinza amperimetrica acopla en cable de alimentacion registra 22.5 Amperios sostenidos al pulsar comando de subida (nominal 4.5A a 7.0A en subida y 12A maximo en tope mecanico). Cristal bloqueado por guaya de acero enrollada de forma asimetrica en el tambor de traccion con tres espiras cruzadas.", "TECNICO", "PINZA_AMPERIMETRICA_CORRIENTE", "consumo_22_5a_bloqueo, guaya_enredada_tambor_espiras_cruzadas", "falla_bateria", "", "NO", "SI", CLASE_48, "L3 corriente 22.5A por guaya cruzada en tambor")
    agregar("G-10-57-27", CLASE_57, "L3", "Medicion con voltimetro automotriz en conectores de motor de elevalunas: al presionar tecla en sentido subida se registran 12.6V directos entre terminales 1 y 2, pero el rotor permanece inmovil. Medicion de resistencia ohmica de devanado de inducido marca infinito (circuito abierto por hilo fundido en conmutador de delgas).", "TECNICO", "MULTIMETRO_TENSION_RESISTENCIA", "tension_12_6v_presente, resistencia_infinita_abierta, inducido_quemado", "falla_interruptor", "", "NO", "NO", "", "L3 12.6V presentes inducido con circuito abierto")
    agregar("G-10-57-28", CLASE_57, "L3", "Inspeccion metrologica de cable de traccion de alzacristales: cable trenzado de acero galvanizado de 7x7 hilos (diametro 1.5 mm) presenta rotura por fatiga de traccion en el terminal prensado de plomo de la corredera; tension residual en resorte compensador es 0 N provocando desplome de masa de vidrio de 4.8 kg al fondo.", "TECNICO", "METROLOGIA_CABLE_ACERO", "rotura_cable_acero_1_5mm, terminal_prensado_roto, cristal_desplomado", "falla_cerradura_chapa", "", "NO", "SI", CLASE_56, "L3 cable 1.5mm roto terminal de plomo zafado")
    agregar("G-10-57-29", CLASE_57, "L3", "Evaluacion de resistencia de desplazamiento mecanico: fuerza de arrastre requerida para mover el cristal manualmente a lo largo del carril con dinamometro de traccion es de 95 N (especificacion de colisas limpias menor a 25 N); acumulacion de arena silicea y goma resecada genera sobrecarga que dispara bimetalico termico a los 4 segundos.", "TECNICO", "DINAMOMETRO_FRICCION_RIEL", "friccion_95n_vs_25n_maximo, colisas_con_arena, bimetalico_corta", "falla_motor_electrico", "", "NO", "NO", "", "L3 friccion en colisas de 95N satura motor")
    agregar("G-10-57-30", CLASE_57, "L3", "Lectura de codigos de falla en modulo de puerta delantera: DTC B1402 (Driver Power Window Circuit Failure) almacenado en historial; escaneo de parametros en vivo registra senal de pulsos Hall de conteo de posicion estancada en 0 Hz mientras la senal de comando de potencia permanece activa en ON.", "TECNICO", "SCANNER_PULSOS_HALL", "dtc_b1402, pulsos_hall_0hz, comando_potencia_on", "falla_sensor_ckp", "B1402", "NO", "NO", "", "L3 DTC B1402 sensor Hall de posicion en 0Hz")
    agregar("G-10-57-31", CLASE_57, "L3", "Prueba de caida de tension en botonera de elevalunas maestro: caida de 3.8V entre entrada de 12V de fusible y terminal de salida hacia puerta trasera derecha durante accionamiento; desmontaje de botonera confirma platinos de conmutacion con arco electrico y resistencia de contacto de 18 Ohmios.", "TECNICO", "CAIDA_TENSION_BOTONERA", "caida_3_8v_contactos, platinos_fogueados_18ohm", "falla_motor_trasero", "", "NO", "NO", "", "L3 caida 3.8V en platinos de botonera maestra")
    agregar("G-10-57-32", CLASE_57, "L3", "Analisis de reductor de alzacristales: desmontaje de carcasa de engranajes revela tornillo sinfin de acero templado integro, pero rueda dentada helicoidal de poliacetal (POM) de 54 dientes con sector central de 12 dientes totalmente barridos por sobreesfuerzo continuo de subida.", "TECNICO", "DESARME_REDUCTOR_POM", "sinfin_acero_ok, rueda_pom_12_dientes_barridos", "falla_electrica_cableado", "", "NO", "NO", "", "L3 engranaje de poliacetal con 12 dientes barridos")
    agregar("G-10-57-33", CLASE_57, "L3", "Comprobacion de sistema antipinzamiento electronico: sensor de efecto Hall integrado en placa de motor no genera senal cuadrada de 5V al girar; modulo de puerta interpreta perdida de pulsos de tacometro como deteccion de obstaculo fisico e invierte la marcha del cristal a los 2 segundos de subida.", "TECNICO", "OSCILOSCOPIO_HALL_5V", "sensor_hall_sin_cuadrada_5v, activacion_falsa_obstaculo, rebote_2s", "falla_cerradura", "", "NO", "SI", CLASE_55, "L3 falla de sensor Hall dispara antipinch falso")
    agregar("G-10-57-34", CLASE_57, "L3", "Prueba en rampa de taller: medicion con galga de espesores en corredera de alzacristales de tijera de doble brazo revela holgura radial de 2.4 mm en pivote central remachado; el paralelismo de las mordazas se desvia 12 mm provocando que el vidrio se enclave en la guia delantera de la puerta.", "TECNICO", "METROLOGIA_TIJERA_DOBLE", "holgura_pivote_2_4mm, desvio_paralelismo_12mm, vidrio_enclavado", "falla_guaya_rota", "", "NO", "NO", "", "L3 tijera con holgura 2.4mm desvia paralelismo")
    agregar("G-10-57-35", CLASE_57, "L3", "Inspeccion de aislamiento en arnes de puerta: cable de senal UP presenta aislamiento desgastado por roce con el filo de chapa del orificio de montaje; al presionar comando de subida el cable toca chapa chasis generando cortocircuito franco a masa y fundiendo fusible F22 de 30A.", "TECNICO", "TALLER_CORTOCIRCUITO", "aislamiento_rozado_chapa, corto_a_masa, fusible_30a_fundido", "falla_cierre_centralizado", "", "NO", "SI", CLASE_55, "L3 cable rozado con chapa quema fusible 30A")
    agregar("G-10-57-36", CLASE_57, "L3", "Evaluacion de motor paso a paso de elevalunas con bus LIN: modulo de puerta no reporta comunicacion en red (DTC U0201: Lost Communication with Door Control Module C); tension de alimentacion permanente en pin 4 es 12.5V pero linea LIN permanece en 0V por diodo TVS de proteccion en corto a masa.", "TECNICO", "SCANNER_RED_LIN", "dtc_u0201, linea_lin_0v_corto, alimentacion_12_5v_ok", "falla_bateria", "U0201", "NO", "SI", CLASE_48, "L3 DTC U0201 linea LIN en corto en puerta C")
    agregar("G-10-57-37", CLASE_57, "L3", "Diagnostico de mecanismo de guaya: polea de desvio inferior de poliamida presenta eje metalico desprendido de la pletina de montaje por fatiga de material; la guaya de traccion pierde tension operativa cayendo a 0 psi y el tambor mastica el cable de acero al activar el pulsador.", "TECNICO", "INSPECCION_POLEA_INFERIOR", "eje_polea_desprendido_pletina, guaya_destensada_masticada", "falla_mecanica_puerta", "", "NO", "SI", CLASE_56, "L3 eje de polea inferior desprendido de pletina")
    agregar("G-10-57-38", CLASE_57, "L3", "Comprobacion de mordazas de sujecion de cristal: tornillos torx de apriete flojos a 0.5 Nm (especificacion de fabrica 8.0 Nm); al bajar la corredera las almohadillas de caucho vulcanizado se deslizan sobre el vidrio sin arrastrarlo, dejando el cristal sostenido unicamente por friccion de marco.", "TECNICO", "TORQUIMETRO_MORDAZAS", "torque_mordazas_0_5nm_vs_8nm, almohadillas_patinan, cristal_suelto", "falla_motor_quemado", "", "NO", "NO", "", "L3 mordazas flojas a 0.5 Nm almohadillas patinan")
    agregar("G-10-57-39", CLASE_57, "L3", "Prueba de esfuerzo en banco dinamometrico: motor alzacristales entrega par maximo bloqueado de solo 1.2 Nm (nominal minimo 7.5 Nm); imanes permanentes de ferrita del estator quebrados en fragmentos internos por golpe en panel de puerta, provocando dispersion de flujo magnetico.", "TECNICO", "BANCO_PAR_BLOQUEADO", "par_bloqueado_1_2nm_vs_7_5nm, imanes_ferrita_quebrados", "falla_bateria", "", "NO", "SI", CLASE_48, "L3 par motor 1.2 Nm por imanes quebrados")
    agregar("G-10-57-40", CLASE_57, "L3", "Inspeccion de interruptor maestro de alzacristales con fuente de poder: corriente consumida por circuito electronico de control interno en reposo es de 180 mA (maximo admisible 2 mA) debido a condensador de filtrado SMD perforado, generando descarga lenta de bateria en estacionamiento nocturno.", "TECNICO", "TALLER_CORRIENTE_REPOSO", "consumo_reposo_180ma_botonera, condensador_smd_en_fuga", "fuga_bcm_general", "", "NO", "SI", CLASE_53, "L3 botonera elevalunas con fuga de 180mA en reposo")

    # =========================================================================
    # CLASE 58: Limpiaparabrisas o motor pluma quemado
    # =========================================================================
    # L1 (10 casos)
    agregar("G-10-58-01", CLASE_58, "L1", "Las plumillas del limpiaparabrisas no se mueven para nada.", "COLOQUIAL", "ACTIVACION_PLUMAS", "plumillas_inmoviles", "NO_REPORTA", "", "SI", "NO", "", "L1 limpiaparabrisas no se mueve")
    agregar("G-10-58-02", CLASE_58, "L1", "Prendi el limpiaparabrisas bajo la lluvia y se quedo congelado a la mitad.", "COLOQUIAL", "LLUVIA_MARCHA", "limpiaparabrisas_frenado_mitad", "NO_REPORTA", "", "SI", "NO", "", "L1 plumas frenadas a la mitad")
    agregar("G-10-58-03", CLASE_58, "L1", "Se escucha el motor del limpiador zumbando pero las plumas no barren.", "COLOQUIAL", "ACCIONAMIENTO", "motor_zumba_plumas_inmoviles", "NO_REPORTA", "", "SI", "NO", "", "L1 motor zumba sin barrer")
    agregar("G-10-58-04", CLASE_58, "L1", "Solo funciona la velocidad maxima del limpiaparabrisas, las demas estan muertas.", "COLOQUIAL", "VELOCIDADES", "solo_funciona_velocidad_alta", "NO_REPORTA", "", "SI", "NO", "", "L1 solo funciona velocidad maxima")
    agregar("G-10-58-05", CLASE_58, "L1", "Las plumas se mueven hiper lentas y parece que se van a quemar.", "COLOQUIAL", "VELOCIDAD_PLUMAS", "barrido_extremadamente_lento", "NO_REPORTA", "", "SI", "NO", "", "L1 barrido extremadamente lento")
    agregar("G-10-58-06", CLASE_58, "L1", "Salio olor a plastico quemado cerca del parabrisas y dejaron de funcionar los limpiavidrios.", "COLOQUIAL", "OLOR_QUEMADO", "olor_quemado_parabrisas, plumas_muertas", "NO_REPORTA", "", "SI", "NO", "", "L1 olor a quemado y plumas muertas")
    agregar("G-10-58-07", CLASE_58, "L1", "El limpiador trasero no barre el vidrio y se escucha trabado.", "COLOQUIAL", "LIMPIADOR_TRASERO", "limpiador_trasero_trabado", "NO_REPORTA", "", "SI", "NO", "", "L1 limpiador trasero trabado")
    agregar("G-10-58-08", CLASE_58, "L1", "Al apagar el limpiaparabrisas no regresa a su posicion abajo, se queda cruzado arriba.", "COLOQUIAL", "APAGADO_MANDO", "no_retorna_a_posicion_cero", "NO_REPORTA", "", "SI", "NO", "", "L1 plumas no retornan a cero")
    agregar("G-10-58-09", CLASE_58, "L1", "Le doy a la palanca del volante y no hace nada el limpia parabrisas.", "COLOQUIAL", "MANDO_VOLANTE", "palanca_sin_respuesta", "NO_REPORTA", "", "SI", "NO", "", "L1 palanca de plumillas sin reaccion")
    agregar("G-10-58-10", CLASE_58, "L1", "Las escobillas del parabrisas vibran y se traban a medio barrido.", "COLOQUIAL", "ACCIONAMIENTO", "escobillas_vibran_traban", "NO_REPORTA", "", "SI", "NO", "", "L1 escobillas vibran y traban")

    # L2 (15 casos)
    agregar("G-10-58-11", CLASE_58, "L2", "Con la palanca de mando en velocidad 1 y 2 no hay reaccion; al seleccionar velocidad 3 maxima las plumas barren con fuerza, debido a resistencia o bobinado de baja velocidad abierto.", "TECNICO", "PRUEBA_VELOCIDADES", "velocidad_1_y_2_inoperantes, velocidad_3_alta_ok", "falla_palanca_mando", "", "NO", "NO", "", "L2 bobinado de baja velocidad abierto")
    agregar("G-10-58-12", CLASE_58, "L2", "Al activar los limpiaparabrisas el motor emite un zumbido continuo pero los brazos no se mueven; el varillaje articulado se desprendio de la rotula plastica del motorreductor.", "TECNICO", "INSPECCION_VARILLAJE", "motor_zumba_ok, varillaje_desprendido_rotula", "motor_quemado", "", "NO", "NO", "", "L2 rotula plastica de varillaje zafada")
    agregar("G-10-58-13", CLASE_58, "L2", "Al apagar el interruptor de limpiaparabrisas las plumas se detienen instantaneamente en el medio del campo visual en vez de regresar a la posicion horizontal de reposo inferior.", "TECNICO", "APAGADO_LIMPIADORES", "parada_inmediata_medio_vidrio, switch_parada_cero_falla", "falla_motor_quemado", "", "NO", "NO", "", "L2 contacto de parada automatica park switch quemado")
    agregar("G-10-58-14", CLASE_58, "L2", "El motor del limpiaparabrisas huele a bobinado quemado y se siente hirviendo al tacto bajo el torpedo; el fusible de 20A de proteccion se funde a los 5 segundos de accionarlo.", "TECNICO", "TORPEDO_INSPECCION", "olor_bobinado_quemado, fusible_20a_funde_5s", "falla_alternador", "", "NO", "SI", CLASE_47, "L2 motor quemado quema fusible de 20A")
    agregar("G-10-58-15", CLASE_58, "L2", "El limpiaparabrisas trasero quedo atascado con la pluma a 90 grados; el eje pasante de metal a traves del cristal presenta oxido y corrosion que amarraron los bujes de bronce.", "TECNICO", "LIMPIADOR_TRASERO", "pluma_trasera_atascada_90_grados, eje_oxidado_amarrado", "falla_bateria", "", "NO", "SI", CLASE_48, "L2 eje de limpiador trasero amarrado por oxido")
    agregar("G-10-58-16", CLASE_58, "L2", "Al accionar el mando de barrido continuo se miden 12.4V en la ficha de conexion del motor de limpiaparabrisas pero el motor permanece inerte sin ningun zumbido ni consumo.", "TECNICO", "MEDICION_VOLTAJE", "tension_12_4v_en_ficha_ok, motor_totalmente_inerte", "falla_palanca_limpiaparabrisas", "", "NO", "NO", "", "L2 12.4V en motor pero circuito abierto en carbones")
    agregar("G-10-58-17", CLASE_58, "L2", "Bajo lluvia fuerte las plumas barren con extrema lentitud tardando 8 segundos por ciclo; con la luna mojada y lubricada el motor apenas tiene fuerza para arrastrar el varillaje.", "COLOQUIAL", "LLUVIA_FUERTE", "barrido_lento_8s_ciclo, motor_sin_torque", "bateria_descargada", "", "NO", "SI", CLASE_48, "L2 barrido lento 8 segundos por ciclo sin fuerza")
    agregar("G-10-58-18", CLASE_58, "L2", "Las plumas limpiaparabrisas barren de forma intermitente no programada: al encender la luz de giro o tocar la bocina se activan solas por derivacion a masa en la columna de direccion.", "TECNICO", "COLUMNA_DIRECCION", "activacion_espasmica_con_bocina, derivacion_masa", "falla_modulo_bcm", "", "NO", "NO", "", "L2 activacion falsa por derivacion a masa en palanca")
    agregar("G-10-58-19", CLASE_58, "L2", "El brazo del limpiaparabrisas del piloto barre hasta golpear el parante exterior izquierdo de la carroceria; la estria conica del eje estriado esta desgastada y safada.", "COLOQUIAL", "BARRIDO_DESFASADO", "pluma_golpea_parante, estria_eje_barrida", "falla_motor_quemado", "", "NO", "NO", "", "L2 estria conica de eje de brazo barrida")
    agregar("G-10-58-20", CLASE_58, "L2", "Escaneo de modulo de carroceria registra codigo B1130 por fallo en rele de limpiaparabrisas de velocidad baja; el motor opera normalmente si se aplica alimentacion directa con cable puente.", "TECNICO", "SCANNER_CARROCERIA", "dtc_b1130_rele_limpiaparabrisas, puente_directo_opera_ok", "falla_motor_pluma", "B1130", "NO", "NO", "", "L2 DTC B1130 en rele de limpiaparabrisas")
    agregar("G-10-58-21", CLASE_58, "L2", "El motor del limpiaparabrisas emite un chillido aspero como de engranaje seco; tras lubricar las articulaciones externas el ruido persiste en el interior del cuerpo reductor.", "COLOQUIAL", "RUIDO_MOTOR", "chillido_aspero_reductor_interno, varillaje_lubricado", "falla_correa_alternador", "", "NO", "SI", CLASE_47, "L2 reductor interno sin grasa vs correa")
    agregar("G-10-58-22", CLASE_58, "L2", "La velocidad intermitente del limpiaparabrisas dejo de funcionar tras lavar el motor con agua a presion; el rele temporizador integrado en el conector sufrio corrosion por humedad.", "TECNICO", "POST_LAVADO_MOTOR", "velocidad_intermitente_muerta, corrosion_rele_temporizador", "falla_motor_quemado", "", "NO", "NO", "", "L2 rele temporizador sulfatado post lavado")
    agregar("G-10-58-23", CLASE_58, "L2", "Ambas plumas quedan trabadas en el centro del parabrisas unicamente cuando el cristal esta seco; con lluvia barren forzadas calentando la carcasa metalica del motor.", "COLOQUIAL", "CRISTAL_SECO_VS_MOJADO", "traba_en_seco_calentamiento_motor, barren_forzadas", "falla_bateria", "", "NO", "SI", CLASE_48, "L2 motor pierde torque con roce en seco")
    agregar("G-10-58-24", CLASE_58, "L2", "El sensor de lluvia del parabrisas activa la peticion de barrido pero el conjunto motorreductor no responde; con la palanca manual en modo fijo continuo tampoco reacciona.", "TECNICO", "SENSOR_LLUVIA_AUTO", "sensor_lluvia_activa_sin_respuesta, modo_manual_tampoco", "falla_sensor_lluvia", "", "NO", "NO", "", "L2 falla de motor descarte de sensor de lluvia")
    agregar("G-10-58-25", CLASE_58, "L2", "Al dar marcha atras con limpiaparabrisas delantero encendido, el barrido automatico del vidrio trasero no activa por motor trasero quemado sin consumo de amperios.", "TECNICO", "RETROCESO_BARRIDO_AUTO", "barrido_trasero_reversa_falla, motor_sin_consumo", "falla_cierre_maletero", "", "NO", "SI", CLASE_55, "L2 limpiador trasero reversa vs cierre maletero")

    # L3 (15 casos)
    agregar("G-10-58-26", CLASE_58, "L3", "Diagnostico de motor de limpiaparabrisas con pinza amperimetrica: en velocidad baja (Low) el consumo de corriente se dispara a 18.2 Amperios (especificacion nominal 2.5A a 4.0A con cristal humedo). Desmontaje confirma colector de delgas de inducido en cortocircuito franco con laminillas de cobre quemadas y barniz derretido.", "TECNICO", "PINZA_AMPERIMETRICA_CORRIENTE", "consumo_18_2a_sobrecorriente, delgas_inducido_en_corto, barniz_derretido", "falla_alternador", "", "NO", "SI", CLASE_47, "L3 corriente 18.2A por inducido en cortocircuito")
    agregar("G-10-58-27", CLASE_58, "L3", "Inspeccion de sistema de parada automatica (Park Switch): medicion de continuidad con multimetro en terminal de retorno a masa revela que las pistas circulares de cobre de la rueda dentada reductora presentan desgaste total con rotura de lengueta de contacto, provocando que el motor corte en cualquier punto aleatorio.", "TECNICO", "MULTIMETRO_PARK_SWITCH", "pistas_cobre_reductora_desgastadas, lengueta_rota, parada_aleatoria", "falla_rele_bcm", "", "NO", "NO", "", "L3 pistas de cobre y lengueta de park switch rotas")
    agregar("G-10-58-28", CLASE_58, "L3", "Comprobacion de tension y caida en conector de motor limpiaparabrisas: con switch en posicion High se registran 12.2V en pin de alta velocidad y caida de masa de 0.05V (alimentacion y tierra en perfecto estado); prueba ohmica en escobilla positiva de alta velocidad arroja circuito abierto (infinito) por escobilla trabada en su portaescobilla.", "TECNICO", "VOLTIMETRO_CAIDA_MASA", "tension_12_2v_ok_masa_0_05v_ok, escobilla_alta_infinita_abierta", "falla_cableado_alimentacion", "", "NO", "NO", "", "L3 escobilla de alta velocidad abierta con 12.2V ok")
    agregar("G-10-58-29", CLASE_58, "L3", "Evaluacion de resistencia mecanica de varillaje articulado (wiper linkage): con brazos desacoplados del motor, se mide par resistente de rotacion en los bujes de los pivotes de brazo con torquimetro centesimal arrojando 6.8 Nm (especificacion de movimiento suave menor a 0.5 Nm) debido a corrosion galvanica por salitre que amarro los bujes de calamina.", "TECNICO", "TORQUIMETRO_PIVOTES_VARILLAJE", "par_resistente_6_8nm_vs_0_5nm, bujes_calamina_amarrados_salitre", "motor_quemado_directo", "", "NO", "NO", "", "L3 par resistente de 6.8 Nm en bujes por salitre")
    agregar("G-10-58-30", CLASE_58, "L3", "Lectura de codigos de averia con escaner en modulo BCM: DTC B1132 (Wiper High Speed Relay Circuit Low) confirmado; con osciloscopio en el pin de control se observa comando logico activo pero la bobina del motorreductor no produce inductancia por corte termico fusible interno abierto.", "TECNICO", "SCANNER_OSCILOSCOPIO", "dtc_b1132, sin_inductancia_bobina, corte_termico_abierto", "falla_bateria", "B1132", "NO", "SI", CLASE_48, "L3 DTC B1132 corte termico interno abierto")
    agregar("G-10-58-31", CLASE_58, "L3", "Prueba de aislamiento en bobinado de estator de motor limpiaparabrisas: ensayo con megohmetro a 500V DC entre borne de alimentacion y carcasa metalica registra 0.08 Megaohmios (aislamiento deficiente, norma OEM minimo 2.0 MΩ); aislamiento de alambre esmaltado degradado por ingreso de agua de lluvia por sello de goma resecado.", "TECNICO", "MEGOHMETRO_ESTATOR", "aislamiento_0_08mohm_a_500v, degradacion_esmalte_agua", "falla_aislamiento_alternador", "", "NO", "SI", CLASE_47, "L3 aislamiento 0.08 MOhm a 500V por agua")
    agregar("G-10-58-32", CLASE_58, "L3", "Analisis de conmutador de palanca en columna de direccion: medicion de caida de voltaje bajo carga de 6A arroja caida de 4.2V a traves de los contactos de velocidad 1 y 2 por fogueo de platinos; la velocidad rapida (terminal independiente) mantiene caida normal de solo 0.15V.", "TECNICO", "CAIDA_TENSION_MANDO_VOLANTE", "caida_4_2v_en_contactos_baja, platinos_fogueados, alta_0_15v_ok", "falla_motorreductor", "", "NO", "NO", "", "L3 caida de 4.2V en mando de columna de direccion")
    agregar("G-10-58-33", CLASE_58, "L3", "Inspeccion de reductor de engranajes de motor pluma: corona helicoidal de nilostick presenta sector de 8 dientes barridos por intento de arranque con plumas congeladas adheridas al parabrisas; el tornillo sinfin de acero gira en vacio a 2800 rpm consumiendo 1.2A sin transferir giro al arbol de salida.", "TECNICO", "DESARME_REDUCTOR_SINFIN", "corona_8_dientes_barridos_hielo, sinfin_gira_en_vacio_1_2a", "motor_quemado_total", "", "NO", "NO", "", "L3 corona barrida por hielo sinfin gira en vacio")
    agregar("G-10-58-34", CLASE_58, "L3", "Diagnostico de limpiador de luneta trasera en hatchback: motor consume 0.0A al recibir 12.5V de pulso de BCM; desmontaje de conjunto revela tubo pasante de fluido lavaparabrisas con fisura interna que inundo la placa de circuito electronico y provoco corrosion total del microcontrolador de barrido.", "TECNICO", "DESARME_MOTOR_LUNETA", "consumo_0_0a, tubo_lavador_fisurado_inundo_placa, corrosion_total", "falla_cierre_maletero", "", "NO", "SI", CLASE_55, "L3 tubo de agua fisurado inundo placa de limpiador trasero")
    agregar("G-10-58-35", CLASE_58, "L3", "Comprobacion de velocidad y tiempo de ciclo: tacometro digital optico registra 18 ciclos por minuto en velocidad baja (especificacion 45 a 55 cpm) y 26 cpm en alta (especificacion 65 a 80 cpm); medicion de temperatura con pirómetro infrarrojo en carcasa de motor acusa 118°C tras 3 minutos de operacion.", "TECNICO", "TACOMETRO_OPTICO_PIROMETRO", "velocidad_18cpm_vs_45cpm, temperatura_carcasa_118c, perdida_torque", "bateria_baja_carga", "", "NO", "SI", CLASE_48, "L3 tacometro 18 cpm vs 45 cpm y temperatura 118C")
    agregar("G-10-58-36", CLASE_58, "L3", "Verificacion de juego axial en eje de motor limpiador: reloj comparador centesimal colocado en la punta del eje acusa juego axial de 1.85 mm (tolerancia maxima 0.20 mm) debido a rotura de la arandela de ajuste de baquelita; el rotor se desplaza rozando axialmente contra la placa portadiodos interna.", "TECNICO", "RELOJ_COMPARADOR_EJE", "juego_axial_1_85mm_vs_0_20mm, arandela_baquelita_rota, roce_rotor", "holgura_varillaje", "", "NO", "NO", "", "L3 juego axial 1.85mm rotor roza con placa")
    agregar("G-10-58-37", CLASE_58, "L3", "Prueba de esfuerzo en banco dinamometrico de motorreductor: par de torsion util medido en el arbol de salida es de 3.2 Nm a 45 rpm (especificacion nominal 18 a 22 Nm); degradacion termica irreversible de imanes de neodimio por sobrecalentamiento previo reduce severamente el campo inductor.", "TECNICO", "BANCO_DINAMOMETRICO_PAR", "par_3_2nm_vs_18nm_nominal, degradacion_imanes_neodimio", "falla_bateria", "", "NO", "SI", CLASE_48, "L3 par motor 3.2 Nm vs 18 Nm por imanes degradados")
    agregar("G-10-58-38", CLASE_58, "L3", "Inspeccion de circuito de retorno con osciloscopio: senal de transicion de masa en posicion de reposo (Park Signal) presenta ruido parasitario de 4.8V con rebotes de 120 ms; modulo de carroceria no reconoce el flanco de bajada y continua ciclando el motor 3 veces tras apagar el mando.", "TECNICO", "OSCILOSCOPIO_SENAL_PARK", "senal_park_ruido_4_8v_rebotes_120ms, ciclado_falso_3_veces", "falla_palanca_mando", "", "NO", "NO", "", "L3 senal de park con rebotes de 120 ms cicla 3 veces")
    agregar("G-10-58-39", CLASE_58, "L3", "Medicion de resistencia en bobinados de estator trifasico de motor sin escobillas (BLDC) de limpiaparabrisas moderno: Fase U-V 0.65 Ohm, V-W 0.64 Ohm, W-U 0.66 Ohm dentro de rango, pero modulo controlador integrado MOSFET presenta puente H en cortocircuito en rama baja de fase U (DTC B1150).", "TECNICO", "TALLER_MOTOR_BLDC", "dtc_b1150, bobinado_bldc_ok_0_65ohm, mosfet_puente_h_en_corto", "falla_motor_electrico_traccion", "B1150", "NO", "NO", "", "L3 motor BLDC bobinados ok MOSFET quemado B1150")
    agregar("G-10-58-40", CLASE_58, "L3", "Comprobacion de articulaciones esfericas de varillaje: cuatro rotulas plasticas de conexion presentan desgaste de 0.8 mm en casquillos de nylon; el retraso mecanico acumulado provoca desfase angular de 25 grados entre el brazo izquierdo y derecho, cruzandose las escobillas en el centro del cristal.", "TECNICO", "METROLOGIA_ROTULAS_VARILLAJE", "desgaste_rotulas_0_8mm, desfase_angular_25_grados, escobillas_cruzan", "falla_motorreductor", "", "NO", "NO", "", "L3 holgura 0.8mm en rotulas plumas se cruzan")

    return casos
