"""
Generador de registros para Lote 09 de Fase 10 (ELECTRICO) - Parte 1.
Cubre exactamente 120 registros:
- Clase 47: Alternador defectuoso o placa de diodos quemada (40 casos: 10 L1, 15 L2, 15 L3)
- Clase 48: Bateria descargada o bornes sulfatados (40 casos: 10 L1, 15 L2, 15 L3)
- Clase 49: Degradacion o falla en paquete de bateria de alto voltaje (EV / Hibridos) (40 casos: 10 L1, 15 L2, 15 L3)
IDs: F10-L09-0001 a F10-L09-0120.
"""

from typing import List, Dict

CLASE_47 = "Alternador defectuoso o placa de diodos quemada"
CLASE_48 = "Bateria descargada o bornes sulfatados"
CLASE_49 = "Degradacion o falla en paquete de bateria de alto voltaje (EV / Hibridos)"
MACRO = "ELECTRICO"
FUENTE = "SINTETICO_IA"


def obtener_casos_47_49(offset: int = 1) -> List[Dict[str, str]]:
    casos = []
    idx = offset

    def agregar(id_grupo, clase, nivel, texto, lenguaje, condicion, presentes, negados, dtc, req_preg, es_cont, clase_cont, obs):
        nonlocal idx
        reg_id = f"F10-L09-{idx:04d}"
        casos.append({
            "id": reg_id,
            "id_grupo": id_grupo,
            "clase_objetivo": clase,
            "macro_sistema": MACRO,
            "nivel_informacion": nivel,
            "texto_usuario": texto,
            "tipo_lenguaje": lenguaje,
            "condicion_operacion": condicion,
            "sintomas_presentes": presentes,
            "sintomas_negados": negados,
            "dtc": dtc,
            "requiere_pregunta": req_preg,
            "es_contrastivo": es_cont,
            "clase_contrastiva": clase_cont,
            "fuente": FUENTE,
            "observaciones": obs
        })
        idx += 1

    # =========================================================================
    # CLASE 47: Alternador defectuoso o placa de diodos quemada (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G47-L1-01", CLASE_47, "L1", "Se encendió un testigo rojo con forma de batería mientras iba manejando en la pista.", "COTIDIANO", "motor_en_marcha", "testigo_bateria_en_marcha", "", "", "SI", "NO", "", "L1 testigo de batería en marcha sin detalles.")
    agregar("G47-L1-02", CLASE_47, "L1", "Hola, las luces del tablero y los faros parpadean o bajan de intensidad cuando acelero.", "WHATSAPP", "aceleracion_ralenti", "luces_parpadean_cambian_intensidad", "", "", "SI", "NO", "", "L1 luces parpadean con cambio de RPM.")
    agregar("G47-L1-03", CLASE_47, "L1", "El carro se me apagó de la nada en pleno tráfico y ya no quiso arrancar.", "COTIDIANO", "pleno_trafico_apagado", "carro_se_apago_en_trafico", "", "", "SI", "NO", "", "L1 apagado en tráfico.")
    agregar("G47-L1-04", CLASE_47, "L1", "Siento un olor a quemado eléctrico que sale del lado de las fajas del motor.", "COTIDIANO", "motor_encendido_fajas", "olor_quemado_electrico_fajas", "", "", "SI", "NO", "", "L1 olor a quemado eléctrico en fajas.")
    agregar("G47-L1-05", CLASE_47, "L1", "Se escucha un silbido o zumbido electromagnético agudo cerca del alternador.", "TALLER", "ralenti_zumbido", "silbido_zumbido_electromagnetico_alternador", "", "", "SI", "NO", "", "L1 zumbido electromagnético en alternador.")
    agregar("G47-L1-06", CLASE_47, "L1", "Buenas, la batería es nuevecita pero después de andar una hora se muere por completo.", "WHATSAPP", "despues_una_hora_uso", "bateria_nueva_muere_andando", "", "", "SI", "NO", "", "L1 batería nueva se descarga rodando.")
    agregar("G47-L1-07", CLASE_47, "L1", "La radio se me apaga sola y la dirección se puso dura de golpe en la pista.", "COTIDIANO", "rodando_en_pista", "radio_se_apaga_direccion_dura", "", "", "SI", "NO", "", "L1 radio y dirección fallan en marcha.")
    agregar("G47-L1-08", CLASE_47, "L1", "Ayuda la luz de bateria parpadea cuando acelero a fondo.", "ERROR_ORTOGRAFICO", "aceleracion_a_fondo", "luz_bateria_parpadea_acelerar", "", "", "SI", "NO", "", "L1 luz batería parpadea con ortografía informal.")
    agregar("G47-L1-09", CLASE_47, "L1", "El auto arranca bien en la mañana pero si prendo las luces y el aire se desmaya el motor.", "COTIDIANO", "cargas_electricas_encendidas", "motor_desmaya_con_luces_y_aire", "", "", "SI", "NO", "", "L1 motor decae al meter consumidores.")
    agregar("G47-L1-10", CLASE_47, "L1", "Noto que los limpiaparabrisas andan lentísimos y los focos alumbran amarillo.", "COTIDIANO", "marcha_focos_amarillos", "limpiaparabrisas_lentos_focos_amarillos", "", "", "SI", "NO", "", "L1 accesorios lentos por bajo voltaje.")

    # --- L2 (15 casos) ---
    agregar("G47-L2-01", CLASE_47, "L2", "Con el motor encendido en ralentí el multímetro marca 11.9 V en los bornes de la batería; al acelerar a 2500 rpm el voltaje no sube de 12.1 V y la batería no se calienta.", "TECNICO", "motor_encendido_ralenti_y_2500rpm", "voltaje_carga_11_9v_no_sube_acelerando", "falla_bateria_interna", "", "NO", "SI", "Bateria descargada o bornes sulfatados", "L2 alternador no genera con 11.9V en marcha descarta batería.")
    agregar("G47-L2-02", CLASE_47, "L2", "Testigo rojo de batería encendido fijo en el tablero mientras conduzco; la batería arranca perfecto en frío pero el alternador tiene la faja floja y patina con chillido.", "COTIDIANO", "conduccion_testigo_encendido", "testigo_bateria_fijo_en_marcha|faja_alternador_patina", "falla_motor_arranque", "", "NO", "SI", "Falla en motor de arranque o solenoide defectuoso (clac seco o carbones gastados)", "L2 testigo en marcha con faja floja descarta arrancador.")
    agregar("G47-L2-03", CLASE_47, "L2", "Zumbido tipo sirena que varía estrictamente con las RPM del motor; al colocar el multímetro en escala de corriente alterna (AC) en la batería se leen 1.2 V AC de rizado por diodos quemados.", "TECNICO", "aceleracion_multimetro_ac", "zumbido_con_rpm|rizado_ripple_1_2v_ac_placa_diodos", "falla_caja_cambios", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L2 rizado AC de 1.2V confirma placa de diodos quemada.")
    agregar("G47-L2-04", CLASE_47, "L2", "El vehículo se apaga rodando tras 30 minutos de trayecto nocturno con faros encendidos; la batería queda en 10.2 V pero retiene la carga si se le conecta un cargador externo.", "TALLER", "trayecto_nocturno_consumidores", "se_apaga_rodando_de_noche|bateria_en_10_2v|retiene_carga_externa", "falla_fuga_parasita", "", "NO", "SI", "Fuga parasita de corriente en reposo (consumo nocturno de bateria)", "L2 descarga rodando de noche con batería reteniendo carga externa.")
    agregar("G47-L2-05", CLASE_47, "L2", "Regulador de voltaje en cortocircuito entregando sobretensión de 16.4 V con motor encendido; el líquido de la batería hierve despidiendo olor a huevo podrido y fundió dos bombillos H4.", "TECNICO", "motor_encendido_sobretension", "sobretension_16_4v_regulador|electrolito_hierve_olor_azufre|bombillos_quemados", "falla_bateria", "", "NO", "SI", "Bateria descargada o bornes sulfatados", "L2 sobretensión de 16.4V por regulador en corto quema bombillos.")
    agregar("G47-L2-06", CLASE_47, "L2", "Hola maestro, mientras manejaba en la avenida se prendió la luz de batería y de golpe el timón eléctrico se puso duro y la radio se apagó; la batería tiene 2 meses de comprada.", "WHATSAPP", "marcha_avenida_perdida_accesorios", "luz_bateria_en_marcha|direccion_eps_dura|radio_apagada", "bateria_vieja", "", "NO", "SI", "Bateria descargada o bornes sulfatados", "L2 batería de 2 meses descargada en marcha descarta batería vieja.")
    agregar("G47-L2-07", CLASE_47, "L2", "DTC P0620 presente en módulo de motor referente a circuito de control del alternador; el borne B+ del alternador registra 12.2 V con motor en ralentí.", "TECNICO", "ralenti_dtc_p0620", "dtc_p0620|borne_b_positivo_12_2v_en_ralenti", "falla_arrancador", "P0620", "NO", "SI", "Falla en motor de arranque o solenoide defectuoso (clac seco o carbones gastados)", "L2 DTC P0620 por fallo en circuito de control de alternador.")
    agregar("G47-L2-08", CLASE_47, "L2", "Carbones o escobillas del regulador del alternador gastados a menos de 2 mm; hacen contacto intermitente prendiendo y apagando el testigo de batería al superar 3000 rpm.", "TALLER", "alta_revolucion_3000rpm", "carbones_alternador_gastados_2mm|testigo_parpadea_a_3000rpm", "falla_fuga_nocturna", "", "NO", "SI", "Fuga parasita de corriente en reposo (consumo nocturno de bateria)", "L2 escobillas gastadas encienden testigo a altas RPM.")
    agregar("G47-L2-09", CLASE_47, "L2", "Al encender las luces altas y el desempañador térmico el voltaje de carga se desploma de 13.6 V a 11.8 V; con todos los consumidores apagados genera 13.5 V.", "COTIDIANO", "ralenti_consumidores_altos", "voltaje_desploma_13_6_a_11_8v_con_cargas", "falla_borne_sulfatado", "", "NO", "SI", "Bateria descargada o bornes sulfatados", "L2 alternador incapaz de sostener amperaje con consumidores.")
    agregar("G47-L2-10", CLASE_47, "L2", "Polea libre desacopladora del alternador (OAP) totalmente gripada; genera vibración y zumbido metálico en la faja de accesorios que desaparece al retirar la correa.", "TECNICO", "inspeccion_polea_oap_desacopladora", "polea_desacopladora_oap_gripada|vibracion_faja_accesorios", "falla_bomba_agua", "", "NO", "SI", "Falla en termostato o motoventilador de radiador", "L2 polea desacopladora OAP gripada zumba en accesorios.")
    agregar("G47-L2-11", CLASE_47, "L2", "Buenas tardes, el carro amanece con la batería muerta únicamente los días que lo uso de noche; si lo dejo parado 3 días sin prender las luces no se descarga nada.", "WHATSAPP", "uso_nocturno_vs_reposo", "descarga_tras_usar_luces|no_descarga_parado_3_dias", "fuga_parasita_nocturna", "", "NO", "SI", "Fuga parasita de corriente en reposo (consumo nocturno de bateria)", "L2 descarga asociada a uso y no a reposo descarta fuga parásita.")
    agregar("G47-L2-12", CLASE_47, "L2", "DTC P0562 registrado por tensión baja del sistema; la pinza amperimétrica en el cable de salida del alternador mide 0 amperios con motor encendido y luces prendidas.", "TECNICO", "motor_encendido_pinza_amperimetrica", "dtc_p0562|salida_cero_amperios_alternador_con_luces", "falla_bateria", "P0562", "NO", "SI", "Bateria descargada o bornes sulfatados", "L2 DTC P0562 con cero amperios de salida del alternador.")
    agregar("G47-L2-13", CLASE_47, "L2", "Estator del alternador con bobinado quemado de color negro carbón y barniz derretido; al medir continuidad entre fase y masa chasis se constata cortocircuito a tierra.", "TALLER", "desarme_banco_estator_quemado", "estator_bobinado_quemado_negro|cortocircuito_fase_a_masa", "falla_arranque", "", "NO", "SI", "Falla en motor de arranque o solenoide defectuoso (clac seco o carbones gastados)", "L2 bobinado de estator quemado en cortocircuito a masa.")
    agregar("G47-L2-14", CLASE_47, "L2", "Luz de batería parpadea al acelerar en carretera; los bornes de la batería están limpios y apretados a 12 Nm sin sulfato pero el conector del alternador está flojo.", "COTIDIANO", "carretera_aceleracion_conector", "luz_bateria_parpadea_acelerando|bornes_limpios_12nm|conector_alternador_flojo", "bornes_sucios", "", "NO", "SI", "Bateria descargada o bornes sulfatados", "L2 luz parpadea con bornes impecables confirmando alternador.")
    agregar("G47-L2-15", CLASE_47, "L2", "Alternador emite humo blanco y calor extremo tras arrancar con puente de cables; el puente de diodos rectificador tiene 3 diodos positivos en cortocircuito continuo.", "TALLER", "humo_blanco_puente_diodos", "humo_blanco_alternador_calor|3_diodos_positivos_en_corto", "falla_bateria", "", "NO", "SI", "Bateria descargada o bornes sulfatados", "L2 diodos en cortocircuito calientan y humean alternador.")

    # --- L3 (15 casos) ---
    agregar("G47-L3-01", CLASE_47, "L3", "Diagnóstico de sistema de carga con osciloscopio automotriz en bornes de batería con motor a 2000 rpm: se observa señal de tensión rectificada con caída periódica profunda de una cresta trifásica con rizado alterno (AC ripple) de 850 mV pico a pico (tolerancia máxima OEM menor a 150 mV AC). En modo voltímetro DC la tensión promedio se sitúa en 12.85 V con luces bajas encendidas (especificación 13.80 V a 14.40 V). Se desmonta el alternador y se comprueba en banco que dos diodos zener de la rama negativa de la placa rectificadora están en circuito abierto.", "TECNICO", "osciloscopio_2000rpm_ac_ripple_850mv", "ac_ripple_850mv_vs_150mv|tension_dc_12_85v_a_2000rpm|dos_diodos_rama_negativa_abiertos", "falla_bateria_quimica", "", "NO", "SI", "Bateria descargada o bornes sulfatados", "L3 osciloscopio registra ripple de 850 mV AC y 12.85V DC por diodos abiertos.")
    agregar("G47-L3-02", CLASE_47, "L3", "Evaluación de alternador pilotado por PWM (módulo de control LIN / RLO en Ford Ranger): el escáner registra DTC P065B referente a rendimiento del circuito de control del alternador. En flujo de datos en vivo el comando de ciclo de trabajo PWM hacia el regulador marca 78% pero la señal de retroalimentación de carga (Field Monitor / terminal FR) permanece estancada en 0.0% con tensión de red en 11.6 V. Prueba con generador de señales confirma que el regulador electrónico inteligente integrado no responde al bus LIN.", "TECNICO", "scanner_datos_en_vivo_p065b_lin_bus", "dtc_p065b|comando_pwm_78porciento_retorno_cero|tension_red_11_6v|regulador_lin_no_responde", "falla_bateria_12v", "P065B", "NO", "SI", "Bateria descargada o bornes sulfatados", "L3 DTC P065B con falla en comunicación LIN bus de alternador inteligente.")
    agregar("G47-L3-03", CLASE_47, "L3", "Prueba de carga máxima en banco de alternadores con reóstato de potencia a 3000 rpm de rotor: alternador nominal de 120 A entrega únicamente 34 A a 13.2 V antes de que la tensión caiga por debajo de 11.5 V. Análisis térmico con cámara infrarroja constata sobrecalentamiento focalizado a 142°C en el tercio inferior del estator debido a espiras en cortocircuito entre fases (resistencia de fase medida en 0.04 ohmios vs 0.28 ohmios nominales).", "TECNICO", "banco_reostato_entrega_34a_vs_120a", "entrega_34a_vs_120a_nominal|estator_a_142c|resistencia_fase_0_04ohm_vs_0_28ohm", "falla_arrancador", "", "NO", "SI", "Falla en motor de arranque o solenoide defectuoso (clac seco o carbones gastados)", "L3 banco confirma entrega de solo 34A de 120A con fase en corto a 142°C.")
    agregar("G47-L3-04", CLASE_47, "L3", "Hola maestro, tengo un Toyota Yaris. Ayer en la noche mientras manejaba con lluvia y luces altas se me encendió la lucecita de la batería en el tablero. A los 10 minutos la radio se apagó, las luces se pusieron amarillas débiles y el timón se puso como una piedra. Cuando me orillé el motor se apagó solo y no dio arranque. Medí con multímetro con motor encendido antes de morir y marcaba 11.4 V; la batería cargada en casa arranca el auto al toque pero en marcha el voltaje se viene abajo.", "WHATSAPP", "yaris_noche_lluvia_luces_altas", "luz_bateria_en_marcha|direccion_dura_luces_debiles|voltaje_11_4v_en_marcha|bateria_externa_ok", "falla_bateria", "", "NO", "SI", "Bateria descargada o bornes sulfatados", "L3 relato WhatsApp de batería que arranca cargada pero cae a 11.4V rodando.")
    agregar("G47-L3-05", CLASE_47, "L3", "Medición de caída de tensión por el cable de fuerza B+ del alternador a borne positivo de batería bajo carga de 60 A: caída de 0.12 V (normal, especificación menor a 0.25 V) y caída de masa de 0.08 V. Sin embargo la tensión directa en el borne B+ con motor a 1500 rpm registra solo 12.15 V con consumo de campo de 0.1 A en el rotor debido a desgaste de anillos rozantes de cobre con surcos de 1.8 mm y escobillas carbonizadas sin presión de resorte.", "TECNICO", "caida_tension_b_positivo_rotor_gastado", "caida_cable_0_12v_ok|tension_borne_b_12_15v|anillos_rozantes_surcos_1_8mm|corriente_campo_0_1a", "falla_cableado_sulfatado", "", "NO", "SI", "Bateria descargada o bornes sulfatados", "L3 cableado perfecto con 0.12V caída pero alternador genera 12.15V por anillos gastados.")
    agregar("G47-L3-06", CLASE_47, "L3", "Diagnóstico de sobretensión intermitente en Chevrolet Cruze: código DTC P0563 presente por alta tensión en el sistema eléctrico (16.8 V registrados en Freeze Frame a 2400 rpm). El regulador de voltaje electrónico sufrió fuga térmica en el transistor de potencia de excitación manteniéndolo saturado al 100%; la sobretensión recalentó la batería provocando ebullición del ácido y activación de modo de protección de la ECU apagando inyectores.", "TECNICO", "freeze_frame_p0563_sobretension_16_8v", "dtc_p0563|freeze_frame_16_8v_a_2400rpm|transistor_excitacion_saturado_100porciento|bateria_hirviendo", "falla_modulo_motor", "P0563", "NO", "SI", "Bateria descargada o bornes sulfatados", "L3 DTC P0563 con sobretensión de 16.8V y ebullición por transistor saturado.")
    agregar("G47-L3-07", CLASE_47, "L3", "Mi carro ase que la luz del tablero y los faros parpadeen rapido como arbolito de navidad cuando ando de noche. El mecanico le puso el voltimetro y con el carro prendio subia y bajaba de 12 a 15 voltios bien loco. Le bajo el alternador y la placa de diodos taba chamuscada con olor a quemao. La bateria taba buena retiene doce punto seis parada.", "ERROR_ORTOGRAFICO", "luces_parpadean_voltaje_inestable", "luces_parpadean_arbolito_navidad|voltaje_inestable_12_a_15v|placa_diodos_chamuscada|bateria_12_6v_parada", "falla_bateria", "", "NO", "SI", "Bateria descargada o bornes sulfatados", "L3 voltaje oscilante 12-15V con placa chamuscada y ortografía informal.")
    agregar("G47-L3-08", CLASE_47, "L3", "Ensayo en osciloscopio automotriz acoplado a la línea de excitación DF/FR: el alternador emite un zumbido audible de 600 Hz transmitido a los altavoces de la radio que incrementa en frecuencia con la aceleración. La señal muestra una deformación periódica con un semiciclo positivo cortado a cero voltios correspondiente a la destrucción por avalancha de un diodo rectificador principal de 50 A.", "TECNICO", "osciloscopio_zumbido_radio_diodo_destruido", "zumbido_radio_aumenta_con_rpm|semiciclo_cortado_a_cero|diodo_50a_destruido_avalancha", "falla_bateria", "", "NO", "SI", "Bateria descargada o bornes sulfatados", "L3 zumbido en radio con semiciclo cortado confirma diodo rectificador destruido.")
    agregar("G47-L3-09", CLASE_47, "L3", "Prueba de consumo parasitario del alternador en reposo con motor apagado y llave retirada: la pinza amperimétrica de precisión acusa un consumo continuo de 3.85 A que no desciende tras 45 minutos de reposo; al desconectar la tuerca del cable B+ del alternador el consumo del vehículo cae inmediatamente a 28 mA confirmando fuga masiva interna por diodo rectificador en cortocircuito.", "TECNICO", "consumo_reposo_borne_b_positivo_3_85a", "fuga_3_85a_motor_apagado|cae_a_28ma_al_desconectar_b_positivo|diodo_en_corto", "fuga_red_can", "", "NO", "SI", "Fuga parasita de corriente en reposo (consumo nocturno de bateria)", "L3 diodo de alternador en cortocircuito consume 3.85A en reposo.")
    agregar("G47-L3-10", CLASE_47, "L3", "Inspección de polea libre de alternador (OAP / decoupler): el embrague unidireccional interno de rodillos helicoidales se encuentra soldado en ambos sentidos de giro; al desacelerar bruscamente desde 4500 rpm el rotor del alternador transmite latigazos torsionales a la correa de accesorios provocando vibración de 12 mm en el tensor y chillido estridente sin patinamiento de embrague de tracción.", "TALLER", "polea_oap_soldada_latigazos_tensor", "embrague_oap_soldado_dos_sentidos|latigazos_12mm_tensor_accesorios|chillido_al_desacelerar", "falla_embrague_transmision", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L3 polea desacopladora OAP soldada genera latigazos torsionales al desacelerar.")
    agregar("G47-L3-11", CLASE_47, "L3", "Análisis termográfico FLIR de alternador bajo carga de 80 A tras 20 minutos de banco de pruebas: la carcasa posterior alcanza 138°C en el área de la placa rectificadora de diodos mientras la carcasa frontal opera en 62°C (gradiente térmico de 76°C); la soldadura de estaño de dos diodos se encuentra derretida con goteo metálico en el interior de la tapa plástica.", "TECNICO", "termografia_flir_placa_diodos_138c", "temperatura_placa_diodos_138c_vs_62c|gradiente_termico_76c|soldadura_estaño_derretida", "falla_refrigeracion_motor", "", "NO", "SI", "Falla en termostato o motoventilador de radiador", "L3 termografía acusa 138°C en placa de diodos con desoldadura de estaño.")
    agregar("G47-L3-12", CLASE_47, "L3", "Verificación de alternador en vehículo diésel con bomba de vacío de frenos adosada al eje posterior del alternador: el retén de aceite del depresor de vacío se rompió inundando el bobinado del rotor y el colector de delgas con aceite de motor 15W-40 caliente; la mezcla de aceite y polvo de carbón generó un puente conductor entre delgas anulando el campo magnético y dejando la tensión en 12.0 V.", "TALLER", "depresor_vacio_inunda_alternador_aceite", "aceite_depresor_inunda_rotor_delgas|puente_conductor_carbon_aceite|tension_cae_a_12_0v", "falla_servofreno_vacio", "", "NO", "SI", "Falla en servofreno (booster) o linea de vacio", "L3 fuga de aceite de bomba de vacío contamina alternador anulando excitación.")
    agregar("G47-L3-13", CLASE_47, "L3", "Evaluación de bus LIN de alternador en BMW Serie 3 con escáner ISTA: código de error 2E97 almacenado por generador sin comunicación en línea BSD/LIN; el alternador opera en modo de emergencia por defecto suministrando tensión fija de 13.55 V independiente de la demanda eléctrica y el estado de carga de la batería AGM, impidiendo la regeneración en frenada.", "TECNICO", "scanner_ista_codigo_2e97_lin_bsd", "dtc_2e97_bsd_lin|tension_emergencia_fija_13_55v|sin_carga_inteligente_agm", "falla_bateria_agm", "", "NO", "SI", "Bateria descargada o bornes sulfatados", "L3 código 2E97 de comunicación BSD fija tensión en modo degradado 13.55V.")
    agregar("G47-L3-14", CLASE_47, "L3", "Prueba de aislamiento de bobinado de estator con megóhmetro a 500 V DC: resistencia de aislamiento fase-carcasa de 0.08 Megaohmios (especificación mínima superior a 5.0 Megaohmios); en caliente a 85°C el barniz aislante se perfora provocando derivación a tierra que descarga la batería a través del chasis en solo 4 horas de uso.", "TECNICO", "megohmetro_estator_0_08_megaohm", "aislamiento_fase_carcasa_0_08_mohm_vs_5_mohm|perforacion_barniz_85c|derivacion_a_tierra", "falla_fuga_parasita", "", "NO", "SI", "Fuga parasita de corriente en reposo (consumo nocturno de bateria)", "L3 megóhmetro registra 0.08 Mohm de aislamiento en estator perforado.")
    agregar("G47-L3-15", CLASE_47, "L3", "Sustitución de alternador tras fractura mecánica de rodamiento trasero de agujas del rotor: el rotor experimentó descentramiento radial de 1.2 mm rozando físicamente contra los núcleos polares del estator a 3500 rpm con chirrido estridente de 96 dBA y desprendimiento de virutas de hierro que destruyeron las escobillas del regulador.", "TALLER", "rodamiento_rotor_descentrado_roce_estator", "rodamiento_rotor_destruido|descentramiento_1_2mm_roza_estator|virutas_destruyen_escobillas", "falla_correa_distribucion", "", "NO", "SI", "Faja o cadena de distribucion destensada o con salto de punto", "L3 rotor rozando contra estator por rodamiento destruido genera 96 dBA.")

    # =========================================================================
    # CLASE 48: Bateria descargada o bornes sulfatados (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G48-L1-01", CLASE_48, "L1", "Al girar la llave para encender el carro solo hace un tic-tic-tic rápido y el tablero se apaga.", "COTIDIANO", "intento_arranque_tic_tic", "tic_tic_tic_rapido_tablero_se_apaga", "", "", "SI", "NO", "", "L1 tic-tic rápido con apagado de tablero.")
    agregar("G48-L1-02", CLASE_48, "L1", "Hola, hoy quise prender el auto y está completamente muerto, ni la luz del techo prende.", "WHATSAPP", "manana_completamente_muerto", "completamente_muerto_sin_luz_techo", "", "", "SI", "NO", "", "L1 carro muerto sin luces.")
    agregar("G48-L1-03", CLASE_48, "L1", "Veo como un polvo blanco y verdoso reseco acumulado encima de los postes de la batería.", "COTIDIANO", "inspeccion_bornes_polvo", "polvo_blanco_verdoso_postes_bateria", "", "", "SI", "NO", "", "L1 sulfatación visible en bornes.")
    agregar("G48-L1-04", CLASE_48, "L1", "El motor intenta girar pero muy lento y pesado como si le faltara fuerza eléctrica.", "COTIDIANO", "crank_lento_pesado", "motor_gira_lento_pesado_sin_fuerza", "", "", "SI", "NO", "", "L1 crank lento y pesado.")
    agregar("G48-L1-05", CLASE_48, "L1", "Si le pongo cables pasacorriente arranca de una pero al apagarlo ya no tiene fuerza.", "TALLER", "arranque_con_puente", "arranca_con_cables_no_retiene_fuerza", "", "", "SI", "NO", "", "L1 arranca con puente pero no retiene.")
    agregar("G48-L1-06", CLASE_48, "L1", "Buenas, el carro no da arranque y las agujas del velocímetro vibran locas al fondo.", "WHATSAPP", "intento_arranque_agujas", "agujas_vibran_sin_arrancar", "", "", "SI", "NO", "", "L1 reseteo de agujas en intento de arranque.")
    agregar("G48-L1-07", CLASE_48, "L1", "A veces no prende nada y si muevo los cables de la batería con la mano vuelve la corriente.", "COTIDIANO", "mover_cables_bateria", "vuelve_corriente_al_mover_cables", "", "", "SI", "NO", "", "L1 falso contacto en cables de batería.")
    agregar("G48-L1-08", CLASE_48, "L1", "Ayuda ase clac clac clac en el motor y se reinisia el estereo.", "ERROR_ORTOGRAFICO", "reinicio_estereo_clac", "clac_clac_clac_reinisia_estereo", "", "", "SI", "NO", "", "L1 clac rápido con reinicio de estéreo.")
    agregar("G48-L1-09", CLASE_48, "L1", "La batería ya tiene como 4 años y en invierno le cuesta un mundo hacer girar el motor.", "COTIDIANO", "invierno_antiguedad", "bateria_4_anos_cuesta_en_frio", "", "", "SI", "NO", "", "L1 batería vieja con dificultad en frío.")
    agregar("G48-L1-10", CLASE_48, "L1", "Giro el contacto y se escucha un chasquido continuo de relés adentro del tablero.", "COTIDIANO", "contacto_chasquido_reles", "chasquido_continuo_reles_tablero", "", "", "SI", "NO", "", "L1 chasquido de relés por baja tensión.")

    # --- L2 (15 casos) ---
    agregar("G48-L2-01", CLASE_48, "L2", "Voltaje en reposo de la batería de 11.4 V con motor apagado; al dar arranque el voltaje cae en picada a 6.2 V y el motor de arranque apenas gira una vuelta pesada.", "TECNICO", "reposo_y_cranking_caida_6_2v", "reposo_11_4v|caida_en_cranking_a_6_2v|crank_lento_pesado", "falla_motor_arranque", "", "NO", "SI", "Falla en motor de arranque o solenoide defectuoso (clac seco o carbones gastados)", "L2 caída severa a 6.2V en cranking descarta motor de arranque.")
    agregar("G48-L2-02", CLASE_48, "L2", "Bornes positivo y negativo con costra gruesa de sulfato de plomo azulado; al medir con multímetro hay 12.6 V en los postes de plomo pero solo 9.8 V en los terminales de cobre.", "TALLER", "caida_tension_bornes_sulfatados", "costra_sulfato_plomo_bornes|12_6v_en_postes_vs_9_8v_en_terminales", "falla_bateria_interna", "", "NO", "SI", "Alternador defectuoso o placa de diodos quemada", "L2 caída de tensión de 2.8V entre poste y terminal por sulfato.")
    agregar("G48-L2-03", CLASE_48, "L2", "El auto arranca al toque si se le colocan cables pasacorriente desde otro auto; una vez encendido el alternador mantiene 14.2 V estables en marcha.", "COTIDIANO", "puente_arranca_alternador_14_2v", "arranca_con_cables_al_toque|alternador_mantiene_14_2v", "falla_alternador", "", "NO", "SI", "Alternador defectuoso o placa de diodos quemada", "L2 alternador genera 14.2V perfecto descarta alternador.")
    agregar("G48-L2-04", CLASE_48, "L2", "Batería de ácido-plomo con una celda comunicada o en cortocircuito interno; la tensión en vacío se estanca en 10.5 V fijos y no sube aunque se cargue durante 12 horas.", "TECNICO", "celda_cortocircuito_10_5v", "tension_estancada_10_5v|celda_en_cortocircuito_interno|no_carga_12h", "falla_fuga_nocturna", "", "NO", "SI", "Fuga parasita de corriente en reposo (consumo nocturno de bateria)", "L2 celda en corto estancada en 10.5V fijos.")
    agregar("G48-L2-05", CLASE_48, "L2", "Al accionar el arranque se produce un tableteo rápido tipo ametralladora del solenoide porque la tensión se desploma por debajo de 8 V; las luces de cabina se extinguen.", "COTIDIANO", "tableteo_ametralladora_solenoide", "tableteo_rapido_solenoide|tension_desploma_bajo_8v|luces_se_apagan", "falla_solenoide_arranque", "", "NO", "SI", "Falla en motor de arranque o solenoide defectuoso (clac seco o carbones gastados)", "L2 ametralladora por caída bajo 8V descarta solenoide roto.")
    agregar("G48-L2-06", CLASE_48, "L2", "Hola maestro, dejé el auto con las luces de parqueo prendidas por 4 horas y la batería se agotó; empujando en segunda arrancó y el alternador carga a 14.1 V.", "WHATSAPP", "luces_parqueo_4_horas_agotada", "bateria_agotada_por_luces_parqueo|arranca_empujando|alternador_14_1v", "falla_alternador", "", "NO", "SI", "Alternador defectuoso o placa de diodos quemada", "L2 descarga por luces olvidadas con alternador sano a 14.1V.")
    agregar("G48-L2-07", CLASE_48, "L2", "Densímetro de batería acusa densidad de electrolito de 1.12 g/cm3 en los 6 vasos (completamente descargada, valor nominal 1.28 g/cm3); el alternador genera correctamente.", "TECNICO", "densimetro_electrolito_1_12", "densidad_electrolito_1_12_vs_1_28|bateria_descargada_quimicamente", "falla_alternador", "", "NO", "SI", "Alternador defectuoso o placa de diodos quemada", "L2 densímetro marca 1.12 g/cm3 confirmando descarga total de electrolito.")
    agregar("G48-L2-08", CLASE_48, "L2", "Terminal negativo flojo en el poste de batería; al intentar dar arranque la chispa salta en el borne y se corta toda la energía del tablero instantáneamente.", "TALLER", "terminal_negativo_flojo_chispa", "borne_negativo_flojo|chispa_en_borne_corta_energia_tablero", "falla_chapa_contacto", "", "NO", "SI", "Falla en motor de arranque o solenoide defectuoso (clac seco o carbones gastados)", "L2 borne flojo genera chispa y corta energía total.")
    agregar("G48-L2-09", CLASE_48, "L2", "Batería sellada libre de mantenimiento muestra el visor óptico (ojo mágico) de color negro opaco indicando necesidad de recarga urgente; en reposo marca 11.7 V.", "COTIDIANO", "ojo_magico_negro_11_7v", "ojo_magico_negro_necesita_recarga|tension_reposo_11_7v", "falla_fuga_parasita", "", "NO", "SI", "Fuga parasita de corriente en reposo (consumo nocturno de bateria)", "L2 ojo mágico en negro y 11.7V confirman batería descargada.")
    agregar("G48-L2-10", CLASE_48, "L2", "Comprobador digital de baterías por conductancia arroja resultado 'Reemplazar Batería' con State of Health (SOH) de 22% y resistencia interna de 28 miliohmios (nominal 4.5 mohm).", "TECNICO", "conductancia_soh_22_porciento", "analizador_conductancia_soh_22porciento|resistencia_interna_28mohm_vs_4_5mohm", "falla_motor_arranque", "", "NO", "SI", "Falla en motor de arranque o solenoide defectuoso (clac seco o carbones gastados)", "L2 analizador de conductancia determina SOH en 22% por sulfatación.")
    agregar("G48-L2-11", CLASE_48, "L2", "Buenas tardes, el carro arranca bien si lo uso seguido cada hora, pero si lo dejo parado 4 horas la batería pierde fuerza y gira pesado; no hay consumo parásito.", "WHATSAPP", "autodescarga_interna_4_horas", "pierde_fuerza_en_4_horas|crank_pesado_lento", "fuga_parasita_nocturna", "", "NO", "SI", "Fuga parasita de corriente en reposo (consumo nocturno de bateria)", "L2 autodescarga química interna en 4 horas sin fuga parásita.")
    agregar("G48-L2-12", CLASE_48, "L2", "Nivel de agua destilada y electrolito por debajo de las placas de plomo en 3 vasos; las placas superiores se secaron y se sulfataron irreversiblemente con plomo blanco.", "TALLER", "placas_secas_sulfatadas_blanco", "electrolito_bajo_placas_secas|placas_sulfatadas_en_blanco", "falla_alternador", "", "NO", "SI", "Alternador defectuoso o placa de diodos quemada", "L2 placas de plomo secas y sulfatadas por falta de agua.")
    agregar("G48-L2-13", CLASE_48, "L2", "La radio pierde las memorias FM y el reloj se resetea a 12:00 cada vez que se da arranque debido al desplome de tensión a 7 V provocado por batería agotada.", "COTIDIANO", "reinicio_reloj_radio_al_arrancar", "reloj_resetea_12_00_en_arranque|caida_de_tension_a_7v", "falla_motor_arranque", "", "NO", "SI", "Falla en motor de arranque o solenoide defectuoso (clac seco o carbones gastados)", "L2 reseteo de reloj al arrancar por caída a 7V de batería.")
    agregar("G48-L2-14", CLASE_48, "L2", "Batería AGM de 70 Ah con 5 años de servicio; la corriente de arranque en frío medida es de 180 A CCA frente a los 680 A CCA estipulados en la etiqueta.", "TECNICO", "bateria_agm_180cca_vs_680cca", "capacidad_arranque_180cca_vs_680cca|bateria_agm_agotada_5_anos", "falla_alternador", "", "NO", "SI", "Alternador defectuoso o placa de diodos quemada", "L2 batería AGM entrega solo 180 CCA de 680 CCA nominales.")
    agregar("G48-L2-15", CLASE_48, "L2", "Bornes con apriete cónico suelto; al aplicar fuerza con la mano el terminal gira sobre el poste impidiendo que pasen los 150 A requeridos por el motor de arranque.", "TALLER", "borne_gira_suelto_conico", "borne_gira_con_la_mano|mal_contacto_conico_postes", "falla_solenoide", "", "NO", "SI", "Falla en motor de arranque o solenoide defectuoso (clac seco o carbones gastados)", "L2 borne suelto que gira a mano impide paso de alta corriente.")

    # --- L3 (15 casos) ---
    agregar("G48-L3-01", CLASE_48, "L3", "Evaluación de batería plomo-ácido de 12 V 60 Ah con probador de descarga con resistencia de carbón (carbon pile load tester): en circuito abierto tras 4 horas de reposo la batería registra 12.10 V (50% de carga). Al aplicar una corriente de descarga de 300 A (la mitad del CCA nominal de 600 A) durante 15 segundos la tensión cae bruscamente a 7.40 V (especificación mínima a 20°C debe superar los 9.60 V) con ebullición violenta en el tercer vaso. El alternador en ralentí entrega 14.25 V estables con 25 A de salida descartando falla de carga.", "TECNICO", "carbon_pile_300a_15s_cae_a_7_40v", "carbon_pile_300a_cae_a_7_40v_vs_9_60v|ebullicion_tercer_vaso|alternador_estable_14_25v", "falla_alternador", "", "NO", "SI", "Alternador defectuoso o placa de diodos quemada", "L3 carbon pile tester acusa 7.40V bajo 300A con alternador sano a 14.25V.")
    agregar("G48-L3-02", CLASE_48, "L3", "Diagnóstico de caída de tensión en conexiones de batería (Volt Drop Testing) durante la fase de cranking: se colocó multímetro digital entre el poste central de plomo de la batería y el borne terminal de bronce positivo registrando una caída de tensión de 3.45 V al accionar la llave (tolerancia máxima de conexión 0.20 V). La superficie de contacto interna presentaba pasivación y sulfatación microscópica de sulfato de plomo aislante; tras limpiar los postes con cepillo de cerdas de acero y aplicar grasa dieléctrica la caída bajó a 0.04 V y el motor arrancó en 1.1 segundos.", "TECNICO", "volt_drop_bornes_3_45v_vs_0_20v", "caida_tension_borne_poste_3_45v_vs_0_20v|sulfatacion_aislante_limpieza|caida_baja_a_0_04v", "falla_motor_arranque", "", "NO", "SI", "Falla en motor de arranque o solenoide defectuoso (clac seco o carbones gastados)", "L3 caída de tensión de 3.45V entre poste y borne por sulfatación aislante.")
    agregar("G48-L3-03", CLASE_48, "L3", "Análisis electroquímico con refractómetro óptico de compensación automática de temperatura (ATC): gravedad específica del electrolito en los 6 vasos: vaso 1: 1.115 g/cm3, vaso 2: 1.118 g/cm3, vaso 3: 1.110 g/cm3, vaso 4: 1.265 g/cm3, vaso 5: 1.112 g/cm3, vaso 6: 1.114 g/cm3; desequilibrio grave de gravedad específica con estratificación ácida irreversible. La batería no es capaz de suministrar más de 90 A sin colapsar por debajo de 8 V.", "TECNICO", "refractometro_atc_densidad_1_110", "densidad_electrolito_1_110_estratificacion_acida|desequilibrio_entre_vasos|colapso_bajo_8v", "falla_fuga_parasita", "", "NO", "SI", "Fuga parasita de corriente en reposo (consumo nocturno de bateria)", "L3 refractómetro acusa estratificación ácida a 1.110 g/cm3 colapsando bajo 8V.")
    agregar("G48-L3-04", CLASE_48, "L3", "Hola maestro, tengo un Nissan Tiida. En la mañana al darle al arranque el tablero hace tac-tac-tac rápido como una metralleta, las luces de advertencia parpadean y el motor ni gira. Vino un amigo con cables y puenteamos desde su auto y prendió al segundo intento suavecito. Con el auto prendido medimos el alternador con tester y da 14.15 V parejito, pero apago el carro y la batería en 5 minutos ya marca 10.8 V y no vuelve a prender.", "WHATSAPP", "tiida_tac_tac_metralleta_puente_ok", "metralleta_tac_tac_tablero_parpadea|arranca_con_puente_al_segundo|alternador_14_15v|bateria_cae_a_10_8v", "falla_alternador", "", "NO", "SI", "Alternador defectuoso o placa de diodos quemada", "L3 relato WhatsApp de metralleta que arranca con puente con alternador sano a 14.15V.")
    agregar("G48-L3-05", CLASE_48, "L3", "Medición de corriente de cranking con pinza amperimétrica True RMS y osciloscopio: al activar el arranque la corriente inicial inrush alcanza solo 140 A (nominal 450 A para motor 2.0L) mientras la tensión en bornes cae a 5.8 V debido a que la resistencia interna de la batería aumentó a 42 miliohmios por sulfatación dura de placas (plomo sulfatado cristalizado blanco no reactivo).", "TECNICO", "pinza_amperimetrica_inrush_140a_vs_450a", "corriente_inrush_140a_vs_450a|tension_cae_a_5_8v|resistencia_interna_42mohm|sulfatacion_cristalizada", "falla_motor_arranque", "", "NO", "SI", "Falla en motor de arranque o solenoide defectuoso (clac seco o carbones gastados)", "L3 corriente inrush limitada a 140A por resistencia interna de 42 mohm.")
    agregar("G48-L3-06", CLASE_48, "L3", "Comprobación de batería AGM con analizador de impedancia Midtronics: State of Charge (SOC) en 45%, State of Health (SOH) en 18%, capacidad CCA residual de 160 A (etiqueta 800 A CCA EN). El calculador de gestión de energía IBS (Intelligent Battery Sensor) montado en el borne negativo registra DTC 299B referente a batería profundamente descargada con degradación irrecuperable por ciclos térmicos superiores a 60°C en vano motor.", "TECNICO", "midtronics_soh_18porciento_dtc_299b", "midtronics_soh_18porciento|cca_160a_vs_800a|sensor_ibs_dtc_299b|bateria_profundamente_descargada", "falla_alternador_lin", "", "NO", "SI", "Alternador defectuoso o placa de diodos quemada", "L3 Midtronics mide 18% SOH con sensor IBS reportando degradación irreversible.")
    agregar("G48-L3-07", CLASE_48, "L3", "Mi carro ase un chasquido continuo en los reles del tablero cuando jiro la llave y se bajan los seguros solos. Los bornes de la bateria tenian un cerro de polvo verde y blanco que parecia salitre. Cuando le pase corriente con cables gruesos de camion prendio al toque. El alternador bota catorce punto dos voltios con el carro encendio.", "ERROR_ORTOGRAFICO", "polvo_verde_blanco_salitre_cables", "chasquido_reles_tablero|bornes_polvo_verde_blanco_salitre|arranca_con_cables|alternador_14_2v", "falla_alternador", "", "NO", "SI", "Alternador defectuoso o placa de diodos quemada", "L3 sulfatación salitrosa con alternador a 14.2V y ortografía informal.")
    agregar("G48-L3-08", CLASE_48, "L3", "Prueba de autodescarga electroquímica en banco: batería desconectada físicamente del vehículo en estante de taller a 22°C ambiente pierde 0.35 V diarios (de 12.60 V a 11.20 V en 4 días) sin ninguna carga conectada debido a sedimentación de lodos de dióxido de plomo en el fondo de las celdas que tocan los separadores microporosos generando micro-cortocircuitos internos.", "TECNICO", "autodescarga_banco_0_35v_diarios_lodos", "autodescarga_0_35v_diarios_en_banco|sedimentacion_lodos_plomo|separadores_perforados", "falla_fuga_parasita", "", "NO", "SI", "Fuga parasita de corriente en reposo (consumo nocturno de bateria)", "L3 autodescarga de 0.35 V/día en banco desconectado por sedimentación de lodos.")
    agregar("G48-L3-09", CLASE_48, "L3", "Medición de caída de tensión en masa de chasis (Ground Voltage Drop Test): al aplicar arranque el voltímetro entre borne negativo de batería y bloque motor marca 0.08 V (excelente conexión de masa de motor), pero entre borne negativo y la chapa del borne registra 2.90 V por corrosión interna entre el cable de cobre prensado y el terminal de plomo.", "TECNICO", "ground_drop_test_borne_a_cable_2_90v", "caida_borne_negativo_a_cable_2_90v_vs_0_05v|masa_bloque_0_08v_ok|corrosion_cobre_plomo", "falla_motor_arranque", "", "NO", "SI", "Falla en motor de arranque o solenoide defectuoso (clac seco o carbones gastados)", "L3 caída de tensión de 2.90V en prensado de cable negativo por corrosión.")
    agregar("G48-L3-10", CLASE_48, "L3", "Inspección de caja plástica de batería: fisura por fatiga de 4 cm en la base inferior del contenedor de polipropileno con fuga lenta de ácido sulfúrico hacia la bandeja de soporte; la densidad del vaso afectado cayó a 1.05 g/cm3 dejando la batería con solo 5 celdas operativas (10.2 V totales en circuito abierto).", "TALLER", "fisura_caja_polipropileno_fuga_acido", "fisura_contenedor_polipropileno|fuga_acido_sulfurico|5_celdas_operativas_10_2v", "falla_alternador", "", "NO", "SI", "Alternador defectuoso o placa de diodos quemada", "L3 fisura de caja con pérdida de electrolito deja 5 celdas en 10.2V.")
    agregar("G48-L3-11", CLASE_48, "L3", "Vehículo ingresa por reseteo continuo de dirección electroasistida EPS y código DTC C1551 de bajo voltaje de alimentación en la ECU de dirección: el escáner registra que durante el accionamiento del motor de arranque la tensión cae a 6.8 V durante 1.8 segundos; la batería original de fábrica tiene 6 años de antigüedad con resistencia óhmica cuatriplicada.", "TECNICO", "scanner_dtc_c1551_bajo_voltaje_cranking", "dtc_c1551_ecu_eps|tension_cae_a_6_8v_en_cranking|bateria_6_anos_resistencia_cuatriplicada", "falla_cremallera_eps", "C1551", "NO", "SI", "Cremallera de direccion asistida con holgura o fuga", "L3 DTC C1551 por caída a 6.8V en arranque debido a batería vieja.")
    agregar("G48-L3-12", CLASE_48, "L3", "Prueba de aceptación de carga (Charge Acceptance Test según norma EN 50342): tras descargar la batería al 50% y conectarla a fuente estabilizada de 14.40 V a 25°C la corriente absorbida es de apenas 1.4 A (especificación mínima superior a 12 A) por pasivación de sulfato de plomo en placas negativas.", "TECNICO", "charge_acceptance_en50342_1_4a_vs_12a", "aceptacion_carga_1_4a_vs_12a|pasivacion_sulfato_plomo|resistencia_a_recarga", "falla_alternador", "", "NO", "SI", "Alternador defectuoso o placa de diodos quemada", "L3 prueba EN 50342 acusa absorción de solo 1.4A por placas pasivadas.")
    agregar("G48-L3-13", CLASE_48, "L3", "Ensayo de arranque en frío a 0°C en cámara climática: la tensión de reposo marca 12.30 V pero al solicitar arranque a solenoide la tensión se desploma instantáneamente a 5.1 V bloqueando el Bendix en la corona; tras entibiar la batería a 25°C la tensión bajo carga asciende a 8.2 V confirmando pérdida crítica de capacidad CCA por sulfatación térmica previa.", "TECNICO", "camara_climatica_0c_desplome_5_1v", "camara_climatica_0c_desplome_5_1v|bendix_bloqueado|perdida_cca_por_frio", "falla_motor_arranque", "", "NO", "SI", "Falla en motor de arranque o solenoide defectuoso (clac seco o carbones gastados)", "L3 ensayo a 0°C desploma batería a 5.1V bloqueando bendix.")
    agregar("G48-L3-14", CLASE_48, "L3", "Comprobación de perno de apriete de borne positivo: perno de acero roscado barrido con torque nulo; al tirar del cable con la mano el borne se desprende del poste cónico de plomo; esto provocaba cortes de encendido aleatorios al pasar por resaltos de la calzada simulando fallo de sensor de cigüeñal.", "TALLER", "perno_rosca_barrida_borne_suelto", "perno_borne_positivo_barrido|borne_suelto_se_desprende|cortes_en_resaltos", "falla_sensor_ckp", "", "NO", "SI", "Falla en sensor de posicion de cigueñal (CKP) o arbol de levas (CMP)", "L3 borne positivo con rosca barrida causa cortes de encendido en baches.")
    agregar("G48-L3-15", CLASE_48, "L3", "Diagnóstico de batería EFB (Enhanced Flooded Battery) en vehículo Start-Stop: el sistema Start-Stop se encuentra desactivado permanentemente por la BCM con mensaje 'Gestión de Batería No Disponible'; el analizador de batería registra resistencia interna de 18.5 mohm y capacidad de 240 A CCA (original 720 A CCA) por sulfatación tras 85,000 ciclos de arranque urbano.", "TECNICO", "bateria_efb_start_stop_inactivo_240cca", "start_stop_desactivado_por_bcm|resistencia_18_5mohm|capacidad_240cca_vs_720cca", "falla_motor_arranque", "", "NO", "SI", "Falla en motor de arranque o solenoide defectuoso (clac seco o carbones gastados)", "L3 Start-Stop bloqueado por batería EFB degradada a 240 CCA.")

    # =========================================================================
    # CLASE 49: Degradacion o falla en paquete de bateria de alto voltaje (EV / Hibridos) (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G49-L1-01", CLASE_49, "L1", "En la pantalla del híbrido sale un mensaje de revisar sistema híbrido y bajó la autonomía.", "COTIDIANO", "pantalla_hibrido_aviso", "aviso_revisar_sistema_hibrido_baja_autonomia", "", "", "SI", "NO", "", "L1 aviso de revisar sistema híbrido.")
    agregar("G49-L1-02", CLASE_49, "L1", "Hola, la batería de tracción se descarga rapidísimo con solo subir una pequeña pendiente.", "WHATSAPP", "subida_pendiente_descarga", "bateria_traccion_descarga_rapido_subida", "", "", "SI", "NO", "", "L1 descarga rápida en pendiente.")
    agregar("G49-L1-03", CLASE_49, "L1", "El carro eléctrico no llega ni a la mitad de los kilómetros que recorría antes con carga llena.", "COTIDIANO", "autonomia_reducida_mitad", "autonomia_reducida_a_la_mitad", "", "", "SI", "NO", "", "L1 autonomía reducida a la mitad.")
    agregar("G49-L1-04", CLASE_49, "L1", "El indicador de carga de la batería alta sube y baja de golpe como loco.", "COTIDIANO", "indicador_carga_inestable", "indicador_carga_salta_de_golpe", "", "", "SI", "NO", "", "L1 indicador de carga salta de golpe.")
    agregar("G49-L1-05", CLASE_49, "L1", "En el escaneo de rutina me dijeron que hay bloques de celdas desbalanceados.", "TALLER", "escaneo_celdas_desbalanceadas", "celdas_bateria_desbalanceadas", "", "", "SI", "NO", "", "L1 celdas desbalanceadas sin DTC.")
    agregar("G49-L1-06", CLASE_49, "L1", "Buenas, el motor de gasolina enciende casi todo el tiempo y el modo EV dura segundos.", "WHATSAPP", "modo_ev_segundos", "modo_ev_dura_segundos_motor_gasolina_fijo", "", "", "SI", "NO", "", "L1 modo EV dura segundos en híbrido.")
    agregar("G49-L1-07", CLASE_49, "L1", "Se prendió la tortuga amarilla de potencia reducida en el tablero de mi auto eléctrico.", "COTIDIANO", "tortuga_potencia_reducida", "testigo_tortuga_potencia_reducida", "", "", "SI", "NO", "", "L1 testigo de tortuga en tablero EV.")
    agregar("G49-L1-08", CLASE_49, "L1", "Ayuda mi carro hibrido no retiene la carga de la bateria grande.", "ERROR_ORTOGRAFICO", "bateria_grande_no_retiene", "bateria_grande_no_retiene_carga", "", "", "SI", "NO", "", "L1 batería grande no retiene con ortografía informal.")
    agregar("G49-L1-09", CLASE_49, "L1", "El auto no pasa de 60 km/h y sale advertencia de degradación de batería.", "COTIDIANO", "limite_velocidad_advertencia", "limite_60kmh_advertencia_bateria", "", "", "SI", "NO", "", "L1 limitación de velocidad con advertencia de batería.")
    agregar("G49-L1-10", CLASE_49, "L1", "Se apaga el sistema de alta tensión al acelerar con fuerza para adelantar.", "TALLER", "aceleracion_fuerte_corte_hv", "corte_alta_tension_acelerar_fuerte", "", "", "SI", "NO", "", "L1 corte de alta tensión al acelerar.")

    # --- L2 (15 casos) ---
    agregar("G49-L2-01", CLASE_49, "L2", "Vehículo híbrido presenta código DTC P0A80 referente a sustitución de batería de alta tensión; el motor térmico permanece encendido de continuo en semáforos.", "TECNICO", "semáforo_dtc_p0a80", "dtc_p0a80|motor_termico_encendido_continuo_semaforo", "falla_bateria_12v", "P0A80", "NO", "SI", "Bateria descargada o bornes sulfatados", "L2 DTC P0A80 por degradación de batería HV descarta 12V.")
    agregar("G49-L2-02", CLASE_49, "L2", "En vehículo eléctrico puro la autonomía máxima estimada cayó de 280 km a solo 110 km con State of Health (SOH) reportado por BMS en 54%; la batería auxiliar de 12 V está nueva.", "TECNICO", "autonomia_110km_soh_54porciento", "autonomia_cae_280_a_110km|bms_soh_54porciento|bateria_12v_nueva", "falla_bateria_12v", "", "NO", "SI", "Bateria descargada o bornes sulfatados", "L2 SOH del 54% en batería HV con batería 12V impecable.")
    agregar("G49-L2-03", CLASE_49, "L2", "Desequilibrio de tensión entre bloques de celdas de la batería HV: en aceleración fuerte el bloque número 7 cae a 11.8 V mientras los otros 13 bloques se mantienen en 14.4 V.", "TECNICO", "aceleracion_bloque_7_desbalanceado", "bloque_7_cae_a_11_8v_vs_14_4v|desbalance_bms", "falla_inversor", "", "NO", "SI", "Fallo en inversor de corriente IGBT o motor electrico (EV)", "L2 bloque 7 de batería HV con desequilibrio severo descarta inversor.")
    agregar("G49-L2-04", CLASE_49, "L2", "DTC P0A7F almacenado en calculador de batería de tracción (Hybrid Battery Pack Deterioration); el ventilador de enfriamiento opera normal y no hay sobrecalentamiento.", "TECNICO", "dtc_p0a7f_deterioro_bateria", "dtc_p0a7f|ventilador_opera_normal|sin_sobrecalentamiento", "falla_refrigeracion_bateria", "P0A7F", "NO", "SI", "Foco o falla en sistema de refrigeracion de bateria/inversor (EV)", "L2 DTC P0A7F con sistema de ventilación normal descarta refrigeración.")
    agregar("G49-L2-05", CLASE_49, "L2", "La barra de State of Charge (SOC) en el tablero pasa de 8 barras (lleno) a 2 barras (morado vacío) en apenas 500 metros de subida suave en vehículo híbrido.", "COTIDIANO", "subida_suave_500m_desplome_soc", "soc_desploma_8_a_2_barras_en_500m|perdida_capacidad_util", "falla_inversor", "", "NO", "SI", "Fallo en inversor de corriente IGBT o motor electrico (EV)", "L2 colapso del SOC de 8 a 2 barras en 500m confirma batería HV agotada.")
    agregar("G49-L2-06", CLASE_49, "L2", "Hola maestro, en mi auto híbrido sale 'Check Hybrid System'; la batería pequeña de 12 V del maletero tiene 12.6 V y prende las luces pero el carro no entra a READY.", "WHATSAPP", "bateria_12v_ok_no_entra_ready", "aviso_check_hybrid_system|bateria_12v_12_6v_ok|no_entra_a_ready", "falla_bateria_12v", "", "NO", "SI", "Bateria descargada o bornes sulfatados", "L2 batería 12V perfecta pero no entra a READY por fallo en pack HV.")
    agregar("G49-L2-07", CLASE_49, "L2", "Resistencia interna de los módulos NiMH de alta tensión duplicada por sulfatación de terminales inter-módulo de cobre; la batería se calienta a 48°C con carga lenta.", "TECNICO", "resistencia_interna_nimh_duplicada", "resistencia_interna_duplicada|bornes_cobre_sulfatados_intermodulo|temperatura_48c", "falla_refrigeracion", "", "NO", "SI", "Foco o falla en sistema de refrigeracion de bateria/inversor (EV)", "L2 resistencia interna de módulos HV alta con terminales de cobre sulfatados.")
    agregar("G49-L2-08", CLASE_49, "L2", "Vehículo eléctrico limita la potencia de propulsión al 40% al llegar al 30% de carga; dos celdas pouch de polímero de litio tienen hinchazón física y deforman el módulo.", "TALLER", "celdas_pouch_hinchadas", "potencia_limitada_al_40porciento|celdas_pouch_hinchadas_deformadas", "falla_motor_electrico", "", "NO", "SI", "Fallo en inversor de corriente IGBT o motor electrico (EV)", "L2 celdas pouch infladas limitan potencia al 40% descarta motor.")
    agregar("G49-L2-09", CLASE_49, "L2", "Al desacelerar en bajada el sistema de frenado regenerativo no acumula energía en la batería HV porque el BMS corta la carga por sobretensión en módulo 4.", "TECNICO", "frenado_regenerativo_corta_carga", "frenado_regenerativo_rechazado_por_bms|sobretension_modulo_4", "falla_freno_regenerativo", "", "NO", "SI", "Falla en sistema de frenado regenerativo (EV / Hibridos)", "L2 rechazo de carga regenerativa por módulo 4 defectuoso.")
    agregar("G49-L2-10", CLASE_49, "L2", "DTC P0A7E presente en módulo de batería de tracción referente a sobretemperatura física en celda de alta tensión sin existir obstrucción en el conducto de aire.", "TECNICO", "dtc_p0a7e_sobretemperatura_celda", "dtc_p0a7e|sobretemperatura_celda_hv|conductos_aire_limpios", "falla_ventilador_bateria", "P0A7E", "NO", "SI", "Foco o falla en sistema de refrigeracion de bateria/inversor (EV)", "L2 DTC P0A7E por celda degradada recalentada con ducto limpio.")
    agregar("G49-L2-11", CLASE_49, "L2", "Buenas tardes, el carro híbrido gasta el doble de gasolina porque la batería grande casi no aporta tracción; el modo 100% eléctrico se desconecta en 5 segundos.", "WHATSAPP", "modo_ev_desconecta_en_5s", "consumo_doble_gasolina|modo_ev_apaga_en_5_segundos|bateria_hv_sin_aporte", "falla_inyectores", "", "NO", "SI", "Inyectores sucios o filtro de combustible obstruido", "L2 modo EV de 5 segundos fuerza motor de gasolina elevando consumo.")
    agregar("G49-L2-12", CLASE_49, "L2", "Contactor principal de alta tensión (rele SMR positivo) no enclava por bobina abierta; el bus de alto voltaje permanece en 0 V y el tablero muestra advertencia de tracción.", "TECNICO", "rele_smr_positivo_abierto", "rele_smr_positivo_no_enclava|bus_hv_en_cero_voltios|advertencia_traccion", "falla_inversor", "", "NO", "SI", "Fallo en inversor de corriente IGBT o motor electrico (EV)", "L2 contactor SMR de batería HV abierto mantiene bus en 0V.")
    agregar("G49-L2-13", CLASE_49, "L2", "Batería de iones de litio de 400 V con State of Health de 58%; el vehículo completa la recarga del 20% al 80% en solo 12 minutos por pérdida severa de capacidad útil.", "TECNICO", "recarga_anormalmente_rapida_12min", "soh_58porciento_bateria_400v|recarga_20_a_80_en_12_minutos|perdida_capacidad_util", "falla_cargador_a_bordo", "", "NO", "NO", "", "L2 recarga anormalmente rápida por pérdida de capacidad útil en pack 400V.")
    agregar("G49-L2-14", CLASE_49, "L2", "Al conectar cargador de nivel 2 se interrumpe la carga al 65% con error de aislamiento interno en el módulo de celdas número 3 de la batería de tracción.", "TALLER", "cargador_nivel_2_interrumpe_65", "interrupcion_carga_al_65porciento|falla_aislamiento_modulo_3", "falla_inversor", "", "NO", "SI", "Fallo en inversor de corriente IGBT o motor electrico (EV)", "L2 interrupción de carga por fuga de aislamiento en módulo 3.")
    agregar("G49-L2-15", CLASE_49, "L2", "La aceleración en modo eléctrico trepida y se apaga de golpe si se pisa más de un tercio del acelerador; la batería HV no soporta demandas de corriente de más de 40 A.", "COTIDIANO", "aceleracion_modo_electrico_corte", "trepidacion_corte_al_acelerar_en_ev|bateria_hv_no_soporta_40a", "falla_motor_electrico", "", "NO", "SI", "Fallo en inversor de corriente IGBT o motor electrico (EV)", "L2 pack HV corta tracción por incapacidad de entregar 40A descarta motor.")

    # --- L3 (15 casos) ---
    agregar("G49-L3-01", CLASE_49, "L3", "Diagnóstico de batería de tracción NiMH de 201.6 V nominales (28 módulos de 7.2 V en serie) con software Techstream en vehículo híbrido: código de falla DTC P0A80 activo permanente. En prueba de esfuerzo en carretera bajo aceleración a plena carga en subida pronunciada el flujo de datos del BMS (Battery Smart Unit) revela un delta de tensión entre bloques (Delta Cell Block Voltage) de 1.85 V (bloque 6 cae a 13.12 V mientras el bloque 12 se mantiene en 14.97 V; especificación máxima tolerada menor a 0.25 V). La resistencia interna calculada del bloque 6 es de 0.052 ohmios (tres veces superior a la nominal). El ventilador de refrigeración opera sin obstrucciones a 3800 rpm descartando falla térmica.", "TECNICO", "techstream_p0a80_delta_bloques_1_85v", "dtc_p0a80|delta_bloques_1_85v_vs_0_25v|bloque_6_cae_a_13_12v|resistencia_0_052ohm|ventilador_ok", "falla_refrigeracion_bateria", "P0A80", "NO", "SI", "Foco o falla en sistema de refrigeracion de bateria/inversor (EV)", "L3 Techstream confirma P0A80 con delta de bloques de 1.85V y ventilador funcionando.")
    agregar("G49-L3-02", CLASE_49, "L3", "Evaluación de batería de iones de litio de 350 V (96 celdas prismáticas en serie) en vehículo eléctrico puro: State of Health (SOH) consolidado en 51.4% con capacidad útil restante de 18.2 kWh (capacidad nominal de fábrica 35.5 kWh). En ensayo de descarga en banco con carga activa a corriente constante de 1C (100 A) a 25°C tres de las celdas del módulo central colapsan por debajo del umbral de corte de seguridad de 2.75 V a los 9 minutos de prueba provocando apertura preventiva de los contactores pirotécnicos SMR. La batería auxiliar de 12 V se encuentra al 100% de carga (12.72 V) descartando fallo en red de baja tensión.", "TECNICO", "banco_descarga_1c_100a_soh_51_4porciento", "soh_51_4porciento_capacidad_18_2kwh|tres_celdas_colapsan_a_2_75v|apertura_smr|bateria_12v_ok", "falla_bateria_12v", "", "NO", "SI", "Bateria descargada o bornes sulfatados", "L3 banco de descarga 1C constata SOH en 51.4% con colapso de celdas a 2.75V.")
    agregar("G49-L3-03", CLASE_49, "L3", "Prueba de ciclado dinámico en banco con ciclador de alta tensión: paquete de batería híbrida presenta pérdida de capacidad coulombimétrica del 44% y resistencia interna de celda promedio de 38 miliohmios (nominal nueva 14 mohm). Durante el ensayo de recarga rápida a 50 kW la temperatura del núcleo de celdas se eleva a 52°C con solo 15 kW de potencia absorbida debido a disipación Joule por alta impedancia electroquímica interna, activando DTC P0A7F.", "TECNICO", "ciclador_banco_perdida_capacidad_44porciento", "dtc_p0a7f|perdida_capacidad_44porciento|resistencia_38mohm_vs_14mohm|temperatura_52c_a_15kw", "falla_refrigeracion_inversor", "P0A7F", "NO", "SI", "Foco o falla en sistema de refrigeracion de bateria/inversor (EV)", "L3 DTC P0A7F por pérdida del 44% de capacidad y resistencia interna de 38 mohm.")
    agregar("G49-L3-04", CLASE_49, "L3", "Hola maestro, tengo un Toyota Prius 2012. En la pantalla me salió el triángulo rojo y el mensaje de revisar sistema híbrido. En subida la barra de la batería se vacía en 20 segundos y el motor de gasolina ruge a 4000 rpm sin avanzar con fuerza. En el taller conectaron el escáner y el bloque de celdas número 11 tiene 12.1 V mientras los demás tienen 14.8 V; la batería de 12 V es nueva de gel y marca 12.8 V perfecta.", "WHATSAPP", "prius_triangulo_rojo_bloque_11_caido", "triangulo_rojo_revisar_hibrido|barra_bateria_vacia_20s|bloque_11_12_1v_vs_14_8v|bateria_12v_ok", "falla_bateria_12v", "", "NO", "SI", "Bateria descargada o bornes sulfatados", "L3 relato WhatsApp de Prius con bloque 11 en 12.1V vs 14.8V y batería 12V perfecta.")
    agregar("G49-L3-05", CLASE_49, "L3", "Medición de resistencia de aislamiento de pack de batería de tracción con megóhmetro de alta tensión Fluke a 1000 V DC: resistencia entre el terminal positivo de alta tensión (desconectado el disyuntor de servicio manual naranja) y la carcasa metálica de tierra chasis registra 0.12 Megaohmios (especificación mínima de seguridad según norma ISO 6469 debe superar 100 Megaohmios). La fuga de aislamiento proviene de electrolito alcalino de hidróxido de potasio fugado por la válvula de alivio de dos módulos NiMH corroídos.", "TECNICO", "megohmetro_fluke_1000v_aislamiento_0_12mohm", "aislamiento_0_12mohm_vs_100mohm_a_1000v|fuga_electrolito_koh_valvula_alivio|corrosion_modulos", "falla_aislamiento_inversor", "", "NO", "SI", "Fallo en inversor de corriente IGBT o motor electrico (EV)", "L3 megóhmetro a 1000V acusa 0.12 Mohm por fuga de electrolito en pack de tracción.")
    agregar("G49-L3-06", CLASE_49, "L3", "Diagnóstico de desequilibrio de celdas en vehículo híbrido enchufable PHEV: escáner registra DTC P0B3C (Hybrid Battery Voltage Sense Circuit Performance). En la gráfica de balanceo pasivo del BMS los circuitos equilibradores por resistencias shunt disipan energía de forma continua durante 6 horas sin lograr reducir la diferencia de tensión entre la celda 18 (3.42 V) y la celda 19 (4.15 V; delta de 730 mV) debido a microcortocircuito interno por dendritas de litio.", "TECNICO", "dtc_p0b3c_delta_730mv_dendritas", "dtc_p0b3c|delta_celdas_730mv|balanceo_pasivo_no_compensa|dendritas_litio_celda_18", "falla_inversor", "P0B3C", "NO", "SI", "Fallo en inversor de corriente IGBT o motor electrico (EV)", "L3 DTC P0B3C por delta de 730 mV entre celdas por dendritas de litio.")
    agregar("G49-L3-07", CLASE_49, "L3", "Mi carro electrico ase que la bateria baje del 80 porciento al 20 en menos de diez minutos de pista rapida. En el taller desarmaron la tapa del paquete de baterias y dos modulos tavan inchados con olor quimico penetrante y el escaner sacaba el codigo P0A80 de cambiar bateria grande. El motor electrico y el inversor no tienen ninguna falla.", "ERROR_ORTOGRAFICO", "descarga_80_a_20_modulos_hinchados", "descarga_80_a_20_en_10min|modulos_inchados_olor_quimico|dtc_p0a80|inversor_y_motor_ok", "falla_inversor_motor", "P0A80", "NO", "SI", "Fallo en inversor de corriente IGBT o motor electrico (EV)", "L3 módulos hinchados con P0A80 y descarte de inversor con ortografía informal.")
    agregar("G49-L3-08", CLASE_49, "L3", "Análisis de impedancia electroquímica (EIS) en módulo de batería LiFePO4: espectro de impedancia a frecuencias de 10 mHz a 10 kHz revela dispersión en el semicírculo de transferencia de carga con resistencia de polarización Rct incrementada en 450% respecto al valor canónico de fábrica, lo que impide al pack suministrar corrientes de aceleración superiores a 0.5C sin activar la protección BMS por subtensión transitoria.", "TECNICO", "espectroscopia_eis_rct_incrementada_450porciento", "espectro_eis_rct_incrementada_450porciento|polarizacion_electroquimica|corte_bms_a_0_5c", "falla_motor_traccion", "", "NO", "SI", "Fallo en inversor de corriente IGBT o motor electrico (EV)", "L3 espectroscopía EIS revela resistencia de transferencia de carga en +450%.")
    agregar("G49-L3-09", CLASE_49, "L3", "Evaluación de sensor de corriente de efecto Hall del paquete de batería HV (Battery Current Sensor): el escáner registra DTC P0A6B referente a circuito del sensor de corriente de batería de tracción; la lectura de corriente permanece fija en +18 A en reposo con contactores abiertos, provocando cálculo aberrante del State of Charge por integración de Coulomb en la ECU híbrida.", "TECNICO", "scanner_dtc_p0a6b_sensor_corriente_hall", "dtc_p0a6b|sensor_corriente_fijo_18a_en_reposo|calculo_soc_aberrante|contactores_abiertos", "falla_bateria_12v", "P0A6B", "NO", "SI", "Bateria descargada o bornes sulfatados", "L3 DTC P0A6B por sensor de corriente Hall de batería HV descalibrado.")
    agregar("G49-L3-10", CLASE_49, "L3", "Inspección de barra colectora de cobre (busbar) y tuercas de terminales de batería híbrida tras desmonte en entorno seguro con guantes dieléctricos Clase 0 (1000 V): corrosión galvánica severa de sulfato de cobre en 8 tuercas con resistencia de contacto de 0.85 ohmios en el puente entre módulo 14 y 15; esto induce una caída óhmica de 17.0 V al circular 20 A simulando caída de módulo en el BMS.", "TECNICO", "inspeccion_segura_busbars_corrosion_cobre", "resistencia_contacto_0_85ohm_busbar|caida_17_0v_a_20a|corrosion_galvanica_tuercas", "falla_cableado_12v", "", "NO", "SI", "Bateria descargada o bornes sulfatados", "L3 corrosión en busbars de pack HV induce 17V de caída de contacto.")
    agregar("G49-L3-11", CLASE_49, "L3", "Diagnóstico de fuga de tensión en bus de alta tensión con código DTC P0AA6 (Hybrid Battery Voltage System Isolation Fault) subcódigo INF 526: la unidad de detección de fugas (Leak Detection Circuit) mide una resistencia de aislamiento de 42 kOhm provocada por acumulación de humedad y polvo conductor sobre la bandeja portabaterías inferior sin que el inversor ni el motor presenten derivaciones.", "TECNICO", "dtc_p0aa6_inf_526_aislamiento_42kohm", "dtc_p0aa6_inf_526|aislamiento_42kohm|polvo_conductor_en_bandeja_pack|inversor_y_motor_ok", "falla_aislamiento_inversor", "P0AA6", "NO", "SI", "Fallo en inversor de corriente IGBT o motor electrico (EV)", "L3 DTC P0AA6 subcódigo 526 acusa 42 kOhm de aislamiento en pack HV.")
    agregar("G49-L3-12", CLASE_49, "L3", "Prueba de capacidad en descarga con analizador computarizado de 28 canales independientes en batería híbrida: 6 de los 28 módulos entregan una capacidad acumulada menor a 1800 mAh (especificación nominal 6500 mAh; pérdida de capacidad del 72%); los 22 módulos restantes promedian 4800 mAh, generando desbalance térmico y corte por baja tensión.", "TECNICO", "analizador_28_canales_capacidad_1800mah", "6_modulos_con_capacidad_1800mah_vs_6500mah|perdida_capacidad_72porciento|desbalance_termico", "falla_refrigeracion", "", "NO", "SI", "Foco o falla en sistema de refrigeracion de bateria/inversor (EV)", "L3 analizador de 28 canales constata 6 módulos con pérdida del 72% de capacidad.")
    agregar("G49-L3-13", CLASE_49, "L3", "Evaluación de módulo BMS esclavo (Cell Monitoring Unit / CMU) en batería de iones de litio de tracción: el circuito integrado de monitoreo multicanal presenta fallo en el convertidor analógico-digital (ADC) interno enviando lectura fija de 0.00 V en las celdas 33 a 40 con DTC P0B24; la verificación con multímetro de alta precisión en las celdas físicas constata 3.82 V reales y estables.", "TECNICO", "scanner_dtc_p0b24_falla_cmu_esclavo", "dtc_p0b24|cmu_envia_cero_voltios_celdas_33_a_40|multimetro_mide_3_82v_reales|falla_adc_bms", "falla_inversor", "P0B24", "NO", "SI", "Fallo en inversor de corriente IGBT o motor electrico (EV)", "L3 DTC P0B24 por fallo en ADC de placa CMU con celdas físicas sanas a 3.82V.")
    agregar("G49-L3-14", CLASE_49, "L3", "Prueba de esfuerzo con dinamómetro de chasis en vehículo EV: con 20% de SoC la aceleración máxima sostenida a 100 km/h provoca un colapso de tensión del pack completo de 380 V a 248 V (caída de 132 V) debido a degradación por envejecimiento de ciclo químico de las celdas, activando el modo de potencia reducida (icono de tortuga) a los 4 segundos.", "TECNICO", "dinamometro_colapso_tension_132v_tortuga", "pack_cae_380v_a_248v_caida_132v_a_20soc|modo_tortuga_a_los_4_segundos|envejecimiento_quimico", "falla_motor_electrico", "", "NO", "SI", "Fallo en inversor de corriente IGBT o motor electrico (EV)", "L3 dinamómetro acusa colapso de 132V a 20% SoC activando modo tortuga.")
    agregar("G49-L3-15", CLASE_49, "L3", "Sustitución de conjunto de batería de tracción tras fusión de fusible principal de servicio de 250 A / 450 V DC (Service Plug fuse): la apertura del fusible se produjo por sobrecorriente provocada por un cortocircuito interno entre electrodos positivos y negativos dentro del módulo 2 tras penetración de tornillo de fijación de accesorio no original.", "TALLER", "fusible_servicio_250a_fundido_corto_interno", "fusible_servicio_250a_450v_fundido|cortocircuito_interno_modulo_2|tornillo_perfora_modulo", "falla_inversor_igbt", "", "NO", "SI", "Fallo en inversor de corriente IGBT o motor electrico (EV)", "L3 fusible de servicio de 250A fundido por perforación y cortocircuito interno en módulo.")

    return casos
