"""
Generador de registros para Lote 08 de Fase 10 (SUSPENSION_CHASIS) - Parte 2.
Cubre exactamente 80 registros:
- Clase 45: Cremallera de direccion asistida con holgura o fuga (40 casos: 10 L1, 15 L2, 15 L3)
- Clase 46: Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura) (40 casos: 10 L1, 15 L2, 15 L3)
IDs: F10-L08-0121 a F10-L08-0200.
"""

from typing import List, Dict

CLASE_45 = "Cremallera de direccion asistida con holgura o fuga"
CLASE_46 = "Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)"
MACRO = "SUSPENSION_CHASIS"
FUENTE = "SINTETICO_IA"


def obtener_casos_45_46(offset: int = 121) -> List[Dict[str, str]]:
    casos = []
    idx = offset

    def agregar(id_grupo, clase, nivel, texto, lenguaje, condicion, presentes, negados, dtc, req_preg, es_cont, clase_cont, obs):
        nonlocal idx
        reg_id = f"F10-L08-{idx:04d}"
        casos.append({
            "id": reg_id,
            "id_grupo": id_grupo,
            "clase_objetivo": clase,
            "macro_sistema": MACRO,
            "nivel_informacion": nivel,
            "texto_usuario": texto,
            "tipo_lenguaje": lenguaje,
            "condicion_operacion": condicion,
            "sintomas_presentes": presentes,
            "sintomas_negados": negados,
            "dtc": dtc,
            "requiere_pregunta": req_preg,
            "es_contrastivo": es_cont,
            "clase_contrastiva": clase_cont,
            "fuente": FUENTE,
            "observaciones": obs
        })
        idx += 1

    # =========================================================================
    # CLASE 45: Cremallera de direccion asistida con holgura o fuga (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G45-L1-01", CLASE_45, "L1", "El timón tiene un juego muerto en el centro y se escucha un golpecito al moverlo.", "COTIDIANO", "timon_movimiento_parado", "juego_muerto_timon_golpecito", "", "", "SI", "NO", "", "L1 juego en volante y golpecito.")
    agregar("G45-L1-02", CLASE_45, "L1", "Hola, la dirección se puso pesadísima como si no tuviera asistencia y chilla al doblar.", "WHATSAPP", "direccion_pesada_chillido", "direccion_pesada_chilla_al_doblar", "", "", "SI", "NO", "", "L1 dirección dura con chillido.")
    agregar("G45-L1-03", CLASE_45, "L1", "Hay un charco de líquido rojizo aceitoso debajo del motor por la cremallera.", "COTIDIANO", "fuga_liquido_rojizo", "charco_liquido_rojizo_aceitoso", "", "", "SI", "NO", "", "L1 fuga de líquido rojizo.")
    agregar("G45-L1-04", CLASE_45, "L1", "Siento un trac-toc hueco en el volante cada vez que paso por un camino ripiado.", "COTIDIANO", "camino_ripiado_volante", "trac_toc_hueco_volante_ripiado", "", "", "SI", "NO", "", "L1 golpe hueco en volante en ripio.")
    agregar("G45-L1-05", CLASE_45, "L1", "En el tablero se prendió una luz con el dibujo de un volante y timón duro.", "TALLER", "testigo_eps_timon_duro", "luz_testigo_volante_timon_duro", "", "", "SI", "NO", "", "L1 testigo de volante con endurecimiento.")
    agregar("G45-L1-06", CLASE_45, "L1", "Buenas, al zigzaguear el timón con el auto detenido se siente una holgura metálica.", "WHATSAPP", "zigzagueo_en_parado", "holgura_metalica_zigzaguear_parado", "", "", "SI", "NO", "", "L1 holgura en zigzagueo detenido.")
    agregar("G45-L1-07", CLASE_45, "L1", "El auto se siente impreciso y flota en la dirección cuando voy derecho en pista.", "COTIDIANO", "flotacion_direccion_recta", "direccion_imprecisa_flota_en_recta", "", "", "SI", "NO", "", "L1 flotación e imprecisión direccional.")
    agregar("G45-L1-08", CLASE_45, "L1", "Ayuda bota aseite por los fuelles de la direccion hidraulica.", "ERROR_ORTOGRAFICO", "fuelles_bota_aceite", "bota_aseite_fuelles_direccion", "", "", "SI", "NO", "", "L1 fuga en fuelles con ortografía informal.")
    agregar("G45-L1-09", CLASE_45, "L1", "Cruje y se traba un poco la dirección al doblar cerrado para estacionar.", "COTIDIANO", "estacionar_traba_direccion", "cruje_se_traba_direccion_doblar", "", "", "SI", "NO", "", "L1 crujido y trabamiento leve al maniobrar.")
    agregar("G45-L1-10", CLASE_45, "L1", "Se escucha un zumbido como de licuadora cuando giro el volante hasta el tope.", "COTIDIANO", "giro_tope_volante", "zumbido_licuadora_volante_tope", "", "", "SI", "NO", "", "L1 zumbido de bomba en topes.")

    # --- L2 (15 casos) ---
    agregar("G45-L2-01", CLASE_45, "L2", "Fuga visible de líquido hidráulico ATF por los retenes laterales de la cremallera; los guardapolvos de goma están inflados y empapados de aceite rojo.", "TECNICO", "inspeccion_fuelles_empapados_atf", "fuga_atf_retenes_laterales_cremallera|guardapolvos_inflados_aceite", "falla_frenos", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L2 fuga de líquido ATF en cremallera descarta circuito de frenos.")
    agregar("G45-L2-02", CLASE_45, "L2", "Dirección electroasistida EPS con código DTC C1511 en módulo de dirección; presenta endurecimiento repentino al realizar giros rápidos a baja velocidad.", "TECNICO", "giros_baja_velocidad_c1511", "dtc_c1511|endurecimiento_repentino_eps|giros_rapidos_baja_velocidad", "falla_bomba_hidraulica", "C1511", "NO", "SI", "Amortiguadores reventados o bujes de suspension gastados", "L2 EPS con C1511 por sensor de par de dirección.")
    agregar("G45-L2-03", CLASE_45, "L2", "Golpeteo seco toc-toc al mover el volante rápidamente de izquierda a derecha con el vehículo detenido; el casquillo de teflón de la barra cremallera tiene holgura.", "TALLER", "movimiento_rapido_parado_casquillo", "toc_toc_volante_parado|holgura_casquillo_teflon_cremallera", "falla_homocinetica", "", "NO", "SI", "Juntas homocineticas o palieres danados", "L2 juego de casquillo en cremallera sin sonar en marcha.")
    agregar("G45-L2-04", CLASE_45, "L2", "Pérdida de nivel de líquido en el reservorio de dirección asistida hidráulica con chillido agudo de la bomba en topes; al frenar en recta no jala a ningún lado.", "COTIDIANO", "deposito_vacio_chillido_topes", "nivel_bajo_reservorio_direccion|chillido_bomba_topes", "desvio_frenado", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L2 depósito hidráulico bajo con chillido de bomba en topes.")
    agregar("G45-L2-05", CLASE_45, "L2", "Hola maestro, cuando paso por adoquines suena un golpeteo que repercute directo en el volante; los bujes de trapecio y rótulas están completamente nuevos.", "WHATSAPP", "adoquines_repercute_en_volante", "golpeteo_repercute_en_volante_adoquines", "falla_bujes_rotulas_nuevos", "", "NO", "SI", "Amortiguadores reventados o bujes de suspension gastados", "L2 golpeteo en volante con bujes de trapecio nuevos confirma cremallera.")
    agregar("G45-L2-06", CLASE_45, "L2", "Terminales axiales de dirección (bieletas interiores de cremallera) con holgura axial de 3 mm; el volante tiene juego libre de 20 grados antes de mover las ruedas.", "TALLER", "terminales_axiales_juego_20grados", "axiales_direccion_holgura_3mm|juego_libre_volante_20_grados", "falla_llanta", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L2 axiales interiores de cremallera con 3 mm de juego libre.")
    agregar("G45-L2-07", CLASE_45, "L2", "Dirección asistida eléctrica con DTC C1532 por sobrecorriente en el motorreductor EPS acoplado a la cremallera; se desactiva la asistencia tras 10 minutos de tráfico.", "TECNICO", "trafico_sobrecorriente_c1532", "dtc_c1532|sobrecorriente_motorreductor_eps|corte_asistencia_en_trafico", "falla_alternador", "C1532", "NO", "SI", "Alternador defectuoso o placa de diodos quemada", "L2 EPS con C1532 por sobrecalentamiento de motorreductor.")
    agregar("G45-L2-08", CLASE_45, "L2", "Fuga masiva de aceite por el retén superior del piñón de ataque de la cremallera; el fluido gotea sobre la cruceta de la columna de dirección en la cabina.", "TALLER", "reten_pinon_ataque_gotea_columna", "fuga_aceite_reten_pinon_cremallera|goteo_cruceta_cabina", "falla_embrague", "", "NO", "SI", "Falla en bombin o bomba hidraulica de embrague", "L2 retén de piñón de cremallera fuga sobre cruceta descarta bombín.")
    agregar("G45-L2-09", CLASE_45, "L2", "Al circular en línea recta por autopista se siente un punto duro en el centro de la cremallera que dificulta pequeñas correcciones de carril; no zumba en rodadura.", "COTIDIANO", "punto_duro_centro_autopista", "punto_duro_centro_cremallera|dificulta_correcciones", "zumbido_rodadura", "", "NO", "SI", "Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)", "L2 punto duro central en cremallera descarta rodamiento de maza.")
    agregar("G45-L2-10", CLASE_45, "L2", "Tornillo de ajuste de precarga del empujador de cremallera (yoke) flojo; la barra dentada golpea contra el cuerpo de aluminio al pasar baches pequeños.", "TECNICO", "yoke_precarga_flojo", "empujador_yoke_flojo|barra_cremallera_golpea_cuerpo", "falla_amortiguador", "", "NO", "SI", "Amortiguadores reventados o bujes de suspension gastados", "L2 yoke de precarga flojo genera golpeteo de barra cremallera.")
    agregar("G45-L2-11", CLASE_45, "L2", "Buenas tardes, al maniobrar en estacionamiento el timón de la dirección hidráulica se pone durísimo hacia el lado izquierdo pero hacia la derecha gira con suavidad; la cremallera tiene sellos internos gastados.", "WHATSAPP", "asistencia_asimetrica_izquierda_dura", "direccion_dura_hacia_la_izquierda_suave_derecha|sellos_internos_gastados", "falla_bomba", "", "NO", "NO", "", "L2 asistencia hidráulica asimétrica por fuga en anillo de pistón.")
    agregar("G45-L2-12", CLASE_45, "L2", "Cremallera electroasistida con deformación en los dientes centrales de la barra tras subir violentamente una vereda; la dirección salta y se traba en 0 grados.", "TALLER", "dientes_deformados_vereda", "dientes_cremallera_deformados|salto_trabamiento_en_centro", "falla_homocinetica", "", "NO", "SI", "Juntas homocineticas o palieres danados", "L2 dientes centrales deformados traban dirección en vereda.")
    agregar("G45-L2-13", CLASE_45, "L2", "Válvula rotativa distribuidora de la cremallera hidráulica comunicada internamente; al girar el timón a ralentí se escucha un silbido continuo y no asiste.", "TECNICO", "valvula_rotativa_comunicada", "valvula_rotativa_comunicada_silbido|perdida_asistencia_ralenti", "falla_frenos", "", "NO", "SI", "Falla en servofreno (booster) o linea de vacio", "L2 válvula rotativa de cremallera pierde presión por bypass interno.")
    agregar("G45-L2-14", CLASE_45, "L2", "Juego axial excesivo entre el piñón sinfín y la cremallera de dirección; en camino de calamina el timón vibra con chasquido metálico en cabina.", "COTIDIANO", "calamina_chasquido_timon", "juego_axial_pinon_cremallera|chasquido_metalico_en_calamina", "vibracion_carretera_alta_velocidad", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L2 holgura piñón-cremallera en calamina descarta desbalanceo.")
    agregar("G45-L2-15", CLASE_45, "L2", "Dirección hidráulica pierde todo el fluido Dexron III en menos de dos días; el fuelle derecho gotea continuamente sobre el trapecio de suspensión.", "COTIDIANO", "fuelle_derecho_gotea_dexron", "perdida_fluido_dexron_iii_dos_dias|goteo_fuelle_cremallera", "falla_aceite_motor", "", "NO", "SI", "Amortiguadores reventados o bujes de suspension gastados", "L2 fuga masiva de Dexron III en fuelle de dirección descarta amortiguador.")

    # --- L3 (15 casos) ---
    agregar("G45-L3-01", CLASE_45, "L3", "Diagnóstico de cremallera de dirección hidráulica en banco de presión: manómetro colocado en la línea de alta presión acusa caída de presión de trabajo de 105 bar nominales a 32 bar al solicitar tope de dirección hacia la izquierda. Al retirar los guardapolvos laterales de caucho se comprueba que el cilindro receptor interior almacena 350 ml de fluido hidráulico ATF Dexron III debido al desgaste por labio cuarteado del retén radial de teflón-NBR de 28 mm. La barra cremallera de acero rectificado presenta estrías superficiales de 0.15 mm que aceleran la pérdida.", "TECNICO", "banco_presion_cremallera_caida_32bar", "presion_cae_105_a_32bar_giro_izq|fuelle_lleno_350ml_atf|reten_labio_cuarteado_28mm|estrias_0_15mm", "falla_frenos", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L3 manómetro registra caída de 105 a 32 bar y 350 ml de ATF en fuelle.")
    agregar("G45-L3-02", CLASE_45, "L3", "Evaluación de dirección electroasistida (EPS) en columna/cremallera con escáner automotriz en vehículo Toyota Yaris: código DTC C1511 almacenado activo referente a sensor de torque de dirección (Torque Sensor 1 / Main Sensor). En flujo de datos en vivo con vehículo en línea recta el sensor registra un voltaje de 3.82 V (especificación central 2.50 V +/- 0.15 V) con un desfase de par de torsión calculado de 4.8 Nm hacia la derecha en reposo, induciendo asistencia involuntaria asimétrica y desconexión de seguridad del relé EPS con testigo de volante ámbar.", "TECNICO", "scanner_datos_en_vivo_c1511_3_82v", "dtc_c1511|sensor_torque_3_82v_vs_2_50v|desfase_par_4_8nm_reposo|desconexion_seguridad_eps", "falla_angulo_volante", "C1511", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L3 escáner acusa C1511 con sensor de torque a 3.82V desfasado 4.8 Nm.")
    agregar("G45-L3-03", CLASE_45, "L3", "Medición de holgura radial de barra cremallera con reloj comparador de carátula en fosa: al aplicar fuerza lateral de 200 N en la barra de salida del lado del copiloto se registra un desplazamiento radial de 1.85 mm (especificación máxima 0.20 mm) debido a fractura y desgaste abrasivo del casquillo guía de teflón-bronce. Al circular sobre adoquines a 25 km/h el golpeteo seco genera un nivel sonoro de 82 dBA en la columna de dirección que desaparece al transitar sobre asfalto liso a 100 km/h.", "TECNICO", "reloj_comparador_holgura_radial_1_85mm", "holgura_radial_barra_1_85mm_vs_0_20mm|casquillo_teflon_fracturado|golpeteo_adoquines_82dba|silencio_pista_lisa", "falla_bujes_suspension", "", "NO", "SI", "Amortiguadores reventados o bujes de suspension gastados", "L3 reloj comparador mide 1.85 mm de holgura radial en casquillo de cremallera.")
    agregar("G45-L3-04", CLASE_45, "L3", "Hola maestro, tengo un Nissan Sentra con dirección electroasistida. Cuando paso por pistas afirmadas o con huequitos suena un traqueteo seco adentro del timón como si la columna estuviera suelta. Las rótulas, bieletas y amortiguadores están nuevos de paquete y bien ajustados. En el taller desarmaron y encontraron que la cremallera de dirección tiene juego interno en el engranaje del piñón sinfín y golpetea en seco.", "WHATSAPP", "sentra_afirmado_juego_pinon_cremallera", "traqueteo_seco_en_timon_afirmado|suspension_nueva_ok|juego_interno_pinon_sinfin_cremallera", "falla_suspension_bujes", "", "NO", "SI", "Amortiguadores reventados o bujes de suspension gastados", "L3 relato WhatsApp de traqueteo en timón con suspensión nueva confirmando cremallera.")
    agregar("G45-L3-05", CLASE_45, "L3", "Verificación de servodirección electrohidráulica (EHPS): electrobomba hidráulica sumergida registra DTC C1521 referente a motor de bomba bloqueado térmicamente tras operar continuo a 135°C; la cremallera de dirección perdió el fluido sintético CHF 11S a través del retén izquierdo inundando el subchasis con 400 ml de lubricante y dejando el timón con 45 N de esfuerzo estático para girar.", "TECNICO", "ehps_electrobomba_c1521_135c", "dtc_c1521|electrobomba_135c_bloqueada|perdida_chf_11s_400ml_subchasis|esfuerzo_estatico_45n", "falla_bateria", "C1521", "NO", "SI", "Bateria descargada o bornes sulfatados", "L3 EHPS con C1521 y fuga de CHF 11S dejando timón en 45 N.")
    agregar("G45-L3-06", CLASE_45, "L3", "Desmontaje de cremallera mecánica de dirección en banco de ajuste: tornillo empujador de precarga (yoke guide) presenta resorte elástico fatigado con pérdida de 4 mm de altura libre (tensión residual nula); el juego entre flancos de dientes engranados entre piñón helicoidal y cremallera alcanza 0.45 mm (límite OEM 0.05 mm) generando crujidos y holgura de 18 grados en el aro del volante.", "TALLER", "desarme_banco_yoke_resorte_fatigado", "resorte_yoke_fatigado_menos_4mm|juego_flancos_dientes_0_45mm|holgura_volante_18_grados", "falla_homocinetica", "", "NO", "SI", "Juntas homocineticas o palieres danados", "L3 banco constata resorte de yoke fatigado y 0.45 mm de holgura en flancos.")
    agregar("G45-L3-07", CLASE_45, "L3", "Medición de concentricidad y juego axial en terminales interiores de dirección (axiales): el axial izquierdo presenta juego axial de 2.4 mm medido con micrómetro palpal en la articulación esférica roscada a la barra cremallera. Al circular en carretera a 90 km/h la rueda izquierda vibra lateralmente provocando flotación direccional continua; no se presentan ruidos de rodadura en curvas.", "TECNICO", "micrometro_axial_interior_2_4mm", "axial_interior_juego_2_4mm|flotacion_direccional_90kmh|sin_ruido_rodadura_curva", "falla_rodaje_maza", "", "NO", "SI", "Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)", "L3 axial interior con 2.4 mm de juego libre provoca flotación sin zumbido.")
    agregar("G45-L3-08", CLASE_45, "L3", "Mi carro ase un golpe seco y feo en el timon cuando paso por piedras sueltas. El mecanico le movio el timon en el taller con el carro apagao y suena un cloc cloc adentro de la cremallera de direccion y taba goteando aseite rojo en el piso de la cochera. Los amortiguadores tan secos y no botan nada.", "ERROR_ORTOGRAFICO", "piedras_cloc_cloc_gotea_aceite_rojo", "golpe_seco_en_timon_piedras|cloc_cloc_en_cremallera_parado|gotea_aseite_rojo|amortiguadores_secos", "falla_amortiguadores", "", "NO", "SI", "Amortiguadores reventados o bujes de suspension gastados", "L3 cloc cloc en cremallera con fuga de aceite rojo y ortografía informal.")
    agregar("G45-L3-09", CLASE_45, "L3", "Ensayo de estanqueidad neumática de carcasa de cremallera en banco: al aplicar 2.0 bar de presión de aire al circuito sellado se constata fuga instantánea a través del retén central del pistón hidráulico comunicando ambas cámaras de doble efecto; en el vehículo esto genera pérdida total de asistencia hidráulica hacia el giro derecho manteniendo asistencia forzada hacia la izquierda.", "TECNICO", "estanqueidad_neumatica_banco_2bar", "fuga_a_2_0bar_reten_piston_central|comunicacion_camaras_doble_efecto|asistencia_nula_hacia_derecha", "falla_bomba_direccion", "", "NO", "NO", "", "L3 ensayo a 2 bar acusa bypass en pistón de cremallera anulando asistencia derecha.")
    agregar("G45-L3-10", CLASE_45, "L3", "Inspección de cremallera asistida eléctrica de cremallera paralela (Belt-Drive EPS): la correa dentada sincrónica de transmisión entre el motor eléctrico y el husillo de bolas recirculantes se encuentra deshilachada con 8 dientes barridos; al solicitar giro rápido de volante se produce patinamiento con chirrido gomoso de 78 dBA y pérdida transitoria de servodirección sin fugas de fluidos.", "TALLER", "belt_drive_eps_correa_deshilachada", "correa_eps_deshilachada_8_dientes_barridos|chirrido_gomoso_patinamiento_78dba|sin_fugas_fluidos", "falla_correa_accesorios", "", "NO", "SI", "Amortiguadores reventados o bujes de suspension gastados", "L3 EPS belt-drive con correa deshilachada y dientes barridos sin fluidos.")
    agregar("G45-L3-11", CLASE_45, "L3", "Deformación por pandeo de la barra cremallera de acero cementado tras impacto lateral en rueda delantera izquierda: flexión permanente de 1.4 mm en los últimos 80 mm de carrera izquierda; al doblar a más de 30 grados de giro el piñón se acuña contra la barra trabando el timón e impidiendo el retorno automático a la posición recta.", "TECNICO", "barra_cremallera_pandeo_1_4mm", "pandeo_barra_cremallera_1_4mm|piñon_se_acuña_a_30_grados|traba_timon_sin_retorno_automatico", "falla_rotula_suspension", "", "NO", "SI", "Amortiguadores reventados o bujes de suspension gastados", "L3 barra cremallera con pandeo de 1.4 mm traba piñón e impide retorno.")
    agregar("G45-L3-12", CLASE_45, "L3", "Medición de temperatura con termómetro infrarrojo en válvula distribuidora rotativa de cremallera hidráulica: tras 15 minutos de funcionamiento continuo alcanza 118°C debido a restricción hidráulica y fricción por teflones de sello quemados (temperatura normal de circuito 70°C); el aceite ATF se encuentra emulsionado y degradado con presencia de finas partículas metálicas de aluminio.", "TECNICO", "termometria_valvula_rotativa_118c", "temperatura_valvula_118c_vs_70c|sellos_teflon_quemados|atf_emulsionado_aluminio", "falla_refrigeracion_motor", "", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L3 válvula rotativa de cremallera alcanza 118°C con teflones quemados.")
    agregar("G45-L3-13", CLASE_45, "L3", "Diagnóstico de cremallera EPS con escáner avanzado: DTC C1512 presente en unidad de control de dirección asistida; la señal de posición absoluta de la barra cremallera registra saltos de señal erráticos de hasta 90 grados en microsegundos debido a contaminación por polvo de grafito en el sensor magneto-resistivo interior, descalibrando el centrado activo de la dirección.", "TECNICO", "scanner_eps_c1512_sensor_posicion", "dtc_c1512|saltos_erraticos_sensor_posicion|polvo_grafito_sensor_magneto_resistivo", "falla_sensor_abs", "C1512", "NO", "SI", "Falla en sensor de velocidad de rueda ABS", "L3 escáner acusa C1512 por sensor de posición cremallera contaminado.")
    agregar("G45-L3-14", CLASE_45, "L3", "Sustitución de fuelles protectores de cremallera tras rotura: el agua salina de pista penetró en el interior de la cremallera oxidando los dientes de la barra de dirección con picaduras de corrosión de 0.8 mm de profundidad; al girar el volante se produce un tacto arenoso y áspero de engrane con resistencia variable cada cuarto de vuelta.", "TALLER", "corrosion_dientes_barra_cremallera_0_8mm", "dientes_cremallera_oxidados_picaduras_0_8mm|tacto_arenoso_aspero|resistencia_variable_cuarto_vuelta", "falla_rodaje_maza", "", "NO", "SI", "Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)", "L3 dientes de cremallera corroídos con picaduras de 0.8 mm dan tacto arenoso.")
    agregar("G45-L3-15", CLASE_45, "L3", "Comprobación dinamométrica de par de retorno de dirección: tras realizar viraje a 40 km/h y soltar el timón el vehículo no retorna a trayectoria recta quedando bloqueado en 15 grados de ángulo de rueda debido a ajuste excesivo del tornillo de empuje yoke que eliminó la holgura de diseño comprimiendo la barra contra el piñón con fricción de 18 Nm.", "TECNICO", "par_retorno_nulo_yoke_sobreapretado", "direccion_no_retorna_bloqueada_15_grados|yoke_sobreapretado_friccion_18nm|barra_apretada_contra_piñon", "falla_geometria_alineacion", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L3 tornillo yoke sobreapretado con 18 Nm de fricción anula retorno de timón.")

    # =========================================================================
    # CLASE 46: Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura) (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G46-L1-01", CLASE_46, "L1", "Se escucha un zumbido grave como un avión bimotor que aumenta con la velocidad del carro.", "COTIDIANO", "velocidad_creciente", "zumbido_grave_tipo_avion_bimotor", "", "", "SI", "NO", "", "L1 zumbido tipo avión que sube con velocidad.")
    agregar("G46-L1-02", CLASE_46, "L1", "Hola, la rueda delantera zumba fuertísimo cuando viajo en la carretera a partir de 60 km/h.", "WHATSAPP", "carretera_a_partir_60kmh", "rueda_delantera_zumba_desde_60kmh", "", "", "SI", "NO", "", "L1 zumbido de rueda a partir de 60 km/h.")
    agregar("G46-L1-03", CLASE_46, "L1", "Suena un bramido sordo constante en la llanta derecha cuando voy en línea recta.", "COTIDIANO", "recta_bramido_sordo", "bramido_sordo_constante_llanta_derecha", "", "", "SI", "NO", "", "L1 bramido constante en rueda derecha.")
    agregar("G46-L1-04", CLASE_46, "L1", "El zumbido cambia de sonido cuando doblo en las curvas de la carretera.", "COTIDIANO", "curvas_carretera_cambio_tono", "zumbido_cambia_de_sonido_en_curvas", "", "", "SI", "NO", "", "L1 zumbido cambia en curvas.")
    agregar("G46-L1-05", CLASE_46, "L1", "Tengo un ruido de fricción y rugosidad que gira parejo con las ruedas.", "TALLER", "rugosidad_con_giro_ruedas", "ruido_friccion_rugosidad_giro_ruedas", "", "", "SI", "NO", "", "L1 rugosidad que acompaña giro de ruedas.")
    agregar("G46-L1-06", CLASE_46, "L1", "Buenas, zumba como turbina en la parte de atrás a velocidad de crucero.", "WHATSAPP", "velocidad_crucero_trasero", "zumba_como_turbina_atras_crucero", "", "", "SI", "NO", "", "L1 zumbido tipo turbina en eje trasero.")
    agregar("G46-L1-07", CLASE_46, "L1", "El ruido no se apaga aunque ponga el cambio en neutro con el auto rodando.", "COTIDIANO", "neutro_rodando_ruido_sigue", "ruido_no_apaga_en_neutro_rodando", "", "", "SI", "NO", "", "L1 zumbido persiste en neutro.")
    agregar("G46-L1-08", CLASE_46, "L1", "Ase un sumbido orrible en la rueda que ase temblar el piso a 80.", "ERROR_ORTOGRAFICO", "velocidad_80_sumbido", "sumbido_orrible_rueda_tiembla_piso", "", "", "SI", "NO", "", "L1 zumbido con ortografía informal.")
    agregar("G46-L1-09", CLASE_46, "L1", "Al tocar la maza de la rueda delantera después de manejar quema caliente.", "COTIDIANO", "maza_caliente_al_tacto", "maza_rueda_quema_caliente", "", "", "SI", "NO", "", "L1 maza caliente tras manejar.")
    agregar("G46-L1-10", CLASE_46, "L1", "Se siente un ronroneo continuo en la cabina que se hace más agudo al acelerar en autopista.", "COTIDIANO", "ronroneo_agudo_autopista", "ronroneo_continuo_mas_agudo_velocidad", "", "", "SI", "NO", "", "L1 ronroneo que se agudiza con velocidad.")

    # --- L2 (15 casos) ---
    agregar("G46-L2-01", CLASE_46, "L2", "Zumbido sordo continuo en rueda delantera izquierda a partir de 60 km/h; al tomar curvas a la derecha el ruido se intensifica fuertemente por transferencia de peso y al doblar a la izquierda disminuye.", "COTIDIANO", "curva_derecha_intensifica_izquierda_calma", "zumbido_delantero_izquierdo_60kmh|intensifica_al_girar_derecha|disminuye_al_girar_izquierda", "falla_diferencial", "", "NO", "SI", "Rodajes de caja mecanica o diferencial gastados", "L2 zumbido que aumenta al cargar rueda en curva descarta diferencial.")
    agregar("G46-L2-02", CLASE_46, "L2", "Rodando a 90 km/h en autopista el zumbido de rodadura se mantiene exactamente idéntico al poner punto muerto o pisar el pedal de embrague; no varía con las RPM del motor.", "TECNICO", "90kmh_neutro_y_embrague_suelto", "zumbido_identico_en_neutro_90kmh|no_varia_con_rpm_motor", "falla_eje_primario", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L2 zumbido constante en neutro a 90 km/h descarta eje primario.")
    agregar("G46-L2-03", CLASE_46, "L2", "Rueda delantera derecha levantada en el aire: al girarla a mano apoyando los dedos en el resorte del amortiguador se transmite una vibración áspera y rugosa de rodamiento picado.", "TALLER", "rueda_en_el_aire_giro_manual", "giro_manual_rugoso_en_resorte|vibracion_aspera_rodaje_picado", "falla_homocinetica", "", "NO", "SI", "Juntas homocineticas o palieres danados", "L2 prueba manual en muelle con rueda levantada confirma rodamiento.")
    agregar("G46-L2-04", CLASE_46, "L2", "Bramido ensordecedor de rodadura en la parte trasera derecha entre 80 y 120 km/h; los neumáticos son completamente nuevos y balanceados con desgaste parejo.", "COTIDIANO", "80_120kmh_trasero_llantas_nuevas", "bramido_rodadura_trasero_derecho_80_120kmh", "neumaticos_nuevos_balanceados_desgaste_parejo", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L2 bramido trasero con neumáticos nuevos descarta desgaste de llantas.")
    agregar("G46-L2-05", CLASE_46, "L2", "Hola maestro, en carretera recta zumba horrible como turbina; al soltar el acelerador rodando en 5ta el zumbido sigue exactamente igual sin cambiar de tono.", "WHATSAPP", "soltar_acelerador_en_quinta", "zumbido_turbina_sigue_igual_al_soltar_gas", "cambio_de_tono_retencion", "", "NO", "SI", "Rodajes de caja mecanica o diferencial gastados", "L2 zumbido que no cambia al soltar gas descarta diferencial.")
    agregar("G46-L2-06", CLASE_46, "L2", "Rodamiento de maza con juego axial de 1.5 mm apreciable al sacudir la rueda a las 12 y las 6 en el elevador; no hay juego en rótulas ni en terminales de dirección.", "TALLER", "sacudida_12_y_6_elevador", "juego_axial_1_5mm_rueda_12_y_6", "juego_rotulas_terminales", "", "NO", "SI", "Amortiguadores reventados o bujes de suspension gastados", "L2 juego axial a las 12 y 6 sin juego en rótulas confirma maza.")
    agregar("G46-L2-07", CLASE_46, "L2", "Zumbido que no genera vibraciones oscilatorias en el volante; el timón no tiembla a 100 km/h pero el zumbido acústico no deja hablar en la cabina.", "COTIDIANO", "100kmh_sin_vibrar_volante", "zumbido_acustico_ensordecedor_cabina", "vibracion_en_volante_100kmh", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L2 zumbido ensordecedor sin vibración en volante descarta desbalanceo.")
    agregar("G46-L2-08", CLASE_46, "L2", "Al pisar suavemente el freno a 90 km/h el zumbido de rodadura no cambia de frecuencia ni vibra el pedal; descarta que provenga del disco de freno.", "TECNICO", "frenada_suave_90kmh", "zumbido_no_cambia_al_frenar_suave", "pulsaciones_pedal_freno", "", "NO", "SI", "Discos de freno alabeados o desgastados", "L2 zumbido sin cambio al frenar descarta disco de freno.")
    agregar("G46-L2-09", CLASE_46, "L2", "Maza de rueda trasera izquierda con pista interior gripada y decolorada por sobretemperatura tras 30 km de autopista; quema la mano al tocar el centro del aro.", "TALLER", "sobretemperatura_maza_trasera", "pista_gripada_decolorada_maza|quema_al_tacto_centro_aro", "falla_caliper_trabado", "", "NO", "SI", "Caliper de freno trabado o mordaza pegada (piston agarrotado)", "L2 maza trasera hirviendo con disco frío descarta caliper trabado.")
    agregar("G46-L2-10", CLASE_46, "L2", "Zumbido que aumenta al virar a la izquierda cargando peso sobre la rueda derecha; en curvas hacia la derecha el ruido desaparece casi por completo.", "COTIDIANO", "viraje_izquierda_carga_derecha", "zumbido_aumenta_curva_izquierda|desaparece_en_curva_derecha", "falla_cremallera", "", "NO", "SI", "Cremallera de direccion asistida con holgura o fuga", "L2 transferencia de carga lateral clásica confirma rodamiento derecho.")
    agregar("G46-L2-11", CLASE_46, "L2", "Buenas tardes, el carro hace un ronquido de rodadura desde los 50 km/h y va aumentando de tono hasta los 100; en ralentí detenido no suena absolutamente nada.", "WHATSAPP", "50_a_100kmh_vs_ralenti", "ronquido_rodadura_50_a_100kmh", "ruido_en_ralenti_detenido", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L2 ronquido dependiente de velocidad que calla detenido descarta primario.")
    agregar("G46-L2-12", CLASE_46, "L2", "Rodamiento de doble hilera de bolas con sello de caucho roto; la grasa lubricante se secó con presencia de óxido y polvo de asfalto en las pistas.", "TECNICO", "sello_caucho_roto_grasa_seca", "sello_roto_grasa_seca_oxido|pistas_picadas_doble_hilera", "falla_homocinetica", "", "NO", "SI", "Juntas homocineticas o palieres danados", "L2 rodamiento de doble hilera con sello roto y pistas picadas.")
    agregar("G46-L2-13", CLASE_46, "L2", "Ruido de rodadura sordo que no cambia si acelero a fondo o si quito el pie del gas en 4ta marcha a 80 km/h; en curva amplia a la derecha se duplica.", "COTIDIANO", "aceleracion_vs_retencion_80kmh", "ruido_sordo_constante_acelerando_o_soltando|duplica_curva_derecha", "cambio_de_tono_gas", "", "NO", "SI", "Rodajes de caja mecanica o diferencial gastados", "L2 ruido insensible a torque de acelerador descarta diferencial.")
    agregar("G46-L2-14", CLASE_46, "L2", "Sensor de velocidad ABS registra código C0035 por deformación y salto de la pista magnética integrada en el sello del rodamiento de maza delantero izquierdo picado.", "TECNICO", "dtc_c0035_pista_magnetica_rodamiento", "dtc_c0035|pista_magnetica_encoder_deformada|rodamiento_picado", "falla_modulo_abs", "C0035", "NO", "SI", "Falla en sensor de velocidad de rueda ABS", "L2 rodamiento picado con DTC C0035 por daño en encoder magnético.")
    agregar("G46-L2-15", CLASE_46, "L2", "Zumbido como de rodaje seco que comienza suave a 40 km/h y a 90 km/h tapa el sonido de la radio; al levantar la rueda y hacerla girar se siente el áspero.", "COTIDIANO", "40_a_90kmh_tapa_radio", "zumbido_40_a_90kmh_tapa_radio|giro_rueda_levantada_aspero", "vibracion_volante", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L2 zumbido progresivo que tapa la radio sin vibrar timón.")

    # --- L3 (15 casos) ---
    agregar("G46-L3-01", CLASE_46, "L3", "Análisis acústico con sonómetro integrador de precisión y FFT: en línea recta sobre asfalto liso a 80 km/h el habitáculo registra 78 dBA con pico de resonancia centrado en 385 Hz; al realizar un suave cambio de carril hacia la derecha (transfiriendo carga dinámica hacia el semieje y rueda delantera izquierda) el nivel sonoro asciende inmediatamente a 87 dBA (+9 dBA); al girar suavemente hacia la izquierda (descargando la rueda izquierda) el nivel sonoro decae drásticamente a 61 dBA. Se engranó neutro a 80 km/h con motor en ralentí manteniéndose el patrón sonoro inalterado descartando transmisión.", "TECNICO", "analisis_acustico_sonometro_fft_385hz", "resonancia_385hz_a_80kmh|sube_a_87dba_giro_derecha|cae_a_61dba_giro_izquierda|patron_identico_en_neutro", "falla_diferencial", "", "NO", "SI", "Rodajes de caja mecanica o diferencial gastados", "L3 sonometría FFT registra 385 Hz con +9 dBA en curva derecha y calma en neutro.")
    agregar("G46-L3-02", CLASE_46, "L3", "Desmontaje y metrología de conjunto de rodamiento de maza de 3ra generación (buje integrado con sensor ABS magnético): al desmontar el cubo de rueda se constata que la pista de rodadura exterior de acero templado al cromo presenta picaduras por fatiga de contacto (spalling) con cráteres de 0.6 mm de profundidad en el arco superior de carga de 120 grados. Cuatro de las 14 bolas de acero presentan microgripado y faceteado plano. La holgura axial en el comparador de carátula mide 0.32 mm (especificación máxima 0.05 mm).", "TECNICO", "metrologia_desarme_spalling_0_6mm", "spalling_crateres_0_6mm_pista_exterior|4_bolas_con_microgripado|holgura_axial_0_32mm_vs_0_05mm", "falla_homocinetica", "", "NO", "SI", "Juntas homocineticas o palieres danados", "L3 metrología constata spalling de 0.6 mm y holgura axial de 0.32 mm en maza.")
    agregar("G46-L3-03", CLASE_46, "L3", "Medición de temperatura superficial con pirómetro infrarrojo de doble láser tras 40 km de recorrido en carretera a 90 km/h: la maza de rueda delantera derecha registra 78°C en el centro del cubo metálico, mientras que la maza izquierda se mantiene en 36°C (delta térmico de +42°C). Los discos de freno de ambos lados se midieron en 44°C descartando mordaza o pastilla pegada; la rotación manual en banco muestra rugosidad estática de 1.8 Nm.", "TECNICO", "pirometria_delta_termico_mas_42c", "maza_derecha_78c_vs_izquierda_36c|delta_termico_42c|discos_freno_frios_44c|rugosidad_1_8nm", "falla_caliper_pegado", "", "NO", "SI", "Caliper de freno trabado o mordaza pegada (piston agarrotado)", "L3 pirómetro registra maza a 78°C con disco frío en 44°C descartando caliper pegado.")
    agregar("G46-L3-04", CLASE_46, "L3", "Hola maestro, tengo un Hyundai Elantra. En carretera a partir de 70 km/h empieza un zumbido sordo como si fuera un avión que aumenta con la velocidad. Si piso el pedal de embrague a fondo a 90 km/h el ruido sigue exactamente idéntico. En las curvas hacia la izquierda el ruido casi desaparece, pero si doblo hacia la derecha se escucha fuertísimo en la llanta delantera izquierda. En la llantería levantaron la rueda y al girarla a mano se siente áspero.", "WHATSAPP", "elantra_70kmh_embrague_al_fondo", "zumbido_tipo_avion_desde_70kmh|embrague_a_fondo_ruido_sigue|desaparece_curva_izq_sube_der|giro_manual_aspero", "falla_eje_primario_caja", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L3 relato WhatsApp de zumbido insensible a embrague que cambia en curvas.")
    agregar("G46-L3-05", CLASE_46, "L3", "Evaluación vibratoria con acelerómetro piezoeléctrico colocado en la maza delantera izquierda: a 100 km/h la señal temporal muestra una aceleración pico de 5.4 m/s2 con componente de frecuencia BPFO (Ball Pass Frequency Outer Race) en 212 Hz correspondiente exactamente a la cinemática del rodamiento según número de bolas y diámetro primitivo. No se observa vibración a 1X de rueda (13.8 Hz) descartando desbalanceo de neumáticos.", "TECNICO", "acelerometria_bpfo_212hz_vs_13_8hz", "frecuencia_bpfo_212hz_aceleracion_5_4ms2|ausencia_frecuencia_1x_13_8hz", "desbalanceo_neumaticos", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L3 acelerometría calcula frecuencia BPFO en 212 Hz descartando 1X de llantas.")
    agregar("G46-L3-06", CLASE_46, "L3", "Comprobación en elevador de 2 columnas de rueda trasera derecha en vehículo AWD: con transmisión desacoplada se acciona el giro de la rueda a 60 km/h mediante rodillo girador eléctrico portátil: estetoscopio de taller colocado en la mangueta trasera detecta zumbido armónico de 86 dBA concentrado en el rodamiento; al apoyar el estetoscopio en la carcasa del diferencial trasero el nivel sonoro se reduce a 48 dBA confirmando daño en maza y no en grupo diferencial.", "TALLER", "rodillo_girador_60kmh_estetoscopio", "rodillo_60kmh_maza_86dba_vs_diferencial_48dba|transmision_desacoplada|estetoscopio_en_mangueta", "falla_diferencial_trasero", "", "NO", "SI", "Rodajes de caja mecanica o diferencial gastados", "L3 rodillo girador discrimina maza trasera (86 dBA) vs diferencial (48 dBA).")
    agregar("G46-L3-07", CLASE_46, "L3", "Mi carro ase un sumbido como turbina que empiesa a sonar en la carretera pasando los 60 y a 100 ya no se puede conversar adentro. El mecanico levanto el carro en la gata y movio la rueda arriba y abajo y taba con juego y al aserla rodar con la mano vibraba feo el resorte. El timon no tiembla nada de nada.", "ERROR_ORTOGRAFICO", "sumbido_turbina_60_a_100_resorte", "sumbido_turbina_60_a_100|juego_arriba_y_abajo_gata|resorte_vibra_al_rodar_mano", "vibracion_timon", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L3 zumbido con vibración en muelle al girar a mano con ortografía informal.")
    agregar("G46-L3-08", CLASE_46, "L3", "Diagnóstico de rodamiento cónico doble en eje rígido trasero: tuerca de precarga de maza se aflojó perdiendo el par de apriete especificado de 240 Nm (encontrada a 45 Nm con chaveta partida); el rodamiento de rodillos cónicos presenta juego axial de 1.1 mm con rodillos marcados por recalentamiento y grasa carbonizada negra; emite aullido áspero continuo a partir de 45 km/h.", "TECNICO", "rodamiento_conico_precarga_45nm_vs_240nm", "precarga_tuerca_45nm_vs_240nm|juego_axial_1_1mm|rodillos_conicos_recalentados|aullido_desde_45kmh", "falla_palier_trasero", "", "NO", "SI", "Juntas homocineticas o palieres danados", "L3 tuerca de maza a 45 Nm aflojada con 1.1 mm de juego en rodillos cónicos.")
    agregar("G46-L3-09", CLASE_46, "L3", "Prueba de rugosidad superficial con rugosímetro de taller en pista de rodamiento reemplazado: rugosidad Ra de 2.85 micrómetros en la pista interna (especificación original de rectificado Ra menor a 0.15 um) provocada por ingreso de agua a través del retén de maza en vadeo de río; genera ruido de rodadura constante tipo molienda metálica independientemente del estado del pavimento.", "TECNICO", "rugosimetro_ra_2_85um_vs_0_15um", "rugosidad_ra_2_85um_vs_0_15um|agua_en_reten_vadeo|molienda_metalica_constante", "falla_amortiguadores", "", "NO", "SI", "Amortiguadores reventados o bujes de suspension gastados", "L3 rugosímetro registra Ra 2.85 um en pista dañada por ingreso de agua.")
    agregar("G46-L3-10", CLASE_46, "L3", "Código de falla ABS DTC C0040 almacenado en memoria del calculador de frenos en rueda delantera derecha: flujo de datos del sensor de velocidad indica lectura oscilante errática a 80 km/h provocada por salto lateral y descentramiento de 0.28 mm en el rodamiento de maza picado que separa intermitentemente el anillo fónico magnético del sensor activo Hall.", "TECNICO", "dtc_c0040_descentramiento_0_28mm", "dtc_c0040|descentramiento_maza_0_28mm|anillo_fonico_se_desalinea|lectura_velocidad_erratica", "falla_sensor_abs_puro", "C0040", "NO", "SI", "Falla en sensor de velocidad de rueda ABS", "L3 DTC C0040 por holgura de 0.28 mm en maza que desacopla anillo fónico.")
    agregar("G46-L3-11", CLASE_46, "L3", "Inspección de par de resistencia al giro con torquímetro dinamométrico en maza delantera izquierda desmontada de pastillas de freno: par resistente de 4.2 Nm con saltos rugosos cada 45 grados (especificación par continuo menor a 0.6 Nm sin retención); se desmonta el conjunto constatando fractura de la jaula separadora de bolas de poliamida reforzada.", "TECNICO", "torquimetro_resistencia_giro_4_2nm", "par_resistente_4_2nm_vs_0_6nm|saltos_rugosos_cada_45_grados|jaula_poliamida_fracturada", "falla_caliper_pegado", "", "NO", "SI", "Caliper de freno trabado o mordaza pegada (piston agarrotado)", "L3 torquímetro acusa par de 4.2 Nm con saltos por jaula de bolas rota.")
    agregar("G46-L3-12", CLASE_46, "L3", "Vehículo presenta zumbido ensordecedor a 90 km/h que el conductor atribuía a la caja de cambios. Se colocaron 6 micrófonos inalámbricos en bancada de chasis: el canal en la mangueta delantera derecha registró 89 dBA a 90 km/h mientras el canal sobre la carcasa del diferencial registró 52 dBA; al presionar el embrague a 90 km/h en neutro el canal de mangueta mantuvo 89 dBA confirmando rodaje de rueda.", "TALLER", "microfonos_chasis_mangueta_89dba_vs_caja_52dba", "mangueta_89dba_vs_diferencial_52dba|embrague_a_fondo_mantiene_89dba|zumbido_rodadura", "falla_caja_cambios", "", "NO", "SI", "Rodajes de caja mecanica o diferencial gastados", "L3 micrófonos inalámbricos confirman 89 dBA en mangueta vs 52 dBA en diferencial.")
    agregar("G46-L3-13", CLASE_46, "L3", "Desgaste por corriente galvánica (fluting) en rodamiento de maza de vehículo híbrido/eléctrico: la pista de rodadura presenta estrías transversales paralelas microscópicas espaciadas a 0.5 mm por paso de corriente parásita a tierra; genera un zumbido electromecánico de alta frecuencia de 680 Hz a 100 km/h con rotor en rueda libre.", "TECNICO", "fluting_estrias_corriente_galvanica_680hz", "estrias_fluting_corriente_parásita|zumbido_680hz_a_100kmh|rotor_en_rueda_libre", "falla_inversor_electrico", "", "NO", "SI", "Fallo en inversor de corriente IGBT o motor electrico (EV)", "L3 fluting por corriente parásita genera zumbido a 680 Hz en rodamiento.")
    agregar("G46-L3-14", CLASE_46, "L3", "Medición de alabeo de maza con disco desmontado: la pestaña de apoyo de la maza de rueda presenta un salto axial de 0.16 mm (máximo tolerado 0.03 mm) debido a choque lateral contra sardinel; induce vibración de rodadura y roce rítmico continuo contra el guardapolvo de chapa sin que exista daño en el caliper ni en pastillas.", "TALLER", "salto_axial_pestana_maza_0_16mm", "salto_axial_maza_0_16mm_vs_0_03mm|roce_ritmico_guardapolvo_chapa", "falla_pastillas_freno", "", "NO", "SI", "Desgaste de pastillas y zapatas de freno", "L3 salto axial de 0.16 mm en pestaña de maza tras choque con sardinel.")
    agregar("G46-L3-15", CLASE_46, "L3", "Análisis con cámara termográfica Fluke tras prueba de carretera a 100 km/h durante 25 minutos: la maza de rueda delantera izquierda registra 86.4°C concentrada en el cuerpo del cojinete con emisividad calibrada en 0.95; la maza derecha registra 41.2°C; los neumáticos registran temperatura uniforme de 42°C en banda de rodadura descartando mala alineación o baja presión.", "TECNICO", "termografia_fluke_86_4c_vs_41_2c", "temperatura_maza_86_4c_vs_41_2c|cuerpo_cojinete_caliente|neumaticos_uniformes_42c", "falla_alineacion_neumaticos", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L3 termografía Fluke confirma maza a 86.4°C con neumáticos uniformes a 42°C.")

    return casos
