"""
Casos de entrenamiento para Fase 10 Lote 07 (TRANSMISIÓN - Parte 1):
- Clase 34: Disco de embrague desgastado o patinando (40 casos: 10 L1, 15 L2, 15 L3)
- Clase 35: Falla en bombin o bomba hidraulica de embrague (40 casos: 10 L1, 15 L2, 15 L3)
- Clase 36: Falta o degradacion de aceite de caja de cambios (40 casos: 10 L1, 15 L2, 15 L3)
- Clase 37: Rodajes de caja mecanica o diferencial gastados (40 casos: 10 L1, 15 L2, 15 L3)

Total: 160 registros (IDs F10-L07-0001 a F10-L07-0160).
"""

CLASE_34 = "Disco de embrague desgastado o patinando"
CLASE_35 = "Falla en bombin o bomba hidraulica de embrague"
CLASE_36 = "Falta o degradacion de aceite de caja de cambios"
CLASE_37 = "Rodajes de caja mecanica o diferencial gastados"


def obtener_casos_34_37(offset=1):
    casos = []
    idx = offset

    def agregar(id_grupo, clase, nivel, texto, tipo_lenguaje, cond, sint_pres, sint_neg, dtc, req_preg, es_cont, cl_cont, obs):
        nonlocal idx
        reg_id = f"F10-L07-{idx:04d}"
        idx += 1
        casos.append({
            "id": reg_id,
            "id_grupo": id_grupo,
            "clase_objetivo": clase,
            "macro_sistema": "TRANSMISION",
            "nivel_informacion": nivel,
            "texto_usuario": texto.strip(),
            "tipo_lenguaje": tipo_lenguaje,
            "condicion_operacion": cond.strip(),
            "sintomas_presentes": sint_pres.strip(),
            "sintomas_negados": sint_neg.strip(),
            "dtc": dtc.strip(),
            "requiere_pregunta": req_preg.strip(),
            "es_contrastivo": es_cont.strip(),
            "clase_contrastiva": cl_cont.strip(),
            "fuente": "SINTETICO_IA",
            "observaciones": obs.strip()
        })

    # =========================================================================
    # CLASE 34: Disco de embrague desgastado o patinando (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G34-L1-01", CLASE_34, "L1", "Acelero y el motor ruge fuerte pero el carro casi no avanza.", "COTIDIANO", "aceleracion", "motor_ruge_sin_avance", "", "", "SI", "NO", "", "L1 patinamiento clásico de embrague.")
    agregar("G34-L1-02", CLASE_34, "L1", "Hola, siento un olor a quemado feo cuando intento subir una cuesta.", "WHATSAPP", "subida", "olor_quemado_en_cuesta", "", "", "SI", "NO", "", "L1 olor a ferodo en subida.")
    agregar("G34-L1-03", CLASE_34, "L1", "El pedal de embrague corta muy arriba, casi al soltarlo del todo.", "COTIDIANO", "salida_parado", "corte_embrague_muy_alto", "", "", "SI", "NO", "", "L1 punto de acople en el extremo superior.")
    agregar("G34-L1-04", CLASE_34, "L1", "En tercera piso a fondo y las revoluciones suben de golpe sin fuerza.", "TALLER", "marcha_tercera", "rpm_suben_sin_fuerza", "", "", "SI", "NO", "", "L1 pérdida de tracción bajo demanda de par.")
    agregar("G34-L1-05", CLASE_34, "L1", "Pérdida de acoplamiento por fricción entre volante de inercia y plato opresor.", "TECNICO", "diagnostico", "perdida_acoplamiento_friccion", "", "", "SI", "NO", "", "L1 reporte técnico de deslizamiento.")
    agregar("G34-L1-06", CLASE_34, "L1", "El carro se queda como en neutro si le exijo velocidad en carretera.", "COTIDIANO", "carretera", "sensacion_neutro_al_acelerar", "", "", "SI", "NO", "", "L1 patinamiento a velocidad crucero.")
    agregar("G34-L1-07", CLASE_34, "L1", "Siento que el embrague resbala cuando llevo pasajeros en el auto.", "COTIDIANO", "carga_pasajeros", "embrague_resbala_con_carga", "", "", "SI", "NO", "", "L1 patinamiento evidente con carga.")
    agregar("G34-L1-08", CLASE_34, "L1", "Mi carro acelera y la aguja de RPM se dispara pero el carro no corre nada.", "ERROR_ORTOGRAFICO", "aceleracion", "rpm_se_disparan_sin_avance", "", "", "SI", "NO", "", "L1 desacople con ortografía informal.")
    agregar("G34-L1-09", CLASE_34, "L1", "Buenas, al salir en primera tiembla y huele a frenos quemados en la cabina.", "WHATSAPP", "salida_primera", "tiembla_al_salir|olor_quemado_cabina", "", "", "SI", "NO", "", "L1 trepidación y recalentamiento de ferodo.")
    agregar("G34-L1-10", CLASE_34, "L1", "Deslizamiento angular relativo superior al 20% bajo carga motriz plena.", "TECNICO", "plena_carga", "deslizamiento_angular_relativo", "", "", "SI", "NO", "", "L1 reporte técnico de resbalamiento cinemático.")

    # --- L2 (15 casos) ---
    agregar("G34-L2-01", CLASE_34, "L2", "En cuarta velocidad a 60 km/h piso a fondo el acelerador; las RPM suben de 2000 a 4500 al instante pero la velocidad sube muy lentamente sin empuje.", "COTIDIANO", "aceleracion_cuarta_60kmh", "rpm_suben_2000_a_4500|velocidad_no_aumenta", "ruido_caja_cambios", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L2 patinamiento evidente en marcha larga descarta rodamientos.")
    agregar("G34-L2-02", CLASE_34, "L2", "Olor penetrante a asbesto o ferodo quemado tras intentar subir una rampa de cochera empinada; el motor aceleró a 3500 rpm y el auto no pudo trepar.", "TALLER", "rampa_cochera", "olor_ferodo_quemado|motor_3500rpm_sin_trepar", "falla_bombin_embrague", "", "NO", "SI", "Falla en bombin o bomba hidraulica de embrague", "L2 ferodo quemado por patinamiento descarta bombín pegado.")
    agregar("G34-L2-03", CLASE_34, "L2", "El punto de contacto del embrague se desplazó al extremo superior del recorrido; al soltar el pedal apenas 1 cm el vehículo ya está completamente acoplado.", "TECNICO", "prueba_estatica_recorrido", "punto_acople_extremo_superior|recorrido_util_1cm", "falla_crapodina", "", "NO", "SI", "Desgaste en collarin de empuje o crapodina de embrague", "L2 desgaste de forro desplaza diafragma hacia afuera.")
    agregar("G34-L2-04", CLASE_34, "L2", "Hola, al meter los cambios entran suaves y sin rascar, pero al soltar el embrague y acelerar en subida el carro se queda amarrado y patina.", "WHATSAPP", "subida_cambios_suaves", "cambios_entran_suaves|patina_en_subida", "dificultad_engrane", "", "NO", "SI", "Falla en bombin o bomba hidraulica de embrague", "L2 cambios entran suaves descarta falla hidráulica de embrague.")
    agregar("G34-L2-05", CLASE_34, "L2", "Prueba de calado en taller: con freno de mano puesto y en tercera velocidad se suelta el embrague acelerando a 1500 rpm; el motor no se apaga y patina.", "TECNICO", "prueba_calado_tercera", "prueba_calado_motor_no_apaga|patinamiento_estatico", "falla_freno_mano", "", "NO", "NO", "", "L2 prueba clásica de calado en 3ra confirma disco gastado.")
    agregar("G34-L2-06", CLASE_34, "L2", "Trepidación fuerte de la carrocería al iniciar la marcha en primera velocidad acompañado de olor a disco recalentado; no hay ruidos con el pedal a fondo.", "COTIDIANO", "arranque_primera", "trepidacion_carroceria_salida|olor_disco_caliente", "ruido_collarin", "", "NO", "SI", "Desgaste en collarin de empuje o crapodina de embrague", "L2 trepidación sin ruido al pisar descarta collarín.")
    agregar("G34-L2-07", CLASE_34, "L2", "Retén de bancada del cigüeñal con fuga de aceite que contaminó la cara de fricción del disco; el embrague patina intermitentemente y vibra al desacoplar.", "TALLER", "inspeccion_fuga_reten", "disco_contaminado_aceite_motor|patina_intermitente", "falla_caja_cambios", "", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L2 contaminación por aceite de motor en disco de fricción.")
    agregar("G34-L2-08", CLASE_34, "L2", "Mi auto en subida acelera a fondo y el motor grita pero la velocidad no pasa de 30 km/h y huele a quemado como frenos.", "ERROR_ORTOGRAFICO", "subida_fuerte", "motor_grita_sin_avance_30kmh|olor_quemado", "falla_motor", "", "NO", "NO", "", "L2 patinamiento en pendiente con ortografía informal.")
    agregar("G34-L2-09", CLASE_34, "L2", "Buenas maestro, en plano corre normal pero si lo cargo con 4 personas y maletas en la carretera empieza a patinar en quinta velocidad al acelerar.", "WHATSAPP", "carretera_plena_carga", "patina_en_quinta_con_carga|en_plano_normal", "falla_transmision", "", "NO", "NO", "", "L2 patinamiento inducido por carga en marcha alta.")
    agregar("G34-L2-10", CLASE_34, "L2", "Espesor del disco de embrague al límite: forro de fricción desgastado hasta las cabezas de los remaches de cobre; produce un leve raspado al acoplar.", "TECNICO", "desarme_embrague", "forro_desgastado_al_remache|raspado_al_acoplar", "falla_rodaje_primario", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L2 remaches rozando prensa sin afectación de rodamientos.")
    agregar("G34-L2-11", CLASE_34, "L2", "Patinamiento de embrague tras reprogramación de potencia (Stage 1); el par del motor supera la capacidad de apriete del diafragma de prensa original gastada.", "COTIDIANO", "aceleracion_post_repro", "patinamiento_exceso_par|prensa_original_debilitada", "falla_turbo", "", "NO", "NO", "", "L2 déficit de par de sujeción en prensa desgastada.")
    agregar("G34-L2-12", CLASE_34, "L2", "Resortes de amortiguación torsional del disco de embrague rotos y con juego excesivo; provocan sacudidas bruscas al soltar el pedal y patinamiento en alta.", "TALLER", "inspeccion_disco_torsional", "resortes_torsionales_rotos_juego|sacudidas_patinamiento", "falla_soportes_motor", "", "NO", "NO", "", "L2 rotura de muelles amortiguadores del disco.")
    agregar("G34-L2-13", CLASE_34, "L2", "Al pisar el embrague el pedal se siente suave y desacopla perfecto sin ruidos extraños, pero al acelerar en adelantamiento patina de 80 a 100 km/h.", "COTIDIANO", "adelantamiento_autopista", "desacopla_suave_sin_ruidos|patina_adelantamiento_80_100", "ruido_crapodina", "", "NO", "SI", "Desgaste en collarin de empuje o crapodina de embrague", "L2 pedal suave y sin ruido descarta crapodina.")
    agregar("G34-L2-14", CLASE_34, "L2", "Diafragma de la prensa de embrague con dedos de empuje desgastados y azulados por fatiga térmica; no ejerce la fuerza de apriete nominal sobre el disco.", "TECNICO", "inspeccion_plato_opresor", "dedos_diafragma_azulados_desgastados|fuerza_apriete_baja", "falla_bomba_hidraulica", "", "NO", "SI", "Falla en bombin o bomba hidraulica de embrague", "L2 dedos de diafragma fatigados reducen presión de contacto.")
    agregar("G34-L2-15", CLASE_34, "L2", "En autopista a 100 km/h constante el tacómetro marca 4200 rpm cuando normalmente marcaba 2800 rpm en quinta marcha debido a deslizamiento continuo.", "TALLER", "velocidad_crucero_autopista", "4200rpm_vs_2800rpm_a_100kmh|deslizamiento_continuo_quinta", "falla_sensor_velocidad", "", "NO", "NO", "", "L2 discrepancia de 1400 rpm en crucero por patinamiento.")

    # --- L3 (15 casos) ---
    agregar("G34-L3-01", CLASE_34, "L3", "Toyota Yaris con 135,000 km presenta patinamiento evidente en tercera y cuarta marcha. Al circular a 50 km/h en 4ta marcha y presionar el acelerador al 100%, el régimen del motor trepa inmediatamente de 1800 rpm a 4200 rpm en 1.5 segundos mientras la velocidad vehicular solo incrementa de 50 a 54 km/h, despidiendo fuerte olor a material de fricción en la cabina. El pedal de embrague no tiene juego libre y corta en el 95% del recorrido superior. Se desmontó la transmisión encontrando el disco de embrague con espesor residual de 5.8 mm (mínimo OEM 6.6 mm) y remaches expuestos rayando la pista del volante bimasa.", "TALLER", "prueba_cuarta_fondo_desarme", "rpm_suben_1800_a_4200_en_1_5s|velocidad_sube_solo_4kmh|espesor_5_8mm_bajo_6_6mm|remaches_expuestos", "falla_bomba_embrague", "", "NO", "SI", "Falla en bombin o bomba hidraulica de embrague", "L3 medición de espesor 5.8 mm bajo cota 6.6 mm y salto de 2400 rpm.")
    agregar("G34-L3-02", CLASE_34, "L3", "Conductor reporta pérdida de fuerza en pendientes pronunciadas. En prueba de ruta con escáner OBD-II se registraron parámetros de velocidad de motor vs velocidad de sensor de salida de caja: en 3ra marcha a plena carga la relación calculada RPM/km/h se desvía un 38% por encima de la relación de transmisión teórica fija de 42.5 rpm/(km/h). Al realizar la prueba estática de calado con freno de estacionamiento aplicado y engranando 2da marcha soltando el pedal a 2000 rpm, el motor permanece en marcha sin calarse durante más de 6 segundos confirmando deslizamiento total.", "TECNICO", "analisis_relacion_rpm_velocidad_escaner", "desviacion_38_porciento_relacion_rpm_kmh|prueba_calado_no_apaga_6s|deslizamiento_total", "falla_sensor_velocidad", "", "NO", "NO", "", "L3 telemetría de relación RPM/km/h desfasada 38% y calado estático.")
    agregar("G34-L3-03", CLASE_34, "L3", "Inspección de embrague tras sobrecalentamiento severo: el disco de fricción presenta vitrificación completa con aspecto brillante de espejo y grietas térmicas radiales. La fuerza elástica de apriete del plato de presión cayó de 4800 N nominales a 2100 N debido a templado residual de los resortes cónicos del diafragma. El cojinete de empuje desliza libremente en su guía y no genera ningún ruido al desembragar en vacío.", "TECNICO", "metrologia_fuerza_prensa_2100n", "vitrificacion_espejo_disco|fuerza_plato_2100n_vs_4800n|cojinete_empuje_silencioso", "desgaste_collarin", "", "NO", "SI", "Desgaste en collarin de empuje o crapodina de embrague", "L3 dinamómetro mide 2100 N en prensa con cojinete silencioso.")
    agregar("G34-L3-04", CLASE_34, "L3", "Vehículo de reparto urbano presenta olor a quemado y trepidación violenta al arrancar cargado con 800 kg. Se desmontó la caja comprobándose que el retén del eje primario de la transmisión sufrió fuga de aceite de engranajes SAE 75W-90, impregnando el 70% del forro de fricción del disco. El disco patinó hasta quemar el compuesto orgánico formando una costra de carbón pegajosa que destruyó la planitud del volante motor con manchas térmicas de 0.15 mm de alabeo.", "TALLER", "contaminacion_aceite_valvulina_75w90", "fuga_aceite_caja_75w90_empapa_disco|costra_carbon|alabeo_volante_0_15mm", "falta_aceite_caja", "", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L3 fuga de valvulina contamina ferodo con alabeo térmico en volante.")
    agregar("G34-L3-05", CLASE_34, "L3", "Hola maestro, tengo un Sentra mecánico. Cuando voy en pista a 80 y quiero pasar un camión piso a fondo y el motor suena ¡roooaaar! como si estuviera en neutro, las revoluciones saltan a 5000 y el carro no se mueve rápido. El bombín no gotea nada de líquido y los cambios entran como mantequilla sin sonar.", "WHATSAPP", "adelantamiento_camion_sentra", "rpm_saltan_a_5000_sin_avance|bombin_no_gotea|cambios_entran_suaves", "falla_bombin_hidraulico", "", "NO", "SI", "Falla en bombin o bomba hidraulica de embrague", "L3 relato WhatsApp de salto de RPM a 5000 con hidráulica sana.")
    agregar("G34-L3-06", CLASE_34, "L3", "Evaluación de desgaste en embrague de fricción seca: medición micrométrica de profundidad de remaches en 12 puntos arrojó valores entre 0.05 mm y 0.18 mm (límite de descarte OEM 0.30 mm). Dos de los remaches de latón del lado de la prensa hicieron contacto abrasivo contra las pistas de acero del plato opresor mecanizando surcos circunferenciales concéntricos de 0.4 mm de profundidad.", "TECNICO", "metrologia_profundidad_remaches_0_05mm", "remaches_a_0_05mm_bajo_0_30mm|surcos_prensa_0_4mm|desgaste_limite", "falla_caja_mecanica", "", "NO", "NO", "", "L3 remaches a 0.05 mm rozando plato opresor con surcos de 0.4 mm.")
    agregar("G34-L3-07", CLASE_34, "L3", "Camioneta 4x4 presenta patinamiento exclusivo en modo 4H bajo esfuerzo de remolque en pendientes del 15%. Al aplicar torque de 320 Nm a 2200 rpm el conjunto de embrague emite un zumbido agudo de deslizamiento friccional y la velocidad disminuye progresivamente hasta detenerse. El sistema hidráulico tiene purga completa con pedal con carrera libre de 15 mm correcta.", "TALLER", "remolque_pendiente_15_porciento", "patinamiento_a_320nm_remolque|zumbido_deslizamiento|carrera_libre_15mm_ok", "falla_transferencia_4x4", "", "NO", "SI", "Falla en bombin o bomba hidraulica de embrague", "L3 deslizamiento a 320 Nm de par con hidráulica purgada.")
    agregar("G34-L3-08", CLASE_34, "L3", "Mi carro ase que suben las revoluciones al pisar en subida y bota humo con olor a quemado por abajo de la campana. El mecanico saco la caja y el disco taba en el fierro pelado con los resortes sueltos que casi se salen.", "ERROR_ORTOGRAFICO", "desarme_campana_embrague", "rpm_suben_subida|humo_olor_quemado_campana|disco_en_fierro_pelado", "falla_collarin", "", "NO", "SI", "Desgaste en collarin de empuje o crapodina de embrague", "L3 disco al fierro pelado con ortografía informal.")
    agregar("G34-L3-09", CLASE_34, "L3", "Análisis termográfico tras prueba de esfuerzo en dinamómetro: la carcasa de la campana de embrague alcanza 185°C en la zona perimetral del volante motor por fricción parasitaria continua sin accionar el pedal. La relación de transmisión calculada por la ECU genera código P0741 en vehículos con gestión electrónica de acoplamiento por patinamiento excesivo en cadena cinemática.", "TECNICO", "termografia_campana_185c_dtc_p0741", "campana_185c_friccion_parasitaria|dtc_p0741|patinamiento_cadena_cinematica", "falla_transmision_automatica", "P0741", "NO", "SI", "Sobrecalentamiento o solenoides en caja automatica CVT / DSG", "L3 termografía a 185°C y código P0741 por patinamiento severo.")
    agregar("G34-L3-10", CLASE_34, "L3", "Buenas tardes maestro, tengo un Kia Rio. Cuando acelero fuerte en autopista las revoluciones suben pero el velocímetro no acompaña. El pedal embraga recién arribita en la punta y no se siente duro ni nada. No hay ruidos cuando piso el embrague a fondo en neutro.", "WHATSAPP", "diagnostico_kia_rio_autopista", "rpm_suben_sin_acelerar_velocimetro|corta_en_la_punta|sin_ruido_en_neutro", "ruido_crapodina", "", "NO", "SI", "Desgaste en collarin de empuje o crapodina de embrague", "L3 corte en la punta y ausencia de ruidos en neutro descarta crapodina.")
    agregar("G34-L3-11", CLASE_34, "L3", "Pérdida de elasticidad en los flejes tangenciales de tracción que unen la cubierta con el plato de presión de la prensa de embrague: flejes deformados y sobrecalentados provocan contacto oblicuo del plato con pérdida del 45% del área efectiva de contacto del forro, acelerando el desgaste localizado y el resbalamiento.", "TECNICO", "inspeccion_flejes_tangenciales", "flejes_tangenciales_deformados|contacto_oblicuo|perdida_45_area_contacto", "falla_plato_opresor", "", "NO", "NO", "", "L3 deformación de flejes tangenciales reduce 45% de contacto útil.")
    agregar("G34-L3-12", CLASE_34, "L3", "Prueba de aceleración de 0 a 100 km/h: tiempo registrado de 19.8 segundos (especificación del fabricante 10.5 s) debido a que al cambiar de primera a segunda y de segunda a tercera el embrague demora 2.2 segundos en acoplar firmemente el giro del cigüeñal con el primario de la transmisión.", "TALLER", "cronometraje_aceleracion_19_8s", "aceleracion_0_a_100_19_8s_vs_10_5s|demora_2_2s_en_acoplar_cambio", "falla_inyectores", "", "NO", "NO", "", "L3 retardo de 2.2 segundos de acople en cambios alarga aceleración.")
    agregar("G34-L3-13", CLASE_34, "L3", "Inspección de volante bimasa (DMF) acoplado a embrague desgastado: juego angular libre de 28 grados (límite de servicio 14 grados) y juego axial de 2.2 mm con fuga de grasa de silicona por choque térmico continuo derivado del patinamiento crónico del disco de embrague.", "TECNICO", "metrologia_volante_bimasa_28_grados", "bimasa_juego_28_grados_vs_14|juego_axial_2_2mm|grasa_fugada_calor", "falla_caja_cambios", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L3 juego bimasa excesivo de 28° derivado de sobrecalentamiento crónico.")
    agregar("G34-L3-14", CLASE_34, "L3", "El cliente reclama que para incorporarse a la autopista debe acelerar con mucha precaución porque si pisa a fondo el auto zumba y patina sin ganar velocidad. Al inspeccionar el ferodo se observa carbonización profunda con espesor residual de 0.2 mm por encima de remaches y ranuras de limpieza totalmente colmatadas.", "TALLER", "incorporacion_autopista_patina", "patina_en_incorporacion_fondo|ferodo_carbonizado_0_2mm|ranuras_colmatadas", "falla_bomba_gasolina", "", "NO", "NO", "", "L3 ranuras de desahogo colmatadas y 0.2 mm de ferodo útil.")
    agregar("G34-L3-15", CLASE_34, "L3", "En banco dinamométrico se aplica rampa de par de 150 Nm a 250 Nm en 4ta marcha a 2500 rpm constantes: a los 195 Nm el disco de embrague cede iniciando resbalamiento con aumento instantáneo de temperatura en la superficie del volante a razón de 12°C por segundo medido con termocupla rápida.", "TECNICO", "dinamometro_rampa_par_195nm", "resbalamiento_inicia_a_195nm|aumento_temperatura_12c_segundo|termocupla", "falla_embrague_patina", "", "NO", "NO", "", "L3 dinamómetro identifica umbral de deslizamiento exacto a 195 Nm.")

    # =========================================================================
    # CLASE 35: Falla en bombin o bomba hidraulica de embrague (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G35-L1-01", CLASE_35, "L1", "El pedal de embrague se fue hasta el fondo y se quedó pegado al piso.", "COTIDIANO", "accionamiento", "pedal_embrague_al_fondo_pegado", "", "", "SI", "NO", "", "L1 pedal sin retorno por pérdida de presión.")
    agregar("G35-L1-02", CLASE_35, "L1", "Hola, no entran los cambios con el motor prendido pero apagado entran suaves.", "WHATSAPP", "parado_motor_encendido", "cambios_no_entran_motor_encendido", "", "", "SI", "NO", "", "L1 imposibilidad de desacoplar embrague.")
    agregar("G35-L1-03", CLASE_35, "L1", "Tengo que bombear tres veces el embrague con el pie para meter primera.", "COTIDIANO", "salida", "bombear_embrague_para_meter_cambio", "", "", "SI", "NO", "", "L1 aire en circuito de embrague.")
    agregar("G35-L1-04", CLASE_35, "L1", "Veo un goteo de líquido aceitoso justo arriba de los pedales del chofer.", "COTIDIANO", "inspeccion_pedalier", "goteo_liquido_pedalier", "", "", "SI", "NO", "", "L1 fuga en bomba principal de embrague.")
    agregar("G35-L1-05", CLASE_35, "L1", "Pérdida de presión hidráulica en el circuito de desembrague con aire atrapado.", "TECNICO", "diagnostico", "perdida_presion_circuito_desembrague", "", "", "SI", "NO", "", "L1 reporte técnico de despresurización.")
    agregar("G35-L1-06", CLASE_35, "L1", "El pedal del embrague se siente aguado y no tiene nada de resistencia.", "TALLER", "accionamiento", "pedal_aguado_sin_resistencia", "", "", "SI", "NO", "", "L1 falta de carga hidráulica.")
    agregar("G35-L1-07", CLASE_35, "L1", "Cuesta meter la primera y la retroceso rasca feo como si no pisara a fondo.", "COTIDIANO", "maniobra", "primera_cuesta|reversa_rasca", "", "", "SI", "NO", "", "L1 embrague arrastra por poco recorrido hidráulico.")
    agregar("G35-L1-08", CLASE_35, "L1", "Mi embrague se callo al piso y no regresa solo tengo que levantarlo con la punta del zapato.", "ERROR_ORTOGRAFICO", "accionamiento", "pedal_cae_al_piso_no_regresa|levantar_con_zapato", "", "", "SI", "NO", "", "L1 pedal muerto con ortografía informal.")
    agregar("G35-L1-09", CLASE_35, "L1", "Buenas, me baja el nivel del líquido de frenos pero las cuatro ruedas están secas.", "WHATSAPP", "revision_niveles", "liquido_frenos_baja|ruedas_secas", "", "", "SI", "NO", "", "L1 depósito compartido pierde por circuito de embrague.")
    agregar("G35-L1-10", CLASE_35, "L1", "Fallo de desplazamiento volumétrico en cilindro maestro o esclavo de embrague.", "TECNICO", "inspeccion", "fallo_desplazamiento_volumetrico", "", "", "SI", "NO", "", "L1 reporte técnico de accionamiento.")

    # --- L2 (15 casos) ---
    agregar("G35-L2-01", CLASE_35, "L2", "Pedal de embrague se queda pegado en la alfombra al presionarlo; al levantarlo manualmente con el pie y bombear varias veces recupera presión suficiente para engranar primera marcha.", "COTIDIANO", "arranque_manana", "pedal_pegado_alfombra|recupera_al_bombear", "embrague_patinando", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L2 necesidad de bombear delata falla hidráulica vs disco patinando.")
    agregar("G35-L2-02", CLASE_35, "L2", "Goteo constante de líquido de frenos DOT 4 sobre la alfombrilla del conductor proveniente del vástago de empuje de la bomba maestra de embrague bajo el tablero.", "TALLER", "inspeccion_habitaculo", "goteo_dot4_alfombrilla|fuga_vastago_bomba_maestra", "falla_frenos_bomba", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L2 fuga en cilindro emisor de embrague dentro de habitáculo.")
    agregar("G35-L2-03", CLASE_35, "L2", "Con el motor encendido es imposible engranar la marcha atrás sin que rasquen los piñones; con el motor apagado todas las velocidades entran con perfecta suavidad.", "TECNICO", "prueba_motor_encendido_vs_apagado", "reversa_rasca_motor_encendido|apagado_entran_suaves", "falla_sincronizadores", "", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L2 rascado solo con motor encendido descarta sincronizadores de caja.")
    agregar("G35-L2-04", CLASE_35, "L2", "Hola, el bombín de embrague que va pegado en la caja está todo mojado y bota líquido por el guardapolvo de goma; el pedal perdió la mitad de su recorrido.", "WHATSAPP", "inspeccion_vano_motor", "bombin_esclavo_mojado_gotea|pedal_perdio_recorrido", "disco_patina", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L2 bombín esclavo con fuga exterior visible.")
    agregar("G35-L2-05", CLASE_35, "L2", "Cilindro maestro de embrague con copela interna desgastada; el líquido recircula internamente sin fugas exteriores provocando que el pedal pierda presión progresiva.", "TECNICO", "prueba_presion_estatica", "copela_interna_desgastada|bypass_interno_bomba|sin_fuga_exterior", "falla_collarin", "", "NO", "SI", "Desgaste en collarin de empuje o crapodina de embrague", "L2 bypass interno en bomba de embrague sin fuga visible.")
    agregar("G35-L2-06", CLASE_35, "L2", "Al esperar en el semáforo con el embrague pisado y primera puesta el vehículo empieza a avanzar solo lentamente como si soltara el pedal por pérdida de presión.", "COTIDIANO", "parada_semaforo_primera", "vehiculo_avanza_solo_pedal_a_fondo|perdida_presion_continua", "falla_frenos", "", "NO", "NO", "", "L2 avance involuntario en semáforo por fuga interna de presión.")
    agregar("G35-L2-07", CLASE_35, "L2", "Presencia de aire en la cañería hidráulica de embrague tras cambio de líquido; la carrera muerta del pedal es de 70 mm y el embrague no desacopla totalmente.", "TALLER", "post_cambio_liquido", "aire_caneria_embrague|carrera_muerta_70mm|no_desacopla", "desgaste_disco", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L2 purga deficiente genera carrera muerta de 70 mm.")
    agregar("G35-L2-08", CLASE_35, "L2", "Mi carro no le entran los cambios cuando calienta y el pedal de embrage esta aguado en el piso. Tengo que bombearlo con el pie varias veses.", "ERROR_ORTOGRAFICO", "motor_caliente", "cambios_no_entran_caliente|pedal_aguado_piso|bombear_varias_veces", "falla_aceite_caja", "", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L2 pedal aguado en caliente con ortografía informal.")
    agregar("G35-L2-09", CLASE_35, "L2", "Buenas maestro, cambié el bombín receptor de la caja pero no logro que agarre pedal; no purga por el sangrador y sigue esponjoso sin presión.", "WHATSAPP", "proceso_purga_bombin", "no_agarra_pedal_post_cambio_bombin|sangrador_no_purga", "falla_disco_embrague", "", "NO", "NO", "", "L2 dificultad de purgado en bombín nuevo.")
    agregar("G35-L2-10", CLASE_35, "L2", "Manguera flexible de embrague entre chasis y caja hinchada bajo presión hidráulica; al pisar el pedal la manguera se expande como globo absorbiendo el volumen.", "TECNICO", "inspeccion_flexible_embrague", "flexible_embrague_se_hincha_presion|absorbe_volumen", "falla_bomba_embrague", "", "NO", "NO", "", "L2 flexible dilatado absorbe desplazamiento de bombín.")
    agregar("G35-L2-11", CLASE_35, "L2", "Depósito compartido de líquido de frenos y embrague: el nivel baja hasta el tabique de separación del compartimento de embrague quedando frenos operativos.", "COTIDIANO", "revision_deposito_compartido", "nivel_baja_hasta_tabique_embrague|frenos_operativos", "fuga_frenos", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L2 tabique de seguridad aísla fuga en embrague protegiendo frenos.")
    agregar("G35-L2-12", CLASE_35, "L2", "El vástago de la bomba de embrague se desenganchó del pedal por rotura del clip plástico de retención; pedal queda libre sin accionar el pistón.", "TALLER", "inspeccion_pedalera", "clip_plastico_roto|vastago_desenganchado_pedal", "falla_embrague_mecanico", "", "NO", "NO", "", "L2 desconexión mecánica en rótula de pedalier.")
    agregar("G35-L2-13", CLASE_35, "L2", "Cilindro esclavo concéntrico (crapodina hidráulica CSC) gotea líquido por el drenaje inferior de la campana de caja; embrague patina por líquido y pedal pierde presión.", "TECNICO", "inspeccion_drenaje_campana", "csc_gotea_drenaje_campana|liquido_en_disco|pedal_sin_presion", "fuga_aceite_motor", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L2 falla de CSC concéntrico con fuga de líquido en campana.")
    agregar("G35-L2-14", CLASE_35, "L2", "Resorte de retroceso del pistón de la bomba maestra de embrague quebrado; el émbolo no regresa a su posición inicial bloqueando la entrada de líquido nuevo.", "TALLER", "desarme_bomba_maestra", "resorte_retroceso_quebrado|embolo_no_retorna|bloqueo_puerto_compensacion", "falla_disco", "", "NO", "NO", "", "L2 resorte interno roto bloquea puerto de compensación.")
    agregar("G35-L2-15", CLASE_35, "L2", "Al pisar el embrague el desplazamiento del bombín receptor es de solo 6 mm (especificación 14 a 16 mm); carrera insuficiente para liberar la prensa.", "TECNICO", "medicion_carrera_bombin", "desplazamiento_bombin_6mm_vs_15mm|carrera_insuficiente", "disco_desgastado", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L2 desplazamiento de 6 mm vs 15 mm impide desembragar.")

    # --- L3 (15 casos) ---
    agregar("G35-L3-01", CLASE_35, "L3", "En un Hyundai Accent mecánico el pedal de embrague se va al piso tras permanecer 20 segundos detenido en un semáforo con la primera marcha seleccionada. Se conectó manómetro de presión hidráulica en la línea de purga del bombín esclavo registrando pico inicial de 35 bar al pisar a fondo, pero la presión decae a razón de 2 bar por segundo hasta 4 bar sin fugas externas visibles en cañerías ni racores. Se desmontó el cilindro maestro de embrague bajo el pedalier comprobándose rayaduras en el cuerpo plástico y copela secundaria invertida permitiendo bypass al depósito.", "TECNICO", "diagnostico_manometro_embrague_35bar", "presion_cae_35_a_4bar_en_20s|copela_secundaria_invertida|bypass_cilindro_maestro|sin_fuga_externa", "falla_bomba_frenos", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L3 manómetro registra caída de 35 a 4 bar por bypass en bomba maestra.")
    agregar("G35-L3-02", CLASE_35, "L3", "Vehículo no permite engranar marcha atrás ni primera velocidad con motor a temperatura de régimen de 90°C. Con motor apagado todos los cambios entran con dos dedos sin resistencia. Se midió el recorrido de empuje de la horquilla en el bombín receptor exterior arrojando solo 7.2 mm de avance (especificación mínima de desembrague 13.5 mm). Al retirar el guardapolvo de fuelle del bombín receptor se expulsaron 15 ml de líquido de frenos sucio acumulado tras haberse cuarteado el retén labial del émbolo.", "TALLER", "medicion_carrera_horquilla_7_2mm", "recorrido_horquilla_7_2mm_vs_13_5mm|cambios_duros_motor_encendido|fuga_reten_bombin_15ml", "falla_sincronizadores_caja", "", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L3 avance de horquilla en 7.2 mm vs 13.5 mm confirma falla de bombín.")
    agregar("G35-L3-03", CLASE_35, "L3", "Camioneta Toyota Hilux presenta pedal de embrague completamente esponjoso tras circular por caminos de tierra. Se realizó inspección visual del circuito hidráulico encontrando que el racor de conexión rápida del bombín esclavo perdió el seguro metálico Omega por vibración, permitiendo que la manguera se desplace 2 mm tomando aire del exterior al soltar el pedal sin fugar líquido en reposo. Se purgó el sistema con bomba de vacío manual Mityvac a 15 inHg extrayendo gran cantidad de espuma.", "TECNICO", "purga_vacio_mityvac_espuma", "seguro_omega_suelto_toma_aire|purga_mityvac_15inhg_espuma|pedal_esponjoso", "falla_disco_patina", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L3 toma de aire por acople rápido suelto purgado con Mityvac a 15 inHg.")
    agregar("G35-L3-04", CLASE_35, "L3", "Falla en vehículo con cojinete de desembrague concéntrico integrado (CSC - Concentric Slave Cylinder): goteo continuo de líquido DOT 4 por la ranura inferior de desahogo de la campana de la transmisión (aproximadamente 50 ml por semana). El líquido derramado centrifugó sobre el disco de embrague contaminando el forro de fricción provocando patinamiento a más de 3000 rpm sumado a pedal que se hunde y pérdida total de nivel en el compartimento de embrague del reservorio.", "TALLER", "fuga_csc_concentric_slave_cylinder", "goteo_dot4_campana_50ml|csc_concentric_fuga|disco_contaminado_patina|pedal_se_hunde", "fuga_aceite_caja", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L3 fuga en crapodina hidráulica CSC empapa disco y despresuriza pedal.")
    agregar("G35-L3-05", CLASE_35, "L3", "Hola maestro, tengo un Nissan Tiida. En las mañanas el pedal de embrague amanece tirado en el suelo y tengo que jalarlo con la mano y bombearlo como 10 veces para que pueda meter primera para salir. En el taller me cambiaron el disco de embrague pensando que era eso pero el carro sigue igualito con el pedal muerto.", "WHATSAPP", "diagnostico_tiida_manana", "pedal_amanece_en_el_suelo|bombear_10_veces_para_primera|disco_nuevo_sigue_igual", "disco_desgastado", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L3 pedal muerto en mañanas que no corrigió cambio de disco.")
    agregar("G35-L3-06", CLASE_35, "L3", "Evaluación de degradación de manguera flexible de alta presión del sistema hidráulico de embrague: al aplicar 45 bar de fuerza en el pedal la manguera elastomérica experimenta dilatación radial del 35% pasando de 10.5 mm a 14.2 mm de diámetro exterior, absorbiendo 4.8 cm3 de volumen hidráulico. Esto reduce la carrera efectiva del émbolo receptor en 6.5 mm impidiendo el desacople completo de los discos.", "TECNICO", "dilatacion_flexible_embrague_35_porciento", "dilatacion_manguera_10_5_a_14_2mm|absorbe_4_8cm3|carrera_reducida_6_5mm", "falla_bomba_maestra", "", "NO", "NO", "", "L3 dilatación volumétrica de manguera flexible de embrague en 35%.")
    agregar("G35-L3-07", CLASE_35, "L3", "El cliente reclama que para cambiar de marcha debe meter el pedal contra la lata del piso con violencia. Se midió la altura del pedal encontrando 110 mm sobre piso (especificación 145 mm) debido a que la tuerca de ajuste del vástago de la bomba maestra se aflojó y retrocedió 8 hilos de rosca sobre la horquilla del pedalier, generando 40 mm de juego muerto antes de comenzar a desplazar el émbolo.", "TALLER", "reglaje_altura_pedalier_vastago", "altura_110mm_vs_145mm|tuerca_aflojada_8_hilos|juego_muerto_40mm", "falla_disco_embrague", "", "NO", "NO", "", "L3 descalibración de 8 hilos en varilla roscada genera 40 mm de holgura.")
    agregar("G35-L3-08", CLASE_35, "L3", "Mi carro le quedo el pedal de embrague aguado como chicle y no entran los cambios. Mire abajo de los pedales y la bombita de plastico ta rota y botando liquido aceitoso en los zapatos del conductor.", "ERROR_ORTOGRAFICO", "rotura_bomba_pedalier", "pedal_aguado_chicle|cambios_no_entran|bomba_plastico_rota_bota_liquido", "falla_caja_cambios", "", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L3 rotura de cuerpo plástico de bomba con ortografía informal.")
    agregar("G35-L3-09", CLASE_35, "L3", "Prueba de hermeticidad con pinzamiento en línea hidráulica de embrague: se estrangula el flexible intermedio con mordaza protegida y se aplica presión en el pedal. El pedal se clava rígido a los 15 mm confirmando que la bomba maestra y su copela primaria están 100% herméticas; al liberar la mordaza el pedal vuelve a hundirse lentamente al piso confirmando que la fuga interna se localiza en el bombín receptor de la caja.", "TECNICO", "prueba_pinzamiento_diagnostico_diferencial", "pedal_rigido_al_estrangular_flexible|se_hunde_al_liberar|fuga_en_bombin_receptor", "falla_bomba_maestra", "", "NO", "NO", "", "L3 prueba de pinzamiento aísla fuga en bombín receptor descartando bomba.")
    agregar("G35-L3-10", CLASE_35, "L3", "Buenas tardes, en mi Duster mecánica el pedal de embrague no sube completo, se queda a mitad de camino y tengo que empujarlo con el pie hacia arriba. Me dijeron que el bombín de embrague tiene el resorte vencido y las gomas hinchadas porque le echaron aceite mineral en vez de DOT 4 en un lubricentro.", "WHATSAPP", "contaminacion_aceite_mineral_dot4", "pedal_a_mitad_de_camino|gomas_hinchadas_aceite_mineral|no_retorna_solo", "falla_disco_patina", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L3 contaminación con aceite mineral degrada sellos EPDM de bombín.")
    agregar("G35-L3-11", CLASE_35, "L3", "Obstrucción del orificio de compensación (breather port) en la bomba maestra de embrague: orificio de 0.6 mm taponado por sedimentos de goma degradada. Al expandirse térmicamente el líquido con el calor del motor el sistema no puede retornar el fluido al depósito, dejando el bombín con 4 bar de precarga constante que empuja la horquilla y hace patinar el embrague en caliente.", "TECNICO", "inspeccion_puerto_compensacion_0_6mm", "orificio_compensacion_0_6mm_taponado|precarga_4bar_caliente|patinamiento_inducido", "disco_desgastado", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L3 puerto de compensación taponado genera precarga de 4 bar y patinamiento.")
    agregar("G35-L3-12", CLASE_35, "L3", "Falla de desacoplamiento por fisura en el soporte metálico de la bomba maestra de embrague en el cortafuegos (firewall): al pisar el pedal con fuerza el cortafuegos de chapa se flexiona 18 mm hacia adelante en lugar de desplazar el vástago de la bomba, perdiendo el 60% del recorrido efectivo del pistón.", "TALLER", "flexion_chapa_cortafuegos_18mm", "cortafuegos_flexiona_18mm|soporte_chapa_fisurado|perdida_60_recorrido", "falla_pedalera", "", "NO", "NO", "", "L3 flexión de 18 mm en cortafuegos por fatiga estructural.")
    agregar("G35-L3-13", CLASE_35, "L3", "Desmontaje de actuador esclavo concéntrico (CSC): se detecta que el tubo de alimentación hidráulica plástico se rajó en la unión termosellada por vibración torsional de la caja. Se midió pérdida de 120 ml de líquido hidráulico dentro del cárter de embrague; el pedal se fue al suelo instantáneamente sin permitir cambiar de marcha.", "TECNICO", "tubo_plastico_csc_rajado_termosellado", "tubo_csc_rajado_termosellado|perdida_120ml_campana|pedal_al_suelo_instantaneo", "fuga_liquido_frenos", "", "NO", "SI", "Fuga hidraulica o aire en el sistema de frenos", "L3 rotura de tubo termosellado de CSC concéntrico con pérdida de 120 ml.")
    agregar("G35-L3-14", CLASE_35, "L3", "El cliente reporta que al circular en tráfico denso el pedal de embrague se torna blando y los cambios rascan progresivamente hasta no entrar ninguno. Al enfriarse el vehículo durante 45 minutos el pedal recupera firmeza. Se verificó que la cañería metálica de embrague estaba pegada al tubo colector de escape sin pantalla anticalórica, hirviendo el líquido a más de 160°C.", "TALLER", "ebullicion_por_cercania_escape", "ebullicion_liquido_cercania_escape_160c|pedal_blando_en_trafico|sin_pantalla_termica", "falla_aceite_caja", "", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L3 ebullición de líquido a 160°C por proximidad a colector de escape.")
    agregar("G35-L3-15", CLASE_35, "L3", "Comprobación de presión en cilindro esclavo con banco de prueba hidráulico: al accionar la bomba maestra a velocidad rápida la presión alcanza 42 bar, pero en accionamiento lento (10 segundos) la presión no supera los 6 bar debido a fuga por el labio exterior de la copela primaria que sella únicamente bajo gradientes de presión elevados.", "TECNICO", "prueba_gradiente_presion_lento_vs_rapido", "fuga_en_accionamiento_lento_6bar|accionamiento_rapido_42bar|copela_labio_cedido", "falla_bomba_maestra", "", "NO", "NO", "", "L3 copela de bomba sella a 42 bar en rápido pero fuga a 6 bar en lento.")

    # =========================================================================
    # CLASE 36: Falta o degradacion de aceite de caja de cambios (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G36-L1-01", CLASE_36, "L1", "Los cambios están durísimos para entrar especialmente en las mañanas frías.", "COTIDIANO", "manana_fria", "cambios_durisimos_en_frio", "", "", "SI", "NO", "", "L1 dificultad de engrane en frío por lubricante.")
    agregar("G36-L1-02", CLASE_36, "L1", "Hola, la caja de cambios zumba como un engranaje seco cuando voy en carretera.", "WHATSAPP", "carretera", "caja_zumba_engranaje_seco", "", "", "SI", "NO", "", "L1 zumbido de engranes sin lubricación.")
    agregar("G36-L1-03", CLASE_36, "L1", "Encontré un charco de aceite espeso y con olor fuerte a azufre bajo el motor.", "COTIDIANO", "estacionamiento", "charco_aceite_espeso_olor_azufre", "", "", "SI", "NO", "", "L1 fuga de valvulina con olor azufrado.")
    agregar("G36-L1-04", CLASE_36, "L1", "La palanca de cambios raspa y se siente áspera al pasar de primera a segunda.", "TALLER", "cambio_1_a_2", "palanca_raspa_aspero_1_a_2", "", "", "SI", "NO", "", "L1 fricción áspera entre sincronizadores.")
    agregar("G36-L1-05", CLASE_36, "L1", "Nivel de lubricante de transmisión manual por debajo del umbral mínimo de seguridad.", "TECNICO", "inspeccion", "nivel_lubricante_bajo_minimo", "", "", "SI", "NO", "", "L1 reporte técnico de nivel insuficiente.")
    agregar("G36-L1-06", CLASE_36, "L1", "La caja calienta muchísimo y despide un olor a aceite requemado al parar.", "COTIDIANO", "post_viaje", "caja_calienta_olor_quemado", "", "", "SI", "NO", "", "L1 sobrecalentamiento de transmisión.")
    agregar("G36-L1-07", CLASE_36, "L1", "Se escucha un silbido metálico continuo en todas las marchas al acelerar.", "COTIDIANO", "marcha", "silbido_metalico_todas_marchas", "", "", "SI", "NO", "", "L1 fricción de piñonería general.")
    agregar("G36-L1-08", CLASE_36, "L1", "Mi caja manual ase un chillido sordo y la segunda raspa feo cuando meto el cambio.", "ERROR_ORTOGRAFICO", "cambio_marcha", "chillido_sordo_caja|segunda_raspa", "", "", "SI", "NO", "", "L1 rascado y zumbido con ortografía informal.")
    agregar("G36-L1-09", CLASE_36, "L1", "Buenas, el mecánico sacó el tapón de la caja y salió solo un chorrito negro con brillo.", "WHATSAPP", "revision_taller", "solo_chorrito_negro_con_brillo", "", "", "SI", "NO", "", "L1 aceite quemado con limalla en suspensión.")
    agregar("G36-L1-10", CLASE_36, "L1", "Degradación oxidativa severa de aditivos de extrema presión EP en fluido GL-4.", "TECNICO", "analisis_fluido", "degradacion_aditivos_ep_gl4", "", "", "SI", "NO", "", "L1 reporte técnico de descomposición de valvulina.")

    # --- L2 (15 casos) ---
    agregar("G36-L2-01", CLASE_36, "L2", "Dificultad severa para engranar primera y segunda marcha con temperatura ambiente de 10°C; tras rodar 20 minutos y calentar la caja los cambios entran con mayor facilidad.", "COTIDIANO", "temperatura_fria_10c", "cambios_duros_frio_10c|suaviza_al_calentar", "falla_embrague", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L2 viscosidad inadecuada o degradada en frío vs embrague.")
    agregar("G36-L2-02", CLASE_36, "L2", "Fuga abundante de valvulina por el retén de salida del semieje derecho; la carcasa de la transmisión está empapada y el tapón de nivel acusa 1 litro faltante.", "TALLER", "inspeccion_elevador", "fuga_reten_semieje|1_litro_faltante_valvulina", "fuga_aceite_motor", "", "NO", "SI", "Rodajes de caja mecanica o diferencial gastados", "L2 fuga por retén con déficit de 1 litro de aceite.")
    agregar("G36-L2-03", CLASE_36, "L2", "Zumbido sordo generalizado que se percibe en 1ra, 2da, 3ra, 4ta y 5ta marcha al acelerar; al retirar el tapón de nivel con el dedo no se toca fluido de transmisión.", "TECNICO", "inspeccion_nivel_tapón", "zumbido_todas_marchas|nivel_seco_sin_aceite", "rodaje_eje_primario", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L2 nivel seco genera zumbido parejo en todas las marchas.")
    agregar("G36-L2-04", CLASE_36, "L2", "Hola maestro, le cambiaron aceite a la caja y le pusieron un 85W-140 grueso de camión en vez de 75W-80 sintético; ahora la palanca está pesadísima y rasca.", "WHATSAPP", "post_cambio_viscosidad_erronea", "palanca_pesada_aceite_grueso_85w140|rasca_cambios", "falla_selectora", "", "NO", "NO", "", "L2 viscosidad incorrecta 85W-140 traba sincronizadores.")
    agregar("G36-L2-05", CLASE_36, "L2", "Al drenar el aceite de la caja de cambios salieron apenas 600 ml de lubricante negro fétido (capacidad nominal 2.2 litros); el imán del tapón tenía una masa de limalla.", "TECNICO", "drenaje_valvulina", "drenaje_600ml_vs_2_2l|iman_masa_limalla|aceite_fetido", "falla_caja_interna", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L2 drenaje de solo 600 ml con limalla imantada.")
    agregar("G36-L2-06", CLASE_36, "L2", "Rascado intermitente al pasar de 3ra a 2da marcha al reducir en bajadas; los frenos están bien y el pedal de embrague desembraga con recorrido completo normal.", "COTIDIANO", "reduccion_3_a_2", "rascado_reduccion_3_a_2|desembrague_completo_ok", "falla_bombin_embrague", "", "NO", "SI", "Falla en bombin o bomba hidraulica de embrague", "L2 desgaste de lubricante afecta sincronizador de 2da.")
    agregar("G36-L2-07", CLASE_36, "L2", "Sobrecalentamiento de la carcasa de la caja de cambios alcanzando 110°C tras 40 km de marcha; el respiradero superior de la transmisión expulsa espuma aceitosa.", "TALLER", "marcha_40km_calor", "carcasa_caja_110c|respiradero_bota_espuma", "falla_motor_calor", "", "NO", "NO", "", "L2 formación de espuma y temperatura de 110°C por aceite degradado.")
    agregar("G36-L2-08", CLASE_36, "L2", "Mi caja manual ase un zumbido feo en pista y bota gotas de aceite color miel espesas con olor fuerte a azufre debajo del chofer.", "ERROR_ORTOGRAFICO", "goteo_estacionamiento", "zumbido_caja|gotea_aceite_miel_azufre", "fuga_aceite_motor", "", "NO", "NO", "", "L2 fuga de valvulina azufrada con ortografía informal.")
    agregar("G36-L2-09", CLASE_36, "L2", "Buenas, el auto tiene 160,000 km y nunca se le cambió el aceite de transmisión manual; ahora la tercera no entra a menos que haga doble embrague.", "WHATSAPP", "160000km_sin_cambio", "160000km_sin_cambio_valvulina|tercera_requiere_doble_embrague", "falla_embrague", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L2 lubricante agotado tras 160,000 km exige doble embrague.")
    agregar("G36-L2-10", CLASE_36, "L2", "Aceite de caja contaminado con agua tras vadear un arroyo; el lubricante tiene aspecto de emulsión lechosa café con leche y perdió capacidad lubricante.", "TECNICO", "inspeccion_emulsion_agua", "emulsion_lechosa_agua_valvulina|perdida_capacidad_lubricante", "falla_embrague_humedo", "", "NO", "NO", "", "L2 emulsión de agua y aceite por respiradero.")
    agregar("G36-L2-11", CLASE_36, "L2", "Ruido áspero de engranajes en neutro que disminuye ligeramente al tomar temperatura; nivel medido a 35 mm por debajo del borde de llenado.", "COTIDIANO", "ralenti_neutro", "ruido_aspero_engranajes_neutro|nivel_bajo_35mm", "rodaje_primario", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L2 nivel a -35 mm causa rumorosidad de piñones.")
    agregar("G36-L2-12", CLASE_36, "L2", "Incompatibilidad química por usar aceite API GL-5 en caja manual que exige GL-4; los aditivos de azufre-fósforo atacaron y corroyeron los anillos de bronce sincronizadores.", "TECNICO", "analisis_quimico_gl5_vs_gl4", "aditivos_gl5_atacan_bronce_sincronizadores|particulas_amarillas", "falla_disco", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L2 corrosión química de sincronizadores de bronce por GL-5.")
    agregar("G36-L2-13", CLASE_36, "L2", "Palanca de cambios se traba ocasionalmente en 5ta marcha al rodar en carretera; el varillaje exterior desliza suave pero la horquilla interna sufre roce seco.", "TALLER", "prueba_carretera_quinta", "quinta_se_traba_carretera|varillaje_suave_ok|roce_seco_horquilla", "falla_varillaje", "", "NO", "NO", "", "L2 engrane atascado por lubricación deficiente en 5ta.")
    agregar("G36-L2-14", CLASE_36, "L2", "Vibración y rumorosidad de caja que desaparece por completo al rellenar 1.4 litros de fluido 75W-85 nuevo por el tapón de servicio.", "COTIDIANO", "post_rellenado_aceite", "rumorosidad_desaparece_tras_1_4l_aceite", "falla_diferencial_mecanico", "", "NO", "SI", "Rodajes de caja mecanica o diferencial gastados", "L2 cese inmediato de rumorosidad tras reponer 1.4 L.")
    agregar("G36-L2-15", CLASE_36, "L2", "Inspección de tapón magnético de caja manual revela filamentos de bronce y viruta fina de acero adherida tras 80,000 km con lubricante de fábrica degradado.", "TECNICO", "inspeccion_tapon_magnetico", "filamentos_bronce_viruta_acero_tapon|aceite_degradado_80000km", "falla_rodaje_caja", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L2 detritos metálicos de desgaste por aceite envejecido.")

    # --- L3 (15 casos) ---
    agregar("G36-L3-01", CLASE_36, "L3", "En un Volkswagen Gol con 115,000 km la transmisión manual presenta dificultad progresiva para insertar la segunda y tercera marcha con chasquido de rascado metálico. Se procedió a retirar el tapón de drenaje magnético de la caja: salieron solo 450 ml de lubricante espeso y ennegrecido (capacidad nominal 2.0 litros de SAE 75W-90). El análisis del residuo en el imán evidenció 8 gramos de pasta metálica con esquirlas de bronce provenientes de los anillos sincronizadores y partículas ferrosas. Se constató fuga continua a través del retén del selector de marchas superior que goteaba sobre el túnel de escape.", "TECNICO", "drenaje_metrologia_450ml_limalla", "drenaje_450ml_vs_2_0l|8g_pasta_metalica_bronce|esquirlas_sincronizadores|fuga_reten_selector", "falla_rodajes_diferencial", "", "NO", "SI", "Rodajes de caja mecanica o diferencial gastados", "L3 drenaje de solo 450 ml con 8g de limalla y fuga en selector.")
    agregar("G36-L3-02", CLASE_36, "L3", "Conductor reporta zumbido agudo en la transmisión en todas las velocidades que aumenta en proporción directa a las RPM y a la velocidad del auto. Se midió la temperatura de la carcasa de la caja con termómetro infrarrojo alcanzando 118°C tras 30 minutos de autopista a 100 km/h (temperatura normal de régimen 65°C a 75°C). Al introducir sonda por el orificio de llenado el nivel de aceite se encuentra 42 mm por debajo de la cota inferior debido a pérdida inadvertida por el fuelle del palier izquierdo rajado.", "TALLER", "medicion_termica_carcasa_118c", "temperatura_caja_118c_vs_70c|nivel_42mm_bajo_cota|fuelle_palier_rajado|zumbido_todas_marchas", "falla_rodamiento_rueda", "", "NO", "SI", "Rodajes de caja mecanica o diferencial gastados", "L3 temperatura anormal de 118°C y nivel a -42 mm por fuelle roto.")
    agregar("G36-L3-03", CLASE_36, "L3", "Análisis de laboratorio de muestra de aceite de transmisión manual SAE 75W-80 GL-4: viscosidad cinemática a 100°C degradada a 4.8 cSt (especificación de aceite nuevo 9.2 cSt) y número de acidez total (TAN) elevado a 4.2 mg KOH/g (límite de descarte 2.0) tras 180,000 km de uso severo urbano sin recambio. La pérdida del paquete de aditivos modificadores de fricción impide el frenado sincronizado de los piñones provocando rascado permanente al reducir a segunda marcha.", "TECNICO", "analisis_laboratorio_viscosidad_4_8cst", "viscosidad_4_8cst_vs_9_2cst|tan_4_2mg_koh|perdida_aditivos_friccion|rascado_segunda", "falla_embrague", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L3 análisis físico-químico: viscosidad caída a 4.8 cSt y TAN en 4.2.")
    agregar("G36-L3-04", CLASE_36, "L3", "Transmisión manual de camioneta Toyota Hilux presenta dureza extrema en la palanca de cambios en arranques a primera hora de la mañana a 8°C. El taller previo aplicó erróneamente lubricante de engranajes para diferencial hipoide SAE 85W-140 con aditivos GL-5 en lugar de la valvulina 75W-90 GL-4 especificada. La alta viscosidad en frío y el exceso de aditivos de azufre activo generaron un coeficiente de rozamiento dinámico inadecuado en los conos de sincronización provocando bloqueo hidrodinámico de los anillos.", "TALLER", "incompatibilidad_viscosidad_85w140_gl5", "lubricante_erroneo_85w140_gl5|bloqueo_hidrodinamico_anillos|dureza_extrema_8c", "falla_varillaje_cambios", "", "NO", "NO", "", "L3 viscosidad errónea 85W-140 GL-5 genera bloqueo hidrodinámico.")
    agregar("G36-L3-05", CLASE_36, "L3", "Hola maestro, tengo un Hyundai i10. En carretera la caja zumba como si tuviera un avión adentro en cuarta y quinta. Le revisaron el tapón de la caja y no tenía casi nada de aceite, le echaron litro y medio y el zumbido bajó bastante pero quedó un silbido bajito porque anduvo seca varios días.", "WHATSAPP", "diagnostico_i10_caja_seca", "zumba_como_avion_4ta_5ta|caja_seca_recibe_1_5l|silbido_remanente_desgaste", "rodajes_diferencial", "", "NO", "SI", "Rodajes de caja mecanica o diferencial gastados", "L3 relato WhatsApp de caja seca que requirió 1.5 litros.")
    agregar("G36-L3-06", CLASE_36, "L3", "Desmontaje e inspección de caja manual de 5 velocidades tras operar con 300 ml de aceite durante 5,000 km: los engranajes de la 5ta marcha montados en el extremo exterior de la carcasa sufrieron decoloración térmica azul (sobrecalentamiento a más de 300°C) y desgaste adhesivo con microsoldadura en los flancos de los dientes por ser el piñón más alto del tren que deja de recibir salpicadura al descender el nivel.", "TECNICO", "inspeccion_desgaste_adhesivo_quinta", "decoloracion_azul_pinon_quinta|300c_microsoldadura_flancos|falta_salpicadura_300ml", "falla_rodaje_primario", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L3 piñón de 5ta descolorido a 300°C por descebe de salpicadura.")
    agregar("G36-L3-07", CLASE_36, "L3", "Vehículo 4x4 presenta emulsión lechosa en la caja de cambios tras cruzar una poza profunda en época de lluvias. El respiradero superior de la transmisión tenía la válvula de retención plástica quebrada permitiendo el ingreso de aproximadamente 400 ml de agua lodosa. El lubricante emulsionó totalmente perdiendo película hidrodinámica elastohidrodinámica provocando rumorosidad en todos los apoyos de engranaje.", "TALLER", "ingreso_agua_valvula_respiradero_rota", "respiradero_quebrado_ingreso_agua_400ml|emulsion_lechosa|perdida_pelicula_lubricante", "falla_transferencia", "", "NO", "NO", "", "L3 400 ml de agua ingresados por respiradero roto destruyen película.")
    agregar("G36-L3-08", CLASE_36, "L3", "Mi carro zumbaba la caja feo en carretera y botaba valvulina por el reten de la flecha izquierda. Al vaciar la caja salio solo un pocillo chiquito de aceite negro quemado lleno de brillantina dorada de los sincronizadores.", "ERROR_ORTOGRAFICO", "vaciado_aceite_brillantina", "zumbaba_caja_carretera|fuga_reten_flecha|pocillo_chiquito_aceite_quemado|brillantina_dorada", "falla_flecha", "", "NO", "NO", "", "L3 brillantina dorada y aceite quemado con ortografía informal.")
    agregar("G36-L3-09", CLASE_36, "L3", "Medición de espesor de película de aceite y ensayo espectrométrico de metales de desgaste (ICP): hierro (Fe) en 480 ppm (normal menor a 80 ppm) y cobre (Cu) en 190 ppm (normal menor a 30 ppm) en caja de cambios mecánica con 95,000 km sin servicio. La degradación oxidativa del lubricante duplicó la fricción en interfaz cono-anillo generando retardo de 0.8 s en sincronización.", "TECNICO", "espectrometria_icp_fe_480ppm", "espectrometria_icp_fe_480ppm_cu_190ppm|retardo_0_8s_sincronizacion", "falla_rodajes_caja", "", "NO", "SI", "Rodajes de caja mecanica o diferencial gastados", "L3 espectrometría ICP acusa Fe a 480 ppm y Cu a 190 ppm.")
    agregar("G36-L3-10", CLASE_36, "L3", "Buenas tardes, en mi Kia Cerato la palanca de cambios se puso áspera y chillan los engranajes al meter reversa. En el taller me sacaron el tapón de nivel y estaba 3 dedos más abajo de lo normal porque perdía por el retén del selector. Le completaron el aceite sintético 75W-85 y los cambios volvieron a entrar suaves.", "WHATSAPP", "diagnostico_kia_cerato_nivel", "palanca_aspera|reversa_chilla|nivel_3_dedos_bajo|suaviza_tras_completar", "falla_bombin_embrague", "", "NO", "SI", "Falla en bombin o bomba hidraulica de embrague", "L3 recuperación inmediata de suavidad al completar nivel a cota.")
    agregar("G36-L3-11", CLASE_36, "L3", "Desgaste corrosivo severo en casquillos de agujas del piñón loco de marcha atrás por acidificación del lubricante: el pH del aceite usado cayó a 4.1 ácido debido a condensación interna y calor extremo. Los rodillos de agujas presentan picaduras por corrosión química perdiendo concentricidad y provocando zumbido específico en marcha atrás.", "TECNICO", "acidificacion_lubricante_ph_4_1", "ph_acido_4_1_valvulina|corrosion_quimica_casquillo_agujas|zumbido_reversa", "falla_rodaje_primario", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L3 acidificación a pH 4.1 causa corrosión química en agujas.")
    agregar("G36-L3-12", CLASE_36, "L3", "Fuga masiva de fluido de transmisión manual a través de fisura en la carcasa inferior provocada por impacto contra resalto de calzada. El conductor continuó la marcha durante 12 km hasta que la tercera velocidad se trabó mecánicamente por gripado térmico del casquillo separador sobre el eje secundario desprovisto de lubricación.", "TALLER", "impacto_carcasa_gripado_12km", "fisura_carcasa_impacto|perdida_total_aceite|gripado_tercera_a_los_12km", "falla_embrague", "", "NO", "NO", "", "L3 impacto fisura cárter con gripado de 3ra tras 12 km en seco.")
    agregar("G36-L3-13", CLASE_36, "L3", "Análisis térmico de caja manual compacta: la temperatura del aceite alcanza 125°C en ciclo continuo de tráfico severo debido a pérdida de propiedades antiespumantes del lubricante mineral básico. La espuma formada reduce la transferencia térmica hacia las aletas de la carcasa provocando dilatación desigual de horquillas de cambio.", "TECNICO", "analisis_perdida_antiespumante_125c", "aceite_alcanza_125c_trafico|perdida_antiespumante|espuma_reduce_refrigeracion", "falla_radiador_motor", "", "NO", "NO", "", "L3 pérdida de antiespumante eleva temperatura a 125°C.")
    agregar("G36-L3-14", CLASE_36, "L3", "El cliente manifiesta que al realizar viajes largos de más de 100 km la palanca se vuelve cada vez más dura y rasca en todas las marchas pero al día siguiente en frío funciona casi normal. Se verificó que el lubricante tenía 14 años de antigüedad con pérdida total de viscosidad cinemática por corte mecánico de polímeros (Shear Stability Loss).", "TALLER", "perdida_estabilidad_cizallamiento", "cambios_duros_post_100km|suaves_en_frio|cizallamiento_polimeros_14anos", "falla_sincronizadores", "", "NO", "SI", "Disco de embrague desgastado o patinando", "L3 degradación por cizallamiento tras 14 años sin reemplazo.")
    agregar("G36-L3-15", CLASE_36, "L3", "Inspección de aceite drenado con tamiz de 50 micras: retención de partículas metálicas de aleación de aluminio y bronce de 0.8 mm de tamaño. La falta de 1.1 litros de aceite en caja de 1.8 L impidió la lubricación por barboteo en los conos de fricción provocando desgaste acelerado de las estrías de acople de los manguitos desplazables.", "TECNICO", "tamizado_50_micras_manguitos", "tamiz_50um_particulas_0_8mm|falta_1_1l_de_1_8l|desgaste_manguitos_desplazables", "falla_rodaje_caja", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L3 tamizado retiene partículas de 0.8 mm por falta de 1.1 L de aceite.")

    # =========================================================================
    # CLASE 37: Rodajes de caja mecanica o diferencial gastados (40 casos)
    # =========================================================================

    # --- L1 (10 casos) ---
    agregar("G37-L1-01", CLASE_37, "L1", "La transmisión zumba como una turbina cada vez que acelero en pista.", "COTIDIANO", "aceleracion_pista", "zumbido_turbina_al_acelerar", "", "", "SI", "NO", "", "L1 zumbido de transmisión bajo carga.")
    agregar("G37-L1-02", CLASE_37, "L1", "Hola, siento un aullido sordo debajo del centro del carro que cambia al soltar el gas.", "WHATSAPP", "retencion", "aullido_centro_cambia_al_soltar_gas", "", "", "SI", "NO", "", "L1 aullido de piñón y corona de diferencial.")
    agregar("G37-L1-03", CLASE_37, "L1", "Se escucha un ronroneo metálico constante que aumenta con la velocidad del carro.", "COTIDIANO", "rodadura_velocidad", "ronroneo_aumenta_con_velocidad", "", "", "SI", "NO", "", "L1 zumbido proporcional a velocidad vehicular.")
    agregar("G37-L1-04", CLASE_37, "L1", "Al desacelerar en quinta suena un quejido áspero en la parte de abajo de la caja.", "TALLER", "desaceleracion_quinta", "quejido_aspero_desaceleracion", "", "", "SI", "NO", "", "L1 ruido en retención en diferencial.")
    agregar("G37-L1-05", CLASE_37, "L1", "Desgaste por fatiga superficial (pitting) en pistas cónicas de rodamientos de diferencial.", "TECNICO", "diagnostico", "desgaste_pitting_rodamientos_diferencial", "", "", "SI", "NO", "", "L1 reporte técnico de pitting en diferencial.")
    agregar("G37-L1-06", CLASE_37, "L1", "Siento un golpeteo y zumbido metálico al doblar cerrado en una esquina.", "COTIDIANO", "curva_cerrada", "zumbido_golpeteo_al_doblar", "", "", "SI", "NO", "", "L1 ruido en planetarios y satélites.")
    agregar("G37-L1-07", CLASE_37, "L1", "El auto zumba fuerte a 80 km/h tanto en línea recta como al doblar.", "COTIDIANO", "velocidad_80kmh", "zumbido_fuerte_80kmh_recta_y_curva", "", "", "SI", "NO", "", "L1 ruido invariable con dirección descarta rueda.")
    agregar("G37-L1-08", CLASE_37, "L1", "Mi carro ase un aullido feo en la carretera como si fuera un avion despegando.", "ERROR_ORTOGRAFICO", "carretera", "aullido_feo_carretera_como_avion", "", "", "SI", "NO", "", "L1 aullido con ortografía informal.")
    agregar("G37-L1-09", CLASE_37, "L1", "Buenas, levantaron el carro en el aire y al girar las llantas la caja suena hueca.", "WHATSAPP", "inspeccion_elevador", "ruedas_girando_caja_suena_hueca", "", "", "SI", "NO", "", "L1 prueba en elevador delata ruido en núcleo de diferencial.")
    agregar("G37-L1-10", CLASE_37, "L1", "Holgura axial y angular fuera de tolerancia en conjunto piñón de ataque y corona.", "TECNICO", "inspeccion", "holgura_axial_pinon_corona", "", "", "SI", "NO", "", "L1 reporte técnico de juego en grupo cónico.")

    # --- L2 (15 casos) ---
    agregar("G37-L2-01", CLASE_37, "L2", "Aullido agudo en la transmisión entre 70 y 90 km/h al pisar el acelerador; al soltar el pedal y rodar en neutro a 80 km/h el aullido desaparece por completo.", "COTIDIANO", "aceleracion_vs_neutro_80kmh", "aullido_al_acelerar_70_90|desaparece_en_neutro", "rodamiento_rueda_zumbido", "", "NO", "SI", "Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)", "L2 ruido exclusivo bajo carga descarta rodaje de rueda.")
    agregar("G37-L2-02", CLASE_37, "L2", "Zumbido constante en el diferencial delantero que no cambia de tono al girar en curvas pronunciadas a izquierda o derecha; rodamientos de maza de rueda sin holgura.", "TALLER", "curvas_izquierda_derecha", "zumbido_no_cambia_en_curvas|rodamientos_maza_ok", "falla_rodamiento_maza", "", "NO", "SI", "Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)", "L2 ruido invariable al apoyar peso en curva descarta maza.")
    agregar("G37-L2-03", CLASE_37, "L2", "Holgura excesiva en la salida de los semiejes de la transmisión; los rodamientos de apoyo de la caja diferencial tienen 1.8 mm de juego radial apreciable.", "TECNICO", "inspeccion_salida_semiejes", "holgura_salida_semiejes|juego_radial_1_8mm_diferencial", "falla_palieres", "", "NO", "SI", "Juntas homocineticas o palieres danados", "L2 juego radial en apoyo de caja diferencial vs palieres.")
    agregar("G37-L2-04", CLASE_37, "L2", "Hola, mi camioneta zumba al acelerar en autopista pero en reversa o parado con embrague pisado no suena nada; el aceite de caja está al nivel máximo correcto.", "WHATSAPP", "autopista_aceleracion", "zumba_al_acelerar_autopista|aceite_a_nivel_maximo", "falta_aceite_caja", "", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L2 nivel de aceite perfecto descarta falta de lubricación.")
    agregar("G37-L2-05", CLASE_37, "L2", "Ruido áspero de rozamiento en rodamientos cónicos del piñón de ataque; el zumbido cambia drásticamente de tonalidad entre tracción y retención de motor.", "TECNICO", "prueba_traccion_retencion", "zumbido_cambia_traccion_a_retencion|rodamientos_pinon_ataque", "falla_eje_primario", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L2 cambio de tono tracción vs retención delata piñón de ataque.")
    agregar("G37-L2-06", CLASE_37, "L2", "Al elevar el vehículo y acelerar las ruedas motrices en el aire a 60 km/h, con estetoscopio se localiza el zumbido directamente sobre la carcasa del diferencial.", "TALLER", "estetoscopio_carcasa_diferencial", "estetoscopio_zumbido_carcasa_diferencial|ruedas_aire", "falla_rodamientos_rueda", "", "NO", "SI", "Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)", "L2 localización con estetoscopio en núcleo de diferencial.")
    agregar("G37-L2-07", CLASE_37, "L2", "Crujido metálico y chasquido al realizar giros cerrados a baja velocidad en pavimento; arandelas de fricción de los engranajes satélites y planetarios desgastadas.", "COTIDIANO", "giro_cerrado_baja_velocidad", "crujido_giros_cerrados|arandelas_satelites_desgastadas", "falla_homocinetica", "", "NO", "SI", "Juntas homocineticas o palieres danados", "L2 chasquido en planetarios de diferencial vs homocinética.")
    agregar("G37-L2-08", CLASE_37, "L2", "Mi carro ase un silbido grave en carretera que empiesa a los 60 y no se quita a ninguna velocidad. Si meto neutro sigue zumbando igualito.", "ERROR_ORTOGRAFICO", "carretera_neutro", "silbido_grave_desde_60kmh|sigue_zumbando_en_neutro", "falla_embrague", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L2 zumbido que continúa en neutro descarta eje primario con ortografía informal.")
    agregar("G37-L2-09", CLASE_37, "L2", "Buenas maestro, en el taller me dijeron que los rodamientos laterales de la corona de la caja están picados; el aceite salió limpio pero con polvillo de hierro.", "WHATSAPP", "diagnostico_taller_corona", "rodamientos_corona_picados|aceite_con_polvillo_hierro", "falla_aceite_caja", "", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L2 pistas picadas con aceite limpio descarta lubricación.")
    agregar("G37-L2-10", CLASE_37, "L2", "Desalineación del contacto de dientes entre piñón de ataque y corona hipoide; patrón de contacto desplazado hacia la punta del diente generando aullido de carga.", "TECNICO", "prueba_azul_prusia_contacto", "patron_contacto_desplazado_punta|aullido_carga_pinon_corona", "falla_caja_cambios", "", "NO", "NO", "", "L2 azul de Prusia revela desajuste de huella en corona.")
    agregar("G37-L2-11", CLASE_37, "L2", "Zumbido en diferencial trasero de vehículo con tracción integral AWD que aparece a partir de 90 km/h; los rodamientos de apoyo de la corona tienen precarga nula.", "COTIDIANO", "autopista_90kmh_awd", "zumbido_diferencial_trasero_90kmh|precarga_nula_corona", "falla_cardan", "", "NO", "NO", "", "L2 pérdida de precarga en diferencial trasero AWD.")
    agregar("G37-L2-12", CLASE_37, "L2", "Juego angular excesivo en la brida de entrada del diferencial de más de 15 grados; produce un golpe metálico 'clac' seco al pasar de acelerar a frenar.", "TALLER", "inversion_carga_acelerar_frenar", "juego_angular_brida_15_grados|golpe_clac_inversion_carga", "falla_cruceta_cardan", "", "NO", "NO", "", "L2 holgura angular de 15° genera clac al invertir par.")
    agregar("G37-L2-13", CLASE_37, "L2", "Aullido agudo en retención de motor (al soltar el acelerador en bajada con marcha engranada); el rodamiento frontal del piñón de ataque presenta holgura axial.", "TECNICO", "retencion_bajada_marcha", "aullido_en_retencion|holgura_axial_rodamiento_pinon", "falla_caja_engranajes", "", "NO", "NO", "", "L2 aullido específico en desaceleración por juego en piñón.")
    agregar("G37-L2-14", CLASE_37, "L2", "Vibración de alta frecuencia en el piso del habitáculo que inicia a 70 km/h y se intensifica a 110 km/h; rodamientos cónicos del carrier del diferencial con picaduras.", "COTIDIANO", "velocidad_70_a_110kmh", "vibracion_piso_70_a_110kmh|rodamientos_carrier_picados", "llantas_desbalanceadas", "", "NO", "SI", "Llantas desbalanceadas o desalineadas", "L2 vibración por pitting en carrier descarta balanceo de ruedas.")
    agregar("G37-L2-15", CLASE_37, "L2", "Prueba de precarga de rodamientos de diferencial con torquímetro dinamométrico: par de giro de apenas 0.2 Nm (especificación con rodamientos sanos 1.5 a 2.5 Nm).", "TECNICO", "metrologia_par_giro_dinamometro", "par_giro_0_2nm_vs_2_0nm|perdida_precarga_rodamientos", "falla_aceite", "", "NO", "NO", "", "L2 par de giro residual en 0.2 Nm acusa desgaste de pistas.")

    # --- L3 (15 casos) ---
    agregar("G37-L3-01", CLASE_37, "L3", "En un Toyota Corolla con caja mecánica de 5 velocidades se presenta un zumbido continuo que inicia a los 50 km/h y se vuelve ensordecedor a 90 km/h. Con el auto en el elevador y las ruedas motrices rodando a 80 km/h se utilizó estetoscopio electrónico de chasis: el canal del rodamiento de maza izquierda marca 28 dB, el de maza derecha marca 30 dB, pero el sensor montado directamente sobre el apoyo del rodamiento cónico de la corona del diferencial registra 84 dB con picos armónicos. Se desmontó el diferencial encontrándose la pista exterior del rodamiento lateral izquierdo con descascarillado severo (spalling) de 15 mm de extensión.", "TECNICO", "estetoscopio_chasis_84db_vs_30db", "estetoscopio_84db_diferencial_vs_30db_ruedas|spalling_15mm_pista_exterior|zumbido_90kmh", "rodamiento_rueda", "", "NO", "SI", "Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)", "L3 estetoscopio registra 84 dB en diferencial vs 30 dB en ruedas descartando maza.")
    agregar("G37-L3-02", CLASE_37, "L3", "Camioneta Nissan Frontier presenta aullido de alta frecuencia en transmisión bajo carga de aceleración entre 60 y 100 km/h en 4ta y 5ta marcha. Al soltar inmediatamente el pedal del acelerador a 90 km/h el aullido desaparece al 100% de forma instantánea. Se montó reloj comparador en la brida del piñón de ataque registrándose juego axial de 0.38 mm (especificación máxima 0.03 mm) debido al colapso del casquillo deformable de precarga, provocando que el piñón se desplace longitudinalmente al recibir par del motor.", "TALLER", "reloj_comparador_brida_pinon_0_38mm", "aullido_al_acelerar_desaparece_al_soltar|juego_axial_0_38mm_pinon|casquillo_deformable_colapsado", "rodajes_eje_primario", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L3 juego axial de 0.38 mm en piñón de ataque y silencio al soltar acelerador.")
    agregar("G37-L3-03", CLASE_37, "L3", "Inspección de grupo cónico de diferencial trasero: se aplicó compuesto marcador azul de Prusia sobre 6 dientes de la corona para evaluar el patrón de contacto bajo carga. La huella de contacto se encuentra completamente concentrada en el talón superior del flanco de tracción (contacto incorrecto tipo 'Heel') debido a que los rodamientos de apoyo de la caja de satélites se desgastaron 0.25 mm hacia la derecha, alejando la corona del piñón e incrementando el backlash a 0.42 mm (tolerancia 0.12 a 0.18 mm).", "TECNICO", "metrologia_backlash_0_42mm_huella_heel", "backlash_0_42mm_vs_0_15mm|huella_heel_azul_prusia|desgaste_rodamientos_0_25mm", "falla_cardan", "", "NO", "NO", "", "L3 backlash de 0.42 mm y huella Heel por desgaste de rodamientos.")
    agregar("G37-L3-04", CLASE_37, "L3", "Conductor reclama que al doblar en 'U' o girar en esquinas cerradas a baja velocidad se escucha un crujido metálico violento 'trac-trac-trac' y el auto tiende a frenarse. En la inspección se descartaron juntas homocinéticas exteriores e interiores comprobándose que el perno pasador de satélites del diferencial tiene una holgura radial de 1.4 mm con rozamiento directo contra la caja portacorona por desintegración total de las arandelas de empuje de bronce fosforado.", "TALLER", "desarme_satelites_planetarios_holgura", "crujido_al_doblar_u|perno_satelites_holgura_1_4mm|arandelas_bronce_desintegradas", "juntas_homocineticas", "", "NO", "SI", "Juntas homocineticas o palieres danados", "L3 perno de satélites con 1.4 mm de juego por arandelas desintegradas vs homocinética.")
    agregar("G37-L3-05", CLASE_37, "L3", "Hola maestro, tengo un Kia Rio mecánico. En pista zumba feo como si fuera rodaje de llanta. En la llantería cambiaron las dos mazas delanteras pero el ruido sigue idéntico. En el taller levantaron el carro en el puente, lo aceleraron a 70 km/h y con una varilla metálica en la oreja escucharon que el zumbido sale del centro donde entran los dos palieres a la caja.", "WHATSAPP", "diagnostico_kia_rio_elevador", "zumbido_persiste_post_cambio_mazas|varilla_localiza_ruido_centro_palieres", "rodamiento_rueda", "", "NO", "SI", "Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)", "L3 relato WhatsApp de zumbido central tras descartar mazas de rueda nuevas.")
    agregar("G37-L3-06", CLASE_37, "L3", "Análisis vibratorio FFT de acelerómetro montado en la campana de transmisión: se identifica pico espectral de 18.5 mm/s a frecuencia de 182 Hz coincidente de forma exacta con la frecuencia cinemática de paso de rodillos (BPFO - Ball Pass Frequency Outer Ring) de los rodamientos de apoyo de la corona a 80 km/h. Se constatan picaduras superficiales generalizadas por fatiga de contacto en la pista exterior del rodamiento cónico.", "TECNICO", "analisis_fft_bpfo_182hz", "pico_fft_182hz_bpfo_rodamientos|vibracion_18_5mms|pitting_pista_exterior", "falla_eje_primario", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L3 análisis FFT identifica frecuencia BPFO de 182 Hz en rodamiento de diferencial.")
    agregar("G37-L3-07", CLASE_37, "L3", "Vehículo 4WD presenta quejido agudo en desaceleración de 100 a 60 km/h con marcha engranada. Al pisar el pedal de embrague a 80 km/h el quejido cambia a un zumbido sordo pero NO desaparece (sigue girando con las ruedas). Al desmontar el conjunto del diferencial se comprobó que el rodamiento cónico de cabeza del piñón de ataque perdió el tratamiento térmico de cementación por circular con bajo nivel de lubricante.", "TALLER", "prueba_embrague_pisado_a_80kmh", "quejido_persiste_con_embrague_pisado|gira_con_ruedas|perdida_cementacion_pinon", "rodajes_eje_primario", "", "NO", "SI", "Rodajes de transmision manual o eje primario gastados", "L3 quejido persiste con embrague pisado confirmando diferencial vs primario.")
    agregar("G37-L3-08", CLASE_37, "L3", "Mi camioneta zumbaba como turbina en pista y en la curva a la derecha zumbaba igualito que a la izquierda. En el taller desarmaron la caja y los rodajes conicos donde se apoya la corona tenian las bolitas y las pistas todas comidas con huequitos negros de desgaste.", "ERROR_ORTOGRAFICO", "desarme_rodamientos_conicos", "zumba_igual_curva_derecha_izquierda|rodajes_conicos_huequitos_negros_pitting", "rodajes_rueda", "", "NO", "SI", "Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)", "L3 zumbido simétrico en curvas con pistas picadas con ortografía informal.")
    agregar("G37-L3-09", CLASE_37, "L3", "Medición de par de fricción de giro del conjunto piñón-corona con dinamómetro de aguja: resistencia de giro de 0.15 Nm (especificación 1.8 a 2.4 Nm) confirmando holgura total de rodamientos de precarga. La corona presenta oscilación lateral de 0.12 mm en el plano de giro por deformación de la brida portacorona tras fatiga de material.", "TECNICO", "par_friccion_0_15nm_salto_0_12mm", "par_friccion_0_15nm_vs_2_0nm|oscilacion_lateral_corona_0_12mm", "falla_aceite_caja", "", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L3 precarga caída a 0.15 Nm y oscilación de corona de 0.12 mm.")
    agregar("G37-L3-10", CLASE_37, "L3", "Buenas tardes, tengo una Duster 4x4. Al andar en autopista zumba fuerte abajo entre los dos asientos delanteros. Para descartar rodamientos de rueda moví el timón en zigzag a 70 km/h y el ruido no varió ni un poquito, sigue constante con la velocidad del carro.", "WHATSAPP", "prueba_zigzag_70kmh_duster", "zumbido_central_entre_asientos|prueba_zigzag_sin_cambio|ruido_constante_velocidad", "rodamiento_maza", "", "NO", "SI", "Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)", "L3 prueba de zigzag sin variación acústica descarta rodamientos de rueda.")
    agregar("G37-L3-11", CLASE_37, "L3", "Desgaste asimétrico en rodamientos cónicos de diferencial delantero en vehículo de tracción delantera: el rodamiento del lado izquierdo tiene desprendimiento de material en la pista interna debido a mayor carga de par motor por semieje corto, provocando desalineación del eje planetario de 0.18 mm.", "TECNICO", "desgaste_asimetrico_lado_semieje_corto", "desprendimiento_pista_interna_lado_corto|desalineacion_planetario_0_18mm", "falla_homocinetica", "", "NO", "SI", "Juntas homocineticas o palieres danados", "L3 desprendimiento en pista interna por sobrecarga en semieje corto.")
    agregar("G37-L3-12", CLASE_37, "L3", "Ruido de golpeteo cíclico a baja velocidad al avanzar en primera marcha sin acelerar: se constató que la corona del diferencial tiene un diente partido por fatiga tras impacto previo. El fragmento de acero de 12 mm quedó alojado en el fondo magnético del cárter sin bloquear el giro pero dañando el piñón de ataque.", "TALLER", "diente_corona_partido_fatiga", "golpeteo_ciclico_primera_baja_velocidad|diente_corona_partido_12mm|danos_pinon", "falla_caja_sincronizadores", "", "NO", "NO", "", "L3 diente partido en corona de diferencial genera golpe cíclico.")
    agregar("G37-L3-13", CLASE_37, "L3", "Análisis con tacómetro digital y estroboscopio: la frecuencia fundamental del zumbido en cabina es exactamente igual a 4.1 veces la velocidad angular de las ruedas delanteras, coincidiendo de forma matemática con la relación final del grupo reductor de diferencial (relación 4.10:1) y descartando rodamientos de rueda (1x velocidad de giro).", "TECNICO", "analisis_frecuencia_relacion_final_4_1", "frecuencia_zumbido_4_1x_ruedas|coincide_grupo_reductor_4_10_1|descarta_rueda_1x", "rodamiento_rueda", "", "NO", "SI", "Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)", "L3 frecuencia fundamental de 4.1x descarta matemáticamente rodamiento de rueda.")
    agregar("G37-L3-14", CLASE_37, "L3", "Zumbido que aumenta al acelerar y se apaga en retención en diferencial autoblocante tipo Torsen: las arandelas de empuje de los piñones helicoidales satélites presentan desgaste de 0.35 mm generando holgura axial que descentra el engrane helicoidal bajo transmisión de par positivo.", "TALLER", "diferencial_torsen_holgura_0_35mm", "diferencial_torsen_zumba_en_aceleracion|arandelas_desgaste_0_35mm|descentrado_par", "falla_transferencia", "", "NO", "NO", "", "L3 diferencial Torsen con holgura de 0.35 mm en engranes satélites.")
    agregar("G37-L3-15", CLASE_37, "L3", "Evaluación de vibración y rumorosidad en banco dinamométrico: a 90 km/h la fuerza acústica en la zona de diferencial alcanza 78 dBA con aceite de fábrica en nivel correcto. Al desmontar los rodamientos de salida se aprecia coloración azulada por sobrecalentamiento y microfisuras en la jaula de retención de rodillos.", "TECNICO", "dinamometro_78dba_jaula_fisurada", "nivel_ruido_78dba_vs_55dba|jaula_rodillos_fisurada|aceite_a_nivel_ok", "falta_aceite_caja", "", "NO", "SI", "Falta o degradacion de aceite de caja de cambios", "L3 78 dBA con aceite a nivel por fatiga estructural en jaula de rodillos.")

    return casos
