"""
Generador de casos de test ciego TEST10 para Clases 14 a 26 (MOTOR).
Exactamente 13 clases x 6 casos = 78 registros (2 L1, 2 L2, 2 L3 por clase).
Totalmente independientes, sin solapamiento léxico ni contaminación con Fase 10 o benchmarks.
"""

from typing import List, Dict
import sys
from pathlib import Path

sys.path.insert(0, str(Path("backend").resolve()))
from src.core.diagnostico.taxonomia_sistemas import FALLA_A_SISTEMA

keys = list(FALLA_A_SISTEMA.keys())

CLASE_01 = keys[0]
CLASE_02 = keys[1]
CLASE_03 = keys[2]
CLASE_04 = keys[3]
CLASE_06 = keys[5]
CLASE_09 = keys[8]
CLASE_11 = keys[10]
CLASE_12 = keys[11]

CLASE_14 = keys[13]  # Falla en actuador de turbocompresor o VGT en motores alemanes TSI / TFSI
CLASE_15 = keys[14]  # Fuga en mangueras de intercooler o turbocompresor danado
CLASE_16 = keys[15]  # Falla de correa dentada banada en aceite (Motor Ford 1.0 Dragon / GM Turbo)
CLASE_17 = keys[16]  # Falla en modulo de bomba de gasolina FSCM / PEM (Ford / Chevrolet)
CLASE_18 = keys[17]  # Falla en filtro de particulas DPF / FAP y sistema AdBlue DEF (Diesel Euro 5/6)
CLASE_19 = keys[18]  # Fuga o baja presion en sistema Common Rail Diesel (Camiones/Pickups)
CLASE_20 = keys[19]  # Falla en sistema Flex / Bi-combustible (Alcohol/Etanol)
CLASE_21 = keys[20]  # Falla en sensor de posicion de cigueal (CKP) o arbol de levas (CMP)
CLASE_22 = keys[21]  # Falla en sistema de control de emisiones evaporativas EVAP (canister o valvula de purga)
CLASE_23 = keys[22]  # Convertidor catalitico ineficiente u obstruido (DTC P0420 / P0430)
CLASE_24 = keys[23]  # Falla en regulador de presion de combustible o diafragma roto
CLASE_25 = keys[24]  # Falla en circuito o solenoide de inyector individual (DTC P0201 - P0208)
CLASE_26 = keys[25]  # Perdida de compresion en cilindro por valvulas pisadas o anillos desgastados

MACRO_MOTOR = "MOTOR"
FUENTE = "SINTETICO_TEST_CIEGO"


def obtener_test10_parte2(offset: int = 79) -> List[Dict[str, str]]:
    casos = []
    idx = offset

    def agregar(clase, nivel, texto, lenguaje, condicion, sp, sn, dtc, req_p, es_c, c_cont, obs):
        nonlocal idx
        reg_id = f"TEST10-{idx:04d}"
        grp_id = f"G-TEST10-{idx:04d}"
        casos.append({
            "id": reg_id,
            "id_grupo": grp_id,
            "clase_objetivo": clase,
            "macro_sistema": MACRO_MOTOR,
            "nivel_informacion": nivel,
            "texto_usuario": texto,
            "tipo_lenguaje": lenguaje,
            "condicion_operacion": condicion,
            "sintomas_presentes": sp,
            "sintomas_negados": sn,
            "dtc": dtc,
            "requiere_pregunta": req_p,
            "es_contrastivo": es_c,
            "clase_contrastiva": c_cont,
            "fuente": FUENTE,
            "observaciones": obs
        })
        idx += 1

    # --- CLASE 14: Actuador de turbo / VGT (TSI / TFSI) ---
    agregar(CLASE_14, "L1", "Aparece un rulo parpadeando en el cuadro y el auto queda sin pique.", "COTIDIANO", "ACELERACION_AUTOPISTA", "testigo_rulo_parpadea, sin_pique", "NO_REPORTA", "", "SI", "NO", "", "L1 rulo parpadea sin pique")
    agregar(CLASE_14, "L1", "de repente se queda sin empuje al querer rebasar y como que corta el turbo", "WHATSAPP", "ADELANTAMIENTO_CARRETERA", "corte_empuje_turbo", "NO_REPORTA", "", "SI", "NO", "", "L1 corta empuje al rebasar")
    agregar(CLASE_14, "L2", "En motor 1.4 TSI entra en modo de emergencia al superar 2500 RPM; código DTC P0234 de sobrepresión; el vástago de la compuerta wastegate electrónica tiene juego y se traba en caliente.", "TALLER", "EXIGENCIA_TURBO_TSI", "modo_emergencia_2500rpm, wastegate_se_traba, p0234", "fuga_manguera_intercooler", "P0234", "NO", "SI", CLASE_15, "L2 modo emergencia TSI wastegate trabada P0234")
    agregar(CLASE_14, "L2", "Actuador eléctrico de turbocompresor VGT no realiza el test de recorrido al dar contacto; varilla con resistencia mecánica dura al intentar moverla a mano.", "TALLER", "CONTACTO_INICIAL", "actuador_vgt_sin_recorrido_inicial, varilla_dura", "falla_cuerpo_aceleracion", "", "NO", "SI", keys[4], "L2 varilla VGT dura sin recorrido vs IAC")
    agregar(CLASE_14, "L3", "Diagnóstico con ODIS en Audi 2.0 TFSI: ajuste básico del actuador de presión de sobrealimentación (V465) aborta con error de tope final no alcanzado; lectura de tensión de sensor de posición marca 4.65V fuera de ventana nominal (3.8V a 4.2V); holgura de eje de mariposa de turbina en 1.1 mm.", "TECNICO", "ODIS_AJUSTE_BASICO_V465", "ajuste_basico_v465_falla, sensor_posicion_4_65v, holgura_eje_1_1mm", "fuga_intercooler", "P00AF", "NO", "SI", CLASE_15, "L3 ODIS ajuste V465 aborta sensor 4.65V")
    agregar(CLASE_14, "L3", "Monitoreo con osciloscopio en línea de control PWM del actuador turbo VGT: ciclo de trabajo de comando de ECU al 85% pero presión absoluta de múltiple MAP se queda en 1050 mbar (presión atmosférica sin ganancia boost); se verifica estanqueidad perfecta en mangueras de intercooler con 1.5 bar de aire a presión.", "TECNICO", "OSCILOSCOPIO_PWM_VGT_MAP", "map_1050mbar_sin_ganancia, pwm_85porciento_ok, mangueras_estancas", "fuga_mangueras_turbo", "P0299", "NO", "SI", CLASE_15, "L3 MAP 1050 mbar con PWM 85% mangueras estancas")

    # --- CLASE 15: Fuga mangueras intercooler / turbo dañado ---
    agregar(CLASE_15, "L1", "Al acelerar suena un soplido fuertísimo como si se desinflara una rueda debajo del capó.", "COTIDIANO", "ACELERACION_CON_CARGA", "soplido_fuerte_desinflado_capo", "NO_REPORTA", "", "SI", "NO", "", "L1 soplido fuerte al acelerar")
    agregar(CLASE_15, "L1", "suena como una sirena de ambulancia en el motor cuando entra el turbo", "WHATSAPP", "SUBIDA_RPM", "silbido_sirena_ambulancia_turbo", "NO_REPORTA", "", "SI", "NO", "", "L1 silbido sirena ambulancia")
    agregar(CLASE_15, "L2", "Humo negro en aceleraciones y silbido agudo continuo por el costado derecho; manguera de goma de salida del intercooler con raja longitudinal de 4 cm y mancha de aceite soplado.", "TALLER", "INSPECCION_BAJO_ELEVADOR", "raja_manguera_intercooler_4cm, silbido_agudo_humo_negro", "falla_actuador_turbo", "", "NO", "SI", CLASE_14, "L2 raja manguera intercooler 4cm vs actuador")
    agregar(CLASE_15, "L2", "Turbo emite aullido metálico a partir de 2000 RPM; al retirar el tubo de admisión se aprecia juego radial excesivo en la turbina rozando contra la caracola de aluminio.", "TALLER", "DESARME_TOMA_AIRE_TURBO", "turbina_roza_caracola, aullido_metalico_2000rpm", "falla_bomba_aceite", "", "NO", "SI", keys[9], "L2 turbina roza caracola juego radial")
    agregar(CLASE_15, "L3", "Prueba de estanqueidad en circuito de sobrealimentación con tapón presurizador a 1.2 bar: caída instantánea de presión con silbido sonoro en la unión engrapada de plástico y aluminio del intercooler; sensor MAP registra 1.1 bar absolutos frente a 2.2 bar demandados por la ECU a 3000 RPM en plena carga.", "TECNICO", "PRESURIZADOR_CIRCUITO_BOOST", "fuga_intercooler_union_plastico, map_1_1bar_vs_2_2bar_objetivo", "falla_actuador_vgt", "P0299", "NO", "SI", CLASE_14, "L3 presurizador 1.2 bar fuga grapa intercooler MAP bajo")
    agregar(CLASE_15, "L3", "Desmontaje de turbocompresor para peritaje técnico: eje de turbina con rotura por fatiga en la zona del collarín de lubricación por carbonización de aceite; laberinto de sellado destruido con fuga masiva de aceite hacia el conducto de escape; holgura axial de 1.85 mm con reloj palpador.", "TECNICO", "PERITAJE_DESARME_TURBO", "rotura_eje_turbina_fatiga, holgura_axial_1_85mm_reloj", "falla_reten_valvulas", "", "NO", "SI", keys[8], "L3 peritaje eje turbo roto holgura axial 1.85mm")

    # --- CLASE 16: Correa bañada en aceite (Ford Dragon / GM) ---
    agregar(CLASE_16, "L1", "Se encendió la luz de baja presión de aceite y el pedal de freno se puso duro como una roca.", "COTIDIANO", "MARCHA_NORMAL", "luz_aceite_encendida, freno_duro_piedra", "NO_REPORTA", "", "SI", "NO", "", "L1 luz aceite pedal freno duro")
    agregar(CLASE_16, "L1", "motor ford 3 cilindros suena feo abajo y salio alerta de presion de aceite baja parar motor", "WHATSAPP", "CIRCULACION_CIUDAD", "ford_3_cilindros_ruido_bajo, alerta_presion_aceite", "NO_REPORTA", "", "SI", "NO", "", "L1 ford 3 cil presion aceite")
    agregar(CLASE_16, "L2", "En motor Ford 1.0 Ecoboost / Dragon de 3 cilindros: el testigo de aceite titila al frenar; al destapar el tapón de llenado se observa la correa dentada con el lomo deshilachado y gomoso.", "TALLER", "INSPECCION_TAPA_ACEITE_DRAGON", "correa_humeda_deshilachada, testigo_aceite_titila", "falla_bomba_aceite", "", "NO", "SI", keys[9], "L2 correa humeda deshilachada Ford Dragon vs bomba")
    agregar(CLASE_16, "L2", "Pérdida de asistencia en servofreno y presión de aceite en 8 psi a 2000 RPM; colador del cárter taponado por restos de caucho y fibras sintéticas desprendidas de la correa de distribución.", "TALLER", "BAJADA_CARTER_MOTOR", "colador_carter_fibras_caucho, vacio_frenos_perdido", "falla_servofreno_booster", "", "NO", "SI", keys[28], "L2 colador tapado fibras caucho booster duro")
    agregar(CLASE_16, "L3", "Análisis de cárter desmontado en motor GM 1.2 Turbo: el chupador de la bomba de aceite tiene el 85% de su superficie tamiz bloqueada por hilachas de caucho EPDM degradado por uso de aceite sin especificación dexos1 gen3; medición de vacío en depresor mecánico arriesga 0.2 bar (nominal 0.8 bar) por falta de lubricación del eje.", "TECNICO", "INSPECCION_CHUPADOR_GM_TURBO", "chupador_85porciento_bloqueado_epdm, vacio_depresor_0_2bar", "falla_bomba_vacio", "", "NO", "SI", keys[28], "L3 chupador 85% bloqueado EPDM aceite incorrecto")
    agregar(CLASE_16, "L3", "Medición de ancho de correa dentada bañada en aceite: ancho nominal 16.0 mm reducido a 12.8 mm por pérdida de material en flancos laterales; dientes de arrastre con desprendimiento en tres sectores contiguos; presión de aceite en galería principal de 10 psi a 2500 RPM.", "TECNICO", "CALIBRE_PIE_REY_CORREA_HUMEDA", "ancho_correa_12_8mm_vs_16mm, dientes_desprendidos, 10psi_galeria", "falla_cadena_distribucion", "", "NO", "SI", keys[10], "L3 ancho correa 12.8 vs 16 mm dientes caidos")

    # --- CLASE 17: Módulo de bomba FSCM / PEM ---
    agregar(CLASE_17, "L1", "El carro se apaga de repente en marcha y después de 10 minutos vuelve a prender como si nada.", "COTIDIANO", "DETENCION_INTERMITENTE", "apaga_en_marcha_prende_luego", "NO_REPORTA", "", "SI", "NO", "", "L1 apaga intermitente prende luego")
    agregar(CLASE_17, "L1", "chevrolet se para en seco y no se oye cargar la bomba hasta que se enfria atras", "WHATSAPP", "PARADA_VIA", "chevrolet_no_carga_bomba_en_caliente", "NO_REPORTA", "", "SI", "NO", "", "L1 chevrolet bomba no carga en caliente")
    agregar(CLASE_17, "L2", "En camioneta Chevrolet Silverado: el motor se apaga en días calurosos; módulo de control de combustible (FSCM) ubicado sobre el eje trasero recalienta al tacto y corta la alimentación a la bomba.", "TALLER", "DIAGNOSTICO_MODULO_FSCM", "fscm_sobrecalienta_corta_bomba, camioneta_silverado", "falla_bomba_gasolina", "", "NO", "SI", CLASE_02, "L2 FSCM sobrecalienta Silverado vs bomba tanque")
    agregar(CLASE_17, "L2", "Código DTC U0109 por pérdida de comunicación con el módulo de la bomba de combustible; tensión en conector del FSCM presente pero salida trifásica a la bomba en 0V.", "TECNICO", "SCANNER_RED_CAN_FSCM", "dtc_u0109_sin_comunicacion_fscm, salida_bomba_0v", "falla_cableado_bomba", "U0109", "NO", "SI", CLASE_02, "L2 U0109 perdida comunicacion FSCM salida 0V")
    agregar(CLASE_17, "L3", "Diagnóstico de módulo PEM en Ford F-150: escáner registra DTC P069E (Fuel Pump Control Module Requested MIL); inspección con osciloscopio en bus CAN confirma paquetes de datos presentes pero la señal de accionamiento modulada hacia la bomba de baja presión cae a 0% cíclicamente al alcanzar 65°C de temperatura interna del módulo.", "TECNICO", "OSCILOSCOPIO_RED_FSCM_PWM", "dtc_p069e_fscm, ciclo_pwm_cae_0_a_65c, can_bus_ok", "falla_bomba_tanque", "P069E", "NO", "SI", CLASE_02, "L3 P069E FSCM Ford PWM cae a 0% a 65C")
    agregar(CLASE_17, "L3", "Prueba de banco en módulo de control de bomba de combustible: corrosión severa en la placa de circuito impreso por infiltración de agua a través del respiradero; al alimentar el módulo en banco a 12V el consumo sube a 4.5A en vacío con caída de regulador de 5V a 1.8V; bomba de gasolina sumergida probada con fuente externa funciona impecable con 4 bar.", "TECNICO", "BANCO_ELECTRONICA_FSCM", "corrosion_placa_fscm_agua, regulador_5v_cae_1_8v, bomba_tanque_ok", "bomba_gasolina_quemada", "", "NO", "SI", CLASE_02, "L3 placa FSCM corroida regulador cae 1.8V bomba ok")

    # --- CLASE 18: DPF / FAP y AdBlue DEF ---
    agregar(CLASE_18, "L1", "Apareció un dibujo de escape con humo en la pantalla y dice que el motor no arrancará en 500 km.", "COTIDIANO", "ALERTA_TABLERO_DIESEL", "alerta_arranque_imposible_500km, dibujo_escape", "NO_REPORTA", "", "SI", "NO", "", "L1 cuenta regresiva km arranque diesel")
    agregar(CLASE_18, "L1", "el carro diesel no pasa de 2000 vueltas y huele feisimo como a quimico quemado", "WHATSAPP", "MODO_PROTECCION_DIESEL", "diesel_limitado_2000rpm, olor_quimico", "NO_REPORTA", "", "SI", "NO", "", "L1 diesel no pasa 2000 rpm olor quimico")
    agregar(CLASE_18, "L2", "Vehículo diésel Euro 6 en modo degradado con DTC P2463 por acumulación de hollín en DPF; regeneración forzada con escáner rechazada por temperatura de gases insuficiente.", "TALLER", "INTENTO_REGENERACION_FORZADA", "dtc_p2463_hollin_dpf, regeneracion_rechazada_temperatura", "falla_catalizador_gasolina", "P2463", "NO", "SI", keys[22], "L2 P2463 hollin DPF regeneracion rechazada")
    agregar(CLASE_18, "L2", "Inyector de urea AdBlue cristalizado con depósito blanco endurecido en el tubo de escape; DTC P20EE por eficiencia baja de catalizador SCR.", "TALLER", "INSPECCION_INYECTOR_UREA", "inyector_adblue_cristalizado_blanco, dtc_p20ee", "falla_inyector_diesel", "P20EE", "NO", "SI", keys[18], "L2 inyector AdBlue cristalizado P20EE")
    agregar(CLASE_18, "L3", "Lectura de sensor de presión diferencial de DPF: en ralentí marca 42 mbar y a 2500 RPM escala a 280 mbar (umbral máximo tolerable 85 mbar); masa de cenizas calculada en 64 gramos excediendo el límite de vida útil del filtro; sondas de temperatura de escape EGT antes y después del DPF registran 620°C coherentes.", "TECNICO", "PRESION_DIFERENCIAL_DPF", "delta_dpf_280mbar_a_2500rpm, cenizas_64g_excede_limite", "falla_sensor_presion_diferencial", "P242F", "NO", "SI", CLASE_19, "L3 delta DPF 280 mbar cenizas 64g sensor EGT ok")
    agregar(CLASE_18, "L3", "Diagnóstico de módulo dosificador de AdBlue Bosch Denoxtronic 2.2: prueba de presión en línea de urea arroja 2.1 bar frente a 5.0 bar nominales por desgaste de membrana de bomba de solenoide; calentador de tanque DEF registra resistencia de 2.2 Ohmios conforme a 12V; sensor NOx aguas abajo clavado en 450 ppm.", "TECNICO", "PRESION_UREA_DENOXTRONIC", "presion_adblue_2_1bar_vs_5_0bar, nox_450ppm_alto", "falla_sensor_nox", "P20A0", "NO", "SI", CLASE_19, "L3 presion urea 2.1 vs 5 bar bomba Denoxtronic")

    # --- CLASE 19: Common Rail Diesel ---
    agregar(CLASE_19, "L1", "La camioneta diésel demora muchísimo en prender en las mañanas y bota humo blanco.", "COTIDIANO", "ARRANQUE_FRIO_DIESEL", "demora_mucho_arranque_humo_blanco", "NO_REPORTA", "", "SI", "NO", "", "L1 diesel demora prender manana")
    agregar(CLASE_19, "L1", "se apago el motor petrolero al acelerar fuerte en subida y prendio el check", "WHATSAPP", "EXIGENCIA_SUBIDA_DIESEL", "apago_al_acelerar_subida_check", "NO_REPORTA", "", "SI", "NO", "", "L1 apaga al acelerar subida diesel")
    agregar(CLASE_19, "L2", "Presión de riel Common Rail requerida de 1400 bar pero la real solo alcanza 850 bar bajo aceleración plena; código DTC P0087; válvula de control de succión SCV con agarrotamiento intermitente.", "TALLER", "LECTURA_PARAMETROS_COMMON_RAIL", "riel_850bar_vs_1400bar_pedido, dtc_p0087_diesel, valvula_scv_agarrotada", "falla_bomba_gasolina", "P0087", "NO", "SI", CLASE_02, "L2 riel 850 vs 1400 bar SCV pegada P0087")
    agregar(CLASE_19, "L2", "Prueba de retorno de inyectores piezoeléctricos Common Rail con probetas: inyector 3 llena la probeta en 20 segundos por fuga excesiva en válvula de control; arranque requiere más de 8 giros de motor.", "TALLER", "PROBETAS_RETORNO_COMMON_RAIL", "fuga_retorno_excesiva_inyector_3, arranque_prolongado", "falla_filtro_petroleo", "", "NO", "SI", CLASE_03, "L2 probetas retorno inyector 3 fuga alta")
    agregar(CLASE_19, "L3", "Monitoreo con escáner de presión de riel durante arranque: alcanza apenas 140 bar en 5 segundos de rotación de motor (umbral mínimo para habilitar inyección es 200 bar a 250 RPM); prueba de bypass en válvula reguladora DRV revela fuga de 120 ml/min hacia retorno; bomba de alta presión Bosch CP4 sin viruta en sensor de temperatura.", "TECNICO", "PRESION_ARRANQUE_COMMON_RAIL", "presion_arranque_140bar_vs_200bar, fuga_drv_120ml_min, cp4_sin_viruta", "falla_bomba_alta_presion", "P0087", "NO", "SI", keys[23], "L3 arranque 140 bar vs 200 bar fuga DRV 120ml")
    agregar(CLASE_19, "L3", "Osciloscopio en válvula dosificadora de entrada MPROP a 2000 RPM: comando PWM en 38% mientras sensor de riel acusa fluctuaciones violentas de presión entre 600 bar y 1650 bar (delta de 1050 bar de rizado inestable); filtro de combustible diésel con presencia de agua libre detectada en sensor decantador.", "TECNICO", "OSCILOGRAMA_MPROP_RIZADO_RIEL", "rizado_inestable_riel_600_1650bar, pwm_mprop_38porciento, agua_decantador", "falla_inyector_individual", "P0088", "NO", "SI", keys[24], "L3 oscilograma MPROP rizado 600 a 1650 bar agua en filtro")

    # --- CLASE 20: Sistema Flex / Bi-combustible (Etanol) ---
    agregar(CLASE_20, "L1", "Cargué combustible barato y al día siguiente el auto no quiere prender en frío.", "COTIDIANO", "MANANA_POST_CARGA", "no_prende_frio_post_carga", "NO_REPORTA", "", "SI", "NO", "", "L1 no prende frio combustible barato")
    agregar(CLASE_20, "L1", "en las mananas falla feo y huele a alcohol crudo hasta que calienta 10 minutos", "WHATSAPP", "CALENTAMIENTO_MOTOR", "olor_alcohol_crudo_falla_manana", "NO_REPORTA", "", "SI", "NO", "", "L1 olor alcohol falla manana")
    agregar(CLASE_20, "L2", "Vehículo Flex (Etanol/Gasolina) con dificultad severa de arranque en frío a 14°C; sistema de precalentamiento de combustible de arranque en frío no activa resistencia en flauta.", "TALLER", "ARRANQUE_TEMPERATURA_BAJA", "precalentador_etanol_inoperativo_14c, arranque_dificil_flex", "falla_bujias_encendido", "", "NO", "SI", CLASE_01, "L2 precalentador etanol inoperativo a 14C vs bujias")
    agregar(CLASE_20, "L2", "Escáner registra porcentaje de etanol inferido en 85% cuando el tanque tiene gasolina pura al 90%; motor marcha ahogado con corrección de combustible STFT en -25%.", "TECNICO", "PARAMETROS_VIVO_ETANOL_VIRTUAL", "etanol_inferido_85porciento_vs_real_10, stft_menos_25", "falla_sensor_oxigeno", "P0172", "NO", "SI", CLASE_04, "L2 etanol inferido 85% vs 10% real STFT -25%")
    agregar(CLASE_20, "L3", "Diagnóstico de sensor físico de composición de combustible (Flex Fuel Sensor): osciloscopio en pin de señal mide frecuencia fija de 50 Hz correspondiente a 0% de etanol mientras refractómetro óptico manual en muestra de combustible extraída del riel arroja 72% de etanol anhidro; sensor descalibrado internamente.", "TECNICO", "SENSOR_COMPOSICION_FRECUENCIA", "frecuencia_50hz_0porciento_vs_72porciento_refractometro, sensor_flex_defectuoso", "falla_sensor_maf", "P0178", "NO", "SI", CLASE_03, "L3 sensor composicion 50Hz 0% vs 72% refractometro")
    agregar(CLASE_20, "L3", "Inspección de inyectores en motor E100 Flex: acumulación de residuo gomoso de sulfatos y acidez de etanol en las agujas de cierre provocando goteo estático de 4 gotas/min a 3.5 bar; prueba de compresión pareja en 185 psi descarta fugas mecánicas.", "TECNICO", "BANCO_GOTEO_ESTATICO_FLEX", "goteo_estatico_inyectores_etanol, acidez_sulfatos, compresion_185psi", "falla_bomba_combustible", "", "NO", "SI", CLASE_03, "L3 goteo estatico 4 gotas min acidez etanol")

    # --- CLASE 21: Sensor CKP o CMP ---
    agregar(CLASE_21, "L1", "El motor se apaga de golpe como si le cortaran la corriente y no da chispa.", "COTIDIANO", "APAGADO_REPENTINO", "apaga_de_golpe_sin_chispa", "NO_REPORTA", "", "SI", "NO", "", "L1 apaga de golpe sin chispa")
    agregar(CLASE_21, "L1", "a veces le cuesta como diez segundos encender y la aguja de rpm no se mueve nada al dar arranque", "WHATSAPP", "INTENTO_ARRANQUE_LARGO", "aguja_rpm_no_mueve_arranque_largo", "NO_REPORTA", "", "SI", "NO", "", "L1 aguja RPM muerta en arranque")
    agregar(CLASE_21, "L2", "Motor se apaga al tomar temperatura de 85°C y no vuelve a prender hasta que se enfría; sensor CKP inductivo mide 950 Ohmios en frío y en caliente entra en circuito abierto (infinito).", "TALLER", "PRUEBA_TERMICA_SENSOR_CKP", "ckp_abierto_en_caliente_infinito, apaga_a_85c", "falla_bobina_encendido", "P0335", "NO", "SI", CLASE_01, "L2 CKP abierto en caliente P0335 vs bobina")
    agregar(CLASE_21, "L2", "Arranque prolongado de 8 segundos; al encender funciona en modo de sincronización de emergencia por código DTC P0340 de árbol de levas; señal de sensor CMP perdida.", "TECNICO", "MODO_EMERGENCIA_ARRANQUE", "dtc_p0340_cmp_perdido, arranque_prolongado_8s", "falla_cadena_distribucion", "P0340", "NO", "SI", CLASE_11, "L2 P0340 CMP senal perdida vs cadena")
    agregar(CLASE_21, "L3", "Osciloscopio digital en sensor CKP inductivo: amplitud de señal pico a pico de apenas 0.4V a 250 RPM durante el arranque (especificación mínima 1.2V pico a pico); entrehierro entre sensor y rueda fónica medido con galga en 2.4 mm (especificación 0.8 mm a 1.2 mm) por soporte doblado tras cambio de embrague.", "TECNICO", "OSCILOSCOPIO_ENTREHIERRO_CKP", "amplitud_0_4v_vs_1_2v_oem, entrehierro_2_4mm_vs_1_0mm", "falla_bateria", "P0335", "NO", "SI", keys[47], "L3 CKP amplitud 0.4V entrehierro 2.4 mm P0335")
    agregar(CLASE_21, "L3", "Diagnóstico de sensor CMP de efecto Hall: señal de onda cuadrada de 0-5V presente pero al acelerar a 3200 RPM la señal colapsa a 0V continuo por fisura interna del circuito integrado del sensor por vibración; bobinas y chispa 100% operativas al excitar con simulador externo.", "TECNICO", "SIMULADOR_SENALES_HALL_CMP", "colapso_cmp_a_3200rpm_0v, chispa_ok_con_simulador", "falla_computadora_pcm", "P0341", "NO", "SI", CLASE_12, "L3 CMP colapsa a 0V a 3200 RPM P0341")

    # --- CLASE 22: Sistema EVAP ---
    agregar(CLASE_22, "L1", "Se prende el check engine cada vez que lleno el tanque de gasolina a tope.", "COTIDIANO", "POST_LLENADO_TANQUE", "check_al_llenar_tanque_completo", "NO_REPORTA", "", "SI", "NO", "", "L1 check al llenar tanque")
    agregar(CLASE_22, "L1", "huele a nafta cerca de la rueda trasera y hace un soplido fuerte al abrir la tapa de gasolina", "WHATSAPP", "ABRIR_TAPA_GASOLINA", "soplido_vacio_tapa_gasolina, olor_nafta_trasero", "NO_REPORTA", "", "SI", "NO", "", "L1 soplido tapa gasolina olor")
    agregar(CLASE_22, "L2", "Motor arranca ahogado y con temblor únicamente justo después de cargar combustible en la gasolinera; válvula de purga de canister trabada abierta deja pasar vapores sin control.", "TALLER", "POST_DESPACHO_GASOLINA", "arranque_ahogado_post_carga, valvula_purga_trabada_abierta", "falla_bomba_gasolina", "P0441", "NO", "SI", CLASE_02, "L2 purga canister trabada abierta P0441")
    agregar(CLASE_22, "L2", "Código DTC P0442 de fuga pequeña en sistema de emisiones evaporativas; prueba de humo en boca de llenado no muestra fugas en mangueras pero la tapa de combustible tiene el sello de goma cuarteado.", "TECNICO", "PRUEBA_HUMO_EVAP_P0442", "dtc_p0442_fuga_pequena, sello_goma_tapa_cuarteado", "falla_sensor_oxigeno", "P0442", "NO", "SI", CLASE_04, "L2 P0442 fuga pequena sello tapa cuarteado")
    agregar(CLASE_22, "L3", "Presurización con máquina de humo y nitrógeno a 0.05 bar en circuito EVAP: sensor de presión del tanque FTP registra caída de 14 inH2O a 0 inH2O en 45 segundos; humo sale por la junta de soldadura ultrasónica del cuerpo del canister de carbón activado; válvula de venteo vent valve sella con 12V conforme.", "TECNICO", "MAQUINA_HUMO_NITROGENO_EVAP", "humo_junta_canister_carbon, caida_presion_ftp_45s, vent_valve_ok", "fuga_tanque_combustible", "P0455", "NO", "SI", keys[23], "L3 maquina humo fuga en canister P0455")
    agregar(CLASE_22, "L3", "Comprobación de solenoide de purga de canister con bomba de vacío manual Mityvac: al aplicar 15 inHg de vacío con solenoide desconectado el vacío cae a 0 inHg de inmediato (asiento de teflón rayado con fuga de paso); resistencia eléctrica de la bobina de 26 Ohmios dentro de rango.", "TECNICO", "MITYVAC_VACIO_PURGA_CANISTER", "valvula_purga_no_retiene_vacio, bobina_26_ohmios_ok", "falla_cuerpo_aceleracion", "P0444", "NO", "SI", keys[4], "L3 Mityvac valvula purga fuga vacio P0444")

    # --- CLASE 23: Convertidor catalítico ineficiente ---
    agregar(CLASE_23, "L1", "El motor se siente amarrado, no tiene fuerza y el piso del auto calienta como un horno.", "COTIDIANO", "MARCHA_PROLONGADA", "piso_caliente_como_horno, motor_amarrado", "NO_REPORTA", "", "SI", "NO", "", "L1 piso caliente como horno sin fuerza")
    agregar(CLASE_23, "L1", "hace un cascabel como piedritas sueltas en el silenciador al acelerar en vacio", "WHATSAPP", "ACELERACION_EN_VACIO", "cascabel_piedritas_sueltas_escape", "NO_REPORTA", "", "SI", "NO", "", "L1 piedritas sueltas en escape")
    agregar(CLASE_23, "L2", "Testigo Check Engine encendido fijo con código DTC P0420 banco 1; sensor de oxígeno downstream (B1S2) oscila idéntico al sensor upstream en vez de entregar señal plana.", "TALLER", "MONITOREO_CATALIZADOR_P0420", "dtc_p0420_eficiencia_catalizador, b1s2_oscila_igual_b1s1", "falla_sensor_oxigeno", "P0420", "NO", "SI", CLASE_04, "L2 P0420 B1S2 oscila igual que B1S1 vs O2")
    agregar(CLASE_23, "L2", "El auto no pasa de 80 km/h en subidas y se ahoga; manómetro instalado en la rosca del sensor de oxígeno registra 4.5 psi de contrapresión en el escape a 2500 RPM (máximo 1.0 psi).", "TALLER", "PRUEBA_CONTRAPRESION_ESCAPE", "contrapresion_escape_4_5psi, no_pasa_80kmh", "falla_bomba_combustible", "", "NO", "SI", CLASE_02, "L2 contrapresion escape 4.5 psi vs bomba")
    agregar(CLASE_23, "L3", "Termografía infrarroja FLIR en convertidor catalítico de tres vías: temperatura en la entrada mide 310°C y en la salida mide 295°C (delta negativo de -15°C; un catalizador activo debe registrar salida entre 30°C y 60°C más caliente que la entrada); cámara boroscópica expone panal de cerámica fundido y quebrado.", "TECNICO", "TERMOGRAFIA_FLIR_CATALIZADOR", "delta_flir_negativo_menos15c, panal_ceramico_fundido", "falla_sensor_o2_b2", "P0420", "NO", "SI", CLASE_04, "L3 FLIR delta negativo panal ceramico fundido P0420")
    agregar(CLASE_23, "L3", "Lectura simultánea de sensores lambda con osciloscopio de 2 canales a 2500 RPM: sensor 1 cicla de 0.1V a 0.85V y sensor 2 copia la misma amplitud y frecuencia con retardo de fase de apenas 40 ms (capacidad de almacenamiento de oxígeno OSC nula por desprendimiento de metales preciosos platino/rodio).", "TECNICO", "OSCILOSCOPIO_SONDAS_OSC", "sensor_2_copia_sensor_1_amplitud, capacidad_osc_nula", "falla_mezcla_rica", "P0420", "NO", "SI", CLASE_04, "L3 oscilograma S2 copia S1 capacidad OSC nula P0420")

    # --- CLASE 24: Regulador de presión de combustible ---
    agregar(CLASE_24, "L1", "Al sacar la manguerita de vacío que va al motor sale un chorro de nafta.", "COTIDIANO", "REVISION_MOTOR_PARADO", "chorro_gasolina_manguera_vacio", "NO_REPORTA", "", "SI", "NO", "", "L1 chorro nafta manguera vacio")
    agregar(CLASE_24, "L1", "el carro arranca con olor a gasolina cruda y humareda negra por el escape", "WHATSAPP", "ARRANQUE_EN_FRIO", "arranque_olor_gasolina_humo_negro", "NO_REPORTA", "", "SI", "NO", "", "L1 olor gasolina humo negro arranque")
    agregar(CLASE_24, "L2", "Presión en el riel de combustible clavada en 65 psi en ralentí y no baja a 40 psi al conectar el vacío; diafragma interno del regulador roto absorbe gasolina por la toma de admisión.", "TALLER", "PRUEBA_REGULADOR_VACIO", "presion_fija_65psi_no_baja_con_vacio, diafragma_roto", "falla_bomba_gasolina", "", "NO", "SI", CLASE_02, "L2 presion 65 psi fija diafragma roto vs bomba")
    agregar(CLASE_24, "L2", "Bujías completamente empapadas en combustible y código DTC P0172 mezcla rica banco 1; al desconectar la manguera de vacío del regulador se comprueba goteo continuo de nafta hacia el colector.", "TECNICO", "DESCONEXION_LINEA_VACIO_REGULADOR", "goteo_gasolina_toma_vacio, dtc_p0172_bujias_mojadas", "falla_sensor_oxigeno", "P0172", "NO", "SI", CLASE_04, "L2 goteo toma vacio P0172 bujias mojadas")
    agregar(CLASE_24, "L3", "Diagnóstico con bomba Mityvac y manómetro en riel de inyección: al aplicar 18 inHg de vacío al regulador la presión de riel no varía en absoluto (se mantiene en 4.5 bar estables vs caída esperada a 3.8 bar); membrana de nitrilo perforada con fuga fluídica hacia la cámara de vacío; LTFT en -24% a ralentí.", "TECNICO", "MITYVAC_MANOMETRO_COMBINADO", "presion_no_varia_con_18inhg, membrana_nitrilo_perforada, ltft_menos_24", "falla_inyectores_goteo", "P0172", "NO", "SI", keys[24], "L3 Mityvac 18 inHg no varia 4.5 bar membrana perforada")
    agregar(CLASE_24, "L3", "Medición de presión de combustible tras apagar el motor: la presión residual en el riel cae de 3.5 bar a 0 bar en 12 segundos con válvula de retención de bomba de combustible descartada con pinza de estrangulamiento; retorno del regulador drena continuamente combustible sin retener presión residual.", "TECNICO", "PRUEBA_PRESION_RESIDUAL_RIEL", "presion_residual_cae_0bar_12s, retorno_drena_continuo", "falla_bomba_combustible", "", "NO", "SI", CLASE_02, "L3 caida presion residual 0 bar en 12s retorno drena")

    # --- CLASE 25: Circuito o solenoide de inyector individual ---
    agregar(CLASE_25, "L1", "El motor anda en tres cilindros parejito, tiembla entero y no empuja nada.", "COTIDIANO", "MARCHA_URBANA", "anda_en_tres_cilindros, tiembla_entero", "NO_REPORTA", "", "SI", "NO", "", "L1 anda en 3 cilindros tiembla")
    agregar(CLASE_25, "L1", "luz de check engine prendida y codigo de falla en el inyector numero tres", "WHATSAPP", "SCANNER_CASERO", "codigo_inyector_tres, check_prendido", "NO_REPORTA", "", "SI", "NO", "", "L1 codigo inyector 3 check")
    agregar(CLASE_25, "L2", "Fallo constante en cilindro 3 con código DTC P0203 de circuito de inyector abierto; al medir con multímetro en los bornes del inyector 3 la resistencia marca infinito (circuito abierto).", "TALLER", "MULTIMETRO_RESISTENCIA_INYECTOR", "dtc_p0203_circuito_abierto, inyector_3_resistencia_infinita", "falla_bobina_encendido", "P0203", "NO", "SI", CLASE_01, "L2 P0203 inyector 3 resistencia infinita vs bobina")
    agregar(CLASE_25, "L2", "Conector eléctrico del inyector número 1 con traba rota y pines con sulfatación verde; el cilindro 1 deja de inyectar intermitentemente al vibrar en empedrado.", "TALLER", "INSPECCION_CABLEADO_MOTOR", "conector_inyector_1_sulfatado, falla_al_vibrar_empedrado", "falla_bujias", "P0201", "NO", "SI", CLASE_01, "L2 conector inyector 1 sulfatado P0201")
    agregar(CLASE_25, "L3", "Osciloscopio digital en pin de control de inyector 2: señal de disparo de masa de ECU presente con pulso de 3.2 ms pero sin pico inductivo de autoinducción (0V de contra-fuerza electromotriz vs 65V nominales); resistencia de bobina de inyector en 1.1 Ohmios (cortocircuito interno vs 14.5 Ohmios en cilindros 1, 3 y 4).", "TECNICO", "OSCILOSCOPIO_INYECTOR_PICO_INDUCTIVO", "sin_pico_inductivo_inyector_2, resistencia_1_1_ohmios_corto", "falla_bobina_ignicion", "P0202", "NO", "SI", CLASE_01, "L3 oscilograma inyector 2 sin pico inductivo 1.1 ohms")
    agregar(CLASE_25, "L3", "Prueba de consumo de corriente con pinza amperimétrica en inyector número 4: corriente máxima de solo 0.15A con pulso de disparo presente (nominal 0.95A a 12V); caída de tensión de 4.8V en el cable de alimentación positiva por empalme sulfatado en mazo principal; inyector en banco funciona a 14.2 Ohmios correctos.", "TECNICO", "PINZA_AMPERIMETRICA_CORRIENTE_INYECTOR", "corriente_0_15a_baja, caida_tension_4_8v_cableado, inyector_ok", "falla_inyector_mecanico", "P0204", "NO", "SI", CLASE_03, "L3 pinza amperimetrica inyector 4 caida 4.8V en arnes")

    # --- CLASE 26: Pérdida de compresión / válvulas pisadas ---
    agregar(CLASE_26, "L1", "El auto perdió fuerza por completo, sopla por la varilla del aceite y vibra como un tractor.", "COTIDIANO", "MARCHA_LLANA", "sopla_por_varilla_aceite, vibra_como_tractor", "NO_REPORTA", "", "SI", "NO", "", "L1 sopla varilla aceite tractor")
    agregar(CLASE_26, "L1", "cuando doy arranque suena disparejo como que en una vuelta gira sin fuerza", "WHATSAPP", "GIRAR_LLAVE", "arranque_disparejo_sin_fuerza", "NO_REPORTA", "", "SI", "NO", "", "L1 arranque disparejo una vuelta libre")
    agregar(CLASE_26, "L2", "Motor a gas GLP con 120,000 km presenta fallo constante en ralentí; prueba de compresión revela cilindro 1 con 60 psi y los demás con 175 psi; holgura de válvulas en cilindro 1 en 0.00 mm (válvulas pisadas).", "TALLER", "GALGA_ESPEDORES_TAQUES", "compresion_cilindro_1_60psi, valvula_pisada_0_00mm, glp", "falla_bobina_encendido", "", "NO", "SI", CLASE_01, "L2 compresion 60 psi valvula pisada GLP vs bobina")
    agregar(CLASE_26, "L2", "Fallo de encendido en cilindro 4 que no se soluciona cambiando bujía ni bobina; prueba de compresión húmeda arroja 70 psi tanto seca como con aceite, confirmando fuga por asiento de válvula quemada.", "TALLER", "COMPRESION_SECA_Y_HUMEDA", "compresion_70psi_seca_y_humeda, fuga_valvula_quemada", "falla_anillos_piston", "", "NO", "SI", CLASE_09, "L2 compresion 70 psi seca y humeda valvula quemada")
    agregar(CLASE_26, "L3", "Prueba de estanqueidad neumática de cilindros (Leakdown test) a 90 psi: cilindro 2 acusa 65% de fuga estática; el aire presurizado escapa audiblemente por el múltiple de escape desmontado; boroscopio confirma válvula de escape del cilindro 2 con muesca por quemadura térmica; compresión en 85 psi.", "TECNICO", "LEAKDOWN_TEST_ESCAPE", "fuga_65porciento_por_escape, valvula_escape_quemada_muesca", "falla_empaque_culata", "P0302", "NO", "SI", CLASE_06, "L3 leakdown 65% escape soplado valvula quemada")
    agregar(CLASE_26, "L3", "Ensayo de compresión relativa con pinza amperimétrica y osciloscopio durante arranque: cilindro 3 muestra una caída de corriente del 42% respecto a los cilindros adyacentes; prueba neumática revela flujo de aire saliendo por la varilla de medición de aceite y tapa de cárter por rotura de falda y tabique de pistón.", "TECNICO", "COMPRESION_RELATIVA_OSCILOSCOPIO", "compresion_relativa_cae_42porciento, soplido_carter_tabique_roto", "falla_inyector", "P0303", "NO", "SI", CLASE_25, "L3 compresion relativa -42% tabique de piston roto")

    return casos
