"""
Generador de casos de test ciego TEST10 para Clases 01 a 13 (MOTOR).
Exactamente 13 clases x 6 casos = 78 registros (2 L1, 2 L2, 2 L3 por clase).
Totalmente independientes, sin solapamiento léxico ni contaminación con Fase 10 o benchmarks.
"""

from typing import List, Dict
import sys
from pathlib import Path

sys.path.insert(0, str(Path("backend").resolve()))
from src.core.diagnostico.taxonomia_sistemas import FALLA_A_SISTEMA

keys = list(FALLA_A_SISTEMA.keys())

CLASE_01 = keys[0]   # Falla en bujias o bobinas de encendido (misfire)
CLASE_02 = keys[1]   # Bomba de gasolina quemada o con baja presion
CLASE_03 = keys[2]   # Inyectores sucios o filtro de combustible obstruido
CLASE_04 = keys[3]   # Falla en sensor de oxigeno o mezcla rica
CLASE_05 = keys[4]   # Cuerpo de aceleracion o valvula IAC sucia
CLASE_06 = keys[5]   # Empaque de culata soplado o danado
CLASE_07 = keys[6]   # Falla en termostato o motoventilador de radiador
CLASE_08 = keys[7]   # Fuga en mangueras de refrigerante o radiador picado
CLASE_09 = keys[8]   # Consumo de aceite por desgaste de anillos o retenes
CLASE_10 = keys[9]   # Baja presion de aceite o bomba de aceite defectuosa
CLASE_11 = keys[10]  # Faja o cadena de distribucion destensada o con salto de punto
CLASE_12 = keys[11]  # Falla en sistema de sincronizacion variable de valvulas (VVT / VVT-i / Valvetronic)
CLASE_13 = keys[12]  # Falla de descarbonizacion e inyeccion directa GDI (acumulacion de carbon en valvulas)

MACRO_MOTOR = "MOTOR"
FUENTE = "SINTETICO_TEST_CIEGO"


def obtener_test10_parte1(offset: int = 1) -> List[Dict[str, str]]:
    casos = []
    idx = offset

    def agregar(clase, nivel, texto, lenguaje, condicion, sp, sn, dtc, req_p, es_c, c_cont, obs):
        nonlocal idx
        reg_id = f"TEST10-{idx:04d}"
        grp_id = f"G-TEST10-{idx:04d}"
        casos.append({
            "id": reg_id,
            "id_grupo": grp_id,
            "clase_objetivo": clase,
            "macro_sistema": MACRO_MOTOR,
            "nivel_informacion": nivel,
            "texto_usuario": texto,
            "tipo_lenguaje": lenguaje,
            "condicion_operacion": condicion,
            "sintomas_presentes": sp,
            "sintomas_negados": sn,
            "dtc": dtc,
            "requiere_pregunta": req_p,
            "es_contrastivo": es_c,
            "clase_contrastiva": c_cont,
            "fuente": FUENTE,
            "observaciones": obs
        })
        idx += 1

    # --- CLASE 01: Bujías / Bobinas (misfire) ---
    agregar(CLASE_01, "L1", "El motor tironea bastante feo cuando quiero pasar a otro carro.", "COTIDIANO", "ACELERACION_ADELANTAMIENTO", "tironeo_fuerte_al_acelerar", "NO_REPORTA", "", "SI", "NO", "", "L1 tironeo en aceleracion")
    agregar(CLASE_01, "L1", "tiembla mucho el carro cuando paro en la luz roja y parpadea la luz amarilla del motor", "WHATSAPP", "RALENTI_SEMAFORO", "temblor_ralenti, check_parpadea", "NO_REPORTA", "", "SI", "NO", "", "L1 temblor semaforo check parpadea")
    agregar(CLASE_01, "L2", "Motor de 4 cilindros vibra en subidas pronunciadas en 3ra marcha; al acelerar a fondo cabecea pero en bajada rueda suave sin jaloneos.", "TALLER", "CARGA_EN_PENDIENTE", "vibracion_bajo_carga, cabeceo_aceleracion_fondo", "falla_caja_cambios", "", "NO", "SI", keys[25], "L2 cabeceo en subida vs inyector")
    agregar(CLASE_01, "L2", "Al exigir potencia en carretera se siente corte de chispa en cilindro 2 con código P0302; bujía con electrodo quemado a 1.4 mm.", "TECNICO", "EXIGENCIA_CARRETERA", "corte_chispa_cilindro_2, bujia_abierta_1_4mm", "falla_presion_gasolina", "P0302", "NO", "SI", CLASE_02, "L2 corte chispa P0302 bujia abierta")
    agregar(CLASE_01, "L3", "Osciloscopio automotriz en primario de bobina individual (COP): cilindro 3 acusa tiempo de quemado de solo 0.65 ms con picos de tensión oscilantes de 420V; se descarta inyector con prueba de pulso de 2.8 ms normal y compresión en 175 psi.", "TECNICO", "DIAGNOSTICO_OSCILOSCOPIO_COP", "tiempo_quemado_corto_0_65ms, pico_420v_bobina_3", "falla_inyector, falla_compresion", "P0303", "NO", "SI", keys[24], "L3 oscilograma bobina COP cilindro 3 vs inyector")
    agregar(CLASE_01, "L3", "Registro de contadores de fallo en tiempo real: cilindro 4 registra 42 misfires por ciclo a 2200 RPM bajo carga dynamométrica; aislamiento de capuchón de silicona perforado con fuga de alta tensión hacia culata; compresión pareja de 180 psi en los 4 cilindros.", "TECNICO", "PRUEBA_BANCO_DINAMOMETRICO", "misfires_cilindro_4_contador, capuchon_aislamiento_perforado", "falla_baja_compresion", "P0304", "NO", "SI", keys[25], "L3 contador misfires cilindro 4 capuchon perforado")

    # --- CLASE 02: Bomba de gasolina ---
    agregar(CLASE_02, "L1", "El auto da vueltas y vueltas el arranque pero no llega a encender para nada.", "COTIDIANO", "INTENTO_ARRANQUE", "arranque_gira_pero_no_enciende", "NO_REPORTA", "", "SI", "NO", "", "L1 gira no prende")
    agregar(CLASE_02, "L1", "se apago andando despues de un bache y ya no se escucha el zumbidito del tanque al poner contacto", "WHATSAPP", "APAGADO_EN_MARCHA", "apaga_en_marcha, sin_zumbido_tanque", "NO_REPORTA", "", "SI", "NO", "", "L1 sin zumbido tanque tras bache")
    agregar(CLASE_02, "L2", "Vehículo pierde fuerza gradualmente tras 20 minutos de marcha hasta detenerse; al enfriarse 1 hora vuelve a encender; presión en riel cae de 45 a 15 psi con temperatura.", "TALLER", "POST_CALENTAMIENTO", "perdida_gradual_fuerza, presion_cae_15psi_en_caliente", "falla_bobina_ignicion", "", "NO", "SI", CLASE_01, "L2 presion cae a 15 psi en caliente vs bobina")
    agregar(CLASE_02, "L2", "Con tanque por debajo de 1/4 el motor sufre ahogos en curvas rápidas; medición directa en bomba sumergida marca 1.8 bar en vez de los 3.5 bar nominales.", "TALLER", "BAJO_NIVEL_TANQUE", "ahogos_curva_tanque_bajo, presion_1_8bar_bomba", "filtro_obstruido", "", "NO", "SI", CLASE_03, "L2 tanque bajo 1.8 bar vs filtro")
    agregar(CLASE_02, "L3", "Manómetro acoplado al puerto Schrader: al dar contacto la presión sube a 2.1 bar pero al acelerar a 3000 RPM desciende abruptamente a 1.2 bar; consumo eléctrico de la bomba en amperímetro de pinza es de 2.2A (especificación 6.0A a 7.5A por conmutador de inducido desgastado); pulso de inyección en 3.1 ms.", "TECNICO", "PRUEBA_PRESION_AMPERAJE", "presion_1_2bar_aceleracion, consumo_bomba_2_2a_bajo", "falla_pulso_inyeccion", "P0087", "NO", "SI", keys[23], "L3 manometro 1.2 bar pinza amperimetrica 2.2A")
    agregar(CLASE_02, "L3", "Ensayo de caudal de combustible en probeta graduada: entrega apenas 450 ml en 30 segundos (tolerancia mínima 950 ml); tensión de alimentación en el conector de la bomba es de 13.8V estables, descartando caída de línea en relé; solenoide y chispa en bujías 100% operativos.", "TECNICO", "BANCO_CAUDAL_PROBETA", "caudal_450ml_vs_950ml_minimo, tension_13_8v_ok", "falla_rele_bomba, falla_chispa", "", "NO", "SI", keys[16], "L3 probeta caudal 450ml 13.8V estables")

    # --- CLASE 03: Inyectores sucios / filtro obstruido ---
    agregar(CLASE_03, "L1", "Siento que el carro responde con pereza cuando le piso el acelerador a fondo.", "COTIDIANO", "ACELERACION_MEDIA", "respuesta_perezosa_acelerador", "NO_REPORTA", "", "SI", "NO", "", "L1 respuesta perezosa")
    agregar(CLASE_03, "L1", "tose un poco al salir en primera como si le faltara comida al motor", "WHATSAPP", "SALIDA_PRIMERA", "tos_en_primera, sensacion_falta_combustible", "NO_REPORTA", "", "SI", "NO", "", "L1 tose en primera")
    agregar(CLASE_03, "L2", "En ralentí el motor funciona parejo pero al exigir 3500 RPM en carretera se producen cortes suaves y tirones sostenidos; filtro de combustible con 60,000 km sin cambiar.", "TALLER", "ALTA_VELOCIDAD_CRUCERO", "cortes_a_3500rpm, filtro_combustible_antiguo", "falla_bujias", "", "NO", "SI", CLASE_01, "L2 cortes a 3500 rpm filtro 60k km")
    agregar(CLASE_03, "L2", "Ajuste de combustible a largo plazo (LTFT) en +18% bajo carga moderada; prueba de limpieza por ultrasonido requerida tras hallar residuo gomoso en toberas.", "TECNICO", "LECTURA_DATOS_VIVO", "ltft_positivo_18porciento, toberas_con_goma", "falla_sensor_oxigeno", "", "NO", "SI", CLASE_04, "L2 LTFT +18% residuo en toberas vs O2")
    agregar(CLASE_03, "L3", "Banco de pruebas de inyectores multipunto: a 3 bar de presión constante, inyector 1 rinde 145 ml/min, inyector 2 rinde 110 ml/min (desbalance del 24% fuera de norma SAE j1832); patrón de abanico deformado en chorro cónico cerrado; presión de bomba de 3.8 bar en riel totalmente conforme.", "TECNICO", "BANCO_PROBETAS_INYECTORES", "desbalance_24porciento_inyector_2, patron_abanico_deforme", "baja_presion_bomba", "", "NO", "SI", CLASE_02, "L3 banco probetas desbalance 24% patron deformado")
    agregar(CLASE_03, "L3", "Diagnóstico de caída de presión en línea de combustible: manómetro diferencial antes y después del filtro de combustible acusa delta de 1.4 bar a 2500 RPM (filtro colmatado por sedimento ferroso); bomba de tanque genera 4.2 bar antes del filtro; chispa y bobinas con oscilograma impecable.", "TECNICO", "PRESION_DIFERENCIAL_FILTRO", "delta_filtro_1_4bar_colmatado, bomba_4_2bar_ok", "falla_chispa_bobinas", "", "NO", "SI", CLASE_02, "L3 delta filtro 1.4 bar bomba 4.2 bar ok")

    # --- CLASE 04: Sensor de oxígeno / mezcla rica ---
    agregar(CLASE_04, "L1", "El tubo de escape bota un olor fuertísimo como a nafta cruda y gasta el doble.", "COTIDIANO", "MARCHA_URBANA", "olor_combustible_crudo_escape, consumo_excesivo", "NO_REPORTA", "", "SI", "NO", "", "L1 olor nafta escape consumo alto")
    agregar(CLASE_04, "L1", "saco las bujias y estan totalmente negras de carbon seco y carbonilla", "WHATSAPP", "REVISION_TALLER", "bujias_negras_carbon_seco", "NO_REPORTA", "", "SI", "NO", "", "L1 bujias negras carbon seco")
    agregar(CLASE_04, "L2", "Humo negro por el escape en aceleradas bruscas; bujías con hollín seco aterciopelado; sensor de oxígeno banco 1 sensor 1 no oscila y queda clavado en 0.92V.", "TALLER", "INSPECCION_ESCANER", "humo_negro_aceleracion, o2_clavado_0_92v", "falla_empaque_culata", "P0172", "NO", "SI", CLASE_06, "L2 humo negro O2 clavado 0.92V P0172")
    agregar(CLASE_04, "L2", "Consumo de combustible aumentó de 10 km/L a 6 km/L; escáner acusa DTC P0131 sensor de oxígeno circuito bajo; al desconectar sensor la ECU entra en lazo abierto.", "TECNICO", "PRUEBA_LAZO_ABIERTO", "consumo_disparado, dtc_p0131_o2_bajo", "falla_catalizador", "P0131", "NO", "SI", keys[22], "L2 consumo alto P0131 lazo abierto")
    agregar(CLASE_04, "L3", "Lectura de flujo de datos PID: sensor O2 B1S1 entrega tensión fija de 0.88V constante sin ciclar a 2000 RPM; corrección de combustible de corto plazo (STFT) en -22% intentando empobrecer; prueba de fuga de vacío negativa con máquina de humo y presión de combustible clavada en 3.5 bar conforme.", "TECNICO", "DATOS_EN_VIVO_STFT", "o2_fijo_0_88v_sin_ciclar, stft_menos_22porciento", "fuga_vacio, alta_presion_riel", "P0172", "NO", "SI", keys[23], "L3 O2 fijo 0.88V STFT -22% humo negativo")
    agregar(CLASE_04, "L3", "Verificación con osciloscopio automotriz en sensor de oxígeno circonio de 4 cables: tiempo de conmutación rico-a-pobre es de 980 ms (tolerancia máxima OEM 300 ms, sensor contaminado por silicio y envejecido); resistencia del calefactor interno mide 14 Ohmios conforme a 20°C.", "TECNICO", "OSCILOSCOPIO_SONDA_LAMBDA", "conmutacion_lenta_980ms_vs_300ms, calefactor_14_ohmios_ok", "falla_calefactor_o2", "", "NO", "SI", CLASE_03, "L3 conmutacion lenta 980ms sensor agotado")

    # --- CLASE 05: Cuerpo de aceleración / válvula IAC ---
    agregar(CLASE_05, "L1", "Llego al semáforo en neutro y el motor se apaga de golpe si no lo bombeo.", "COTIDIANO", "DETENCION_SEMAFORO", "apaga_al_frenar_neutro, requiere_bombear", "NO_REPORTA", "", "SI", "NO", "", "L1 apaga en neutro semaforo")
    agregar(CLASE_05, "L1", "el ralenti sube y baja solo como loco entre 800 y 1600 vueltas", "WHATSAPP", "MOTOR_CALIENTE_PARADO", "ralenti_oscilante_800_1600rpm", "NO_REPORTA", "", "SI", "NO", "", "L1 ralenti oscilante 800 1600")
    agregar(CLASE_05, "L2", "Mariposa electrónica con borde obstruido por carbonilla aceitosa; al encender el aire acondicionado el motor no compensa RPM y se cala de inmediato.", "TALLER", "CONEXION_AC_CARGA", "mariposa_carbonilla, no_compensa_rpm_con_ac", "falla_compresor_ac", "", "NO", "SI", keys[53], "L2 mariposa carbonilla no compensa vs AC")
    agregar(CLASE_05, "L2", "Ralentí inestable tras desconectar la batería; cuerpo de aceleración motorizado perdió el aprendizaje de tope inferior; DTC P0507 por ralentí superior a lo esperado.", "TECNICO", "POST_DESCONEXION_BATERIA", "perdida_calibracion_tope_ralenti, dtc_p0507", "falla_bateria", "P0507", "NO", "SI", keys[47], "L2 perdida aprendizaje tope P0507")
    agregar(CLASE_05, "L3", "Escaneo de porcentaje de apertura de mariposa TPS relativo en ralentí: 6.8% en reposo cuando el valor nominal calibrado es 2.1% a 3.0%; acumulación de barniz negro de 0.8 mm en garganta de aluminio bloquea el paso de aire calibrado; motor paso a paso de mariposa consume 1.1A conforme.", "TECNICO", "MONITOREO_TPS_RELATIVO", "tps_relativo_6_8_vs_2_5porciento, barniz_0_8mm_garganta", "falla_motor_mariposa", "P0505", "NO", "SI", CLASE_01, "L3 TPS 6.8% vs 2.5% barniz 0.8mm garganta")
    agregar(CLASE_05, "L3", "Diagnóstico de válvula IAC de 4 pines en motor multipunto: prueba de resistencia de bobinas A y B arroja 52 Ohmios idénticos; inspección con boroscopio evidencia vástago cónico trabado mecánicamente por depósito endurecido de vapores PCV; vacío de admisión de 19 inHg en marcha normal descarta fugas externas.", "TECNICO", "BOROSCOPIO_VALVULA_IAC", "iac_conico_trabado_pcv, bobinas_52_ohmios_ok, vacio_19inhg", "fuga_vacio_admision", "", "NO", "SI", keys[21], "L3 IAC conico trabado PCV bobinas 52 ohms")

    # --- CLASE 06: Empaque de culata soplado ---
    agregar(CLASE_06, "L1", "Hierve el depósito de agua y se llena de burbujas como si fuera champaña.", "COTIDIANO", "DETENIDO_POST_MARCHA", "burbujeo_deposito_refrigerante, ebullicion", "NO_REPORTA", "", "SI", "NO", "", "L1 burbujas deposito champaña")
    agregar(CLASE_06, "L1", "sale humo blanco espeso por el cano de escape con olor dulzon a refrigerante", "WHATSAPP", "ARRANQUE_EN_FRIO", "humo_blanco_dulzon_escape", "NO_REPORTA", "", "SI", "NO", "", "L1 humo blanco olor dulzon")
    agregar(CLASE_06, "L2", "Presión excesiva en mangueras de radiador que se ponen duras como piedra a los 5 minutos de encender; la tapa del aceite tiene pasta café con leche (emulsión).", "TALLER", "CALENTAMIENTO_MOTOR", "mangueras_petreas, emulsion_cafe_con_leche_tapa", "falla_termostato", "", "NO", "SI", CLASE_07, "L2 mangueras petreas emulsion tapa aceite vs termostato")
    agregar(CLASE_06, "L2", "El motor recalienta solo en carretera abierta a velocidad; nivel de refrigerante baja sin que haya gotas en el piso; prueba química de CO2 en el vaso da positivo virando a amarillo.", "TECNICO", "PRUEBA_RUTA_ALTA_VELOCIDAD", "recalienta_en_ruta, refrigerante_consume, test_co2_positivo", "fuga_radiador", "", "NO", "SI", CLASE_08, "L2 test quimico CO2 amarillo sin fuga externa")
    agregar(CLASE_06, "L3", "Prueba de estanqueidad de cilindros con detector de fugas neumático a 100 psi: al presurizar el cilindro 3 se aprecia un flujo masivo de burbujas en el radiador destapado y una caída de presión del 45%; compresión del cilindro 3 en 90 psi frente a 170 psi en cilindro 1; bujía 3 lavada con vapor de agua.", "TECNICO", "TEST_FUGAS_NEUMATICO_CILINDROS", "fuga_45porciento_burbujas_radiador, compresion_cilindro_3_90psi, bujia_lavada", "falla_anillos", "", "NO", "SI", keys[25], "L3 leakdown test 45% burbujas radiador cilindro 3")
    agregar(CLASE_06, "L3", "Análisis con detector de gases de combustión por infrarrojo en boca de radiador: presencia de hidrocarburos no quemados superior a 180 ppm en el cuello de llenado; desmontaje revela rotura de aro de fuego metálico de culata entre cilindros 2 y 3; planitud de culata con alabeo de 0.12 mm (límite 0.05 mm).", "TECNICO", "ANALIZADOR_GASES_CUELLO_RADIADOR", "hc_180ppm_cuello_radiador, aro_fuego_roto, alabeo_0_12mm", "falla_bomba_agua", "", "NO", "SI", CLASE_07, "L3 HC 180 ppm cuello radiador alabeo 0.12mm")

    # --- CLASE 07: Termostato o motoventilador ---
    agregar(CLASE_07, "L1", "La aguja de temperatura se sube al rojo vivo cuando me quedo parado en el tráfico.", "COTIDIANO", "CONGESTION_TRAFICO", "aguja_temperatura_al_rojo_trafico", "NO_REPORTA", "", "SI", "NO", "", "L1 aguja al rojo en trafico")
    agregar(CLASE_07, "L1", "prendo el carro y la aguja de temperatura nunca sube se queda abajo del todo en carretera", "WHATSAPP", "MARCHA_CARRETERA", "temperatura_no_sube_en_ruta, motor_frio", "NO_REPORTA", "", "SI", "NO", "", "L1 aguja nunca sube en ruta")
    agregar(CLASE_07, "L2", "El ventilador del radiador no gira nunca a pesar de que el motor llega a 108°C; fusible principal y relé de ventilador probados en banco con continuidad correcta.", "TALLER", "PRUEBA_BANCO_RELE", "electroventilador_no_activa_108c, rele_fusible_ok", "falla_empaque_culata", "", "NO", "SI", CLASE_06, "L2 ventilador no gira a 108C rele ok vs culata")
    agregar(CLASE_07, "L2", "En autopista la temperatura baja a 60°C y gasta mucha gasolina con DTC P0128; manguera superior del radiador se calienta desde el primer minuto con motor frío.", "TECNICO", "RUTA_ALTA_VELOCIDAD", "termostato_abierto_p0128, manguera_caliente_desde_arranque", "falla_sensor_oxigeno", "P0128", "NO", "SI", CLASE_04, "L2 P0128 termostato trabado abierto")
    agregar(CLASE_07, "L3", "Termografía infrarroja FLIR en circuito de refrigeración: radiador registra 99°C en entrada superior pero solo 38°C en tanque inferior con manguera de retorno fría; termostato con elemento de cera trabado en posición cerrada; resistencia del sensor ECT mide 185 Ohmios a 100°C totalmente calibrada.", "TECNICO", "TERMOGRAFIA_FLIR_RADIADOR", "delta_flir_99c_a_38c_radiador, termostato_cerrado_cera, sensor_ect_ok", "falla_sensor_ect, radiador_picado", "", "NO", "SI", CLASE_08, "L3 termografia 99C vs 38C termostato cerrado")
    agregar(CLASE_07, "L3", "Diagnóstico de motoventilador con módulo PWM integrado: escáner solicita activación al 90% y señal oscilográfica de 12V con ciclo de trabajo PWM de 90% llega al pin de control; motor eléctrico del electroventilador presenta consumo de 0.0A por escobillas de carbón totalmente pulverizadas.", "TECNICO", "CONTROL_PWM_MOTOFAN", "pwm_90porciento_ok, ventilador_0a_escobillas_muertas", "falla_computadora_pcm", "", "NO", "SI", keys[46], "L3 PWM 90% ok consumo 0.0A escobillas gastadas")

    # --- CLASE 08: Fuga de refrigerante / radiador picado ---
    agregar(CLASE_08, "L1", "Encuentro un charco verde brillante en el piso del garaje debajo de la trompa.", "COTIDIANO", "ESTACIONADO_GARAJE", "charco_verde_debajo_motor", "NO_REPORTA", "", "SI", "NO", "", "L1 charco verde bajo trompa")
    agregar(CLASE_08, "L1", "humo blanco con vapor saliendo de la parrilla delantera y huele a dulce caliente", "WHATSAPP", "DETENIDO_POST_MARCHA", "vapor_parrilla_delantera, olor_dulce", "NO_REPORTA", "", "SI", "NO", "", "L1 vapor parrilla olor dulce")
    agregar(CLASE_08, "L2", "Goteo constante por la abrazadera de la manguera inferior del radiador al presurizar el circuito; depósito de reserva se vacía cada 2 días pero el motor no recalienta en viajes cortos.", "TALLER", "INSPECCION_FOSO", "goteo_manguera_inferior_abrazadera, vaciado_deposito_2_dias", "falla_culata", "", "NO", "SI", CLASE_06, "L2 goteo abrazadera manguera inferior vs culata")
    agregar(CLASE_08, "L2", "Fisura en el tanque plástico lateral del radiador de aluminio; al tomar temperatura el agua sale en chorro fino tipo aerosol pulverizado hacia el alternador.", "TALLER", "MOTOR_TEMPERATURA_REGIMEN", "fisura_tanque_plastico_radiador, chorro_pulverizado", "falla_termostato", "", "NO", "SI", CLASE_07, "L2 fisura tanque plastico radiador chorro fino")
    agregar(CLASE_08, "L3", "Prueba de presurización con bomba hidrostática manual en el cuello del radiador a 1.2 bar: manómetro registra caída de presión a 0.4 bar en 90 segundos; trazador fluorescente UV revela fluorescencia en el núcleo de aluminio del radiador por corrosión galvánica con picadura de 0.6 mm.", "TECNICO", "PRESURIZADOR_SISTEMA_REFRIGERANTE", "caida_1_2_a_0_4bar_90s, fluorescencia_uv_nucleo_aluminio", "empaque_culata_soplado", "", "NO", "SI", CLASE_06, "L3 bomba presion 1.2 bar fuga UV nucleo radiador")
    agregar(CLASE_08, "L3", "Inspección técnica de tubería rígida de bypass de bomba de agua: tubo de acero estampado muestra perforación por óxido debajo de la curva de fijación; fuga de 180 ml/min a régimen de temperatura; se comprueba aceite de motor sin emulsión y prueba de CO2 en refrigerante 100% negativa.", "TECNICO", "PRUEBA_BANCO_FUGAS_HIDRO", "tubo_bypass_oxidado_perforado, fuga_180ml_min, co2_negativo", "falla_empaque_culata", "", "NO", "SI", CLASE_06, "L3 tubo bypass perforado 180 ml min CO2 negativo")

    # --- CLASE 09: Consumo de aceite por anillos/retenes ---
    agregar(CLASE_09, "L1", "Tengo que echarle un litro de aceite cada semana porque se lo traga todito.", "COTIDIANO", "USO_DIARIO", "consumo_1_litro_aceite_semanal", "NO_REPORTA", "", "SI", "NO", "", "L1 litro aceite por semana")
    agregar(CLASE_09, "L1", "bota una humareda azulada por el escape cuando acelero en las mananas", "WHATSAPP", "ARRANQUE_MANANA", "humo_azul_aceleracion_manana", "NO_REPORTA", "", "SI", "NO", "", "L1 humo azul manana")
    agregar(CLASE_09, "L2", "Humo azul denso visible en el retrovisor al acelerar tras haber estado detenido en ralentí; bujías con costra aceitosa brillante y nivel de varilla al mínimo cada 800 km.", "TALLER", "POST_RALENTI_PROLONGADO", "humo_azul_post_ralenti, bujias_costra_aceite, consumo_800km", "fuga_aceite_externa", "", "NO", "SI", CLASE_10, "L2 humo azul post ralenti bujias con costra")
    agregar(CLASE_09, "L2", "Consumo de 1.5 cuartos de aceite en 1000 km sin manchas en el suelo; compresión seca arroja 140 psi y con una cucharada de aceite sube a 180 psi (anillos desgastados).", "TECNICO", "TEST_COMPRESION_HUMEDA", "compresion_seca_140_humeda_180psi, consumo_1_5qt_1000km", "falla_valvulas", "", "NO", "SI", keys[25], "L2 compresion seca 140 humeda 180 psi anillos")
    agregar(CLASE_09, "L3", "Inspección endoscópica de cilindros con cámara HD de 5.5 mm: paredes del cilindro 2 muestran pérdida completa del bruñido original (honing) con espejo pulido brillante y pistón con depósito carbonoso aceitoso húmedo de 1.5 mm; prueba de estanqueidad de guías de válvula con retenes de viton endurecidos por ciclo térmico.", "TECNICO", "BOROSCOPIO_HD_CILINDROS", "perdida_brunido_pared_cilindro, retenes_viton_cristalizados", "falla_turbo", "", "NO", "SI", keys[14], "L3 boroscopio pared espejo sin brunido retenes duros")
    agregar(CLASE_09, "L3", "Desmontaje de múltiples de escape y bujías: roscas y asientos de válvulas de admisión presentan escurrimiento de aceite crudo descendente desde las guías de válvula; juego radial de vástago de válvula en micrómetro arroja 0.18 mm (tolerancia límite 0.08 mm); consumo medido en dinamómetro de 1.2 L por cada 1000 km.", "TECNICO", "MICROMETRO_JUEGO_GUIAS", "juego_radial_guia_0_18mm_vs_0_08mm, escurrimiento_aceite_valvula", "falla_anillos_compresion", "", "NO", "SI", keys[25], "L3 micrometro juego guias 0.18mm escurrimiento valvula")

    # --- CLASE 10: Baja presión de aceite ---
    agregar(CLASE_10, "L1", "Se prende el testigo de la alcuza de aceite en el tablero y suena un cascabeleo metálico feo.", "COTIDIANO", "RALENTI_CALIENTE", "testigo_aceite_encendido, cascabeleo_metalico", "NO_REPORTA", "", "SI", "NO", "", "L1 testigo alcuza cascabeleo")
    agregar(CLASE_10, "L1", "en caliente la luz del aceite titila cuando me paro en una esquina", "WHATSAPP", "DETENCION_ESQUINA", "luz_aceite_titila_en_caliente", "NO_REPORTA", "", "SI", "NO", "", "L1 luz aceite titila caliente")
    agregar(CLASE_10, "L2", "En frío el motor suena sereno pero al llegar a 90°C la luz de presión de aceite titila en ralentí y los taqués hidráulicos comienzan a sonar como máquina de coser.", "TALLER", "REGIMEN_TERMICO_CALIENTE", "luz_aceite_titila_90c, taques_suenan_maquina_coser", "falla_cadena_distribucion", "", "NO", "SI", CLASE_11, "L2 luz titila 90C taques descargados vs cadena")
    agregar(CLASE_10, "L2", "Nivel de aceite en varilla correcto y aceite nuevo 10W-40 colocado; manómetro mecánico en switch de presión marca apenas 6 psi en ralentí a 850 RPM (mínimo 15 psi).", "TALLER", "MANOMETRO_MECANICO_ACEITE", "presion_6psi_ralenti_vs_15psi_oem, nivel_aceite_correcto", "falla_sensor_presion_aceite", "", "NO", "SI", keys[20], "L2 manometro 6 psi ralenti nivel aceite ok")
    agregar(CLASE_10, "L3", "Comprobación manométrica en galería principal de lubricación: 8 psi en ralentí (800 RPM) y solo 22 psi a 3000 RPM a 95°C de temperatura de aceite (especificación técnica 35-50 psi); desmontaje de cárter expone colador de chupador de bomba parcialmente obstruido con silicona y viruta de cojinete; holgura de engranajes de bomba en 0.22 mm.", "TECNICO", "MANOMETRO_GALERIA_LUBRICACION", "presion_8psi_ralenti_22psi_3000rpm, colador_chupador_tapado_silicona", "falla_sensor_presion", "", "NO", "SI", CLASE_09, "L3 manometro 8 psi ralenti colador chupador tapado")
    agregar(CLASE_10, "L3", "Inspección de cojinetes de biela con micrómetro y Plastigage: holgura de aceite en muñón de biela número 3 marca 0.085 mm (límite máximo 0.045 mm por desgaste de metal antifricción babbit); válvula de alivio de presión de bomba de aceite con resorte vencido y embolo rayado que fuga internamente.", "TECNICO", "PLASTIGAGE_COJINETES_BIELA", "plastigage_0_085mm_vs_0_045mm, valvula_alivio_bomba_rayada", "falla_bomba_aceite", "", "NO", "SI", keys[25], "L3 Plastigage 0.085mm valvula alivio vencida")

    # --- CLASE 11: Faja o cadena de distribución ---
    agregar(CLASE_11, "L1", "Se escucha un zumbido y cascabeleo fuerte por la tapa de plástico del costado del motor.", "COTIDIANO", "RALENTI_FRIO", "zumbido_cascabeleo_costado_motor", "NO_REPORTA", "", "SI", "NO", "", "L1 ruido costado motor")
    agregar(CLASE_11, "L1", "se me apago el auto de golpe y cuando doy arranque gira demasiado liviano y rapido", "WHATSAPP", "ROTURA_EN_MARCHA", "apago_de_golpe, arranque_gira_liviano_rapido", "NO_REPORTA", "", "SI", "NO", "", "L1 apago de golpe gira liviano")
    agregar(CLASE_11, "L2", "Ruido de golpeteo metálico rítmico en la tapa de distribución al acelerar a 1500 RPM; tensor hidráulico extendido al máximo sin amortiguar la cadena.", "TALLER", "DESARME_TAPA_DISTRIBUCION", "golpeteo_tapa_distribucion, tensor_hidraulico_al_limite", "falla_vvt", "", "NO", "SI", CLASE_12, "L2 golpeteo tensor al limite vs VVT")
    agregar(CLASE_11, "L2", "Motor arranca con dificultad y tiene marcha irregular; códigos de sincronización DTC P0016 presentes por cadena saltada un diente respecto a marcas de calado.", "TECNICO", "INSPECCION_PUNTOS_CALADO", "dtc_p0016_desfase, cadena_saltada_un_diente", "falla_sensor_ckp", "P0016", "NO", "SI", keys[20], "L2 P0016 cadena saltada 1 diente vs CKP")
    agregar(CLASE_11, "L3", "Captura simultánea con osciloscopio de doble canal de sensores CKP inductivo y CMP Hall: el flanco descendente del CMP se produce 18 grados de cigüeñal retrasado respecto a la ventana de referencia de la rueda fónica (calado desfasado por estiramiento de cadena de distribución de 7 mm); compresiones parejas en 165 psi descartan válvulas dobladas.", "TECNICO", "OSCILOSCOPIO_CKP_CMP_DESFASE", "cmp_retrasado_18_grados_vs_ckp, estiramiento_cadena_7mm", "falla_sensor_cmp, valvulas_dobladas", "P0016", "NO", "SI", CLASE_12, "L3 oscilograma CKP CMP desfase 18 grados estiramiento 7mm")
    agregar(CLASE_11, "L3", "Comprobación de calado con herramientas fijadoras OEM: los pasadores de bloqueo de los árboles de levas no entran en sus ranuras posteriores cuando el pistón 1 se encuentra en PMS con reloj comparador; patín guía de teflón quebrado en su apoyo inferior; tensor con trinquete trabado en el diente 11.", "TECNICO", "RELOJ_COMPARADOR_PMS_CALADO", "pasadores_calado_no_entran_pms, patin_teflon_quebrado", "falla_eje_levas", "", "NO", "SI", CLASE_12, "L3 pasadores no entran PMS patin quebrado tensor diente 11")

    # --- CLASE 12: Sistema VVT / VVT-i / Valvetronic ---
    agregar(CLASE_12, "L1", "El auto pierde toda la fuerza arriba de 3000 vueltas como si se ahogara.", "COTIDIANO", "ALTA_REVOLUCION", "perdida_potencia_altas_vueltas", "NO_REPORTA", "", "SI", "NO", "", "L1 perdida fuerza sobre 3000 rpm")
    agregar(CLASE_12, "L1", "hace un traqueteo seco como matraca justo al encender por 3 segundos y luego se calla", "WHATSAPP", "ARRANQUE_EN_FRIO", "traqueteo_matraca_arranque_3_segundos", "NO_REPORTA", "", "SI", "NO", "", "L1 matraca 3 segundos arranque")
    agregar(CLASE_12, "L2", "Traqueteo en la polea variadora de admisión al arrancar en frío por falta de traba del pin hidráulico; código DTC P0011 de posición avanzada de árbol de levas.", "TALLER", "ARRANQUE_FRIO_POLEA", "traqueteo_polea_vvt_arranque, dtc_p0011", "falla_cadena_distribucion", "P0011", "NO", "SI", CLASE_11, "L2 traqueteo polea pin destrabado P0011")
    agregar(CLASE_12, "L2", "Solenoide electrohidráulico de control VVT atascado por lodo de aceite quemado; malla de microfiltro del árbol de levas totalmente tapada impidiendo el avance angular.", "TALLER", "INSPECCION_VALVULA_OCV", "solenoide_vvt_atascado_barniz, microfiltro_tapado", "falla_presion_aceite", "", "NO", "SI", CLASE_10, "L2 solenoide VVT atascado microfiltro tapado")
    agregar(CLASE_12, "L3", "Diagnóstico de actuador VVT con escáner y osciloscopio: activación bidireccional PWM del solenoide al 60% no produce variación en el ángulo de desfase de levas (permanece fijo en 0.0° vs 25.0° objetivo); resistencia de la bobina solenoide en 8.2 Ohmios conforme pero émbolo trabado; presión de aceite en culata a 35 psi normal.", "TECNICO", "PRUEBA_BIDIRECCIONAL_VVT", "pwm_60porciento_angulo_fijo_0, bobina_8_2_ohmios_ok, embolo_trabado", "falla_presion_aceite", "P0012", "NO", "SI", CLASE_11, "L3 prueba bidireccional VVT angulo 0 vs 25 grados")
    agregar(CLASE_12, "L3", "Inspección de motor de árbol excéntrico BMW Valvetronic: escáner registra DTC 2A67 (mecanismo Valvetronic sobrecarga); medición de consumo de corriente con pinza arroja 38 Amperios de pico con bloqueo mecánico del sinfín por desgaste de dientes en el eje intermedio de levas; sensor de ángulo de levas excéntricas 100% operativo.", "TECNICO", "VALVETRONIC_BMW_CORRIENTE", "valvetronic_sobrecarga_38a, desgaste_dientes_sinfin_excentrico", "falla_sensor_arbol_levas", "P0014", "NO", "SI", keys[20], "L3 Valvetronic sobrecarga 38A sinfin desgastado")

    # --- CLASE 13: Descarbonización e inyección directa GDI ---
    agregar(CLASE_13, "L1", "El carro se siente achanchado, lento para responder y tironea en frío al partir.", "COTIDIANO", "ARRANQUE_EN_FRIO", "motor_achanchado, tironea_en_frio", "NO_REPORTA", "", "SI", "NO", "", "L1 achanchado tironea en frio")
    agregar(CLASE_13, "L1", "gasta demasiado combustible y falla un cilindro al encender por las mananas", "WHATSAPP", "PRIMER_ARRANQUE", "falla_cilindro_manana, consumo_alto", "NO_REPORTA", "", "SI", "NO", "", "L1 falla cilindro manana consumo")
    agregar(CLASE_13, "L2", "Motor GDI de inyección directa con 85,000 km presenta fallos de encendido aleatorios en frío; desmontaje de múltiple de admisión revela costra negra espesa en las válvulas de admisión.", "TALLER", "DESMONTAJE_COLECTOR_GDI", "costra_carbonilla_valvulas_admision, misfires_en_frio", "falla_bobinas", "", "NO", "SI", CLASE_01, "L2 costra carbonilla valvulas admision GDI")
    agregar(CLASE_13, "L2", "Pérdida de potencia en altas RPM en motor turbo GDI; DTC P0300 múltiple; prueba de presión en riel arroja 150 bar perfectos pero el flujo de aire se encuentra estrangulado en admisión.", "TECNICO", "INSPECCION_ESCANER_GDI", "estrangulamiento_flujo_admision, p0300_aleatorio, 150bar_riel_ok", "falla_bomba_alta_presion", "P0300", "NO", "SI", CLASE_02, "L2 estrangulamiento admision P0300 riel 150 bar ok")
    agregar(CLASE_13, "L3", "Inspección con videoboroscopio articulado 360° en conductos de culata GDI: acumulación de carbón vitrificado de 3.2 mm de grosor sobre los vástagos y tulipas de válvulas de admisión de cilindros 2 y 3; reducción del área de pasaje de aire estimada en 40%; inyectores de alta presión probados con pulverización limpia a 180 bar.", "TECNICO", "BOROSCOPIO_360_VALVULAS_GDI", "carbon_vitrificado_3_2mm_tulipas, reduccion_pasaje_aire_40porciento", "falla_inyectores_gdi", "P0300", "NO", "SI", keys[24], "L3 boroscopio carbon 3.2mm tulipas admision reduccion 40%")
    agregar(CLASE_13, "L3", "Evaluación de masa de aire MAF en banco: a 4500 RPM WOT el sensor registra 88 g/s frente al valor teórico de 125 g/s por turbulencia generada por depósitos carbonosos en puertos de admisión; prueba de compresión pareja en 175 psi descarta pérdida mecánica en cilindros; limpieza con cáscara de nuez (walnut blasting) requerida.", "TECNICO", "FLUJO_MASA_AIRE_WOT", "maf_88g_s_vs_125g_s_teorico, carbon_puertos_admision, compresion_ok", "falla_sensor_maf", "", "NO", "SI", CLASE_01, "L3 MAF 88 vs 125 g/s carbon en puertos WOT")

    return casos
