"""
Generador de casos de test ciego TEST10 para Clases 42 a 61.
Cubre SUSPENSION_CHASIS, ELECTRICO, CLIMATIZACION y CARROCERIA_NEUMATICA.
Exactamente 20 clases x 6 casos = 120 registros (2 L1, 2 L2, 2 L3 por clase).
Totalmente independientes, sin solapamiento léxico ni contaminación con Fase 10 o benchmarks.
"""

from typing import List, Dict
import sys
from pathlib import Path

sys.path.insert(0, str(Path("backend").resolve()))
from src.core.diagnostico.taxonomia_sistemas import FALLA_A_SISTEMA

keys = list(FALLA_A_SISTEMA.keys())

# Clases 42 a 46 (SUSPENSION_CHASIS)
CLASE_42 = keys[41]  # Amortiguadores reventados o bujes de suspension gastados
CLASE_43 = keys[42]  # Juntas homocineticas o palieres danados
CLASE_44 = keys[43]  # Llantas desbalanceadas o desalineadas
CLASE_45 = keys[44]  # Cremallera de direccion asistida con holgura o fuga
CLASE_46 = keys[45]  # Rodamiento de maza o rodaje de rueda picado (zumbido de rodadura)

# Clases 47 a 53 (ELECTRICO)
CLASE_47 = keys[46]  # Alternador defectuoso o placa de diodos quemada
CLASE_48 = keys[47]  # Bateria descargada o bornes sulfatados
CLASE_49 = keys[48]  # Degradacion o falla en paquete de bateria de alto voltaje (EV / Hibridos)
CLASE_50 = keys[49]  # Fallo en inversor de corriente IGBT o motor electrico (EV)
CLASE_51 = keys[50]  # Foco o falla en sistema de refrigeracion de bateria/inversor (EV)
CLASE_52 = keys[51]  # Falla en motor de arranque o solenoide defectuoso (clac seco o carbones gastados)
CLASE_53 = keys[52]  # Fuga parasita de corriente en reposo (consumo nocturno de bateria)

# Clase 54 (CLIMATIZACION)
CLASE_54 = keys[53]  # Falla en compresor de aire acondicionado o fuga de gas R134a

# Clases 55 a 61 (CARROCERIA_NEUMATICA)
CLASE_55 = keys[54]  # Falla electrica del cierre centralizado o actuador de puerta
CLASE_56 = keys[55]  # Cerradura, chapa o pestillo mecanico de puerta trabado o desalineado
CLASE_57 = keys[56]  # Elevalunas electrico o guaya de alzacristales rota o trabada
CLASE_58 = keys[57]  # Limpiaparabrisas o motor pluma quemado
CLASE_59 = keys[58]  # Fugas de aire o fallos en el sistema de frenos neumático (Camiones)
CLASE_60 = keys[59]  # Válvula de freno de aire o secador APS obstruido (Camiones)
CLASE_61 = keys[60]  # Falla en actuador de resorte o camara Maxi-Brake trabada (frenos de aire)

# Contrastivas útiles
CLASE_05 = keys[4]
CLASE_07 = keys[6]
CLASE_27 = keys[26]
CLASE_28 = keys[27]
CLASE_30 = keys[29]
CLASE_33 = keys[32]
CLASE_34 = keys[33]

FUENTE = "SINTETICO_TEST_CIEGO"


def obtener_test10_parte4(offset: int = 247) -> List[Dict[str, str]]:
    casos = []
    idx = offset

    def agregar(clase, macro, nivel, texto, lenguaje, condicion, sp, sn, dtc, req_p, es_c, c_cont, obs):
        nonlocal idx
        reg_id = f"TEST10-{idx:04d}"
        grp_id = f"G-TEST10-{idx:04d}"
        casos.append({
            "id": reg_id,
            "id_grupo": grp_id,
            "clase_objetivo": clase,
            "macro_sistema": macro,
            "nivel_informacion": nivel,
            "texto_usuario": texto,
            "tipo_lenguaje": lenguaje,
            "condicion_operacion": condicion,
            "sintomas_presentes": sp,
            "sintomas_negados": sn,
            "dtc": dtc,
            "requiere_pregunta": req_p,
            "es_contrastivo": es_c,
            "clase_contrastiva": c_cont,
            "fuente": FUENTE,
            "observaciones": obs
        })
        idx += 1

    # --- CLASE 42: Amortiguadores / bujes ---
    agregar(CLASE_42, "SUSPENSION_CHASIS", "L1", "El carro parece una lancha que no para de rebotar cada vez que paso un lomo de toro.", "COTIDIANO", "PASO_BADEN", "rebote_continuo_lancha_baden", "NO_REPORTA", "", "SI", "NO", "", "L1 rebote continuo lancha")
    agregar(CLASE_42, "SUSPENSION_CHASIS", "L1", "golpe seco tipo clac clac abajo en los baches como si se fuera a desarmar la rueda", "WHATSAPP", "CALZADA_IRREGULAR", "golpe_seco_clac_clac_baches", "NO_REPORTA", "", "SI", "NO", "", "L1 golpe seco baches clac clac")
    agregar(CLASE_42, "SUSPENSION_CHASIS", "L2", "Vástago del amortiguador delantero derecho bañado en aceite espeso con polvo adherido; al presionar el capó hacia abajo la carrocería oscila 4 veces antes de frenar.", "TALLER", "TEST_REBOTE_CARROCERIA", "amortiguador_reventado_fuga_aceite, oscilacion_4_veces", "falla_cremallera_direccion", "", "NO", "SI", CLASE_45, "L2 amortiguador fugado rebote 4 veces vs cremallera")
    agregar(CLASE_42, "SUSPENSION_CHASIS", "L2", "Golpeteo en empedrado al frenar o acelerar; bujes silentblock de tijera inferior con goma cuarteada y descentramiento de 8 mm tocando el metal de la cuna.", "TALLER", "PALANCA_FOSO_TIJERA", "bujes_silentblock_rajados, descentramiento_metal_con_metal", "falla_homocinetica", "", "NO", "SI", CLASE_43, "L2 bujes silentblock rajados metal con metal")
    agregar(CLASE_42, "SUSPENSION_CHASIS", "L3", "Banco de prueba de amortiguadores por resonancia EUSAMA: eficacia de amortiguación en eje delantero izquierdo registra 21% (mínimo de seguridad 40%, desequilibrio de eje del 52%); vástago muestra pérdida total de gas presurizado y retén de guía desintegrado.", "TECNICO", "BANCO_RESONANCIA_EUSAMA", "eficacia_eusama_21porciento, desequilibrio_eje_52porciento", "llantas_desbalanceadas", "", "NO", "SI", CLASE_44, "L3 banco EUSAMA 21% desequilibrio 52% vástago sin gas")
    agregar(CLASE_42, "SUSPENSION_CHASIS", "L3", "Medición de holgura elástica con banco de holguras neumático para inspección técnica: buje posterior de brazo oscilante presenta desplazamiento axial anómalo de 11.5 mm con cizallamiento del núcleo de caucho vulcanizado; bieletas de barra estabilizadora sin juego en rótulas.", "TECNICO", "BANCO_HOLGURAS_NEUMATICO", "desplazamiento_axial_11_5mm_buje, bieletas_ok", "falla_caja_direccion", "", "NO", "SI", CLASE_45, "L3 banco holguras buje cizallado 11.5mm bieleta ok")

    # --- CLASE 43: Homocinéticas / palieres ---
    agregar(CLASE_43, "SUSPENSION_CHASIS", "L1", "Hace un trac trac trac rápido y seguido cada vez que doblo toda la dirección para entrar al garaje.", "COTIDIANO", "GIRO_COMPLETO_DIRECCION", "trac_trac_al_doblar_direccion", "NO_REPORTA", "", "SI", "NO", "", "L1 trac trac al doblar todo")
    agregar(CLASE_43, "SUSPENSION_CHASIS", "L1", "al girar la curva acelerando suena un traqueteo fuerte en la rueda derecha", "WHATSAPP", "CURVA_CON_TRACCION", "traqueteo_en_curva_con_aceleracion", "NO_REPORTA", "", "SI", "NO", "", "L1 traqueteo curva acelerando")
    agregar(CLASE_43, "SUSPENSION_CHASIS", "L2", "Chasquido metálico continuo al girar cerrado en primera o segunda marcha; fuelle de goma exterior de homocinética rasgado con grasa negra grafitada salpicada en la llanta.", "TALLER", "INSPECCION_FUELLE_PALIER", "fuelle_rasgado_grasa_salpicada, chasquido_al_doblar", "falla_rodaje_maza", "", "NO", "SI", CLASE_46, "L2 fuelle rasgado grasa salpicada vs rodaje")
    agregar(CLASE_43, "SUSPENSION_CHASIS", "L2", "Vibración transversal en la carrocería que aparece únicamente al acelerar fuerte entre 80 km/h y 100 km/h; en neutro desaparece; triceta interior con juego axial de 6 mm en la copa.", "TALLER", "PRUEBA_RUTA_VIBRACION_TRICETA", "vibracion_solo_al_acelerar_80_100, triceta_juego_copa", "llantas_desbalanceadas", "", "NO", "SI", CLASE_44, "L2 vibracion solo al acelerar 80-100 triceta con juego")
    agregar(CLASE_43, "SUSPENSION_CHASIS", "L3", "Desarme de junta homocinética fija tipo Rzeppa: jaula porta-bolas de acero cementado fisurada en una de las ventanas de alojamiento; pistas elípticas de la campana con huellas de picadura de 1.2 mm de profundidad por trabajo seco sin lubricante; estrías de unión con maza de rueda intactas.", "TECNICO", "INSPECCION_DESARME_RZEPPA", "jaula_bolas_fisurada, pistas_picadas_1_2mm, estrias_maza_ok", "falla_rodamiento_rueda", "", "NO", "SI", CLASE_46, "L3 jaula Rzeppa fisurada picaduras 1.2mm sin grasa")
    agregar(CLASE_43, "SUSPENSION_CHASIS", "L3", "Comprobación con reloj comparador en semieje delantero derecho: salto radial (runout) en la barra de transmisión mide 1.6 mm por deformación plástica tras golpe de cordón en cuneta; a 90 km/h genera fuerza de desbalanceo centrífugo oscilante de 320 N que sacude el piso del habitáculo.", "TECNICO", "RELOJ_COMPARADOR_PALIER_RUNOUT", "runout_barra_palier_1_6mm, vibracion_320n_90kmh", "falla_diferencial", "", "NO", "SI", keys[36], "L3 runout barra palier 1.6 mm reloj comparador")

    # --- CLASE 44: Llantas desbalanceadas / desalineadas ---
    agregar(CLASE_44, "SUSPENSION_CHASIS", "L1", "El volante empieza a vibrar justo cuando llego a 90 o 100 y si acelero más se le pasa.", "COTIDIANO", "VELOCIDAD_CRUCERO_AUTOPISTA", "vibracion_volante_90_100_kmh", "NO_REPORTA", "", "SI", "NO", "", "L1 vibracion volante a 90-100")
    agregar(CLASE_44, "SUSPENSION_CHASIS", "L1", "suelto el timon en recta plana y el carro se va solito para la cuneta derecha", "WHATSAPP", "RECTA_LLANA", "desvio_hacia_derecha_soltar_timon", "NO_REPORTA", "", "SI", "NO", "", "L1 desvio a la derecha en recta")
    agregar(CLASE_44, "SUSPENSION_CHASIS", "L2", "Vibración rítmica en el volante a partir de 95 km/h constante sin pisar el freno; neumático delantero perdió el plomo de contrapeso exterior de la llanta de aleación.", "TALLER", "INSPECCION_CONTRAPESOS_LLANTA", "vibracion_a_95kmh_sin_frenar, contrapeso_plomo_faltante", "discos_alabeados", "", "NO", "SI", CLASE_28, "L2 vibracion 95 kmh sin frenar plomo perdido vs disco")
    agregar(CLASE_44, "SUSPENSION_CHASIS", "L2", "Desgaste asimétrico acelerado en el borde interno de las dos llantas delanteras; neumáticos lisos por dentro con apenas 10,000 km por convergencia negativa excesiva.", "TALLER", "INSPECCION_BANDA_RODADURA", "desgaste_borde_interno_10000km, convergencia_abierta", "falla_amortiguadores", "", "NO", "SI", CLASE_42, "L2 desgaste borde interno convergencia negativa")
    agregar(CLASE_44, "SUSPENSION_CHASIS", "L3", "Diagnóstico en balanceadora dinámica computarizada: rueda delantera izquierda registra desbalance dinámico residual de 45 gramos en plano exterior y 20 gramos en plano interior; variación de fuerza radial (RFV) de 140 N por abolladura de 3 mm en pestaña interior del aro de chapa.", "TECNICO", "BALANCEADORA_DINAMICA_RFV", "desbalance_45g_exterior_20g_interior, rfv_140n_aro_abollado", "falla_disco_freno", "", "NO", "SI", CLASE_28, "L3 balanceadora 45g desbalance RFV 140N aro golpeado")
    agregar(CLASE_44, "SUSPENSION_CHASIS", "L3", "Alineación láser 3D computarizada: ángulo de convergencia total delantero mide -0°54' (nominal +0°10' ± 0°05' abierta en exceso); ángulo de caída (camber) izquierdo en -2°15' frente a -0°30' derecho; tirón lateral constante de 35 N/m sobre el volante sin juego en rótulas de dirección.", "TECNICO", "ALINEADORA_LASER_3D", "convergencia_menos_0_54_abierta, camber_desfasado_2_grados", "falla_cremallera_direccion", "", "NO", "SI", CLASE_45, "L3 alineacion laser convergencia -0 54 camber asimetrico")

    # --- CLASE 45: Cremallera de dirección con holgura / fuga ---
    agregar(CLASE_45, "SUSPENSION_CHASIS", "L1", "El timón tiene un juego muerto grandísimo antes de que las llantas doblen.", "COTIDIANO", "MOVIMIENTO_ESTACIONADO", "juego_muerto_amplio_volante", "NO_REPORTA", "", "SI", "NO", "", "L1 juego muerto volante amplio")
    agregar(CLASE_45, "SUSPENSION_CHASIS", "L1", "hace un clac en la direccion al doblar lento en las esquinas y el volante se siente suelto", "WHATSAPP", "MANIOBRA_ESQUINA", "clac_direccion_volante_suelto", "NO_REPORTA", "", "SI", "NO", "", "L1 clac direccion volante suelto")
    agregar(CLASE_45, "SUSPENSION_CHASIS", "L2", "Pérdida de líquido hidráulico ATF rojo con charco debajo de la cremallera; fuelles de dirección empapados de fluido por retén lateral soplado.", "TALLER", "FOSO_INSPECCION_CREMALLERA", "fuelle_direccion_goteo_atf, reten_lateral_soplado", "falla_bomba_direccion", "", "NO", "SI", CLASE_30, "L2 fuelle direccion goteo ATF reten lateral")
    agregar(CLASE_45, "SUSPENSION_CHASIS", "L2", "Dirección asistida eléctrica con juego y golpeteo metálico al mover el volante rápido izquierda-derecha con motor apagado; buje guía de teflón de la barra con desgaste.", "TALLER", "TEST_JUEGO_ESTACIONADO", "golpeteo_buje_teflon_cremallera, juego_volante_apagado", "falla_rotula_suspension", "", "NO", "SI", CLASE_42, "L2 buje teflon cremallera golpe volante apagado")
    agregar(CLASE_45, "SUSPENSION_CHASIS", "L3", "Medición de holgura angular con goniómetro en columna y reloj comparador en bieleta axial: carrera muerta del volante mide 16 grados antes de transmitir desplazamiento lineal a la barra dentada; tornillo de precarga de cremallera apretado a tope sin lograr eliminar juego por desgaste central de dientes de cremallera.", "TECNICO", "GONIOMETRO_HOLGURA_CREMALLERA", "carrera_muerta_16_grados, dientes_centrales_gastados", "falla_rotula_axial", "", "NO", "SI", CLASE_42, "L3 goniometro 16 grados juego dientes centrales gastados")
    agregar(CLASE_45, "SUSPENSION_CHASIS", "L3", "Prueba de presión de cremallera hidráulica en tope de viraje con manómetro de 150 bar: la presión de bomba entrega 110 bar pero la cremallera fuga 1.4 L/min internamente a través de los sellos de teflón del distribuidor rotativo (válvula piñón); dirección dura a bajas revoluciones en maniobras de aparcamiento.", "TECNICO", "MANOMETRO_PRESION_DIRECCION_HIDRO", "fuga_interna_distribuidor_rotativo_1_4l, direccion_pesada", "falla_bomba_hidraulica_direccion", "", "NO", "SI", keys[46], "L3 manometro fuga interna distribuidor 1.4 L min")

    # --- CLASE 46: Rodamiento de maza / rueda picado ---
    agregar(CLASE_46, "SUSPENSION_CHASIS", "L1", "Se escucha un zumbido ronco de rodadura que no me deja ni hablar dentro del carro a 70 por hora.", "COTIDIANO", "MARCHA_CALZADA_BUENA", "zumbido_ronco_rodadura_a_70kmh", "NO_REPORTA", "", "SI", "NO", "", "L1 zumbido ronco a 70 kmh")
    agregar(CLASE_46, "SUSPENSION_CHASIS", "L1", "el zumbido aumenta fuertisimo cuando tomo una curva a la izquierda y si doblo a la derecha se apaga", "WHATSAPP", "CURVA_CARRETERA", "zumbido_sube_en_curva_izquierda_apaga_derecha", "NO_REPORTA", "", "SI", "NO", "", "L1 zumbido sube curva izq apaga der")
    agregar(CLASE_46, "SUSPENSION_CHASIS", "L2", "Zumbido que varía de tono al cambiar de carril en carretera; con la rueda delantera derecha suspendida en el aire y haciéndola girar a mano se siente aspereza y vibración en el muelle de suspensión.", "TALLER", "TEST_MANUAL_MUELLE_SUSPENSION", "aspereza_vibracion_en_espiral_rueda_al_aire, zumbido_cambio_carril", "falla_diferencial", "", "NO", "SI", keys[36], "L2 aspereza en muelle al girar rueda al aire vs caja")
    agregar(CLASE_46, "SUSPENSION_CHASIS", "L2", "Rueda trasera izquierda con juego axial perceptible al zarandearla en cruz con las manos; rodamiento de cubo integrado con tuerca de buje apretada a 240 Nm que continúa con holgura.", "TALLER", "ZARANDEO_RUEDA_ELEVADOR", "juego_axial_rueda_trasera, tuerca_apretada_240nm", "falla_buje_suspension", "", "NO", "SI", CLASE_42, "L2 juego axial rueda trasera tuerca 240 Nm ok")
    agregar(CLASE_46, "SUSPENSION_CHASIS", "L3", "Análisis con estetoscopio electrónico de chasis fijado en la mangueta delantera derecha: a 60 km/h en banco de rodillos el rodamiento genera pico de vibración en la frecuencia de paso de bolas de pista exterior (BPFO) de 285 Hz con amplitud de 74 dB; desmontaje confirma microfisuras y descascarillado en pista exterior.", "TECNICO", "ESTETOSCOPIO_FRECUENCIA_BPFO", "frecuencia_bpfo_285hz_74db, descascarillado_pista_exterior", "falla_homocinetica_buje", "", "NO", "SI", CLASE_43, "L3 estetoscopio frecuencia BPFO 285 Hz 74 dB mangueta")
    agregar(CLASE_46, "SUSPENSION_CHASIS", "L3", "Medición de juego de rodamiento de rueda con reloj comparador en el disco de freno: holgura axial de 0.08 mm (tolerancia máxima permitida 0.02 mm); temperatura con pirómetro infrarrojo en el centro de la maza registra 98°C tras 15 km frente a 42°C en el lado opuesto; disco y pastillas sin roce mecánico.", "TECNICO", "PIROMETRO_RELOJ_RODAMIENTO", "holgura_axial_0_08mm_vs_0_02mm, maza_98c_vs_42c_opuesta", "falla_caliper_trabado", "", "NO", "SI", CLASE_33, "L3 holgura 0.08mm maza a 98C vs 42C opuesta")

    # --- CLASE 47: Alternador defectuoso / diodos ---
    agregar(CLASE_47, "ELECTRICO", "L1", "Se prendió la lucecita roja de la batería en el tablero y las luces de noche alumbran amarillo débil.", "COTIDIANO", "MARCHA_NOCTURNA", "luz_bateria_encendida, luces_amarillas_debiles", "NO_REPORTA", "", "SI", "NO", "", "L1 luz bateria luces debiles")
    agregar(CLASE_47, "ELECTRICO", "L1", "huele a plastico quemado del lado de las fajas y se escucha un zumbido electrico como turbina", "WHATSAPP", "RALENTI_MOTOR", "olor_plastico_quemado_fajas, zumbido_electrico", "NO_REPORTA", "", "SI", "NO", "", "L1 olor quemado zumbido alternador")
    agregar(CLASE_47, "ELECTRICO", "L2", "Con motor encendido a 2000 RPM el multímetro en los bornes de la batería marca solo 11.8V (no carga); correa de accesorios tensada y sin patinar.", "TALLER", "VOLTIMETRO_BORNES_BATERIA", "voltaje_11_8v_motor_en_marcha, correa_tensada_ok", "falla_bateria_descargada", "", "NO", "SI", CLASE_48, "L2 voltaje 11.8V con motor en marcha vs bateria")
    agregar(CLASE_47, "ELECTRICO", "L2", "Sobretensión peligrosa: multímetro marca 16.2V en la batería y las luces delanteras parpadean con riesgo de quemar lámparas; regulador de voltaje en cortocircuito.", "TALLER", "MULTIMETRO_SOBRETENSION", "sobretension_16_2v_luces_parpadean, regulador_en_corto", "falla_bornes_bateria", "", "NO", "SI", CLASE_48, "L2 sobretension 16.2V regulador en corto")
    agregar(CLASE_47, "ELECTRICO", "L3", "Osciloscopio automotriz en borne B+ de alternador a 2500 RPM: presencia de rizado de corriente alterna excesivo con ondulación pico a pico de 1.85V AC (norma máxima admisible < 0.3V AC); diodo rectificador positivo abierto en el puente de diodos; consumo del estator asimétrico en prueba de banco.", "TECNICO", "OSCILOSCOPIO_RIZADO_ALTERNA_B_MAS", "rizado_ac_1_85v_vs_0_3v_maximo, diodo_rectificador_abierto", "falla_bateria", "", "NO", "SI", CLASE_48, "L3 oscilograma rizado 1.85V AC diodo quemado")
    agregar(CLASE_47, "ELECTRICO", "L3", "Prueba de carga con reóstato de carbón a 14.0V constantes: alternador de 120A entrega solo 38A a 3000 RPM de rotor antes de colapsar la tensión a 12.1V; escobillas de carbón gastadas a 3.5 mm de longitud con resortes sin presión de contacto contra los anillos rozantes de cobre.", "TECNICO", "BANCO_PRUEBA_REOSTATO_ALTERNADOR", "entrega_38a_vs_120a_nominal, escobillas_3_5mm_desgastadas", "falla_fuga_parasita", "", "NO", "SI", keys[52], "L3 banco reostato 38A vs 120A escobillas gastadas")

    # --- CLASE 48: Batería descargada / bornes ---
    agregar(CLASE_48, "ELECTRICO", "L1", "Giro la llave para prender el auto, hace un clac seco débil y se apagan todas las luces del tablero.", "COTIDIANO", "INTENTO_ARRANQUE", "clac_debil_luces_tablero_apagan", "NO_REPORTA", "", "SI", "NO", "", "L1 clac luces apagan intento arranque")
    agregar(CLASE_48, "ELECTRICO", "L1", "los postes de la bateria tienen un polvo verde y blanco esponjoso que los tapa por completo", "WHATSAPP", "REVISION_CAPO", "bornes_polvo_verde_blanco_sulfatados", "NO_REPORTA", "", "SI", "NO", "", "L1 bornes polvo sulfato verde blanco")
    agregar(CLASE_48, "ELECTRICO", "L2", "Tensión de reposo de la batería en 10.4V tras 8 horas de estacionamiento; al puentear con cables desde otro vehículo el motor arranca al toque en medio segundo.", "TALLER", "PUENTE_BATERIA_AUXILIAR", "reposo_10_4v_arranca_con_cables, bateria_muerta", "falla_motor_arranque", "", "NO", "SI", keys[51], "L2 reposo 10.4V arranca con cables vs arranque")
    agregar(CLASE_48, "ELECTRICO", "L2", "Caída de tensión de 3.2V entre el borne de plomo de la batería y el terminal de bronce del cable durante el intento de arranque; bornes flojos y sulfatados impiden el paso de corriente.", "TALLER", "VOLTIMETRO_CAIDA_BORNES", "caida_3_2v_en_borne_sulfatado, bornes_flojos", "falla_alternador", "", "NO", "SI", CLASE_47, "L2 caida 3.2V en borne sulfatado flojo")
    agregar(CLASE_48, "ELECTRICO", "L3", "Diagnóstico con analizador de baterías por conductancia Midtronics: batería de 650 CCA nominales rinde únicamente 180 CCA reales con estado de salud (SOH) al 24%; resistencia interna elevada a 18.5 mOhmios (nominal 4.5 mOhmios) por sulfatación irreversible de placas de plomo-ácido.", "TECNICO", "ANALIZADOR_MIDTRONICS_CONDUCTANCIA", "cca_180_vs_650_soh_24porciento, resistencia_interna_18_5mohms", "falla_motor_arranque", "", "NO", "SI", keys[51], "L3 Midtronics 180 vs 650 CCA SOH 24% sulfatada")
    agregar(CLASE_48, "ELECTRICO", "L3", "Prueba de densidad de electrolito con densímetro óptico refractómetro: celdas 1, 2, 4 y 5 marcan 1.26 g/ml pero celda 3 marca 1.10 g/ml en cortocircuito interno por lodo de plomo decantado en el fondo; tensión en circuito abierto estancada en 10.5V.", "TECNICO", "DENSIMETRO_REFRACTOMETRO_BATERIA", "celda_3_densidad_1_10_en_corto, tension_10_5v_fija", "falla_alternador", "", "NO", "SI", CLASE_47, "L3 refractometro celda 3 en corto 1.10 g ml 10.5V")

    # --- CLASE 49: Batería alto voltaje (EV / Híbridos) ---
    agregar(CLASE_49, "ELECTRICO", "L1", "La autonomía del auto eléctrico se cayó de 250 km a solo 80 km con la carga al 100%.", "COTIDIANO", "CARGA_COMPLETA", "autonomia_desplomada_250_a_80km", "NO_REPORTA", "", "SI", "NO", "", "L1 autonomia desplomada carga 100%")
    agregar(CLASE_49, "ELECTRICO", "L1", "aparece una tortuga roja en el cuadro y no deja acelerar mas de 30 km por hora", "WHATSAPP", "MODO_TORTUGA_EV", "modo_tortuga_ev_limitado_30kmh", "NO_REPORTA", "", "SI", "NO", "", "L1 modo tortuga EV no acelera")
    agregar(CLASE_49, "ELECTRICO", "L2", "En vehículo híbrido Toyota / Lexus: mensaje de revisar sistema híbrido con DTC P0A80 por degradación del paquete de batería HV; ventilador de enfriamiento de la batería suena continuo al máximo.", "TALLER", "ESCANEO_PAQUETE_BATERIA_HV", "dtc_p0a80_reemplazar_bateria_hv, ventilador_bateria_al_maximo", "falla_bateria_12v", "P0A80", "NO", "SI", CLASE_48, "L2 P0A80 reemplazar bateria HV ventilador al maximo")
    agregar(CLASE_49, "ELECTRICO", "L2", "Diferencia de tensión entre bloques de la batería de tracción supera los 1.2V al acelerar en pendiente; el BMS corta la asistencia eléctrica para proteger las celdas débiles.", "TECNICO", "DATOS_EN_VIVO_BMS_DELTA", "delta_tension_bloques_1_2v, corte_asistencia_bms", "falla_inversor_corriente", "", "NO", "SI", CLASE_50, "L2 delta bloques 1.2V corte BMS vs inversor")
    agregar(CLASE_49, "ELECTRICO", "L3", "Diagnóstico de batería de alto voltaje con escáner Techstream: lectura de los 14 bloques NiMH registra bloque 6 con 13.8V mientras los demás están en 15.6V bajo descarga forzada (delta V de 1800 mV; límite máximo admisible 200 mV); resistencia interna de bloque 6 en 0.048 Ohmios (4 veces superior a la media).", "TECNICO", "TECHSTREAM_DELTAV_BLOQUES_HV", "bloque_6_cae_13_8v_vs_15_6v, delta_1800mv_resistencia_alta", "falla_inversor_igbt", "P0A80", "NO", "SI", CLASE_50, "L3 Techstream delta V 1800 mV bloque 6 resistencia 4x")
    agregar(CLASE_49, "ELECTRICO", "L3", "Inspección de relés de pre-carga y contactores principales de alto voltaje (SMR): relé positivo SMRB presenta resistencia de contacto de 14 Ohmios en cerrado por flameo de contactos de plata; código DTC P0AA6 por fallo de aislamiento de alto voltaje a chasis detectado con megóhmetro a 1000V DC (resistencia de 150 kOhmios vs > 10 MOhmios).", "TECNICO", "MEGOHMETRO_AISLAMIENTO_HV", "dtc_p0aa6_perdida_aislamiento, smr_flameado_14_ohmios", "falla_inversor", "P0AA6", "NO", "SI", CLASE_50, "L3 megohmetro 1000V P0AA6 perdida aislamiento SMR")

    # --- CLASE 50: Inversor de corriente IGBT / motor eléctrico ---
    agregar(CLASE_50, "ELECTRICO", "L1", "El auto híbrido prende pero al poner Directa no avanza nada y suena una alarma aguda.", "COTIDIANO", "PONER_MARCHA", "no_avanza_al_poner_directa_alarma_aguda", "NO_REPORTA", "", "SI", "NO", "", "L1 hibrido no avanza directa alarma")
    agregar(CLASE_50, "ELECTRICO", "L1", "pego un tiron seco y se apago todo el sistema electrico con olor a electronica quemada", "WHATSAPP", "FALLO_EN_MARCHA", "tiron_seco_olor_electronica_quemada", "NO_REPORTA", "", "SI", "NO", "", "L1 tiron olor electronica quemada")
    agregar(CLASE_50, "ELECTRICO", "L2", "Inversor híbrido con código DTC P0A94 de rendimiento de convertidor DC-DC; fusible principal de 125A de alta tensión intacto pero no hay salida de 14V para cargar la batería de accesorios.", "TALLER", "REVISION_CONVERTIDOR_DC_DC", "dtc_p0a94_convertidor_dc_dc, sin_salida_14v_accesorios", "falla_alternador", "P0A94", "NO", "SI", CLASE_47, "L2 P0A94 convertidor DC-DC sin salida 14V vs alternador")
    agregar(CLASE_50, "ELECTRICO", "L2", "Mensaje de fallo en sistema de propulsión eléctrica en vehículo 100% EV; motor eléctrico emite chillido de alta frecuencia sin girar; el inversor entra en corte por sobrecorriente de fase.", "TECNICO", "ESCANEO_CONTROL_MOTOR_EV", "sobrecorriente_fase_inversor, motor_no_gira_chillido", "falla_bateria_alta_tension", "", "NO", "SI", CLASE_49, "L2 sobrecorriente fase inversor motor sin girar")
    agregar(CLASE_50, "ELECTRICO", "L3", "Diagnóstico de módulo de potencia inteligente IPM en inversor de tracción: prueba de diodos con multímetro en bornes U, V, W respecto al bus DC positivo arroja 0.00V en fase V (transistor IGBT en cortocircuito franco por avalancha térmica); condensador de enlace DC de 800 uF con abombamiento visible.", "TECNICO", "MULTIMETRO_PRUEBA_IGBT_FASES", "igbt_fase_v_en_cortocircuito_0v, condensador_link_abombado", "falla_refrigeracion_inversor", "P0A78", "NO", "SI", CLASE_51, "L3 prueba IGBT fase V en corto 0.00V P0A78")
    agregar(CLASE_50, "ELECTRICO", "L3", "Medición de resistencia y aislamiento en devanados del motor síncrono de imanes permanentes MG2: puente Kelvin de miliohmios mide 18.2 mOhmios parejos en fases U-V, V-W y W-U; prueba con megóhmetro a 1000V registra > 500 MOhmios a masa (motor estatórico 100% sano); falla localizada en driver de disparo de compuerta PWM del inversor.", "TECNICO", "PUENTE_KELVIN_MEGOHMETRO_MOTOR_EV", "motor_mg2_devanados_sanos_18mohms, driver_compuerta_inversor_muerto", "falla_motor_electrico", "P0A1B", "NO", "SI", CLASE_49, "L3 puente Kelvin devanados sanos driver gate quemado")

    # --- CLASE 51: Refrigeración de batería / inversor (EV) ---
    agregar(CLASE_51, "ELECTRICO", "L1", "Aparece un mensaje de temperatura alta del sistema híbrido cuando subo cuestas largas.", "COTIDIANO", "SUBIDA_PROLONGADA", "temperatura_alta_sistema_hibrido_subida", "NO_REPORTA", "", "SI", "NO", "", "L1 temperatura alta sistema hibrido")
    agregar(CLASE_51, "ELECTRICO", "L1", "el ventilador debajo del asiento trasero suena fuertisimo como una turbina todo el tiempo", "WHATSAPP", "FUNCIONAMIENTO_CABINA", "ventilador_asiento_trasero_como_turbina", "NO_REPORTA", "", "SI", "NO", "", "L1 ventilador asiento trasero turbina")
    agregar(CLASE_51, "ELECTRICO", "L2", "Bomba eléctrica de refrigerante del inversor híbrido no genera turbulencia en el vaso de expansión al dar contacto; código DTC P0A93 de sobrecalentamiento del circuito de enfriamiento del inversor.", "TALLER", "INSPECCION_DEPOSITO_INVERSOR", "dtc_p0a93_inversor_caliente, bomba_inversor_sin_turbulencia", "falla_termostato_motor", "P0A93", "NO", "SI", CLASE_07, "L2 P0A93 bomba inversor sin turbulencia vs termostato")
    agregar(CLASE_51, "ELECTRICO", "L2", "Enfriamiento de batería de tracción bloqueado; rejilla de ventilación ubicada en el asiento posterior totalmente tapizada de pelos de perro y pelusas compactadas.", "TALLER", "INSPECCION_REJILLA_ASIENTO", "rejilla_bateria_obstruida_pelusas, alerta_refrigeracion", "falla_bateria_alta_tension", "", "NO", "SI", CLASE_49, "L2 rejilla ventilador bateria tapada pelusas")
    agregar(CLASE_51, "ELECTRICO", "L3", "Termografía infrarroja FLIR en radiador dedicado del inversor híbrido: el radiador se encuentra a 28°C mientras el cuerpo de aluminio del inversor escala a 89°C; bomba centrífuga de refrigerante de 12V con rotor trabado mecánicamente por sedimento; consumo eléctrico de 0.0A con 12.8V en el conector.", "TECNICO", "TERMOGRAFIA_FLIR_CIRCUITO_INVERSOR", "inversor_89c_radiador_28c_flir, bomba_rotor_trabado_0a", "falla_inversor_igbt", "P0A93", "NO", "SI", CLASE_50, "L3 FLIR inversor 89C radiador 28C bomba trabada P0A93")
    agregar(CLASE_51, "ELECTRICO", "L3", "Diagnóstico de ventilador de batería de tracción con escáner: activación manual al 100% de PWM registra lectura de sensor Hall de velocidad en 0 RPM; desmontaje expone rodamiento de turbina tipo jaula de ardilla agarrotado por lodo de polvo húmedo; temperatura de celdas centrales alcanza 52°C en reposo.", "TECNICO", "PRUEBA_ACTIVA_VENTILADOR_BMS", "ventilador_0rpm_con_pwm_100porciento, turbina_agarrotada, temp_52c", "falla_bateria_degradada", "P0A82", "NO", "SI", CLASE_49, "L3 ventilador 0 RPM con PWM 100% turbina trabada P0A82")

    # --- CLASE 52: Motor de arranque / solenoide ---
    agregar(CLASE_52, "ELECTRICO", "L1", "Giro la llave para encender y solo suena un clac metálico seco en el motor pero no gira.", "COTIDIANO", "INTENTO_ARRANQUE", "clac_metalico_seco_sin_girar", "NO_REPORTA", "", "SI", "NO", "", "L1 clac seco motor no gira")
    agregar(CLASE_52, "ELECTRICO", "L1", "le doy varios llavazos seguidos y a la quinta recien agarra y prende", "WHATSAPP", "ARRANQUE_INTERMITENTE", "enciende_a_los_cinco_llavazos", "NO_REPORTA", "", "SI", "NO", "", "L1 prende al 5to llavazo")
    agregar(CLASE_52, "ELECTRICO", "L2", "El motor de arranque no gira; al golpear suavemente la carcasa del burro con una barra metálica el auto enciende de inmediato por carbones gastados al límite.", "TALLER", "GOLPE_CARCASA_ARRANQUE", "enciende_al_golpear_arranque, carbones_al_limite", "falla_bateria_descargada", "", "NO", "SI", CLASE_48, "L2 enciende al golpear carbones gastados vs bateria")
    agregar(CLASE_52, "ELECTRICO", "L2", "El automático del arranque suena con fuerza al dar contacto pero el motor térmico no gira; borne de contacto interno de cobre del solenoide totalmente carbonizado.", "TALLER", "BANCO_PRUEBA_SOLENOIDE_ARRANQUE", "solenoide_ataca_pero_no_gira, borne_cobre_carbonizado", "falla_rele_arranque", "", "NO", "SI", CLASE_48, "L2 solenoide ataca borne carbonizado no gira")
    agregar(CLASE_52, "ELECTRICO", "L3", "Diagnóstico de circuito de arranque con osciloscopio y pinza amperimétrica de 600A: al dar arranque la corriente sube a 45A (consumo del solenoide) pero la corriente principal del inducido permanece en 0A con tensión de batería estable en 12.4V (sin caída de carga); escobillas de carbón gastadas a 2.1 mm sin contacto con delgas.", "TECNICO", "PINZA_AMPERIMETRICA_CORRIENTE_ARRANQUE", "corriente_45a_solenoide_0a_inducido, tension_12_4v_estable", "bateria_descargada", "", "NO", "SI", CLASE_48, "L3 pinza 45A solenoide 0A motor carbones gastados")
    agregar(CLASE_52, "ELECTRICO", "L3", "Desarme de motor de arranque en banco: colector de delgas del inducido con desprendimiento de una lámina por recalentamiento tras insistencia de arranque; bendix de acople con piñón de 9 dientes desgastado que resbala mecánicamente en su embrague unidireccional de rodillos; conmutador en cortocircuito.", "TECNICO", "DESARME_BANCO_INDUCIDO_BENDIX", "bendix_resbala_embrague_rodillos, delga_inducido_quemada", "falla_cremallera_volante", "", "NO", "SI", keys[10], "L3 bendix resbala delgas quemadas desarme en banco")

    # --- CLASE 53: Fuga parásita de corriente en reposo ---
    agregar(CLASE_53, "ELECTRICO", "L1", "Si dejo el auto parado dos días sin usar amanece con la batería totalmente muerta.", "COTIDIANO", "REPOSO_FIN_SEMANA", "bateria_muerta_tras_dos_dias_parado", "NO_REPORTA", "", "SI", "NO", "", "L1 bateria muerta tras 2 dias")
    agregar(CLASE_53, "ELECTRICO", "L1", "le compre bateria nueva hace una semana y ya se descargo dos veces de la noche a la manana", "WHATSAPP", "REPOSO_NOCTURNO", "bateria_nueva_descarga_de_la_noche_a_la_manana", "NO_REPORTA", "", "SI", "NO", "", "L1 bateria nueva descarga noche")
    agregar(CLASE_53, "ELECTRICO", "L2", "Consumo de corriente en reposo medido con multímetro en serie arroja 650 mA con el vehículo cerrado y en reposo (normal menor a 50 mA); al retirar el fusible de la radio el consumo baja a 25 mA.", "TALLER", "AMPERIMETRO_SERIE_FUSIBLES", "consumo_reposo_650ma_baja_con_radio, normal_25ma", "falla_alternador", "", "NO", "SI", CLASE_47, "L2 consumo 650 mA baja con fusible radio vs alternador")
    agregar(CLASE_53, "ELECTRICO", "L2", "Luz del maletero permanece encendida con la tapa cerrada por interruptor trabado; drena la batería de 60 Ah en 48 horas.", "TALLER", "INSPECCION_LUCES_CORTESIA", "luz_maletero_encendida_tapa_cerrada, drena_en_48h", "bateria_defectuosa", "", "NO", "SI", CLASE_48, "L2 luz maletero encendida interruptor trabado")
    agregar(CLASE_53, "ELECTRICO", "L3", "Medición de caída de tensión en microvoltios a través de fusibles (Voltage Drop Method) tras 45 minutos de reposo: fusible F14 de 15A en fusilera de habitáculo acusa caída de 3.2 mV (equivalente a 420 mA de drenaje continuo según tabla de resistencia de fusibles mini); circuito alimenta módulo de control de carrocería BCM que no entra en modo sleep.", "TECNICO", "METODO_CAIDA_TENSION_FUSIBLES_MV", "caida_3_2mv_fusible_f14_420ma, bcm_no_entra_sleep", "falla_bateria_quimica", "", "NO", "SI", CLASE_48, "L3 metodo caida tension 3.2 mV F14 BCM no duerme")
    agregar(CLASE_53, "ELECTRICO", "L3", "Prueba de consumo parasitario con registrador de datos de corriente (Data Logger) durante 8 horas: consumo basal de 45 mA que cada 12 minutos se dispara cíclicamente a 2.8 Amperios durante 90 segundos; el módulo de alarma no original despierta continuamente el bus CAN del vehículo impidiendo la desconexión del relé principal de accesorios.", "TECNICO", "DATA_LOGGER_CORRIENTE_REPOSO", "consumo_ciclico_2_8a_alarma_despierta_can, rele_activo", "falla_alternador_diodos", "", "NO", "SI", CLASE_47, "L3 data logger consumo ciclico 2.8A alarma despierta CAN")

    # --- CLASE 54: Aire acondicionado / fuga R134a ---
    agregar(CLASE_54, "CLIMATIZACION", "L1", "Prendo el aire acondicionado en frío máximo pero solo sale aire tibio por las rejillas.", "COTIDIANO", "USO_HABITACULO_AC", "aire_acondicionado_bota_aire_tibio_cabina", "NO_REPORTA", "", "SI", "NO", "", "L1 AC bota aire tibio cabina")
    agregar(CLASE_54, "CLIMATIZACION", "L1", "el ventilador de la cabina sopla bien fuerte pero no enfria nada y no se oye acoplar el compresor", "WHATSAPP", "COMANDO_AC_TABLERO", "sopla_fuerte_no_enfria_compresor_no_acopla", "NO_REPORTA", "", "SI", "NO", "", "L1 sopla fuerte no enfria no acopla")
    agregar(CLASE_54, "CLIMATIZACION", "L2", "Enfría moderadamente mientras el auto rueda en carretera a velocidad pero al detenerse en semáforos el aire de las rejillas se torna caliente; presiones con manómetros: baja en 28 psi y alta en 110 psi (baja para régimen de trabajo).", "TALLER", "REGIMEN_DETENIDO_VS_MARCHA", "enfria_en_ruta_calienta_en_semaforo, presion_alta_baja_110psi", "falla_termostato_motor", "", "NO", "SI", CLASE_07, "L2 enfria en ruta calienta en semaforo vs termostato")
    agregar(CLASE_54, "CLIMATIZACION", "L2", "Pérdida progresiva de capacidad frigorífica en 3 semanas; manómetro de baja acusa 10 psi con compresor activo (falta de gas refrigerante); manchas aceitosas de lubricante PAG visibles en la esquina inferior del condensador de aluminio.", "TALLER", "INSPECCION_MANOMETROS_AC", "baja_en_10psi_falta_gas, mancha_aceite_pag_condensador", "fuga_radiador_motor", "", "NO", "SI", keys[7], "L2 baja en 10 psi mancha aceite PAG condensador vs radiador")
    agregar(CLASE_54, "CLIMATIZACION", "L3", "Medición termométrica en tobera central del evaporador: temperatura de salida registra 19.5°C con perilla al mínimo (nominal 4°C a 7°C con ambiente a 26°C); puente de manómetros acopla en 75 psi en baja y 78 psi en alta con compresor de desplazamiento variable accionado (presiones igualadas sin bombeo por rotura de placa de válvulas del compresor; válvula de control PWM recibe 0.85A correctos).", "TECNICO", "TERMOMETRO_TOBERA_MANOMETROS_IGUALADOS", "tobera_19_5c_vs_5c_oem, presiones_igualadas_75_78psi, pwm_0_85a_ok", "falla_ventilador_radiador", "", "NO", "SI", CLASE_07, "L3 tobera 19.5C presiones igualadas 75-78 psi PWM 0.85A ok")
    agregar(CLASE_54, "CLIMATIZACION", "L3", "Prueba de estanqueidad con detector electrónico de fugas de gas halógeno (sensibilidad 3 g/año): alarma focalizada suena en el retén del eje frontal de la polea del compresor de aire acondicionado; peso recuperado de gas R134a en estación de carga es de apenas 85 gramos (especificación de carga 520 ± 20 gramos); motor térmico funciona a 90°C impecable.", "TECNICO", "ESTACION_RECUPERACION_DETECTOR_HALOGENO", "recupera_85g_vs_520g_r134a, fuga_reten_eje_compresor, motor_90c_ok", "falla_sobrecalentamiento_motor", "", "NO", "SI", CLASE_07, "L3 recupera 85g vs 520g fuga reten eje compresor")

    # --- CLASE 55: Cierre centralizado eléctrico / actuador ---
    agregar(CLASE_55, "CARROCERIA_NEUMATICA", "L1", "Apreto el botón de la llave para trabar las puertas y solo una no baja el seguro.", "COTIDIANO", "MANDO_A_DISTANCIA", "una_puerta_no_baja_seguro_mando", "NO_REPORTA", "", "SI", "NO", "", "L1 una puerta no baja seguro")
    agregar(CLASE_55, "CARROCERIA_NEUMATICA", "L1", "hace un traqueteo electrico como matraca adentro de la puerta del chofer al poner seguro", "WHATSAPP", "BOTON_SEGURO_CABINA", "traqueteo_electrico_puerta_al_cerrar", "NO_REPORTA", "", "SI", "NO", "", "L1 traqueteo electrico puerta")
    agregar(CLASE_55, "CARROCERIA_NEUMATICA", "L2", "El seguro eléctrico de la puerta trasera derecha no responde ni con el mando ni con el botón central; al mover manualmente el pestillo corre suave sin resistencia mecánica alguna.", "TALLER", "COMPROBACION_PESTILLO_MANUAL", "actuador_no_reacciona, pestillo_manual_corre_suave", "falla_cerradura_mecanica", "", "NO", "SI", CLASE_56, "L2 actuador no reacciona pestillo manual suave vs mecanica")
    agregar(CLASE_55, "CARROCERIA_NEUMATICA", "L2", "Al presionar el botón de cierre centralizado los fusibles están intactos pero la puerta del copiloto emite un zumbido débil de motorcito eléctrico sin fuerza para empujar la traba.", "TALLER", "INSPECCION_PANEL_PUERTA", "motorcito_sin_fuerza_zumbido, fusible_ok", "falla_chapa_mecanica", "", "NO", "SI", CLASE_56, "L2 motorcito sin fuerza zumbido vs mecanica")
    agregar(CLASE_55, "CARROCERIA_NEUMATICA", "L3", "Comprobación de alimentación en el conector del actuador de puerta: pulso de 12.6V con polaridad reversible presente durante 450 ms al activar el mando; multímetro en el micromotor eléctrico de corriente continua arroja bobinado inducido quemado con resistencia infinita (circuito abierto); varillaje mecánico completamente alineado.", "TECNICO", "PULSO_ALIMENTACION_ACTUADOR_PUERTA", "pulso_12_6v_presente_450ms, micromotor_abierto_infinito, varillaje_ok", "falla_mecanica_puerta", "", "NO", "SI", CLASE_56, "L3 pulso 12.6V 450ms motor abierto varillaje alineado")
    agregar(CLASE_55, "CARROCERIA_NEUMATICA", "L3", "Diagnóstico de red de confort en módulo BCM: DTC B1318 por circuito de bloqueo de puerta delantera; osciloscopio en el mazo pasacables del pilar A detecta cable de masa de potencia cortado por fatiga de apertura de puerta; actuador en banco de pruebas externo funciona con 0.8A conforme.", "TECNICO", "OSCILOSCOPIO_PASACABLES_PILAR_A", "cable_masa_cortado_pasacables, dtc_b1318, actuador_banco_ok", "falla_cerradura_desalineada", "B1318", "NO", "SI", CLASE_56, "L3 cable cortado pasacables pilar A actuador banco ok B1318")

    # --- CLASE 56: Cerradura mecánica / pestillo trabado ---
    agregar(CLASE_56, "CARROCERIA_NEUMATICA", "L1", "Cierro la puerta del auto y rebota abierta, no engancha la traba.", "COTIDIANO", "CERRADO_PUERTA", "puerta_rebota_abierta_no_engancha", "NO_REPORTA", "", "SI", "NO", "", "L1 puerta rebota no engancha")
    agregar(CLASE_56, "CARROCERIA_NEUMATICA", "L1", "la manija de afuera esta floja como rota y la puerta no abre ni por dentro ni por fuera", "WHATSAPP", "INTENTO_APERTURA", "manija_floja_no_abre_por_dentro_ni_fuera", "NO_REPORTA", "", "SI", "NO", "", "L1 manija floja no abre dentro ni fuera")
    agregar(CLASE_56, "CARROCERIA_NEUMATICA", "L2", "El pestillo interior está trabado con una dureza extrema que dobla la varilla si se intenta forzar; el actuador eléctrico intenta destrabar y golpea con fuerza pero el trinquete mecánico está atascado.", "TALLER", "DESARME_TAPIZ_PUERTA", "pestillo_dureza_extrema_trinquete_atascado, actuador_empuja_fuerte", "falla_electrica_cierre", "", "NO", "SI", CLASE_55, "L2 trinquete atascado pestillo duro actuador empuja vs electrico")
    agregar(CLASE_56, "CARROCERIA_NEUMATICA", "L2", "Puerta del conductor descolgada 6 mm por desgaste de los pasadores de las bisagras; el cerrojo pega contra el perno cerrador del parante B requiriendo un golpe violento para cerrar.", "TALLER", "INSPECCION_ALINEACION_BISAGRAS", "puerta_descolgada_6mm_bisagras, cerrojo_pega_perno_parante", "falla_actuador_puerta", "", "NO", "SI", CLASE_55, "L2 puerta descolgada 6mm cerrojo roza perno vs actuador")
    agregar(CLASE_56, "CARROCERIA_NEUMATICA", "L3", "Inspección mecánica de cerradura con calibre: uña de bloqueo de acero presenta muelle espiral de retorno partido en dos partes; el trinquete giratorio queda en posición cerrada impidiendo abrazar el pasador del chasis; señal de sensor de puerta abierta funciona eléctricamente en 0V y 12V.", "TECNICO", "DESARME_CERRADURA_MECANICA_PUERTA", "muelle_retorno_trinquete_roto, cerradura_rebota, microswitch_ok", "falla_cierre_centralizado", "", "NO", "SI", CLASE_55, "L3 muelle retorno trinquete partido microswitch ok")
    agregar(CLASE_56, "CARROCERIA_NEUMATICA", "L3", "Desmontaje de chapa de puerta trasera: varilla metálica de accionamiento de la manija exterior desacoplada por fractura del clip plástico de sujeción de nylon; se comprueba pestillo libre y traba de seguridad para niños desactivada; cerrojo funciona manualmente de forma impecable una vez recolocada la varilla.", "TECNICO", "INSPECCION_VARILLAJE_NYLON", "clip_nylon_sujecion_fracturado, varilla_desacoplada", "falla_actuador_electrico", "", "NO", "SI", CLASE_55, "L3 clip nylon partido varilla desacoplada pestillo ok")

    # --- CLASE 57: Elevalunas eléctrico / guaya rota ---
    agregar(CLASE_57, "CARROCERIA_NEUMATICA", "L1", "Sonó un chasquido fuerte adentro de la puerta y el vidrio se cayó hasta el fondo.", "COTIDIANO", "ACCIONAMIENTO_VENTANA", "chasquido_puerta_vidrio_cae_al_fondo", "NO_REPORTA", "", "SI", "NO", "", "L1 chasquido vidrio cae al fondo")
    agregar(CLASE_57, "CARROCERIA_NEUMATICA", "L1", "aprieto el boton para subir el vidrio suena el motorcito girar pero la ventana no sube nada", "WHATSAPP", "SUBIR_VENTANA", "motorcito_gira_ventana_no_sube", "NO_REPORTA", "", "SI", "NO", "", "L1 motorcito gira ventana no sube")
    agregar(CLASE_57, "CARROCERIA_NEUMATICA", "L2", "El vidrio sube torcido hacia adelante y se traba a mitad de camino; al quitar el tapiz se observa la guaya de acero deshilachada y trabada en la polea de plástico blanca.", "TALLER", "INSPECCION_TAPIZ_ELEVALUNAS", "vidrio_sube_torcido_traba, guaya_acero_deshilachada_polea", "falla_bateria", "", "NO", "SI", CLASE_48, "L2 vidrio torcido guaya deshilachada en polea")
    agregar(CLASE_57, "CARROCERIA_NEUMATICA", "L2", "Al accionar el interruptor de la ventana no hay ruido ni movimiento; prueba con lámpara lógica en la ficha del motor confirma 12V y masa presentes; motor eléctrico con bobinado quemado.", "TALLER", "LAMPARA_LOGICA_FICHA_MOTOR", "12v_y_masa_presentes, motor_elevalunas_quemado", "falla_boton_elevalunas", "", "NO", "SI", CLASE_55, "L2 12V presentes motor elevalunas quemado vs boton")
    agregar(CLASE_57, "CARROCERIA_NEUMATICA", "L3", "Diagnóstico de mecanismo de alzacristales tipo tijera con cable Bowden: cable de acero trenzado cortado por fricción con desprendimiento de un extremo del carro deslizante; motorreductor eléctrico consume 2.1A en vacío girando libremente sin arrastrar la luna; colisas laterales de goma limpias sin resistencia.", "TECNICO", "INSPECCION_CABLE_BOWDEN_CARRO", "cable_bowden_cortado_carro_suelto, motor_2_1a_vacio_ok", "falla_motor_elevalunas", "", "NO", "SI", CLASE_55, "L3 cable Bowden cortado motor consume 2.1A en vacio")
    agregar(CLASE_57, "CARROCERIA_NEUMATICA", "L3", "Prueba con pinza amperimétrica en interruptor de ventana del conductor: al solicitar subida de ventana el motor consume 24 Amperios de bloqueo continuo (nominal 4.5A a 6.0A) por patín plástico de arrastre descarrilado y acuñado en el riel de chapa; luna de cristal templado sin fisuras.", "TECNICO", "PINZA_AMPERIMETRICA_MOTOR_VENTANA", "consumo_bloqueo_24a_patin_descarrilado, riel_cunado", "falla_modulo_confort", "B1402", "NO", "SI", CLASE_55, "L3 consumo 24A patin descarrilado acunado B1402")

    # --- CLASE 58: Limpiaparabrisas / motor pluma ---
    agregar(CLASE_58, "CARROCERIA_NEUMATICA", "L1", "Bajo lluvia torrencial prendí los limpiaparabrisas y se quedaron tiesos a mitad del vidrio.", "COTIDIANO", "LLUVIA_FUERTE", "limpiaparabrisas_tiesos_mitad_vidrio", "NO_REPORTA", "", "SI", "NO", "", "L1 parabrisas tiesos a mitad vidrio")
    agregar(CLASE_58, "CARROCERIA_NEUMATICA", "L1", "las plumas barren lentisimo como si pesaran cien kilos y salio olor a quemado", "WHATSAPP", "USO_LIMPIAPARABRISAS", "plumas_barren_lentisimo_olor_quemado", "NO_REPORTA", "", "SI", "NO", "", "L1 plumas lentisimas olor quemado")
    agregar(CLASE_58, "CARROCERIA_NEUMATICA", "L2", "El motor del limpiaparabrisas no funciona en ninguna velocidad pero el lavaparabrisas tira agua; fusible principal de 20A intacto y relé conmuta audiblemente en la caja de fusibles.", "TALLER", "COMPROBACION_FUSIBLE_RELE_PLUMAS", "motor_plumas_muerto, fusible_rele_ok, sapito_tira_agua", "falla_alternador", "", "NO", "SI", CLASE_47, "L2 motor plumas muerto fusible y rele ok vs alternador")
    agregar(CLASE_58, "CARROCERIA_NEUMATICA", "L2", "Brazos limpiaparabrisas desacoplados: el motor eléctrico gira pero las plumas no se mueven; rótula plástica de la biela del varillaje articulado partida debajo de la rejilla torpedera.", "TALLER", "DESARME_TORPEDERA_VARILLAJE", "motor_gira_plumas_no_mueven, rotula_varillaje_partida", "falla_motor_quemado", "", "NO", "SI", CLASE_47, "L2 motor gira varillaje articulado partido")
    agregar(CLASE_58, "CARROCERIA_NEUMATICA", "L3", "Diagnóstico de motor de limpiaparabrisas en banco: conector de 5 pines recibe 12.8V en pin de velocidad baja y 12.8V en alta pero el motor no gira; medición de resistencia del estator arroja 0.2 Ohmios por devanado inducido en cortocircuito térmico con olor a resina calcinada; varillaje mecánico en vacío gira libre a mano.", "TECNICO", "BANCO_MOTOR_LIMPIAPARABRISAS", "motor_devanado_en_corto_0_2_ohmios, alimentacion_12_8v_ok, varillaje_suave", "falla_bateria", "B1420", "NO", "SI", CLASE_48, "L3 motor limpiaparabrisas devanado en corto B1420 varillaje suave")
    agregar(CLASE_58, "CARROCERIA_NEUMATICA", "L3", "Comprobación de mecanismo pantográfico de limpiaparabrisas: los ejes de pivote de los brazos presentan agarrotamiento severo por corrosión galvánica entre aluminio y acero; par de torsión requerido para mover el pantógrafo sin motor supera los 18 Nm (especificación < 1.5 Nm), provocando que el fusible térmico interno del motor abra por sobrecorriente.", "TECNICO", "TORQUIMETRO_PIVOTES_PANTOGRAFO", "pivotes_agarrotados_18nm_vs_1_5nm, fusible_termico_abierto", "falla_motor_electrico", "", "NO", "SI", CLASE_48, "L3 pivotes agarrotados 18 Nm fusible termico abre")

    # --- CLASE 59: Fugas de aire frenos neumáticos (Camiones) ---
    agregar(CLASE_59, "CARROCERIA_NEUMATICA", "L1", "El camión amanece con los tanques de aire vacíos en cero libras todas las mañanas.", "COTIDIANO", "REPOSO_NOCTURNO_CAMION", "tanques_aire_en_cero_cada_manana", "NO_REPORTA", "", "SI", "NO", "", "L1 camion amanece sin aire tanques en cero")
    agregar(CLASE_59, "CARROCERIA_NEUMATICA", "L1", "chilla un escape de aire continuo abajo del chasis cada vez que aprieto el pedal del freno", "WHATSAPP", "PISAR_FRENO_CAMION", "escape_aire_continuo_chasis_al_frenar", "NO_REPORTA", "", "SI", "NO", "", "L1 escape aire chasis al frenar")
    agregar(CLASE_59, "CARROCERIA_NEUMATICA", "L2", "Caída de presión neumática de 120 psi a 80 psi en solo 3 minutos con motor apagado; solución jabonosa revela burbujas abundantes en racor acodado de tubería de poliamida hacia calderín primario.", "TALLER", "PRUEBA_JABONOSA_CALDERIN", "caida_120_a_80psi_3min, burbujas_racor_poliamida", "falla_secador_aps", "", "NO", "SI", CLASE_60, "L2 caida 120 a 80 psi en 3 min burbujas racor vs secador")
    agregar(CLASE_59, "CARROCERIA_NEUMATICA", "L2", "Válvula de pedal de freno neumático (Treadle Valve) descarga aire continuo por el escape inferior con el pedal suelto; sello de obturador cónico desgastado.", "TALLER", "INSPECCION_VALVULA_PEDAL", "treadle_valve_fuga_por_escape_pedal_suelto, sello_conico_roto", "falla_maxi_brake", "", "NO", "SI", CLASE_61, "L2 valvula pedal fuga continuo con pedal suelto vs maxi")
    agregar(CLASE_59, "CARROCERIA_NEUMATICA", "L3", "Prueba de hermeticidad estática según normativa FMVSS 121 en camión tracto: con frenos aplicados a 6.0 bar y motor apagado, la tasa de fuga registra 0.48 bar/min (máximo reglamentario 0.20 bar/min); transductor ultrasónico de 40 kHz detecta fuga puntual de 22 L/min en racor rápido Voss de manguera de alimentación de eje tándem.", "TECNICO", "ULTRASONIDO_FMVSS121_CAMION", "tasa_fuga_0_48bar_min_vs_0_20, ultrasonido_40khz_22l_min", "falla_freno_hidraulico", "", "NO", "SI", CLASE_30, "L3 FMVSS 121 fuga 0.48 bar min ultrasonido 40kHz 22 L min")
    agregar(CLASE_59, "CARROCERIA_NEUMATICA", "L3", "Evaluación de tiempo de recuperación de presión de aire con manómetros patrones en calderines húmedo y seco: compresor bicilíndrico tarda 5 minutos y 10 segundos en elevar presión de 6.0 bar a 8.5 bar a 1800 RPM (tolerancia OEM 1 min 45 s); láminas de descarga de culata de compresor con fuga y carbonilla; tanques sin perforaciones.", "TECNICO", "CRONOMETRO_RECUPERACION_PRESION_AIRE", "recuperacion_5m10s_vs_1m45s_oem, laminas_compresor_carbonilla", "falla_valvula_secador", "", "NO", "SI", CLASE_60, "L3 recuperacion presion 5m10s vs 1m45s laminas compresor")

    # --- CLASE 60: Válvula secador APS obstruido (Camiones) ---
    agregar(CLASE_60, "CARROCERIA_NEUMATICA", "L1", "El secador de aire del camión estornuda a cada ratito cada 20 segundos sin parar.", "COTIDIANO", "RALENTI_CAMION", "secador_estornuda_cada_20s_continuo", "NO_REPORTA", "", "SI", "NO", "", "L1 secador estornuda cada 20s")
    agregar(CLASE_60, "CARROCERIA_NEUMATICA", "L1", "drene los tanques de aire y salio un chorro de agua con aceite negro espeso", "WHATSAPP", "PURGA_TANQUES_AIRE", "agua_con_aceite_negro_en_tanques_aire", "NO_REPORTA", "", "SI", "NO", "", "L1 agua y aceite en tanques aire")
    agregar(CLASE_60, "CARROCERIA_NEUMATICA", "L2", "Presión en tanques de freno no pasa de 7.5 bar y el compresor no descarga; cartucho desecante coalescente con 2 años sin cambio totalmente colmatado de emulsión oleosa.", "TALLER", "INSPECCION_CARTUCHO_SECADOR", "presion_estancada_7_5bar, cartucho_desecante_colmatado", "fuga_lineas_aire", "", "NO", "SI", CLASE_59, "L2 presion estancada 7.5 bar cartucho secador tapado vs fuga")
    agregar(CLASE_60, "CARROCERIA_NEUMATICA", "L2", "Válvula de cuatro vías de protección de circuitos no reparte aire al circuito de remolque; circuito 23 trabado en 0 bar mientras circuitos 21 y 22 tienen 9 bar correctos.", "TALLER", "MANOMETRO_VALVULA_4_VIAS", "circuito_23_bloqueado_0bar, c21_c22_con_9bar", "falla_maxi_brake", "", "NO", "SI", CLASE_61, "L2 circuito 23 en 0 bar valvula 4 vias vs maxi")
    agregar(CLASE_60, "CARROCERIA_NEUMATICA", "L3", "Diagnóstico de unidad de procesamiento de aire Knorr-Bremse EAC2: medición de presión diferencial a través del filtro coalescente arroja delta P de 3.2 bar (umbral máximo 0.6 bar); electroválvula de purga de regeneración registra circuito abierto en banco; punto de rocío del aire comprimido desciende a solo +8°C a 7 bar por saturación de zeolitas.", "TECNICO", "PRESION_DIFERENCIAL_PUNTO_ROCIO", "delta_p_3_2bar_cartucho, punto_rocio_mas8c_saturado", "fuga_calderin_aire", "", "NO", "SI", CLASE_59, "L3 delta P cartucho 3.2 bar punto rocio +8C zeolitas saturadas")
    agregar(CLASE_60, "CARROCERIA_NEUMATICA", "L3", "Inspección de resistencia calefactora de secador de aire Wabco Air Processing Unit (APU) a 24V: multímetro mide resistencia infinita en bornes del termostato de descongelamiento; en ruta nocturna a -2°C la tobera de descarga de purga se congela por carámbanos de hielo impidiendo el alivio del compresor.", "TECNICO", "MULTIMETRO_CALEFACTOR_24V_APU", "calefactor_24v_abierto_infinito, congelamiento_tobera_menos2c", "falla_maxi_brake", "", "NO", "SI", CLASE_61, "L3 calefactor APU 24V abierto hielo en tobera -2C")

    # --- CLASE 61: Actuador Maxi-Brake trabado (Camiones) ---
    agregar(CLASE_61, "CARROCERIA_NEUMATICA", "L1", "Suelto la válvula de parqueo amarilla del camión pero el eje trasero no destraba y arrastra las llantas.", "COTIDIANO", "QUITAR_PARQUEO_CABINA", "eje_trasero_no_destraba_arrastra_llantas", "NO_REPORTA", "", "SI", "NO", "", "L1 eje trasero arrastra llantas parqueo suelto")
    agregar(CLASE_61, "CARROCERIA_NEUMATICA", "L1", "una campana trasera esta ardiendo en fuego y echa humo tras rodar dos kilometros", "WHATSAPP", "MARCHA_CORTA_CAMION", "campana_trasera_ardiendo_humo", "NO_REPORTA", "", "SI", "NO", "", "L1 campana trasera ardiendo humo")
    agregar(CLASE_61, "CARROCERIA_NEUMATICA", "L2", "Presión en calderines en 115 psi normales en manómetro pero la cámara de resorte Maxi-Brake del lado derecho no comprime el muelle; vástago trabado en aplicación continua.", "TALLER", "INSPECCION_CAMARA_MAXI", "tanques_115psi_ok, maxi_brake_vastago_no_retrocede", "fuga_linea_aire", "", "NO", "SI", CLASE_59, "L2 tanques 115 psi ok Maxi derecho no retrocede vs fuga")
    agregar(CLASE_61, "CARROCERIA_NEUMATICA", "L2", "Al enroscar el perno de liberación manual de emergencia (caging bolt) en la cámara combinada trasera la rueda destraba de inmediato y gira libre en el foso.", "TALLER", "PERNO_CAGING_BOLT_FOSO", "caging_bolt_destraba_rueda_gira_libre", "falla_balatas_freno", "", "NO", "SI", CLASE_27, "L2 caging bolt destraba rueda gira libre")
    agregar(CLASE_61, "CARROCERIA_NEUMATICA", "L3", "Inspección metrológica de carrera de actuador doble tipo 30/30 en banco neumático: al aplicar 8.2 bar en el puerto 12 de estacionamiento, el vástago solo retrocede 12 mm (carrera nominal de desenganche 48 mm a 52 mm); muelle helicoidal acumulador fracturado con espiras montadas que traban el plato de presión interno.", "TECNICO", "BANCO_CARRERA_MAXI_BRAKE", "carrera_desenganche_12mm_vs_50mm, resorte_fracturado_espiras_montadas", "falla_valvula_4_vias", "", "NO", "SI", CLASE_60, "L3 carrera 12 vs 50mm muelle acumulador fracturado espiras montadas")
    agregar(CLASE_61, "CARROCERIA_NEUMATICA", "L3", "Comprobación de hermeticidad interna entre cámaras de servicio y emergencia en actuador Maxi-Brake: al alimentar 7.0 bar en puerto de parqueo se registra fuga cruzada de 28 L/min hacia el puerto de servicio por rotura de junta central de labio; leva S-cam queda retenida con sobrecarga mecánica de 18 kN que bloquea la campana.", "TECNICO", "CAUDALIMETRO_FUGA_CRUZADA_MAXI", "fuga_cruzada_28l_min_junta_central, leva_s_cam_sobrecarga_18kn", "caliper_freno_trabado", "", "NO", "SI", CLASE_33, "L3 fuga cruzada 28 L min junta central rota leva S-cam 18 kN")

    return casos
