"""
Generador de casos de test ciego TEST10 para Clases 27 a 41 (FRENOS y TRANSMISION).
Exactamente 15 clases x 6 casos = 90 registros (2 L1, 2 L2, 2 L3 por clase).
Totalmente independientes, sin solapamiento léxico ni contaminación con Fase 10 o benchmarks.
"""

from typing import List, Dict
import sys
from pathlib import Path

sys.path.insert(0, str(Path("backend").resolve()))
from src.core.diagnostico.taxonomia_sistemas import FALLA_A_SISTEMA

keys = list(FALLA_A_SISTEMA.keys())

# Clases 27 a 33 (FRENOS)
CLASE_27 = keys[26]  # Desgaste de pastillas y zapatas de freno
CLASE_28 = keys[27]  # Discos de freno alabeados o desgastados
CLASE_29 = keys[28]  # Falla en servofreno (booster) o linea de vacio
CLASE_30 = keys[29]  # Fuga hidraulica o aire en el sistema de frenos
CLASE_31 = keys[30]  # Falla en sensor de velocidad de rueda ABS
CLASE_32 = keys[31]  # Falla en sistema de frenado regenerativo (EV / Hibridos)
CLASE_33 = keys[32]  # Caliper de freno trabado o mordaza pegada (piston agarrotado)

# Clases 34 a 41 (TRANSMISION)
CLASE_34 = keys[33]  # Disco de embrague desgastado o patinando
CLASE_35 = keys[34]  # Falla en bombin o bomba hidraulica de embrague
CLASE_36 = keys[35]  # Falta o degradacion de aceite de caja de cambios
CLASE_37 = keys[36]  # Rodajes de caja mecanica o diferencial gastados
CLASE_38 = keys[37]  # Sobrecalentamiento o solenoides en caja automatica CVT / DSG
CLASE_39 = keys[38]  # Falla en caja robotizada Dualogic / I-Motion / Easytronic (Fiat / VW)
CLASE_40 = keys[39]  # Desgaste en collarin de empuje o crapodina de embrague
CLASE_41 = keys[40]  # Rodajes de transmision manual o eje primario gastados

MACRO_FRENOS = "FRENOS"
MACRO_TRANS = "TRANSMISION"
FUENTE = "SINTETICO_TEST_CIEGO"


def obtener_test10_parte3(offset: int = 157) -> List[Dict[str, str]]:
    casos = []
    idx = offset

    def agregar(clase, macro, nivel, texto, lenguaje, condicion, sp, sn, dtc, req_p, es_c, c_cont, obs):
        nonlocal idx
        reg_id = f"TEST10-{idx:04d}"
        grp_id = f"G-TEST10-{idx:04d}"
        casos.append({
            "id": reg_id,
            "id_grupo": grp_id,
            "clase_objetivo": clase,
            "macro_sistema": macro,
            "nivel_informacion": nivel,
            "texto_usuario": texto,
            "tipo_lenguaje": lenguaje,
            "condicion_operacion": condicion,
            "sintomas_presentes": sp,
            "sintomas_negados": sn,
            "dtc": dtc,
            "requiere_pregunta": req_p,
            "es_contrastivo": es_c,
            "clase_contrastiva": c_cont,
            "fuente": FUENTE,
            "observaciones": obs
        })
        idx += 1

    # --- CLASE 27: Pastillas y zapatas de freno ---
    agregar(CLASE_27, MACRO_FRENOS, "L1", "Cada vez que rozo el pedal para bajar la velocidad suena un chirrido de lata.", "COTIDIANO", "FRENADO_SUAVE", "chirrido_lata_al_frenar", "NO_REPORTA", "", "SI", "NO", "", "L1 chirrido lata freno suave")
    agregar(CLASE_27, MACRO_FRENOS, "L1", "raspa fierro contra fierro en la rueda delantera derecha al parar", "WHATSAPP", "DETENCION_FINAL", "raspa_fierro_con_fierro_frenada", "NO_REPORTA", "", "SI", "NO", "", "L1 raspa fierro con fierro")
    agregar(CLASE_27, MACRO_FRENOS, "L2", "Chirrido estridente al frenar hacia adelante; testigo mecánico sonoro de desgaste roza contra el disco; espesor visual del material de fricción en apenas 1.5 mm.", "TALLER", "INSPECCION_RUEDA_DESMONTADA", "avisador_acustico_roza, material_friccion_1_5mm", "falla_disco_alabeado", "", "NO", "SI", CLASE_28, "L2 avisador acustico 1.5 mm vs alabeo")
    agregar(CLASE_27, MACRO_FRENOS, "L2", "Pedal de freno con recorrido largo pero esponjoso ausente; zapatas del tambor trasero gastadas al remache rayando la campana interior.", "TALLER", "DESARME_TAMBOR_TRASERO", "zapatas_al_remache, recorrido_largo_pedal", "fuga_liquido_frenos", "", "NO", "SI", CLASE_30, "L2 zapatas al remache tambor rayado")
    agregar(CLASE_27, MACRO_FRENOS, "L3", "Inspección metrológica con pie de rey en pastillas de freno delanteras: espesor de material de fricción remanente de 1.1 mm en pastilla interior y 2.0 mm en exterior (espesor mínimo admisible 3.0 mm); disco de freno sin reborde pronunciado de 21.8 mm (mínimo 20.0 mm); pinza flotante desliza suavemente.", "TECNICO", "METROLOGIA_PASTILLAS_CALIBRE", "espesor_1_1mm_pastilla_interior, disco_21_8mm_ok, guias_suaves", "caliper_trabado", "", "NO", "SI", CLASE_33, "L3 espesor 1.1mm calibre disco ok guias suaves")
    agregar(CLASE_27, MACRO_FRENOS, "L3", "Evaluación de tambor y zapatas de eje posterior en frenómetro de rodillos: desequilibrio de frenado trasero del 18%; desmontaje confirma forro de fricción de zapata primaria con espesor de 0.8 mm cristalizado por calor; cilindro de rueda esclavo seco sin fugas de líquido hidráulico.", "TECNICO", "FRENOMETRO_RODILLOS_TAMBOR", "desequilibrio_18porciento_trasero, forro_zapata_0_8mm, cilindro_seco", "fuga_cilindro_rueda", "", "NO", "SI", CLASE_30, "L3 frenometro forro 0.8mm cilindro esclavo seco")

    # --- CLASE 28: Discos alabeados ---
    agregar(CLASE_28, MACRO_FRENOS, "L1", "El volante me tirita de un lado a otro y el pedal pulsa cuando freno a 100 en la carretera.", "COTIDIANO", "FRENADA_ALTA_VELOCIDAD", "volante_tirita_pedal_pulsa_frenar", "NO_REPORTA", "", "SI", "NO", "", "L1 volante tirita pedal pulsa a 100")
    agregar(CLASE_28, MACRO_FRENOS, "L1", "el carro cabecea adelante y tiembla todo el tablero solo al pisar el freno bajando", "WHATSAPP", "FRENADA_PENDIENTE", "cabeceo_tablero_al_frenar_bajada", "NO_REPORTA", "", "SI", "NO", "", "L1 cabeceo tablero al frenar bajando")
    agregar(CLASE_28, MACRO_FRENOS, "L2", "Vibración pulsante en el pedal de freno que aumenta proporcional a la velocidad; las pastillas tienen 80% de vida útil; superficie del disco presenta manchas azules térmicas (hot spots).", "TALLER", "PRUEBA_RUTA_VIBRACION", "pulsacion_pedal_velocidad, hot_spots_azules_disco, pastillas_ok", "falla_pastillas_freno", "", "NO", "SI", CLASE_27, "L2 pulsacion pedal manchas azules pastillas ok")
    agregar(CLASE_28, MACRO_FRENOS, "L2", "Al frenar fuerte en recta el timón sacude violentamente las manos pero al rodar libre sin frenar no vibra nada; llantas balanceadas en 0 gramos.", "TALLER", "BALANCEO_DESCARTADO", "sacudida_timon_solo_al_frenar, balanceo_llantas_0g", "llantas_desbalanceadas", "", "NO", "SI", keys[43], "L2 sacudida timon solo al frenar balanceo 0g ok")
    agregar(CLASE_28, MACRO_FRENOS, "L3", "Medición de alabeo lateral con reloj comparador milesimal fijado a la mangueta: disco delantero izquierdo registra deflexión de 0.14 mm en el borde exterior (tolerancia máxima de alabeo OEM 0.04 mm); variación de espesor del disco (DTV) de 0.028 mm con micrómetro de exteriores; rodamiento de masa sin holgura (0.01 mm).", "TECNICO", "RELOJ_COMPARADOR_ALABEO_DISCO", "alabeo_0_14mm_vs_0_04mm_limite, dtv_0_028mm, rodamiento_ok", "falla_rodamiento_maza", "", "NO", "SI", keys[45], "L3 reloj comparador alabeo 0.14mm DTV 0.028mm")
    agregar(CLASE_28, MACRO_FRENOS, "L3", "Verificación de discos traseros ventilados con micrómetro de disco: espesor medido en cuatro cuadrantes arroja 18.2 mm, 18.15 mm, 18.26 mm y 18.14 mm con alabeo de 0.09 mm; al frenar desde 120 km/h en banco dinamométrico se registran picos de desaceleración fluctuantes de 4.2 m/s² a 6.8 m/s² por ondulación de pista.", "TECNICO", "BANCO_DINAMOMETRICO_DESACELERACION", "alabeo_0_09mm_ondulacion, fluctuacion_desaceleracion_frenado", "falla_caliper_mordaza", "", "NO", "SI", CLASE_33, "L3 micrometro cuadrantes alabeo 0.09mm dinamometro")

    # --- CLASE 29: Servofreno (booster) / línea de vacío ---
    agregar(CLASE_29, MACRO_FRENOS, "L1", "El pedal de freno está durísimo como un tabique y tengo que pararme encima para que pare.", "COTIDIANO", "INTENTO_FRENADO", "pedal_durismo_tabique, requiere_pararse", "NO_REPORTA", "", "SI", "NO", "", "L1 pedal duro tabique pararse")
    agregar(CLASE_29, MACRO_FRENOS, "L1", "suena como un chistido de aire por debajo del volante cada vez que piso el freno", "WHATSAPP", "PISAR_FRENO_CABINA", "chistido_aire_bajo_volante_al_frenar", "NO_REPORTA", "", "SI", "NO", "", "L1 chistido aire bajo volante")
    agregar(CLASE_29, MACRO_FRENOS, "L2", "Al pisar el freno en ralentí el motor tiembla y amaga con apagarse; se escucha silbido de succión de aire dentro de la cabina junto a la pedalera.", "TALLER", "PRUEBA_VACIO_RALENTI", "motor_tiembla_pisar_freno, silbido_succion_pedalera", "falla_cuerpo_aceleracion", "", "NO", "SI", keys[4], "L2 silbido pedalera motor tiembla vs IAC")
    agregar(CLASE_29, MACRO_FRENOS, "L2", "Prueba funcional de servofreno: al bombear 5 veces con motor apagado el pedal sube, pero al encender el motor el pedal no desciende ni un milímetro; manguera de vacío con válvula check rota.", "TALLER", "TEST_CONVENCIONAL_BOOSTER", "pedal_no_baja_al_arrancar, valvula_check_vacio_rota", "falla_bomba_freno_hidraulica", "", "NO", "SI", CLASE_30, "L2 test booster pedal no baja al arrancar check rota")
    agregar(CLASE_29, MACRO_FRENOS, "L3", "Medición con vacuómetro analógico en cámara de vacío de servofreno: el colector entrega 21 inHg pero en la entrada del booster se registran solo 6 inHg por fisura en la tubería plástica corrugada; diafragma interno del booster con fuga de 18 L/min en la junta del vástago de empuje de pedalera.", "TECNICO", "VACUOMETRO_CAMARA_BOOSTER", "vacio_booster_6inhg_vs_21inhg_motor, fuga_vastago_18l_min", "falla_cilindro_maestro", "", "NO", "SI", CLASE_30, "L3 vacuometro 6 vs 21 inHg fuga vastago 18 L/min")
    agregar(CLASE_29, MACRO_FRENOS, "L3", "Diagnóstico de bomba de vacío mecánica en motor diésel: depresor acoplado al árbol de levas genera apenas 0.35 bar de depresión (especificación 0.85 bar en 3 segundos tras soltar pedal); al pisar el freno dos veces seguidas la asistencia colapsa y el esfuerzo sobre el pedal escala de 120 N a 480 N para 0.4g de frenada.", "TECNICO", "PRUEBA_DEPRESOR_VACIO_DIESEL", "depresor_0_35bar_insuficiente, esfuerzo_pedal_escala_480n", "falla_caliper_pegado", "", "NO", "SI", CLASE_33, "L3 depresor diesel 0.35 bar esfuerzo pedal 480N")

    # --- CLASE 30: Fuga hidráulica / aire en frenos ---
    agregar(CLASE_30, MACRO_FRENOS, "L1", "Piso el pedal del freno y se va despacito hasta el fondo de la alfombra sin frenar casi nada.", "COTIDIANO", "DETENCION_SUAVE", "pedal_se_va_al_fondo_alfombra", "NO_REPORTA", "", "SI", "NO", "", "L1 pedal se hunde al fondo")
    agregar(CLASE_30, MACRO_FRENOS, "L1", "tengo que bombear tres veces seguidas para que el freno agarre y frene bien", "WHATSAPP", "CIRCULACION_CALLE", "requiere_bombear_3_veces_para_frenar", "NO_REPORTA", "", "SI", "NO", "", "L1 bombear 3 veces para frenar")
    agregar(CLASE_30, MACRO_FRENOS, "L2", "Nivel de líquido de frenos DOT 4 en el depósito por debajo del mínimo; manguera flexible de goma de la rueda trasera izquierda hinchada con mancha húmeda de goteo.", "TALLER", "INSPECCION_FLEXIBLES_FRENOS", "deposito_bajo_minimo, flexible_freno_hinchado_goteo", "desgaste_pastillas", "", "NO", "SI", CLASE_27, "L2 flexible hinchado deposito bajo minimo vs pastillas")
    agregar(CLASE_30, MACRO_FRENOS, "L2", "Pedal esponjoso y blando tras cambio de pastillas; el sistema tiene burbujas de aire por purga incompleta; al bombear recupera altura momentánea.", "TALLER", "PURGA_SISTEMA_FRENOS", "pedal_esponjoso_aire_circuito, recupera_altura_al_bombear", "falla_booster", "", "NO", "SI", CLASE_29, "L2 pedal esponjoso aire en purga vs booster")
    agregar(CLASE_30, MACRO_FRENOS, "L3", "Prueba de estanqueidad estática con presurizador de pedal a 80 bar: la presión cae a 45 bar en 60 segundos sin fugas externas visibles; desmontaje del cilindro maestro (bomba de freno) revela cubetas de goma primarias rayadas con bypass interno de fluido entre cámaras; depósito sin pérdida volumétrica externa.", "TECNICO", "PRESURIZADOR_CILINDRO_MAESTRO", "caida_80_a_45bar_bypass_interno, cubetas_bomba_rayadas", "fuga_caliper", "", "NO", "SI", CLASE_33, "L3 presurizador bypass interno cubetas rayadas")
    agregar(CLASE_30, MACRO_FRENOS, "L3", "Inspección de cañería rígida de acero de freno trasero: corrosión perforante por salinidad genera fuga en abocardado cónico con pérdida de 15 ml por cada frenada; purga presurizada a 2 bar expone chorro fino continuo hacia el chasis; pedal colapsa en la segunda aplicación.", "TECNICO", "PRESURIZADOR_PURGA_CANERIA", "fuga_abocardado_caneria_acero, perdida_15ml_frenada", "falla_booster", "", "NO", "SI", CLASE_29, "L3 caneria acero picada fuga abocardado 15ml")

    # --- CLASE 31: Sensor de velocidad de rueda ABS ---
    agregar(CLASE_31, MACRO_FRENOS, "L1", "Se prendió la luz amarilla de ABS en el tablero y a veces vibra el pedal en frenadas secas.", "COTIDIANO", "FRENADO_EN_SECO", "luz_abs_prendida, vibracion_pedal_seco", "NO_REPORTA", "", "SI", "NO", "", "L1 luz ABS pedal vibra en seco")
    agregar(CLASE_31, MACRO_FRENOS, "L1", "al parar despacio en una esquina se activa el abs solo pateando el pedal", "WHATSAPP", "FRENADA_BAJA_VELOCIDAD", "abs_activa_solo_baja_velocidad", "NO_REPORTA", "", "SI", "NO", "", "L1 ABS patea en baja velocidad")
    agregar(CLASE_31, MACRO_FRENOS, "L2", "Activación falsa del ABS a menos de 15 km/h en piso seco; escáner acusa código DTC C0035 sensor de velocidad de rueda delantera izquierda; cable con aislamiento cortado por roce con la barra estabilizadora.", "TALLER", "INSPECCION_CABLE_ABS", "dtc_c0035_rueda_izq, cable_cortado_estabilizadora", "falla_disco_alabeado", "C0035", "NO", "SI", CLASE_28, "L2 C0035 cable cortado estabilizadora vs alabeo")
    agregar(CLASE_31, MACRO_FRENOS, "L2", "Luz de ABS y control de tracción fijas; sensor de rueda magnético lleno de viruta metálica pegada en la punta impidiendo la lectura de los polos magnéticos del rodamiento.", "TALLER", "LIMPIEZA_PUNTA_SENSOR_ABS", "punta_sensor_llena_viruta, luces_abs_esp_fijas", "falla_rodamiento_maza", "", "NO", "SI", keys[45], "L2 viruta pegada en sensor ABS vs rodaje")
    agregar(CLASE_31, MACRO_FRENOS, "L3", "Osciloscopio digital en sensor ABS activo magnetorresistivo de 2 cables: a 30 km/h en banco de rodillos, la señal cuadrada de corriente cicla de 7 mA a 14 mA pero presenta pérdida periódica de 3 pulsos por vuelta (anillo codificador magnético en guardapolvo de rodamiento con sector desmagnetizado).", "TECNICO", "OSCILOSCOPIO_ABS_ACTIVO", "perdida_3_pulsos_vuelta_abs, anillo_magnetico_desmagnetizado", "falla_modulo_abs", "C0040", "NO", "SI", CLASE_30, "L3 oscilograma ABS activo perdida 3 pulsos anillo desmagnetizado")
    agregar(CLASE_31, MACRO_FRENOS, "L3", "Diagnóstico de sensor ABS pasivo inductivo delantero derecho: medición de resistencia eléctrica marca 1150 Ohmios conforme pero tensión alterna generada en giro de rueda a 60 RPM es de solo 45 mV pico a pico (nominal > 250 mV); entrehierro excesivo de 2.2 mm por óxido levantando el asiento del sensor en la mangueta.", "TECNICO", "MILIVOLTIMETRO_ENTREHIERRO_ABS", "senal_45mv_vs_250mv_minimo, entrehierro_oxido_2_2mm", "falla_sensor_abs", "C0037", "NO", "SI", CLASE_30, "L3 ABS inductivo 45 mV entrehierro 2.2mm oxido")

    # --- CLASE 32: Frenado regenerativo (EV / Híbridos) ---
    agregar(CLASE_32, MACRO_FRENOS, "L1", "Al soltar el acelerador el auto eléctrico no retiene nada y la barra de carga no sube.", "COTIDIANO", "DESACELERACION_LLANO", "electrico_no_retiene, barra_carga_no_sube", "NO_REPORTA", "", "SI", "NO", "", "L1 EV no retiene regeneracion")
    agregar(CLASE_32, MACRO_FRENOS, "L1", "frenada brusca con tiron irregular al cambiar entre el freno electrico y los discos", "WHATSAPP", "TRANSICION_FRENADO", "tiron_transicion_freno_electrico_discos", "NO_REPORTA", "", "SI", "NO", "", "L1 tiron transicion freno electrico")
    agregar(CLASE_32, MACRO_FRENOS, "L2", "En vehículo híbrido Toyota / Prius: código DTC C1391 por fuga anormal en acumulador de presión de frenos regenerativos; la bomba electrohidráulica de freno enciende cada 4 segundos de forma continua.", "TALLER", "DIAGNOSTICO_MODULO_FRENO_HIBRIDO", "dtc_c1391_fuga_acumulador, bomba_electrohidraulica_cada_4s", "falla_bomba_freno_convencional", "C1391", "NO", "SI", CLASE_30, "L2 C1391 Prius acumulador cicla cada 4s vs bomba")
    agregar(CLASE_32, MACRO_FRENOS, "L2", "Frenado regenerativo desactivado por alerta en módulo de control de tracción híbrido; al pisar el pedal la frenada es puramente mecánica y áspera con consumo alto de pastillas.", "TECNICO", "ESCANEO_MODULO_HIBRIDO", "regenerativo_inoperativo_solo_mecanico, alerta_control_freno", "falla_pastillas_freno", "", "NO", "SI", CLASE_27, "L2 regenerativo inoperativo solo mecanico vs pastillas")
    agregar(CLASE_32, MACRO_FRENOS, "L3", "Diagnóstico de simulador de carrera de pedal de freno (Stroke Sensor) en Nissan Leaf: escáner registra DTC C118A por discordancia entre sensor de ángulo de pedal y presión hidráulica regenerativa; lectura de canales 1 y 2 arroja 1.2V y 3.8V fijos sin respuesta al esfuerzo de pisada; servomotor electrohidráulico iBooster 100% operativo.", "TECNICO", "STROKE_SENSOR_LEAF_DATOS", "stroke_sensor_discordancia_c118a, voltajes_fijos_pedal", "falla_ibooster_mecanico", "C118A", "NO", "SI", CLASE_29, "L3 Leaf stroke sensor C118A discordancia iBooster ok")
    agregar(CLASE_32, MACRO_FRENOS, "L3", "Monitoreo de corriente regenerativa hacia batería de alto voltaje en frenada moderada de 60 a 0 km/h: corriente inversa registra 0.0A mientras la potencia de frenado mecánico absorbe el 100% del par; módulo inversor híbrido rechaza comando de regeneración por sobretemperatura de 94°C en sensor térmico de motor MG2.", "TECNICO", "CORRIENTE_REGENERACION_BMS", "corriente_inversa_0a_en_frenada, inversor_rechaza_temp_94c_mg2", "falla_inversor_igbt", "P0A3F", "NO", "SI", keys[49], "L3 corriente regeneracion 0A inversor 94C MG2")

    # --- CLASE 33: Caliper trabado / mordaza pegada ---
    agregar(CLASE_33, MACRO_FRENOS, "L1", "Una sola llanta delantera está hirviendo, huele a quemado y el carro se tira para ese lado.", "COTIDIANO", "MARCHA_AUTOPISTA", "llanta_hirviendo_tira_hacia_un_lado", "NO_REPORTA", "", "SI", "NO", "", "L1 llanta hirviendo tira a un lado")
    agregar(CLASE_33, MACRO_FRENOS, "L1", "siento el carro pesado como amarrado y la rueda izquierda bota humo al parar", "WHATSAPP", "PARADA_DESPUES_RUTA", "carro_amarrado_rueda_bota_humo", "NO_REPORTA", "", "SI", "NO", "", "L1 carro amarrado rueda bota humo")
    agregar(CLASE_33, MACRO_FRENOS, "L2", "Rueda delantera derecha con pastillas desgastadas al 100% en 5000 km mientras la izquierda tiene 90% de vida; pistón del cáliper con guardapolvo roto y óxido visible en la camisa.", "TALLER", "REVISION_DESGASTE_DISPAREJO", "desgaste_asimetrico_100_vs_10porciento, piston_caliper_oxidado", "falla_pastillas_freno", "", "NO", "SI", CLASE_27, "L2 desgaste asimetrico piston oxidado vs pastillas")
    agregar(CLASE_33, MACRO_FRENOS, "L2", "Con el auto levantado en el elevador la rueda trasera no gira libre con la mano tras pisar el freno; al aflojar el purgador el fluido no salta a presión pero la rueda sigue frenada (traba mecánica del pistón).", "TALLER", "TEST_PURGADOR_ELEVADOR", "rueda_trancada_purgador_abierto, traba_mecanica_caliper", "fuga_flexible_freno", "", "NO", "SI", CLASE_30, "L2 rueda trancada purgador abierto traba mecanica")
    agregar(CLASE_33, MACRO_FRENOS, "L3", "Termometría láser tras 10 km de autopista: disco delantero derecho a 285°C frente a 65°C en el disco izquierdo; desmontaje de pinza en banco expone pistón de acero cromado con corrosión picada de 0.4 mm que traba la retracción elástica del retén de sección cuadrada; correderas deslizantes de teflón lubricadas y libres.", "TECNICO", "TERMOMETRO_LASER_BANCO_CALIPER", "disco_285c_vs_65c_laser, piston_picado_oxido_0_4mm, correderas_ok", "falla_disco_alabeado", "", "NO", "SI", CLASE_28, "L3 laser 285C vs 65C piston picado 0.4mm correderas ok")
    agregar(CLASE_33, MACRO_FRENOS, "L3", "Inspección de pernos guía deslizantes de mordaza flotante trasera con freno de mano integrado: perno guía inferior totalmente agarrotado en el soporte por entrada de agua tras rotura de fuelle de goma; fuerza requerida para deslizar la pinza con dinamómetro de tracción manual supera los 650 N (nominal < 25 N).", "TECNICO", "DINAMOMETRO_TRACCION_GUIAS_CALIPER", "guias_deslizantes_agarrotadas_650n_vs_25n, fuelle_roto", "falla_pastillas_freno", "", "NO", "SI", CLASE_27, "L3 dinamometro 650N guias agarrotadas fuelle roto")

    # --- CLASE 34: Disco de embrague desgastado / patinando ---
    agregar(CLASE_34, MACRO_TRANS, "L1", "Acelero en subida, el motor ruge fuerte pero el carro casi no avanza y huele a quemado.", "COTIDIANO", "SUBIDA_EMPINADA", "motor_ruge_no_avanza_olor_quemado", "NO_REPORTA", "", "SI", "NO", "", "L1 motor ruge no avanza subida")
    agregar(CLASE_34, MACRO_TRANS, "L1", "se suben las revoluciones solas de golpe en cuarta cuando le piso a fondo", "WHATSAPP", "ACELERACION_CUARTA", "revoluciones_suben_solas_en_cuarta", "NO_REPORTA", "", "SI", "NO", "", "L1 RPM suben solas en 4ta")
    agregar(CLASE_34, MACRO_TRANS, "L2", "Al intentar salir en 3ra marcha con freno de mano aplicado el motor no se cala y sigue encendido a 1500 RPM patinando el embrague; pedal acopla en el último centímetro superior.", "TALLER", "PRUEBA_CALADO_EMBRAGUE", "motor_no_cala_tercera_marcha, pedal_acopla_arriba_todo", "falla_bomba_embrague", "", "NO", "SI", CLASE_35, "L2 no cala en 3ra pedal arriba del todo vs bomba")
    agregar(CLASE_34, MACRO_TRANS, "L2", "Fuerte olor a ferodo quemado tras maniobras de estacionamiento en rampa; el vehículo patina progresivamente en cambios altos (4ta y 5ta velocidad) bajo aceleración plena.", "TALLER", "PRUEBA_RUTA_CARGA", "olor_ferodo_quemado, patinamiento_4ta_5ta", "falla_caja_cambios", "", "NO", "SI", CLASE_36, "L2 olor ferodo patinamiento 4ta 5ta")
    agregar(CLASE_34, MACRO_TRANS, "L3", "Inspección visual y metrológica por ventana de registro de caja de cambios: forro de fricción de disco de embrague gastado al ras de las cabezas de remache de cobre (profundidad medida con calibre de profundidad en 0.05 mm vs mínimo 0.30 mm); placa de presión de embrague con decoloración azul violácea por sobrecalentamiento térmico.", "TECNICO", "CALIBRE_PROFUNDIDAD_REMACHES", "remaches_a_ras_0_05mm, placa_presion_azulada_termica", "falla_collarin_embrague", "", "NO", "SI", CLASE_40, "L3 calibre remaches 0.05mm placa azulada")
    agregar(CLASE_34, MACRO_TRANS, "L3", "Medición de desacoplamiento de RPM entre motor y eje primario mediante escáner y sensor VSS: a 3000 RPM de cigüeñal en 4ta marcha con mariposa al 100%, la velocidad de salida de transmisión acusa resbalamiento relativo del 28% sostenido; horquilla y sistema hidráulico de accionamiento retornan a tope sin retención mecánica.", "TECNICO", "TELEMETRIA_RESBALAMIENTO_EMBRAGUE", "resbalamiento_28porciento_telemetria, horquilla_retorna_tope", "falla_bombin_embrague", "", "NO", "SI", CLASE_35, "L3 telemetria resbalamiento 28% en 4ta horquilla libre")

    # --- CLASE 35: Bombín o bomba hidráulica de embrague ---
    agregar(CLASE_35, MACRO_TRANS, "L1", "El pedal de embrague se quedó pegado en el piso y no entran los cambios.", "COTIDIANO", "ARRANQUE_MANANA", "pedal_embrague_pegado_en_piso, cambios_no_entran", "NO_REPORTA", "", "SI", "NO", "", "L1 pedal embrague pegado piso")
    agregar(CLASE_35, MACRO_TRANS, "L1", "tengo que jalar el pedal con la punta del zapato para que suba de nuevo", "WHATSAPP", "MANIOBRA_CAMBIOS", "pedal_requiere_jalar_con_zapato", "NO_REPORTA", "", "SI", "NO", "", "L1 jalar pedal con zapato")
    agregar(CLASE_35, MACRO_TRANS, "L2", "Primera y retroceso raspan al meter el cambio con motor encendido; mancha húmeda de líquido DOT 4 en la alfombra interior debajo del pedal de embrague.", "TALLER", "INSPECCION_PEDALERA_INTERIOR", "fuga_dot4_alfombra_pedalera, primera_retroceso_raspan", "falla_sincronizadores_caja", "", "NO", "SI", CLASE_37, "L2 fuga DOT4 alfombra pedalera vs caja")
    agregar(CLASE_35, MACRO_TRANS, "L2", "Bombín auxiliar (esclavo) de embrague sobre la caja suda líquido hidráulico por el fuelle guardapolvo; el pedal pierde presión progresivamente si se mantiene pisado en el semáforo.", "TALLER", "FOSO_INSPECCION_BOMBIN", "bombin_esclavo_suda_liquido, pedal_pierde_presion_mantenido", "falla_disco_embrague", "", "NO", "SI", CLASE_34, "L2 bombin esclavo suda pedal cede mantenido")
    agregar(CLASE_35, MACRO_TRANS, "L3", "Prueba de hermeticidad hidráulica con manómetro de 50 bar en línea de embrague: al pisar el pedal y sostenerlo, la presión hidráulica cae de 28 bar a 8 bar en 15 segundos sin fugas exteriores; desmontaje de bomba principal de embrague confirma retén de émbolo primario gastado con bypass hacia el depósito.", "TECNICO", "PRESURIZADOR_CIRCUITO_EMBRAGUE", "presion_cae_28_a_8bar_15s_bypass, reten_embolo_desgastado", "falla_crapodina_collarin", "", "NO", "SI", CLASE_40, "L3 manometro 28 a 8 bar bypass interno bomba embrague")
    agregar(CLASE_35, MACRO_TRANS, "L3", "Diagnóstico de actuador concéntrico de desembrague hidráulico (CSC): líquido de frenos escurre profusamente por la ventana de unión entre campana de transmisión y motor; aire en el circuito que reingresa de inmediato tras purga manual; desmontaje confirma junta de estanqueidad de bombín concéntrico reventada.", "TECNICO", "INSPECCION_BOMBIN_CONCENTRICO_CSC", "escurrimiento_liquido_campana_caja, csc_reventado", "falla_disco_patinando", "", "NO", "SI", CLASE_34, "L3 escurrimiento campana bombin concentrico CSC reventado")

    # --- CLASE 36: Aceite de caja de cambios ---
    agregar(CLASE_36, MACRO_TRANS, "L1", "La palanca de cambios está durísima y raspan las marchas sobre todo en frío.", "COTIDIANO", "MANANAS_FRIO", "palanca_durisima_raspan_cambios_frio", "NO_REPORTA", "", "SI", "NO", "", "L1 palanca dura raspan marchas frio")
    agregar(CLASE_36, MACRO_TRANS, "L1", "zumba la caja de cambios cuando voy en quinta pero si piso el embrague se calla", "WHATSAPP", "MARCHA_QUINTA", "zumbido_caja_quinta_calla_pisar_embrague", "NO_REPORTA", "", "SI", "NO", "", "L1 zumba caja quinta calla embrague")
    agregar(CLASE_36, MACRO_TRANS, "L2", "Tapón de nivel de caja manual retirado en foso: el nivel de valvulina está 25 mm por debajo del orificio de llenado; el fluido extraído sale negro espeso con olor a azufre requemado.", "TALLER", "INSPECCION_NIVEL_VALVULINA", "nivel_valvulina_25mm_bajo, aceite_negro_olor_azufre", "falla_disco_embrague", "", "NO", "SI", CLASE_34, "L2 nivel valvulina 25mm bajo negro requemado")
    agregar(CLASE_36, MACRO_TRANS, "L2", "En transmisión automática: tirones y resbalamiento al pasar de 2da a 3ra; varilla de medición muestra fluido ATF de color café oscuro con olor a tostado y burbujas de espuma.", "TALLER", "INSPECCION_VARILLA_ATF", "atf_color_cafe_olor_tostado, resbalamiento_2da_3ra", "falla_solenoides_caja", "", "NO", "SI", CLASE_38, "L2 ATF cafe tostado resbalamiento 2da a 3ra")
    agregar(CLASE_36, MACRO_TRANS, "L3", "Análisis espectrométrico de aceite de transmisión manual SAE 75W-90: contenido de partículas metálicas de cobre en 185 ppm y hierro en 340 ppm (desgaste severo acelerado por degradación de aditivos EP); viscosidad cinemática a 100°C cayó de 14.5 cSt a 8.2 cSt; tapón imantado con 12 gramos de viruta pastosa.", "TECNICO", "ANALISIS_LABORATORIO_LUBRICANTE", "viscosidad_8_2cst_vs_14_5cst, fe_340ppm_cu_185ppm, viruta_tapon", "falla_rodaje_caja", "", "NO", "SI", CLASE_37, "L3 analisis aceite viscosidad 8.2 vs 14.5 cSt Fe 340ppm")
    agregar(CLASE_36, MACRO_TRANS, "L3", "Evaluación de transmisión automática con escáner: temperatura de fluido ATF alcanza 128°C en ruta llana de 20 km (temperatura de trabajo máxima recomendada 90°C); presión de línea en puerto de prueba hidráulica cae 1.8 bar por pérdida de viscosidad del fluido degradado; solenoides de cambio responden con retardo.", "TECNICO", "TERMOMETRIA_PRESION_LINEA_ATF", "atf_128c_sobrecalentado, presion_linea_cae_1_8bar", "falla_enfriador_aceite", "", "NO", "SI", CLASE_38, "L3 ATF a 128C caida presion de linea 1.8 bar")

    # --- CLASE 37: Rodajes de caja mecánica o diferencial ---
    agregar(CLASE_37, MACRO_TRANS, "L1", "Suena un zumbido sordo tipo avión en la trompa que aumenta según la velocidad del carro.", "COTIDIANO", "VELOCIDAD_CARRETERA", "zumbido_tipo_avion_aumenta_velocidad", "NO_REPORTA", "", "SI", "NO", "", "L1 zumbido tipo avion aumenta vel")
    agregar(CLASE_37, MACRO_TRANS, "L1", "zumba fuerte cuando acelero y cuando suelto el acelerador se calla de golpe", "WHATSAPP", "TRANSICION_CARGA_RETENCION", "zumba_al_acelerar_calla_al_soltar", "NO_REPORTA", "", "SI", "NO", "", "L1 zumba al acelerar calla al soltar")
    agregar(CLASE_37, MACRO_TRANS, "L2", "Aullido agudo procedente del diferencial trasero en retención entre 70 km/h y 90 km/h; en neutro el ruido continúa proporcional al giro de las ruedas; juego en brida piñón de 1.5 mm.", "TALLER", "PRUEBA_ELEVADOR_RODAJE", "aullido_diferencial_retencion, juego_brida_pinon_1_5mm", "falla_rodamiento_rueda", "", "NO", "SI", keys[45], "L2 aullido diferencial retencion juego brida vs maza")
    agregar(CLASE_37, MACRO_TRANS, "L2", "Zumbido áspero y constante en la caja de cambios que no desaparece al girar a la izquierda o derecha en curvas; al acelerar en cualquier cambio zumba la corona.", "TALLER", "PRUEBA_CURVAS_DESCARTAR_MAZA", "zumbido_no_cambia_en_curvas, zumba_corona_caja", "falla_rodaje_rueda_maza", "", "NO", "SI", keys[45], "L2 zumbido no cambia en curvas vs maza")
    agregar(CLASE_37, MACRO_TRANS, "L3", "Inspección de grupo cónico diferencial con reloj comparador y azul de Prusia: holgura entre dientes (backlash) de corona y piñón de ataque en 0.42 mm (tolerancia nominal 0.13 mm a 0.18 mm); huella de contacto desplazada al talón por precarga de rodamientos cónicos de piñón vencida; precarga de giro en 0.2 Nm vs 1.8 Nm.", "TECNICO", "AZUL_PRUSIA_BACKLASH_DIFERENCIAL", "backlash_0_42mm_vs_0_15mm, precarga_pinon_0_2nm_vs_1_8nm", "falla_semieje_palier", "", "NO", "SI", keys[42], "L3 azul prusia backlash 0.42mm precarga 0.2 Nm")
    agregar(CLASE_37, MACRO_TRANS, "L3", "Estetoscopio electrónico de chasis fijado en carcasa de transmisión manual de 5 velocidades: rodamiento cónico de apoyo del diferencial emite pico acústico de 68 dB centrado en 450 Hz al rodar a 80 km/h; desmontaje de satélites y planetarios revela picaduras profundas por fatiga (spalling) en pistas de rodamientos cónicos.", "TECNICO", "ESTETOSCOPIO_CHASIS_FRECUENCIAS", "pico_68db_450hz_rodamiento_diferencial, spalling_pistas_conicas", "falla_rodaje_primario", "", "NO", "SI", CLASE_41, "L3 estetoscopio 68 dB 450Hz spalling pistas conicas")

    # --- CLASE 38: CVT / DSG sobrecalentamiento y solenoides ---
    agregar(CLASE_38, MACRO_TRANS, "L1", "La caja automática da un golpe fuertísimo al meter directa o reversa y se bloquea.", "COTIDIANO", "SELECCION_MARCHA", "golpe_fuerte_directa_reversa_bloqueo", "NO_REPORTA", "", "SI", "NO", "", "L1 golpe fuerte directa reversa")
    agregar(CLASE_38, MACRO_TRANS, "L1", "en subida se acelera el motor como loco pero la caja cvt patina y salio alerta de sobrecalentamiento", "WHATSAPP", "SUBIDA_AUTOPISTA_CVT", "cvt_patina_alerta_sobrecalentamiento", "NO_REPORTA", "", "SI", "NO", "", "L1 CVT patina alerta sobrecalentamiento")
    agregar(CLASE_38, MACRO_TRANS, "L2", "Transmisión CVT entra en modo de protección limitando velocidad a 40 km/h; código DTC P0700 y P0841 por presión de fluido primaria fuera de rango; viruta metálica fina en imanes de cárter.", "TALLER", "ESCANEO_CAJA_CVT", "dtc_p0700_p0841_cvt, viruta_metalica_imanes_carter", "falla_disco_embrague", "P0841", "NO", "SI", CLASE_34, "L2 CVT modo proteccion P0841 viruta imanes")
    agregar(CLASE_38, MACRO_TRANS, "L2", "Caja de doble embrague DSG de 7 marchas da tirones violentos en 1ra y 2da; mecatrónica pierde presión hidráulica; solenoide de embrague K1 con retardo de activación.", "TALLER", "INSPECCION_DSG_TIRONES", "dsg_tirones_1ra_2da, perdida_presion_mecatronica", "falla_caja_robotizada", "", "NO", "SI", CLASE_39, "L2 DSG tirones 1ra 2da solenoide K1 vs robotizada")
    agregar(CLASE_38, MACRO_TRANS, "L3", "Diagnóstico de unidad mecatrónica DSG DQ200: lectura de acumulador de presión hidráulica arroja ciclos de recarga de la bomba eléctrica cada 1.8 segundos por fisura en el bloque hidráulico de aluminio; presión nominal de 60 bar cae a 35 bar con código DTC P17BF (bomba hidráulica límite de protección).", "TECNICO", "PRESION_ACUMULADOR_DSG_DQ200", "fisura_bloque_aluminio_dq200, ciclo_bomba_1_8s, dtc_p17bf", "falla_embrague_dsg", "P17BF", "NO", "SI", CLASE_34, "L3 mecatronica DQ200 fisura acumulador P17BF")
    agregar(CLASE_38, MACRO_TRANS, "L3", "Monitoreo con escáner de transmisión CVT Nissan Jatco: solenoide de control de presión secundaria (Solenoide B) registra resistencia de 18.5 Ohmios (nominal 5.1 a 5.6 Ohmios a 20°C por recalentamiento de devanado); presión de sujeción de poleas cae a 0.8 MPa provocando deslizamiento de cinta metálica de empuje.", "TECNICO", "SOLENOIDE_PRESION_CVT_RESISTENCIA", "solenoide_b_18_5_ohmios_vs_5_3, caida_presion_poleas_0_8mpa", "falla_aceite_caja", "P0746", "NO", "SI", CLASE_36, "L3 solenoide B CVT 18.5 ohms presion poleas 0.8 MPa")

    # --- CLASE 39: Caja robotizada Dualogic / I-Motion / Easytronic ---
    agregar(CLASE_39, MACRO_TRANS, "L1", "Pongo la palanca en directa y la pantalla marca N titilando y suena una chicharra.", "COTIDIANO", "ARRANQUE_CABINA", "marca_n_titilando_chicharra_robotizada", "NO_REPORTA", "", "SI", "NO", "", "L1 marca N titila chicharra")
    agregar(CLASE_39, MACRO_TRANS, "L1", "el carro se quedo clavado en tercera marcha en medio de la avenida y no baja cambios", "WHATSAPP", "MARCHA_ATASCADA", "clavado_en_tercera_marcha_robotizada", "NO_REPORTA", "", "SI", "NO", "", "L1 clavado en 3ra marcha robotizada")
    agregar(CLASE_39, MACRO_TRANS, "L2", "En sistema Fiat Dualogic: la bomba eléctrica de la mecatrónica suena continua por más de 45 segundos al abrir la puerta del conductor; presión de sistema no supera 32 bar (mínimo 45 bar); acumulador de presión desinflado.", "TALLER", "INSPECCION_BOMBA_DUALOGIC", "bomba_dual_logic_45s_continua, presion_32bar_acumulador_vencido", "falla_bateria", "", "NO", "SI", keys[47], "L2 bomba Dualogic 45s presion 32 bar vs bateria")
    agregar(CLASE_39, MACRO_TRANS, "L2", "En VW I-Motion: mensaje de caja no disponible en tablero con código DTC P0882; potenciómetro de posición de selección de marchas con pista resistiva desgastada.", "TECNICO", "SCANNER_I_MOTION_POSICION", "caja_no_disponible_i_motion, potenciometro_seleccion_desgastado", "falla_dsg", "P0882", "NO", "SI", CLASE_38, "L2 I-Motion caja no disponible potenciometro P0882")
    agregar(CLASE_39, MACRO_TRANS, "L3", "Diagnóstico hidráulico de grupo robotizado Magneti Marelli Selespeed / Dualogic: prueba de estanqueidad estática acusa caída de presión de 50 bar a 28 bar en 12 segundos sin comandos de marcha activos; fuga interna masiva en electroválvula proporcional de acoplamiento de embrague EV0; líquido Tutela CS Speed degradado.", "TECNICO", "MANOMETRO_BANCO_DUALOGIC", "fuga_interna_ev0_dual_logic, caida_50_a_28bar_12s", "falla_bomba_hidraulica_caja", "P1810", "NO", "SI", CLASE_35, "L3 Dualogic fuga electrovalvula EV0 caida 50 a 28 bar")
    agregar(CLASE_39, MACRO_TRANS, "L3", "Verificación de actuador de embrague en Opel Easytronic: el módulo de control electrónico MTA registra DTC P1607 (error de control de posición de embrague); motor eléctrico paso a paso presenta escobillas de carbón gastadas y atascadas por carbonilla; el vástago del émbolo maestro no retrocede al tope inicial.", "TECNICO", "DESARME_MODULO_EASYTRONIC", "dtc_p1607_easytronic_posicion, escobillas_motor_mta_gastadas", "falla_embrague_mecanico", "P1607", "NO", "SI", CLASE_34, "L3 Easytronic P1607 escobillas motor MTA gastadas")

    # --- CLASE 40: Collarín de empuje / crapodina ---
    agregar(CLASE_40, MACRO_TRANS, "L1", "Suena un chillido agudo de rolinera cuando piso el embrague y al soltarlo desaparece.", "COTIDIANO", "APLICACION_EMBRAGUE", "chillido_rolinera_al_pisar_embrague", "NO_REPORTA", "", "SI", "NO", "", "L1 chillido al pisar embrague")
    agregar(CLASE_40, MACRO_TRANS, "L1", "hace un ruido de raspado feo en el pedal justo al apoyar el pie", "WHATSAPP", "CONTACTO_PEDAL", "raspado_al_apoyar_pie_embrague", "NO_REPORTA", "", "SI", "NO", "", "L1 raspado al apoyar pie embrague")
    agregar(CLASE_40, MACRO_TRANS, "L2", "Zumbido chirriante metálico que se manifiesta exclusivamente con el pedal de embrague presionado a fondo; en neutro con pedal libre hay silencio absoluto.", "TALLER", "PRUEBA_PEDAL_NEUTRO_FONDO", "zumbido_solo_con_pedal_a_fondo, silencio_en_neutro", "falla_rodaje_primario", "", "NO", "SI", CLASE_41, "L2 zumbido solo al pisar a fondo vs eje primario")
    agregar(CLASE_40, MACRO_TRANS, "L2", "Al pisar el embrague el pedal vibra bajo la suela del zapato; rodamiento de empuje con juego axial excesivo que roza torcido contra las lengüetas del diafragma.", "TALLER", "VIBRACION_PEDALERA_EMBRAGUE", "vibracion_suela_zapato_embrague, collarin_roza_torcido", "falla_disco_patinando", "", "NO", "SI", CLASE_34, "L2 vibracion suela collarin roza torcido")
    agregar(CLASE_40, MACRO_TRANS, "L3", "Inspección endoscópica por la horquilla de desembrague: pista del collarín de empuje totalmente seca de grasa con pistas picadas y bolas deformadas; lengüetas de la placa de diafragma del embrague presentan desgaste por fricción de 1.8 mm de profundidad (límite 0.5 mm); al girar a mano emite crujido seco.", "TECNICO", "BOROSCOPIO_VENTANA_CAMPANA", "collarin_sin_grasa_crujido, lenguetas_diafragma_gastadas_1_8mm", "falla_eje_primario", "", "NO", "SI", CLASE_41, "L3 boroscopio collarin seco lenguetas gastadas 1.8mm")
    agregar(CLASE_40, MACRO_TRANS, "L3", "Evaluación acústica con estetoscopio electrónico de taller: al oprimir el pedal de embrague el nivel sonoro en la carcasa de la campana sube de 42 dB a 76 dB con frecuencia predominante de 1200 Hz; se descarta rodamiento de eje primario ya que al pisar el pedal el primario se detiene por completo.", "TECNICO", "ESTETOSCOPIO_SONOMETRO_CAMPANA", "salto_sonoro_42_a_76db_al_pisar, primario_detenido_sin_ruido", "falla_rodamiento_primario", "", "NO", "SI", CLASE_41, "L3 sonometro 42 a 76 dB al pisar primario parado")

    # --- CLASE 41: Rodajes de transmisión manual / eje primario ---
    agregar(CLASE_41, MACRO_TRANS, "L1", "En neutro el motor suena como si tuviera piedras adentro y cuando piso el embrague se calla.", "COTIDIANO", "RALENTI_NEUTRO", "suena_piedras_neutro_calla_pisar_embrague", "NO_REPORTA", "", "SI", "NO", "", "L1 piedras en neutro calla pisar embrague")
    agregar(CLASE_41, MACRO_TRANS, "L1", "zumba la transmision parado en ralenti y al apretar el pedal de embrague desaparece", "WHATSAPP", "PARADA_RALENTI", "zumbido_ralenti_desaparece_pisar_embrague", "NO_REPORTA", "", "SI", "NO", "", "L1 zumbido ralenti desaparece pisar embrague")
    agregar(CLASE_41, MACRO_TRANS, "L2", "Ruido de cascabel y zumbido áspero en ralentí en punto muerto; al pisar el pedal de embrague el ruido desaparece por completo (inverso a la falla de collarín).", "TALLER", "TEST_COMPARATIVO_NEUTRO_EMBRAGUE", "ruido_en_neutro_desaparece_al_pisar, rodaje_directa", "falla_collarin_embrague", "", "NO", "SI", CLASE_40, "L2 ruido en neutro desaparece al pisar vs collarin")
    agregar(CLASE_41, MACRO_TRANS, "L2", "Zumbido constante en 1ra, 2da y 3ra marcha que disminuye notablemente en 4ta (marcha directa 1:1); rodamiento delantero del eje primario con pista picada.", "TALLER", "PRUEBA_CAMBIOS_MARCHA_DIRECTA", "zumbido_1ra_2da_3ra_baja_en_4ta, rodaje_primario_picado", "falla_diferencial_corona", "", "NO", "SI", CLASE_37, "L2 zumba en 1-2-3 baja en 4ta rodaje primario")
    agregar(CLASE_41, MACRO_TRANS, "L3", "Diagnóstico con acelerómetro piezoeléctrico en la carcasa frontal de la caja de cambios junto al retén de directa: nivel de vibración en aceleración rms de 4.8 m/s² a 800 RPM en neutro que colapsa a 0.2 m/s² al desembragar; desmontaje expone pista exterior de rodamiento de bolas de eje primario con fractura y picaduras de 0.6 mm.", "TECNICO", "ANALIZADOR_VIBRACION_RMS", "vibracion_4_8_a_0_2ms2_desembrague, pista_primario_picada", "falla_crapodina_embrague", "", "NO", "SI", CLASE_40, "L3 acelerometro 4.8 a 0.2 ms2 al desembragar primario")
    agregar(CLASE_41, MACRO_TRANS, "L3", "Desarme de transmisión manual: holgura radial del eje primario medida con reloj comparador en la punta estriada arroja 0.38 mm (límite máximo admisible 0.05 mm); jaula separadora de bolas de acero partida en dos pedazos dentro de la pista; engranajes y sincronizadores sin desgaste anómalo.", "TECNICO", "RELOJ_COMPARADOR_PUNTA_PRIMARIO", "holgura_radial_primario_0_38mm_vs_0_05, jaula_bolas_rota", "falla_aceite_caja", "", "NO", "SI", CLASE_36, "L3 holgura radial primario 0.38mm jaula de bolas rota")

    return casos
